### PR TITLE
Update global_det j-job, module files modified to work with ecflow workflow

### PR DESCRIPTION
**Pull request by lgannoaa**
GitHub #187 

Tested in development ecflow workflow. Result checked by team member.
Modified J-Job and module files.
Remove loading prod_envir module.
Fix DATA location assignment.
Fix cyc variable assignment solution.
Fix COMOUT assignment logic.
Remove unused pgmout statement.

- [Yes] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

## Pull Request Checklist ##

- [Yes] Complete the PR description above.
- [Yes] Ensure the PR title matches the feature branch name.
- [Yes]  Check that the ecf file has all the proper definitions of variables
- [Yes]  Check to see that the output directory structure is followed
- [Yes]  Be sure that you are not using MET utilities outside the METplus wrapper structure
- [Yes] After submitting the PR, select **Development** issue with the original issue number.

### CODE REVIEW

**Comment by malloryprow** [comment]
Thanks for your work on this Lin! I'm glad we have global_det ecflow ready!

**Comment by malloryprow** [comment]
Do the driver scripts need to be updated for renaming of module files? Not ecflow related but the change for the module file naming is in this PR.

For example, dev/drivers/scripts/global_det/prep/jevs_global_det_atmos_prep.sh is still loading 

```
module reset
source $HOMEevs/versions/run.ver
source $HOMEevs/modulefiles/global_det/global_det_prep.sh
```

but $HOMEevs/modulefiles/global_det/global_det_prep.sh is now $HOMEevs/modulefiles/global_det/prep.sh

**Comment by AliciaBentley-NOAA** [comment]
Hi Mallory,

When we spoke to Lin Gan, he said that it was fine if we kept the
modulefiles naming convention that everyone changed to:
modulefiles/global_det/global_det_prep.sh
Even though this convention uses $component twice, that's what Geoff wanted
and we're not going to ask everyone to change it again. Please keep the
script name global_det_prep.sh. Thanks! Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by malloryprow** [comment]
@lgannoaa Please see Alicia's comment

**Comment by lgannoaa** [comment]
@AliciaBentley-NOAA @malloryprow ,
I recall in the meeting we have agreed that the module will not need to have model name in the file name because it is already identified in the directory.
The driver is a one list change to this statement:
source $HOMEevs/modulefiles/global_det/global_det_prep.sh

**Comment by AliciaBentley-NOAA** [comment]
Hi Lin,

During our meeting, the EVS Project Managers were concerned about asking
developers to change the name of their modulefiles scripts for a second
time. I thought that you said that it was OK if we left the modulefile
names the way we already had them ($component_$step.sh) because it wasn't
against any EE2 policies. It was your personal preference to change them,
but not required. Perhaps I'm remembering this meeting incorrectly. I'll
let Perry, Shelley, and Logan chime in on what they remember. Thanks!

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
My recollection is the same as Alicia's, that we were all OK with leaving the modulefile names as they are now.  We should only change it only if it has to be changed to comply with EE2 policies.  

Perry

**Comment by LoganDawson-NOAA** [comment]
@lgannoaa @AliciaBentley-NOAA I recall the same as Alicia and Perry on this. With just a few weeks left until code delivery, we should really be limiting code changes to updates that are required to meet EE2 guidelines.

**Comment by lgannoaa** [comment]
Thank you everyone with your recommendation. I will modify the module approach on this PR to keep the model name included.

**Comment by lgannoaa** [comment]
This PR has been modified to include component with the module file name.

**Comment by malloryprow** [comment]
Thank you @lgannoaa!

**Comment by ShelleyMelchior-NOAA** [comment]
@lgannoaa , can you explain the removal of the loading of the prod_envir module in the modulefiles/ files?

Also, please update branch `evs-issue-187` with the auth EVS develop.

**Comment by lgannoaa** [comment]
Regarding the question of prod_envir, it is explained in a group chat.

**Comment by lgannoaa** [comment]
@ShelleyMelchior-NOAA merged to upstream.

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @lgannoaa , please merge w/ upstream again and I will get started on this PR today.

**Comment by lgannoaa** [comment]
@ShelleyMelchior-NOAA merged upstream.

**Comment by ShelleyMelchior-NOAA** [comment]
@malloryprow , prep processing for global_det atmos is underway.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_prep_00.o76855687`

**Comment by malloryprow** [comment]
Looks good!

**Comment by ShelleyMelchior-NOAA** [comment]
@malloryprow , I am also running stats and plots, specifically
`jevs_global_det_atmos_long_term_stats.sh` and 
`jevs_global_det_atmos_grid2grid_sea_ice_plots_31days.sh`. 
I chose long term stats b/c that job was edited by Lin. The plots job is complete; stats will be a bit longer.

logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_long_term_stats_00.o76856818`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2grid_sea_ice_plots_31days_00.o76858480`

**Comment by malloryprow** [comment]
Hmmm I don't see the changes for jevs_global_det_atmos_long_term_stats.sh in the PR. This won't run in production. This will take about 4 hours to run.

**Comment by lgannoaa** [comment]
I was been told at the time when I worked on this model that global_det atmos long_term_stats job was not ready. Therefore it was not tested. @malloryprow am I correct? Thanks

**Comment by malloryprow** [comment]
It is not that it is not ready, it is that it will not be run in production.

**Comment by lgannoaa** [comment]
Got it. Thanks
For any job that is not going to be implemented in production at this implementation, I will not work on it.

**Comment by ShelleyMelchior-NOAA** [comment]
Sorry for the bad test choice! I picked it b/c its J-job has a super minor adjustment in this PR:  `jobs/global_det/stats/JEVS_GLOBAL_DET_ATMOS_LONG_TERM_STATS`. Let me pick a smaller and better stats process to test.

**Comment by ShelleyMelchior-NOAA** [comment]
@lgannoaa  -- please merge this branch in your fork w/ upstream.

**Comment by ShelleyMelchior-NOAA** [comment]
> @malloryprow , I am also running stats and plots, specifically `jevs_global_det_atmos_long_term_stats.sh` and `jevs_global_det_atmos_grid2grid_sea_ice_plots_31days.sh`. I chose long term stats b/c that job was edited by Lin. The plots job is complete; stats will be a bit longer.
> 
> logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_long_term_stats_00.o76856818` `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2grid_sea_ice_plots_31days_00.o76858480`

@malloryprow -- did you get a chance to look at the plots processing? If so, was that OK? Or should I run it again?

**Comment by malloryprow** [comment]
(On Cactus) I see /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/global_det/atmos.20230814/evs.plots.global_det.atmos.grid2grid_sea_ice.last31days.v202
30814.tar. Tar file was created. It didn't run on any data (see starting on line 1424 of the log), but I'm not too concerned that it didn't? Plots would all just be empty. I'm fine with it.

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks @malloryprow , I am fine w/ that, too. The functionality is in place and it performed as expected, even in the absence of stats data.

I am running a different process to test stats: `jevs_global_det_atmos_metfra_grid2grid_stats.sh`
Please review:
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_metfra_grid2grid_stats_00.o89896970`
At the moment it is still running ... and it looks like it didn't finish b/c of wall time exceedance. I chose that one b/c it is only 10 mins. I am assuming under normal conditions 10 mins is enough. I can re-run with it set to 30 minutes if you would like.

**Comment by malloryprow** [comment]
Cool, let me know when it is done and I'll check it out. Should be a quick one.

**Comment by ShelleyMelchior-NOAA** [comment]
> Cool, let me know when it is done and I'll check it out. Should be a quick one.

See my previous comment ... I added to it after my initial update.

**Comment by malloryprow** [comment]
Sure bump it up to 30 min!

**Comment by ShelleyMelchior-NOAA** [comment]
Ok, the re-run is completed ... and much more quickly, b/c it effectively exercised the restart functionality! Bonus!
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_metfra_gririd_stats_00.o89902123`

**Comment by malloryprow** [comment]
/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/global_det/metfra.20230815/./evs.stats.metfra.atmos.grid2grid.v20230815.stat looks good!

**Comment by ShelleyMelchior-NOAA** [comment]
Great! @lgannoaa I can merge this PR once the branch is updated w/ upstream.

**Comment by lgannoaa** [comment]
Merged with upstream.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The global_det software tests as expected for spot checks. This PR is approved for merge.

**Pull request merged**
