### PR TITLE
Bugfix/cam ee2 rev4

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

All stats jobs were run to completion.  All affected jobs completed cleanly, output files appear normal, and the following EE2 review notes have been addressed successfully:

> Please review all EVS jobs where implement the RESTART capability for the following EE2 issue discovered:
> (1) Review dead code: VERIF_TYPE == 'mping' session in $HOMEevs/ush/cam/cam_stats_grid2obs_create_job_script.py

All references to "mping" were removed from everywhere in EVS (cam and mesoscale)

> (2) Change statement cp -rpv to use cpreq as needed to be full comply with NCO implementation standard.

"cp -rpv" has been used in the cam component to copy restart files from $DATA to the restart directory.  All such instances were replaced with "cpreq -rpv".

> (3) Ensure dynamically generated job scripts (poe scripts) in $DATA are not removed if KEEPDATA=YES. Unconditional remove those file disable ability for NCO to debug failed job.

No such incidents (removal of files and directories in $DATA) occur in the cam component.  However, $DATA contained empty subdirectories that resembled other subdirectories that are used to store poe scripts.  The unused subdirectories have been removed.

> (4) The following statement removes the directory in production COM location. NCO implementation standards prohibit delete directory/file from COM location.
>     find ${COMevs}/stats/cam/atmos.20231203/hireswarw/grid2obs/restart/c12 -type d -empty -delete

During the stats step of the cam component of EVS, subdirectories that store METplus output are written in $DATA, then METplus is run, then METplus output are copied to a similarly structured restart directory.  More directories are written than are required, resulting in empty directories in both $DATA and the restart directory.  To prevent empty directories from getting into the restart directory (without deleting them at the end of the job), $DATA subdirectories are no longer written if they may not be populated, and instead, their contents, if any, are stored in a single directory that is always populated.  I tested this fix with the relevant jobs (all cam-det stats jobs) and found no empty subdirectories in the restart directories.

### Other changes included in this PR:

- several code segments in mesoscale/sref/stats jobs that cat log files to the stdout file were fixed to prevent "No such file..." warnings
- two duplicate cat'ing sections were removed from an ush file used by mesoscale/sref/stats, at the recommendation of the developer
- template for input files to cam spatial maps plotting scripts was adjusted to reflect file/directory name changes that address (4) in the review quoted above
- duplicate function definitions were removed from `ush/cam/cam_util.py`

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Same process as in the recent cam PRs:
### (1) Set up jobs 
•	symlink the EVS_fix directory locally as "fix"
•	In all driver scripts, point all exports of "HOMEevs" to your EVS test directory
•	In all driver scripts, change COMIN to the parallel directory (`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`)
•	Optional: In all stats drivers scripts, change "MAILTO" to point to your email address
### (2) Test Jobs
Use the following …
•	…to submit jevs_cam_*_precip_stats: `qsub –v vhr=19,VDATE=$(date -d "-3 days" +"%Y%m%d")`
•	…to submit everything else: `qsub –v vhr=00 `
(_Note change to "vhr" in qsub commands_)

From your EVS testing directory, the following scripts should be run using the set up in step (1):
```
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_snowfall_stats.sh
```
```
dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_sref_cnv_stats.sh
dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_sref_grid2obs_stats.sh
dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_sref_precip_stats.sh
```
```
dev/drivers/scripts/plots/cam/jevs_cam_precip_plots.sh
```
_[Total: 0 prep jobs, 28 stats jobs, 1 plots job]_

Stats jobs will be checked for: 
✔️ successful completion (no "FATAL ERROR", "error", "Error", "No such file", "argument expected", "Cgroup", etc.) 
✔️ normal output files
✔️ restart directories containing 0 empty subdirectories.

- [x] Has the code been checked to ensure that no errors occur during the execution? **YES**

- [x] Do these updates/additions include sufficient testing updates? **YES**

- [x] Please complete this pull request review by **12/08/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA The following message is from Binbin about the "No such file or directory" issue. I'm not sure if it'll change anything here, or if what you've already done will work too:

@PerryShafran-NOAA ,

The cat of all log files for precip stats is located between lines 131~
133 in ush/mesoscale/evs_sref_precip.sh
The cat of all log files for grid2obs stats is located between lines
95~97 in ush/mesoscale/evs_sref_grid2obs.sh
So the cat processes in [evs_prepare_sref.sh](https://github.com/NOAA-EMC/EVS/blob/develop/ush/mesoscale/evs_prepare_sref.sh)
are duplicated.

Binbin

**Comment by MarcelCaron-NOAA** [comment]
@AliciaBentley-NOAA Okay, I addressed all cat'ing sections I could find for sref, but did not delete any of them.  In that case, I will delete all of the cat'ing sections in evs_prepare_sref.sh and include the change in this PR.

**Comment by AliciaBentley-NOAA** [comment]
Thank you, @MarcelCaron-NOAA! I think it'll be better to have both PRs match! Thank you!
Here is Binbin's, for reference: https://github.com/NOAA-EMC/EVS/pull/373

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA  - I am going to work on the cam sections of this PR.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA I got a lot of missing file emails, just so you know! These might be expected, but here are some examples:

Warning: No HiRes Window FV3 Forecast data were available for valid date 20231202, cycle 19Z, and f059, f060.
Missing files are:
/lfs/h1/ops/prod/com/hiresw/v8.1/hiresw.20231128/hiresw.t18z.fv3_5km.f59.pr.grib2
/lfs/h1/ops/prod/com/hiresw/v8.1/hiresw.20231128/hiresw.t18z.fv3_5km.f60.pr.grib2
Job ID: jevs_cam_hireswfv3_precip_stats.94987662.cbqs01


Warning: No HiRes Window ARW2 Forecast data were available for valid date 20231202, cycle 19Z, and f039, f040, f041, f042, f043, f044, f045, f046, f047, f048.
Missing files are:
/lfs/h1/ops/prod/com/hiresw/v8.1/hiresw.20231129/hiresw.t12z.arw_5km.f39.conusmem2.grib2
/lfs/h1/ops/prod/com/hiresw/v8.1/hiresw.20231129/hiresw.t12z.arw_5km.f40.conusmem2.grib2
/lfs/h1/ops/prod/com/hiresw/v8.1/hiresw.20231129/hiresw.t12z.arw_5km.f41.conusmem2.grib2
/lfs/h1/ops/prod/com/hiresw/v8.1/hiresw.20231129/hiresw.t12z.arw_5km.f42.conusmem2.grib2
/lfs/h1/ops/prod/com/hiresw/v8.1/hiresw.20231129/hiresw.t12z.arw_5km.f43.conusmem2.grib2
/lfs/h1/ops/prod/com/hiresw/v8.1/hiresw.20231129/hiresw.t12z.arw_5km.f44.conusmem2.grib2
/lfs/h1/ops/prod/com/hiresw/v8.1/hiresw.20231129/hiresw.t12z.arw_5km.f45.conusmem2.grib2
/lfs/h1/ops/prod/com/hiresw/v8.1/hiresw.20231129/hiresw.t12z.arw_5km.f46.conusmem2.grib2
/lfs/h1/ops/prod/com/hiresw/v8.1/hiresw.20231129/hiresw.t12z.arw_5km.f47.conusmem2.grib2
/lfs/h1/ops/prod/com/hiresw/v8.1/hiresw.20231129/hiresw.t12z.arw_5km.f48.conusmem2.grib2
Job ID: jevs_cam_hireswarwmem2_precip_stats.94987651.cbqs01

CC @MarcelCaron-NOAA

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA @MarcelCaron-NOAA

Also these missing MRMS emails, which seem less expected:
Warning: No MRMS data were available for valid date 20231202 at 05Z.
Missing files are:
/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/cam/mrms.20231201/mrms.t10z.01h.ak.gb2
Job ID: jevs_cam_hrrr_precip_stats.94987670.cbqs01

**Comment by RoshanShrestha-NOAA** [comment]
Hi @MarcelCaron-NOAA, mesoscale restart scripts have two minor edits (i.e. change cp to cpreq). 
ush/mesoscale/mesoscale_production_restart.py
ush/mesoscale/mesoscale_stats_g2o_production_restart.sh
Will you please include these changes in this PR?

https://github.com/NOAA-EMC/EVS/compare/develop...RoshanShrestha-NOAA:EVS:bugfix/test_meso_restart

Thanks

**Comment by MarcelCaron-NOAA** [comment]
@AliciaBentley-NOAA @PerryShafran-NOAA The missing forecasts are expected; we are running the jobs a day late so that obs files are fully available, so some forecasts have aged out.

The missing mrms files are not typical but can happen some days.  Let me look into that.

**Comment by MarcelCaron-NOAA** [comment]
@RoshanShrestha-NOAA Sure, I'll make those changes now.

**Comment by MarcelCaron-NOAA** [comment]
> @AliciaBentley-NOAA @PerryShafran-NOAA The missing forecasts are expected; we are running the jobs a day late so that obs files are fully available, so some forecasts have aged out.
> 
> The missing mrms files are not typical but can happen some days. Let me look into that.

The source mrms files have aged out, but it does look like a single file was missing when cam/prep copied files over from dcom.  All of the others are available:
/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/cam/mrms.202312*/mrms.t\*z.01h.*.gb2

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA A few jobs continue to run, but most are completed.

Please check out all the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr376test/EVS/dev/drivers/scripts/stats/cam

And then check out all the stats directories here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam

Especially pay attention to the items that are being addressed in this PR, including and especially empty restart subdirectories.  

@AliciaBentley-NOAA @ShelleyMelchior-NOAA

**Comment by MarcelCaron-NOAA** [comment]
Hi @PerryShafran-NOAA:

✔️ All of the grid2obs, radar, severe, and snowfall stats jobs completed successfully (I checked for keywords listed in the PR description) and output are comparable to the parallel
✔️ All precip jobs completed as expected and output are comparable to the parallel.  A note that they contained missing forecast errors and obs errors, but I checked these and they are expected, as described above. 

I used the following command to check for empty files in restart directories:
```
find /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/atmos.202312*/*/*/restart -type d -empty | wc -l
0
```

✔️ No empty files in restart directories.

There is one empty directory farther up:
```
find /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/atmos.202312* -type d -empty 
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/atmos.20231203/hireswfv3/precip
```

I believe this is from an errant jevs_cam_hireswfv3_precip_stats test job, but maybe you can confirm.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Yes, in going through the qsubs of all the files, I went too far and submitted a precip job that I shouldn't have, and killed the job as soon as I could.  Thus, if this is the only empty directory, we can probably ignore that.  If you think we should delete and run a clean job again, just to make sure, I can do that.  

Also, check to see if the plot job is still running or if it's done.  I submitted that a bit ago.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Please sync your fork.  I think that would resolve the conflict we see.

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA okay, I figured.  I don't think it needs to be re-run, because the correct precip runs used a different valid date and their output files are located in the 20231202 directory.  That directory has no empty files:
```
find /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/atmos.20231202 -type d -empty | wc -l
0
```

🚩 jevs_cam_precip_plots failed because it was not given a value for vhr.  Using "qsub -v vhr=00 ..." to submit should fix that.

**Comment by PerryShafran-NOAA** [comment]
Oh, I forgot that plots also needed a vhr=00.  Let me fix.

**Comment by ShelleyMelchior-NOAA** [comment]
> Oh, I forgot that plots also needed a vhr=00. Let me fix.

Tidbit: Perry, my check for this is to always grep on vhr in the driver to see if it set to an explicit value or set to an incoming value. If it is already set to a value, then you know you don't need to bring it in in the qsub command. I started making that a habit before constructing qsub commands when working on PRs for the various regional components.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Can you answer what is being addressed in the cam precip plot test?

**Comment by MarcelCaron-NOAA** [comment]
Only a minor edit was made to a file in that job, however I thought it would be a good idea to check that the job completed cleanly.

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA Perry is asking because not having the PR in the emc.vpppg parallel is preventing Lin from doing our final EE2 review. Can you please let us know as soon as the job passes the point where you can see that your edit worked? Thanks.

**Comment by MarcelCaron-NOAA** [comment]
> @MarcelCaron-NOAA Perry is asking because not having the PR in the emc.vpppg parallel is preventing Lin from doing our final EE2 review. Can you please let us know as soon as the job passes the point where you can see that your edit worked? Thanks.

Ah I see.  In that case, let me check now.  I only need to know if the spatial maps job cards are being written correctly.  I will update shortly

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA @PerryShafran-NOAA I think that this PR looks really good. Please triple check the cat'ing changes made in this PR. That shouldn't conflict with Binbin's recent PR and we should still get the results that we want. Thanks.

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA @AliciaBentley-NOAA  jevs_cam_precip_plots looks good to me!  I'm okay with calling it.

No concerns from me about the cat'ing changes.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA I did not run any of the sref jobs, btw.  I'm starting those now so you can look at those job logs and see if the cat'ing was done properly, as well as cpreq.

**Comment by PerryShafran-NOAA** [comment]
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr376test/EVS/dev/drivers/scripts/stats/mesoscale for the .o files
 
 /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/mesoscale for the stats files.

**Comment by MarcelCaron-NOAA** [comment]
✔️ jevs_mesoscale_sref_cnv_stats completed and cat'ing worked well

the other two jobs are still running. (est. 40m and 1h30m from now until one and the other are complete)

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA grid2obs appears to be done.

**Comment by MarcelCaron-NOAA** [comment]
✔️ jevs_mesoscale_sref_grid2obs_stats completed successfully and cat'ing looks good!

**Comment by PerryShafran-NOAA** [comment]
I think the precip job is complete, would you take a look and assess?

**Comment by MarcelCaron-NOAA** [comment]
Yes let me check now!

**Comment by MarcelCaron-NOAA** [comment]
Also @PerryShafran-NOAA: I checked the output files for jevs_cam_*_radar_stats in the parallel because they have been smaller than I expect them to be.  It turns out a small fix to the radar stats jobs is needed.   The radar stats jobs are quick jobs, and I only need to run one job to test it ...  do you mind redoing jevs_cam_hireswarw_radar_stats with the fix I just pushed?

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA I'm sorry, I don't see a push?

**Comment by PerryShafran-NOAA** [comment]
Ah there it is.

**Comment by PerryShafran-NOAA** [comment]
The job is underway.  See /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr376test/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_radar_stats.o95014484

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA That job is already done!

**Comment by PerryShafran-NOAA** [comment]
Oops, hold please, forgot the vhr=00

**Comment by PerryShafran-NOAA** [comment]
Job is now jevs_cam_hireswarw_radar_stats.o95014840

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Job is done; please look.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA I see you made another update.  Would you like me to run again?

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA New job log would be jevs_cam_hireswarw_radar_stats.o95015210

**Comment by MarcelCaron-NOAA** [comment]
Yes, thanks @PerryShafran-NOAA 
✔️ jevs_mesoscale_sref_precip_stats completed successfully and cat'ing looks good!
🚩 jevs_cam_hireswarw_radar_stats almost finished successfully but failed at the end.  The update should make it work!

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Job is complete, please look at updated log file for the hireswarw radar stats.

**Comment by MarcelCaron-NOAA** [comment]
Sorry Perry, it seems a previous job interfered with this one.  Do you mind doing the following and running the same job one more time?
`rm /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/atmos.20231204/hireswarw/radar`

Should only take a couple minutes to run again

**Comment by PerryShafran-NOAA** [comment]
Yup, job is underway once again.  Job log is jevs_cam_hireswarw_radar_stats.o95015943

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Job is complete.

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA It worked!   Thanks.

**Comment by PerryShafran-NOAA** [comment]
Thanks, Marcel!  We just approved another PR, so please do another sync fork.

**Comment by MarcelCaron-NOAA** [comment]
Okay, should be good now

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
