### PR TITLE
Bugfix/met ver parse

### PR DESCRIPTION
**Pull request by ShelleyMelchior-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- Ran sref plotting drivers for cape and cloud to make sure MET_VERSION was set correctly.
- Checked cape and cloud tar files to make sure they match emc.vpppg.
- NOTE: ecf changes cannot be tested, but are included in this PR per NCO SPA request.
- NOTE: dev driver changes were previously tested offline by Perry. There is no impact as this is a placeholder whose setting has no impact yet.
- NOTE: the wafs plots driver was updated to use place=shared. That driver is in develop. Take care to not include this file in para.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- Run one plotting driver for the following components: cam-href, mesoscale-sref, narre, global_ens. One driver of your choice is sufficient since all plotting processes for the listed components use the changed ush scripts.
- Minimally, check the log file to make sure MET_VERSION is set correctly.
- If you allow the jobs to run to completion, just make sure the resultant tar files match what is in emc.vpppg for the same VDATE.
- Run global_ens_wave_grid2obs_plots to make sure the sfcshp mkdir error is removed.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA I have run plots for each of the ensemble components, once today and once yesterday.  You can take a look at various .o files by looking at the directories cam, mesoscale, narre, and global_ens under here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr393test/EVS/dev/drivers/scripts/plots

Plot tarballs can be found here:

/lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots (look under cam, mesoscale, narre, and global_ens)

I haven't personally taken a look at any of these items yet, but I am presenting it to you in case you get a chance to log on and look.  I will probably take a look myself to look at these issues and report back findings.

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks, Perry! I looked at the log files and tar listings for cam, mesoscale, narre, and global_ens. 
✔️ The MET_VERSION is appropriately set.
✔️ The resulting tar files also match nicely w/ emc.vpppg.

**cam**
```
[dlogin07 /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr393test/EVS/dev/drivers/scripts/plots/cam]$ grep MET_VERSION= jevs_cam_href_snowfall_past31days_plots.*
jevs_cam_href_snowfall_past31days_plots.o121954657:++++ MET_VERSION=11.0.2
jevs_cam_href_snowfall_past31days_plots.o121954657:0.017 + MET_VERSION=11.0
```
```
[dlogin07 /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/cam/atmos.20231220]$ ll
total 7940
-rw-r--r-- 1 perry.shafran emc 8130560 Dec 22 15:57 evs.plots.href.snowfall.past31days.v20231220.tar
[dlogin07 /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/cam/atmos.20231220]$ ll /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/cam/atmos.20231220/evs.plots.href.snowfall.past31days.v20231220.tar 
-rw-r--r-- 1 emc.vpppg emc 8130560 Dec 22 12:46 /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/cam/atmos.20231220/evs.plots.href.snowfall.past31days.v20231220.tar
```
**mesoscale**
```
[dlogin07 /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr393test/EVS/dev/drivers/scripts/plots/mesoscale]$ grep MET_VERSION= jevs_mesoscale_sref_precip_past90days_plots.*
jevs_mesoscale_sref_precip_past90days_plots.o121954698:++++ MET_VERSION=11.0.2
jevs_mesoscale_sref_precip_past90days_plots.o121954698:0.080 + MET_VERSION=11.0
```
```
[dlogin07 /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/mesoscale/atmos.20231220]$ ll
total 27440
-rw-r--r-- 1 perry.shafran emc 28098560 Dec 22 16:01 evs.plots.sref.precip.past90days.v20231220.tar
[dlogin07 /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/mesoscale/atmos.20231220]$ ll /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/mesoscale/atmos.20231220/evs.plots.sref.precip.past90days.v20231220.tar 
-rw-r--r-- 1 emc.vpppg emc 28098560 Dec 22 12:35 /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/mesoscale/atmos.20231220/evs.plots.sref.precip.past90days.v20231220.tar
```
**narre**
```
[dlogin07 /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr393test/EVS/dev/drivers/scripts/plots/narre]$ grep  MET_VERSION= jevs_narre_past31days_plots.*
jevs_narre_past31days_plots.o121869586:+ export MET_VERSION=11.0
jevs_narre_past31days_plots.o121869586:+ MET_VERSION=11.0
```
```
[dlogin07 /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/narre/atmos.20231221]$ ll
total 3112
-rw-r--r-- 1 perry.shafran emc 3184640 Dec 22 16:04 evs.plots.narre.grid2obs.last31days.v20231221.tar
[dlogin07 /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/narre/atmos.20231221]$ ll /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/narre/atmos.20231221/evs.plots.narre.grid2obs.last31days.v20231221.tar 
-rw-r--r-- 1 emc.vpppg emc 3184640 Dec 22 10:37 /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/narre/atmos.20231221/evs.plots.narre.grid2obs.last31days.v20231221.tar
```
**global_ens**
```
[dlogin07 /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr393test/EVS/dev/drivers/scripts/plots/global_ens]$ grep MET_VERSION= jevs_global_ens_atmos_gefs_profile4_past31days_plots.*
jevs_global_ens_atmos_gefs_profile4_past31days_plots.o121954716:++++ MET_VERSION=11.0.2
jevs_global_ens_atmos_gefs_profile4_past31days_plots.o121954716:+ MET_VERSION=11.0
```
```
[dlogin07 /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_ens/atmos.20231220]$ ll
total 601656
-rw-r--r-- 1 perry.shafran emc 616079360 Dec 22 16:07 evs.plots.global_ens.atmos.gefs.profile4.past31days.v20231220.tar
[dlogin07 /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_ens/atmos.20231220]$ ll /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/global_ens/atmos.20231220/evs.plots.global_ens.atmos.gefs.profile4.past31days.v20231220.tar 
-rw-r--r-- 1 emc.vpppg emc 616079360 Dec 22 13:39 /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/global_ens/atmos.20231220/evs.plots.global_ens.atmos.gefs.profile4.past31days.v20231220.tar
```

**Comment by ShelleyMelchior-NOAA** [comment]
Perry, can you please run this bullet from the test instructions?

- Run global_ens_wave_grid2obs_plots to make sure the sfcshp mkdir error is removed.

**Comment by PerryShafran-NOAA** [comment]
Right, I was going to run that after all the other items have been confirmed.

**Comment by ShelleyMelchior-NOAA** [comment]
> Right, I was going to run that after all the other items have been confirmed.

I confirm the other items are addressed and tests show expected results.

**Comment by PerryShafran-NOAA** [comment]
The global_ens wave plot job is complete.

See the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr393test/EVS/dev/drivers/scripts/plots/global_ens/jevs_global_ens_wave_grid2obs_plots.o122281800

and the plot tarballs here:

/lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_ens/wave.20231225

**Comment by ShelleyMelchior-NOAA** [comment]
Excellent. The log file appropriately handles the creation of the sfcshp subdir in $DATA.
```
+ 0 + cd /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_global_ens_wave_grid2obs_plots.12228180
0.dbqs01+ 0 + mkdir -p /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_global_ens_wave_grid2obs_plots.12
2281800.dbqs01/sfcshp
+ 0 + touch plot_all_gefs_wave_g2o_plots.sh
```
Also, the resultant tar files match the emc.vpppg parallel.
```
[dlogin07 /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_ens/wave.20231225]$ ll
total 343792
-rw-r--r-- 1 perry.shafran emc 161679360 Dec 26 13:25 evs.plots.global_ens.wave.grid2obs.last31days.v20231225.tar
-rw-r--r-- 1 perry.shafran emc 190361600 Dec 26 13:25 evs.plots.global_ens.wave.grid2obs.last90days.v20231225.tar
[dlogin07 /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_ens/wave.20231225]$ ll /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/global_ens/wave.20231225                                                   
total 343792
-rw-r--r-- 1 emc.vpppg emc 161679360 Dec 26 11:04 evs.plots.global_ens.wave.grid2obs.last31days.v20231225.tar
-rw-r--r-- 1 emc.vpppg emc 190361600 Dec 26 11:04 evs.plots.global_ens.wave.grid2obs.last90days.v20231225.tar
```

**Comment by ShelleyMelchior-NOAA** [comment]
I think this PR is ready for merge into develop. It has my green light.

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA do we need a few other tests of the place=shared stuff that was placed in the dev drivers?

**Comment by ShelleyMelchior-NOAA** [comment]
You can if you'd like, but I do not think they are necessary.

Just a reminder about the wafs plots driver that was updated in this PR, to not let it get into the para branch.

**Comment by PerryShafran-NOAA** [comment]
OK then, if you don't think it is necessary, I'll just go ahead and merge.

**Review by PerryShafran-NOAA — APPROVED** [review]
Changes work as expected.  Merging.

**Pull request merged**
