### PR TITLE
Adding a new file to sorc/ to build the symbolic link for FIXevs.

### PR DESCRIPTION
**Pull request by ShelleyMelchior-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

Created sorc/build-fix-slink.sh for NCO SPA to build the symbolic link for $FIXevs.
Tested from my $HOMEevs/sorc. Creates $HOMEevs/fix.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Clone my repository and checkout `feature/build-fix-slink`.
cd to EVS/sorc
run build-fix-slink.sh --> `./build-fix-slink.sh`
Should create $HOMEevs/fix linking to `/lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix`
```
$ ls -l ../fix
lrwxrwxrwx 1 shelley.melchior vpppg 56 Sep 28 17:39 ../fix -> /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix
```

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
I am starting work on this PR.

**Comment by PerryShafran-NOAA** [comment]
This seemed to work.  After I ran the script, I saw the following:

```
199 (clogin06) /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr267test/EVS > ls -l
total 40
drwxr-sr-x  3 perry.shafran vpppg 4096 Sep 28 20:16 dev
drwxr-sr-x  5 perry.shafran vpppg 4096 Sep 28 20:16 ecf
lrwxrwxrwx  1 perry.shafran vpppg   56 Sep 28 20:19 fix -> /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix
drwxr-sr-x 18 perry.shafran vpppg 4096 Sep 28 20:16 jobs
drwxr-sr-x 14 perry.shafran vpppg 4096 Sep 28 20:16 modulefiles
drwxr-sr-x  4 perry.shafran vpppg 4096 Sep 28 20:16 parm
-rwxr-xr-x  1 perry.shafran vpppg   91 Sep 28 20:16 README.md
drwxr-sr-x 18 perry.shafran vpppg 4096 Sep 28 20:16 scripts
drwxr-sr-x  8 perry.shafran vpppg 4096 Sep 28 20:17 sorc
drwxr-sr-x 18 perry.shafran vpppg 4096 Sep 28 20:16 ush
drwxr-sr-x  2 perry.shafran vpppg 4096 Sep 28 20:16 versions
```

Is there more I need to do to test this?

**Comment by PerryShafran-NOAA** [comment]
Also when I ran it a second time, I got this (which is also what you expected I think)

```
203 (clogin06) /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr267test/EVS/sorc > !sh
sh build-fix-link.sh
symbolic link for FIXevs previously created
lrwxrwxrwx 1 perry.shafran vpppg 56 Sep 28 20:19 ../fix -> /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix
204 (clogin06) /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr267test/EVS/sorc
```

**Comment by ShelleyMelchior-NOAA** [comment]
Great! Yes, I wanted to make sure there was behavior for all cases that could be trapped as non-error. I think the testing works as intended. I am satisfied w/ merging this PR.

**Comment by PerryShafran-NOAA** [comment]
No testing of any components needs to be done?

**Comment by ShelleyMelchior-NOAA** [comment]
I don't think it is necessary. If the fix dir is there then everything should run as needed as long as FIXevs is defined as HOMEevs/fix in all of the drivers, which they all should be at this stage.

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by PerryShafran-NOAA** [comment]
Approved for merge.

**Pull request merged**
