### PR TITLE
feature/nfcens_wave

### PR DESCRIPTION
**Pull request by DeannaSpindler-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [x] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [x] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR description above.
- [x] Ensure the PR title matches the feature branch name.
- [x] Check the following:
- [x]  Instructions provided on how to run
- [x]  Developer's name is replaced by ${user} where necessary throughout the code
- [x]  Check that the ecf file has all the proper definitions of variables
- [x]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [x]  Check to see that the output directory structure is followed
- [x]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,

This code has been running on my cron since the 19th of November.  I've shared sample plots with Alicia, and since it's basically the same as the global_ens and global_det she has approved the PR.

One thing: make sure that export nfcens_ver=v1.3 is in run.ver.

To run the prep step, make sure to modify the OUTPUTROOT directory under the "developers directories" in
ecf/nfcens/prep/jevs_nfcens_wave_grid2obs_prep.ecf
and to point COMIN to my OUTPUTROOT='/lfs/h2/emc/vpppg/noscrub/deanna.spindler/EVS_stats/evs/v1.0'
because the prep jobs will need this to access the archive.
Then:
qsub jevs_nfcens_wave_grid2obs_prep.ecf
The work directory will be under: /lfs/h2/emc/stmp/$USER/evs_output
and is named jevs_nfcens_wave_g2o_prep.{qsubID}
The run will make ${OUTPUTROOT}/evs/v1.0/prep/nfcens/wave.YYYYMMDD/nfcens/grid2obs
where you will find 5 NetCDF files and 82 grib2 files per day.

To run the stats step, also change the OUTPUTROOT (same as the one above) in
ecf/nfcens/stats/jevs_nfcens_wave_grid2obs_stats.ecf
then
qsub jevs_nfcens_wave_grid2obs_stats.ecf
The work directory will be under the same /lfs/h2/emc/stmp/$USER/evs_output
but this time is named jevs_nfcens_wave_g2o_stats.{qsubID}
This run will make ${OUTPUTROOT}/evs/v1.0/stats/nfcens/wave.YYYYMMDD/nfcens/grid2obs
where you will find 42 small stat files: point_stat_fcstNFCENS_obsGDAS_climoERA5_*.stat
and
${OUTPUTROOT}/evs/v1.0/stats/nfcens/nfcens.YYYYMMDD/evs.stats.nfcens.wave.grid2obs.vYYYYMMDD.stat

Then it's on to the plots.  Same as usual, change the OUTPUTROOT (same as the one above) in
ecf/nfcens/plots/jevs_nfcens_wave_grid2obs_plots.ecf
then
qsub jevs_nfcens_wave_grid2obs_plots.ecf
The work directory will be under the same /lfs/h2/emc/stmp/$USER/evs_output
but this time is named jevs_nfcens_wave_g2o_plots.{qsubID}
This run will make ${OUTPUTROOT}/evs/v1.0/plots/nfcens/nfcens.YYYYMMDD
where you will find the two tar files:
evs.plots.nfcens.wave.grid2obs.last31days.vYYYYMMDD.tar
and
evs.plots.nfcens.wave.grid2obs.last90days.vYYYYMMDD.tar

Let me know if you have any questions,
Deanna

**Comment by PerryShafran-NOAA** [comment]
Beginning work on this one now.  

Perry

**Comment by DeannaSpindler-NOAA** [comment]
I just checked, and this one has in the stats:
##export HPC_OPT=/apps/ops/para/libs

It has been running fine for weeks now - do we want to leave it as is?

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by DeannaSpindler-NOAA** [comment]
Take that back.. the GitHub version has:
##export HPC_OPT=/apps/ops/para/libs
but the code that I am running on cron has:
export HPC_OPT=/apps/ops/prod/libs

I will update the repo now.

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
I would recommend uncommenting it out and using the prod version.

Also, I had to add this line to the run.ver file - please check to see if it is in your working copy:

`export nfcens_ver=v1.3`

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Yes, that is the version in my run.ver file.
I already uploaded the change to use export HPC_OPT=/apps/ops/prod/libs
to all steps (prep, stats, plot).

You'll need the archive for this one also.

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
Hello, Deanna,

I have run both the prep and the stats steps.  Please take a look at the results here:

for prep:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_stats/evs/v1.0/prep/nfcens/wave.20221221
for stats:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_stats/evs/v1.0/stats/nfcens/nfcens.20221221

I'll also do the plots step.

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,

The prep files check out identical to mine, but the stat file is different:
yours only has 800 lines, mine has 884 lines.
I'm trying to see what happened..

Best,
Deanna

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,

Does your archive have the data for 20221220:

   -

   gribs/HTSGW_mean.20221220.t12z.f024.grib2
   -

   gribs/HTSGW_mean.20221220.t12z.f012.grib2
   -

   gribs/HTSGW_mean.20221220.t00z.f036.grib2
   -

   gribs/HTSGW_mean.20221220.t00z.f024.grib2


It's missing these in your workdir/gribs, and as a result is not
calculating the stats for the 12 and 24 hr fcsts.

Best,
Deanna

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
Ah, no it does not.  I think the reason is that my copy of run.ver didn't seem to have the proper version of wgrib2 in it for some reason.  I put that into the run.ver today, but apparently I had it wrong yesterday and thus there are no grib files in there.  

As long as the correct version of wgrib2 is denoted in the run.ver file (2.0.8), it brings in the grib files like it should.

In the meantime, I'll copy in the grib files and re-run your stats.

Thanks, and good eye!

Perry

**Comment by PerryShafran-NOAA** [comment]
The stats run is complete, and the stat file is larger than previous.  Please take another look:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_stats/evs/v1.0/stats/nfcens/nfcens.20221221

**Comment by DeannaSpindler-NOAA** [comment]
Yes, that did the trick.  The files are now identical.

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
Good to hear!  On to running the plots now.

Perry

**Comment by PerryShafran-NOAA** [comment]
Plot tar files are here:  

/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_stats/evs/v1.0/plots/nfcens/nfcens.20221221

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,

All the plots are there! Only difference is that I am now running with
dpi=150, and the GitHub version still has dpi=300.

Best,
Deanna

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
Would you like me to submit the code that makes the dpi 150 and re-run the code, so it's identical to yours?  Once that's done and verified, we can put this one to bed.

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Yes, it's probably best if all the EVSv1 runs on the lowest dpi it can.
Let me push my copy to my repo, and then you can run the plots again..


--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by DeannaSpindler-NOAA** [comment]
I've updated  my repo, you can copy it now.

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
New plot files are up.  They are about half the size, which I think is what you expect!

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Hmm.. they are smaller than mine, so I looked at them: they are blank.
Mine have lines.
I don't know what could have gone wrong though..


--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
I'll double check to see that they are pointing to the right archive. 

Perry

**Comment by DeannaSpindler-NOAA** [comment]
I just managed to add my run.ver file to this repo.  Try running it with that?

**Comment by PerryShafran-NOAA** [comment]
Before we do that, check the individual plots here.  They seem to be sizeable enough to have data:   /lfs/h2/emc/stmp/perry.shafran/evs_output/jevs_nfcens_g2o_plots.26404651.cbqs01/sfcshp

**Comment by DeannaSpindler-NOAA** [comment]
The images have the graphs and titles etc, but no lines in them.  It's missing all the data.

**Comment by DeannaSpindler-NOAA** [comment]
Did you copy the stats archive too?

Your errfile has:
Found 1
/lfs/h2/emc/stmp/perry.shafran/evs_output/jevs_nfcens_g2o_plots.26404651.cbqs01/stats/evs*stat
file for 20221221
Mine has:
Found 28
/lfs/h2/emc/stmp/deanna.spindler/evs_output/jevs_nfcens_g2o_plots.26338360.cbqs01/stats/evs*stat
file for 20221221


--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
Hmm - I thought I did but perhaps there are some items missing.  I'll check.

**Comment by PerryShafran-NOAA** [comment]
Well, I had copied all the prep, but I forgot that I needed to copy the stats.  Darn!  Well, I just did so, and I'll do another full run for 20221222.

Perry

**Comment by PerryShafran-NOAA** [comment]
OK, I ran the prep, stats, and plots.  I have plot files that are still a slightly different size but very very close in size.  I compared individual plots to the ones in your tar file and individual plots seem to be identical in size.  

In any case, that seems to be OK, but you can also check the tar files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_stats/evs/v1.0/plots/nfcens/nfcens.20221222

Thanks!

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,

Yes, I see what you mean.  I looked at some of the plots, and they look
fine.  There are the right number of plots too, so I think it's ok.

Best,
Deanna

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
Excellent!  I think I can merge this one.  Thanks!

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
