### PR TITLE
Stats step for CAM radar and severe vx

### PR DESCRIPTION
**Pull request by LoganDawson-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

The stats jobs have been run routinely on user cron and output is being generated as expected.

There are changes to JEVS_CAM_STATS that have been approved by @BinbinZhou-NOAA. Further changes to the definition of `$COMOUT` are needed, but I suggest deferring that effort to a later PR before EE2 review. 

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

1. Clone the radar_svr_stats feature branch
2. Clone the repository with cron scripts for testing: https://github.com/LoganDawson-NOAA/EVS_crons. The driver scripts listed in `crontab.pr134` need to be updated to point to the reviewer's location for $HOMEevs for each `qsub` command
3. In ecf scripts, update COMINspclsr, COMINspcotlk, COMINfcst, and COMINmrms to point to /lfs/h2/emc/vpppg/noscrub/logan.dawson/evs/v1.0/prep/cam (or symlink my prep data to your user space)
4. Set up cron jobs following `crontab.pr134`. (Need to ensure there's a cron.out directory in the user's ptmp space.
5. Radar stats jobs runs hourly on a 1-day lag. All hours between 00-22 UTC must be completed before running cyc=23.
6. The severe stats job can be tested for the current date any time after 08 UTC.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes]**

- [ ] Do these updates/additions include sufficient testing updates? **[No]**

- [ ] Please complete this pull request review by **[As time allows]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@LoganDawson-NOAA  -- I have cloned your fork and checked out your branch: `radar_svr_stats`.

**Comment by ShelleyMelchior-NOAA** [comment]
I have modified all scripts per the instructions and the cron entries have been enabled. I will have these run through the weekend. Please examine the output.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0`
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_*_radar_.o*`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_*_severe_.o*`

**Comment by LoganDawson-NOAA** [comment]
@ShelleyMelchior-NOAA I've examined the output for the radar stats jobs, and your runs for VDATE= 20230624 and 20230625 produced the same output as mine. Final stat files are the same size and the output is the same. I also checked the log files and saw clean exits for all scripts and jobs. The radar piece looks 👍 

For the severe stats jobs, there is no output yet. Those jobs run for VDATE=PDYm7, and all the forecast prep files for the last few daily runs were only on Dogwood up until today. I'll check the jobs that run overnight, and I'll let you know if we need to test the severe case with a specific VDATE that has more forecast prep data available.

**Comment by LoganDawson-NOAA** [comment]
@ShelleyMelchior-NOAA I've brought my feature branch up to date with the changes from Rahul's PR that moved our job cards into `dev/drivers`. The process wasn't 100% straightforward (it seems Github didn't correctly handle all the files with "sample" as the only text), but I got it straightened out.

I also found and fixed a couple of bugs that were impacting the severe stats generation and error mitigation. Whenever you're ready to catch your local branch up with my remote branch, you can rerun the 6 severe stats jobs for today (PDY=20230629 and VDATE=20230622), and I can validate your stat output against mine. The prep archives aren't complete for this VDATE, but I can validate that the expected output is produced (and missing data emails are correct).

**Comment by ShelleyMelchior-NOAA** [comment]
Great @LoganDawson-NOAA  -- I will pull the updates into my clone of your fork and update my cron processing accordingly. I will udpate this PR when that is completed.

**Comment by ShelleyMelchior-NOAA** [comment]
The clone has bee updated, as well as the cron processing. We have passed the window for cron entries for prep, so I will force a manual run. I will udpate when there are results to share.

**Comment by ShelleyMelchior-NOAA** [comment]
The runs are complete.

**Comment by LoganDawson-NOAA** [comment]
The manual runs were successful. The expected output matches the output from my runs, and the jobs completed without error or abnormal exits. Some prep data were missing for this VDATE and the jobs correctly sent "missing data" emails and did not try to verify missing forecast hours.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All changes look good. The driver scripts were updated to populate in `EVS/dev/drivers/scripts`. A follow on PR will address the moving of module load statements into a new file in `EVS/modulefiles` that is then sourced from the driver script.

**Pull request merged**
