### PR TITLE
Bugfix/cam rev6

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

This PR addresses issues 2, 5, 6, 8, 9 and 20 noted in the Google Doc titled "EVS v1.0 issues".

One larger change  (addressing issue 9) was tested by running jevs_mesoscale_nam_grid2obs_stats with and without the change to confirm that the change doesn't affect the job's restart capability.

The other affected jobs were not tested.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

### (1) Set up jobs 
•	symlink the EVS_fix directory locally as "fix"
•	In all driver scripts, point all exports of "HOMEevs" to your EVS test directory
•	In all stats driver scripts, change COMIN to the parallel directory (`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`)
•	Optional: In the stats driver scripts, change "MAILTO" to point to your email address
### (2) Test Jobs
Use the following to submit all jobs: `qsub –v vhr=00 `
From your EVS testing directory, the following scripts should be run using the setup in step (1):
```
dev/drivers/scripts/prep/cam/jevs_cam_hireswarw_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswarwmem2_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswfv3_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hrrr_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_namnest_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswarw_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswarwmem2_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswfv3_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hrrr_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_namnest_severe_prep.sh
```
```
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_mesoscale_nam_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_mesoscale_rap_grid2obs_stats.sh
```

_[Total: 10 prep jobs, 3 stats jobs, 0 plots jobs]_

### (3) Timing
- All jobs can be run at any time

### (4) Review
- I'll check for red flags:
```
check="FATAL\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|empty\|failed\|unexpected\|exceeded"
grep "$check" $outfile
```

- [x] Has the code been checked to ensure that no errors occur during the execution? **YES**

- [x] Do these updates/additions include sufficient testing updates? **YES**

- [x] Please complete this pull request review by **ASAP**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA @AliciaBentley-NOAA Currently starting work on this PR.  The prep jobs are underway.

**Comment by PerryShafran-NOAA** [comment]
Hi, @MarcelCaron-NOAA ,

All the cam prep jobs are now complete.  Please check the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr394test/EVS/dev/drivers/scripts/prep/cam

The output is all here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/cam

Please take a look at all of this.

**Comment by MarcelCaron-NOAA** [comment]
✔️ No negative differences in logs compared to the parallel
✔️ Output files match the parallel

👍 I'm giving the prep jobs a pass

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Excellent!

Also, the one cam stats job you asked to run is complete:

See the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr394test/EVS/dev/drivers/scripts/stats/cam
And the stats are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/___.20231220

**Comment by MarcelCaron-NOAA** [comment]
jevs_cam_hireswarw_radar_stats:
✔️ No hits on red flag keywords
✔️ output files match the parallel

👍 this job looks good to me

**Comment by MarcelCaron-NOAA** [comment]
### Update regarding one of the changes affecting the listed prep jobs:  
It was suggested in a recent email to run prep jobs serially rather than use sleep commands to offset the timing of cpreq commands.  Therefore commit de7e9ab75a5ef36f6620f0b30d7ec4d443489840 is being reverted, and the issue will be addressed on the NCO side.  

_No additional testing is required._

**Comment by AliciaBentley-NOAA** [comment]
Thanks for removing the sleep commands, @MarcelCaron-NOAA! Do we have any plots jobs to test or are we done with testing? If we are done with testing, I approve this PR to be merged! @PerryShafran-NOAA

**Comment by MarcelCaron-NOAA** [comment]
@AliciaBentley-NOAA No plots need to be tested, but two mesoscale stats jobs still need review (one is still running, est. complete 12:50 PM)

**Comment by MarcelCaron-NOAA** [comment]
> No additional testing is required.

Sorry this was vague-- I meant that no _prep_ jobs need to be re-tested because of the commit reversion

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA @AliciaBentley-NOAA All stats jobs are now done if you wish to take a look.  

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr394test/EVS/dev/drivers/scripts/stats/mesoscale

**Comment by MarcelCaron-NOAA** [comment]
jevs_mesoscale_[rap/nam]_grid2obs_stats:
✔️ No hits on red flag keywords
✔️ output files match the parallel

👍 these jobs look good to me.  All jobs referenced above have been tested and reviewed

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Pull request merged**
