### PR TITLE
feature/global_det_wave_rework

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- Rename dev driver scripts to follow naming convention for both atmos and wave
- Adjust job resources
- Clean up unused scripts
- Use same J-JOB for both global_det atmos and wave for prep, stats, and plots
- Add NDBC Buoys and U.S Coastal Water Regions
- Add restart capabilities
- Change image names to follow EVS Image Naming Conventions

- [ ] Describe testing already performed for this Pull Request:</br>

> Prep and stats have been running daily in a cron. Plots has been ran as needed and webpage updated to display new images.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> Checkout the branch
> Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_test_scripts/pr_166/run_evs_global_det_wave_prep.sh. Run it. Have me check the output once it is finished running.
> Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_test_scripts/pr_166/run_evs_global_det_wave_stats.sh. Run it. Have me check the output once it is finished running.
> Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_test_scripts/pr_166/run_evs_global_det_wave_plots.sh. Run it. Have me check the output once it is finished running.
>
> **The cron times for the wave jobs will need to be updated when this is merged into the parallel. Prep will run at 1310, stats at 1315, and the plots jobs at 1345. The crons will also have to be updated for the dev driver script renaming for atmos and wave.**

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **7/31/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

I'm starting to work on this PR.  Question for you though; I see that the module load statements are still in the driver scripts. Did you want to add the modulefiles to this PR or will that be separate?  

Perry

**Comment by malloryprow** [comment]
Oh no, they shouldn't. Which ones are you seeing it in?

**Comment by PerryShafran-NOAA** [comment]
I'm sorry, I forgot to check out the branch!  My mistake.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Here's a legit question:  Does the filename jevs_global_det_wave_gfs_grid2obs_stats.sh include the "gfs" just to be consistent with the atmos file names?  Waves aren't being run on any other model, so I don't think we need the "gfs", but maybe it needs to be there for consistency with the others?

Perry

**Comment by malloryprow** [comment]
Yup, I did it for consistency, though like you said global_det wave only does GFS.

**Comment by PerryShafran-NOAA** [comment]
Prep is finished.

You can see the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr166test/EVS/dev/drivers/scripts/global_det/prep

And the prep output here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det/wave.20230724

Perry

**Comment by malloryprow** [comment]
:heavy_check_mark: Prep is good!

**Comment by PerryShafran-NOAA** [comment]
OK great!  Now to run the stats.

Perry

**Comment by PerryShafran-NOAA** [comment]
Stats is now done..

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr166test/EVS/dev/drivers/scripts/global_det/stats

And the output is here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/*20230724*

Perry

**Comment by malloryprow** [comment]
:heavy_check_mark:  Stats is good!

**Comment by PerryShafran-NOAA** [comment]
Thanks!  Now running the plot jobs.

Perry

**Comment by malloryprow** [comment]
I was watching the .o files in /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr166test/EVS/dev/drivers/scripts/global_det/plots to see when they were done.

:heavy_check_mark: Plots is good!

**Comment by PerryShafran-NOAA** [comment]
Wonderful!  I'm going to do a quick code review and then if all is good, I'll merge.

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by malloryprow** [comment]
Thanks for your work on this PR, @PerryShafran-NOAA! Just wanted to make sure the crons for both global_det atmos and wave get updated when this is merged into the para branch.

**Comment by PerryShafran-NOAA** [comment]
Yes, thanks!  Using Logan's driver scripts that I've been using, that should be relatively easy.  

Perry

**Comment by malloryprow** [comment]
🥳 Woohoo! Let me know if you have any questions.

**Pull request merged**
