### PR TITLE
feature/global_det_atmos_ghrsst_ospo

### PR DESCRIPTION
**Pull request by malloryprow**
This pull request includes:

* replacing the GHRSST GMPE/Median data with GHRSST OSPO

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

> ecf scripts were tested and run over the span of a few days. Plots are at https://emc.ncep.noaa.gov/gmb/mpr/evs_plots_check/grid2grid/sst/ and approved by @AliciaBentley-NOAA 

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
1. Checkout the branch
2. Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_50/evs_global_det_atmos_set_up.sh. Open and set EVSclone to where the clone is. This script will link the fix files, build executables, and clear out the user's prep & stats/global_det directory and the link to my prep & stats/global_det directory since my directory has more data in it.
3. Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_50/run_evs_global_det_atmos_prep.sh. Open and set EVSclone to where the clone is. This script will submit the ecf scripts to run the prep jobs.
4. Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_50/run_evs_global_det_atmos_stats.sh. Once the prep step is run, this script can be run. Open and set EVSclone to where the clone is. This script will submit the ecf scripts to run the stats jobs (3 of them).5. 

We may need to run the prep and stats jobs once or twice to make sure we got the right data.
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

> Yes

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

> Yes

- [ ] Please complete this pull request review by 1/23/2023.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

I have run the prep and the stats for this step.  This doesn't seem to include plots, so I'm not running them.

Please validate the data in the prep directory:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/prep/global_det/atmos.20230111

And also validate the data in the stats directory: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det

Thanks!

Perry

**Comment by malloryprow** [comment]
Looks good! I see the GHRSST OSPO file in the prep output, and SST stat lines in the final stat files.

**Comment by PerryShafran-NOAA** [comment]
OK, thanks!  Does this need a plot test as well?  

Perry

**Comment by malloryprow** [comment]
Nope, this is just switching out the old GHRSST GMPE data for the GHRSST OSPO. No new plots were created to need to check out.

**Comment by PerryShafran-NOAA** [comment]
OK, great!  Let me merge this one in then.

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
