### PR TITLE
bugfix/MAILTO for  mesoscale (det)

### PR DESCRIPTION
**Pull request by ShelleyMelchior-NOAA**
Moving MAILTO definition line into test for definition to be applied only when SENDMAIL=YES.

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

`ush/mesoscale/mesoscale_check_input_data.py` was modified to move the definition of MAILTO to be inside the conditional test for whether or not SENDMAIL is set. MAILTO will only be defined when SENDMAIL=YES.

I ran `dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_nam_grid2obs_stats.sh`.
COMOUT matches the NCO para comout.
This covers item 10 in Wei's document. 

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run either of the nam or rap grid2obs stats drivers. Make sure SENDMAIL=YES. Assure proper completion of the process.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA I have downloaded the code.  I removed MAILTO from the dev driver to see how well this works.  Test is running now.

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA Regretfully, I just noticed that the job died when checking for MAILTO in the script:

/lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr411test/EVS/dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_nam_grid2obs_stats_00.o125649545

```
1 + python /lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr411test/EVS/ush/mesoscale/mesoscale_check_input_data.py
BEGIN: mesoscale_check_input_data.py
Traceback (most recent call last):
  File "/lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr411test/EVS/ush/mesoscale/mesoscale_check_input_data.py", line 67, in <module>
    MAILTO = os.environ['MAILTO']
  File "/apps/spack/python/3.10.4/intel/19.1.3.304/xqft4d45h4dp4xnbz2ue3nbxv65i6bgp/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'MAILTO'
```

Can you double check this directory to see whether /lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr411test/EVS/ush/mesoscale/mesoscale_check_input_data.py is indeed the updated file?  If it is, this needs to be fixed further.

**Comment by ShelleyMelchior-NOAA** [comment]
Yes, the script you ran has the intended changes.
`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr411test/EVS/ush/mesoscale/mesoscale_check_input_data.py`

**Comment by MarcelCaron-NOAA** [comment]
Was SENDMAIL set to "YES"?  I think failure is expected: if SENDMAIL="YES" and MAILTO is not set, we should fail because we need MAILTO as the destination for the warning email.  

I believe the test should be SENDMAIL="NO" + do not set MAILTO.  From Alicia/Perry to motivate the original cam fix:
> If you can add a small fix to your open PR so that MAILTO does not need to be exported if SENDMAIL=NO, that would be great.

**Comment by PerryShafran-NOAA** [comment]
OK, I can test with SENDMAIL=NO.

**Comment by ShelleyMelchior-NOAA** [comment]
The run w/ SENDMAIL=NO has completed.
logfile: `/lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr411test/EVS/dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_nam_grid2obs_stats_00.o125669431`
There are no errors associated w/ MAILTO.
```
$ grep MAILTO /lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr411test/EVS/dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_nam_grid2obs_stats_00.o125669431
##  export MAILTO="perry.shafran@noaa.gov,alicia.bentley@noaa.gov"
  # export MAILTO="firstname.lastname@noaa.gov"
```
The output stat files are not exact, but comparable. My run was a lot later and likely some late arriving metar data was used in the stats that were not available during Wei's run.
```
$ ll /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/mesoscale/nam.20240117
total 84692
-rw-r--r-- 1 emc.vpppg vpppg 36807707 Jan 18 22:27 evs.stats.nam.atmos.grid2obs.metar.v20240117.stat
-rw-r--r-- 1 emc.vpppg vpppg 49913732 Jan 18 22:27 evs.stats.nam.atmos.grid2obs.v20240117.stat
```
```
$ ll /lfs/h1/ops/para/com/evs/v1.0/stats/mesoscale/nam.20240117                                                                                           
total 84040
-rw-rw-r-- 1 ops.para para 36140984 Jan 18 08:51 evs.stats.nam.atmos.grid2obs.metar.v20240117.stat
-rw-rw-r-- 1 ops.para para 49913732 Jan 18 08:51 evs.stats.nam.atmos.grid2obs.v20240117.stat
```

**Comment by PerryShafran-NOAA** [comment]
OK - so the code was designed to run successfully only if SENDMAIL is NO, but it fails when SENDMAIL is YES.  Is this what we want?  If so, then I could merge this PR now.

**Comment by ShelleyMelchior-NOAA** [comment]
> OK - so the code was designed to run successfully only if SENDMAIL is NO, but it fails when SENDMAIL is YES. Is this what we want? If so, then I could merge this PR now.

That is correct. If SENDMAIL=YES , then MAILTO must be set. If MAILTO is not set, then the process is killed.

I think we are good to merge.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
