### PR TITLE
Feature/global ens ghrsst bugfix

### PR DESCRIPTION
**Pull request by StevenSimon-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

I performed a preliminary test to confirm that the modifications made to the global_ens sst prep job workflow enable the access of the ghrsst validation netcdf dataset at the proper vday and with the 12h time shift applied to the time variable in the ghrsst netcdf dataset. Afterwards, I performed a preliminary test to confirm that the updated ghrsst validation netcdf dataset does not trigger a METPLUS WARNING (or any WARNING or ERROR) for the global_ens sst stats job, as shown in the accompanying logfile.     

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run the global_ens atmos prep driver and confirm that the ghrsst validation netcdf dataset archived on COMOUT is at the correct vday and that the time variable features the required 12 h time shift (do a ncdump -h and ncdump -v time to confirm). Afterwards, run the global_ens sst stats driver and confirm that the accompanying logfile features no WARNINGs or ERRORs.    

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

Yes for the preliminary tests.

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

No

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@StevenSimon-NOAA I have begun work on this PR.  The global_ens prep job is underway.

**Comment by ShelleyMelchior-NOAA** [comment]
If you want to follow along, I sniffed out the logfile:
`/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr423test/EVS/dev/drivers/scripts/prep/global_ens/jevs_global_ens_atmos_prep.o114002171`

**Comment by StevenSimon-NOAA** [comment]
Good news. The proper ghrsst netcdf was retrieved:

start_time = "20240123T000000Z" ;
stop_time = "20240124T000000Z"

Also, the 12 h shift in the time variable was also successfully implemented.

**Comment by PerryShafran-NOAA** [comment]
@StevenSimon-NOAA OK, so I forgot to link the fix directory, and hence we see an error in the output.  I linked the fix directory and am rerunning.

HOWEVER, the job got past the ghrsst copy, which is the reason for this PR.  See: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr423test/EVS/dev/drivers/scripts/prep/global_ens/jevs_global_ens_atmos_prep.o114002171

```
+ [ -s /lfs/h1/ops/prod/dcom/20240123/validation_data/marine/ghrsst/20240123_OSPO_L4_GHRSST.nc ]
+ python /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr423test/EVS/ush/global_ens/global_ens_prep_ghrsst_obs.py
BEGIN: global_ens_prep_ghrsst_obs.py
20240123
Copying /lfs/h1/ops/prod/dcom/20240123/validation_data/marine/ghrsst/20240123_OSPO_L4_GHRSST.nc to /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_global_ens_atmos_prep.114002171.cbqs01/atmos.20240123_OSPO_L4_GHRSST.nc
Copying /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_global_ens_atmos_prep.114002171.cbqs01/atmos.20240123_OSPO_L4_GHRSST.nc to /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20240124/gefs/ghrsst.t00z.nc
END: global_ens_prep_ghrsst_obs.py
```
You can see all prep stuff here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20240124

I am now running the jevs_global_ens_gefs_atmos_sst_stats.sh driver, to see if we get any errors there.  If we don't, we should consider this PR successful.  The prep re-run is mainly a sanity check.

@AliciaBentley-NOAA @ShelleyMelchior-NOAA

**Comment by PerryShafran-NOAA** [comment]
OK, the sst stats job was super fast.

See the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr423test/EVS/dev/drivers/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_sst_stats.o114008261

And the stats file here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens/gefs.20240124

I see no warnings or errors in the sst stats job.  

@ShelleyMelchior-NOAA @AliciaBentley-NOAA

**Comment by AliciaBentley-NOAA** [comment]
I looked at the files changed in this PR and think that they look good! If @StevenSimon-NOAA, @ShelleyMelchior-NOAA, and @PerryShafran-NOAA are satisfied with the output (no WARNING, etc.), I would support merging this PR so it can be included in today's EVS v1.0.3 tag for Wei. Thanks!

**Comment by StevenSimon-NOAA** [comment]
> OK, the sst stats job was super fast.
> 
> See the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr423test/EVS/dev/drivers/scripts/stats/global_ens/jevs_global_ens_gefs_atmos_sst_stats.o114008261
> 
> And the stats file here:
> 
> /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens/gefs.20240124
> 
> I see no warnings or errors in the sst stats job.
> 
> @ShelleyMelchior-NOAA @AliciaBentley-NOAA

Everything looks good on my end as well. I think we are in good shape to merge this.

**Comment by PerryShafran-NOAA** [comment]
OK, we're good here and I think we are ready to merge.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
