### PR TITLE
AQM EVS2.0 FIX Feature/fixplotcpu

### PR DESCRIPTION
**Pull request by Ho-ChunHuang-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

> Please include a summary of the changes and the related GitHub issue(s). Please also include relevant motivation and context.

(1) Fix AQM plot script resource to 1 CPU
(2) mv headline directory from atmos.yyyymmdd to headline.yyyymmdd

## Developer Questions and Checklist
* Is this a high priorty PR? If so, why and is there a date it needs to be merged by?
NO

* Do you have any planned upcoming annual leave/PTO?
NO

* Are there any changes needed for when the jobs are supposed to run?
NO 

- [ ] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
YES

- [ ] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
YES

- [ ] References the feature branch for `HOMEevs` are removed from the code.
YES

- [ ] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
YES

- [ ] Jobs over 15 minutes in runtime have restart capability.
YES

- [ ] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
YES

- [ ] Jobs contain the approriate file checking and don't run METplus for any missing data.
NA

- [ ] Code is using METplus wrappers structure and not calling MET executables directly.
YES

- [ ] Log is free of any ERRORs or WARNINGs.
YES, except where there are no stats for ozmax8 in fall and winter time.

## Testing Instructions

> Please include testing instructions for the PR assignee. Include all relevant input datasets needed to run the tests.

Perform regular AQM plots step, and inspects  the log and output directories.

### CODE REVIEW

**Comment by malloryprow** [comment]
Just kicked off the job...

### jevs_aqm_grid2obs_plots.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr598/EVS/dev/drivers/scripts/plots/aqm/jevs_aqm_grid2obs_plots.o159588020
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_aqm_grid2obs_plots.159588020.cbqs01
**COMOUT:** lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr598/evs/v2.0

**Comment by Ho-ChunHuang-NOAA** [comment]
The log look s good.

headline is in the right location

The figures look okay to me
https://www.emc.ncep.noaa.gov/users/verification/air_quality/aqm/pr/grid2obs/pm25/

**Review by malloryprow — APPROVED** [review]
Changes are good and testing successful.

**Review by AndrewBenjamin-NOAA — APPROVED** [review]
I approve the changes for this PR

**Comment by malloryprow** [comment]
Thanks @Ho-ChunHuang-NOAA! Make sure to check these items off for the Fixes and Additions document.

**Pull request merged**
