### PR TITLE
Feature/nfcens wave

### PR DESCRIPTION
**Pull request by DeannaSpindler-NOAA**
This code has the addition of the lead_average plots, and has been running on my cron for months with no issues.  The only concern is that the stats file archive will have gaps (due to machine switchovers) since I have not been monitoring this project.

To run the prep step, make sure to modify the OUTPUTROOT directory under the "developers directories" in 
ecf/nfcens/prep/jevs_nfcens_wave_grid2obs_prep.ecf 
and to point COMIN to my OUTPUTROOT='/lfs/h2/emc/vpppg/noscrub/deanna.spindler/EVS_stats/evs/v1.0' or to the parallel stats files (because mine will have gaps): ‘/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0’ 
because the prep jobs will need this to access the archive. 
Then:  qsub jevs_nfcens_wave_grid2obs_prep.ecf 
The work directory will be under: /lfs/h2/emc/stmp/$USER/evs_output  and is named jevs_nfcens_wave_g2o_prep.{qsubID} 
The run will make ${OUTPUTROOT}/evs/v1.0/prep/nfcens/wave.YYYYMMDD/nfcens/grid2obs  where you will find 5 NetCDF files and 82 grib2 files per day.

To run the stats step, also change the OUTPUTROOT (same as the one above) in 
ecf/nfcens/stats/jevs_nfcens_wave_grid2obs_stats.ecf 
then 
qsub jevs_nfcens_wave_grid2obs_stats.ecf 
The work directory will be under the same /lfs/h2/emc/stmp/$USER/evs_output  but this time is named jevs_nfcens_wave_g2o_stats.{qsubID} 
This run will make ${OUTPUTROOT}/evs/v1.0/stats/nfcens/wave.YYYYMMDD/nfcens/grid2obs  where you will find 42 small stat files: point_stat_fcstNFCENS_obsGDAS_climoERA5_*.stat  and  
${OUTPUTROOT}/evs/v1.0/stats/nfcens/nfcens.YYYYMMDD/evs.stats.nfcens.wave.grid2obs.vYYYYMMDD.stat

Then it's on to the plots. Same as usual, change the OUTPUTROOT in
 ecf/nfcens/plots/jevs_nfcens_wave_grid2obs_plots.ecf
to my OUTPUTROOT='/lfs/h2/emc/vpppg/noscrub/deanna.spindler/EVS_stats/evs/v1.0' or to the parallel stats files (because mine will have gaps): ‘/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0’ 
then 
qsub jevs_nfcens_wave_grid2obs_plots.ecf 
The work directory will be under the same /lfs/h2/emc/stmp/$USER/evs_output  but this time is named jevs_nfcens_wave_g2o_plots.{qsubID} 
This run will make ${OUTPUTROOT}/evs/v1.0/plots/nfcens/nfcens.YYYYMMDD  where you will find the two tar files:  evs.plots.nfcens.wave.grid2obs.last31days.vYYYYMMDD.tar  and  evs.plots.nfcens.wave.grid2obs.last90days.vYYYYMMDD.tar

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Just a note: backlog of prep data can be found in `/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/nfcens/wave*`

**Comment by PerryShafran-NOAA** [comment]
Hi, @DeannaSpindler-NOAA ,

This one seems to be quick.  Please validate that all is ok:  we have prep, stats, and plots output here:  

prep: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/nfcens/wave.20230423
stats:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/nfcens/wave and nfcens.20230423
plots: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/nfcens/nfcens.20230423

Thanks!

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,

Everything looks good, the stat files and plots are all there.  

Best,
Deanna

**Comment by PerryShafran-NOAA** [comment]
Excellent!  I did notice that the lead_average plots did seem to be there this time, so we look to be all good for this one.

Thanks!  I will merge and approve.

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
