### PR TITLE
feature/rtofs_ee2

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

1. Set KEEPDATA to YES in dev/drivers/scripts
2. Replace hard-coded dcom/prod paths with $DCOMROOT
3. Add module loads for PrgEnv-intel and intel, and removing /apps/prod/lmodules/intel/${intel_ver}
4. Move J-Jobs under jobs/
5. Remove setting VDATE in dev/drivers/scripts, and adjust VDATE is J-Jobs
6. Remove hard-coded MET version in plotting configuration files
7. Add SENDDBN alerts for final plots tar file; set default in J-Jobs to SENDDBN=YES while setting to SENDDBN=NO in dev/drivers/scripts
8.  Replace "set +x" with "set -x"
9. Add SENDMAIL; set default in J-Jobs to SENDMAIL=NO while setting to SENDMAIL=YES in dev/drivers/scripts
10. Use 1 exscript for prep
11. Break apart dev/driver/scripts for plots and add appropriate exscripts
12. Use machine.conf in METplus calls
13. Use "compath.py -o" with COMOUT
14. Adjust resources for prep and plots

- [ ] Describe testing already performed for this Pull Request:</br>

> I compared the file counts for the prep step to the emc.vpppg parallel; file counts matched. I ran the stats jobs for the last date (20230918) in the emc.vpppg parallel and the jobs where the observation dataset was still available the stat files were the same. I tested the new, broken-out plots jobs using the emc.vpppg parallel stats files and tar files were the same.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

**Set-up**
> 1. Clone my fork and checkout branch feature/rtofs_ee2
> 2. ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix...or run sorc/build-fix-link.sh?

**prep**

> 3. Run dev/drivers/scripts/rtofs/prep/jevs_rtofs_prep.sh

**stats**
> Do we want to run the stats jobs? If we do we should run for a VDATE of 20230918.

**plots**
> 4. Run dev/drivers/scripts/rtofs/plots/jevs_rtofs_argo_grid2obs_last60days_plots.sh, dev/drivers/scripts/rtofs/plots/jevs_rtofs_aviso_grid2grid_last60days_plots.sh, dev/drivers/scripts/rtofs/plots/jevs_rtofs_ghrsst_grid2grid_last60days_plots.sh, dev/drivers/scripts/rtofs/plots/jevs_rtofs_headline_grid2grid_last90days_plots.sh, dev/drivers/scripts/rtofs/plots/jevs_rtofs_ndbc_grid2obs_last60days_plots.sh, dev/drivers/scripts/rtofs/plots/jevs_rtofs_osisaf_grid2grid_last60days_plots.sh, dev/drivers/scripts/rtofs/plots/jevs_rtofs_smap_grid2grid_last60days_plots.sh, and dev/drivers/scripts/rtofs/plots/jevs_rtofs_smos_grid2grid_last60days_plots.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/${evs_ver}.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes-ish**

- [ ] Do these updates/additions include sufficient testing updates? **Yes-ish**

- [ ] Please complete this pull request review by **10/13/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@malloryprow are we good for testing now?

**Comment by malloryprow** [comment]
I think so. The RTOFS plots and prep step in the parallel already ran for today.

**Comment by malloryprow** [comment]
I'm comfortable with saying the prep job is good!

The files counts from the test are 272. "find /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs/rtofs.20231003 -type f | wc -l" shows 272.

"find /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/rtofs/rtofs.20231002 -type f | wc -l" shows 272 as well.

**Comment by PerryShafran-NOAA** [comment]
Prep also writes files several days back.  Can you check rtofs.20231001 and rtofs.20230930, for example?

**Comment by malloryprow** [comment]
find /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/rtofs/rtofs.20231001 -type f | wc -l
295

find /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs/rtofs.20231001 -type f | wc -l
295

find /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/rtofs/rtofs.20230930 -type f | wc -l
318

find /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs/rtofs.20230930 -type f | wc -l
318

**Comment by PerryShafran-NOAA** [comment]
Great!  Makes me happy to see that.  Thanks!

**Comment by PerryShafran-NOAA** [comment]
Would you like me to run stats or is all good there?  You seemed to be unsure in your instructions.  Up to you.  Are there changes there?

**Comment by malloryprow** [comment]
Yeah, I have all the METplus calls using machine.conf now. The last dates with stat files in the parallel is for 20230918, so if you would like to test them we should do that VDATE so we can compare to the parallel. Since that VDATE is so far back some of the data has aged off of dcom so not all stat files will be able to be reproduced.

**Comment by malloryprow** [comment]
The testing I did yesterday for this is in /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/global/feature_rtofs_ee2/evs/v1.0/stats/rtofs/rtofs.20230918. I could only get stat files for argo, ndbc, and osisaf since the datasets were still available. I think that is because the data are all processed in the prep step. The other ones for aviso, ghrsst, smap, and smos the observations files all aged off from dcom.

**Comment by AliciaBentley-NOAA** [comment]
I support testing the RTOFS stats with the VDATE Mallory indicated!

**Comment by PerryShafran-NOAA** [comment]
OK, let's be complete and thorough here.

@malloryprow - if you're still there, which rtofs stats jobs would you like to see run?  I can do them all. argo and ndbc take a long time to run; everything else is pretty fast.

Perry

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Mallory's work day usually ends at ~3:30pm, so perhaps you could launch all of the RTOFS stats jobs like you offered and then Mallory can check the output tomorrow morning?

**Comment by malloryprow** [comment]
I just got home and I'm gonna work a little more more today! Yes I'm fine with running them all!

**Comment by malloryprow** [comment]
I think the ARGO stats jobs take quite a long time so that will have to be checked in the morning.

**Comment by PerryShafran-NOAA** [comment]
It is actually ndbc that takes the longest - over 3 hours - to complete.  Argo takes about an hour or so.  The other stats jobs I think take much less time.

**Comment by malloryprow** [comment]
Ah gotcha!

**Comment by PerryShafran-NOAA** [comment]
Question:  COMIN and COMINfcst need to be set to emc.vpppg?

**Comment by malloryprow** [comment]
Yes!

**Comment by PerryShafran-NOAA** [comment]
OK all stats jobs are underway.  I'll taking off for the night, but @ShelleyMelchior-NOAA might take over later this evening.

**Comment by PerryShafran-NOAA** [comment]
Note:  I can't do VDATE=20230918 because validation datasets have aged off.  I pretty much have caught up to current time on emc.vpppg, if you want to try a regular 2 days ago case.

**Comment by ShelleyMelchior-NOAA** [comment]
I am also having a hard time running stats. VDATE=20230918 doesn't work b/c older dates for emc.vpppg have aged off. And VDATE=PDYm2 and VDATE=PDYm3 also don't work b/c of holes in the emc.vpppg prep data. I tried to point COMIN to perry.shafran, but the same behavior persisted. I tried to find prep data in mallory.row, too, but must not have been looking in the right places.

But I took the liberty to run the **_plots_** processing as a way to lighten Perry's load a little bit. Please review.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/rtofs/rtofs.20230918`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/rtofs/headline.20230918`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rtofs_*plots.oplots.o8360*`

**Comment by malloryprow** [comment]
✔️  **stats jobs looks good!** 

Available files in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs/rtofs.2023
0918 match /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/rtofs/rtofs.20230918.

**Comment by malloryprow** [comment]
I believe the plots are good as well. I couldn't compare them directly (i.e. comparing file sizes) to those produced from the emc.vpppg parallel since there are no plots for VDATE=20230918, but the number of tar files is are what is expected and the number of images in each tar file is what is expected.

**Comment by malloryprow** [comment]
I think we can go ahead and merged this. I want to get the reorganization started. I want to start it after this is merged because of the creation of new dev/drivers/scripts and the removal and addition of exscripts.

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow I agree. We should merge this one now so we can work on the code structure PR and also add in the ability to run with missing files!

**Comment by ShelleyMelchior-NOAA** [comment]
> @malloryprow I agree. We should merge this one now so we can work on the code structure PR and also add in the ability to run with missing files!

Which is exactly what this component needs!
@PerryShafran-NOAA , want me to merge this one?

**Comment by PerryShafran-NOAA** [comment]
Sure, go ahead.  I was looking for consensus to merge anyway, and we have it now.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All tests produced anticipated results. Stats testing was incomplete, but that is due to the prep data being incomplete. This PR is ready for merge.

**Pull request merged**
