### PR TITLE
EVS AQMv7 verification round 2

### PR DESCRIPTION
**Pull request by Ho-ChunHuang-NOAA**
## Pull Request Testing ##

Only **Prep and Stats** processes has been updated.  

- [ ] Describe testing already performed for this Pull Request:</br>
Pre, stats, and plots on vdate=20240218
cronjob of all 3 steps on vdate=20240219

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Please see [instruction](https://docs.google.com/document/d/1DIAhkvYTuvWDZoWew-imj-NVJdAbrd5I/edit?usp=sharing&ouid=110971079403051862772&rtpof=true&sd=true)
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
YES
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
YES
- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks @Ho-ChunHuang-NOAA , this looks great and I am certain NCO will accept this.

**Comment by PerryShafran-NOAA** [comment]
Hi, @Ho-ChunHuang-NOAA - I have begun working on this PR and am working on the prep step.

**Comment by PerryShafran-NOAA** [comment]
@Ho-ChunHuang-NOAA The prep jobs are complete.

See all the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr457test/EVS/dev/drivers/scripts/prep/aqm
And the output prep directories are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/aqm 

Please take a look.

**Comment by PerryShafran-NOAA** [comment]
@Ho-ChunHuang-NOAA The stats jobs are complete.  I ran the stats job at vhr=00, 04, 11.

See all the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr457test/EVS/dev/drivers/scripts/stats/aqm
See the stats output here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/aqm/____.20240219

**Comment by Ho-ChunHuang-NOAA** [comment]
The log files look okay and the file sizes of prep are the same as my prep output.

**Comment by Ho-ChunHuang-NOAA** [comment]
@PerryShafran-NOAA all logs file look fine with me.  The ozmax8 and pmave stats on 20240219 are identical to mine.  **Can not** verify hourly statistic since it is not ran for a full 00-23.

**Comment by PerryShafran-NOAA** [comment]
@Ho-ChunHuang-NOAA If you like, I can run all hours.  You can also do a quick check on the hourly stats in atmos.20240219.  

Also - there were no changes in any plot scripts, so I am assuming that I do not need to run the plots?

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Could be produce the AQM plots to ensure that the new AQMv7 stats work with them? @Ho-ChunHuang-NOAA

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA I could.  But we only have one day's worth of stats files for v7, unless Ho-Chun has a month-long archive of stats files to use.  

The format of the stats files aren't any different between v6 and v7, so I would suspect that the plots would be just fine.  But I can run it if you'd like.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Perhaps we can merge it (when you are ready) and put it in the emc.vpppg parallel. We could keep an eye on it as it populates the images over the next week? @Ho-ChunHuang-NOAA

**Comment by Ho-ChunHuang-NOAA** [comment]
@PerryShafran-NOAA @AliciaBentley-NOAA Please see instruction for EMC para testing and follow it for PR **plots** testing.

**Comment by Ho-ChunHuang-NOAA** [comment]
Yes, you can run a full set of hourly statistic and I will compare them to mine.

**Comment by PerryShafran-NOAA** [comment]
@Ho-ChunHuang-NOAA I ran all 24 hours of stats verification.  Please compare.

**Comment by Ho-ChunHuang-NOAA** [comment]
@PerryShafran-NOAA Thanks.  I only have script to compare statanalysis products but not stats for each lead time.

**Comment by Ho-ChunHuang-NOAA** [comment]
@PerryShafran-NOAA the 20230219 hourly statics have been checked and they are identical to mine.

**Comment by PerryShafran-NOAA** [comment]
@Ho-ChunHuang-NOAA @AliciaBentley-NOAA Thanks!  I can now then follow Ho-Chun's instructions for plots testing and run a plot test.

**Comment by PerryShafran-NOAA** [comment]
@Ho-ChunHuang-NOAA Please check out the aqm plot log file:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr457test/EVS/dev/drivers/scripts/plots/aqm/jevs_aqm_grid2obs_plots.o134087794

And the plot output:

/lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/aqm/____.20240218

**Comment by Ho-ChunHuang-NOAA** [comment]
@PerryShafran-NOAA The figures look good.

**Comment by PerryShafran-NOAA** [comment]
Excellent!  I think we can merge this then.

**Review by PerryShafran-NOAA — APPROVED** [review]
Tests work as expected.  Approved for merge.

**Pull request merged**
