### PR TITLE
Adjust columns lists used for METv12.0 stats

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

> Please include a summary of the changes and the related GitHub issue(s). Please also include relevant motivation and context.

The METv12.0.0-beta5 update includes new columns for the VL1L2, VAL1L2, and VCNT line types.  Plots scripts that read these line types from stats files need to be updated to reflect the new columns or they will throw an error.

## Developer Questions and Checklist
* Is this a high priorty PR? If so, why and is there a date it needs to be merged by?

I believe this is the next-priority fix needed for most EVS components.  No specific merge date is required as far as I know.

* Do you have any planned upcoming annual leave/PTO?

No, but I am in the middle of resolving WCOSS2 access issues and am unable to review test runs as of 09/18/2024

* Are there any changes needed for when the jobs are supposed to run?

No.
  
- [x] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [x] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [x] References the feature branch for `HOMEevs` are removed from the code.
- [x] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [x] Jobs over 15 minutes in runtime have restart capability.
- [x] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [x] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [x] Code is using METplus wrappers structure and not calling MET executables directly.
- [ ] Log is free of any ERRORs or WARNINGs.

## Testing Instructions

> Please include testing instructions for the PR assignee. Include all relevant input datasets needed to run the tests.

#### (1) Set up jobs

- symlink the EVS_fix directory locally as "fix"
- In each driver script, edit the following environment variables:
**HOMEevs** - set to your test EVS directory
**COMIN** - set to `/lfs/h2/emc/vpppg/noscrub/emc.vpppg/${NET}_beta5/$evs_ver_2d`
**COMOUT** - set to your test output directory
**SENDMAIL** - (_optional_) set to `"NO"`
**DATAROOT** - (_optional_) set to your test DATAROOT directory

#### (2) Running jobs

I recommend testing the following jobs:
```
jevs_cam_grid2obs_plots_last31days
jevs_cam_grid2obs_plots_last90days
jevs_cam_headline_plots
```
[Total: 3 plots jobs]

- All driver scripts can be submitted using `qsub -v vhr=00 $driver`
- All jobs can be submitted at any time

#### (3) Checking jobs
Log files should be checked by the developer for the following keywords:

```
check="FATAL\|WARNING\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|failed\|unexpected\|exceeded"
grep "$check" $logfile
```

_**Note:** Changes are small but they have not been tested due to WCOSS2 access issues._

### CODE REVIEW

**Comment by malloryprow** [comment]
Realizing that pointing to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d for COMIN that all those stats files are generated using beta4, so I don't think the columns are going to be read in correctly. Do you have a parallel run going using beta5? I know your WCOSS2 access has been messed up so perhaps not.

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow Oh, you're right!  We don't have a beta5 archive.  No I do not have a parallel running yet... in that case I'll start one up as soon as I fix access and then these test jobs can be rerun on that output.

**Comment by malloryprow** [comment]
BTW, I set up a beta5 parallel under emc.vpppg and have got the cam prep and stats job set up this afternoon. I can let that run over the weekend (I am off tomorrow). The output is at /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs_beta5, if you get WCOSS2 access soon.

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow sounds good!  I'll take a look at the output and update the instructions by Monday.

**Comment by MarcelCaron-NOAA** [comment]
Hi @malloryprow - I updated the instructions of this PR so that COMIN uses the evs_beta5 output directory.

Also, it looks like the EVS-beta5 runs have been completing successfully since the 12Z cycle today—thanks for setting that up.  I'll check on the 21Z run to confirm that final grid2obs stats files are being produced, and if so then I think we can continue testing this PR.

**Comment by MarcelCaron-NOAA** [comment]
Confirming that yesterday's EVS-beta5 stats runs completed successfully.  There is probably enough data for testing, but a second day of data would be good to have since yesterday's set of runs was incomplete.

**Comment by malloryprow** [comment]
Thanks! I'll give it another day or so and then we can pick this up again!

**Comment by malloryprow** [comment]
### jevs_cam_grid2obs_plots_last31days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr565/EVS/dev/drivers/scripts/plots/cam/jevs_cam_grid2obs_plots_last31days.o156371913
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_grid2obs_plots_last31days.156371913.cbqs01

### jevs_cam_grid2obs_plots_last90days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr565/EVS/dev/drivers/scripts/plots/cam/jevs_cam_grid2obs_plots_last90days.o156371901
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_grid2obs_plots_last90days.156371901.cbqs01

### jevs_cam_headline_plots
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr565/EVS/dev/drivers/scripts/plots/cam/jevs_cam_headline_plots.o156371864
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_headline_plots.156371864.cbqs01

COMOUT for all is /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr565/evs/v2.0/plots/cam.

The grid2obs jobs are still running!

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow All jobs have completed successfully, and output look normal:
✔️ jevs_cam_grid2obs_last31days_plots
✔️ jevs_cam_grid2obs_last90days_plots
✔️ jevs_cam_headline_plots

👍 No other concerns about this PR from me!

**Review by malloryprow — APPROVED** [review]
Changes and testing are good.

**Review by AndrewBenjamin-NOAA — APPROVED** [review]
Thanks for updating the line types and testing the beta5 changes! I approve this PR

**Comment by malloryprow** [comment]
Thanks Marcel! It will be great to have this PR for people to reference for making changes for beta5.

**Pull request merged**
