### PR TITLE
feature/global_det_wave_jason3

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

This PR adds:

1. JASON-3 (satellite altimetry) verification for global_det wave

- [ ] Describe testing already performed for this Pull Request:</br>

> The prep and stats global_det wave jobs have been running in my cron for the past few days. I generated plots for those few days and put them on [https://emc.ncep.noaa.gov/users/verification/global/gfs/test/wave/grid2obs/swh](https://emc.ncep.noaa.gov/users/verification/global/gfs/test/wave/grid2obs/swh) and [https://emc.ncep.noaa.gov/users/verification/global/gfs/test/wave/grid2obs/wsp](https://emc.ncep.noaa.gov/users/verification/global/gfs/test/wave/grid2obs/wsp).

Here is a quick look example though from the few days of stats I have so far!

image

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

NOTE: Since I don't have 31+ days of the JASON-3 stats, the stats on the plots will be the same values. It be good to run both just in case!

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **8/23/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `feature/global_det_wave_jason3`. The `fix/` dir has been linked and I have built `exec/`.

**Comment by ShelleyMelchior-NOAA** [comment]
It is presently 1445Z. Do I need to adjust INITDATE for the prep driver?

**Comment by malloryprow** [comment]
No adjustments needed!

**Comment by ShelleyMelchior-NOAA** [comment]
Great, I will proceed w/ prep. Btw, reading your instructions, there is a typo for the plots driver script names. You wrote atmos but I believe you mean wave?

**Comment by malloryprow** [comment]
Fixed!

**Comment by ShelleyMelchior-NOAA** [comment]
The prep run is complete.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_prep_00.o146233751`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v2.0/prep/global_det`

**Comment by malloryprow** [comment]
prep output looks good!

Log contains the WARNING messages that have been previously noted and discussed. DTC is aware of them and working on adjusting the pb2nc to handle this.

> WARNING:
> WARNING: process_pbfile() -> The observation time should remain the same for all Bufr messages
> WARNING: process_pbfile() ->    80825 messages with different reference time (20240729_000000):
> WARNING: process_pbfile() ->    - 20240729_010000
> WARNING: process_pbfile() ->    - 20240729_020000
> WARNING: process_pbfile() ->    - 20240729_030000
> WARNING: process_pbfile() ->    - 20240729_040000
> WARNING: process_pbfile() ->    - 20240729_050000
> WARNING: process_pbfile() ->    - 20240729_080000
> WARNING: process_pbfile() ->    - 20240729_060000
> WARNING: process_pbfile() ->    - 20240729_070000
> WARNING: process_pbfile() ->    - 20240729_090000
> WARNING: process_pbfile() ->    - 20240729_100000
> WARNING: process_pbfile() ->    - 20240729_110000
> WARNING: process_pbfile() ->    - 20240729_130000
> WARNING: process_pbfile() ->    - 20240729_140000
> WARNING: process_pbfile() ->    - 20240729_120000
> WARNING: process_pbfile() ->    - 20240729_150000
> WARNING: process_pbfile() ->    - 20240729_160000
> WARNING: process_pbfile() ->    - 20240729_180000
> WARNING: process_pbfile() ->    - 20240729_170000
> WARNING: process_pbfile() ->    - 20240729_190000
> WARNING: process_pbfile() ->    - 20240729_200000
> WARNING: process_pbfile() ->    - 20240729_210000
> WARNING: process_pbfile() ->    - 20240729_220000
> WARNING: process_pbfile() ->    - 20240729_230000
> WARNING:

We can move on to testing global_det wave stats with no adjustment needed to VDATE.

**Comment by ShelleyMelchior-NOAA** [comment]
The stats run is complete.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_gfs_wave_grid2obs_stats_00.o146234840`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v2.0/stats/global_det/gfs.20240729`

**Comment by malloryprow** [comment]
stat matches my output and the log looks fine (no red flags in the log).

We can move onto plots with no adjustment to VDATE needed!

**Comment by ShelleyMelchior-NOAA** [comment]
The plots processing is underway. 31 days has finished. 90 days is still going.
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_grid2obs_plots_last*days_00.o*`
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v2.0/plots/global_det/wave.20240729`

**Comment by malloryprow** [comment]
Log is good!

I put the images from this testing on [https://emc.ncep.noaa.gov/users/verification/global/gfs/test/wave/grid2obs/swh/](https://emc.ncep.noaa.gov/users/verification/global/gfs/test/wave/grid2obs/swh/) and [https://emc.ncep.noaa.gov/users/verification/global/gfs/test/wave/grid2obs/wsp/](https://emc.ncep.noaa.gov/users/verification/global/gfs/test/wave/grid2obs/wsp/) if anyone else wants to look over. I think the quick look I did looks good!

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow The new images look good to me, too! Thank you!

CC @ShelleyMelchior-NOAA

**Comment by ShelleyMelchior-NOAA** [comment]
Agreed. Here is a screen grab of the same sample plots that was provided in the PR instructions, but for shifted 31 days.
image

**Comment by ShelleyMelchior-NOAA** [comment]
I did the formal code review and the changes look good. I will wait for an official Mallory green light 🟢 💡 , and then will merge into develop. We can hold off on integrating into the parallel until Perry is back to work next week.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Changes and additions look good. This PR is approved for merge.

**Comment by malloryprow** [comment]
All is good with me!

**Pull request merged**
