### PR TITLE
feature/wave_stats_rm_fbias1

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> Use COMIN from emc.vpppg parallel
> Run dev/drivers/scripts/global_det/stats/jevs_global_det_wave_gfs_grid2obs_stats.sh
> Run dev/drivers/scripts/global_ens/stats/jevs_global_ens_wave_grid2obs_stats.sh
> Run dev/drivers/scripts/nfcens/stats/jevs_nfcens_wave_grid2obs_stats.sh

- [ ] Has the code been checked to ensure that no errors occur during the execution? **No**

- [ ] Do these updates/additions include sufficient testing updates? **No**

- [ ] Please complete this pull request review by **9/14/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@malloryprow , I have cloned your fork and checked out branch `feature/wave_stats_rm_fbias1`. Please go ahead and run sync fork on this branch.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran the 3 stats jobs pointing COMIN to the emc.vpppg para. I used VDATE=20230819

`jevs_global_det_wave_gfs_grid2obs_stats.sh` did not appear to run correctly. There are a bunch of COMINs that I had to reset but maybe I didn't get them all set up correctly?
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/global_det`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o77710334`

`jevs_global_ens_wave_grid2obs_stats.sh`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/global_ens`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_ens_wave_grid2obs_stats.o77707770`

`jevs_nfcens_wave_grid2obs_stats.sh`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/nfcens/`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nfcens_grid2obs_stats.o77707684`

**Comment by malloryprow** [comment]
> grep -r "ERROR" logfile: /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o77710334
> grep: logfile:: No such file or directory
> /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o77710334:1 + echo '*** ERROR : NO NDBC netcdf FILES *** '
> /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o77710334:*** ERROR : NO NDBC netcdf FILES *** 
> /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o77710334:1 + ./postmsg '' 'FATAL ERROR : NO NDBC ASCII2NC FILES for valid date 20230819'
> /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o77710334:1 + err_exit 'FATAL ERROR: Did not copy the NDBC ascii2nc files for valid date 20230819'
> /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o77710334:-- FATAL ERROR: FATAL ERROR: Did not copy the NDBC ascii2nc files for valid date 20230819
> /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o77710334:FATAL ERROR: Did not copy the NDBC ascii2nc files for valid date 20230819

I searched ERROR since that is how I caught this the problem with FBIAS==1 last time. On Cactus, the NDBC buoy data files are not populating, but on Dogwood they are (I opened at ticket with Dataflow this morning).

I'm realizing the code is set up if ascii2nc doesn't not run and create a netCDF file the code _exits out_ instead of not running the METplus jobs. https://github.com/NOAA-EMC/EVS/blob/cad4f868e782484186882686d72884881fc90d86/scripts/global_det/stats/exevs_global_det_wave_grid2obs_stats.sh#L163.

I'm going to update the code so that it does not do this. @AliciaBentley-NOAA @ShelleyMelchior-NOAA This may be in other wave jobs (global_ens, nfcens). Should this update be done for them too?

**Comment by malloryprow** [comment]
Ah, Dataflow has already fixed it!

**Comment by AliciaBentley-NOAA** [comment]
Hi Mallory,

Yes, if there are places where the wave code exits out when the NDBC file
is missing, we need to remove those exits and allow the code to cleanly
continue to run. If you could add those changes to the other wave
components so they can be in ops EVS, that would be great. Thank you!

It's awesome that Dataflow already fixed the missing file issue this
morning!

-Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks @malloryprow  -- let me know when a re-run should happen.

**Comment by malloryprow** [comment]
We are good to re-run. :)

**Comment by ShelleyMelchior-NOAA** [comment]
The re-run for `jevs_global_det_wave_gfs_grid2obs_stats.sh` has completed.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o77909106`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/global_det/` (VDATE=20230822)

**Comment by malloryprow** [comment]
I can still get on Cactus during the prod test. I will check the output now!

**Comment by malloryprow** [comment]
Good news: stat file was created and no fatal errors in the log file

Maybe bad news?: the NDBC files don't get in until 1300Z, so no stats from that but the changes to NOT exit of the code worked as they should (and the NDBC METplus jobs did not run because NDBC file wasn't there)

**Comment by AliciaBentley-NOAA** [comment]
Hi Mallory and Shelley,

Sounds like an inadvertently good test of the GFS wave change to NOT exit
the code! Cool!

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by malloryprow** [comment]
Merged develop in and made a logging message that output ERROR to WARNING. This was made for the changes where the exiting was done. No changes impacting the code that was run, just the logging output.

**Comment by ShelleyMelchior-NOAA** [comment]
Ok, yep, good and bad. Darnit! I should have run it to force VDATE of 20230821. Oh well. I will run again one last time, after pulling in the updates, once cactus is back in dev configuration since that will be well after 13Z.

**Comment by ShelleyMelchior-NOAA** [comment]
I re-ran `jevs_global_det_wave_gfs_grid2obs_stats.sh` and forced VDATE=20230821. 

Aside ...
Interestingly, w/o assigning VDATE in the driver, the job uses PDYm1, which is 20230822, and there was no ndbc data. I don't know if that is always the case, or just a one off situation. Does VDATE need to be PDYm2? The logfile for when VDATE was not set: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o77971714`

logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o77972088`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/global_det/wave.20230821`

**Comment by malloryprow** [comment]
The job are set to run once the job when the NDBC data is available. Parallel production test caused the prep step not to run for VDATE=20230822 so no NDBC files were available for the stats in the emc.vpppg COMIN. The prep step trims the NDBC buoy files so that only data for the VDATE are in them.

:heavy_check_mark: No errors in the log and stat file for 20230821 look good!

**Comment by ShelleyMelchior-NOAA** [comment]
Excellent. Thanks for helping me understand the situation, Mallory. That all adds up and makes me feel better.

**Comment by malloryprow** [comment]
Me too! :) Good to merge this if you are!

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Final tests produced expected results. This PR is approved for merge.

**Pull request merged**
