### PR TITLE
Fixing bug in the ceiling processing for the analysis perfdiag

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

> Please include a summary of the changes and the related GitHub issue(s). Please also include relevant motivation and context.

It was noted by an EMC user that the performance diagrams for the analysis component had the ceiling data in miles, rather than the standard of kft (kilofeet).  Other plots (such as the threshold mean plots) correctly had the data in kft, but the perfdiag did not.  This PR corrects the bug.  

## Developer Questions and Checklist
* Is this a high priorty PR? If so, why and is there a date it needs to be merged by?

Somewhat.  The perfdiag needed to be corrected.  
* Do you have any planned upcoming annual leave/PTO?

I will be on leave 11/25-11/29.

* Are there any changes needed for when the jobs are supposed to run?

No.  
  
- [x ] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [x ] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [x ] References the feature branch for `HOMEevs` are removed from the code.
- [x ] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [ x] Jobs over 15 minutes in runtime have restart capability.
- [x ] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [x ] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [x ] Code is using METplus wrappers structure and not calling MET executables directly.
- [x ] Log is free of any ERRORs or WARNINGs.

## Testing Instructions

> Please include testing instructions for the PR assignee. Include all relevant input datasets needed to run the tests.

1) Clone my fork.
2) Checkout the bugfix/analysis_ceil_fix branch.
3) Link the fix directory.  
4) In the dev/drivers/scripts/plots/analyses directory, set the COMIN directory to emc.vpppg.
5) Run jevs_analyses_grid2obs_plots.sh.

### CODE REVIEW

**Comment by malloryprow** [comment]
### jevs_analyses_grid2obs_plots.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr608/EVS/dev/drivers/scripts/plots/analyses/jevs_analyses_grid2obs_plots.o206875905
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_analyses_grid2obs_plots.206875905.dbqs01
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr608/evs/v2.0

**Review by AndrewBenjamin-NOAA — APPROVED** [review]
I approve these changes pending a successful test. Thank you for identifying the problem quickly and implementing this fix.

**Comment by PerryShafran-NOAA** [comment]
The plot job is finished. The plot tarballs match.  We do see WARNINGs but that was because of missing stats files from the days that the parallel did not run due to outage.  

More importantly, the plot in question now is in kft rather than miles.

image


I think that this PR is good.

**Review by malloryprow — APPROVED** [review]
Changes are good and testing successful.

**Pull request merged**
