### PR TITLE
feature/wafs_atmos2

### PR DESCRIPTION
**Pull request by YaliMao-NOAA**
1. Fix a bug to create stat file of the global region.
2. Modify Python plotting scripts to plot the global region.
3. In Python plotting scripts, change the pressure levels of icing severity from integer to float which is displayed in the plotting.
4. Add the capability of wind direction plotting

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@YaliMao-NOAA , we can get to this PR very soon. Can you sync the feature branch associated with this PR with the auth EVS develop? There have been a number of PRs merged since you initiated this PR and we need your feature branch up to date. Thanks!

**Comment by YaliMao-NOAA** [comment]
@ShelleyMelchior-NOAA Thank you for the reminder. I just merged EVS develop branch to my branch for this PR. Thank you!

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @YaliMao-NOAA ! I haven't tested any of your PRs before, but hopefully this one will be pretty straightforward. Do you only need me to test the plots processing?

**Comment by YaliMao-NOAA** [comment]
@ShelleyMelchior-NOAA The stat script was modified too with this PR. I did my test on my own. If you want to do a test, please do both stat and plot.
dev/drivers/scripts/wafs/stats/jevs_wafs_atmos_stats.sh
dev/drivers/scripts/wafs/plots/jevs_wafs_atmos_plots.sh
Thank you!

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @YaliMao-NOAA , I ran the plots driver using the stats from the emc.vpppg para. Please review.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/wafs/atmos.20230803`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_wafs_plots.o88691590`

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks Yali! I saw your note too late and jumped the gun. I will test stats, too. Do you have a stats archive I can test with so that the plots reflect the stats changes? Otherwise, I can generate plots w/ my stats that are generated in my test, but it will be a short period.

**Comment by ShelleyMelchior-NOAA** [comment]
In `jevs_wafs_atmos_stats.sh` please remove the following line. 
`export MET_bin_exec=bin`
This no longer needs to be exported from the driver because it is specified in the machine.conf file.

**Comment by ShelleyMelchior-NOAA** [comment]
I have run the stats processing. Please review.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/wafs/wafs.20230803`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_wafs_stats.o88710223`

**Comment by YaliMao-NOAA** [comment]
@ShelleyMelchior-NOAA Both log file and output files look good to me. I also checked it worked after removing export MET_bin_exec=bin from the stat job card. Thank you for pointing it out.

**Comment by ShelleyMelchior-NOAA** [comment]
@YaliMao-NOAA -- Great! Can you recommend how I test plots? Should I point to the stats files I just generated? Or do you have a larger archive w/ the stats updates that I should use instead?

**Comment by YaliMao-NOAA** [comment]
@ShelleyMelchior-NOAA You can just simply submit the plot job card. I don't have a larger archived data resources now.

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @YaliMao-NOAA , the plots processing completed. I pointed it to use the stats files that I generated earlier today. Please review.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/wafs/atmos.20230803`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_wafs_plots.o88756420`

**Comment by YaliMao-NOAA** [comment]
@ShelleyMelchior-NOAA Sorry for the late reply. I took a look at the plotting and found the xaxis range is not set correctly so there are overlapped dates shown on xaxis when the end date is one the few beginning days of a month. I just committed the correction.

**Comment by ShelleyMelchior-NOAA** [comment]
No problem, @YaliMao-NOAA . I appreciate your thorough checking. I can re-run the plots for the same VDATE to confirm the plots look as expected.

**Comment by ShelleyMelchior-NOAA** [comment]
@YaliMao-NOAA , I re-ran the plots processing for VDATE=20230803, using the stats I generated yesterday. I scp'd the tar files to emcrzdm and untar'd them for you to review when WCOSS2 is unavailable. Please review.
[g2g 31](https://ftp.emc.ncep.noaa.gov/users/smelchior/EVS/wafs/g2g31/)
[g2g 90](https://ftp.emc.ncep.noaa.gov/users/smelchior/EVS/wafs/g2g90/)

**Comment by YaliMao-NOAA** [comment]
@ShelleyMelchior-NOAA Thank you for the re-plotting. However the axis of last31days.rmse is still messed up. My plotting is not. I made an update which I am not sure you picked it up or not:
https://github.com/NOAA-EMC/EVS/pull/177/commits/8ab7fc4d285faec2dd015818512429557d5f7c80
Thank you!

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks Yali! I was pretty sure I did, but let me double check.

**Comment by ShelleyMelchior-NOAA** [comment]
Nope! I remember noting the change in the code review, but I never did a git pull in my clone of your fork. My apologies. I will re-run the plots right now!

**Comment by ShelleyMelchior-NOAA** [comment]
@YaliMao-NOAA , the re-run is complete! I didn't untar this time since we still have access to dogwood today.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/wafs/atmos.20230803`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_wafs_plots.o88985996`

**Comment by YaliMao-NOAA** [comment]
@ShelleyMelchior-NOAA It looks good now! Thank you.

**Comment by ShelleyMelchior-NOAA** [comment]
Excellent. I will formalize the code review and approve the PR for merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
This PR is approved for merge.

**Pull request merged**
