### PR TITLE
feature/global_det_cyc_changes

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

1. Change "cyc" to "vhr"; set "cycle" default to "t${vhr}z"
2. I found no instances of "CYC" being used by global_det
3. Change non-J-job references of "cyc" to "inithour"
4. Remove "DCOMINget_d"
5. Add check for ECMWF files in COMOUT before changing file permissons

- [ ] Describe testing already performed for this Pull Request:</br>
> I ran all global_det dev/drivers/scripts and compared the output. All output matched as expected.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

**Set-up**
> 1. Clone my fork and checkout branch feature/global_det_cyc_changes
> 2. cd sorc
> 3. ./build-fix-link.sh
> 4. ./build.sh

**prep**
> 5. Run dev/drivers/scripts/prep/global_det/jevs_global_det_atmos_prep.sh and dev/drivers/scripts/prep/global_det/jevs_global_det_wave_prep.sh. Depending on when this is run, INITDATE in jobs/JEVS_GLOBAL_DET_PREP may be need to be set to PDYm2.

**stats**
> 6. Run dev/drivers/scripts/stats/global_det/jevs_global_det_wave_gfs_grid2obs_stats.sh, dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_gfs_grid2grid_stats.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver. Depending on when this is run, VDATE in jobs/JEVS_GLOBAL_DET_STATS may be need to be set to PDYm2.

**plots**
> 7. Run dev/drivers/scripts/plots/global_det/jevs_global_det_wave_grid2obs_plots_31days.sh and dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2obs_pres_levs_plots_31days.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **11/17/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
I have begun work on this PR, starting with the prep step.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Prep is complete (ran for PDYm2).

The .o files are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr302test/EVS/dev/drivers/scripts/prep/global_det
The output is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det/*20231015*

**Comment by malloryprow** [comment]
:heavy_check_mark: **prep is good!**

Let's run stats for VDATE=PDYm2 as well!

**Comment by malloryprow** [comment]
:heavy_check_mark: **stats are good!**

For the jobs we are testing for plots, no need to adjust the date in the jobs/JEVS_GLOBAL_DET_PLOTS.

dev/drivers/scripts/plots/global_det/jevs_global_det_wave_grid2obs_plots_31days.sh already ran today in the parallel. dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2obs_pres_levs_plots_31days.sh is currently running.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Could you re-run the plots jobs but leaving jobs/JEVS_GLOBAL_DET_PLOTS as it is?

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Oops, I had already changed it to PDYm2 earlier.  Changed it back to PDYm1 and re-running the plots jobs.

**Comment by PerryShafran-NOAA** [comment]
Plots are now done.

See the .o files:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr302test/EVS/dev/drivers/scripts/plots/global_det
and the output here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_det/*20231016*

**Comment by malloryprow** [comment]
✔️ **plots are good!**

**Comment by PerryShafran-NOAA** [comment]
Excellent!  I will do a quick code review.  Check to see if you need to sync fork.

**Comment by malloryprow** [comment]
It is up to date 👍

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Pull request merged**
