### PR TITLE
Feature/subseasonal G2G TMP and future warning fix

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
This PR includes the addition of 2m temperature stats and plots, as well as fixing/removing the FutureWarning message that appears in G2O job output (on list of Fixes and Additions in EVS v2.0 doc).
Testing has been done on the command line and plots have been initially reviewed on dev rzdm space.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Checkout this feature branch.
Change HOMEevs, FIXevs, etc. accordingly.
NOTE: It is important given this is for EVSv2.0 development that EVS/versions/run.ver is changed to "export met_ver=12.0.0-beta4" and "export metplus_ver=6.0.0-beta4".
For stats jobs, please link to my prep data:
/lfs/h2/emc/vpppg/noscrub/shannon.shields/EVS_Data/evs/v1.0/prep/subseasonal
For plots jobs, please link to my stats archive:
/lfs/h2/emc/vpppg/noscrub/shannon.shields/evs_subseasonal_test/dev/com/evs/v1.0/stats/subseasonal
To test the G2G stats scripts for new TMP variable, please run the following:
EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_cfs_grid2grid_stats.sh
EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.sh
To test the G2G plots scripts for new TMP variable, please run the following:
EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_temp_plots_31days.sh
EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_temp_plots_90days.sh
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>
Within a week or so.
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA I am starting work on your PR.  You have quite the long name for your branch!  

Thanks for the detailed instructions.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA Yes, I know it is a long name but I wanted to capture what is included in this PR.
Can you please hold off on testing this PR until my prep jobs are done for today? That will be around 10:40am (in about an hour). This way, we test the stats with today's full worth of prep data since you will be linking to my directory.

**Comment by PerryShafran-NOAA** [comment]
Yes, I will wait for your go-ahead.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA The prep jobs have completed for today, so you may proceed with the stats testing for this PR. Please remember to:
Change HOMEevs, FIXevs, etc. accordingly.
Given this is for EVSv2.0 development, change /versions/run.ver to "export met_ver=12.0.0-beta4" and "export metplus_ver=6.0.0-beta4".
Link to my prep data:
/lfs/h2/emc/vpppg/noscrub/shannon.shields/EVS_Data/evs/v1.0/prep/subseasonal

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Sorry - had to take care of an issue in operations, but I'm now back to your PR.

Your job completed.  Here are the .o files, you can find them here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr476test/EVS/dev/drivers/scripts/stats/subseasonal

And the output is here:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/subseasonal

Please take a look.  Check for any errors or warnings, and double check that I did, in fact, use the beta4 versions.  I haven't upgraded the parallel to beta4 yet, so I may need to re-run the test, but do check to see that it's at least good for beta4.

Thanks!

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA No worries, I heard of the ops issue. So I just confirmed that everything ran correctly for the G2G stats jobs with no WARNINGs nor ERRORs. Memory limit is good and I can confirm TMP variable is now in the final stat files.
Before proceeding with G2G plots, I forgot a part of this PR that we need to test. So please run the following in order to test the G2O FutureWarning fix:
EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_cfs_grid2obs_stats.sh
EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2obs_stats.sh

**Comment by PerryShafran-NOAA** [comment]
The grid2obs stats jobs are underway.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Looks like the grid2obs jobs are finished.  Would you please look at the .o file, in the same directory as the other .o files?  And also check the output as well in the same directory as noted above as well.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA Yes, I just finished checking all of the output and confirmed no WARNINGs nor ERRORs, and "FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead" no longer shows up in the output file (fixed).
If you have time to test G2G plots jobs, please run the following:
EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_temp_plots_31days.sh
EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_temp_plots_90days.sh
Please make sure to set COMIN to my stats archive:
/lfs/h2/emc/vpppg/noscrub/shannon.shields/evs_subseasonal_test/dev/com/evs/v1.0/stats/subseasonal

**Comment by PerryShafran-NOAA** [comment]
Plot jobs are underway.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Jobs are finished.  Please check the .o files here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr476test/EVS/dev/drivers/scripts/plots/subseasonal

And the tarballs are here:

/lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/subseasonal/atmos.20240511

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA I am about to end my workday, but I can confirm that each of the plot jobs ran successfully with no ERROR and no unexpected WARNING (memory is fine too). I checked the size of the tar files and they match my own test runs:
-rw-r--r-- 1 perry.shafran emc 21M May 13 20:14 evs.plots.subseasonal.atmos.gr
id2grid_temp.last31days.v20240511.tar
shannon.shields@clogin08: atmos.20240511:$ls -lath evs.plots.subseasonal.atmos.grid2grid_temp.last90days.v20240511.tar                                     
-rw-r--r-- 1 perry.shafran emc 22M May 13 20:14 evs.plots.subseasonal.atmos.gr
id2grid_temp.last90days.v20240511.tar
So with your last code review, this PR should be set to merge. :-)

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Do you want to check that the specific new temperature variable plots look as expected?  I think we should do that before we merge this.  It's not a big deal to wait until tomorrow AM.

**Comment by ShannonShields-NOAA** [comment]
Yes, good idea @PerryShafran-NOAA . I will check tomorrow.

**Comment by ShannonShields-NOAA** [comment]
Good  morning @PerryShafran-NOAA . I have checked the new temp plots on my dev rzdm space and everything looks as expected.
https://emc.ncep.noaa.gov/users/verification/global/subseasonal/dev/atmos/grid2grid/tmp_2m/
This PR is fully tested/vetted and ready for merging.

**Comment by PerryShafran-NOAA** [comment]
Thank you!  I'll do a code review and then merge if all looks good.

**Comment by ShannonShields-NOAA** [comment]
& I double-checked to confirm the repo is up-to-date.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
