### PR TITLE
Bugfix/subseasonal cpreq and chmod command error fixes

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
This PR includes:
Change cpreq to cp and add file checks
Address item 86 from Wei to fix chmod 640 error by adding file check
Remove old/unused code
Testing has been done on the command line.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Checkout branch and adjust HOMEevs path and link FIXevs.
Go to jobs/JEVS_SUBSEASONAL_PREP and change the COMINnam path to ${envir}/coms/obsproc/${obsproc_ver to simulate missing data.
Run the following prep job to test the chmod error fix:
dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_obs_prep.sh
For stats testing, link COMIN path to emc.vpppg parallel prep.
Then run the following:
dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.sh
dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2obs_stats.sh
The only thing to test for the plots step is the change from cpreq to cp. First link COMIN to emc parallel stats.
Then run:
dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_anom_plots_31days.sh
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>
ASAP
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
I have reviewed this PR and think that it looks good. I see all the cp -v changes that we expected. I also see the changes to fix item 86 from Wei for subseasonal (chmod 640). Commented out code was deleted, but some other clean up was done to code that wasn't commented out. I recommend thorough testing and would support this PR being merged if @ShannonShields-NOAA and @PerryShafran-NOAA felt that the output looked good! Thanks!

CC @ShelleyMelchior-NOAA

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA Can you please confirm that the following lines from item 86 was also addressed in this PR?

```
**JEVS_SUBSEASONAL_PREP** missing ghrsst - complete w/ WARNING but pointing to /tmp

WARNING: /lfs/f1/ops/para/tmp/evs_subseasonal_obs_prep.132057861.dbqs01/prep/atmos.20240203_OSPO_L4_GHRSST.nc does not exist
```

```
**JEVS_SUBSEASONAL_PREP** missing ecmwf - failed w/ WARNING and FATAL ERROR

WARNING: /lfs/h1/ops/pppp/dcom/20240204/wgrbbul/ecmwf/DCD02040000020400001 does not exist
Running  chmod 640 /lfs/h1/ops/test/com/evs/v1.0/prep/subseasonal/atmos.20240204/ecmwf/ecmwf.2024020400.anl
FATAL ERROR: chmod 640 /lfs/h1/ops/test/com/evs/v1.0/prep/subseasonal/atmos.20240204/ecmwf/ecmwf.202402040
0.anl gave return code 1
```

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA I am starting work on your PR.  I have followed the instructions to mimic a fake directory to create the missing file situation and started the prep job.  The .o file can be found here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr438test/EVS/dev/drivers/scripts/prep/subseasonal

**Comment by ShannonShields-NOAA** [comment]
Thanks @PerryShafran-NOAA . I have to see what the issue is with the missing GHRSST before proceeding.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Please look at Wei's document.  There were actually two issues with subseasonal that were added, perhaps after you submitted this PR.  There was also an issue with ecmwf data.

**Comment by ShannonShields-NOAA** [comment]
Ugh, this is frustrating. So I am using "log_missing_file_obs(log_missing_file, daily_source_file, 'GHRSST OSPO', date_dt)" which has the correct source path, but since we are not sending these email missing messages, this is basically useless. My code then goes on to "copy_file(daily_prepped_file, daily_dest_file)" which is why the prep tmp path is showing up in the WARNING. @PerryShafran-NOAA and @AliciaBentley-NOAA I am going to need some time to fix this because this applies to all prep data, not just GHRSST. Wei must not be listing the full missing data test results.

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA Would you like us to test this PR as it is, so we can get the other fixes into develop and the next tag, and then you can submit a new PR for the other items in 86 that aren't done yet?

@PerryShafran-NOAA @ShelleyMelchior-NOAA

**Comment by malloryprow** [comment]
@ShannonShields-NOAA Check what I did for global_det: https://github.com/NOAA-EMC/EVS/blob/0c1e87f0f1b54e7e4af2964111d10ec1deffd76e/ush/global_det/global_det_atmos_util.py#L101

It attaches WARNING only for missing file in com or dcom

**Comment by ShannonShields-NOAA** [comment]
Ah yes, thank you so much @malloryprow ! That is a much quicker/better fix than what I was thinking.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Please let me know when this is ready to restart testing and new instructions for what to test.

**Comment by ShannonShields-NOAA** [comment]
Ok, all of Wei's items are now addressed. @PerryShafran-NOAA please go in jobs/JEVS_SUBSEASONAL_PREP and change ALL the COMIN paths to reflect ALL missing data to replicate Wei's test. Change it to /lfs/h1/ops/pppp/.
Then run the following:
dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_gefs_prep.sh
dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_cfs_prep.sh
dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_obs_prep.sh

**Comment by ShannonShields-NOAA** [comment]
Make sure to recheck out the branch or sync it to get that last update "Adjust WARNING alerts".
Then make sure to set HOMEevs and FIX link as said in original PR instructions.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA OK, I changed envir=pppp in the J-job in order to get these to work.  Check out the .o files now and see if I did that correctly and to see if these changes worked as intended.

**Comment by ShannonShields-NOAA** [comment]
Darn, I forgot to tell you to turn off the SENDMAIL alerts. Can you please kill the jobs and set SENDMAIL=NO? @PerryShafran-NOAA

**Comment by ShannonShields-NOAA** [comment]
Sorry for the million emails; please ignore and turn off SENDMAIL for all prep jobs.

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA It's ok- it happens! I get spammed by these tests a lot! Yes, we should turn SENDMAIL off in turn tests in this PR and others. @PerryShafran-NOAA @ShelleyMelchior-NOAA

**Comment by PerryShafran-NOAA** [comment]
OK, should I re-run all the prep jobs with SENDMAIL=NO?

**Comment by ShannonShields-NOAA** [comment]
Yes, please @PerryShafran-NOAA because otherwise we are all going to get a million emails in our inbox about the fake missing data. Also, you first need to delete all data in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/subseasonal/atmos.20240205 for a clean restart test.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Re-runs are underway, with SENDMAIL=NO.

**Comment by ShannonShields-NOAA** [comment]
Sorry @PerryShafran-NOAA , we are still having issues. I'm not seeing the full path: "WARNING: 00/6hrly_grib_01/pgbf2024020500.01.2024020500.grb2 does not exist". I realize we need to set "export envir=pppp" in the dev/drivers (jevs_subseasonal_gefs_prep.sh, jevs_subseasonal_cfs_prep.sh, and jevs_subseasonal_obs_prep.sh). Right now, you have "envir=pppp" in the j-job.

**Comment by ShannonShields-NOAA** [comment]
I'm still trying to figure out the path issue. I realize that you did have the right idea in putting the envir change in JEVS_SUBSEASONAL_PREP. However, can you possibly hardcode it in such as "$(compath.py pppp/com/" to make sure the change is only in the COMIN prep paths?

**Comment by ShelleyMelchior-NOAA** [comment]
> I'm still trying to figure out the path issue. I realize that you did have the right idea in putting the envir change in JEVS_SUBSEASONAL_PREP. However, can you possibly hardcode it in such as "$(compath.py pppp/com/" to make sure the change is only in the COMIN prep paths?

@PerryShafran-NOAA , I suggest just exporting the specific COMIN variables from the driver script so that the imported value overwrites the default.

**Comment by ShannonShields-NOAA** [comment]
Ah ok, I finally realize why the paths are confusing/incorrect @AliciaBentley-NOAA @ShelleyMelchior-NOAA @PerryShafran-NOAA .  The output file says:
"11 + compath.py pppp/com/cfs/v2.3/cfs.20240205
**The relative COM path provided (pppp/com/cfs/v2.3/cfs.20240205) is not formatted correctly.**
1 + export COMINcfs=
1 + COMINcfs="
This is the same for all envir to pppp changes; it won't recognize the path so it appears blank in the WARNING message:
"WARNING: 00/6hrly_grib_01/pgbf2024020500.01.2024020500.grb2 does not exist"
as opposed to the tmp prepped file NOTE:
"NOTE: /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_subseasonal_cfs_prep.132127377.dbqs01/prep/data/cfs/pgbfcfs.01.00z.f000 does not exist"

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA @ShelleyMelchior-NOAA I suppose that I can hard code the paths in the driver scripts.  I was trying to minimize my editing previously.  Let me do that now.  

But also this doesn't solve stuff coming in from DCOMIN - which was what the issue is with ghrsst and ecmwf.  How would you like me to deal with that?

**Comment by ShannonShields-NOAA** [comment]
@AliciaBentley-NOAA @ShelleyMelchior-NOAA and @PerryShafran-NOAA Please see my message about "**The relative COM path provided (pppp/com/cfs/v2.3/cfs.20240205) is not formatted correctly**". No matter how/where envir=pppp is set, it won't matter for the testing because it won't be recognized; the COMIN path will be blank! We cannot truly test in this manner. **I think we should consult Wei in how he did his missing data testing to get around this?**

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA We will use the full path in the driver script to do this.  Stay tuned.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA I am placing this block of code in all three prep drivers:

```
export COMINgefs=/lfs/h1/ops/pppp/com/gefs/${gefs_ver}/gefs.${INITDATE}
export COMINcfs=/lfs/h1/ops/pppp/com/cfs/${cfs_ver}/cfs.${INITDATE}
export COMINgfs=/lfs/h1/ops/pppp/com/gfs/${gfs_ver}
export DCOMIN=/lfs/h1/ops/pppp/dcom
export COMINnam=/lfs/h1/ops/pppp/com/obsproc/${obsproc_ver}
```

This should force all the directories to be exactly what you want.

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA @PerryShafran-NOAA For what it's worth, these are some instructions that Wei gave Mallory in the EVS v1.0 Issues document: `"Wei: I simply changed COMINmodel to a fake place, then ran the jobs."`

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Prep jobs are underway.  Please examine the new .o files.  And I did delete the prep directory in COMOUT before I submitted..

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA They're already finished (due to the missing data).  Please take a look.

**Comment by ShannonShields-NOAA** [comment]
Ugh. So the CFS prep is all good but I need to check out GEFS prep. Also, the DCOMIN path setting did not work as the script is still looking at prod: "Copying /lfs/h1/ops/**prod**/dcom/20240204/validation_data/marine/ghrsst/20240204_OSPO_L4_GHRSST.nc"
@PerryShafran-NOAA I'm running out of ideas on how to test this.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Let me look as to why that is.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA OK, those all need to be added to the dev drivers as well.  One second please.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA OK, new runs are finished.  Please check the new .o files.

**Comment by ShannonShields-NOAA** [comment]
Ok, my apologies for the delay; I was re-checking the GEFS and obs prep runs.
So all is good now except for GHRSST. I included the fix as you can see above. Please remove ghrsst directory from the COMOUT and then rerun jevs_subseasonal_obs_prep.sh. This should be the last prep test!

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA please make sure to re-check out or sync my branch first to include the GHRSST fix. Then remove ghrsst directory from the COMOUT and then rerun jevs_subseasonal_obs_prep.sh. Thanks!

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA I pulled in your latest changes, removed the ghrsst directory, and am now rerunning.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA The obs prep job is done.  Would you please take a look at the most recent .o file?

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA YES! Ok, now everything is good to go with the prep testing. Stats testing should be much more straightforward.
For stats, please link the COMIN path to emc.vpppg parallel prep in dev/drivers. ("export COMIN=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/${evs_ver_2d}/prep/$COMPONENT/$RUN")
Then run the following:
dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.sh
dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2obs_stats.sh

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Do you need prep testing without the fake directories, using real data to test changes other than missing file warnings?  Or do we not need any further prep tests?

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA @ShannonShields-NOAA And if we are testing missing files, can SENDMAIL be set to NO again so we don't have a repeat of prep? haha

**Comment by ShannonShields-NOAA** [comment]
Nope, the prep testing was only for missing files. We can move onto stats.

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA I think that the rest of the testing is standard testing not having anything to do with missing files (more for the cpreq to cp requirement).  Is that correct, @ShannonShields-NOAA ?

**Comment by ShannonShields-NOAA** [comment]
Yes, that is exactly correct @PerryShafran-NOAA. (& why I'm having you link to the full existing prep dir in the parallel)

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Stats jobs are underway.  You can see the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr438test/EVS/dev/drivers/scripts/stats/subseasonal

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA I confirmed that both stats jobs have completed successfully and copied correctly to COMOUT using new cp function. 
For plots testing (just testing cp change only), please set COMIN=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/${evs_ver_2d}
Then run dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_anom_plots_31days.sh.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA The plots test is underway.  You can find the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr438test/EVS/dev/drivers/scripts/plots/subseasonal

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA I confirmed that the plot job has completed successfully and copied correctly to COMOUT using new cp change. Phew! I know this PR testing literally took all day; thank you so much for your assistance with everything. All should be good now to review and merge.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Good news!  I think no other PR was merged today, but please check if we need to sync your fork with develop.  Thanks!

**Comment by ShannonShields-NOAA** [comment]
All is up-to-date!

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
