### PR TITLE
Feature/ascii2ncv6

### PR DESCRIPTION
**Pull request by Ho-ChunHuang-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@Ho-ChunHuang-NOAA , the auth EVS develop was just updated a bit ago by a PR merge. Please go ahead and repeat the sync and merge steps so your `feature/ascii2ncv6` branch is up to date w/ the latest code.

**Comment by ShelleyMelchior-NOAA** [comment]
Run instructions from Ho-Chun ...

You need to update the directory hosted the code/script, running directory, and output directory to your personal setting.  Maybe the mail list as well.  For others, it should be automatically set for NRT verification.  Additional adjustment is needed if you want older date verification.

(1) ~/EVS/ecf/aqm/prep/jevs_aqm_prep.ecf
update 

export HOMEevs=

export DATA=

export COMIN=

export maillist=

Run this first before stats, as in  (2).  The default is PDYm3 in $HOMEevs/jobs/aqm/prep/JEVS_AQM_PREP.

Otherwise, for older date, check the available date by

ls /lfs/h1/ops/prod/dcom/yyyymmdd/airnow
ls /lfs/h1/ops/prod/com/aqm/v6.1/cs.yyyymmdd

The date can be used also needs to be found in these two obs & fcst directories.

> qsub jevs_aqm_prep.ecf

Output is in ${COMIN}/prep/aqm/atmos.yyyymmdd/aqm

(2) ~/EVS/ecf/aqm/stats/jevs_aqm_stats.ecf
update 

export HOMEevs=

export DATA=

export COMIN=

export maillist=

The default in run.ver is model_ver=aqm_ver=v6.1.  So it automatically works for aqmv6.

> qsub run_aqm_stats.sh

Output is in ${COMIN}/stats/aqm/aqm.yyyymmdd

Please let me know if you have any questions

**Comment by ShelleyMelchior-NOAA** [comment]
Instructions from Ho-Chun ...

You need to update the directory hosted the code/script, running directory, and output directory to your personal setting.  Maybe the mail list as well.  For others, it should be automatically set for NRT verification.  Additional adjustment is needed if you want older date verification.

(1) ~/EVS/ecf/aqm/prep/jevs_aqm_prep.ecf
update 

export HOMEevs=

export DATA=

export COMIN=

export maillist=

Run this first before stats, as in  (2).  The default is PDYm3 in $HOMEevs/jobs/aqm/prep/JEVS_AQM_PREP.

Otherwise, for older date, check the available date by

ls /lfs/h1/ops/prod/dcom/yyyymmdd/airnow
ls /lfs/h1/ops/prod/com/aqm/v6.1/cs.yyyymmdd

The date can be used also needs to be found in these two obs & fcst directories.

> qsub jevs_aqm_prep.ecf

Output is in ${COMIN}/prep/aqm/atmos.yyyymmdd/aqm

(2) ~/EVS/ecf/aqm/stats/jevs_aqm_stats.ecf
update 

export HOMEevs=

export DATA=

export COMIN=

export maillist=

The default in run.ver is model_ver=aqm_ver=v6.1.  So it automatically works for aqmv6.

> qsub run_aqm_stats.sh

Output is in ${COMIN}/stats/aqm/aqm.yyyymmdd

Please let me know if you have any questions

**Comment by PerryShafran-NOAA** [comment]
@Ho-ChunHuang-NOAA - I noticed that the run_aqm_stats.sh file had the same line that I was using in my day-to-day runs:

`qsub -v cyc=$fhr /lfs/h2/emc/vpppg/save/$USER/EVS3/ecf/aqm/stats/jevs_aqm_stats.ecf`

Please validate for me that you, indeed, were running the new stats jobs rather than pointing somewhere else.  

Thanks!

Perry

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Perry:

All tests were ran from my own HOMEevs, i.e.,
* /lfs/h2/emc/vpppg/noscrub/ho-chun.huang/EVS*
/ecf/aqm/stats/jevs_aqm_stats.ecf.

I did not update the run_aqm_stats.sh because it should be used by you in
parallel.  I have a similar one but using my HOMEevs.

Ho-CHun

--

Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Comment by PerryShafran-NOAA** [comment]
OK, thanks!

One issue that I am running into is that email warnings are being sent out for missing AQM forecast files.  But all the warnings are for f00 files.  It appears that production AQM forecast files start at f01, there are no f00 forecast files.  This email warning should be changed so that it only looks for missing data for f01 or later in the forecast.  Do you think you can make that modification?

Thanks!

Perry

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Perry:

Okay I will do it.  Stay tune.

Ho-Chun

--

Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Perry:

Scripts are modified to check from ihr=1.

Ho-Chun

--

Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Comment by PerryShafran-NOAA** [comment]
Thanks!  I'll re-test these changes.  

Perry

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Perry:

I update the ~/ecf/* comments for running v7 NRT.

Ho-Chun

--

Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Perry:

I fixed and updated the ihr=0 for v7 scripts.  It will not impact your v6
NRT testing.

Ho-Chun

--

Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Comment by PerryShafran-NOAA** [comment]
Hi, Ho-Chun,

I have completed both the prep and the stats runs.  Would you please go ahead and validate the results for me?  

You can find the prep data here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/aqm/atmos.20230529
The stats data is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/aqm/aqm.20230529 and atmos.20230529

The .o files are here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_aqm/ecf/aqm/prep/jevs_aqm_prep_00.o73920870
For stats they are in my home directory /u/perry.shafran; please look at the last 24 aqm stats files for those results.

There is no change to plots, is that correct?

Thanks!

Perry

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Perry:

No changes to plot on jobs, scripts, ush.  Only ecf have been changed
(export, emaillist,...).  I will check the result and get back to you later.

Ho-Chun

--

Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Perry:

(a) The conf for hourly may not be correct, can I take a look at yours?
There are no matching, for example, model valid time 20230529_000000 vs obs
valid time 20230528_230000

V11.0.2 AQM   NA    120000
V11.0.2 AQM   NA    180000
V11.0.2 AQM   NA    360000
V11.0.2 AQM   NA    420000
V11.0.2 AQM   NA    600000
V11.0.2 AQM   NA    660000

(b) for ozmax8 and pmave, did you run the prep from 20230526 to 20230529
first before you run the stat for 20230529"04" and 20230529"11"?

Ho-Chun








--

Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Comment by PerryShafran-NOAA** [comment]
a)  Please take a look at the conf files in /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_aqm/parm/metplus_config.  They should be exactly the same as yours, I did not touch them.

b) I put in already existing prep data for 20230527 and 20230528.  Should I have added in 20230526 also?

Thanks!

Perry

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Perry:

Yes, you need day 3 forecast of 20230526, that is valid at 20230529 04 or
11Z.

Ho-Chun

--

Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Comment by Ho-ChunHuang-NOAA** [comment]
Perry:

Are you still using the BUFR as OBS input? Make sure you use the updated
CONF file for v6.

(a1) there are no statistic for cat_thresh
in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/aqm/atmos.20230529/aqm/grid2obs/point_stat_aqm_awpozcon_bc_120000L_20230529_000000V.stat
(a2) OBS_VAR is COPO
(a3) OBTYPE is AIRNOW

(b1) there are statistic for the cat_thresh
in /lfs/h2/emc/physics/noscrub/ho-chun.huang/evs/v1.0/stats/aqm/atmos.20230529/aqm/grid2obs/point_stat_aqm_awpozcon_bc_120000L_20230529_000000V.stat
(b2) OBS_VAR is OZONE
(b3) OBTYPE is AIRNOW_HOURLY_AQOBS

Maybe you should remove all hourly-statistics of this day then re-run.
This maybe the reason why the daily statistic missing matching of file like
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/aqm/atmos.20230529/aqm/grid2obs/point_stat_aqm_awpozcon_bc_120000L_20230529_000000V.stat

--

Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Perry:

What it said in previous email happens to all valid time at *000000V.stat
in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/aqm/atmos.20230529/aqm/grid2obs

Ho-Chun

--

Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Comment by PerryShafran-NOAA** [comment]
Perhaps part of the problem is that data from the PR is going in the same directory that I am running all my regular AQM runs.  I will stop those and  clear the directory and start over with your PR.  Data is being muddled up.  Let me restart all of this and I will get back to you.

Perry

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Perry:

Thanks for the update.

I did not change the DATA because it will be a unique directory in an
operational setting.

But for personal run, to prevent overwriting the data when multiple days
are running at the same time, you might want to consider using

For Prep:
export DATA=${DATAROOT}/${VDATE}_${MODELNAME}

move this statement after the "export VDATE=".

For Stats:
export DATA=${DATAROOT}/ ${VDATE} _${cyc}_${MODELNAME}

move this statement inside the for cyc loop.

Simply my suggestion for your consideration.

Ho-Chun

--

Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Comment by PerryShafran-NOAA** [comment]
DATA should have the jobid in there so each run will have a unique directory so there is no overwriting in the working directory.  I can show you some examples of what I have done for the $DATA working directory in other EVS components so you can make similar changes.  DATA shouldn't even be defined in the ecf file, but we are doing so only for development purposes.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Ho-Chun,

Today's run is complete.  I ran the prep and stats steps for 20230530, and I also stopped the jobs that were using the prepbufr file, so it should be a clean run.  Please take a look at the prep and stats output, in the same place where I told you about yesterday.

Thanks!

Perry

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Perry:

Thanks.  I will compare them with my own run.

Ho-Chun

--

Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Perry:

Your daily statistic are identical to mine in
/lfs/h2/emc/physics/noscrub/ho-chun.huang/evs/v1.0/stats/aqm/aqm.20230530

If you have any questions, please let me know.

Ho-Chun

--

Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by PerryShafran-NOAA** [comment]
I thought I entered a comment here, but somehow it disappeared. I did approve this PR given the stats from my run were identical to yours.

Thanks for all the good work.

Perry

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Perry:

Thanks for all your hard work.

Ho-cHun

--

Ho-Chun Huang, Ph.D.

Physical Scientist III, Contractor with Lynker in Support of

NOAA/NWS/NCEP/EMC, U.S. Department of Commerce

5830 University Research Ct., Rm. 2792

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3958

**Pull request merged**
