### PR TITLE
feature/global_det_rm_jlogfile

### PR DESCRIPTION
**Pull request by malloryprow**
1. Remove jlogfile from J-Jobs

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
> I did not do any testing

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
**Set-up**
> 1. Clone my fork and checkout branch feature/global_det_rm_jlogfile
> 2. cd sorc
> 3. ./build-fix-link.sh
> 4. ./build.sh

**prep**
> 5. Run dev/drivers/scripts/prep/global_det/jevs_global_det_wave_prep.sh (Run after 1315Z or 9:15am)

**stats**
> 6. Run dev/drivers/scripts/stats/global_det/jevs_global_det_wave_gfs_grid2obs_stats.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vppg/$NET/${evs_ver_2d}.

**plots**
> 7. Run dev/drivers/scripts/plots/global_det/jevs_global_det_wave_grid2obs_plots_31days.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vppg/$NET/${evs_ver_2d}.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **No**

- [ ] Do these updates/additions include sufficient testing updates? **No**

- [ ] Please complete this pull request review by **11/09/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Starting work on your PR.  Looks like this only affects the wave portion of global_det, which is good - fewer jobs to check!

**Comment by malloryprow** [comment]
Great! Since the jobs have already ran in the parallel (plots may still be running), no need to change any of the dates.

**Comment by PerryShafran-NOAA** [comment]
The prep job is finished.  Please take a look at the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr329test/EVS/dev/drivers/scripts/prep/global_det/jevs_global_det_wave_prep_00.o107879923.  Pay close attention to see whether things like jlogfile and postmsg aren't anywhere in your output.

The output is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det/wave.20231031

**Comment by malloryprow** [comment]
:heavy_check_mark: **prep is good!**

Matches the emc.vpppg parallel run for today and found no instances of "postmsg" or "jlogfile" in /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr329test/EVS/dev/drivers/scripts/prep/global_det/jevs_global_det_wave_prep_00.o107879923.

**Comment by PerryShafran-NOAA** [comment]
Great!  Starting the stats step now.

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow @PerryShafran-NOAA I have looked over the jlogfile changes in this PR and think that it looks good! I approve this for merge after all testing is completed! Thanks!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I had to resubmit the job.  It seemed that the wallclock time was exceeded on this run. Trying again to see if the machine is better.

**Comment by PerryShafran-NOAA** [comment]
Finally, the job completed.  I added some wall clock time to the run.  Please see the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr329test/EVS/dev/drivers/scripts/stats/global_det

And the output files are here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/____.20231031

**Comment by malloryprow** [comment]
:heavy_check_mark: **stats is good!**

Matches the emc.vpppg parallel run for today and found no instances of "postmsg" or "jlogfile" in /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr329test/EVS/dev/drivers/scripts/stats/global_det/*.o*.

**Comment by PerryShafran-NOAA** [comment]
Great, on to plots!

**Comment by PerryShafran-NOAA** [comment]
Plots is done.

Please see the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr329test/EVS/dev/drivers/scripts/plots/global_det
and the plot tarball here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_det/wave.20231031

**Comment by malloryprow** [comment]
:heavy_check_mark: **plots is good!**

The parallel's global_det wave tar files are missing, but given the problems on Dogwood this morning this would have impacted the jobs. The image count in /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_det/wave.20231031/evs.plots.global_det.wave.grid2obs.last31days.v20231031.tar is what it should be though, so I feel fine merging this.

**Comment by PerryShafran-NOAA** [comment]
OK thanks!  We are ready to merge then.

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
