### PR TITLE
feature/global_det_v1.0plus

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

This PR includes a variety of changes and updates related to EVS v2.0:

1. Add "last" into dev drivers and ecf plots script names
2. Remove echo of $config in dev driver scripts
3. _Change "past" to "last" in global_det wave image names_
4. _Remove use of LOOP\_ORDER in METplus config files_
5. _Use subprocess.run_ and remove subprocess import when not used
6. _Switch GFS and ECMWF order on headline plot so GFS is first_
7. Update grid2grid and grid2obs stats job script formatting
8. Clean up logging messages
9. Mask out negative values prior to taking square root to avoid warning messages
10. _Rename dev drivers scripts so they match ops ecf scripts_
11. Add "set -x" to mail scripts
12. _Define $NET before $HOMEevs_
13. _Remove PBS \-V_ (#464)
14. Add 0.25 inch threshold for ETS global_det atmos headline plots
15. Update default MET version in plotting scripts for running standalone
16. Add $COMOUTosisaf
17. Fix y-axis scale on headline precip ETS plots per WPC request
18. _Use PB2NC\_SKIP\_VALID\_TIMES_
19. _Remove cat'ing of log files as LOG\_TO\_TERMINAL\_ONLY = TRUE is now being use_
20. _Update long-term plots to show the ACC average of the period they display (all vs. 10 yr)_
21. Remove ltop, uptrop, and trop grid2grid_pres_levs plots for Ozone
22. Make some warning messages debug or note statements.
23. Update drivers to use environment VDATE_END

Those is _italics_ are in the [Fix and Additions in EVS v2.0](https://docs.google.com/document/d/1vOGnCwCM3COUhQlTqHyBZrYSCPx9b6AYnxLc5NtVGEk/edit) document.

**NOTE**: Upon merging this PR, we will need to update the cron scripts for the renamed stats and plots drivers.

- [ ] Describe testing already performed for this Pull Request:</br>
I have been running the global_det prep, stats, and plots drivers in my crontab for the past two weeks. I compared the prep and stats output to the emc.vpppg parallel and the output for 20240706 all matched. I did not compare the plots tar files directly as I'm pointing to my stats and not the emc.vpppg parallel stats. I checked the logs and there are not unexpected warning or error messages.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

The testing for this PR is going to be a lot but we can take it chunk by chunk and work through it.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **7/19/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I will be starting this PR.  Looks extensive!  Downloading the code to get ready to run the first step.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Sounds good! The wave jobs are good to go to run for today if you are starting with those. atmos prep just finished running in the parallel too, (INITDATE/VDATE=20240707)

**Comment by PerryShafran-NOAA** [comment]
OK, I'll start with all prep jobs.

**Comment by malloryprow** [comment]
Cool! Will check the output in morning; I'm heading out for the day in about 15 min.

**Comment by malloryprow** [comment]
Both global_det wave and atmos prep are good. The output matches the emc.vpppg parallel and the logs are good too. The only WARNING messages in the log files are related to the missing dcom JMA precip files, so all is working as it should. :+1:

**Comment by malloryprow** [comment]
We can do the wave stats and plots next, if you want. Those will run at 1325Z and 1350Z respectively.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow OK let me do the wave stats and plots.  I already set up each of the codes to point to emc.vpppg so we're good to go.  I'll wait an hour or so to submit them since it's not yet 1325Z.

**Comment by PerryShafran-NOAA** [comment]
Submitted the wave stats component.

**Comment by malloryprow** [comment]
wave stats output and log are good.  The final stat file matches the emc.vpppg parallel and the log is good too. :+1:

**Comment by PerryShafran-NOAA** [comment]
Excellent, starting the wave plot jobs.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow While the wave plots job is running, can we start some of the atmos stats jobs?  Are we good on timing for those?

**Comment by malloryprow** [comment]
You can start running them, just make sure to run with VDATE=20240707.

**Comment by PerryShafran-NOAA** [comment]
All stats jobs are underway.

**Comment by malloryprow** [comment]
:+1: wave plots are good! Logs are good and final tar file size and image counts match emc.vpppg parallel.

Confirming that the image names have been changed from "pastXdays" to "lastXdays".

> tar -tvf /lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/global_det/wave.20240708/evs.plots.global_det.wave.grid2obs.last90days.v20240708.tar 
> -rw-r--r-- perry.shafran/emc 125506 2024-07-09 15:38 evs.global_det.corr.htsgw_l0_ndbc_standard.last90days.fhrmean_valid00z_f384.latlon_0p25_glb.png
> -rw-r--r-- perry.shafran/emc 138058 2024-07-09 15:38 evs.global_det.corr.htsgw_l0_ndbc_standard.last90days.fhrmean_valid00z_f384.latlon_0p25_gom.png
> -rw-r--r-- perry.shafran/emc 124467 2024-07-09 15:38 evs.global_det.corr.htsgw_l0_ndbc_standard.last90days.fhrmean_valid00z_f384.latlon_0p25_hawaii.png

**Comment by PerryShafran-NOAA** [comment]
All the stats jobs have completed except for the gfs atmos grid2obs job, if you wish to take a look.  

The long_term_stats job seems to be smaller than all the others, but perhaps it's supposed to be?

**Comment by malloryprow** [comment]
All jobs are done now!

The atmos stats jobs are good. :+1: There are ERROR and WARNING messages in the logs, but these are known and expected and will be resolved in beta5. The final stat files are all good.

For atmos plots, you'll want to run with VDATE_END=20240707 for every job but jevs_global_det_atmos_long_term_plots.sh. Additionally, in jevs_global_det_atmos_headline_plots.sh set envir=dev.

**Comment by PerryShafran-NOAA** [comment]
Awesome!  Just to confirm, your thumbs up includes for long term stats?  

I'll get the plot jobs started.

**Comment by malloryprow** [comment]
Yup! The long-term stats are set up a bit different than the "standard" stats jobs.

**Comment by PerryShafran-NOAA** [comment]
Plot jobs are all now underway.

**Comment by malloryprow** [comment]
I'll check them when I start working tomorrow. The GFS v17 T2O meeting is soon, and then I'm heading out after. Some of the plot jobs take an hour+ to run.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow All the plot jobs are finished.  I noted that I set the date for VDATE, not VDATE_END, and realized that those values are different because all the plot tarballs have a vdate of 20240708, and I set VDATE for 20240707.  If I need to re-run anything, please let me know, but since you are checking tomorrow, those plot jobs can be compared.

**Comment by malloryprow** [comment]
I'd prefer if we can rerun with VDATE_END=20240708 and clear out the COMOUT. I'd like to compare the final tarball sizes with the  emc.vpppg parallel.

**Comment by PerryShafran-NOAA** [comment]
OK will do!

**Comment by malloryprow** [comment]
Interesting! I see in the logs you ran with "-v VDATE_END=20240708", but the job ran with VDATE_END=20240709. I can see what happened in the driver scripts. `export VDATE_END=$(finddate.sh $today d-1)` overrode your passed environment variable. I can make the change for the code to check if VDATE_END exists in the environment and make $(finddate.sh $today d-1) the default.

**Comment by PerryShafran-NOAA** [comment]
Oh thanks for checking!  Yeah, that would certainly be helpful here.

**Comment by malloryprow** [comment]
Just pushed the changes!

**Comment by PerryShafran-NOAA** [comment]
Thank you!  I'll re-run once again.  

When Samira's PR is merged, you'll also need to sync your fork.  But you always pay attention to these things!

**Comment by malloryprow** [comment]
Will watch!

**Comment by PerryShafran-NOAA** [comment]
Re-runs underway.  Hopefully this one is good!

**Comment by malloryprow** [comment]
🤞 May the third time be the charm

**Comment by malloryprow** [comment]
Woohoo!

> mallory.row@dlogin06:~> ls -ltr /lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/global_det
> total 8
> drwxr-sr-x  2 perry.shafran emc 4096 Jul 10 12:47 headline.20240708
> drwxr-sr-x 11 perry.shafran emc 4096 Jul 10 12:48 atmos.20240708

I'll watch the jobs and report back. I will watch for Samira's PR merge too.

**Comment by malloryprow** [comment]
The atmos headline plots is done running so I reviewed that. Log is good and headline images that run in prod match the emc.vpppg parallel. Confirming the change of GFS being listed before ECMWF in the long-term ACC plot.

image

**Comment by PerryShafran-NOAA** [comment]
All the plot jobs are finished - but for some reason accidentally neglected to submit the long term plot job.  Just did so now.  We should have a complete plot set when that finishes.  Please check everything else.

**Comment by malloryprow** [comment]
Minus the long-term plots, the final plots tarballs are good. File sizes match the emc.vpppg parallel but the grid2grid_pres_levs which is expected because the Ozone lower troposphere, upper troposphere, and troposphere vertical profile plots were removed. Logs are good too.

I'll follow the long-term plots log.

**Comment by malloryprow** [comment]
The long-term plots jobs is done now. All looks well with the output and log.

All good with testing and reviewing the output.

**Comment by PerryShafran-NOAA** [comment]
Good news!  Let me do the code review.  I think you already took care of the ecf defs file, which is a pretty large chunk of the job, but let me double check.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
