### PR TITLE
Bugfix/cam copy pcpcombine obs

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>
All stats jobs have been tested, running to completion and successfully outputting obs files to COMOUT.  
- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
**_Slightly different process compared to recent cam PRs_**:
### (1) Set up jobs 
•	symlink the EVS_fix directory locally as "fix"
•	In all driver scripts, point all exports of "HOMEevs" to your EVS test directory
•	In _stats_ driver scripts, change COMIN to the parallel directory (`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`)
•	In _plots_ driver script, change COMIN **to the test stats COMOUT directory** (`/lfs/h2/emc/vpppg/noscrub/$USER/$NET/$evs_ver_2d/stats/$COMPONENT`)
•	Optional: In all stats drivers scripts, change "MAILTO" to point to your email address
### (2) Test Jobs
Use the following... 
...to submit stats jobs: `qsub –v vhr=21,VDATE=$(date -d "-3 days" +"%Y%m%d") `
...to submit plots jobs: `qsub –v vhr=00,VDATE=$(date -d "-2 days" +"%Y%m%d") `
From your EVS testing directory, the following scripts should be run using the set up in step (1):
```
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_precip_stats.sh
```
```
dev/drivers/scripts/plots/cam/jevs_cam_precip_plots.sh
```

_[Total: 0 prep jobs, 5 stats jobs, 1 plots jobs]_

I'll check the resulting COMOUT directory for 24-hour MRMS precip netCDF files:
`ls $COMOUT/atmos.2023*/*/precip/spatial_maps/mrms*`

...and for spatial maps:
`tar --wildcards -tvf $COMOUTplots/evs.plots.cam.atmos.precip.v2023*.tar qpe*`

I'll also check for red flags:
```
check="FATAL\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|empty\|failed\|unexpected\|exceeded"
grep "$check" $outfile
```

- [x] Has the code been checked to ensure that no errors occur during the execution? **YES**

- [x] Do these updates/additions include sufficient testing updates? **YES**

- [x] Please complete this pull request review by **12/19/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA ,

I will begin work on this PR.  Just a point of clarification:  you say for the plots test to point NOT to emc.vpppg but to the stats output from the stats test.  That would mean that there is only one day's worth of stats to test the plots job on.  Just wanted to clarify this is what you want.

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA Yes, there's no obs mrms data in the parallel so we have to generate it first and point to that.  This will test generating mrms precip maps.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA I am done with the stats testing for precip stats.

Please look at the .o files here:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr385test/EVS/dev/drivers/scripts/stats/cam

And the output stats directory here:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/atmos.20231210

There are no final stats files, but I guess that's to be expected since the gather step is done at 22Z?

**Comment by MarcelCaron-NOAA** [comment]
> There are no final stats files, but I guess that's to be expected since the gather step is done at 22Z?

Yes, this is expected!

___
✔️ output stats files look good compared to the parallel
✔️ no hits on red flag keywords
✔️ stats processing produced MRMS files:
```
[marcel.caron@dlogin04 ~] ls /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/atmos.20231210/*/precip/spatial_maps/mrms* | wc -l
66
```

👍 Therefore, stats are ok with me.  I think we are ready to test the plots job

**Comment by PerryShafran-NOAA** [comment]
Excellent!  I will submit the plots job.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA I don't think that the precip plot job quite worked.  Will you take a look at the output for me?

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr385test/EVS/dev/drivers/scripts/plots/cam/jevs_cam_precip_plots.o121107840

I pointed to my local copy of the stats job and submitted the plot job exactly as you prescribed.  Yet it seems that the plot tarball is empty.  Please look at the output for me.

**Comment by PerryShafran-NOAA** [comment]
OSError: FATAL ERROR: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/stats/cam does not exist.
Create and populate /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/stats/cam and retry.

I think this is part of the error.  It seemed you had asked me to add stats/$COMPONENT to $COMIN, but that caused some issues here.  Let me remove that and try again.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA @MarcelCaron-NOAA The COMIN path in the dev drivers should end at the "same" directory as the COMIN path in the associated J-job. If there two lengths are different, this script will not work in ops. Can you please confirm that we are ending COMIN at the same directory length in both the dev drivers and J-jobs? Thanks. 

CC @ShelleyMelchior-NOAA

**Comment by MarcelCaron-NOAA** [comment]
Hi @AliciaBentley-NOAA :

Yup, they match --
dev/drivers/scripts/plots/cam/jevs_cam_[grid2obs/headline/precip/snowfall]_plots.sh:
> export COMIN=/lfs/h2/emc/vpppg/noscrub/$USER/$NET/$evs_ver_2d

jobs/JEVS_CAM_PLOTS:
>   88   export COMIN=${COMIN:-$(compath.py $envir/com/$NET/$evs_ver)}

(*edited to show COMIN settings)

**Comment by MarcelCaron-NOAA** [comment]
> OSError: FATAL ERROR: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/stats/cam does not exist. Create and populate /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/stats/cam and retry.
> 
> I think this is part of the error. It seemed you had asked me to add stats/$COMPONENT to $COMIN, but that caused some issues here. Let me remove that and try again.

@PerryShafran-NOAA sorry my instructions were incorrect.  Please use `/lfs/h2/emc/vpppg/noscrub/$USER/$NET/$evs_ver_2d` if you haven't already.  Thanks

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA Please double check the paths in the last two messages that you wrote. It appears that COMIN in the dev driver for the plotting script should be /lfs/h2/emc/vpppg/noscrub/$USER/$NET/$evs_ver_2d based on your last message. That is not what you wrote in message before that (which ends at /$COMPONENT). Is /lfs/h2/emc/vpppg/noscrub/$USER/$NET/$evs_ver_2d in both places correct?

**Comment by MarcelCaron-NOAA** [comment]
Hi @AliciaBentley-NOAA:
I mistakenly gave the COMOUT settings when you asked about the COMIN settings.  The COMOUT settings end at $COMPONENT.   The COMIN settings as they are written in the edited comment above are correct.  Sorry for the confusion.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Thanks so much for your clarifications.  I was wondering about those instructions, but I think that we clarified things and all scripts are now correct.

The job has completed, and the plot tarball is not empty.

Please check the .o file here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr385test/EVS/dev/drivers/scripts/plots/cam/jevs_cam_precip_plots.o121120489

And the plot tarball (and the restart directory) is here:

/lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/cam/atmos.20231211

@AliciaBentley-NOAA @ShelleyMelchior-NOAA

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA Thanks!

✔️ no red flags from keywords check
✔️ plots processing produced MRMS-based observation maps:
```
[marcel.caron@dlogin09 EVS] tar --wildcards -tvf $COMOUTplots/evs.plots.cam.atmos.precip.v2023*.tar qpe*
-rw-r--r-- perry.shafran/emc 37481 2023-12-13 19:17 qpe.v2023121012.024h.hawaii.png
-rw-r--r-- perry.shafran/emc 18385 2023-12-13 19:17 qpe.v2023121012.024h.hawaii.gif
-rw-r--r-- perry.shafran/emc 53723 2023-12-13 19:17 qpe.v2023121012.024h.alaska.gif
-rw-r--r-- perry.shafran/emc 135765 2023-12-13 19:17 qpe.v2023121012.024h.alaska.png
-rw-r--r-- perry.shafran/emc  51466 2023-12-13 19:17 qpe.v2023121012.024h.prico.png
-rw-r--r-- perry.shafran/emc  22667 2023-12-13 19:17 qpe.v2023121012.024h.prico.gif
```
✔️ plots processing also produced HRRR and NAM Nest CONUS maps, which was a recent concern.

👍 plots job is ok with me.

**Comment by PerryShafran-NOAA** [comment]
Good news!  Let me do a quick code check and then we will merge.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code runs as expected; approved for merge.

**Pull request merged**
