### PR TITLE
feature/global_det_atmos_restart

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

Adds restart capabilities for global_det atmos prep, stats, and plots

- [ ] Describe testing already performed for this Pull Request:</br>

> I would run these myself submitting jobs to the queue

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> I haven't come up with specific instructions or scripts like I have in the past. My guess is we want test that the restart works and the results are what expected. Therefore, rather than the scripts jobs may be needed to be submitted from the command line to the queue, cancelled, and then reran to test the restart capabilities. To be able to compare the stats and plots to my run we may need to link some directories when we get there.

> However be sure once you checkout the branch and move in to the directory be sure to 
> 1. "ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix"
> 2. mkdir -p exec
> 3. cd sorc
> 4. ./build_evs_global_det_atmos.sh

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes **

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **5/16/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

I'm going to start working on this today.  I'll follow your above instructions.  Can you suggest which ones of your jobs runs the longest, so I can probably test those?  Maybe I can shorten the run time so they are killed before they are complete, so I don't have to babysit them while they are running.  Then change it back and resubmit the job to test the restart.  I guess I can do this on any one of your scripts.  

Perry

**Comment by malloryprow** [comment]
Sure!

For the prep, there is only the one so you'll just want to run that one.
For the stats, jevs_gfs_atmos_grid2grid_stats.ecf, jevs_gfs_atmos_grid2obs_stats.ecf are the longest.
For the plots, jevs_global_det_atmos_grid2obs_pres_levs_plots_90days.ecf, jevs_global_det_atmos_grid2obs_pres_levs_plots_31days.ecf, jevs_global_det_atmos_grid2obs_sfc_plots_90days.ecf, jevs_global_det_atmos_grid2obs_sfc_plots_31days.ecf are the longest.

For the plots jobs, you'll want to link the my stats directory. For the stats, if you run any others you'll need my prep directories.

**Comment by PerryShafran-NOAA** [comment]
Is this still the directory you are operating in?  

ln -sf /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det global_det

**Comment by malloryprow** [comment]
Yup, once we confirm the stats jobs run okay then you can link it. I think if you link it now then the stats jobs won't be able to write to it.

**Comment by PerryShafran-NOAA** [comment]
OK, I'll just start from prep and work my way in.  Do I need several days of prep to run the stats job, or is just running prep good enough to run the stats job?

Perry

**Comment by malloryprow** [comment]
For the GFS, no. The stats jobs will just need the output from the prep job from today, but no previous days.

**Comment by PerryShafran-NOAA** [comment]
I must be missing something.  I just took your prep job and ran it, but got this error:

```
1 + /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/scripts/global_det/prep/exevs_global_det_atmos_prep.sh
0 + echo

0 + python /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ush/global_det/global_det_atmos_prep.py
Traceback (most recent call last):
  File "/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ush/global_det/global_det_atmos_prep.py", line 11, in <module>
    import global_det_atmos_util as gda_util
  File "/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ush/global_det/global_det_atmos_util.py", line 7, in <module>
    import netCDF4 as netcdf
ModuleNotFoundError: No module named 'netCDF4'
```

After a quick look, I noticed that run.ver does not have a python version number added to it.  Maybe if you load the EVS VE into this?  I'm not sure I realized that python was removed from the run.ver file with the VE.

Perry

**Comment by PerryShafran-NOAA** [comment]
Or I need to use run.ver.metplus5.0.0.  Looks like you don't have the VE set up in the stats files either.

Perry

**Comment by malloryprow** [comment]
Oh shoot, no you're right. I may have submitted this before the run.ver changes. I'll update the script to use run.ver.metplus5.0.0. I have a different branch I'm working on the to the version upgrades.

**Comment by malloryprow** [comment]
Should be all good now

**Comment by PerryShafran-NOAA** [comment]
OK, help me understand what I'm seeing here.

I cut the run time of both the grid2obs and grid2grid gfs jobs to 30 minutes (from the original 1:15).  The grid2grid job is humming along, running METplus and such, but the grid2obs job seems to be very short.  Please see /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/global_det/stats/jevs_gfs_atmos_grid2obs_stats_00.o57571411.  It seems to be doing some restart thing but then the job ends, and "successfully", the output seems to suggest.

Perry

**Comment by malloryprow** [comment]
I'll take a look. Has the prep job been run too? Do you want me to take a look at anything from that?

**Comment by PerryShafran-NOAA** [comment]
You can look, if you think that will help.  I usually like to have people see the whole thing when prep, stats, and plots are all done, but this behavior intrigued me and I felt you should look now.

**Comment by malloryprow** [comment]
Where are the log files?

**Comment by malloryprow** [comment]
Exit statement was left in at https://github.com/malloryprow/EVS/blob/97cb451601034734c06e571a97a6f6e74c029363/scripts/global_det/stats/exevs_global_det_atmos_grid2obs_stats.sh#L54.

It has been removed and branch updated. Not sure how I let that slip in.

**Comment by PerryShafran-NOAA** [comment]
Oh!  I guess that's why that happened.  I'll bring in the updated code and do it again.

Thanks!

Perry

**Comment by malloryprow** [comment]
✔️ the prep output looks good; matches mine

**Comment by PerryShafran-NOAA** [comment]
Can you tell me where I should be able to find restart data?

**Comment by PerryShafran-NOAA** [comment]
Is it just that you have stat files listed here, and that is checked as part of the restart process?  :  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/atmos.20230508/gfs/grid2obs

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

I just completed the GFS grid2obs and grid2grid stats.  As I said previously, I originally cut the run time to 30 minutes so that the jobs would be killed before the job completed.  Then I reset the job time to its original 1:15 and ran a second time.

Looking at the directory and listing, you can see there were a lot of files written by 17:27.  At that point the job stopped and then I restarted later.  You can see the listing resumes at 19:08.  You can see that the final stat file was written at 19:18.

The directories are here:/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/atmos.20230508/gfs, grid2obs and grid2grid.

Final stat files:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/gfs.20230508

Please look!

Perry

**Comment by malloryprow** [comment]
There is no specific restart data. Everything builds upon each other so it is all restart data. The restart capabilities is just copying what (if anything) is in COM. The code checks if the output already exists and if it does no METplus job runs.

Timing sounds right though. If it ran 30 minutes and then was killed, then restarted and completed in 10 minutes. I'll check the output right now.

**Comment by malloryprow** [comment]
✔️ the stats output looks good

**Comment by PerryShafran-NOAA** [comment]
Is there a plots restart I should be testing as well?  Or are we done with this PR?

**Comment by malloryprow** [comment]
Plots need to be done as well

**Comment by malloryprow** [comment]
Let me know which ones you plan to run so I can also run them to make sure the output matches

**Comment by PerryShafran-NOAA** [comment]
Any recommendations on which to run?

**Comment by malloryprow** [comment]
Let's do jevs_global_det_atmos_grid2obs_pres_levs_plots_31days.ecf

**Comment by PerryShafran-NOAA** [comment]
OK, so this time I think it's best to link to your stats dir.

**Comment by malloryprow** [comment]
Yup!

**Comment by PerryShafran-NOAA** [comment]
OK, so I'm testing the 90 days one (90 days plots take longer than 31 days, I would think).  The requested time in that file is 4:30, so I'm making that time 1;30, so the script should be killed before it is finished.  Then I'll restart it for the full 4:30 and then see what happens.  

Perry

**Comment by malloryprow** [comment]
True, they do take longer. It might finish prior to 1:30. That was the old time from prior to when I did the rework in March.

**Comment by PerryShafran-NOAA** [comment]
Interesting.  Well, if I see a tar file after this run, I'll try again but with a 30-min wall clock request.  Think the job will finish in fewer than 30 minutes?

**Comment by malloryprow** [comment]
Nah, it is about an 90 minutes, so it might not or might barely finish with the walltime. Nail biter!

**Comment by PerryShafran-NOAA** [comment]
You're right, the job finished in 90 minutes, as I see the final tar file.  Darn.  I'm going to delete everything and then do a 30-minute run time to start.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Plots are done.

The log files are here:   /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/global_det/plots.  The earlier .o file is from the 30-minute run that died.  The 2nd one is the one that was restarted after the previous one died and the wall clock time increased.

The plot files are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230509.  The plot tar file is there; it was not there at the end of the 30-minute run.

Please take a look and let me know that all is ok, or you'd like more tests of more codes.

Perry

**Comment by malloryprow** [comment]
✔️ the plots tar file looks good

**Comment by PerryShafran-NOAA** [comment]
Are we good with the restart capabilities of the plots script?  Just making sure that not only does the plots tar file look good but the restart is good as well.  I guess, if the tar file is good, then the restart worked as expected.

One other thing I might recommend.  As you know, we're all worried about space issues.  Your process creates a directory, grid2obs_pres_levs, which I am guessing is used for the restart.  This directory is 23 GB.  I would guess that each of your plot processes would contain a similar directory.  Any way we can get this cleaned up by your scripts when the final tar file is created, so that we don't add several hundred GB to disk every day?

Thanks!

Perry

**Comment by malloryprow** [comment]
Yes that all looks good too.

I was told to keep this directory. But you can scrub the directory everyday. The plots don't need to stay around.

**Comment by AliciaBentley-NOAA** [comment]
Hi Perry and Mallory,

Yes, I also asked if the individual plots could be removed a few weeks ago,
but was reminded that we can't remove part of /com in ops (so it needs to
stay until the whole thing is scrubbed). Also, the images from the parallel
should eventually be the ones used to populate the GFS atmos verification
webpage, so deleting them right away might not be ideal. Maybe after 2
days?

Perry- can you please do a full size check of space used by this restart
test in /com for global_det atmos and let me know what you find? This would
be more accurate information for the kickoff meeting than what's currently
in the parallel. Thanks.

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
Hi, Alicia,

OK, I can run the full global_det_atmos suite to get these numbers.  

In the meantime, this PR works as expected, so I will go ahead and merge that in, while I run the suite to get the full numbers.  

Perry

**Comment by malloryprow** [comment]
I have a full suite of it sitting around. I can get the numbers.

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by AliciaBentley-NOAA** [comment]
Hi Mallory,

Thanks! In yesterday's Kickoff Planning meeting, Geoff said he needs 1) the
size of each component's /prep, /stats, and /plots directories for a given
day. He also needs 2) the size of the final .stat tar balls and the handful
of headline score plots for a given day (we'll add these up for an eventual
HPSS request).

Perry- Thanks for merging that!

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by malloryprow** [comment]
449G	atmos.20230419

Breakdown of what is in the directory:
1.6G	evs.plots.global_det.atmos.grid2grid_means.last31days.v20230419.tar
1.7G	evs.plots.global_det.atmos.grid2grid_means.last90days.v20230419.tar
1.3G	evs.plots.global_det.atmos.grid2grid_precip.last31days.v20230419.tar
1.4G	evs.plots.global_det.atmos.grid2grid_precip.last90days.v20230419.tar
1.7G	evs.plots.global_det.atmos.grid2grid_pres_levs.last31days.v20230419.tar
1.9G	evs.plots.global_det.atmos.grid2grid_pres_levs.last90days.v20230419.tar
30M	evs.plots.global_det.atmos.grid2grid_sea_ice.last31days.v20230419.tar
31M	evs.plots.global_det.atmos.grid2grid_sea_ice.last90days.v20230419.tar
635M	evs.plots.global_det.atmos.grid2grid_snow.last31days.v20230419.tar
710M	evs.plots.global_det.atmos.grid2grid_snow.last90days.v20230419.tar
13M	evs.plots.global_det.atmos.grid2grid_sst.last31days.v20230419.tar
14M	evs.plots.global_det.atmos.grid2grid_sst.last90days.v20230419.tar
13G	evs.plots.global_det.atmos.grid2obs_pres_levs.last31days.v20230419.tar
15G	evs.plots.global_det.atmos.grid2obs_pres_levs.last90days.v20230419.tar
231M	evs.plots.global_det.atmos.grid2obs_ptype.last31days.v20230419.tar
252M	evs.plots.global_det.atmos.grid2obs_ptype.last90days.v20230419.tar
79G	evs.plots.global_det.atmos.grid2obs_sfc.last31days.v20230419.tar
85G	evs.plots.global_det.atmos.grid2obs_sfc.last90days.v20230419.tar
4.1G	grid2grid_means
7.2G	grid2grid_precip
8.1G	grid2grid_pres_levs
76M	grid2grid_sea_ice
4.6G	grid2grid_snow
38M	grid2grid_sst
39G	grid2obs_pres_levs
609M	grid2obs_ptype
185G	grid2obs_sfc

**Comment by PerryShafran-NOAA** [comment]
These numbers are 248 GB (minus the tar files).  For clarification, is *only* these extra directories that I would want to delete right away - NOT the plot tar files, which are needed for plotting.  These restart directories should not be needed once the plot tar files are created.

Perry

**Comment by AliciaBentley-NOAA** [comment]
Hi Perry,

Yes, I asked about the same thing. Because the restart directories are
underneath /com, I'm told that we can't delete them until NCO scrubs
the whole /atmos.YYYYMMDD directory. Perhaps YOU can delete them in dev
with a scrubber to save us space after a few days, but we can't have them
deleted as part of the job itself, for example. They will stick around in
ops until that /com directory is scrubbed. Thanks.

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
Ah yes, true, we cannot do that in com.  In that case, I can do something for the noscrub space. 

Thanks!

Perry

**Pull request merged**
