### PR TITLE
Bugfix/subseasonal_fix_leadavg_error_and_timeseries_warning

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
Testing was done on command line for grid2obs 31 and 90-day plots; confirmed no ERROR or UserWarning.
This PR addresses the recently found nsamples error in lead average plots and marker UserWarning in time series plots.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Checkout feature branch and adjust paths as necessary.
Copy or link all stats files from parallel.
Run all plots jobs under dev/drivers/scripts/plots/subseasonal/.
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>
ASAP
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA I have cloned your fork and will begin work on this PR.

**Comment by PerryShafran-NOAA** [comment]
FYI - I am running using PDYm3 because these plot jobs failed yesterday, and I thought it would be a good test to compare plot jobs for the same day to see if they were successful with the new code.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Your jobs are fast!  They are all complete.

Please see the output files here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr364test/EVS/dev/drivers/scripts/plots/subseasonal
and the plot tarballs are here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/subseasonal/atmos.20231125

Please check all the .o files for any errors.  I also see that all plot tarballs have been created; hopefully they are of the proper size.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA I have gone through each of the output files and confirmed no ERROR nor UserWarning exist. The plot tar files seem the proper size to me and I did quickly look at some images to confirm all looks normal with markers, etc.
The only thing I am going to fix quick is to change "evs.plots.${COMPONENT}.${RUN}.${VERIF_CASE}_${VERIF_TYPE}.last${NDAYS}days.v${PDYm2}.tar
with
"evs.plots.${COMPONENT}.${RUN}.${VERIF_CASE}_${VERIF_TYPE}.last${NDAYS}days.v${end_date}.tar"
for the naming convention under SENDCOM in exevs scripts. I'll let you know when I have done that.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA Please re-run all plots jobs under dev/drivers/scripts/plots/subseasonal/ to confirm naming convention change.

**Comment by PerryShafran-NOAA** [comment]
Underway.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Runs are finished, please have a look, same directories.  Again, please be sure there are no errors or weird warnings.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA  Everything looks good to go! Please make sure PDYm2 is set in the code that is merging with the parallel.

**Comment by PerryShafran-NOAA** [comment]
Great!  No need to worry; only the code from your fork makes it to the parallel.  I don't upload anything from my own directories.  

Will check the code and then merge in.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected; ready to merge.

**Pull request merged**
