### PR TITLE
feature/global_det_atmos_fix_ccpa_map

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- Fix path issues causing the CCPA (QPE) spatial maps to not be generated
- Fix precip and NOHRSC spatial map restart
- Fix "perfdia" to "perfdiag" in image name

- [ ] Describe testing already performed for this Pull Request:</br>

> Tested and reviewed precip spatial map output

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> Checkout the branch
> /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_test_scripts/pr_160/run_evs_global_det_atmos_plots.sh. Run it. Let me know before you run. **_The needed files to create the spatial map plots from my stats directory start running at 1630 so this will need to run after that, maybe around 1700_**.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **7/18/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, @malloryprow.  Ready to test your PR, but your instructions say that you need to know before I run.  Let me know any further instructions before I start running, or let me know what I need to do to be OK to start running.

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA You're good to run! Just wanted to have you check with me before you ran it to make sure the files were available/jobs had already ran for the day.

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

The jobs are finished.  Please check the directory  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/dev/drivers/scripts/global_det/plots for the .o files.

I do not see any plot files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230716.  Both the plot jobs timed out.

Perry

**Comment by PerryShafran-NOAA** [comment]
I added 1 hr of wallclock time to each of your jobs and submitted again.

Perry

**Comment by PerryShafran-NOAA** [comment]
Looks like your jobs completed more quickly this time.  See the last two .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/dev/drivers/scripts/global_det/plots.  Also, the plot files are here:   /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230716

Thanks!

Perry

**Comment by malloryprow** [comment]
Dogwood was really overwhelmed yesterday (https://www2.nco.ncep.noaa.gov/pmb/spatools/HWM/DOGWOOD/live/p1.nid.nodes.html).

I see the tar files in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230716. The QPE/CCPA gif and png files are there. **This PR is good to go!** :heavy_check_mark:

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by PerryShafran-NOAA** [comment]
Everything looks good, and you already merged in develop after I completed the last PR.  Merging this one in now.

Perry

**Pull request merged**
