### PR TITLE
Bugfix/subseasonal cat logs and evs_ver change

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
Testing has been successfully done on the command line and/or cronjob.
This bugfix addresses the following:
Cat METplus and plotting log files in DATA
Add evs_ver lines to dev/drivers for a 2- to 3-digit evs version number change
Update HOMEevs definition in J-jobs
Add if statement in create_METplus_subseasonal_output_dirs.py so that the COMOUT/atmos restart directory is only created for grid-to-obs jobs. (This prevents empty grid2grid directories.)
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Checkout the feature branch and update paths accordingly.
Since this is the last major PR on the Project Plan list, let's run everything to be thorough.
So please run all scripts under dev/drivers/scripts/prep/subseasonal/.
Make sure you have 35 days worth of prep data linked from the parallel before running all scripts under dev/drivers/scripts/stats/subseasonal/.
Lastly, please run all scripts under dev/drivers/scripts/plots/subseasonal/ after making sure there are enough stat files.
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>
As soon as time allows
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, @ShannonShields-NOAA .  I am starting work on this PR now.  I have downloaded and am now starting the prep jobs.

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA While looking over your PR, I see that your redefine $evs_ver twice in your dev drivers. Please remove the second definition. You should use the 2-digit variable where you need the 2-digit version and the 3-digit variable where you need the 3-digit version. The two digit version should not be used outside the dev drivers. That is why there is no "export" in front of it. Thanks! 

Example from [dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_anom_plots_31days.sh](https://github.com/NOAA-EMC/EVS/pull/317/files#diff-00089d1adb02b83eee4c2001a40ce212139423bdb78e27ecd538c0a311053f92R47):
```
export evs_ver=v1.0.0
evs_ver_2d=$(echo $evs_ver | cut -d'.' -f1-2)
...
export evs_ver=${evs_ver_2d}
```

From EVS Project Plan (9/28–11/9): _"We checked, and compath.py is smart enough to take a 3-digit version number and convert it to a 2-digit version number in ops! That means that we can still use $evs_ver in our J-jobs (no changes are needed)."_

CCing @PerryShafran-NOAA and @ShelleyMelchior-NOAA

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA I edited my comment above about "export evs_ver" to add some clarification about compath.py. Please check out the updated comment when you can. Thanks!

**Comment by ShannonShields-NOAA** [comment]
@AliciaBentley-NOAA Ok, I will change that; I guess I am a bit confused about this version change. I see we are leaving ve_evs_ver=1.0 so is this ok? Also, when we do change evs_ver to 3 digits, are we going to leave "evs_ver_2d=$(echo $evs_ver | cut -d'.' -f1-2)" ? All of our COMIN and COMOUT paths are set with the 2-digit version so I assume so..?

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA The ve_evs_ver is the version number of the VE, not of EVS - that version number remains v1.0.  But because we have to turn in our package name as evs.v1.0.0 as required by NCO, we need to set evs_ver to be equal to v1.0.0.  But the output directories need to remain v1.0, also as required by NCO.  

That evs_ver_2d is basically only in your driver script, which is dev so NCO isn't going to care.  But when compath.py is used to create COMIN and COMOUT directories, that code automatically shortens v1.0.0 to v1.0 for those directories.  Thus, all we need to do is to set evs_ver=1.0.0 and do the evs_ver_2d to create your COMIN and COMOUT in the driver to overwrite the J-job definitions (which will be used in ops).  

Eventually, when everyone has done this, we'll set evs_ver in run.ver to v1.0.0, as it should be.

Does this make sense or make it more confusing?

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA You only need to make the additions that we included in the EVS Project Plan. These include:

1) Adding the following two lines after “source $HOMEevs/modulefiles/${COMPONENT}/${COMPONENT}_${STEP}.sh”.
```
export evs_ver=v1.0.0
evs_ver_2d=$(echo $evs_ver | cut -d'.' -f1-2)
```
2) Updating your COMIN and COMOUT paths in your dev drivers to use the 2-digit EVS version number:
```
export COMIN=/lfs/h2/emc/vpppg/noscrub/$USER/${NET}/${evs_ver_2d}
export COMOUT=/lfs/h2/emc/vpppg/noscrub/$USER/${NET}/${evs_ver_2d}
```
(Note: COMOUT is different in your plots scripts, but it should be updated to use ${evs_ver_2d} too.)  

The variable ve_evs_ver=1.0 in run.ver is the EVS **Virtual Environment (VE)** version number. This does not need to be three digits and should be left alone. Eventually, we will update evs_ver in run.ver (the EVS version number) to be the required three digits. The code managers will do this for us after everyone has updated their dev drivers to be able to handle this change.

Remember, compath.py is smart enough to take the 3-digit EVS version number from your dev drivers (and eventually from run.ver) and convert it to a 2-digit version number in ops! That means that we can still use a 3-digit $evs_ver in our J-jobs. No changes are needed there. Thanks!

@PerryShafran-NOAA @ShelleyMelchior-NOAA

**Comment by ShannonShields-NOAA** [comment]
@AliciaBentley-NOAA and @PerryShafran-NOAA Yes, thank you for the clarification; that answered my questions. It still seems a bit strange to me that the version number is not consistent with what is set in the COMIN/COMOUT directories, but I understand that NCO has its reasons and is picky about things. @PerryShafran-NOAA please hold off on any further testing until I tell you that I have finished these dev/drivers changes. Although simple, it will take a bit of time to go through all my drivers.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA I have made the changes described above; please re-checkout this branch and re-run the prep scripts when you get the chance.

**Comment by PerryShafran-NOAA** [comment]
Prep jobs are being run again with the new code.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA It looks like the prep jobs are done; the COMOUT files look good.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Good news!  Since this job is testing the cat'ting of the log files into your output, please look into the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr317test/EVS/dev/drivers/scripts/prep/subseasonal  Please check to see that all log files are printed out there.

In the meantime, I will go ahead and submit the stats jobs.

**Comment by ShannonShields-NOAA** [comment]
The prep jobs do not produce any other log files; that is only for stats and plots. So for this next round of stats testing, I will make sure to look for the cat messages.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA I finished checking all of the stats output files and everything looks good! The jobs are successfully cat'ing the METplus log files.

**Comment by PerryShafran-NOAA** [comment]
Great!  I don't even think I told you where to look ( /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr317test/EVS/dev/drivers/scripts/stats/subseasonal for the .o files), but you found them and examined them.  Also, since everything wound up in the correct directory, that means your changes to v1.0.0 were good as well.

I will be submitting the plot jobs soon.

Perry

**Comment by ShannonShields-NOAA** [comment]
Yes, I just went back from the prep output directory and confirmed that each of the .o stat files contained the cat log messages (looking for "Start:" and "End:").

**Comment by PerryShafran-NOAA** [comment]
Plot jobs are fast.

See the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr317test/EVS/dev/drivers/scripts/plots/subseasonal.  Please check for log files printed out in the output file.

The tarballs are here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/subseasonal/atmos.20231023

Thanks!

Perry

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA As you can see in my recent commits, I realized as I was following along with the jobs that I was missing "atmos.VDATE" in my log_dir where I tell the script to look for log files. I corrected this; please re-check out the branch and re-run the plots. Apologies for not noticing this before (I only tested stats in my working dir), but at least the plots do run fast.

**Comment by PerryShafran-NOAA** [comment]
New plot runs are underway.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA I can confirm that all .o files in /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr317test/EVS/dev/drivers/scripts/plots/subseasonal contain cat log messages and the correct evs_ver change. All tar files look correct in /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/subseasonal/atmos.20231023.
This should be ready for merging after a code review.

**Comment by PerryShafran-NOAA** [comment]
OK, great, let me do that code review.

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Pull request merged**
