### PR TITLE
bugfix/global_det_rev2

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

This PR addresses the following in [EVS v1.0 Issue](https://docs.google.com/document/d/1VYGABeEe2eXA1k5NFL5oavgMgiiTPyTKGWk-zWmsPdc/edit?pli=1):

- 76 WARNING in global_det_atmos_grid2obs_*_stats
- 77 WARNING in global_det_atmos_grid2grid_*_stats

Additional changes were put in to address WARNING messages found in the logs that were not specifically listed in the EVS v1.0 Issues document.

- [ ] Describe testing already performed for this Pull Request:</br>

> I ran the all global_det driver scripts and looked to see if the unneeded WARNING messages went away and the only ones that appeared are relevant.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **2/2/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
I have downloaded your PR and am starting with the prep scripts.

**Comment by PerryShafran-NOAA** [comment]
OK, I have submitted all the wave prep, stats, and plots jobs.  

You can follow along with the .o files in various directories here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr427test/EVS

**Comment by malloryprow** [comment]
wave prep is good! Output is what is expected and the log looks good.

wave stats is good! Output is what is expected and the log look good.

wave plots is good! The tar files have different sizes than /lfs/h1/ops/para/com/evs/v1.0/plots/global_det/wave.20240130, but COMIN was set to the emc.vpppg parallel for the tests. However, the file counts in the tar files are the same and what is expected. Log file shows the ncpus burst but that is being addressed in another PR.

**Comment by malloryprow** [comment]
To continue testing for atmos we will need to adjust the dates in the script, otherwise we need to wait until 1815Z.

In the atmos prep script, add `export INITDATE=20240129` in the driver script.
In the atmos stats scripts, add `export VDATE=20240129` in the driver scripts.
In the atmos plots scripts, change `export VDATE_END=$(finddate.sh $today d-1)` to `export VDATE_END=$(finddate.sh $today d-2)` in the driver scripts.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I had to do the wave stats job again, because I forgot to set the HOMEevs directory in that script.  Please check that when it's complete.  

The atmos prep job is underway.  

I am working on the stats jobs.  Did you know that you can do a qsub -v VDATE=20240129 when submitting the job?  That's what Marcel always suggests.  I'm going to try that.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA I sure did not but that is a heck of a lot easier than setting in the drivers! That's awesome!

**Comment by malloryprow** [comment]
@PerryShafran-NOAA In regards to rerunning the wave stats jobs, did the wave.20240130 and gfs.20240124 get cleared out? Otherwise restart would kick in.

**Comment by malloryprow** [comment]
atmos prep is good! Output is what is expected and the log looks good.

**Comment by PerryShafran-NOAA** [comment]
I removed the directories and started again, for wave stats.

**Comment by malloryprow** [comment]
> I removed the directories and started again, for wave stats.

Which log file is it? /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr427test/EVS/dev/drivers/scripts/stats/global_det/jevs_global_det_wave_gfs_grid2obs_stats_00.o131485175 or jevs_global_det_wave_gfs_grid2obs_stats_00.o131485730? I'm guessing the latter?

**Comment by PerryShafran-NOAA** [comment]
Rule of thumb:  always check the log file with the latest date.  So the latter, yes.

**Comment by malloryprow** [comment]
jevs_global_det_wave_gfs_grid2obs_stats_00.o131485730

> /var/spool/pbs/mom_priv/jobs/131485730.dbqs01.SC: line 55: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr427test/pr427test/EVS/jobs/JEVS_GLOBAL_DET_STATS: No such file or directory

**Comment by PerryShafran-NOAA** [comment]
Thanks!  Fixed all that, refilled the atmos.20240125 prep directory, and re-submitted all the stats jobs, including the wave stats job.

**Comment by malloryprow** [comment]
Re-run of wave stats is still good!

**Comment by malloryprow** [comment]
This was a good test for global_det atmos stats (even if we didn't plan it)! Restart kicked in for the second run of global_det atmos. Some of the new code I added broke in the restart. Let me fix these scripts. I'll let you know when everything is good to re-run!

**Comment by PerryShafran-NOAA** [comment]
OK, I'll have to delete some files before we run these again.

**Comment by malloryprow** [comment]
Okay! The fix is in!

**Comment by PerryShafran-NOAA** [comment]
OK.  I have the COMOUT directories cleared and the jobs restarted.

**Comment by PerryShafran-NOAA** [comment]
Everything looks done but the longer jobs, if you want to have a look at the most recent .o files.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I submitted all the atmos plots drivers.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow All stats jobs are finished, and there are three plots jobs that remain.  

Do you need a test on a stats driver to test your restart fix?  Just let me know.

**Comment by malloryprow** [comment]
The stats for cmc_regional grid2grid, fnmoc grid2obs, and imd grid2grid weren't run, but it is okay.

atmos stats is fine. The output looks good, and the WARNING messages are fine with what NCO would want to see.

**Comment by malloryprow** [comment]
> @malloryprow All stats jobs are finished, and there are three plots jobs that remain.
> 
> Do you need a test on a stats driver to test your restart fix? Just let me know.

Let's do jevs_global_det_atmos_jma_grid2obs_stats.sh.

**Comment by PerryShafran-NOAA** [comment]
I missed some stats jobs?  Whoops, that was not meant to be done.  Let me know if you need me to run those.

I'll run the jma job to get the restart test in.

**Comment by malloryprow** [comment]
It's okay, I don't think we need to. Re-run of the jma grid2obs stats job looks good. I'll look at the atmos plots now.

**Comment by malloryprow** [comment]
atmos plots looks fine. Tar sizes look about right and nothing glaring in the log files.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Feels like we've checked all of the boxes above, yes?  Let me know if there is anything outstanding, otherwise maybe we can merge this one?

**Comment by malloryprow** [comment]
Nothing from me, I'm good with merging!

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
