### PR TITLE
Bugfix/mesoscale plotting memory issue

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

This PR fixes the RAM exceedence issue for the mesoscale precip plotting job.  The mesoscale precip plotting job was tested for successful completion and for substantial reduction in RAM load.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Two jobs should be run to test this PR.  They can be run interactively (`qsub {driver_script}`) or in the cron.  Below are the driver scripts that should be submitted:
```
{HOMEevs}/dev/drivers/scripts/mesoscale/plots/jevs_mesoscale_precip_plots.sh
{HOMEevs}/dev/drivers/scripts/mesoscale/plots/jevs_mesoscale_snowfall_plots.sh
```

These can run at any time of day.

For testing, make sure "COMIN" points to the emc.vpppg stats directory (`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/...`), and edit other developer settings as needed (HOMEevs, COMOUT, DATA, ...).

- [x] Has the code been checked to ensure that no errors occur during the execution? **[Yes]**

- [x] Do these updates/additions include sufficient testing updates? **[Yes]**

- [x] Please complete this pull request review by **[08/30/2023]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@MarcelCaron-NOAA , I have cloned your fork and checked out branch `bugfix/mesoscale_plotting_memory_issue`. Please go ahead and run sync fork to bring in the changes in develop since submitting the PR.

**Comment by ShelleyMelchior-NOAA** [comment]
The plots processing is underway.
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/mesoscale`
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_precip_plots.o77704050`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_snowfall_plots.o77704129`

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA Thank you.  This branch should be up to date now.

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA I just checked and both precip and snowfall jobs completed cleanly in that there were no failures due to memory overage.  Output files look normal.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All changes produced expected results. The PR is approved for merge.

**Pull request merged**
