### PR TITLE
feature/global_det_atmos_rework_plots

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

Add rework and optimization of global_det atmos plots

- [ ] Describe testing already performed for this Pull Request:</br>

> ecf scripts were submitted to be run and tested. Plots are displayed at https://emc.ncep.noaa.gov/users/verification/global/gfs/atmos/para/.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> Checkout the branch
> Be sure to update the COM related paths so they don't overwrite the parallel's output
>Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_78/evs_global_det_atmos_set_up.sh. Open and set EVSclone to where the clone is. This script will link the fix files and clear out the user's stats/global_det directory and the link to my stats/global_det directory since my directory has more data in it.
>Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_78/run_evs_global_det_atmos_plots.sh . Open and set EVSclone to where the clone is. This script will submit the ecf scripts to run the plotting jobs.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **4/1/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
Hi Perry. Mallory has reworked and optimized her global_det plotting code.
We would like her updated plotting code to be included in the EVSv1
parallel in order to get a better estimate of resources for the upcoming
HPCRAC request. Please include this PR in the parallel as soon as possible.
Thank you!

___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
The plot jobs are currently running.  

Perry

**Comment by AliciaBentley-NOAA** [comment]
Hi Perry. I'm a little confused and wanted to clarify. Do you mean that
Mallory's old plotting jobs are currently running in the EVSv1 parallel?
Once the old plotting jobs are finished running, please use this PR to
replace her old plotting jobs with these reworked/updated plotting jobs. If
you mean that the new plotting jobs from this PR are currently running, I
think that they should go through the standard PR process to bring them
into the EVSv1 parallel formally. Thanks!

___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
I am currently running the jobs as any other PR - on my own account and not in the parallel on the group account.  They will not be integrated in the parallel until we go through the PR process to approve these code changes.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

The plot jobs have completed.  Interestingly I am seeing a few errors.  For example, here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/global_det/plots/jevs_global_det_atmos_grid2obs_ptype_plots_31days_00.o51168664, I am seeing the following:

```
=>> PBS: job killed: walltime 345 exceeded limit 300
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source             
cfp                000000000041593B  for__signal_handl     Unknown  Unknown
libpthread-2.31.s  0000149AE7B468C0  Unknown               Unknown  Unknown
libc-2.31.so       0000149AE781C76D  wait4                 Unknown  Unknown
libc-2.31.so       0000149AE7793BC7  Unknown               Unknown  Unknown
cfp                000000000040C761  system_               Unknown  Unknown
cfp                000000000040BBE3  Unknown               Unknown  Unknown
cfp                000000000040AC52  Unknown               Unknown  Unknown
libc-2.31.so       0000149AE77702BD  __libc_start_main     Unknown  Unknown
cfp                000000000040AB6A  Unknown               Unknown  Unknown
```

I am also seeing SIGTERMs in the following files:

jevs_global_det_atmos_grid2grid_means_plots_31days_00.o51168658
jevs_global_det_atmos_grid2grid_means_plots_90days_00.o51168659
jevs_global_det_atmos_grid2grid_sea_ice_plots_31days_00.o51168656
jevs_global_det_atmos_grid2grid_snow_plots_31days_00.o51168652
jevs_global_det_atmos_grid2grid_snow_plots_90days_00.o51168653
jevs_global_det_atmos_grid2grid_sst_plots_31days_00.o51168654

There are plot tar files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230322

I guess the timings worked in some cases but caused problems for others?  Can we look into this?

Perry

**Comment by malloryprow** [comment]
I think it is due to the production switch. When we all get access again, we overload the system and the module loads take a painfully long time, and it causes the wall time to be reached. It might perhaps impact other processes. I was seeing some of my jobs take a longer time to run than usual because of this.

I realized though in the testing script I passed you the I didn't update where to link my stats directory to. It is updated now though. Can you recopy my testing scripts and run them again?

**Comment by PerryShafran-NOAA** [comment]
Will do!

Perry

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Still getting SIGTERMs, but for a smaller number of scripts:

jevs_global_det_atmos_grid2grid_precip_plots_90days_00.o51180184
jevs_global_det_atmos_grid2grid_snow_plots_31days_00.o51180185
jevs_global_det_atmos_grid2obs_ptype_plots_31days_00.o51180217

Perry

**Comment by malloryprow** [comment]
Try rerunning again. Or we can look at increasing the walltime, or try tomorrow when Cactus was stabilized out.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA I'm doing some testing today for this. I'm looking at decreasing resources how that impacts the run time.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Adjustments made. Feel free to test again.

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

Are we good to give this another test?  Or are there more fixes to be made?

Perry

**Comment by malloryprow** [comment]
I need to make some minor adjustments to the ecf scripts this morining. Also waiting for @GeoffManikin-NOAA  to confirm fixing the axis limits for FBIAS for the Snowfall verification.

**Comment by PerryShafran-NOAA** [comment]
OK, great, I'll wait for the official thumbs up to test before I do anything.

Thanks!

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA :thumbsup: Good to go! Though I have been trying to run the scripts so I could compare your output to mine and I was noticing that the "module load" statements were taking a very long time to load. It was taking 10 minutes to just load all the modules earlier.

**Comment by malloryprow** [comment]
Things seem like the are running better right now

**Comment by malloryprow** [comment]
@PerryShafran-NOAA I have run my plot jobs for today, so if you can run them for today I can compare my output and your output.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Were you able to run the jobs yesterday?

**Comment by PerryShafran-NOAA** [comment]
Yes, I ran jobs late yesterday, and they ended after I got off work.

Perry

**Comment by malloryprow** [comment]
Sweet, where are the tar files and log files?

**Comment by PerryShafran-NOAA** [comment]
Log files:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_mallory_timingtests/ecf/global_det/plots
Plots: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230402

**Comment by malloryprow** [comment]
It looks like 3 tar files are missing: evs.plots.global_det.atmos.grid2obs_pres_levs.last31days.v20230402.tar, evs.plots.global_det.atmos.grid2obs_sfc.last31days.v20230402.tar, and evs.plots.global_det.atmos.grid2obs_sfc.last90days.v20230402.tar. I would expect the tar sizes to be identical to mine as well since you liked to my stats directory, but they are not.

I'm guessing your clone of my branch is at /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_mallory_timingtests? Looking at the log files, HOMEevs is being set to /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS, so it isn't running the right scripts for this pull request.

Either my branch will need to be moved to /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS, or you can go through the ecf scripts and set HOMEevs appropriately.

**Comment by PerryShafran-NOAA** [comment]
OK, let me check on that and re-run.  I'll let you know later today.

**Comment by malloryprow** [comment]
Cactus is running incredibly slow right now...so the jobs you are running right now a lot of them will probably time out

**Comment by malloryprow** [comment]
Okay, Cactus seems to be running A LOT better now. My jobs are running at normal speed. Can you resubmit the jobs?

**Comment by PerryShafran-NOAA** [comment]
Yup, thanks!  They are underway.

**Comment by PerryShafran-NOAA** [comment]
Apparently Cactus remains slow as there are still some jobs that are ending before completion.  Some jobs that should take 5 minutes to run are taking the full 15 allotted, and that is due to a problem in the system.  Will continue to figure this out.

**Comment by malloryprow** [comment]
The window were Cactus was normal was nice while it lasted :(

**Comment by AliciaBentley-NOAA** [comment]
Ugh, so frustrating. Thanks for working on this, both of you! Sorry about
the computer issues.
___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by malloryprow** [comment]
I was able to get some jobs that timed out earlier run right now.

**Comment by PerryShafran-NOAA** [comment]
I'm still getting some runs that hit the wall clock limit before completing.  Hopefully Cactus will be back to normal by tomorrow.

**Comment by malloryprow** [comment]
> jevs_global_det_atmos_grid2grid_means_plots_31days_00.o52401091:=>> PBS: job killed: walltime 906 exceeded limit 900
> jevs_global_det_atmos_grid2grid_means_plots_90days_00.o52401092:=>> PBS: job killed: walltime 1207 exceeded limit 1200
> jevs_global_det_atmos_grid2grid_snow_plots_31days_00.o52401085:=>> PBS: job killed: walltime 910 exceeded limit 900
> jevs_global_det_atmos_grid2grid_snow_plots_90days_00.o52401086:=>> PBS: job killed: walltime 1211 exceeded limit 1200
> jevs_global_det_atmos_grid2obs_ptype_plots_31days_00.o52401097:=>> PBS: job killed: walltime 904 exceeded limit 900
> jevs_global_det_atmos_grid2obs_ptype_plots_90days_00.o52401098:=>> PBS: job killed: walltime 910 exceeded limit 900

Cactus is going to be the death of me

**Comment by AliciaBentley-NOAA** [comment]
UGHHHHHH.

___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
Computer is running normally now, so submitted another run of these jobs.

**Comment by PerryShafran-NOAA** [comment]
Interestingly, I am *still* getting a few SIGTERMs from some of the runs.  See /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/global_det/plots.  Are you seeing your 15-minute runs finish before the time allotted?

Perry

**Comment by malloryprow** [comment]
Yeah started seeing things slow down again. I alerted NCO on Slack I was seeing a slow down again, and they said they identified another user causing problems. They said is wasn't me, but I asked them to elaborate on if the problem is with python _what_ exactly the issue is so I can make sure to avoid it.

**Comment by malloryprow** [comment]
Slack Thread: https://ncep-wcoss.slack.com/archives/C02CMG808G7/p1680700607478599

**Comment by malloryprow** [comment]
Though everything that has run successfully so far in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230404 is looking identical to what I have :) some good news!

**Comment by AliciaBentley-NOAA** [comment]
Hi Mallory,

That is some good news! And I just read the Slack thread. I wonder if a
specific node was taken down by a user and you happened to be on that node?
Unsure. I wonder what the issue was/is so that we can avoid it!

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
That's good!  But I'll have to restart at least the 15-minute jobs, which is basically means, snow, and ptype runs.  I'll submit those again.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Looks like the 15-minute jobs are still ending at 15 minutes before finishing.  Think it's time to adjust these to longer?  It still seems to be taking a great deal of time doing the module loads.

**Comment by malloryprow** [comment]
They shouldn't need adjusting if Cactus is running normally. You can adjust them if you need for testing.

**Comment by PerryShafran-NOAA** [comment]
I guess Cactus is still not running normally - especially if "normalcy" comes and goes.  This seems to be a continuing problem.

**Comment by AliciaBentley-NOAA** [comment]
Hi all. I would support adjusting to longer runtimes so that these jobs can
successfully finish in order to test the PR's functionality. Do you agree?

___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by malloryprow** [comment]
Sure! When I had to do this, I added an hour to the walltime and things finally ran to completion.

**Comment by PerryShafran-NOAA** [comment]
I can do that.

**Comment by PerryShafran-NOAA** [comment]
I added an hour to the wall clock run times and resubmitted the ptype, means, and snow jobs.  Let's see if that works.

Perry

**Comment by malloryprow** [comment]
Looks like everything is in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230404 and ran my checking script to make sure the tar files are the same size and they are!!

**Comment by AliciaBentley-NOAA** [comment]
ARE WE GOOD?!?! 😂

___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by malloryprow** [comment]
Yes! Let's approve this thing and get on with our lives!

**Comment by PerryShafran-NOAA** [comment]
Just to note - the run times in the code that I used to get a successful run are not the run times that were set for this PR.  I thought the purpose of this is to get a good set of run times for optimization.  Thus, if we are good with this, I can approve and merge.

Perry

**Comment by AliciaBentley-NOAA** [comment]
Hi Perry. Understood. The long run times are not you or Mallory's fault.
When Cactus is working correctly, we know that it runs faster than this!
Please merge it as is so that Mallory can continue to work on optimizing
her code run times with this as a baseline. We'll get a better assessment
soon. Thank you!

___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by malloryprow** [comment]
Yes, what @AliciaBentley-NOAA said. The run times have been significantly reduced for the grid-to-obs pres_levs and sfc jobs. These use to take multiple hours, but now are down to about an hour or hour and a half.

**Comment by PerryShafran-NOAA** [comment]
Excellent, works for me!  I will approve and merge.

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
