### PR TITLE
Bugfix/correct subseasonal OSI and GHRSST averaging

### LINKED ISSUE #548: subseasonal: Fix file checking for weekly and monthly average files
There were two failures in operations on 9/16/2024 in the subseasonal grid2grid stats jobs (both gefs and cfs). The failure happened in weekly_osi_saf_file in ush/subseasonal/subseasonal_util.py. Things are getting crossed as the same list that is being looped over to check files and is the same that is removing items for when files don't exist. Some files are not actually being checked for their existence.

In addition to weekly_osi_saf, this style of file checking is happening in monthly_osi_saf_file, weekly_ghrsst_ospo_file, and monthly_ghrsst_ospo_file.

- [x] Create `release/evs.v1.0.12` and make changes (#549)
- [x] Create EVS.v1.0.12 tag from `release/evs.v1.0.12`
- [x] Bring changes from `release/evs.v1.0.12` into para
- [x] Bring changes from `release/evs.v1.0.12` into develop

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

> Please include a summary of the changes and the related GitHub issue(s). Please also include relevant motivation and context.
The ush/subseasonal/subseasonal_util.py script was edited to fix an ops issue/failure related to weekly and monthly OSI-SAF and GHRSST-OSPO averaging. Issue #548.
## Developer Questions and Checklist
* Is this a high priorty PR? If so, why and is there a date it needs to be merged by?
* Yes, as grid-to-grid jobs will continue to fail without this bugfix. ASAP.
* Do you have any planned upcoming annual leave/PTO?
* No
* Are there any changes needed for when the jobs are supposed to run?
* No
  
- [ ] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [ ] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [ ] References the feature branch for `HOMEevs` are removed from the code.
- [ ] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [ ] Jobs over 15 minutes in runtime have restart capability.
- [ ] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [ ] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [ ] Code is using METplus wrappers structure and not calling MET executables directly.
- [ ] Log is free of any ERRORs or WARNINGs.

## Testing Instructions

> Please include testing instructions for the PR assignee. Include all relevant input datasets needed to run the tests.
Clone my fork and checkout branch bugfix/subseasonal_osi_ghrsst_avg
ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix (link EVS_fix dir)
cd dev/drivers/scripts/stats/subseasonal
For the following: jevs_subseasonal_cfs_grid2grid_stats.sh, jevs_subseasonal_gefs_grid2grid_stats.sh:
Set HOMEevs to the location of the clone.
Set COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v2.0/prep/subseasonal/atmos
Run jobs

### CODE REVIEW

**Review by AliciaBentley-NOAA — APPROVED** [review]
I have reviewed this PR and found that it includes the same changes to `subseasonal_util.py` that we need in develop to prevent future operational failures (previous PR was merged into the EVS v1.0.12 release). I approve this PR to be merged into develop once testing of weekly and monthly jobs proves that it is working correctly. Thanks!

CC @malloryprow @ShannonShields-NOAA @PerryShafran-NOAA

**Comment by malloryprow** [comment]
Small and unrelated thing: in dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.sh can we get the purpose code at the end of the script all lined up?

**Comment by ShannonShields-NOAA** [comment]
@malloryprow Yes, done! Sorry, not sure what happened there.

**Comment by malloryprow** [comment]
### jevs_subseasonal_cfs_grid2grid_stats.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr563/EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_cfs_grid2grid_stats.o155513161
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr563/evs/v2.0/stats/subseasonal
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_cfs_grid2grid_stats.155513161.cbqs01

### jevs_subseasonal_gefs_grid2grid_stats.sh
**Log File:**  /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr563/EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.o155513453
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr563/evs/v2.0/stats/subseasonal
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_gefs_grid2grid_stats.155513453.cbqs01

One weird thing is I don't see a COMOUTsmall directory.

**Comment by ShannonShields-NOAA** [comment]
COMOUTsmall is in JEVS_SUBSEASONAL_STATS.

**Comment by malloryprow** [comment]
Sorry. I mean I see COMOUTsmall being set in both log files, but no output there. The directories do not exist.

> grep "export COMOUTsmall=" *.o*
>
> jevs_subseasonal_cfs_grid2grid_stats.o155513161:0 + export COMOUTsmall=/lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr563/evs/v2.0/stats/subseasonal/atmos.20240916/cfs/grid2grid
> jevs_subseasonal_gefs_grid2grid_stats.o155513453:0 + export COMOUTsmall=/lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr563/evs/v2.0/stats/subseasonal/atmos.20240916/gefs/grid2grid

>  ls /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr563/evs/v2.0/stats/subseasonal/atmos.20240916/cfs/grid2grid
> ls: cannot access '/lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr563/evs/v2.0/stats/subseasonal/atmos.20240916/cfs/grid2grid': No such file or directory

> ls /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr563/evs/v2.0/stats/subseasonal/atmos.20240916/gefs/grid2grid
> ls: cannot access '/lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr563/evs/v2.0/stats/subseasonal/atmos.20240916/gefs/grid2grid': No such file or directory
> 

Is that expected?

**Comment by ShannonShields-NOAA** [comment]
Ah, my apologies @malloryprow. Currently, the G2G jobs do not need those restart directories so NCO said I couldn't have an empty atmos directory so the code does not create those in the first place.

**Comment by ShannonShields-NOAA** [comment]
(But I still needed to list them in the J-jobs and will be needed in the future)

**Comment by malloryprow** [comment]
Oh got it! Okay I wasn't sure if I missed something in my testing set-up. Thanks for confirming. How are the final stat files looking?

**Comment by ShannonShields-NOAA** [comment]
@malloryprow I can confirm that the final stat files look as expected and there are no ERRORs, only the expected WARNINGs related to the missing OSI-SAF data. All should be set to merge!

**Review by malloryprow — APPROVED** [review]

**Comment by malloryprow** [comment]
Thanks for the quick fixes, Shannon!

**Comment by ShannonShields-NOAA** [comment]
Thank you for finding the fix solutions in the first place! I greatly appreciate it.

**Pull request merged**
