### PR TITLE
Bugfix/href spcoutlook file check

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

This PR addresses issue 50 noted in the Google Doc titled "EVS v1.0 issues".  Information about its cause and fix:

* 50 - A recent fix for this issue included a more explicit check for SPC outlook mask files, where the job exits if there are no masks available to use for verification.  This fix was tested with the setting SENDMAIL=yes, for which the job exits with a mail message and completes successfully in cases where no masks are available.  However, when SENDMAIL=no, the code skips the exit and continues running METplus verification, which fails. _Fix:_ Move the exit statement outside of the section of code that runs if SENDMAIL=yes.

The affected job was tested by myself and the NCO correspondent, and it ran successfully in both tests.

---
- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

### (1) Set up jobs 
•	symlink the EVS_fix directory locally as "fix"
•	In the driver script, point "HOMEevs" to your EVS test directory
•	In the driver script, change COMIN to the parallel directory (`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`)

### (2) Test Jobs
Use the following to submit: `qsub –v vhr=00 `

From your EVS testing directory, the following script should be run using the setup in step (1):
```
dev/drivers/scripts/stats/cam/jevs_cam_href_spcoutlook_stats.sh
```

_[Total: 1 stats job]_

### (3) Review
- I'll check for red flags:
```
check="FATAL\|WARNING\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|empty\|failed\|unexpected\|exceeded"
grep "$check" $outfile
```
- I'll also verify that the corresponding issue in the EVSv1.0 issue doc no longer exists

---
- [x] Has the code been checked to ensure that no errors occur during the execution? **YES**

---
- [x] Do these updates/additions include sufficient testing updates? **YES**

---
- [x] Please complete this pull request review by **ASAP**.</br>

---
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks, Marcel! I cloned your repo and checked out branch `bugfix/href_spcoutlook_file_check`.

**Comment by ShelleyMelchior-NOAA** [comment]
The job has been submitted. 
```
131664602.dbqs01               shelley.melchi* dev             jevs_cam_href_*   152878    1     4  100gb 01:00 R 00:02
```
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_href_spcoutlook_stats.o131664602`

**Comment by ShelleyMelchior-NOAA** [comment]
It's done! I ran your grep command. One WARNING recurs, one that we are already aware of (item 49, deferred as Bugzilla till we can get help from DTC in METplus).
```
[dlogin05 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ check="FATAL\|WARNING\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|empty\|failed\|unexpected\|exceeded"
[dlogin05 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ grep "$check" jevs_cam_href_spcoutlook_stats.o131664602
WARNING: 
WARNING: PointStatVxOpt::process_config() -> The range of requested observation pressure levels is not contained within the range of requested forecast pressure levels.  No vertical interpolation will be performed for observations falling outside the range of forecast levels.  Instead, they will be matched to the single nearest forecast level.
```

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA Great--yes I agree it looks good.  The only remaining warning will be covered by the bugzilla item you mentioned, so I agree it is acceptable here.

Otherwise, output are comparable to that of the parallel run.

👍 No further concerns from me.

**Comment by AliciaBentley-NOAA** [comment]
The file changed looks good and does what Wei needed. I approve this PR for merge and inclusion in today's EVS v1.0.4 tag! @MarcelCaron-NOAA @ShelleyMelchior-NOAA

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Test yields expected results. This PR is approved for merge.

**Pull request merged**
