### PR TITLE
feature/rtofs_rm_jlogfile

### PR DESCRIPTION
**Pull request by malloryprow**
1. Remove incorrectly formatted postmsg commands from J-Jobs

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
> I did not do any testing

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
**Set-up**
> 1. Clone my fork and checkout branch feature/rtofs_rm_jlogfile
> 2. cd sorc
> 3. ./build-fix-link.sh

**prep**
> 4. Run dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.sh

**stats**
> 5. Run dev/drivers/scripts/stats/rtofs/jevs_rtofs_aviso_stats.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vppg/$NET/${evs_ver_2d}.

**plots**
> 6. Run dev/drivers/scripts/plots/rtofs/jevs_rtofs_headline_grid2grid_last90days_plots.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/${evs_ver_2d}.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **No**

- [ ] Do these updates/additions include sufficient testing updates? **No**

- [ ] Please complete this pull request review by **11/09/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Beginning work on this PR, starting with the prep step.

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow @PerryShafran-NOAA I have looked over the jlogfile changes in this RTOFS PR and think that it looks good! I approve this for merge after all testing is completed! Thanks!

**Comment by PerryShafran-NOAA** [comment]
The rtofs prep step is done.  Please check out the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr330test/EVS/dev/drivers/scripts/prep/rtofs

and the prep files here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs

**Comment by malloryprow** [comment]
:heavy_check_mark: **prep is good!**

File count is what is expected and no "postmsg" or "jlogfile" instances in the log.

**Comment by PerryShafran-NOAA** [comment]
Great! Moving on to stats.  aviso only, per your instructions.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow You should be able to look at the stats output.  

The .o file: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr330test/EVS/dev/drivers/scripts/stats/rtofs
The stats output:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs

**Comment by malloryprow** [comment]
Log file looks good! I forgot that the rtofs stats jobs don't run until 2200Z, I think it is?? But I think it looks good. There are 298 lines in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs/rtofs.20231030/evs.stats.rtofs.aviso.grid2grid_ssh.v20231030.stat and /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/rtofs/rtofs.20231029/evs.stats.rtofs.aviso.grid2grid_ssh.v20231029.stat had 298 as well.

**Comment by PerryShafran-NOAA** [comment]
I don't remember which file was needed at 2200Z, but apparently aviso isn't one of them.  

Let's go on to the plots step!

**Comment by PerryShafran-NOAA** [comment]
Plots is complete.

See the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr330test/EVS/dev/drivers/scripts/plots/rtofs

and the plot tarball here: /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/rtofs/headline.20231029

**Comment by malloryprow** [comment]
:heavy_check_mark: **plots is good!**

Tar file size matches the parallel run and no "postmsg" or "jlogfile" found in the log.

Good to merge!

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Pull request merged**
