### PR TITLE
feature/rtofs_reorg

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

1. Reorganize dev, parm, and script directories
2. Set COMOUT to ptmp for plots
3. Add SENDMAIL to job/JEVS_RTOFS_PLOTS
4. Remove "exit 0" statments

- [ ] Describe testing already performed for this Pull Request:</br>

> I compared the file counts for the prep step to the emc.vpppg parallel; file counts matched. I ran the stats jobs for 20230918 in the emc.vpppg parallel and the jobs where the observation dataset was still available the stat files were the same. I tested the plots jobs using the emc.vpppg parallel as input and the tar files were the same.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

**Set-up**
> 1. Clone my fork and checkout branch feature/rtofs_reorg
> 2. cd sorc; ./build-fix-link.sh

**prep**
> 3. Run dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.sh

**stats**
> 4. Run dev/drivers/scripts/stats/rtofs/jevs_rtofs_osisaf_stats.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vppg/$NET/${evs_ver} and COMINfcst to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/${evs_ver}/prep/$COMPONENT.

**plots**
> 5. Run dev/drivers/scripts/plots/rtofs/jevs_rtofs_argo_grid2obs_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_aviso_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_ghrsst_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_headline_grid2grid_last90days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_ndbc_grid2obs_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_osisaf_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_smap_grid2grid_last60days_plots.sh, and dev/drivers/scripts/plots/rtofs/jevs_rtofs_smos_grid2grid_last60days_plots.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/${evs_ver}.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **10/13/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Beginning work on your PR now.  Started the prep job.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow OK, the prep job finally completed.  

Here is the output file:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr291test/EVS/dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.o84015629

And all the output is here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs.  Please check all the dates that the prep file writes out.

Thanks!

Perry

**Comment by malloryprow** [comment]
find /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs/rtofs.20231008 -type f | wc -l
272

find /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/rtofs/rtofs.20231008 -type f | wc -l
88

/lfs/h2/emc/ptmp/emc.vpppg/output/jevs_rtofs_prep.o83989899 shows the walltime was hit, but the file counts for /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs/rtofs.20231008 are what I would expect.

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs/rtofs.2023100[4-7] all have 0 file counts. This would be because you wouldn't have been running them every day to fill the directories with the original RTOFS so when the prep step goes back to those dates there are no files there.

**Comment by PerryShafran-NOAA** [comment]
OK - should I copy several days' worth of rtofs prep files into the perry.shafran directory and re-try?  (Also I'm curious how long the wall time is being hit for rtofs and if I need to re-run prep for several days.)

**Comment by malloryprow** [comment]
Looks like it has happened the past few days. I will increase the wall time in the dev/driver/scripts.

**Comment by PerryShafran-NOAA** [comment]
Would you like me to run prep again or continue on with stats?

**Comment by malloryprow** [comment]
I'm fine with continuing to the stats. The stats job in the emc.vpppg parallel doesn't run until 2200. Do you want to wait to run it then, or run a different VDATE?

**Comment by PerryShafran-NOAA** [comment]
Right now, I am working on backfilling prep data, which I think is vital to working on this PR.  But this will take a bit of time I think.  Or I can go back to VDATE=20231005, which I think would be OK for prep data.  What are your thoughts?

**Comment by malloryprow** [comment]
I think VDATE=20231005 would be fine. /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/rtofs/rtofs.20231005/evs.stats.rtofs.osisaf.grid2grid_sic.v20231005.stat exists. If you point the COMIN variables to the emc.vpppg parallel we should be good.

**Comment by PerryShafran-NOAA** [comment]
OK will do.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I have an issue.  I set COMIN and COMINfcst to be set to emc.vpppg, but yet:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr291test/EVS/dev/drivers/scripts/stats/rtofs/jevs_rtofs_osisaf_stats.o84025208:


```
10/10 17:49:30.889 metplus (command_builder.py:257) ERROR: (command_builder.py:656) Could not find FCST_INPUT file /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs/rtofs.20230930/osisaf/rtofs_glo_2ds_f120_ice.osisaf.nc using template rtofs.{init?fmt=%Y%m%d}/osisaf/rtofs_glo_2ds_f{lead?fmt=%3H}_ice.osisaf.nc
10/10 17:49:30.889 metplus INFO: Processing forecast lead 6 days
10/10 17:49:30.890 metplus (command_builder.py:591) DEBUG: Looking for FCST_INPUT file /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs/rtofs.20230929/osisaf/rtofs_glo_2ds_f144_ice.osisaf.nc
10/10 17:49:30.892 metplus (command_builder.py:257) ERROR: (command_builder.py:656) Could not find FCST_INPUT file /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs/rtofs.20230929/osisaf/rtofs_glo_2ds_f144_ice.osisaf.nc using template rtofs.{init?fmt=%Y%m%d}/osisaf/rtofs_glo_2ds_f{lead?fmt=%3H}_ice.osisaf.nc
```

Why is this looking in perry.shafran for these files?  

Perry

**Comment by malloryprow** [comment]
Hmmmm, not sure I figured that would have done the trick.

**Comment by malloryprow** [comment]
Well...looks like despite those being set input directories get set with COMOUT.https://github.com/NOAA-EMC/EVS/blob/0a6e29e7cef00674707437eaf40d382bdc16dfdf/parm/metplus_config/rtofs/grid2grid/stats/GridStat_fcstRTOFS_obsOSISAF_nh.conf#L179

**Comment by malloryprow** [comment]
Perhaps this may be worthwhile to do...

1. Clear out /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs
2. Copy or link /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/rtofs/rtofs.20230929, /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/rtofs/rtofs.20230930, /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/rtofs/rtofs.2023100[1-7] to /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs.
3. Run dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.sh (this will generate /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs/rtofs.20231008).
4. Run dev/drivers/scripts/stats/rtofs/jevs_rtofs_osisaf_stats.sh with VDATE=2023107 and will use the files copied in step 2 as input. This will generate /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs/rtofs.20231007/evs.stats.rtofs.osisaf.grid2grid_sic.v20231007.stat.

**Comment by PerryShafran-NOAA** [comment]
For 3, you mean /lfs/h2/emc.vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs/rtofs.20231008?

**Comment by PerryShafran-NOAA** [comment]
Here's what I think I should do:

a) Backfill all missing prep data from 20231005 through 20231007.  That way I'll have a full contingent of prep data in my directory (which I will also use to back fill emc.vpppg prep directories).
b) Re-run prep for 20231008
c) Re-run stats for 20231007

I think once I do that, we'll have a better sense of this code working.  

Perry

**Comment by malloryprow** [comment]
Ah yeah, I did. I fixed it.
The prep data only goes through 20231008. 

The stats go back to forecast hour 192, so whatever you need the prep data for that span of dates.

**Comment by malloryprow** [comment]
I'm fine with doing whatever you are fine with.

**Comment by malloryprow** [comment]
I think in the next PR where I need to fix up COMIN paths I will address these problems of how the input files for METplus are being defined with the COMOUT variable.

**Comment by PerryShafran-NOAA** [comment]
OK - I am starting by backfilling the prep data so we have a complete set.  I think that is vital to continuing on.

**Comment by PerryShafran-NOAA** [comment]
OK, I backfilled the rtofs data and have that in all in my prep directory, thus returning COMIN and COMINfcst to $USER, and I re-ran the osisaf stats job.  This time it looks much better.

Please check the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr291test/EVS/dev/drivers/scripts/stats/rtofs/jevs_rtofs_osisaf_stats.o84032106

And the stats file here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs/rtofs.20231005

**Comment by malloryprow** [comment]
Woohoo!

✔️ **prep and stats are good**

We can do plots after the production switch is done.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow OK, finally got a change to submit all the plot jobs.  They are all complete except whichever one is the longest one (argo I think)?  

See the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr291test/EVS/dev/drivers/scripts/plots/rtofs

And the tarballs here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/rtofs

Thanks!

Perry

**Comment by malloryprow** [comment]
The number of images in each tar file that have been created so far is correct. I'll wait until the argo job is done to give the official approval.

**Comment by malloryprow** [comment]
argo is done and looks good too

✔️ **plots are good**

**Comment by PerryShafran-NOAA** [comment]
OK!  So, to sum, you are going to take care of all the COMIN items in a future PR, yes?

I'll start looking at the code.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code review looks good.  This code is approved to merge.

**Comment by malloryprow** [comment]
Yeah, I've been working on cleaning up the COMIN paths today in another branch. Additionally, I'm going changes so the stats jobs use the files in COMIN and not COMOUT.

**Comment by PerryShafran-NOAA** [comment]
Great!  Merging now.

**Comment by malloryprow** [comment]
Don't forget to update the paths for scripts for the cronjobs too!

**Pull request merged**
