### PR TITLE
Feature/global_det_atmos_nohrsc_map

### PR DESCRIPTION
**Pull request by malloryprow**
This pull request includes:

* adjustments to colormaps for precip spatial maps
* addition of 24 hour accumulation NOHRSC spatial map

- [ ] Describe testing already performed for this Pull Request:</br>

> ecf scripts were submitted to be run and tested. Plot is displayed at https://emc.ncep.noaa.gov/gmb/mpr/evs_plots_check/grid2grid/images/nohrsc.v2022122912.024h.conus.gif.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

1. Checkout the branch
2. Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_48/evs_global_det_atmos_set_up.sh. Open and set EVSclone to where the clone is. This script will link the fix files and clear out the user's stats/global_det directory and the link to my stats/global_det directory since my directory has more data in it.
3. Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_48/run_evs_global_det_atmos_plots.sh . Open and set EVSclone to where the clone is. This script will submit the ecf scripts to run the plotting jobs.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

> Yes

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

> Yes

- [ ] Please complete this pull request review by 1/10/2023.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

Working on this PR now.  Just to confirm, this is *only* a plots testing PR?

Thanks!

Perry

**Comment by malloryprow** [comment]
Plots only, in fact only a single plot will be made in this update!

**Comment by PerryShafran-NOAA** [comment]
The plots tar files are now available here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/plots/global_det/atmos.20230109.  Please validate and let me know if all looks good.

Thanks!

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Yup, looks good! The new plot is there, and looks great.

**Comment by PerryShafran-NOAA** [comment]
Excellent.  This seemed to be an easy one!  

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
