### PR TITLE
bugfix_fhr24snow

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

> This PR has been running daily under my account producing stats for the GFS, IMD, and ECMWF. Plots were generated to show the impact of the changes done in this PR.

snowfall
old_evs global_det fbias_ge0p0254 weasd_a24_z0 last31days fhrmean_valid12z_f240 g211_buk_conus
new_evs global_det fbias_ge0p0254 snod_a24_z0 last31days fhrmean_valid12z_f240 g211_buk_conus
old_evs global_det fbias_ge0p0254 snod_a24_z0 last31days fhrmean_valid12z_f240 g211_buk_conus
new_evs global_det fbias_ge0p0254 weasd_a24_z0 last31days fhrmean_valid12z_f240 g211_buk_conus

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

 ###  **Set-up**
> 1. Clone my fork and checkout branch bugfix_fhr24snow
> 2. `ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix`

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **4/28/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @malloryprow ! I have cloned your fork and checked out branch `bugfix_fhr24snow`. I will follow the rest of the instructions and begin the checkout of this PR.

**Comment by malloryprow** [comment]
Sounds good!

**Comment by ShelleyMelchior-NOAA** [comment]
The runs are underway!
Logfiles are in `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/global_det`

**Comment by malloryprow** [comment]
I got some missing data emails

> Warning: No IMD forecast was available for 2024032800f012
> Missing file is /lfs/h1/ops/prod/com/evs/v1.0/prep/global_det/atmos.20240328/imd/imd.t00z.f012
> Job ID: jevs_global_det_atmos_imd_grid2grid_stats_00.140326817.dbqs01

This would make sense since global_det atmos prep doens't run until 1815Z.

**Comment by ShelleyMelchior-NOAA** [comment]
OH ok! Let me run again w/ an earlier date. I forgot about that.

**Comment by malloryprow** [comment]
I forgot too!

**Comment by AliciaBentley-NOAA** [comment]
I got the missing emails as well as was about to write in! Thanks, all! An earlier date sounds good!

**Comment by ShelleyMelchior-NOAA** [comment]
Re-runs are underway w/ VDATE=20240327.
```
[dlogin01 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ lltr jevs_global_det_atmos_*grid2grid_stats_00.o140328*
-rw-r--r-- 1 shelley.melchior emc 9214232 Mar 29 16:47 jevs_global_det_atmos_imd_grid2grid_stats_00.o140328148
-rw-r--r-- 1 shelley.melchior emc 6268810 Mar 29 16:47 jevs_global_det_atmos_gfs_grid2grid_stats_00.o140328147
-rw-r--r-- 1 shelley.melchior emc 8212512 Mar 29 16:47 jevs_global_det_atmos_ecmwf_grid2grid_stats_00.o140328146
```

**Comment by AliciaBentley-NOAA** [comment]
No missing file emails so far!

**Comment by malloryprow** [comment]
Everything looks good!

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The code change yields the expected results.

**Pull request merged**
