### PR TITLE
AqmStatsMissingFileBugFix

### PR DESCRIPTION
**Pull request by Ho-ChunHuang-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

With a full set of FCST and OBS input files, the current code produces identical output as current code version in authoritative repository.
With a missing 12z run of 20231224 AQMv7 output, the current code successfully completed without any error.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

To mimic  the situation of 12/24/2023;
please link the COMINaqm=/lfs/h2/emc/ptmp/ho-chun.huang/emc.para/com/aqm/v7.0_test
please link the prep output directory (EVSINaqm) to /lfs/h2/emc/physics/noscrub/ho-chun.huang/evstest/v1.0/prep/aqm
Run stats on VDATE=20231224

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
YES
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by Ho-ChunHuang-NOAA** [comment]
Please see instruction described above for testing.  Search for "err=" in logout for any error other err=0.  Check the fcsthours_list="24 48" only for hour=12 loop for both OZMAX8 and PMAVE.

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `feature/aqmdailystatsfix`.

**Comment by ShelleyMelchior-NOAA** [comment]
@Ho-ChunHuang-NOAA , should I specify a certain vhr for the run? The outage for AQMv7 was the 12z cycles, but the stats run can be for any vhr? Or maybe all vhr's for that VDATE?

**Comment by Ho-ChunHuang-NOAA** [comment]
@ShelleyMelchior-NOAA  The stats is run one vhr at a time from 00 to 23.  At vhr = 04, hourly point_stats valid at 04Z will run first followed by PMAVE daily point_stat.  At vhr=11, hourly point_stats valid at 11Z will run first followed by OZMAX8 daily point_stat.  For the remaining vhr, only hourly point_stats will be ran.

Th error occurred for the daily pmave and ozmax8 point stat at 04 and 11 vhr, respectively.   Hourly stats has no error from 00 to 23 vhr.

It will be good to test entire day from vhr 00 to 23 to assure the new code generates nor error for every vhr.  For target test, please run vhr=04 and 11.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran all cycles for VDATE=20231224.
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_stats.o12249*`

The stats files mostly match. Are these differences expected w/ the AQMv7 outage?
```
[dlogin08 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ ll /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/aqm/aqm.20231224
total 49144
-rw-r--r-- 1 shelley.melchior vpppg   375379 Dec 28 20:37 evs.stats.aqm_bc.atmos.grid2obs_ozmax8.v20231224.stat
-rw-r--r-- 1 shelley.melchior vpppg 10089416 Dec 28 20:43 evs.stats.aqm_bc.atmos.grid2obs_ozone.v20231224.stat
-rw-r--r-- 1 shelley.melchior vpppg 14158037 Dec 28 20:44 evs.stats.aqm_bc.atmos.grid2obs_pm25.v20231224.stat
-rw-r--r-- 1 shelley.melchior vpppg   528961 Dec 28 20:37 evs.stats.aqm_bc.atmos.grid2obs_pmave.v20231224.stat
-rw-r--r-- 1 shelley.melchior vpppg   375500 Dec 28 20:36 evs.stats.aqm_raw.atmos.grid2obs_ozmax8.v20231224.stat
-rw-r--r-- 1 shelley.melchior vpppg 10089725 Dec 28 20:43 evs.stats.aqm_raw.atmos.grid2obs_ozone.v20231224.stat
-rw-r--r-- 1 shelley.melchior vpppg 14158038 Dec 28 20:44 evs.stats.aqm_raw.atmos.grid2obs_pm25.v20231224.stat
-rw-r--r-- 1 shelley.melchior vpppg   529077 Dec 28 20:36 evs.stats.aqm_raw.atmos.grid2obs_pmave.v20231224.stat
```
```
[dlogin08 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ ll /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/aqm/aqm.20231224                                               
total 51280
-rw-r--r-- 1 emc.vpppg vpppg   375379 Dec 27 11:11 evs.stats.aqm_bc.atmos.grid2obs_ozmax8.v20231224.stat
-rw-r--r-- 1 emc.vpppg vpppg 10544563 Dec 27 23:12 evs.stats.aqm_bc.atmos.grid2obs_ozone.v20231224.stat
-rw-r--r-- 1 emc.vpppg vpppg 14796820 Dec 27 23:13 evs.stats.aqm_bc.atmos.grid2obs_pm25.v20231224.stat
-rw-r--r-- 1 emc.vpppg vpppg   528961 Dec 27 04:12 evs.stats.aqm_bc.atmos.grid2obs_pmave.v20231224.stat
-rw-r--r-- 1 emc.vpppg vpppg   375500 Dec 27 11:11 evs.stats.aqm_raw.atmos.grid2obs_ozmax8.v20231224.stat
-rw-r--r-- 1 emc.vpppg vpppg 10544973 Dec 27 23:11 evs.stats.aqm_raw.atmos.grid2obs_ozone.v20231224.stat
-rw-r--r-- 1 emc.vpppg vpppg 14796818 Dec 27 23:12 evs.stats.aqm_raw.atmos.grid2obs_pm25.v20231224.stat
-rw-r--r-- 1 emc.vpppg vpppg   529077 Dec 27 04:11 evs.stats.aqm_raw.atmos.grid2obs_pmave.v20231224.stat
```

I only see "err=0" in the log files.
```
[dlogin08 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ grep err= jevs_aqm_grid2obs_stats.o12249* | grep -v "err=0"
[dlogin08 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$
```

**Comment by Ho-ChunHuang-NOAA** [comment]
@ShelleyMelchior-NOAA only err=0 is what we want.  Your output is the same as mine in the 20231224 situation at /lfs/h2/emc/physics/noscrub/ho-chun.huang/evstest/v1.0/stats/aqm/aqm.20231224.

emc.para may have different stats because I added the missing 12Z model output in the middle of the day, so the later vhr may use full set of FCST file for verification.

My stats with complete three days FCST output looks like
```
dlogin09:/lfs/h2/emc/physics/noscrub/ho-chun.huang/evsv7/v1.0/stats/aqm > ll aqm.20231224
total 53444
drwxr-sr-x  2 ho-chun.huang physics     4096 Dec 28 02:39 ./
drwxr-sr-x 29 ho-chun.huang physics    20480 Dec 28 10:16 ../
-rw-r--r--  1 ho-chun.huang physics   450776 Dec 28 02:25 evs.stats.aqm_bc.atmos.grid2obs_ozmax8.v20231224.stat
-rw-r--r--  1 ho-chun.huang physics 10923779 Dec 28 02:38 evs.stats.aqm_bc.atmos.grid2obs_ozone.v20231224.stat
-rw-r--r--  1 ho-chun.huang physics 15329138 Dec 28 02:39 evs.stats.aqm_bc.atmos.grid2obs_pm25.v20231224.stat
-rw-r--r--  1 ho-chun.huang physics   635082 Dec 28 02:17 evs.stats.aqm_bc.atmos.grid2obs_pmave.v20231224.stat
-rw-r--r--  1 ho-chun.huang physics   450913 Dec 28 02:24 evs.stats.aqm_raw.atmos.grid2obs_ozmax8.v20231224.stat
-rw-r--r--  1 ho-chun.huang physics 10924346 Dec 28 02:37 evs.stats.aqm_raw.atmos.grid2obs_ozone.v20231224.stat
-rw-r--r--  1 ho-chun.huang physics 15329138 Dec 28 02:38 evs.stats.aqm_raw.atmos.grid2obs_pm25.v20231224.stat
-rw-r--r--  1 ho-chun.huang physics   635223 Dec 28 02:17 evs.stats.aqm_raw.atmos.grid2obs_pmave.v20231224.stat
```

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks, Ho-Chun. That lines up. My stats files are the smallest, running from your test case. emc.vpppg parallel was backfilled. And your stats files are largest, having complete stats for all 3 days.

I think this PR is OK to merge. Let me do the formal code review.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yield expected results. This PR is approved for merge.

**Pull request merged**
