### PR TITLE
feature/global_det_atmos_headline_31day_acc

### PR DESCRIPTION
**Pull request by malloryprow**
This pull request includes:

* adding global_det atmos headline plot 31 day 500 hPa Geopotential Height Day 5 ACC

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

> The ecf scripts was run and final image at https://emc.ncep.noaa.gov/gmb/mpr/evs.global_det.acc.hgt_p500.last31days.timeseries_valid00z_f120.g004_nhem.png was approved by @AliciaBentley-NOAA 

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

1. Checkout the branch
2. Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_51/evs_global_det_atmos_set_up.sh. Open and set EVSclone to where the clone is. This script will link the fix files and clear out the user's stats/global_det directory and the link to my stats/global_det directory since my directory has more data in it.
3. Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_51/run_evs_global_det_atmos_headline_plots.sh. Open and set EVSclone to where the clone is. This script will submit the ecf scripts to run the headline plots job.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

> Yes

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

> Yes

- [ ] Please complete this pull request review by 1/25/2023.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Will this pull requested be tested soon? It should be pretty simple. It just produces one graphic.

**Comment by PerryShafran-NOAA** [comment]
Yes, sorry.  I had been focused on the parallels.  I will test it today.

Perry

**Comment by PerryShafran-NOAA** [comment]
Please validate the results here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/plots/global_det/headline.20230208

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Looks good!

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
