### PR TITLE
bugfix/nfcens_r2

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
This PR addresses the comment no. 84 for EVS-NFCENS component. The mail messages for prep STEP were wrapped in a conditional statement.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
1- To test the changes, you can only run the prep STEP.
2- Clone my fork in your local and checkout branch "bugfix/nfcens_R2", then find the driver scripts located at: EVS/dev/drivers/scripts/prep/nfcens/jevs_nfcens_wave_grid2obs_prep.sh

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/nfcens_R2`.

**Comment by ShelleyMelchior-NOAA** [comment]
@SamiraArdani-NOAA , is SENDMAIL ever set in the nfcens prep processing? I am not seeing it. I think you may need to add it to `JEVS_NFCENS_WAVE_GRID2OBS_PREP` w/ the default of NO.  Then you need to add it to `jevs_nfcens_wave_grid2obs_prep.sh` set to YES.

**Comment by SamiraArdani-NOAA** [comment]
Hi @ShelleyMelchior-NOAA . I set the SENDMAIL in driver script and jobs.

**Comment by ShelleyMelchior-NOAA** [comment]
Excellent! I re-ran the prep driver.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nfcens_wave_grid2obs_prep.o131950055`
I can see in the logfile, around line 2220 that the logic to send an email is not entered into b/c the file exists. This is the correct behavior.
```
Copying GDAS prepbufr files
+ 0 + for HH in 00 06 12 18
+ 0 + export inithour=t00z
+ 0 + inithour=t00z           
+ 0 + '[' '!' -s /lfs/h1/ops/prod/com/obsproc/v1.1/gdas.20240204/00/atmos/gdas.t00z.prepbufr '
]'
+ 0 + cp -v /lfs/h1/ops/prod/com/obsproc/v1.1/gdas.20240204/00/atmos/gdas.t00z.prepbufr /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_nfcens_wave_grid2obs_prep.131950055.dbqs01/
gdas.2024020400.prepbufr
```

**Comment by ShelleyMelchior-NOAA** [comment]
If we want, I can fudge the script to make it enter the SENDMAIL logic to test when the prepbufr file doesn't exist.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran a test to see what the code does when the grib2 file is not found.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nfcens_wave_grid2obs_prep.o131952028`
I fudged the grib2 filename to be a suffix of grib22. Alicia and Samira should have gotten emails. The logfile reflects the email activity.

**Comment by AliciaBentley-NOAA** [comment]
Missing emails confirmed! Example:

WARNING: No NFCENS forecast was available for 2024020400
WARNING: Missing file is /lfs/h1/ops/prod/com/wave_nfcens/v1.3/nfcens.20240204/HTSGW_mean.t00z.**grib22**
Job ID: jevs_nfcens_wave_grid2obs_prep.131952028.dbqs01

@ShelleyMelchior-NOAA @SamiraArdani-NOAA

**Comment by SamiraArdani-NOAA** [comment]
@ShelleyMelchior-NOAA : Confirmed. I received emails.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The tests yield expected results. This PR is approved for merge.

**Pull request merged**
