### PR TITLE
Bugfix/cam cat logs and ver change

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

All jobs were run as described in this PR and completed normally.

### This bugfix addresses the following:
- Aggregate locations of METplus and plotting log files in DATA and cat each file near the end of the job
- Prepare driver scripts to handle an upcoming change in run.ver from a 2- to 3-digit evs version number 
- Remove hardcoded paths in some cam files
- Correct the HOMEevs definition in cam J-jobs
- Change some plotting log messages from "ERROR" to "WARNING"

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Same process as in the most recent cam PR:
### (1) Set up jobs 
•	symlink the EVS_fix directory locally as "fix"
•	In all driver scripts, point all exports of "HOMEevs" to your EVS test directory
•	In all driver scripts, change COMIN to the parallel directory (`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`)
•	Optional: In all stats drivers scripts, change "maillist" to point to your email address
### (2) Test Jobs
Use the following …
•	…to submit stats/precip: `qsub –v vhr=19,VDATE=$(date -d "-3 days" +"%Y%m%d")`
•	…to submit everything else: `qsub –v vhr=00 `
(_Note change to "vhr" in qsub commands_)

From your EVS testing directory, the following scripts should be run using the set up in step (1):
```
dev/drivers/scripts/prep/cam/jevs_cam_hireswarw_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswarw_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswarwmem2_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswarwmem2_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswfv3_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswfv3_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_href_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hrrr_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hrrr_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_namnest_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_namnest_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_radar_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_severe_prep.sh
```
```
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_spcoutlook_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_nam_firewxnest_grid2obs_stats.sh
```
```
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_cape_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_cape_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ctc_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ctc_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_precip_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_precip_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_precip_spatial_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_profile_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_profile_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_snowfall_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_snowfall_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_spcoutlook_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_spcoutlook_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_nam_firewxnest_grid2obs_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_grid2obs_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_headline_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_precip_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_snowfall_plots.sh
```
_[Total: 13 prep jobs, 31 stats jobs, 20 plots jobs]_

- [x] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [x] Do these updates/additions include sufficient testing updates? **Yes**

- [x] Please complete this pull request review by **11/17/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA Can you please remove Line 128 from the stats J-job (and make sure you and I are listed in all stats dev drivers for cam)?

[export maillist=${maillist:-'alicia.bentley@noaa.gov'}](https://github.com/NOAA-EMC/EVS/blob/01004a82083bad29e4586ad36ac03191886fc946/jobs/JEVS_CAM_STATS#L128)

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA I've looked over the changes made in this PR and think that they look great! Very comprehensive. I've also compared this PR to the EMC's EE2 checklist and confirmed that the requested changes to the hardcoded paths were made. I approve this PR for testing! Thanks!

@PerryShafran-NOAA @ShelleyMelchior-NOAA

**Comment by MarcelCaron-NOAA** [comment]
> @MarcelCaron-NOAA Can you please remove Line 128 from the stats J-job (and make sure you and I are listed in all stats dev drivers for cam)?
> 
> [export maillist=${maillist:-'alicia.bentley@noaa.gov'}](https://github.com/NOAA-EMC/EVS/blob/01004a82083bad29e4586ad36ac03191886fc946/jobs/JEVS_CAM_STATS#L128)

Removed!  I checked @AliciaBentley-NOAA and you are included in all cam mailing lists.  Most of the href jobs also list Binbin, and the nam_firewxnest job also lists Perry.  Is that right?

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/cam_cat_logs_and_ver_change`

**Comment by ShelleyMelchior-NOAA** [comment]
prep processing is underway.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/cam`
logfiles: `jevs_cam_*_prep.o107214*`

2 processes are still finishing up.
```
dbqs01: 
                                                                                                   Req'd  Req'd   Elap
Job ID                         Username        Queue           Jobname         SessID   NDS  TSK   Memory Time  S Time
------------------------------ --------------- --------------- --------------- -------- ---- ----- ------ ----- - -----
107214921.dbqs01               shelley.melchi* dev             jevs_cam_namne*   108652    1     1   10gb 00:30 R 00:09
107214929.dbqs01               shelley.melchi* dev             jevs_cam_radar*   164026    1     1   25gb 00:45 R 00:09
```

**Comment by ShelleyMelchior-NOAA** [comment]
Things look good in terms of logfile cat'ing. I still have the log files from the cam runs last week. The newer log files are bigger. For example ...
```
[dlogin03 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ lltr jevs_cam_severe_prep.o10*
-rw-r--r-- 1 shelley.melchior emc 1128549 Oct 20 15:06 jevs_cam_severe_prep.o106881734
-rw-r--r-- 1 shelley.melchior emc 1433803 Oct 24 18:41 jevs_cam_severe_prep.o107214932
```
```
[dlogin03 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ lltr jevs_cam_hireswfv3_severe_prep.o10*
-rw-r--r-- 1 shelley.melchior emc 1088136 Oct 20 15:07 jevs_cam_hireswfv3_severe_prep.o106881664
-rw-r--r-- 1 shelley.melchior emc 1157646 Oct 24 18:41 jevs_cam_hireswfv3_severe_prep.o107214898
```

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA 
All of the prep jobs completed successfully and the output seem normal.  The outfile size comparison test is a good confirmation that the cat'ing is working, and I was able to confirm by checking the contents to boot.

**All prep jobs have my approval!**

**Comment by ShelleyMelchior-NOAA** [comment]
Great! I just kicked off all of the non-precip stats jobs. I need to go afk for several hours, but feel free to watch along as processes end. I will kick off precip stats jobs in a little while and update the PR.
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_*_stats.o10721*`

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA Can you please remove the "export run_envir" lines in:
 [dev/drivers/scripts/stats/cam/jevs_cam_href_grid2obs_stats.sh](https://github.com/NOAA-EMC/EVS/blob/01004a82083bad29e4586ad36ac03191886fc946/dev/drivers/scripts/stats/cam/jevs_cam_href_grid2obs_stats.sh#L30)
and
[dev/drivers/scripts/stats/cam/jevs_cam_href_spcoutlook_stats.sh](https://github.com/NOAA-EMC/EVS/blob/01004a82083bad29e4586ad36ac03191886fc946/dev/drivers/scripts/stats/cam/jevs_cam_href_spcoutlook_stats.sh#L28)

I don't think that removing these should break anything (these are the only two instances of run_envir outside of ecflow), but please confirm! Thanks!

**Comment by MarcelCaron-NOAA** [comment]
Done.  Agreed that deleting these will not cause problems.

**Comment by ShelleyMelchior-NOAA** [comment]
OK, **_all_** stats processing has been submitted.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam/`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_*_stats.o10721*`

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA @MarcelCaron-NOAA I got a lot of missing file emails this evening from Shelley! I'm not sure if they were from a previously test this evening that failed or from the latest test!

**Comment by MarcelCaron-NOAA** [comment]
> @ShelleyMelchior-NOAA @MarcelCaron-NOAA I got a lot of missing file emails this evening from Shelley! I'm not sure if they were from a previously test this evening that failed or from the latest test!

Sorry about the emails.  They are likely from the current precip stats test.  I chose to recommend testing with VDATE=PDYm3 even though normally this is PDYm2.  The benefit is all the obs files are available, but the downside is the longer forecast leads are not, hence the emails.

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA 
All of the stats jobs completed successfully and the output seem normal (compared to emc.vpppg).  All of the outfiles contain cat'ed logs.

**All stats jobs have my approval based on my checks**

**Comment by ShelleyMelchior-NOAA** [comment]
> > @ShelleyMelchior-NOAA @MarcelCaron-NOAA I got a lot of missing file emails this evening from Shelley! I'm not sure if they were from a previously test this evening that failed or from the latest test!
> 
> Sorry about the emails. They are likely from the current precip stats test. I chose to recommend testing with VDATE=PDYm3 even though normally this is PDYm2. The benefit is all the obs files are available, but the downside is the longer forecast leads are not, hence the emails.

How will this be run in operations? Will it be PDYm2? And will it be run late enough so that all of the obs files are available?

**Comment by ShelleyMelchior-NOAA** [comment]
I kicked off the plots processing.
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/cam` (atmos.20231022 for cam and href; atmos.20231023 for firewx)
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_*_plots.o1072428*`

I initially ran at 01Z-ish, but that was too soon into 20231025 for some of the stats and prep files to be available in the emc.vpppg, so I bumped VDATE back by one day so it would be as though I was running this on 20231024.

For the tar files in atmos.20231023, only consider firewx. The href plots the look at are in atmos.20231022.

**Comment by MarcelCaron-NOAA** [comment]
> > > @ShelleyMelchior-NOAA @MarcelCaron-NOAA I got a lot of missing file emails this evening from Shelley! I'm not sure if they were from a previously test this evening that failed or from the latest test!
> > 
> > 
> > Sorry about the emails. They are likely from the current precip stats test. I chose to recommend testing with VDATE=PDYm3 even though normally this is PDYm2. The benefit is all the obs files are available, but the downside is the longer forecast leads are not, hence the emails.
> 
> How will this be run in operations? Will it be PDYm2? And will it be run late enough so that all of the obs files are available?

Yes, this will be run at PDYm2 at 19, 20, 21, and 22Z.   All obs files are available by 18Z, probably earlier; running at 19-22Z seems to be sufficient to avoid missing obs data.

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA Can lines like 14–17 in [scripts/stats/cam/exevs_href_grid2obs_stats.sh](https://github.com/NOAA-EMC/EVS/blob/01004a82083bad29e4586ad36ac03191886fc946/scripts/stats/cam/exevs_href_grid2obs_stats.sh#L14-L17) be removed from the cam component? I see met_verbosity in [machine.conf](https://github.com/NOAA-EMC/EVS/blob/develop/parm/metplus_config/machine.conf), but not metplus_verbosity. I'd like you to remove them, but I'm not sure if machine.conf should be updated. 

```
export MET_bin_exec='bin'
export log_met_output_to_metplus=''
export metplus_verbosity=2
export met_verbosity=2
```

**Comment by MarcelCaron-NOAA** [comment]
@AliciaBentley-NOAA I noticed this question on the narre PR and checked to see how these variables are being used.  They seemed dead to me, so I think they can be simply removed.

@ShelleyMelchior-NOAA this change I believe would only affect jevs_cam_href_precip_stats and jevs_cam_href_grid2obs_stats.  Maybe those two should be rerun to make sure?

**Comment by ShelleyMelchior-NOAA** [comment]
> @AliciaBentley-NOAA I noticed this question on the narre PR and checked to see how these variables are being used. They seemed dead to me, so I think they can be simply removed.
> 
> @ShelleyMelchior-NOAA this change I believe would only affect jevs_cam_href_precip_stats and jevs_cam_href_grid2obs_stats. Maybe those two should be rerun to make sure?

Sure thing!

**Comment by MarcelCaron-NOAA** [comment]
> I kicked off the plots processing. COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/cam` (atmos.20231022 for cam and href; atmos.20231023 for firewx) logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_*_plots.o1072428*`
> 
> I initially ran at 01Z-ish, but that was too soon into 20231025 for some of the stats and prep files to be available in the emc.vpppg, so I bumped VDATE back by one day so it would be as though I was running this on 20231024.
> 
> For the tar files in atmos.20231023, only consider firewx. The href plots the look at are in atmos.20231022.

@ShelleyMelchior-NOAA All of the plots jobs completed successfully, the output seem normal relative to emc.vpppg runs, and all of the outfiles contain cat'ed logs.

**All plots jobs have my approval based on those checks**

**Comment by ShelleyMelchior-NOAA** [comment]
I re-ran stats for firewx since I saw those lines removed for that processing, too. Resultant stats files match b/t my run and emc.vpppg. 👍 

I re-ran an href plot process, too, since I saw those lines removed from a plotting util script in ush. Resultant tar file matches b/t my run and emc.vpppg. 👍 

The href stats processing is still running. I will keep checking on it since these processes need more time.
```
dbqs01: 
                                                                                                   Req'd  Req'd   Elap
Job ID                         Username        Queue           Jobname         SessID   NDS  TSK   Memory Time  S Time
------------------------------ --------------- --------------- --------------- -------- ---- ----- ------ ----- - -----
107289765.dbqs01               shelley.melchi* dev             jevs_cam_href_*     4483    1    72  500gb 04:30 R 00:22
107289785.dbqs01               shelley.melchi* dev             jevs_cam_href_*   194613    1    88   10gb 02:00 R 00:22
```
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/`
`jevs_cam_href_grid2obs_stats.o107289765`
`jevs_cam_href_precip_stats.o107289785`

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA @MarcelCaron-NOAA I sent the following email to you, but will include here too for completeness:

It looks like there are strange question marks in this missing file name for jevs_cam_href_precip_stats.sh that Shelley just reran:

```
Missing file is /lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_??H_Pass2_00.00_20231022-120000.grib2.gz
Job ID: jevs_cam_href_precip_stats.107289785.dbqs01
```

Did this get corrected after it was sent to me and Binbin? If not, can we investigate?

**Comment by ShelleyMelchior-NOAA** [comment]
```
Missing file is /lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_??H_Pass2_00.00_20231022-120000.grib2.gz
Job ID: jevs_cam_href_precip_stats.107289785.dbqs01
```
Those question marks might just be wildcards. You can use `?` in place of `*` when you want to indicate just a single character substitution.

**Comment by MarcelCaron-NOAA** [comment]
It seems that it is the programmed mail message output given missing mrms files for this job (line 357 in [ush/cam/evs_href_preppare.sh](https://github.com/NOAA-EMC/EVS/blob/0f7f90e43950683c9e3841e8297961076b59b25d/ush/cam/evs_href_preppare.sh)):
```
357    echo Missing file is $DCOMINmrms/MultiSensor_QPE_??H_Pass2_00.00_${vday}-120000.grib2.gz  >> mailmsg
```

I agree with @ShelleyMelchior-NOAA that it is a wildcard.  The ?? replaces what would normally be the qpe accumulation period.  I figure it is supposed to represent "03", since I think this mail message triggers if the 3-hour accumulation file is not found.

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA @ShelleyMelchior-NOAA Thanks! Would it be possible to make the email message more meaningful in your **next** cam PR? Perhaps the email could say "03" to indicate the file that was actually missing? No need to hold this PR up to make this update now, but please try to incorporate it into your next cam PR! Thanks!

**Comment by MarcelCaron-NOAA** [comment]
@AliciaBentley-NOAA Sure, I'll add that to my list for the next PR!

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA @ShelleyMelchior-NOAA Excellent! Is this PR cleared to merge then?!? :)

**Comment by MarcelCaron-NOAA** [comment]
All of the href jobs that needed to be rerun have completed successfully except for jevs_cam_href_grid2obs_stats, which is still running.  It's currently at 1h40m of a typically 3h30m job.  No issues so far.  

All other jobs I believe have been run successfully.

**Comment by ShelleyMelchior-NOAA** [comment]
@MarcelCaron-NOAA , while we wait on the href g2o stats job to complete, go ahead and do a sync fork for `bugfix/cam_cat_logs_and_ver_change`.

**Comment by ShelleyMelchior-NOAA** [comment]
> It seems that it is the programmed mail message output given missing mrms files for this job (line 357 in [ush/cam/evs_href_preppare.sh](https://github.com/NOAA-EMC/EVS/blob/0f7f90e43950683c9e3841e8297961076b59b25d/ush/cam/evs_href_preppare.sh)):
> 
> ```
> 357    echo Missing file is $DCOMINmrms/MultiSensor_QPE_??H_Pass2_00.00_${vday}-120000.grib2.gz  >> mailmsg
> ```
> 
> I agree with @ShelleyMelchior-NOAA that it is a wildcard. The ?? replaces what would normally be the qpe accumulation period. I figure it is supposed to represent "03", since I think this mail message triggers if the 3-hour accumulation file is not found.

If it is always the 3 hour accumulation files, then I am fine w/ this. But will there ever be the possibility that it could be a different accumulation file? If so, that could be the reasoning behind using the `?` wildcards. 
I looked more closely at the code. The top of the if block specifically tests on the 03 file. However, when you list on DCOMINmrms directory ( `/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE` ), there are other ??H files available.

**Comment by ShelleyMelchior-NOAA** [comment]
I honestly don't mind if you change that  `??` to `03` in this PR while the last test finishes up. That way it can't get accidentally forgotten.

**Comment by MarcelCaron-NOAA** [comment]
Okay.  Since we have time I'll check to make sure 03 is right, that there is no other possible accum for the ?? mail message, and if so I'll push the change here.

**Comment by ShelleyMelchior-NOAA** [comment]
👍 those changes look good, @MarcelCaron-NOAA .

**Comment by ShelleyMelchior-NOAA** [comment]
🙌 all the tests have completed and the results are the same as emc.vpppg. I think this PR is now ready for merge.

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA agreed, thanks!

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All tests yield expected results. This PR is approved for merge.

**Pull request merged**
