### PR TITLE
Bugfix/Subseasonal Update COMIN

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
Changes for this PR include: COMINdcomobs to DCOMIN, COMINclimo to EVSINclimo in stats, COMINgefs and COMINcfs to EVSINgefs and EVSINcfs in plots, removing old lines of code, making restart comments, changing verif_type PrepBufr to prepbufr for grid-to-obs stats, and adding overall documentation to scripts.
These changes have been tested in a working directory.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Please test the following in order after checking out the feature branch:
dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_obs_prep.sh
dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_cfs_grid2obs_stats.sh (Make sure you have 35 days of data)
dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2obs_prepbufr_plots_31days.sh (Make sure you have some stat files to plot)
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>
As soon as you are able
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Beginning work for this PR, starting with the prep step.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA prep has completed. 

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr303test/EVS/dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_obs_prep.o106583757

The output directory is here:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/subseasonal/atmos.20231015

**Comment by ShannonShields-NOAA** [comment]
Hi @PerryShafran-NOAA , sorry for the delay in checking this. We are having a bit of a crisis with the GHRSST-OSPO validation data. I checked the output data and output file and all looks good with the DCOMIN change for prep obs. Please proceed with the stats testing.

**Comment by PerryShafran-NOAA** [comment]
OK, will do!

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA The stats job is complete.  Looks like all went well, but just a word to the wise, I am seeing these statements in your .o file:

```
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr303test/EVS/ush/subseasonal/subseasonal_stats_grid2obs_create_days6_10_avg.py:175: 
FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat i
nstead.
```

@AliciaBentley-NOAA @ShelleyMelchior-NOAA Wanted to note this for you here as well.

Here is the .o file:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr303test/EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_cfs_grid2obs_stats.o106591962

And the output directories:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/subseasonal/*20231015*

**Comment by AliciaBentley-NOAA** [comment]
Thank you for pointing that out, @PerryShafran-NOAA!

@ShannonShields-NOAA, please continue with this PR without updating to `pandas.concat` (or `pd.concat`). If you would like to test out this function before submitting your next PR to avoid this warning statement, that would be fine. But I don't want that to hold up this one. Thanks! 

@malloryprow Do you use `frame.append` in global_det?

**Comment by malloryprow** [comment]
I was but I think I got rid of all uses because I was seeing this as well.

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA A quick [search of the EVSv1 auth repo](https://github.com/search?q=repo%3ANOAA-EMC%2FEVS+pd.concat&type=code) reveals that a few other components have switched to `pd.concat`. Hopefully this will be easy to switch to in your next PR!

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA @AliciaBentley-NOAA @malloryprow I was checking my G2O avg scripts against global_det as I originally copied this from Mallory and I believe the warning is occurring at this point:
https://github.com/ShannonShields-NOAA/EVS/blob/develop/ush/subseasonal/subseasonal_stats_grid2obs_create_days6_10_avg.py#L173C1-L173C1
with all_days_avg_df.append(days_avg_file_df,
                                                           ignore_index=True)
I see Mallory still has this in her avg.py scripts for G2O as well so I can check on this for the next PR.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA Otherwise, the CFS G2O stats job ran fine and we can proceed with plots testing.

**Comment by PerryShafran-NOAA** [comment]
Plots testing is underway.

**Comment by PerryShafran-NOAA** [comment]
Plots run super fast!  Please check the output:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr303test/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2obs_prepbufr_plots_31days.o106598895

plot tarball is here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/subseasonal/atmos.20231015

**Comment by ShannonShields-NOAA** [comment]
Yes, everything looks good @PerryShafran-NOAA . After your code review, this PR should be set to merge.

**Comment by PerryShafran-NOAA** [comment]
Excellent, thanks!  I'll do the code review now.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Do we need a sync fork or is this code fully up to date?  I know there were a few PRs merged this morning.

**Comment by ShannonShields-NOAA** [comment]
I just double-checked and all is updated after this morning.

**Comment by PerryShafran-NOAA** [comment]
OK!  I will now merge.

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Pull request merged**
