### PR TITLE
Bugfix/cam severe prep

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

Addresses an issue in which bad lines in SPC storm report CSV files cause cam severe prep jobs to fail.  

An error occurs at pandas.read_csv(), which reads an SPC storm report CSV file.  The file is expected to contain lines comma-separated into eight fields.  If more than eight fields are found for any line, pandas throws an error, which is passed to the err_chk production utility, causing the entire job to fail.  

A fix is to explicitly set the read_csv() argument, on_bad_lines='warn', which outputs a warning when a bad line is encountered, then skips the line.  The default behavior is to throw an error and break.

The fix has been tested successfully on the CSV file involved in a failed run that was flagged by NCO.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

I recommend testing two ways:
### (1) Explicitly on the "bad" file (Dogwood):
```
cd /your/working/dir
source /lfs/h2/emc/vpppg/noscrub/marcel.caron/ush/rrfs_plotting/run.env
export VDATE=20240415
HOMEevs=/path/to/test/EVS/dir
BAD_CSV="/lfs/h1/ops/prod/dcom/20240414/validation_data/weather/spc/spc_reports_20240414.csv"
$HOMEevs/ush/cam/read_ascii_storm.py $BAD_CSV > test.txt
```
**Review:** The output file should contain some information about the python file and input file,  a warning about line 6, and information about the data contents.  There should be no pandas.errors.ParserErrors.
### (2) Entire job:
**Set up:**
• symlink the EVS_fix directory locally as "fix"
• In driver script, point "HOMEevs" to your EVS test directory
• In driver script, change COMIN to the prod directory (/lfs/h1/ops/prod/com/$NET/$evs_ver_2d)
• In driver script, set SENDMAIL to "NO"

**Submit:** 
Use the following to submit the job: qsub –v vhr=07,VDATE=20240415

From your EVS testing directory, the following script should be run using the setup described above:
```
dev/drivers/scripts/prep/cam/jevs_cam_severe_prep.sh
```
[Total: 1 prep job]

**Review:**
You can use the following check:

check="FATAL\|WARNING\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|failed\|unexpected\|exceeded"
grep "$check" $outfile

- [x] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [x] Do these updates/additions include sufficient testing updates? **Yes**

- [x] Please complete this pull request review by **ASAP**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA I started your PR to ensure we can run these tests before the csv file disappears.

I ran the first test.  I see the line:

`Skipping line 6: expected 8 fields, saw 9`

And there is the output file:
/lfs/h2/emc/ptmp/perry.shafran/cam_test/test.txt

Please look at this file and let me know that this file contains what you expect.

**Comment by MarcelCaron-NOAA** [comment]
Great, thanks!



> @MarcelCaron-NOAA I started your PR to ensure we can run these tests before the csv file disappears.
> 
> I ran the first test. I see the line:
> 
> `Skipping line 6: expected 8 fields, saw 9`
> 
> And there is the output file: /lfs/h2/emc/ptmp/perry.shafran/cam_test/test.txt
> 
> Please look at this file and let me know that this file contains what you expect.

👍 The warning is good and expected, and the output file contains the expected csv data.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Your run is completed.

Please check the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr471test/EVS/dev/drivers/scripts/prep/cam 
And the output here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/cam, the spc_lsr.20240414 and spc_otlk.20240421

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA 

No red flags in the output log.  Output files look good.  Also, the job did properly handle the bad data by printing a warning and skipping the bad line. 

✔️ No other concerns from me.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Excellent!

As per our new PR procedure, we need to also run this using the beta versions of met/metplus.  Thus, I will set that up and then do a re-run using the beta versions.  The input will be emc.vpppg rather than production.  I am assuming that this ERROR also occurred in today's cam severe prep run (I haven't checked), but we still need to test with the new versions.  Please stay tuned.

**Comment by MarcelCaron-NOAA** [comment]
Thanks Perry!  I'll keep an eye out for the re-runs.

Yes, the ParseError occurred in today's parallel:
/lfs/h2/emc/ptmp/emc.vpppg/output/jevs_cam_severe_prep.o143069859

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Re-runs are finished.  Please check to see that this run actually indeed used the parallel versions and also that everything worked fine.

**Comment by MarcelCaron-NOAA** [comment]
Looks like the newer runs were successful. No red flags in the output logs: 
```
[marcel.caron@dlogin03 EVS] OFILE="/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr471test/EVS/dev/drivers/scripts/prep/cam/jevs_cam_severe_prep.o*"
[marcel.caron@dlogin03 EVS] grep "$check" $OFILE
[marcel.caron@dlogin03 EVS] grep "Error" $OFILE
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr471test/EVS/dev/drivers/scripts/prep/cam/jevs_cam_severe_prep.o143107747:    Error_Path = dlogin07.dogwood.wcoss2.ncep.noaa.gov:/lfs/h2/emc/vpppg/noscru
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr471test/EVS/dev/drivers/scripts/prep/cam/jevs_cam_severe_prep.o143109080:    Error_Path = dlogin07.dogwood.wcoss2.ncep.noaa.gov:/lfs/h2/emc/vpppg/noscru
[marcel.caron@dlogin03 EVS] grep "line 6" $OFILE
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr471test/EVS/dev/drivers/scripts/prep/cam/jevs_cam_severe_prep.o143107747:Skipping line 6: expected 8 fields, saw 9
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr471test/EVS/dev/drivers/scripts/prep/cam/jevs_cam_severe_prep.o143109080:Skipping line 6: expected 8 fields, saw 9
```
✔️ Output files look good.  No other concerns from me.

**Comment by PerryShafran-NOAA** [comment]
Thank you!  I will go ahead and merge the PR.

**Comment by MarcelCaron-NOAA** [comment]
> @MarcelCaron-NOAA Re-runs are finished. Please check to see that this run actually indeed used the parallel versions and also that everything worked fine.

Missed this.  The following run used the EVS parallel and beta versions of MET/METplus (met_ver=12.0.0-beta3, metplus_ver=6.0.0-beta3):  
jevs_cam_severe_prep.o14310908

**Review by PerryShafran-NOAA — APPROVED** [review]
Changes work as expected.  Ready for merge.

**Pull request merged**
