### PR TITLE
Feature/mesoscale plotting pcp sno

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

Both jobs (mesoscale/precip and /snowfall) were run several times, completed cleanly, and each results in a tarball that contains the necessary graphics for EVS/mesoscale/precip and EVS/mesoscale/snowfall.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

The ecf scripts can be submitted from the command line (`qsub {HOMEevs}/ecf/...`), but I normally run the jobs from the cron like this (replacing **{USER}** with your username and **{HOMEevs}** with the path to the EVS directory that is being tested):
```
0 0 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_mesoscale_precip_plots.out {HOMEevs}/ecf/scripts/mesoscale/plots/jevs_mesoscale_precip_plots.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_mesoscale_precip_plots.out 2>&1
0 0 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_mesoscale_snowfall_plots.out {HOMEevs}/ecf/scripts/mesoscale/plots/jevs_mesoscale_snowfall_plots.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_mesoscale_snowfall_plots.out 2>&1
```

The snowfall job should take about 2 1/2 hours to complete.  The precip job should take about 4 hours.  I can check for clean runs and a successfully outputted plots tarball for each of the two verif cases.

- [x] Has the code been checked to ensure that no errors occur during the execution? 
Yes

- [x] Do these updates/additions include sufficient testing updates? 
Yes

- [x] Please complete this pull request review by **[6/28/2023]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, @MarcelCaron-NOAA .  I will begin working on this PR.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, @MarcelCaron-NOAA .  Is there a way to test this not in cron?  Like maybe I can make the day PDYm2 or PDYm3, depending on what it's currently set as?

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Yes these don't have to be run in cron, and can be successfully run at any time of the day.  Both jobs use PDYm1 which is set in the J-job script.

**Comment by PerryShafran-NOAA** [comment]
Hi, Marcel,

I have been running this in cron since the switch, and it looks like the jobs were successful.  See the output files in /lfs/h2/emc/stmp/perry.shafran.

I also found the output tar files here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/mesoscale (and thanks for already writing them in ptmp!  I could not find the plot files anywhere else).

I'm also noting that you have the tar command being written directly to the final output directory.  I do believe that you need to do the tarring in your temporary working directory, and *then* move the tar file to the com directory after the tar.  That is, instead of this:

tar -cvf $COMOUT/file.tar *png

Do this:

tar -cvf $DATA/file.tar *png
cp $DATA/file.tar $COMOUT

Let me know if you have any questions on this.

Thanks!

Perry

Should be a simple change.  

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi Perry, glad that these jobs completed successfully, and thanks for checking the tar command!  I am currently troubleshooting some work laptop issues with NCO but will doublecheck the output from your tests, fix the tar commands and get back to you shortly.

**Comment by MarcelCaron-NOAA** [comment]
Hi @PerryShafran-NOAA apologies for the wait; I needed to fully replace my work laptop.  

Note the updates to the branch that fix the tar command as you instructed.  Otherwise, the plotting jobs look like they are completing successfully, with output tarballs that match what I'd been generating.  Maybe another run that includes the recent updates will confirm that this branch is ready to be merged.  Thanks.

**Comment by PerryShafran-NOAA** [comment]
Hi, Marcel,

Thank you.  Please note that since this is an active PR, you'll need to be sure that you bring in the develop branch that is under the new directory structure, as noted in Geoff's email regarding the new structure.  You will need to do this before this PR is accepted.

Also apparently there are some conflicts in the ush/mesoscale plot files.  Could be that the latest PR from @RoshanShrestha-NOAA made some changes in these files that should be resolved.  Adding in @ShelleyMelchior-NOAA for awareness as well, as she was working on Roshan's PRs.  Shelley - do you remember if there were plot changes?  

We want to make sure that the plot changes Roshan might have made are OK or if there are other changes to be made, we should take care of them.  

Perry

**Comment by MarcelCaron-NOAA** [comment]
Perry:  Yes you're right, I'll have to merge develop into this branch and fix some conflicts.  I'll get the updates listed in Geoff's email included as well.  Thanks

**Comment by PerryShafran-NOAA** [comment]
Since the develop has updates to the plotting codes, please re-run your precip plot jobs one more time to see if your jobs are still OK and what you expect.

Thanks!

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
Yes, despite efforts to get plots files out of Roshan's stats g2o PR, I think some still got through.

**Comment by PerryShafran-NOAA** [comment]
OK, so no changes should have been made?  

Looks like there are no more conflicts here, so at least that's good.

But now it looks like the entire ush/mesoscale directory is being changed, and plus there are some differences  in ush/cam too, which shouldn't be.  We will definitely need to be more careful in merging files.  

Perry

**Comment by AliciaBentley-NOAA** [comment]
Hi Perry and Shelley,

Does Marcel's PR fix the unintentionally changed scripts by reverting them
back to the way they were before, or are we past that point? Adding Logan
as well.

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
Hi, Alicia,

I don't know, I'm trying to figure that out.  Marcel can help us by letting us know for sure.  

Perry

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA I ran these updated jobs myself and they completed successfully.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA  - I would also assume that any scripts that were unintentionally changed by a previous PR by someone else is now corrected by this PR.  I don't know why there are cam changes, but I want to be sure that the files in *that* directory* aren't hosed somewhat.  Please validate.

Perry

**Comment by MarcelCaron-NOAA** [comment]
Sorry, I missed these latest comments.  

Some old versions of mesoscale plotting scripts had slipped into develop for the first time with the recent mesoscale/grid2obs/stats PR, but the conflicts encountered with this plotting PR were fixed manually (not reverted back).  Merging the PR should correctly update those plotting scripts.

@PerryShafran-NOAA I see the change you are referring to in ush/cam.  It seems like a few small changes were made to settings.py.  Is that right?  I can remove the changes from that file and push the updated file to this feature branch, if that sounds good to you.

**Comment by PerryShafran-NOAA** [comment]
The file should be unchanged from what it is in the authoritative repo.  Please make that change and push it to the branch, and then it should not show up as a changed file.

Perry

**Comment by RoshanShrestha-NOAA** [comment]
Are these changes affecting mesoscale scripts too? Let me know if I have to make any corrections.
Thanks 
-Roshan

**Comment by PerryShafran-NOAA** [comment]
@RoshanShrestha-NOAA - You won't be making any corrections in this PR, but Marcel is ensuring that the correct versions of the ush scripts are used in this particular PR.  You should be sure not to make corrections that would harm the plotting capability of snow and precip.  

From what I understand, your last PR was for stats only, but some plot files were changed as well.  Please take precautions when doing PRs so that if you are making only stats updates that plot files are left untouched in your feature branch.  

Perry

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA the cam/ush files that should not have been changed have been restored and they no longer appear under the "Files Changed" tab.  Thanks for catching this.

**Comment by PerryShafran-NOAA** [comment]
OK, thanks!  And also, all the files in ush/mesoscale are exactly the way you want them, is that correct?  

Perry

**Comment by MarcelCaron-NOAA** [comment]
Yes, each of the ush/mesoscale scripts are correctly changed.

Marcel

**Comment by PerryShafran-NOAA** [comment]
OK, thanks!  Do we need another check of the plot outputs?  Have you validated the plots that I've been creating?

Perry

**Comment by MarcelCaron-NOAA** [comment]
Yes the plots you've been creating look good, however the most recent set were outputted earlier this morning.  I think it would be good to check one more iteration that includes the updates that were pushed later this morning.

**Comment by PerryShafran-NOAA** [comment]
I have pulled in all the changes to my test branch on WCOSS2 and will let that run over the weekend.

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi @PerryShafran-NOAA, 

I am not seeing the output from this weekend, neither logs in /lfs/h2/emc/stmp/perry.shafran nor tarballs in /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/mesoscale.  Am I searching in the right folders?  Seemingly the updated jobs did not work.  Also, I know some have been having issues with the cron this weekend so it may be a cron issue.  

-Marcel

**Comment by PerryShafran-NOAA** [comment]
I have no idea as there is nothing in the cron.out directory.  If I just ran the scripts manually, would that work?

Perry

**Comment by MarcelCaron-NOAA** [comment]
Yeah running them manually is fine!  Anytime is also fine I believe.

**Comment by PerryShafran-NOAA** [comment]
Hi, Marcel,

I found out why the jobs weren't running - I didn't have HOMEevs set correctly after the changes were brought in.  I changed that for the test, and now the jobs are running.  I will let you know what happens after it completes.

Perry

**Comment by PerryShafran-NOAA** [comment]
I need to run this again now that we are on a new machine.  I will do so today.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, @MarcelCaron-NOAA ,

The results of the latest runs were not quite right.  I had to pull in the latest changes and make the runs all over again.  I will let you know the results.

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, @MarcelCaron-NOAA 

Now that Dogwood is back up, I can report on the runs from late Friday night.  

The tar files are here:  /lfs/h2/emc/ptmp/perry.shafran/EVS_out/com/evs/v1.0/plots/mesoscale

Note:  The COMOUT for the tar files should be /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/mesoscale.  We should not be using the EVS_out/com part of this.  However, I can change that when I run the parallel.  

The .o files are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr133test/EVS/dev/drivers/scripts/mesoscale/plots

Please validate to see if all looks good.

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi @PerryShafran-NOAA the logs indicate that the jobs completed cleanly, I did not notice any errors, and indeed the output tar files are what I expect in size.  Skimming their contents, they also look complete. 

I also took the liberty of pushing the corrected COMOUT directory names to the drivers scripts as you described.  Otherwise I am okay with merging this PR.

**Comment by PerryShafran-NOAA** [comment]
OK, great!  Let me do the code review and if all looks good, go ahead with the merge.

Perry

**Comment by PerryShafran-NOAA** [comment]
I just noticed that there are cam changes in this PR for radar and severe.  I'm not sure that they are meant to be in here?  Can we double check how they got there, before I merge this?

Otherwise, all the other file changes look standard, with the modulefile for the mesoscale plots and all that.  

Perry

**Comment by LoganDawson-NOAA** [comment]
@PerryShafran-NOAA thanks for flagging the changes to the dev drivers `jevs_cam_severe_plots.sh` and `jevs_cam_radar_plots.sh`. My guess on what happened is that Github made a couple mistakes when moving our old .ecf scripts into the new dev/drivers .sh scripts. I think it happened because similarly named placeholder files only included "sample" in the text. I had the same thing happened to me when I updated my fork following PR #145 being merged in.

@MarcelCaron-NOAA let's make sure the dev drivers you intended to include in this PR are in the correct file location.

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA @LoganDawson-NOAA Thanks for catching this.  I had similar issues where git would overwrite my driver data with the "sample" file of the same filename, but never that it copied data from a different filename.   

I checked and the mesoscale precip and snowfall driver scripts are fine, so I'll just push back the "sample" versions of radar and severe.  Let me know if there's a different better solution.  Thanks.

**Comment by LoganDawson-NOAA** [comment]
@MarcelCaron-NOAA pushing "sample" back in to remove the changes to those two files works. I did the same on my last PR.

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA Okay the radar and severe plots driver scripts should be back to normal.  I also merged some recent updates to develop so this PR should be able to merge smoothly.  Let me know if there are any other issues.

**Comment by PerryShafran-NOAA** [comment]
Confirmed - we are ready to merge.

Thanks!

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
