### PR TITLE
Feature/update_alaska_mrms

### PR DESCRIPTION
**Pull request by LoganDawson-NOAA**
## Pull Request Testing ##

This PR updates the MRMS product used to verify REFC in the Alaska CAM runs. This update is required due to the recent promotion of this product from dev/dcom to prod/dcom on WCOSS2.

- [ ] Describe testing already performed for this Pull Request:</br>

Testing of this update has been completed via cron jobs running in my personal parallel. The radar prep, stats, and plots steps have all been validated.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Unlike my prior PRs, there isn't a need to set up full cron jobs to test these changes. 

1. Clone the update_alaska_mrms feature branch
2. Grab updates to cron drivers from [here](https://github.com/LoganDawson-NOAA/EVS_crons/tree/main), and the jobs can be submitted interactively to confirm successful execution. The driver scripts listed below will need to be updated to point to the reviewer's location for $HOMEevs for each qsub command

3. **Prep step:** Run `drive_jevs_cam_radar_prep.sh` interactively (typically takes ~12-15 mins to complete)
4. **Stats step:** Run `drive_cam_radar_stats.sh` interactively after prior job completes. This will submit stats jobs for each jevs_${model}_radar_stats.sh script included in this PR.
The only wrinkle is steps 1 and 2 must be run during the same hour to ensure that hour's prep output is available for the stats jobs.

5. In `dev/drivers/scripts/cam/plots/jevs_cam_radar_plots.sh`, update COMIN to point to `/lfs/h2/emc/vpppg/noscrub/logan.dawson/evs/v1.0` (or symlink to your user space)
6. **Plots step:** Run `drive_jevs_cam_radar_plots.sh` interactively after the prior job completes. This will submit four batch jobs that will include four tarfiles.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes]**

- [ ] Please complete this pull request review by **[as soon as time allows]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@LoganDawson-NOAA , while I wait on other PRs to be updated w/ upstream develop, I will start on testing your PR. I have cloned your fork and checked out branch `update_alaska_mrms`. Just to be extra clear, it is only cam_radar steps that need to be tested, correct?

**Comment by LoganDawson-NOAA** [comment]
@ShelleyMelchior-NOAA yes, that's correct!

**Comment by ShelleyMelchior-NOAA** [comment]
Prep is underway. It has been running for 5 mins so far and I see content populating COMOUT now.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/cron.out/jevs_cam_radar_prep.o89925370`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/cam`

**Comment by LoganDawson-NOAA** [comment]
Prep output is as expected and the logfile is clean. We're good to proceed to the stats step.

**Comment by ShelleyMelchior-NOAA** [comment]
Stats processing is underway.
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/cron.out/jevs_cam_*_radar_stats.o*` (latest time stamps)
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam`

**Comment by LoganDawson-NOAA** [comment]
the stats step didn't work. I got a bunch of "MRMS Prep Data Missing" emails for these stats jobs.

the trick is the stats step has to be run in the same hour as the prep step so the MRMS prep output is available in your COMOUT location. The other option is to symlink to my prep directory `/lfs/h2/emc/vpppg/noscrub/logan.dawson/evs/v1.0/prep/cam` so you can access my prep output at any hour. 

On my cron, I launch `drive_jevs_cam_radar_prep.sh` at 5 minutes after the hour, and the output is usually all available by 20 minutes after the hour if WCOSS2 is running ok.

**Comment by LoganDawson-NOAA** [comment]
actually @ShelleyMelchior-NOAA, now that I think of it... 

Instead of rerunning prep or anything like that, you can just edit `drive_cam_radar_stats.sh` to define `VDATE=20230815` and `cyc=19` immediately before the job submission loop, and the stats jobs will use the data from your earlier prep run in testing this PR.

**Comment by ShelleyMelchior-NOAA** [comment]
Apologies for missing the key detail in your step 4. I will re-run stats per your suggestion.

**Comment by ShelleyMelchior-NOAA** [comment]
I re-ran stats for VDATE=20230815, cyc=19, and using my local COMIN (the prep files I produced yesterday).
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/cron.out/jevs_cam_*_radar_stats.o*` (time stamp 19:??)

**Comment by LoganDawson-NOAA** [comment]
@ShelleyMelchior-NOAA the stats processing was successful. The logfiles are error-free, and the same number of stat files were produced. (The stat file sizes are slightly different from mine because I didn't have you include the SPC outlook region verification masks.)

**Comment by LoganDawson-NOAA** [comment]
There's no need to run the plotting step. There are no plotting code changes included in this PR. The plotting code was previously set up to run either observation variable, so it will still work with the new observation variable.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The tests yield expected results. This PR is approved for merge.

**Pull request merged**
