### PR TITLE
bugfix/global_det_compath

### PR DESCRIPTION
**Pull request by malloryprow**
This PR includes:

1. Updates to COMIN compath.py usage following Wei's comments

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

> No testing has been done

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
> > **Set-up**
> 1. Clone my fork and checkout branch bugfix/global_det_compath
> 2. ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix
> 
> So I'm not sure if we want to run anything or what to run? COMIN is set in the driver scripts so it is not going to get to the point where it executes compath.py where the changes were made. Perhaps a test would be comment out COMIN in a driver script, but an exit statement after the COMIN in the J-Job and see if it works?

- [ ] Has the code been checked to ensure that no errors occur during the execution? **No**

- [ ] Do these updates/additions include sufficient testing updates? **No**

- [ ] Please complete this pull request review by **ASAP**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow @ShelleyMelchior-NOAA @PerryShafran-NOAA This PR matches the global_det request from Wei and is ready to test. I recommend what Mallory suggested above: Comment out COMIN in a dev driver, temporarily put an exit statement after COMIN in the J-Job and see what COMIN outputs, but don't run the job to completion. Thanks!

**Comment by PerryShafran-NOAA** [comment]
Hi, @malloryprow @AliciaBentley-NOAA ,

As expected, similar to Shannon's subseasonal test, this is a bit challenging to get to work when you comment COMIN in the dev driver, because you get the following (because there is no prod evs directory):

```
77 + compath.py prod/com/evs/v1.0.0
Could not find evs/v1.0
7 + export COMIN=
7 + COMIN=
```

But, I do note that in the J-jobs script in Wei's para directory on Cactus, this change has been made to the J-job:

`export COMIN=${COMIN:-$(compath.py ${envir}/com/$NET/$evs_ver)}`

And thus, I see in one of his output files, the following:

```
00 + compath.py para/com/evs/v1.0.0
1 + export COMIN=/lfs/h1/ops/para/com/evs/v1.0
1 + COMIN=/lfs/h1/ops/para/com/evs/v1.0
```

This would seem to indicate that this works in Wei's testing.  

Note:  even if we were to change envir=para, it still would not work on a Dogwood test because the /lfs/h1/ops/para/com/evs directory does not exist on Dogwood, only Cactus.  

All this to say:  the change seems to work in Wei's testing, which should make it good enough for us to merge.

**Comment by malloryprow** [comment]
Cool! Yeah I figured it be something kind of hard to test. We can merge then! Thanks!

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected merging.

**Pull request merged**
