### PR TITLE
feature/global_det_cartopy_data_dir

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

1. Remove catropyDataDir setting and usage

- [ ] Describe testing already performed for this Pull Request:</br>

> I ran jevs_global_det_atmos_grid2grid_snow_plots_31days.sh and confirmed the NOHRSC spatial map was produced.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> 1. Clone my fork and checkout branch feature/global_det_cartopyDataDir
> 2. cd sorc; ./build-fix-link.sh
> 3. Run dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_snow_plots_31days.sh, dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_snow_plots_90days.sh, dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_precip_plots_31days.sh, and dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_precip_plots_90days.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d. In the emc.vpppg parallel, these jobs run at 1945. The precip ones need the PCPCombine files generated from the grid2grid stats jobs. The snowfall just uses the NOHRSC data from dcom.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **11/17/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, @malloryprow - cloning your fork and getting to work on this.

**Comment by PerryShafran-NOAA** [comment]
I will run the jobs at 1945.  It is about an hour away from now.

**Comment by PerryShafran-NOAA** [comment]
Jobs are now underway!

**Comment by malloryprow** [comment]
Thank you! I will check in the morning and compare against the parallel!

**Comment by PerryShafran-NOAA** [comment]
The plot jobs have finished.

See the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr351test/EVS/dev/drivers/scripts/plots/global_det
and the plot tarballs are here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_det/atmos.20231113

**Comment by malloryprow** [comment]
Everything is good! Good to merge!

**Comment by PerryShafran-NOAA** [comment]
Excellent, thanks!  I will merge.

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
