### PR TITLE
feature/global_det_corrupt_data

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

This PR adds checks for data in dcom to see if the files are corrupted. It does runs `wgrib` for GRIB1 files, `wgrib2` for GRIB2 files, and `ncks` for netCDF files. If the command is successful, the prep work on the file is continued, if is not successful no prep is done on the file.

- [ ] Describe testing already performed for this Pull Request:</br>

> I created my own dcom directory with corrupted files. I checked the the right commands were being run according to the type of data and made sure the corrupted files were not a part of the final prepped archive.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

`export INITDATE=20240529`
`export DCOMINndbc=/lfs/h2/emc/vpppg/noscrub/mallory.row/verification/global/feature_global_det_corrupt_data`

NOTE: Let me know when you go to run this as depending on the time of day we may need to adjust the value of INITDATE
> 9. **Test 2 (corrupt data)**: Please add the additional lines in the job script before running again. 
`export INITDATE=20240529`
`export COMINcmc=/lfs/h2/emc/vpppg/noscrub/mallory.row/verification/global/feature_global_det_corrupt_data/cmc.$INITDATE`
`export DCOMROOT=/lfs/h2/emc/vpppg/noscrub/mallory.row/verification/global/feature_global_det_corrupt_data`
NOTE: For this test, @AliciaBentley-NOAA and I will get emails about missing FNMOC data. I forgot to fill in the rest of the directory for the FNMOC data and files only kept in its dcom directory for 3 days and it isn't saved in the dcom tar files on HPSS.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **06/20/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow Thanks for submitting this PR! I've looked over the changes and I think that they look great. Can you please add to your instructions that this should be tested with MET-11.0.2/METplus-5.0.1, as well as MET-12.0.0-beta4/METplus-6.0.0-beta4? That will help us remember. Thanks!

CC @PerryShafran-NOAA @ShelleyMelchior-NOAA

**Comment by malloryprow** [comment]
@AliciaBentley-NOAA Sure! These jobs don't use MET and or METplus, but did you want me to add testing instructions for stats jobs that use MET and METplus and the prep files?

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow Gotcha gotcha. Yes, I think testing at least one stats job with each version of MET/METplus/VE after the prep files are create will prove that the stats scripts still work. That would be enough of a sanity check. Thanks!

CC @PerryShafran-NOAA @ShelleyMelchior-NOAA

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I am starting with the global_det wave prep, non-corrupt version.

**Comment by PerryShafran-NOAA** [comment]
OK, the first job is complete.  This is the unchanged job, so I am guessing all would be OK.  But please look anyway.

The .o file is /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr486test/EVS/dev/drivers/scripts/prep/global_det/jevs_global_det_wave_prep_00.o134146923
And the output directory is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v2.0/prep/global_det/wave.20240602

Let's check that the baseline is OK before we move on to the corrupt file test.

**Comment by malloryprow** [comment]
All is good for Test 1 for global_det wave prep!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The test with the corrupt data is complete.  Please look at the .o file:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr486test/EVS/dev/drivers/scripts/prep/global_det/jevs_global_det_wave_prep_00.o134149858 and let me know if it is what you expect.

**Comment by malloryprow** [comment]
All is good for Test 2 for global_det wave prep! I see the message from python in the log file that it encountered a bad line but skipped it. The output is good too.

**Comment by PerryShafran-NOAA** [comment]
Oh, I didn't realize there was still output to be seen.  OK, this is good to know.  We'll move on to the atmos prep step.  We'll start with the normal version.

**Comment by malloryprow** [comment]
Sounds good! Job is good to run now without any changes to INITDATE for the normal job.

**Comment by PerryShafran-NOAA** [comment]
Normal run of prep is finished.

See the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr486test/EVS/dev/drivers/scripts/prep/global_det/jevs_global_det_atmos_prep_00.o134151188

Output is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v2.0/prep/global_det/atmos.20240602

**Comment by malloryprow** [comment]
All is good for Test 1 for global_det atmos prep!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow On to test 2.  Should I set SENDMAIL to NO, or did you want to see all those missing data emails?  I can also remove Alicia's email from this as well.

**Comment by malloryprow** [comment]
You can remove Alicia and just have them sent to me.

**Comment by AliciaBentley-NOAA** [comment]
Thanks, all! This afternoon has been beastly. Hahaha

**Comment by PerryShafran-NOAA** [comment]
Done!  Test is now underway.

**Comment by malloryprow** [comment]
Test 2 for global_det atmos prep failed. There was a permission issue on one of the files I made for the corrupted file test. Sorry about that!

> PermissionError: [Errno 13] Permission denied: '/lfs/h2/emc/vpppg/noscrub/mallory.row/verification/global/feature_global_det_corrupt_data/20240529/qpf_verif/METFRA_12_20240529.gz'

I fixed it though! Can we rerun?

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The run with corrupt data seems to be finished.  See the .o file here:  jevs_global_det_atmos_prep_00.o134153694

**Comment by PerryShafran-NOAA** [comment]
Yup, rerunning the atmos prep.

**Comment by malloryprow** [comment]
Re-run of Test 2 for global_det atmos prep is good! I see the "is corrupt" messages for the corrupted data files but they aren't in the prep archive.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The stats test is complete.  Please look at the .o file here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr486test/EVS/dev/drivers/scripts/stats/global_det/jevs_global_det_wave_gfs_grid2obs_stats_00.o134159193

And the stats output here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v2.0/stats/global_det, the 20240529 directories.

**Comment by malloryprow** [comment]
All good for global_det wave stats! The final stat only has a few hours but that is because the COMIN doesn't have many forecast hours.

I think all is well here, depending your code review.

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow and @PerryShafran-NOAA: I think this PR looks good and can be merged when Perry is ready. Thanks!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow @AliciaBentley-NOAA I have not run the stats test for MET v11.0.2/METplus v5.0.1 yet.  I'd have to run prep and stats for this test, as well as adjust the modulefile and the run.ver.  Let me proceed with this test.

**Comment by malloryprow** [comment]
Oh duh! Yes!! prep is not needed to run though. It doesn't use MET or METplus.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The runs have completed. 

Please see the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr486test/EVS/dev/drivers/scripts/stats/global_det/jevs_global_det_wave_gfs_grid2obs_stats_00.o134228938

And the output here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det, the 20240529 directories.

**Comment by malloryprow** [comment]
So the NDBC stats didn't run because it is looking in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/_v1.0_/prep/global_det, but the prep data from the previous tests is in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/_v2.0_/prep/global_det.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Gah, I ran the wrong prep (I ran atmos, not wave).  That's why that happened.  Let me try that again.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow OK please check again.

**Comment by malloryprow** [comment]
Much better! I see the NDBC stats now and it all looks good.

**Comment by PerryShafran-NOAA** [comment]
OK, now I can go ahead and merge.

**Comment by malloryprow** [comment]
Thanks!

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
