### PR TITLE
Updating ecf files to match the production ecf files

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

This PR is meant to ensure that the ecf files match the production ecf files currently in EVS v1.0.9.  This update adds in the commented out lines found in the production directory.  No testing is needed.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Great, Perry! I will run a diff against this PR's branch and the evs.v1.0.9 installation in $PACKAGEROOT to ensure agreement.

**Comment by ShelleyMelchior-NOAA** [comment]
Please check this ecf script: `ecf/scripts/stats/global_det/jevs_global_det_fnmoc_atmos_grid2obs_stats.ecf`
```
[clogin05 /lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/ps]$ diff -r -x .git EVS/ecf/scripts/stats/global_det/jevs_global_det_fnmoc_atmos_grid2obs_stats.ecf /lfs/h1/ops/prod/packages/evs.v1.0.9/ecf/scripts/stats/global_det/jevs_global_det_fnmoc_atmos_grid2obs_stats.ecf
6a7
> ##PBS -l walltime=00:15:00
```

**Comment by PerryShafran-NOAA** [comment]
Fixed.

**Comment by ShelleyMelchior-NOAA** [comment]
Great. Thanks.

And what was decided in chat about this file? `ecf/defs/evs-nco.def`
```
[clogin05 /lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/ps]$ diff -r -x .git EVS/ecf/defs/evs-nco.def /lfs/h1/ops/prod/packages/evs.v1.0.9/ecf/defs/evs-nco.def
515c515
<               trigger :TIME >= 0945 and ../../../../00/evs/prep/global_ens/jevs_global_ens_atmos_prep == complete
---
>               trigger :TIME >= 1000 and ../../../../00/evs/prep/global_ens/jevs_global_ens_atmos_prep == complete
590c590
<               time 05:30
---
>               time 07:00
797c797
<               time 07:30
---
>               time 08:30
```

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA I think that Perry made those changes today, but after you ran your diff command! Can you bring in the latest version and do the diff of that file one more time?

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA These changes were made at the request of Simon of NCO - to ensure that these jobs would finish in time for a machine switch.  That is why the kickoff time of these jobs were changed.

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA @ShelleyMelchior-NOAA Interesting - according to Shelley's comment above, the changes requested by Simon are *not* in the current defs file in production.

**Comment by ShelleyMelchior-NOAA** [comment]
If indeed the PR branch is correct and $PACKAGEROOT is out of date, I think this PR is in good shape upon initial inspection.

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA @PerryShafran-NOAA I just emailed NCO about EVS v1.0.9 not having the updated trigger times that Simon said that he made, but didn't make it in. I added Steven Earle, too. We'll see what they say to do now!

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA Please go ahead and merge this PR.  We will make further walltime adjustments that Simon is suggesting in a new PR.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All expected changes are present.

**Comment by ShelleyMelchior-NOAA** [comment]
This PR is approved for merge.

**Pull request merged**
