### PR TITLE
Bugfix/rtofs-EVSINprep

### PR DESCRIPTION
**Pull request by ShelleyMelchior-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

This PR replaces COMOUTprep w/ EVSINprep where appropriate.
When the code is reading in data in the prep step com directory, the EVSINprep variable is used in place of COMOUTprep.
When the code is writing out data to the prep step com directory, the COMOUTprep variable is retained.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Clone my fork and check out branch `bugfix/rtofs-EVSINprep`.
Change the prep driver script to point COMIN to use emc.vpppg instead of $USER.
Add a line to the prep driver script to force the processing to use VDATE of 3 days ago: `export VDATE=20231204`
The runtime should take just over 3 hours.
There should be no WARNING messages related to finding files in the rtofs prep com directory.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I kicked off a local run of the prep processing to have it run in parallel to Perry's test. Mine is 7 minutes in and running fine so far.

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA The test is underway.  

The .o file would be here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr382test/EVS/dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.o120586817

The prep data would be here:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs/rtofs.20231204

**Comment by ShelleyMelchior-NOAA** [comment]
Great, thanks Perry. I am keeping an eye on things.

**Comment by PerryShafran-NOAA** [comment]
Code review looks good.  Mainly was checking to see where COMOUTprep was changed to EVSINprep in all the right places, and where COMOUTprep was kept because that's where data is being written.  Looks like the changes were made in the proper places and left the same where they should have been left alone.

And looking at the .o file, EVSINprep and COMOUTprep are properly defined:

EVSINprep=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/rtofs
COMOUTprep=/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs

So far, looking good, and no missing file WARNINGs thus far.

@ShelleyMelchior-NOAA @AliciaBentley-NOAA @malloryprow

**Comment by ShelleyMelchior-NOAA** [comment]
Perry's run for rtofs prep, and my local run for rtofs prep, have completed.
WARNING messages that exist do not relate to finding files in the prep com directory.

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA @PerryShafran-NOAA Sounds good! Changes here make sense. I approve merging.

**Review by PerryShafran-NOAA — APPROVED** [review]
Approving for merge.

**Pull request merged**
