### PR TITLE
Bugfix/remove mping verification

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

Updated cam/grid2obs/stats jobs were run without a prep step and completed successfully.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

I recommend running the following jobs interactively:
```
{HOMEevs}/dev/drivers/scripts/cam/stats/jevs_cam_hireswarw_grid2obs_stats.sh
{HOMEevs}/dev/drivers/scripts/cam/stats/jevs_cam_hireswarwmem2_grid2obs_stats.sh
{HOMEevs}/dev/drivers/scripts/cam/stats/jevs_cam_hireswfv3_grid2obs_stats.sh
{HOMEevs}/dev/drivers/scripts/cam/stats/jevs_cam_hrrr_grid2obs_stats.sh
{HOMEevs}/dev/drivers/scripts/cam/stats/jevs_cam_namnest_grid2obs_stats.sh
```

Where {HOMEevs} is the path of the EVS testing directory.

Finally, for testing, edit the definition for COMINspcotlk in the driver scripts so that it matches the following:
`export COMINspcotlk=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver/prep/$COMPONENT`

- [x] Has the code been checked to ensure that no errors occur during the execution? **[Yes]**

- [x] Do these updates/additions include sufficient testing updates? **[Yes]**

- [x] Please complete this pull request review by **[08/30/2023]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Will be working on this right now.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, @MarcelCaron-NOAA 

All the jobs finished.  Please look at the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr219test/EVS/dev/drivers/scripts/cam/stats

And the stat files are here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/atmos.20230828

Please examine these items and let me know if that is what you expect.

Perry

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA Thanks for running this so quickly.  I checked the output logs and all completed cleanly.  The output stat files match what I was seeing in my tests.  This looks successful to me.

**Comment by PerryShafran-NOAA** [comment]
Thank you.  I will go ahead and merge then.  

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
