### PR TITLE
feature/update_obsproc_v1.3

### PR DESCRIPTION
**Pull request by malloryprow**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

This PR includes updates to support the EVS code delivery for obpsroc v1.3. It includes

1. Add 'Saildrone' into the title for SFCSHP obs for global_det wave plots.
2. Increase memory: global_det atmos stats GFS grid2obs, global_det wave stats GFS grid2obs, global_ens wave stats grid2obs, nfcens wave stats grid2obs,
3. Adjust walltimes: cam href grid2obs stats

## Developer Questions and Checklist
* Is this a high priority PR? If so, why and is there a date it needs to be merged by?
> Yes, the code delivery for obsproc v1.3 is 10/4.
* Do you have any planned upcoming annual leave/PTO?
> No
* Are there any changes needed for when the jobs are supposed to run?
> No

- [x] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [x] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [x] References the feature branch for `HOMEevs` are removed from the code.
- [x] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [x] Jobs over 15 minutes in runtime have restart capability.
- [x] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [x] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [x] Code is using METplus wrappers structure and not calling MET executables directly.
- [ ] Log is free of any ERRORs or WARNINGs.

###  **Set-up**
1. Clone my fork and checkout branch feature/global_det_atmos_plots_units
2. `ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix`
3. Uncomment `evs_ver` in `versions/run.ver`

### :heavy_check_mark:   **global_det plots**
4. `cd dev/drivers/scripts/plots/global_det`
5. Run `jevs_global_det_wave_grid2obs_plots_31days.sh` and `jevs_global_det_wave_grid2obs_plots_90days.sh`.
> - Set `HOMEevs` to the location of the clone.
> - Set `COMIN=/lfs/h1/ops/prod/com/$NET/$evs_ver_2d`

### :heavy_check_mark:  **cam stats**
6. `cd dev/drivers/scripts/stats/cam`
7. Run `jevs_cam_href_grid2obs_stats.sh`.
> - Set `HOMEevs` to the location of the clone.
> - Set `COMIN=/lfs/h1/ops/prod/com/$NET/$evs_ver_2d`
> - Set `COMINobsproc=/lfs/h2/emc/vpppg/noscrub/mallory.row/EVS_obsproc_v1.3_test/obsproc/${obsproc_ver}`

### :black_square_button:  **global_det stats**
6. `cd dev/drivers/scripts/stats/global_det`
7. Run `jevs_global_det_atmos_gfs_grid2obs_stats.sh` and `jevs_global_det_wave_gfs_grid2obs_stats.sh`.
> - Set `HOMEevs` to the location of the clone.
> - Set `COMIN=/lfs/h1/ops/prod/com/$NET/$evs_ver_2d`
> - Set `COMINobsproc=/lfs/h2/emc/vpppg/noscrub/mallory.row/EVS_obsproc_v1.3_test/obsproc/${obsproc_ver}`

### :heavy_check_mark: **global_ens wave prep and stats**
6. `cd dev/drivers/scripts/prep/global_ens`
7. Run `jevs_global_ens_wave_grid2obs_prep.sh`.
> - Set `HOMEevs` to the location of the clone.
> - Set `COMIN=/lfs/h1/ops/prod/com/$NET/$evs_ver_2d`
> - Set `COMINobsproc=/lfs/h2/emc/vpppg/noscrub/mallory.row/EVS_obsproc_v1.3_test/obsproc/${obsproc_ver}/gdas`
8. We will need to link the prod global_ens wave prep to where the prep output from the test was written. We can work on this when we get to this step.
9. Run `jevs_global_ens_wave_grid2obs_stats.sh`.
> - Set `HOMEevs` to the location of the clone.
> - Maybe need to adjust `COMIN`

### :heavy_check_mark: **nfcens prep and stats**
10. `cd dev/drivers/scripts/prep/nfcens`
7. Run `jevs_nfcens_wave_grid2obs_prep.sh`.
> - Set `HOMEevs` to the location of the clone.
> - Set `COMIN=/lfs/h1/ops/prod/com/$NET/$evs_ver_2d`
> - Set `COMINobsproc=/lfs/h2/emc/vpppg/noscrub/mallory.row/EVS_obsproc_v1.3_test/obsproc/${obsproc_ver}/gdas`
8. We will need to link the prod nfcens prep to where the prep output from the test was written. We can work on this when we get to this step.
9. Run `jevs_nfcens_wave_grid2obs_stats.sh`.
> - Set `HOMEevs` to the location of the clone.
> - Maybe need to adjust `COMIN`

### CODE REVIEW

**Review by AliciaBentley-NOAA — APPROVED** [review]
I have reviewed this PR and found that the memory and wallclock time increases needed to use obsproc/1.3 make sense. I also found that there was an .ecf change that corresponded to every dev/driver change, which was good. I approve this PR to be merged after any appropriate testing is done. Thanks!

@malloryprow @PerryShafran-NOAA

**Review by AndrewBenjamin-NOAA — APPROVED** [review]
I agree with Alicia's assessment: I think the adjustments to job memory and wallclock time make sense. Thank you for working to get obsproc v1.3 into EVS, I approve these changes.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow @AliciaBentley-NOAA @AndrewBenjamin-NOAA Please let me know if you want me to add an additional test for any memory or wallclock increases.  Otherwise I'll just test the plot codes.

**Comment by malloryprow** [comment]
You can test the plots and I will add instructions for the other ones!

**Comment by AndrewBenjamin-NOAA** [comment]
> @malloryprow @AliciaBentley-NOAA @AndrewBenjamin-NOAA Please let me know if you want me to add an additional test for any memory or wallclock increases. Otherwise I'll just test the plot codes.

My thought would be to test everything. 

> You can test the plots and I will add instructions for the other ones!

I agree, once Mallory adds instructions, please also test the memory/wallclock increases

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Just want to make sure:  the description says cam href stats is changed, but your instructions say cam hrrr stats to test.  Just want to confirm which one it should be.

**Comment by malloryprow** [comment]
Yes, it is the only one changed.

**Comment by malloryprow** [comment]
Typo!

**Comment by PerryShafran-NOAA** [comment]
So it should be hrrr?

**Comment by PerryShafran-NOAA** [comment]
Oh, you changed to href.  Thanks!

**Comment by malloryprow** [comment]
HREF

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The HREF run failed.  I think it's due to a missing gdas file:

See: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/stats/cam/jevs_cam_href_grid2obs_stats.o156764727


```
7.618 + echo 'Warning:  No GFS or RAP Prepbufr data available for 20240929'
7.618 + 1> mailmsg
7.620 + echo Missing file is /lfs/h2/emc/vpppg/noscrub/mallory.row/EVS_obsproc_v1.3_test/obsproc/v1.3/rap.20240929/rap.t12z.prepbufr.tm00 or /lfs/h2/emc/vpppg/noscrub/mallory.row/EVS_obsproc_v1.3_test/obsproc/v1.3/gdas.20240929/00/atmos/gdas.t00z.prepbufr

```

```
13 (clogin09) /lfs/h2/emc/vpppg/noscrub/mallory.row/EVS_obsproc_v1.3_test/obsproc/v1.3/gdas.20240929/00/atmos > ls
14 (clogin09) /lfs/h2/emc/vpppg/noscrub/mallory.row/EVS_obsproc_v1.3_test/obsproc/v1.3/gdas.20240929/00/atmos >
```

I'm pretty sure this is why this didn't run.

**Comment by malloryprow** [comment]
That's a bummer looks like in the obsproc parallel for GDAS there is only the 18Z prepbufr file for that date.

> **`ls /lfs/h2/emc/stmp/iliana.genkova/CRON/R13/com/obsproc/v1.3/gdas.20240929/*/atmos/gdas.t*z.prepbufr`**
> /lfs/h2/emc/stmp/iliana.genkova/CRON/R13/com/obsproc/v1.3/gdas.20240929/18/atmos/gdas.t18z.prepbufr

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The global_det wave stats jobs is complete:

wave: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_gfs_grid2obs_stats_00.o156764168
output: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/gfs.20240929, wave.20240929

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The global_det wave plot jobs are complete:

See the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/plots/global_det
and the plot tarballs here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_det/wave.20240929

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The global_ens prep job is complete.

See here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/prep/global_ens/jevs_global_ens_wave_grid2obs_prep.o156764327
output here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/wave.20240929/gefs/grid2obs

FYI - I only see one prepbufr file in this directory.  Shouldn't there be 4 prepbufr files in here?  Can we verify?

**Comment by PerryShafran-NOAA** [comment]
@malloryprow We have the missing GDAS file for nfcens also.

See /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/prep/nfcens/jevs_nfcens_wave_grid2obs_prep.o156764358

**Comment by malloryprow** [comment]
> @malloryprow The global_det wave plot jobs are complete:
> 
> See the .o files here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/plots/global_det and the plot tarballs here: /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_det/wave.20240929

This is good. I confirm I see 'Saildrone' in the titles.

**Comment by malloryprow** [comment]
> @malloryprow The global_ens prep job is complete.
> 
> See here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/prep/global_ens/jevs_global_ens_wave_grid2obs_prep.o156764327 output here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/wave.20240929/gefs/grid2obs
> 
> FYI - I only see one prepbufr file in this directory. Shouldn't there be 4 prepbufr files in here? Can we verify?

Correct. See my message about the missing GDAS prepbufr files in the obsproc parallel for 20240929.

**Comment by PerryShafran-NOAA** [comment]
> That's a bummer looks like in the obsproc parallel for GDAS there is only the 18Z prepbufr file for that date.
> 
> > **`ls /lfs/h2/emc/stmp/iliana.genkova/CRON/R13/com/obsproc/v1.3/gdas.20240929/*/atmos/gdas.t*z.prepbufr`**
> > /lfs/h2/emc/stmp/iliana.genkova/CRON/R13/com/obsproc/v1.3/gdas.20240929/18/atmos/gdas.t18z.prepbufr

Oh, that would seem to be why there is only one prepbufr file in the global_ens job.

Do we need to re-adjust dates for these tests?

**Comment by malloryprow** [comment]
Given the missing GDAS prepbufr files for 20240929, we may have to consider using another VDATE but that could also mean that needed prep data could have aged off in ops.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Running the jobs this morning, since the obsproc 1.3 files are all there for today.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The global_ens prep is finished.

See .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/prep/global_ens/jevs_global_ens_wave_grid2obs_prep.o156849921
The output directory is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/wave.20240930

I see 4 prepbufr files, so this run looks good.  Please validate.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The nfcens prep job is complete.

See the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/prep/nfcens/jevs_nfcens_wave_grid2obs_prep.o156851151
The output directory is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/nfcens/wave.20240930

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The global_det stats wave job is finished.

See the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/stats/global_det/jevs_global_det_wave_gfs_grid2obs_stats_00.o156849874
Small stats files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/wave.20240930
Final stat file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/gfs.20240930

**Comment by malloryprow** [comment]
> @malloryprow The global_ens prep is finished.
> 
> See .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/prep/global_ens/jevs_global_ens_wave_grid2obs_prep.o156849921 The output directory is here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/wave.20240930
> 
> I see 4 prepbufr files, so this run looks good. Please validate.

This one looks good!

Now to test stats we will need to link /lfs/h1/ops/prod/com/evs/v1.0/prep/global_ens/wave.[20240912-20240929] into /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens. Then we can run stats.

**Comment by malloryprow** [comment]
> /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/prep/nfcens/jevs_nfcens_wave_grid2obs_prep.o156851151

Looks good!

Now to test stats we will need to link /lfs/h1/ops/prod/com/evs/v1.0/prep/nfcens/wave.[20240918-20240929] into /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/nfcens. Then we can run stats.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Running the stats for global_ens and nfcens.  Thanks to your suggestion to link to the prod archive, no change to COMIN was needed for either.

**Comment by malloryprow** [comment]
> @malloryprow The global_det stats wave job is finished.
> 
> See the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/stats/global_det/jevs_global_det_wave_gfs_grid2obs_stats_00.o156849874 Small stats files here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/wave.20240930 Final stat file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/gfs.20240930

Can you remove /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/wave.20240930 and /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/gfs.20240930 and run again? prep had not run in ops yet.

**Comment by PerryShafran-NOAA** [comment]
Yes, re-running those two jobs now.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The global_ens wave stats job is complete.  

See the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/stats/global_ens/jevs_global_ens_wave_grid2obs_stats.o156854316
Small stats files:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens/wave.20240930
Large stats file: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens/gefs.20240930

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The nfcens wave stats job is complete.

See the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/stats/nfcens/jevs_nfcens_wave_grid2obs_stats.o156854429
Small stats files:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/nfcens/wave.20240930
Large stats file: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/nfcens/nfcens.20240930

**Comment by malloryprow** [comment]
> @malloryprow The global_ens wave stats job is complete.
> 
> See the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/stats/global_ens/jevs_global_ens_wave_grid2obs_stats.o156854316 Small stats files: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens/wave.20240930 Large stats file: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens/gefs.20240930

global_ens wave is good!

**Comment by malloryprow** [comment]
> @malloryprow The nfcens wave stats job is complete.
> 
> See the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/stats/nfcens/jevs_nfcens_wave_grid2obs_stats.o156854429 Small stats files: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/nfcens/wave.20240930 Large stats file: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/nfcens/nfcens.20240930

nfcens is good!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The global_det wave stats re-run is finished.

See the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_gfs_grid2obs_stats_00.o156855423

The stats files are in the same location as above.

**Comment by PerryShafran-NOAA** [comment]
> @malloryprow The global_det wave stats re-run is finished.
> 
> See the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_gfs_grid2obs_stats_00.o156855423
> 
> The stats files are in the same location as above.

Oops, I put in the atmos output file.  Correct one for wave is jevs_global_det_wave_gfs_grid2obs_stats_00.o156855425

**Comment by malloryprow** [comment]
> > @malloryprow The global_det wave stats re-run is finished.
> > See the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr570test/EVS/dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_gfs_grid2obs_stats_00.o156855423
> > The stats files are in the same location as above.
> 
> Oops, I put in the atmos output file. Correct one for wave is jevs_global_det_wave_gfs_grid2obs_stats_00.o156855425

global_det wave is good!

**Comment by malloryprow** [comment]
Could we kill jevs_global_det_atmos_gfs_grid2obs_stats_00.o156855423 and run with VDATE=20240929?

**Comment by PerryShafran-NOAA** [comment]
> Could we kill jevs_global_det_atmos_gfs_grid2obs_stats_00.o156855423 and run with VDATE=20240929?

Sure, will do.

**Comment by malloryprow** [comment]
Awesome!

That just leaves then:

1. href grid2obs stats
2. gfs grid2obs stats

The HREF ones takes a long time.

**Comment by malloryprow** [comment]
Checked the HREF and all is good there.

When we are back from the verification meeting, can we run the GFS job again but for VDATE=20240930? I forgot we didn't have the prepbufr files for 20240929. :face_exhaling:

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Oops!  Hey, I forgot about that as well.  Unfortunately, the GFS job is not likely to be done by the time your workday ends, but it should be good to go first thing tomorrow morning.  

Can you check mark cam stats above, if all is good there?  Thanks!

**Comment by malloryprow** [comment]
I'll check it first thing tomorrow!

**Comment by malloryprow** [comment]
GFS grid2obs: The re-run had a missing 21Z NAM prepbufr file but otherwise I think everything looks good!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow OK, great!  Since we already have 2 approvals from both Alicia and Andrew, I'll review the code and then go ahead and merge.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
