### PR TITLE
Correct valid initialization time lists for alaska forecast templates

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

jevs_cam_*_radar_stats jobs were looking for incorrect forecasts when verifying over alaska.  This PR fixes the lists of valid initialization times that may be used to fill forecast file templates.

All affected jobs were submitted as they are in the parallel and none outputted missing data mail messages for forecast files.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Same process as in the recent cam PRs:
### (1) Set up jobs 
•	symlink the EVS_fix directory locally as "fix"
•	In all driver scripts, point all exports of "HOMEevs" to your EVS test directory
•	In all driver scripts, change COMIN to the parallel directory (`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`)
•	Optional: In all stats drivers scripts, add your email address to the "MAILTO" list
### (2) Test Jobs
Use the following to submit each job: `qsub –v vhr=00 `

From your EVS testing directory, the following scripts should be run using the set up in step (1):
```
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_radar_stats.sh

```

_[Total: 0 prep jobs, 6 stats jobs, 0 plots jobs]_

No errors should occur, and no missing forecast emails should be received (unless the forecast is needed and missing)

- [x] Has the code been checked to ensure that no errors occur during the execution? **YES**

- [x] Do these updates/additions include sufficient testing updates? **YES**

- [x] Please complete this pull request review by **12/08/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @MarcelCaron-NOAA , your fork has been cloned and branch `bugfix/cam_radar_stats` has been checked out.
I have submitted the 6 radar jobs for VDATE=20231205 and vhr=02. The logfiles are listed below.
```
[clogin06 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ lltr jevs_cam_*radar*stats.o9503*
-rw-r--r-- 1 shelley.melchior emc 1133086 Dec  6 03:42 jevs_cam_hrrr_radar_stats.o95034691
-rw-r--r-- 1 shelley.melchior emc 1208129 Dec  6 03:44 jevs_cam_hireswfv3_radar_stats.o95034648
-rw-r--r-- 1 shelley.melchior emc 1565075 Dec  6 03:44 jevs_cam_hireswarwmem2_radar_stats.o95034642
-rw-r--r-- 1 shelley.melchior emc 1685590 Dec  6 03:44 jevs_cam_href_radar_stats.o95034689
-rw-r--r-- 1 shelley.melchior emc 1465605 Dec  6 03:44 jevs_cam_hireswarw_radar_stats.o95034645
-rw-r--r-- 1 shelley.melchior emc 1212589 Dec  6 03:44 jevs_cam_namnest_radar_stats.o95034703
```

**Comment by ShelleyMelchior-NOAA** [comment]
I have also submitted the 6 radar jobs for VDATE=20231204 and vhr=23. The logfiles are listed below.
```
[clogin06 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ lltr jevs_cam_*radar*stats*.o95035*
-rw-r--r-- 1 shelley.melchior emc 1133826 Dec  6 03:51 jevs_cam_hrrr_radar_stats.o95035237
-rw-r--r-- 1 shelley.melchior emc 1589963 Dec  6 03:53 jevs_cam_hireswarwmem2_radar_stats.o95035204
-rw-r--r-- 1 shelley.melchior emc 1579218 Dec  6 03:53 jevs_cam_hireswarw_radar_stats.o95035205
-rw-r--r-- 1 shelley.melchior emc 1719714 Dec  6 03:54 jevs_cam_hireswfv3_radar_stats.o95035209
-rw-r--r-- 1 shelley.melchior emc 1390545 Dec  6 03:56 jevs_cam_namnest_radar_stats.o95035239
-rw-r--r-- 1 shelley.melchior emc 2809151 Dec  6 03:56 jevs_cam_href_radar_stats.o95035236
```

**Comment by ShelleyMelchior-NOAA** [comment]
For completeness, I have also submitted the 6 radar jobs for VDATE=20231205 and vhr=00. The logfiles are listed below.
```
[clogin06 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ lltr jevs_cam_*radar*stats*.o950354*
-rw-r--r-- 1 shelley.melchior emc 1133295 Dec  6 03:59 jevs_cam_hrrr_radar_stats.o95035455
-rw-r--r-- 1 shelley.melchior emc 1565842 Dec  6 04:00 jevs_cam_hireswarwmem2_radar_stats.o95035451
-rw-r--r-- 1 shelley.melchior emc 1555255 Dec  6 04:00 jevs_cam_hireswarw_radar_stats.o95035452
-rw-r--r-- 1 shelley.melchior emc 1710956 Dec  6 04:01 jevs_cam_href_radar_stats.o95035454
-rw-r--r-- 1 shelley.melchior emc 1695478 Dec  6 04:01 jevs_cam_hireswfv3_radar_stats.o95035453
-rw-r--r-- 1 shelley.melchior emc 1307796 Dec  6 04:01 jevs_cam_namnest_radar_stats.o95035456
```

**Comment by MarcelCaron-NOAA** [comment]
Can you rerun for hrrr?  The COMIN value is "emc.vppg" instead of "emc.vpppg" 😆 

Either of the two submissions I think is fine.

**Comment by ShelleyMelchior-NOAA** [comment]
> Can you rerun for hrrr? The COMIN value is "emc.vppg" instead of "emc.vpppg" 😆
> 
> Either of the two submissions I think is fine.

oh darn!

**Comment by ShelleyMelchior-NOAA** [comment]
> Can you rerun for hrrr? The COMIN value is "emc.vppg" instead of "emc.vpppg" 😆
> 
> Either of the two submissions I think is fine.

The third case has been resubmitted for hrrr: VDATE=20231205, vhr=00.

**Comment by MarcelCaron-NOAA** [comment]
The hrrr job has finished running.

✔️ There are no missing data emails for the recent hrrr job and any of the other jobs.  Also, no hits when I grepped each output file using:
`grep "FATAL ERROR\|Missing\|Error\|error\|Killed\|Cgroup"`

✔️ I checked all output files, and they all include alaska stats:
`ls /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam/atmos.20231205/*/radar`

✔️ All jobs look good to me!

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Changes look good. Tests yield expected results. This PR is approved for merge.

**Pull request merged**
