### PR TITLE
WAFS cyc rename and fix no data found errors

### PR DESCRIPTION
**Pull request by YaliMao-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
@YaliMao-NOAA I have looked over this PR and I think that it looks good. You've checked off all of the boxes in the EE2 document as well. I approve this PR for testing.

@PerryShafran-NOAA @ShelleyMelchior-NOAA

**Comment by PerryShafran-NOAA** [comment]
I have begun work on this PR.  

@AliciaBentley-NOAA to be clear, we only need to look at the stats job for this PR, yes?

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Please test both the WAFS stats and plots scripts, even though only stats will be submitted in the EVSv1 code delivery. The closer we get plots to following EE2 standards, the easier it will be to incorporate plots into EVSv2. 

Thanks for asking! I hope testing plots won't take too much time.

**Comment by YaliMao-NOAA** [comment]
I just saw a new item: 'Update maillist variable to MAILTO variable using find/replace before code delivery'.
Should I include it in this PR? If so, can you merge after I'm done with it?

**Comment by AliciaBentley-NOAA** [comment]
@YaliMao-NOAA Thank you for checking, but you don't need to make that update. Perry/Shelley are going to change maillist to MAILTO across EVS in a "clean up" PR before code delivery. Thank you for staying on top of things in the EE2 checklist! I'll add a note to make it clearer that that particular comment is for the code managers. Thanks!

**Comment by PerryShafran-NOAA** [comment]
@YaliMao-NOAA I found an error in your stats job:

In /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr322test/EVS/dev/drivers/scripts/stats/wafs/jevs_wafs_stats.o107720138

`10/30 12:56:04.184 metplus (command_builder.py:257) ERROR: (command_builder.py:656) Could not find FCST_INPUT file /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_wafs_stats.107720138.dbqs01/GCIP_0P25_data/uk.2023102815.f09.grib2 using template uk.{init?fmt=%Y%m%d%H}.f{lead?fmt=%HH}.grib2`

There are a bunch of errors looking at this.  

Are we checking to see that the ukmet data exists before using them?  

We need to make sure that there are no errors.  Should we be looking for 15Z data?  It looks like the dcom directories only have data for 00Z, 06Z, 12Z, and 18Z.  Please take a look at this.  

@AliciaBentley-NOAA @ShelleyMelchior-NOAA for awareness.

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA @AliciaBentley-NOAA Yes, those error messages are expected. Do you know how to configure variables to do verification with the observation data valid at 00z, 03z, 06z, ... 21z, but forecast data at 00z, 06z, 12z and 18z?

**Comment by PerryShafran-NOAA** [comment]
@YaliMao-NOAA We can't have ERROR messages, even if expected.  We'd need to fix this.

That said, since I don't know your code that well, I'm not entirely sure what to set in order to do this.  I do it all the time, but I only do one valid hour per run.  Like, you need to set your forecast hours that make sense for each model cycle.  Like, I check to see that files exist, and if they do, then I put that into a fcsthours list that I pass into METplus for my forecast hours.

**Comment by PerryShafran-NOAA** [comment]
@YaliMao-NOAA 

See if you can follow the logic in lines 38 through 57 - this creates a list of fcsthours that I use in METplus when I run nam_firewxnest.  This model runs at 00Z, 06Z, 12Z, and 18Z, but has hourly output that I verify, based on the files you find.  

https://github.com/NOAA-EMC/EVS/blob/develop/scripts/stats/cam/exevs_cam_nam_firewxnest_grid2obs_stats.sh

Thus if you run this for valid hour 00Z, you'll get fcsthours=00, 06, 12, 18, 24, 30, 36 (and so on)
For valid hour 03Z, you'll get fcsthours=03, 09, 15, 21, 27, 33 (and so on)

Pass those fcsthours into METplus, assuming you are cycling by valid hour.

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA Thank you for the instructions to create different forecast hours list for different valid hours. I've modified the code. I did a test and the errors were gone. Thank you a bunch!

**Comment by PerryShafran-NOAA** [comment]
Hi, @YaliMao-NOAA ,

I re-ran your latest code, and indeed the word "ERROR" did not appear!  This is good news.

Please validate your data.  You can see the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr322test/EVS/dev/drivers/scripts/stats/wafs/jevs_wafs_stats.o107798049

Please look at the output stat files:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/wafs/*20231030*

Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA Yes, both log file and stat files are good. The stat files are the same without 'ERROR' as with 'ERROR' as expected, because the 'ERROR' messages are all about forecast files which don't exist.

**Comment by PerryShafran-NOAA** [comment]
@YaliMao-NOAA Great to hear that the stat files are looking good with your fix in there, and glad to have done it so quickly!

I've been asked to test wafs plots as well, just to see if it works.  wafs plots will not be in the production code, but it will be run in dev and we need to check that it works.  Stay tuned for the results of that test!

**Comment by PerryShafran-NOAA** [comment]
@YaliMao-NOAA wafs plotting is complete:

Please check the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr322test/EVS/dev/drivers/scripts/plots/wafs/jevs_wafs_plots.o107807544

The plot tarballs are here: /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/wafs/atmos.20231030

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA Plots look good. Thank you for testing

**Comment by PerryShafran-NOAA** [comment]
Excellent!  Can you please do a sync fork so I can merge in this PR?

**Review by PerryShafran-NOAA — APPROVED** [review]
Changes look good.  Approved for merge.

**Pull request merged**
