### PR TITLE
Feature/ee2 rev4 rtofs

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
This PR fixes the potential syntax errors that may occur due to the future missing observational data. It was observed that sometimes the observational data have abnormal sizes while they exist that causes syntax errors in the .o files. To prevent this, the size of the data file is checked in addition to its existence.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
clone my EVS repository in your local, then find the driver scripts located at: EVS/dev/drivers/scripts
To test the stats scripts for SMOS, AVISO and GHRSST, please run:
dev/drivers/scripts/stats/rtofs/jevs_rtofs_smos_stats.sh
dev/drivers/scripts/stats/rtofs/jevs_rtofs_ghrsst_stats.sh
dev/drivers/scripts/stats/rtofs/jevs_rtofs_aviso_stats.sh
Since ARGO, NDBC and OSI-SAF obs data need preparation, we need to test the prep script for them. To do so, please run: 
/dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.sh

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA I am working on your PR now, I have submitted all the requested jobs.  

@AliciaBentley-NOAA @ShelleyMelchior-NOAA

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Thank you very much! Please let us know where to find the output so we can keep track of the longer job after your day ends!

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA @AliciaBentley-NOAA @ShelleyMelchior-NOAA 

The prep job is located here: 

log file:   /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr378test/EVS/dev/drivers/scripts/prep/rtofs
output: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs

stats jobs are here:  
log files: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr378test/EVS/dev/drivers/scripts/stats/rtofs
output: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA All the stats jobs are done, btw, if you want to check to see if they are good.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : Thanks. I will check the files and let you know.

**Comment by ShelleyMelchior-NOAA** [comment]
@SamiraArdani-NOAA , when you get a chance you can do a sync fork on `feature/EE2_REV4_rtofs`. We just approved 2 PRs in quick succession.

**Comment by PerryShafran-NOAA** [comment]
Also the prep job is now finished.  Please validate.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA @AliciaBentley-NOAA @ShelleyMelchior-NOAA I'm re-running the stats jobs for PDYm3 so that you can have a cleaner comparison with emc.vpppg.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : Sounds great. Thanks!

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA The runs have completed.  Please check the latest run vs emc.vpppg, as well as the log files, and let me know if all is good.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : stat files for SMOS and AVISO look good.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA Great news!  Are we checking the ghrsst?  

And have we validated the prep job also?

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : GHRSST also looks good. Still checking prep job results.

**Comment by AliciaBentley-NOAA** [comment]
Thanks, @SamiraArdani-NOAA! We're all waiting for your results with bated breath!

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA @ShelleyMelchior-NOAA : prep job results were checked. The number of files are identical to emc.vpppg parallel. The files size have little differences (not significant).

**Comment by PerryShafran-NOAA** [comment]
Good news!  I think that I can go ahead and merge now.

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : Do we also need to check stats for argo, osisaf and ndbc?

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : Thanks.

**Comment by PerryShafran-NOAA** [comment]
No, we do not need to run stats.  prep was the only thing that changed for those three items.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : ok, Thanks. I just wanted to confirm.

**Pull request merged**
