### PR TITLE
Feature/aq mcpreq :: replace cp with cpreq

### PR DESCRIPTION
**Pull request by Ho-ChunHuang-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by Ho-ChunHuang-NOAA** [comment]
Please reference https://docs.google.com/document/d/1Cgi79XJaNec5FeQtNquag5Ao1KdDCt02/edit?usp=sharing&ouid=110971079403051862772&rtpof=true&sd=true for PR test instruction

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @Ho-ChunHuang-NOAA , I will start on your PR. Your fork has been cloned and branch `feature/AQMcpreq` has been checked out. I will test all steps since there are more changes in here than the cpreq.

**Comment by Ho-ChunHuang-NOAA** [comment]
Please do so on prep/stats/plots

**Comment by ShelleyMelchior-NOAA** [comment]
The aqm prep processing is complete.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/aqm/atmos.20231113/aqm`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_prep_00.o93404699`

**Comment by Ho-ChunHuang-NOAA** [comment]
@ShelleyMelchior-NOAA log file looks clean.  The file size of /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/aqm/atmos.20231113/aqm/ is the same as mine.

Please copy prep from atmos.20231110 to atmos.20231112, and proceed with stats.

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks Ho-Chun!
Stats is underway. I simply exported EVSINaqm from the stats driver to point to your stats. I ran stats for all vhr's. Please review.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/aqm/aqm.20231113`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_stats.o*`

One point. I think `cp` is ok for COMOUTsmall. `cpreq` is only needed for COMOUTfinal. The final stats file can have some missing small stats files.

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA Thanks! Are we asking @Ho-ChunHuang-NOAA  to make that change for us or are we making it for him?

**Comment by ShelleyMelchior-NOAA** [comment]
> @ShelleyMelchior-NOAA Thanks! Are we asking @Ho-ChunHuang-NOAA to make that change for us or are we making it for him?

Ho-Chun can make the change.

**Comment by Ho-ChunHuang-NOAA** [comment]
@ShelleyMelchior-NOAA and @AliciaBentley-NOAA 
I am back from a meeting, I think I change all cp to cpreq in script/prep&stats&plots/aqm.  Where do you see the cp from or to COMOUTsmall?  Please advise.

**Comment by Ho-ChunHuang-NOAA** [comment]
@ShelleyMelchior-NOAA and @AliciaBentley-NOAA  

Oh, you want to change some cpreq back to cp?

I think the cpreq is needed for file to COUMOUsmall.   Later in the code some of the same stat files will be copied from COUMOUsmall to temporary running directory "finalstat" for StatAnalysis_*_GatherByDay.conf.  Therefore, if no stats generated from point_stat we need to stop at "cpreq #### ${COMOUTsmall}".  Simply for the sake of debugging where went wrong.

**Comment by AliciaBentley-NOAA** [comment]
@Ho-ChunHuang-NOAA I think @ShelleyMelchior-NOAA was saying that the cpreq should be changed back to cp when copying to ${COMOUTsmall}. So in places like Line 174 in [scripts/stats/aqm/exevs_aqm_grid2obs_stats.sh](https://github.com/NOAA-EMC/EVS/pull/353/files#diff-9b96f53ba3a81eec1b5dbb75e5bc571ab8980caebb4981a475319bd5fcf2320c), you can change cpreq back to cp because those small .stat files may not always exist and using cpreq may cause the code to exit.

**Comment by Ho-ChunHuang-NOAA** [comment]
@AliciaBentley-NOAA and @ShelleyMelchior-NOAA 

I think we should always has **SAME** number of stats files generated from each point_stat configs execution if we already checked the needed model output and obs input, e.g.,

"if [ ${numo3fcst} -gt 0 -a ${obs_hourly_found} -eq 1 ]; then"
"if [ ${numpmfcst} -gt 0 -a ${obs_hourly_found} -eq 1 ]; then"
"if [ ${ozmax8} -gt 0 -a ${obs_daily_found} -gt 0 ]; then"
"if [ ${pmave1} -gt 0 -a ${obs_daily_found} -gt 0 ]; then"

**Comment by AliciaBentley-NOAA** [comment]
@Ho-ChunHuang-NOAA - Thanks! Once EVSv1 becomes operational, we can't "debug" the code anymore. AQM in EVSv1 needs to run cleanly 99.999% the time in order to be in ops. If we know there are times when .stat files that are intended for ${COMOUTsmall} are not generated, then we can't use cpreq there. There must **always** be files to move to ${COMOUTsmall} if we are going to use cpreq.

Similarly, there should be checks in the AQM component of EVSv1 to look for the ${COMOUTsmall} stat files BEFORE jobs try to copy them to the temporary running directory "finalstat" for StatAnalysis_*_GatherByDay.conf. If the ${COMOUTsmall} files don't exist, then that part of AQM should not execute. Does that makes sense? We need to have checks in place so that this code will not try to run and crash in operations. 

Please let us know if this is confusing or unclear. Basically, we need to ensure that this code works 99.999% of the time, and checking for files before we try to copy them is the best way to do that.

CC @PerryShafran-NOAA @ShelleyMelchior-NOAA

**Comment by Ho-ChunHuang-NOAA** [comment]
@AliciaBentley-NOAA @ShelleyMelchior-NOAA and @PerryShafran-NOAA 

Perry's design already assure there are stat file generated within each if loop
"if [ ${numo3fcst} -gt 0 -a ${obs_hourly_found} -eq 1 ]; then"
"if [ ${numpmfcst} -gt 0 -a ${obs_hourly_found} -eq 1 ]; then"
"if [ ${ozmax8} -gt 0 -a ${obs_daily_found} -gt 0 ]; then"
"if [ ${pmave1} -gt 0 -a ${obs_daily_found} -gt 0 ]; then"

If first one has no stats file, 
cp ${DATA}/point_stat/${MODELNAME}/* ${COMOUTsmall} 


Then the rest will fail with cpreq.
cpreq ${COMOUTsmall}/*${outtyp}${bcout}* ${finalstat}
cpreq ${finalstat}/evs.${STEP}.${COMPONENT}${bcout}.${RUN}.${VERIF_CASE}_ozone.v${VDATE}.stat ${COMOUTfinal}

This is redundant but I will add some checking statements to assure cpreq will not fail.

**Comment by AliciaBentley-NOAA** [comment]
@Ho-ChunHuang-NOAA Thank you very much! Anything that helps the AQM component of EVS not fail in operations is a great thing to add! We appreciate it!

**Comment by Ho-ChunHuang-NOAA** [comment]
@ShelleyMelchior-NOAA 
Please git pull origin feature/AQMcpreq for the revision and rerun the prep/stats/plots.

**Comment by ShelleyMelchior-NOAA** [comment]
> @ShelleyMelchior-NOAA Please git pull origin feature/AQMcpreq for the revision and rerun the prep/stats/plots.

Sure thing, Ho-Chun! I will bring in your changes. I will re-run prep and stats first, then get to plots.

**Comment by ShelleyMelchior-NOAA** [comment]
prep and stats re-runs have completed.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/aqm`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/aqm`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_prep_00.o93476168`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_stats.o93476*`

Since plots takes a little longer, I willl submit that job while prep and stats are reviewed.

**Comment by Ho-ChunHuang-NOAA** [comment]
The prep and stats logout looks good.  The prep file size and stats are the same as mine.

In the stats, I found it copied the same files repeatedly to  ${COMOUTsmall} and it did StateAnalysis twice per days (one for 06 and one for 12).   I am looking at the code and see if I can modify it cleanly.  If it is a success, I will ask you to run stats (only) again.   As long as the stats is the same as mine, the prep and plots should be the same.

**Comment by ShelleyMelchior-NOAA** [comment]
Hi Ho-Chun -- the plots processing is underway. NOTE: the tar files in COMOUT are presently empty b/c of initial runs when I didn't have the EVSINaqm variable formulated correctly. That is resolved now. The plots process is still running. It is 25 mins in.
```
cbqs01: 
                                                                                                   Req'd  Req'd   Elap
Job ID                         Username        Queue           Jobname         SessID   NDS  TSK   Memory Time  S Time
------------------------------ --------------- --------------- --------------- -------- ---- ----- ------ ----- - -----
93490741.cbqs01                shelley.melchi* dev             jevs_aqm_grid2*    50420    1   128  500gb 02:00 R 00:25
```
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_plots.o93490741`
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm`

**Comment by ShelleyMelchior-NOAA** [comment]
@Ho-ChunHuang-NOAA , the plots are done.

**Comment by AliciaBentley-NOAA** [comment]
@Ho-ChunHuang-NOAA When you get a chance, can you please validate the plots produced by Shelley test? We'd love to get this PR merged today (i.e., before people start taking time off for Thanksgiving)! Thanks so much!

**Comment by Ho-ChunHuang-NOAA** [comment]
@ShelleyMelchior-NOAA 
The figures look good, https://www.emc.ncep.noaa.gov/users/verification/air_quality/aqm/evs/.

I am still working on the stats.  Please wait before the PR merge.

**Comment by ShelleyMelchior-NOAA** [comment]
Thank you for working through the conflict, Ho-Chun!

**Comment by Ho-ChunHuang-NOAA** [comment]
@ShelleyMelchior-NOAA 

I received some error after the merge to develop that I did not have early in the day, do you know what went wrong?

::::::::::::::::::::::::::::::::::::::::::::::::::::
Fri Nov 17 21:11:51 UTC 2023
0.002 + PS4='$SECONDS + '
0.002 + export PS4
0.002 + DATA=/lfs/h2/emc/ptmp/ho-chun.huang/EVStest/stats/20231114_00_aqmv7
0.002 + export DATA
0.002 + mkdir -p /lfs/h2/emc/ptmp/ho-chun.huang/EVStest/stats/20231114_00_aqmv7
0.003 + cd /lfs/h2/emc/ptmp/ho-chun.huang/EVStest/stats/20231114_00_aqmv7
0.003 + cycle=t00z
0.003 + export cycle
0.003 + setpdy.sh
**/lfs/h2/emc/vpppg/noscrub/ho-chun.huang/EVScpreq/jobs/JEVS_AQM_STATS[35]: setpdy.sh: not found [No such file or directory]**
0.127 + . ./PDY
**/lfs/h2/emc/vpppg/noscrub/ho-chun.huang/EVScpreq/jobs/JEVS_AQM_STATS[36]: .: ./PDY: cannot open [No such file or directory]**
+ for vhr in 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23
+ export vhr
+ echo 01
01
+ export cycle=t01z
::::::::::::::::::::::::::

**Comment by ShelleyMelchior-NOAA** [comment]
Ho-Chun, you need to make sure you are pointing to the new location for the modulefiles. It looks like the prod_util module was not located since setpdy.ph wasn't able to run.

**Comment by AliciaBentley-NOAA** [comment]
@Ho-ChunHuang-NOAA Please see Shelley's message in Slack about the PRs what were merged earlier today. The changes are listed. Thanks!

**Comment by Ho-ChunHuang-NOAA** [comment]
@AliciaBentley-NOAA Thanks. The change of modulefiles dir path fixed the problem.
@ShelleyMelchior-NOAA Should I change all $maillist to $MAILTO in this PR?

**Comment by Ho-ChunHuang-NOAA** [comment]
@ShelleyMelchior-NOAA 
I finally get it ready for the merge.  Please update the branch again and run stats for comparison.   Thanks.

**Comment by Ho-ChunHuang-NOAA** [comment]
@ShelleyMelchior-NOAA 
I saw the files were generated at different time in /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/aqm/aqm.20231114

Can you remove them first before you run the aqm stats?  Thanks.

**Comment by ShelleyMelchior-NOAA** [comment]
Ho-Chun, your sync fork of develop into this branch should take care of everything for you, re: maillist and MAILTO and modulefiles, and etc ...

**Comment by ShelleyMelchior-NOAA** [comment]
> @ShelleyMelchior-NOAA I saw the files were generated at different time in /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/aqm/aqm.20231114
> 
> Can you remove them first before you run the aqm stats? Thanks.

Yes, I ran stats for a random vhr (=04) to make sure stats still worked OK after the merge of PR #354  into develop. I will run stats again tomorrow which will be a different VDATE, so it will all be OK.

**Comment by Ho-ChunHuang-NOAA** [comment]
@ShelleyMelchior-NOAA 
Different VDATE is fine, I have a cron set running the new VDATE for comparison.  Thanks.  Have a good night.

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @Ho-ChunHuang-NOAA , I ran all of stats for all vhr's for VDATE=20231116.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/aqm/aqm.20231116`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_stats.o936937*` and
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_stats.o93693972` (vhr=23)

**Comment by Ho-ChunHuang-NOAA** [comment]
@ShelleyMelchior-NOAA 
The 2023 11 16 stats log file looks good. The stats are the same as mine.

**Comment by ShelleyMelchior-NOAA** [comment]
I think we have done all of the testing in this PR. Things look satisfactory. If you think the PR is in a good spot, I will do the formal code review and approve for merge.

**Comment by Ho-ChunHuang-NOAA** [comment]
@ShelleyMelchior-NOAA 

I think the code is ready for merging back to the authoritative repository.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The changes look good and all tests produce expected results. This PR is approved for merge.

**Pull request merged**
