### PR TITLE
EVS v1.0.2 for AQMv6 verification

### PR DESCRIPTION
**Pull request by Ho-ChunHuang-NOAA**
## Pull Request Testing ##
This is the revision of EVSv1.0.1 for AQMv6 verification, assuming to be v1.0.2

Please read[ instruction](https://docs.google.com/document/d/1_BaHOAtGJ2Bj7GX8hw45PXpgZsEHkI2Y/edit?usp=sharing&ouid=110971079403051862772&rtpof=true&sd=true) carefully for PR testing on the BACKUPSYS WCOSS2, EMC PARA on the BACKUPSYS WCOSS2, and NCO PARA on the PRIMARYSYS WCOSS2

- [ ] Describe testing already performed for this Pull Request:</br>

Performed AQMv6 prep from 20231225 to 20240104
/lfs/h2/emc/physics/noscrub/ho-chun.huang/evstestv6/v1.0/prep/aqm

Perform AQMv6 stats from 20240101 20240104
/lfs/h2/emc/physics/noscrub/ho-chun.huang/evstestv6/v1.0/stats/aqm

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
YES
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
YES
- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks Ho-Chun. These changes look good upon quick glance. Me or Perry will get started on this PR as soon as we are able, given supercomputer constraints.

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `feature/forAQMv6`.

**Comment by ShelleyMelchior-NOAA** [comment]
I have completed the prep step for VDATEs=20240104, 20240105, 20240106.
I pointed DCOMIN to your archive: `/lfs/h2/emc/vpppg/noscrub/ho-chun.huang/dcom/prod/airnow`
The logfiles are:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_prep_00.o123571194`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_prep_00.o123572598`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_prep_00.o123573408`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/aqm`

My only concern is that while COMINaqm was removed from the driver script, it doesn't appear to get defined correctly by the default in JEVS_AQM_PREP. 
```
[dlogin08 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ grep COMINaqm jevs_aqm_prep_00.o12357*
jevs_aqm_prep_00.o123571194:0.774 + COMINaqm=''
jevs_aqm_prep_00.o123571194:0.774 + export COMINaqm
jevs_aqm_prep_00.o123572085:0.891 + COMINaqm=''
jevs_aqm_prep_00.o123572085:0.891 + export COMINaqm
jevs_aqm_prep_00.o123572598:0.845 + COMINaqm=''
jevs_aqm_prep_00.o123572598:0.845 + export COMINaqm
jevs_aqm_prep_00.o123573408:0.891 + COMINaqm=''
jevs_aqm_prep_00.o123573408:0.891 + export COMINaqm
```
But when I run the compath.py from command line, the path is resolved correctly:
```
[dlogin08 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ envir=prod
[dlogin08 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ modsys=aqm
[dlogin08 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ mod_ver=v6.1
[dlogin08 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ compath.py ${envir}/com/${modsys}/${mod_ver}
/lfs/h1/ops/prod/com/aqm/v6.1
```

Please review.

### UPDATE! I know why. I have aqm set to v7 in the versions file. I had brought in some other version changes and that over-wrote your change to v6.1. I will resolve and re-run. My mistake!

**Comment by Ho-ChunHuang-NOAA** [comment]
In the logfile aqm_ver=v7.0 ???  The version/run.ver=v6.1.  Can you double check your version/run.ver? or did you redefine aqm_ver somewhere?

**Comment by ShelleyMelchior-NOAA** [comment]
Ok, sorry about that! The version is now set to v6.1. The re-runs are complete for the same settings described in my previous comment.
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_prep_00.o123577502`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_prep_00.o123577708`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_prep_00.o123577875`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/aqm`
COMINaqm is resolved correctly:
```
[dlogin08 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ grep COMINaqm jevs_aqm_prep_00.o123577502
1.002 + COMINaqm=/lfs/h1/ops/prod/com/aqm/v6.1
1.002 + export COMINaqm
```

**Comment by Ho-ChunHuang-NOAA** [comment]
file size looks okay, please go ahead to run stats for VDATE=20240106 with your prep or point to my prep.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran the stats processing for VDATE=20240106 pointing to my local prep files.
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_stats.o1235*`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/aqm`

**Comment by Ho-ChunHuang-NOAA** [comment]
The 20240106 AQMv6 stats is the same as mine.

**Comment by ShelleyMelchior-NOAA** [comment]
None of the plotting code changed. I presume the plots processing does not need to be tested.

**Comment by Ho-ChunHuang-NOAA** [comment]
Only the scripts/config for prep and stats has been changed.  You do not need to test the plots step unless you want to.  This is my suggestion for your consideration.

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks, Ho-Chun. For your awareness, I am going to make a commit to your branch in this PR. These are few minor changes for Wei that are not related to AQM. They will not impact your PR.

**Comment by AliciaBentley-NOAA** [comment]
Looks great! I approve this PR with the changes that were made! Thanks, @Ho-ChunHuang-NOAA and @ShelleyMelchior-NOAA!

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yield expected results. This PR is approved for merge.

**Pull request merged**
