### PR TITLE
Remove `goto`. Update to Fortran90

### PR DESCRIPTION
**Pull request by aerorahul**
This PR:
- removes `goto` statements
- updates the code to Fortran 90 standards

**NOTE**:
This branch is not tested.

I have kept the old code alongside the new code and can/will be removed when testing concludes.

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks @aerorahul . I have cloned your fork and checked out branch `feature/no-goto`.

I ran `sorc/build.sh` to see how compilation would go. I saw that you modified the makefiles to point to your new code (*.f90 files). 5 of the 6 executables were generated, but the compiling faltered for `evs_g2g_adjustCMC.f90`
```
ftn -g -traceback -O3 -auto -convert big_endian -I /apps/ops/prod/libs/intel/19.1.3.304/g2/3.4.5/include_4 -o evs_g2g_adjustCMC.x  evs_g2g_adjustCMC.f90 /apps/ops/prod/libs/intel/19.1.3.304/ip/3.3.3/lib/libip_4.a /apps/ops/prod/libs/intel/19.1.3.304/w3emc/2.9.2/lib64/libw3emc_4.a /apps/ops/prod/libs/intel/19.1.3.304/bacio/2.4.1/lib/libbacio_4.a  /apps/ops/prod/libs/intel/19.1.3.304/sp/2.3.3/lib/libsp_4.a /apps/ops/prod/libs/intel/19.1.3.304/g2/3.4.5/lib64/libg2_4.a /apps/spack/jasper/2.0.25/intel/19.1.3.304/sjib74krrorkyczqpqah4tvewmlnqdx4/lib64/libjasper.a /apps/spack/libpng/1.6.37/intel/19.1.3.304/4ohkronuhlyherusoszzrmur5ewvlwzh/lib/libpng.a /apps/spack/zlib/1.2.11/intel/19.1.3.304/hjotqkckeoyt6j6tibalwzrlfljcjtdh/lib/libz.a
evs_g2g_adjustCMC.f90(21): error #6303: The assignment operation or the binary expression operation is invalid for the data types of the two operands.   [GDSS]
    im = gdss(2)
---------^
evs_g2g_adjustCMC.f90(22): error #6303: The assignment operation or the binary expression operation is invalid for the data types of the two operands.   [GDSS]
    jm = gdss(3)
---------^
evs_g2g_adjustCMC.f90(23): error #6355: This binary operation is invalid for this data type.   [GDSS]
    jf = gdss(2) * gdss(3)
---------^
evs_g2g_adjustCMC.f90(23): error #6355: This binary operation is invalid for this data type.   [GDSS]
    jf = gdss(2) * gdss(3)
-------------------^
evs_g2g_adjustCMC.f90(23): error #6549: An arithmetic or LOGICAL type is required in this context.
    jf = gdss(2) * gdss(3)
-----------------^
evs_g2g_adjustCMC.f90(23): error #6303: The assignment operation or the binary expression operation is invalid for the data types of the two operands.
    jf = gdss(2) * gdss(3)
-----------------^
evs_g2g_adjustCMC.f90(41): error #6366: The shapes of the array expressions do not conform.   [KPD1]
    kpd1 = [3, 3, 0, 2, 2, 2, 2, 2, 3, 3, 0, 2]
----^
evs_g2g_adjustCMC.f90(42): error #6366: The shapes of the array expressions do not conform.   [KPD2]
    kpd2 = [5, 5, 0, 2, 3, 2, 3, 1, 5, 0, 2, 3]
----^
evs_g2g_adjustCMC.f90(43): error #6366: The shapes of the array expressions do not conform.   [KPD12_GEFS]
    kpd12_gefs = [50000, 100000, 85000, 25000, 25000, 85000, 85000, 70000, 50000, 10, 10, 10]
----^
evs_g2g_adjustCMC.f90(44): error #6366: The shapes of the array expressions do not conform.   [KPD12_CMCE]
    kpd12_cmce = [5, 1, 85, 25, 25, 85, 85, 7, 5, 10, 10, 10]
----^
evs_g2g_adjustCMC.f90(45): error #6366: The shapes of the array expressions do not conform.   [KPD11_GEFS]
    kpd11_gefs = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
----^
evs_g2g_adjustCMC.f90(46): error #6366: The shapes of the array expressions do not conform.   [KPD11_CMCE]
    kpd11_cmce = [-4, -5, -3, -3, -3, -3, -3, -4, -4, 0, 0, 0]
----^
evs_g2g_adjustCMC.f90(47): error #6366: The shapes of the array expressions do not conform.   [KPD10_GEFS]
    kpd10_gefs = [100, 100, 100, 100, 100, 100, 100, 100, 100, 101, 100, 103]
----^
evs_g2g_adjustCMC.f90(48): error #6366: The shapes of the array expressions do not conform.   [KPD10_CMCE]
    kpd10_cmce = [100, 100, 100, 100, 100, 100, 100, 100, 100, 101, 100, 103]
----^
compilation aborted for evs_g2g_adjustCMC.f90 (code 1)
make: *** [makefile:10: evs_g2g_adjustCMC.x] Error 1
```
```
[clogin02 /lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/RM/EVS/sorc]$ ls ../exec
ecm_gfs_look_alike_new  jma_merge  pcpconform  sref_precip.x  ukm_hires_merge

```

**Comment by aerorahul** [comment]
> Thanks @aerorahul . I have cloned your fork and checked out branch `feature/no-goto`.
> 
> I ran `sorc/build.sh` to see how compilation would go. I saw that you modified the makefiles to point to your new code (*.f90 files). 5 of the 6 executables were generated, but the compiling faltered for `evs_g2g_adjustCMC.f90`
> 
> ```
> ftn -g -traceback -O3 -auto -convert big_endian -I /apps/ops/prod/libs/intel/19.1.3.304/g2/3.4.5/include_4 -o evs_g2g_adjustCMC.x  evs_g2g_adjustCMC.f90 /apps/ops/prod/libs/intel/19.1.3.304/ip/3.3.3/lib/libip_4.a /apps/ops/prod/libs/intel/19.1.3.304/w3emc/2.9.2/lib64/libw3emc_4.a /apps/ops/prod/libs/intel/19.1.3.304/bacio/2.4.1/lib/libbacio_4.a  /apps/ops/prod/libs/intel/19.1.3.304/sp/2.3.3/lib/libsp_4.a /apps/ops/prod/libs/intel/19.1.3.304/g2/3.4.5/lib64/libg2_4.a /apps/spack/jasper/2.0.25/intel/19.1.3.304/sjib74krrorkyczqpqah4tvewmlnqdx4/lib64/libjasper.a /apps/spack/libpng/1.6.37/intel/19.1.3.304/4ohkronuhlyherusoszzrmur5ewvlwzh/lib/libpng.a /apps/spack/zlib/1.2.11/intel/19.1.3.304/hjotqkckeoyt6j6tibalwzrlfljcjtdh/lib/libz.a
> evs_g2g_adjustCMC.f90(21): error #6303: The assignment operation or the binary expression operation is invalid for the data types of the two operands.   [GDSS]
>     im = gdss(2)
> ---------^
> evs_g2g_adjustCMC.f90(22): error #6303: The assignment operation or the binary expression operation is invalid for the data types of the two operands.   [GDSS]
>     jm = gdss(3)
> ---------^
> evs_g2g_adjustCMC.f90(23): error #6355: This binary operation is invalid for this data type.   [GDSS]
>     jf = gdss(2) * gdss(3)
> ---------^
> evs_g2g_adjustCMC.f90(23): error #6355: This binary operation is invalid for this data type.   [GDSS]
>     jf = gdss(2) * gdss(3)
> -------------------^
> evs_g2g_adjustCMC.f90(23): error #6549: An arithmetic or LOGICAL type is required in this context.
>     jf = gdss(2) * gdss(3)
> -----------------^
> evs_g2g_adjustCMC.f90(23): error #6303: The assignment operation or the binary expression operation is invalid for the data types of the two operands.
>     jf = gdss(2) * gdss(3)
> -----------------^
> evs_g2g_adjustCMC.f90(41): error #6366: The shapes of the array expressions do not conform.   [KPD1]
>     kpd1 = [3, 3, 0, 2, 2, 2, 2, 2, 3, 3, 0, 2]
> ----^
> evs_g2g_adjustCMC.f90(42): error #6366: The shapes of the array expressions do not conform.   [KPD2]
>     kpd2 = [5, 5, 0, 2, 3, 2, 3, 1, 5, 0, 2, 3]
> ----^
> evs_g2g_adjustCMC.f90(43): error #6366: The shapes of the array expressions do not conform.   [KPD12_GEFS]
>     kpd12_gefs = [50000, 100000, 85000, 25000, 25000, 85000, 85000, 70000, 50000, 10, 10, 10]
> ----^
> evs_g2g_adjustCMC.f90(44): error #6366: The shapes of the array expressions do not conform.   [KPD12_CMCE]
>     kpd12_cmce = [5, 1, 85, 25, 25, 85, 85, 7, 5, 10, 10, 10]
> ----^
> evs_g2g_adjustCMC.f90(45): error #6366: The shapes of the array expressions do not conform.   [KPD11_GEFS]
>     kpd11_gefs = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
> ----^
> evs_g2g_adjustCMC.f90(46): error #6366: The shapes of the array expressions do not conform.   [KPD11_CMCE]
>     kpd11_cmce = [-4, -5, -3, -3, -3, -3, -3, -4, -4, 0, 0, 0]
> ----^
> evs_g2g_adjustCMC.f90(47): error #6366: The shapes of the array expressions do not conform.   [KPD10_GEFS]
>     kpd10_gefs = [100, 100, 100, 100, 100, 100, 100, 100, 100, 101, 100, 103]
> ----^
> evs_g2g_adjustCMC.f90(48): error #6366: The shapes of the array expressions do not conform.   [KPD10_CMCE]
>     kpd10_cmce = [100, 100, 100, 100, 100, 100, 100, 100, 100, 101, 100, 103]
> ----^
> compilation aborted for evs_g2g_adjustCMC.f90 (code 1)
> make: *** [makefile:10: evs_g2g_adjustCMC.x] Error 1
> ```
> 
> ```
> [clogin02 /lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/RM/EVS/sorc]$ ls ../exec
> ecm_gfs_look_alike_new  jma_merge  pcpconform  sref_precip.x  ukm_hires_merge
> ```

Ok.  While you test the other 2, I will see what I can do about this one.  Probably not tonight.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran `jevs_global_det_atmos_prep.sh`, which @malloryprow advised will call `ukm_hires_merge` and `jma_merge`.  The job failed when running `jma_merge`. Please see the logfile.
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_prep_00.o94982366`

**Comment by malloryprow** [comment]
It looks like it hit the wall time?

>  /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_
>  00.94982366.cbqs01/atmos.jma.t00z.f000.tmp1
> 
>  /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_
>  00.94982366.cbqs01/atmos.jma.t00z.f000.tmp2
> 
>  /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_
>  00.94982366.cbqs01/atmos.jma.t00z.f000
> 
> =>> PBS: job killed: walltime 1809 exceeded limit 1800

**Comment by malloryprow** [comment]
Could it be stuck in a loop somewhere?

**Comment by ShelleyMelchior-NOAA** [comment]
> Could it be stuck in a loop somewhere?

Solid thought ... since gotos were removed which may have exited loop processing.
Here are the two files to compare.
Original (goto included): `/lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/RM/EVS/sorc/jma_merge.fd/jma_merge.f`
Rewrite (no goto): `/lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/RM/EVS/sorc/jma_merge.fd/jma_merge.f90`
I am snooping in these to compare, especially in getgb processing, but no grand ideas yet.

**Comment by aerorahul** [comment]
Full disclosure: I just copied and pasted the code from an AI-generated response to refactor old code as a starting point.

**Comment by ShelleyMelchior-NOAA** [comment]
> Full disclosure: I just copied and pasted the code from an AI-generated response to refactor old code as a starting point.

All good, @aerorahul ! 😄 We appreciate the hail mary attitude! Why not!?

**Comment by malloryprow** [comment]
I can look more into it? @aerorahul I'm not sure if you have the time to or not.

**Comment by malloryprow** [comment]
I think I found what is going on. I found it by adding some print statements in the original code.

```
j = -1
do while (j /= 0)
   [do stuff]
    j = j - 1
end do
```

j it _always_ not equal to 0. This is how the original code it set up too but what stops it is

`if(iretn.ne.0) goto 100   !reached end of record or incorrect file`

and in the case of the original code when it reaches the end of the file iretn=99.

In the new code it has

```
if (irets.ne.0) then
      if (irets.eq.-1) then
         write(*,*) 'Error reading input file 12'
         stop
      endif
      if (irets.eq.-2) then
         write(*,*) 'Error reading input file 12'
         stop
      endif
endif
```

but since iretn=99 it never gets to those stop statements.

**Comment by malloryprow** [comment]
> I think I found what is going on. I found it by adding some print statements in the original code.
> 
> ```
> j = -1
> do while (j /= 0)
>    [do stuff]
>     j = j - 1
> end do
> ```
> 
> j it _always_ not equal to 0. This is how the original code it set up too but what stops it is
> 
> `if(iretn.ne.0) goto 100 !reached end of record or incorrect file`
> 
> and in the case of the original code when it reaches the end of the file iretn=99.
> 
> In the new code it has
> 
> ```
> if (irets.ne.0) then
>       if (irets.eq.-1) then
>          write(*,*) 'Error reading input file 12'
>          stop
>       endif
>       if (irets.eq.-2) then
>          write(*,*) 'Error reading input file 12'
>          stop
>       endif
> endif
> ```
> 
> but since iretn=99 it never gets to those stop statements.

Just did these changes and that is what it was. Output file matches the output file from the original code.

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow Thank you very much! @ShelleyMelchior-NOAA is at a doctor's appointment, but maybe she can make these changes and check this when she gets back!

**Comment by ShelleyMelchior-NOAA** [comment]
Awesome!! I will make these changes in my clone of Rahul's fork and then re-run global_det_atmos_prep!

**Comment by malloryprow** [comment]
looks like sorc/ukm_hires_merge.fd/ukm_hires_merge.f90 still has a goto statement in it. I'll see if I can fix it

@ShelleyMelchior-NOAA I'll let you know what files to copy when I'm done.

**Comment by malloryprow** [comment]
@ShelleyMelchior-NOAA Good to go!

Files to copy:

1. /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/global/feature_no-goto/EVS/sorc/jma_merge.fd/jma_merge.f90
2. /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/global/feature_no-goto/EVS/sorc/ukm_hires_merge.fd/ukm_hires_merge.f90

**Comment by ShelleyMelchior-NOAA** [comment]
@aerorahul , can you update this PR branch w/ a sync fork?
I have merged Binbin's changes into develop. I will update this PR to remove `sorc/evs_g2g_adjustCMC.fd/evs_g2g_adjustCMC.f90` from the branch and also revert `sorc/evs_g2g_adjustCMC.fd/makefile` to use the original .f file, not the .f90 file.

I will test Mallory's changes and also update this PR w/ her changes once they test successfully.

**Comment by ShelleyMelchior-NOAA** [comment]
The run of `jevs_global_det_atmos_prep.sh` has completed.
COMOUT=` /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_det/atmos.20231203`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_prep_00.o95010442`
Just need to check that the ukmet and jma subdirs agree w/ emc.vpppg.

**Comment by AliciaBentley-NOAA** [comment]
Comparing 
/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_det/atmos.20231203/ukmet
and
/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/global_det/atmos.20231203/ukmet
resulted in the same files that were the same size. Now on to jma...

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA JMA files match as well! I think you can update this PR to use the new files and remove the old files when you get back. 

[alicia.bentley@clogin04 ~] ls -l /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_det/atmos.20231203/jma
total 7164
-rw-r--r-- 1 shelley.melchior vpppg 707640 Dec  5 20:11 jma.t00z.anl
-rw-r--r-- 1 shelley.melchior vpppg 707640 Dec  5 20:11 jma.t00z.f000
-rw-r--r-- 1 shelley.melchior vpppg 470418 Dec  5 20:11 jma.t00z.f024
-rw-r--r-- 1 shelley.melchior vpppg 467790 Dec  5 20:11 jma.t00z.f048
-rw-r--r-- 1 shelley.melchior vpppg 470418 Dec  5 20:11 jma.t00z.f072
-rw-r--r-- 1 shelley.melchior vpppg 666486 Dec  5 20:11 jma.t12z.anl
-rw-r--r-- 1 shelley.melchior vpppg 666486 Dec  5 20:11 jma.t12z.f000
-rw-r--r-- 1 shelley.melchior vpppg 465162 Dec  5 20:11 jma.t12z.f024
-rw-r--r-- 1 shelley.melchior vpppg 473046 Dec  5 20:11 jma.t12z.f048
-rw-r--r-- 1 shelley.melchior vpppg 473046 Dec  5 20:11 jma.t12z.f072
-rw-r--r-- 1 shelley.melchior vpppg 470418 Dec  5 20:11 jma.t12z.f096
-rw-r--r-- 1 shelley.melchior vpppg 471732 Dec  5 20:11 jma.t12z.f120
-rw-r--r-- 1 shelley.melchior vpppg 267696 Dec  5 20:11 jma.t12z.f144
-rw-r--r-- 1 shelley.melchior vpppg 262440 Dec  5 20:11 jma.t12z.f168
-rw-r--r-- 1 shelley.melchior vpppg 267696 Dec  5 20:11 jma.t12z.f192
[alicia.bentley@clogin04 ~] ls -l /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/global_det/atmos.20231203/jma
total 7164
-rw-r--r-- 1 emc.vpppg vpppg 707640 Dec  4 18:22 jma.t00z.anl
-rw-r--r-- 1 emc.vpppg vpppg 707640 Dec  4 18:22 jma.t00z.f000
-rw-r--r-- 1 emc.vpppg vpppg 470418 Dec  4 18:22 jma.t00z.f024
-rw-r--r-- 1 emc.vpppg vpppg 467790 Dec  4 18:22 jma.t00z.f048
-rw-r--r-- 1 emc.vpppg vpppg 470418 Dec  4 18:22 jma.t00z.f072
-rw-r--r-- 1 emc.vpppg vpppg 666486 Dec  4 18:23 jma.t12z.anl
-rw-r--r-- 1 emc.vpppg vpppg 666486 Dec  4 18:22 jma.t12z.f000
-rw-r--r-- 1 emc.vpppg vpppg 465162 Dec  4 18:22 jma.t12z.f024
-rw-r--r-- 1 emc.vpppg vpppg 473046 Dec  4 18:22 jma.t12z.f048
-rw-r--r-- 1 emc.vpppg vpppg 473046 Dec  4 18:22 jma.t12z.f072
-rw-r--r-- 1 emc.vpppg vpppg 470418 Dec  4 18:22 jma.t12z.f096
-rw-r--r-- 1 emc.vpppg vpppg 471732 Dec  4 18:22 jma.t12z.f120
-rw-r--r-- 1 emc.vpppg vpppg 267696 Dec  4 18:22 jma.t12z.f144
-rw-r--r-- 1 emc.vpppg vpppg 262440 Dec  4 18:22 jma.t12z.f168
-rw-r--r-- 1 emc.vpppg vpppg 267696 Dec  4 18:22 jma.t12z.f192

**Comment by ShelleyMelchior-NOAA** [comment]
TY for checking the output, @AliciaBentley-NOAA . I will update this PR's code accordingly.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The test yields expected results. This PR is approved for merge.

**Pull request merged**
