### PR TITLE
FAKE dbnet 

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

Added in the two lines from Lin to create the fake dbnet alerts into each of the modulefiles in dev.  
Ran a sample of plot jobs across EVS.  All created the following fake dbnet alert (similar to this):
```
29 + /apps/ops/prod/nco/core/prod_util.v2.0.13/fakedbn/bin/dbn_alert MODEL EVS_RZDM jevs_global_det_atmos_grid2grid_sst_plots_31days_00 /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_det/atmos.20231129/evs.plots.global_det.atmos.grid2grid_sst.last31days.v20231129.tar
FAKE dbn_alert MODEL EVS_RZDM jevs_global_det_atmos_grid2grid_sst_plots_31days_00 /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_det/atmos.20231129/evs.plots.global_det.atmos.grid2grid_sst.last31days.v20231129.tar
```

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Pull in the fork, and don't forget the link to the fix directory.
Then, run a sample of plot jobs across EVS.  You might have to set SENDDBN=YES in the driver script.  Then check the .o files for a block similar to the sample one above.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I cloned Perry's fork and checked out branch `feature/fakedbnet`. After setting up my user environment I ran nfcens plots. The FAKE dbn_alert was successful.
```
FAKE dbn_alert MODEL EVS_RZDM jevs_nfcens_grid2obs_plots /lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/nfcens/wave.20231129/evs.plots.nfcens.wave.grid2obs.last31days.v20231129.tar /lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/nfcens/wave.20231129/evs.plots.nfcens.wave.grid2obs.last90days.v20231129.tar
```
This is a little different from Perry's example b/c it is alerting on multiple (in this case, 2) files in one command. The code:
```
if [ $SENDDBN = YES ]; then
        $DBNROOT/bin/dbn_alert MODEL EVS_RZDM $job ${COMOUTplots}/${NET}.${STEP}.${COMPONENT}.${RUN}.*.tar
fi
```
Anyway, I just wanted to point this out b/c it is different from Perry's global_det example, but I still think it is correct/OK.

**Comment by ShelleyMelchior-NOAA** [comment]
I also ran plots for narre g2o past31 days. The FAKE dbn_alert worked.
```
[clogin05 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ grep FAKE jevs_narre_past31days_plots.o94535713 
FAKE dbn_alert MODEL EVS_RZDM jevs_narre_past31days_plots /lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/narre/atmos.20231129/evs.plots.narre.grid2obs.last31days.v20231129.tar
```

**Comment by PerryShafran-NOAA** [comment]
This seems to be good.  Would you run analyses or aqm plots to see that all looked good for these systems?  I had to make a few changes?

**Comment by ShelleyMelchior-NOAA** [comment]
Plots for aqm and analyses are underway. Processing is still too premature to have gotten to the SENDDBN test.
```
   Req'd  Req'd   Elap
Job ID                         Username        Queue           Jobname         SessID   NDS  TSK   Memory Time  S Time
------------------------------ --------------- --------------- --------------- -------- ---- ----- ------ ----- - -----
94537474.cbqs01                shelley.melchi* dev             jevs_aqm_grid2*   134680    1   128  500gb 02:00 R 00:12
94537956.cbqs01                shelley.melchi* dev             jevs_analyses_*   172016    1     1   10gb 02:00 R 00:03
```
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_plots.o94537474`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_analyses_grid2obs_plots.o94537956`

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA I see the fake dbn alerts for aqm and analyses.

`FAKE dbn_alert MODEL EVS_RZDM jevs_analyses_grid2obs_plots /lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/analyses/atmos.20231128/evs.plots.analyses.atmos.grid2obs.last31days.v20231128.tar`

`FAKE dbn_alert MODEL EVS_RZDM jevs_aqm_grid2obs_plots /lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/atmos.20231127/evs.plots.aqm.atmos.grid2obs.last31days.v20231127.tar`

Seems to be working just fine.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA @ShelleyMelchior-NOAA I've looked over this PR and I think that it looks great! Thanks for testing!

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yield expected results. This PR is approved for merge.

**Pull request merged**
