### PR TITLE
Bugfix/warning review

### PR DESCRIPTION
**Pull request by RoshanShrestha-NOAA**
Testing these driver scripts should be enough to check these bugfix changes. 
- dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_rap_precip_stats.sh
- dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_rap_snowfall_stats.sh

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/warning_review`.

**Comment by ShelleyMelchior-NOAA** [comment]
I will run rap stats for snowfall and precip. The changes are to ush scripts which are utilized by both nam and rap.
I will run a nominal test and a data denial test.

The nominal test is underway:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_snowfall_stats_00.o132738518`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_precip_stats_00.o132738484`

**Comment by RoshanShrestha-NOAA** [comment]
The nominal test concluded. There is no error or warning, as expected, and all look good to me.

**Comment by ShelleyMelchior-NOAA** [comment]
Great! I will remove the stats files that were generated for the nominal test and then run the data denial test.

**Comment by ShelleyMelchior-NOAA** [comment]
rap stats for precip and snowfall for data denial are complete. SORRY FOR THE EMAILS @RoshanShrestha-NOAA and @AliciaBentley-NOAA . 😨 
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_precip_stats_00.o132742476`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_snowfall_stats_00.o132742477`
COMOUT is empty.
No FATALs.
I see the expected WARNINGs in the log file.

**Comment by RoshanShrestha-NOAA** [comment]
> rap stats for precip and snowfall for data denial are complete. SORRY FOR THE EMAILS @RoshanShrestha-NOAA and @AliciaBentley-NOAA . 😨
> `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_precip_stats_00.o132742476`
> `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_snowfall_stats_00.o132742477`
> COMOUT is empty.
> No FATALs.
> I see the expected WARNINGs in the log file.

I agree, the expected WARNINGs are there in the log files for both precip and snowfall test runs.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yield expected results. This PR is approved for merge.

**Pull request merged**
