### PR TITLE
Feature/aqm 3-digit evs_ver

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

Put in evs_ver=v1.0.0, the 3-digit version number required by EE2. To ensure a 2-digit version number for COMIN and COMOUT, we used cut to shorten and created a new variable for the driver only, evs_ver_2d

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run the prep driver.

Run the stats driver. Please be sure you include -v vhr=00 in your qsub command, or any cycle you choose. Set COMIN to emc.vpppg.

For plots, set COMIN to emc.vpppg.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP. 

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your repository and checked out branch `feature/aqm_run_ver`.

**Comment by ShelleyMelchior-NOAA** [comment]
prep processing has completed.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/aqm/atmos.20231017/aqm`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_prep_00.o106899933`
Everything resolves as expected for evs_ver_2d, COMIN, and COMOUT.

**Comment by ShelleyMelchior-NOAA** [comment]
stats processing has completed.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/aqm/atmos.20231017/aqm/grid2obs`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_stats.o106900566`
Everything resolves as expected for evs_ver_2d, COMIN, and COMOUT.

**Comment by ShelleyMelchior-NOAA** [comment]
The plots processing is underway.
evs_ver_2d is resolved correctly, and subsequently, so are COMOUT and COMIN. We'll just watch to make sure the tar looks good.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_plots.o106901519`
```
106901519.dbqs01               shelley.melchi* dev             jevs_aqm_grid2*   259763    1   128  500gb 02:00 R 00:01
```
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/atmos.20231017`

**Comment by PerryShafran-NOAA** [comment]
stats files look good.  As long as everything resolved correctly, it should equal what they were before this change.

**Comment by PerryShafran-NOAA** [comment]
prep output is fine too.

**Comment by PerryShafran-NOAA** [comment]
The plot tarball has been created and is identical to what is in emc.vpppg.

**Comment by ShelleyMelchior-NOAA** [comment]
This PR is ready for merge. I will do the formal code review and then approve for merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yield expected results. This PR is approved for merge.

**Pull request merged**
