### PR TITLE
Adding Seasonal Modulefiles in dev/modulefiles

### PR DESCRIPTION
**Pull request by AmandeepVashisht-NOAA**
Adding seasonal modulefiles in dev/modulefiles. Has 3 shell scrips in dev/modulefiles/seasonal-one each for prep, stats, plots step.

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</Testing not needed for this first PR, as discussed in our last meeting>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</none>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes, the codes in the 3 scripts was basically copied and pasted from subseasonal parallel component on WCOSS2 at /lfs/h2/emc/vpppg/noscrub/emc.vpppg/EVS/dev/modulefiles/subseasonal]**

- [ ] Do these updates/additions include sufficient testing updates? **[n/a]**

- [ ] Please complete this pull request review by **[When you can]**

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your repository and checked out branch `feature_seasonal_modulefiles`.

I confirmed that the seasonal module files are the same as the subseasonal module files, except for the different component name as mentioned in line 2 of the 3 module files.

**Comment by ShelleyMelchior-NOAA** [comment]
No further testing for this PR is required or necessary.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
This PR is approved for merge to begin to populate the seasonal component of EVS.

**Comment by AmandeepVashisht-NOAA** [comment]
Thanks so much, Shelley!

**Pull request merged**
