### PR TITLE
feature/global_det_atmos_plots_logging

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

This PR contains changes done for EVS v1.0.10 but for the v2.0 version of the code:

1. Adjust threshold of Scatter Index for global_det wave, global_ens wave, and nfcens from 200 to 500.
2. Reduce atmos plots log sizes by removing very high level logging messages
3. Remove repeated environment variable export statements in the individual jobs scripts for atmos plots

In addition:
4. Remove repeated environment variable export statements in the individual jobs scripts for atmos stats
5. Remove repeated environment variable export statements in the individual jobs scripts for wave plots

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **08/21/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Beginning this PR now.  I will start at the very top and work my way on down, which means I am starting with the global_det wave stats.  I don't recall if I need to adjust the date, but I think that I do?

**Comment by malloryprow** [comment]
global_det wave job will quick off in 30 minutes. I'm fine with waiting until then.

**Comment by PerryShafran-NOAA** [comment]
OK, I'm going to run the stats jobs now.  The stats job runs at 1320 so even though it's a few minutes early, you should be able to compare results soon.

**Comment by PerryShafran-NOAA** [comment]
The global_det wave stats job is finished.

You can see the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr510test/EVS/dev/drivers/scripts/stats/global_det

And the stats output here:   /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v2.0/stats/global_det, the 20240807 directories.

**Comment by malloryprow** [comment]
👍  All is good for global_det wave stats, log file and final output.

**Comment by PerryShafran-NOAA** [comment]
Great, testing the plot jobs now.

**Comment by PerryShafran-NOAA** [comment]
The wave plot jobs are complete.

See the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr510test/EVS/dev/drivers/scripts/plots/global_det

And the plot tarballs are here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/global_det/wave.20240807

**Comment by malloryprow** [comment]
👍 All is good for global_det wave plots, log file and final output.

For the global_det atmos stats, let's run with VDATE=PDYm2.

**Comment by PerryShafran-NOAA** [comment]
Will be running them for VDATE=20240806.  I'm starting these jobs now.

**Comment by PerryShafran-NOAA** [comment]
All the jobs except for gfs grid2obs are complete.  

You can see all the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr510test/EVS/dev/drivers/scripts/stats/global_det

And the stats output is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v2.0/stats/global_det, the 20240806 directories.

**Comment by malloryprow** [comment]
One job didn't get run, `jevs_global_det_gfs_atmos_wmo_daily_stats.sh`. Could we run that? I had it on step 13 instead of step12 but I moved it. 

👍 Otherwise, output is good. Logs have WARNING messages that are known and while be resolved in future MET beta release.

**Comment by PerryShafran-NOAA** [comment]
Thanks!  Running the wmo stats job.  I must have missed that in the jumble of jobs that needed to be run.

**Comment by PerryShafran-NOAA** [comment]
I will set VDATE_END to 20240806 for the plot jobs as well, and get those started.

**Comment by malloryprow** [comment]
jevs_global_det_gfs_atmos_wmo_daily_stats.sh run is good so now all global_det atmos stats is complete. 👍 

I think a few plots jobs are still running but will start reviewing.

**Comment by malloryprow** [comment]
👍  global_det atmos plots is good! Log files are a lot smaller like we saw in the EVS v1.0.10 PR for these same changes.

For global_ens wave it looks like it last ran for 20240807, and for nfcens 20240806. If we can run those last two tests for those dates respectively that be great.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I'll make those runs.  Shall we inform the developers responsible for those two components that their we are changing their code?

**Comment by malloryprow** [comment]
Good call. I can send an email tomorrow.

**Comment by PerryShafran-NOAA** [comment]
The plot jobs are finished.

global_ens
See .o files here:   /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr510test/EVS/dev/drivers/scripts/plots/global_ens
Plot tarballs: /lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/global_ens/wave.20240807

nfcens
See .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr510test/EVS/dev/drivers/scripts/plots/nfcens
Plot tarballs: /lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/nfcens/wave.20240806

**Comment by malloryprow** [comment]
👍 global_ens wave plots is good! The number of mages in the tar files matches the amount in ops. Because of this bug in the code this PR addresses, not all the images in the emc.vpppg parallel get generated.

👍  nfcens is good too! The number of images in the tar files matches the amount in ops and emc.vpppg parallel.

**Comment by PerryShafran-NOAA** [comment]
Excellent!  Will do a quick code review and, if all is good, do the merge.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA I'm also assigned as a reviewer (we're doing two reviewers per PR now)! I'll do my review now, too.

**Review by AliciaBentley-NOAA — APPROVED** [review]
@malloryprow @PerryShafran-NOAA I had previously looked over the changes and found that they all look good. With the log files also looking good, I approve this PR to be merged.

**Review by PerryShafran-NOAA — APPROVED** [review]
Changes look good.  This has my approval for merge.

**Pull request merged**
