### PR TITLE
Bugfix/new met columns

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

This bugfix updates the line type column lists for ECNT and VL1L2 statistics (used for plotting).  Two new columns were added to the ECNT stats and three were added to VL1L2.  The fix prevents a "ParserError" that triggers when python plots scripts read in stats data.

All jobs were tested using the EVSv2.0 stats archive.  No test runs outputted "FATAL ERROR"s or "ParserError"s.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

## 1) Edit driver scripts
For each driver script, edit the following environment variables:
**HOMEevs** - set to your test EVS directory
**COMIN** - set to `/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`
**COMOUT** - (optional) set to test output directory

Also, change the evs_ver in versions/run.ver:
**evs_ver** - 2.0.0

## 2) Run jobs
```
 jevs_cam_grid2obs_plots
 jevs_cam_headline_plots
 jevs_cam_href_grid2obs_ecnt_past31days_plots
 jevs_cam_href_grid2obs_ecnt_past90days_plots
 jevs_cam_href_profile_past31days_plots
 jevs_cam_href_profile_past90days_plots
 jevs_cam_nam_firewxnest_grid2obs_plots
```
```
 jevs_global_ens_atmos_gefs_grid2grid_past31days_plots
 jevs_global_ens_atmos_gefs_grid2grid_past90days_plots
 jevs_global_ens_atmos_gefs_grid2obs_past31days_plots
 jevs_global_ens_atmos_gefs_grid2obs_past31days_separate_plots
 jevs_global_ens_atmos_gefs_grid2obs_past90days_plots
 jevs_global_ens_atmos_gefs_grid2obs_past90days_separate_plots
 jevs_global_ens_atmos_gefs_precip_past31days_plots
 jevs_global_ens_atmos_gefs_precip_past90days_plots
 jevs_global_ens_atmos_gefs_profile1_past31days_plots
 jevs_global_ens_atmos_gefs_profile1_past90days_plots
 jevs_global_ens_atmos_gefs_profile2_past31days_plots
 jevs_global_ens_atmos_gefs_profile2_past90days_plots
 jevs_global_ens_atmos_gefs_profile3_past31days_plots
 jevs_global_ens_atmos_gefs_profile3_past90days_plots
 jevs_global_ens_atmos_gefs_profile4_past31days_plots
 jevs_global_ens_atmos_gefs_profile4_past90days_plots
 jevs_global_ens_atmos_gefs_sea_ice_past31days_plots
 jevs_global_ens_atmos_gefs_sea_ice_past90days_plots
 jevs_global_ens_atmos_gefs_snowfall_past31days_plots
 jevs_global_ens_atmos_gefs_snowfall_past90days_plots
 jevs_global_ens_atmos_gefs_sst_past31days_plots
 jevs_global_ens_atmos_gefs_sst_past90days_plots
 jevs_global_ens_atmos_naefs_grid2grid_past31days_plots
 jevs_global_ens_atmos_naefs_grid2grid_past90days_plots
 jevs_global_ens_atmos_naefs_grid2obs_past31days_plots
 jevs_global_ens_atmos_naefs_grid2obs_past90days_plots
 jevs_global_ens_atmos_naefs_precip_past31days_plots
 jevs_global_ens_atmos_naefs_precip_past90days_plots
```
```
 jevs_mesoscale_grid2obs_plots
 jevs_mesoscale_headline_plots
 jevs_mesoscale_sref_grid2obs_past90days_plots
```

## 3) Check
```
check_keywords="FATAL ERROR\|ParserError"
grep -l "$check_keywords" $logfile
```

- [x] Has the code been checked to ensure that no errors occur during the execution? **YES**

- [x] Do these updates/additions include sufficient testing updates? **YES**

- [x] Please complete this pull request review by **6/4/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA I am running your PR now.  I have made the changes and submitted all the jobs, and will let you know when you can look at things.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA All plot jobs have finished.  Would you please take a look at the output for me?

all cam jobs: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr480test/EVS/dev/drivers/scripts/plots/cam
all global_ens jobs: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr480test/EVS/dev/drivers/scripts/plots/global_ens
all mesoscale jobs: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr480test/EVS/dev/drivers/scripts/plots/mesoscale

You can find all plot tarballs here:

/lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots

I kind of expected some of these jobs to last longer, so it is possible there are errors.  I will check too.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA I think there are errors in the cam plot jobs; I think those require a VDATE and vhr to be defined in the qsub?  

Everything else has completed with a plot tarball.

When you have a moment, please let me know the VDATE and vhr for the cam plot jobs.

**Comment by MarcelCaron-NOAA** [comment]
Thanks @PerryShafran-NOAA!  All global_ens jobs completed successfully.  cam jobs look good, except the two you mentioned do need to be fed vhr (see below).  Two mesoscale jobs had unexpected errors unrelated to the changes made here and need more investigation (see below).

### Jobs with ParserError:

- **jevs_mesoscale_grid2obs_plots** - This ParserError does not seem to be related to the added columns to VL1L2 or ECNT (those seem to have been resolved).  I need to dig a bit more.

### Jobs with FATAL ERROR:

- **jevs_mesoscale_sref_grid2obs_past90days_plots** - I was confused about this; failure in a python script during plotting.  I checked the parallel output and the problem exists there too, i.e. it is not related to the changes in this PR.  Not sure if we'd like to address the bug here or in a separate PR.
- **jevs_cam_grid2obs_plots** - Yes, this job needs to be fed with vhr, so e.g., "qsub -v vhr=00 $DRIVER".  Apologies for forgetting to put that info in the PR description.
- **jevs_cam_headline_plots** - Same as jevs_cam_grid2obs_plots

**Comment by MarcelCaron-NOAA** [comment]
> @MarcelCaron-NOAA I think there are errors in the cam plot jobs; I think those require a VDATE and vhr to be defined in the qsub?
> 
> Everything else has completed with a plot tarball.
> 
> When you have a moment, please let me know the VDATE and vhr for the cam plot jobs.

I believe you can use any vhr.  vhr=00 should work!  
You shouldn't need to feed it a VDATE.  Given vhr, the job will successfully define PDYm1 and set VDATE to that.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA I don't know where we are in the process here, but I'll run the 2 CAM plot jobs that required the vhr=00.  But there are still two other errors to be addressed above?  Please check.  

Also be sure to sync fork.

**Comment by MarcelCaron-NOAA** [comment]
Thanks @PerryShafran-NOAA yes, the jobs that needed vhr can be rerun.  I'm still catching up, but let me get to addressing the two mesoscale jobs with errors.  I'll update again about that when I push the two fixes.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Please examine the two most recent .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr480test/EVS/dev/drivers/scripts/plots/cam

And the plot tarballs here:/lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/cam the 20240602 directories.

**Comment by MarcelCaron-NOAA** [comment]
Hi @PerryShafran-NOAA, The two recent jobs completed successfully (no FATAL ERROR or ParserError) and output tar files look good.
✔️ jevs_cam_grid2obs_plots
✔️ jevs_cam_headline_plots

The following was fixed.  I'm honestly surprised it hasn't been flagged by NCO; it should have been also failing in ops.  In any case, it is ready to be re-tested:
☑️ jevs_mesoscale_sref_grid2obs_past90days_plots

I am testing the following job and hope to push a fix here later today:
🛠️ jevs_mesoscale_grid2obs_plots

**Comment by PerryShafran-NOAA** [comment]
OK, I pulled in your changes - two changes in /ush/mesoscale/ush_sref_plot_py, yes?

I'll re-run this sref plot job.

**Comment by MarcelCaron-NOAA** [comment]
> OK, I pulled in your changes - two changes in /ush/mesoscale/ush_sref_plot_py, yes?

Correct!

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA None of my test **jevs_mesoscale_grid2obs_plots** jobs contain the "ParserError".  I also couldn't find any bug that might've caused the ParserErrors in the PR test job.  Maybe it was a configuration issue?  Do you mind running **jevs_mesoscale_grid2obs_plots** one more time to confirm?

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Certainly!  Does this job require a -v vhr= statement?

**Comment by PerryShafran-NOAA** [comment]
Also, the sref plot job is finished.

See the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr480test/EVS/dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_grid2obs_past90days_plots.o134235492

The tarball is here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/mesoscale

Also, please do a sync fork if you have not done it today.

**Comment by MarcelCaron-NOAA** [comment]
> @MarcelCaron-NOAA Certainly! Does this job require a -v vhr= statement?

Yes, and I've been testing with `-v vhr=00`

**Comment by MarcelCaron-NOAA** [comment]
jevs_mesoscale_sref_grid2obs_past90days_plots completed successfully (no FATAL ERROR or ParserError) and output tar files look good.
✔️ jevs_mesoscale_sref_grid2obs_past90days_plots

**Comment by PerryShafran-NOAA** [comment]
Excellent!  So now we have just the one job remaining, and that will take some time because it's a long job and I just started it.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA The plot job is complete.

Check out the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr480test/EVS/dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_grid2obs_plots.o134252355

and the tarball is here: /lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/mesoscale/atmos.20240603

**Comment by MarcelCaron-NOAA** [comment]
> @MarcelCaron-NOAA The plot job is complete.
> 
> Check out the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr480test/EVS/dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_grid2obs_plots.o134252355
> 
> and the tarball is here: /lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/mesoscale/atmos.20240603

Thanks!  Unfortunately not resolved.  I'm going to run this job overnight with some checks in the code and hopefully have a better idea about where exactly the problem is occurring.  I'll update here again tomorrow!

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA The remaining ParserError in jevs_mesoscale_grid2obs_plots is caused by a corrupted stat file:
/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v2.0/stats/global_det/gfs.20240323/evs.stats.gfs.atmos.grid2obs.v20240323.stat

Line 473601 is misprinted:
`V12.00 gfs G104 1560000 2V12.0.0 gfs G104 1560000 ...`
`                          ^                            `

... and therefore the line contains 34 columns of data instead of the expected 30 for CTC, confusing the csv-reader during plotting.  

It seems like this is the only corrupted line in any GFS stats file read by the job.  Therefore, for this PR at least, **I recommend no changes**.  

Output from the test job look good, and since the issue described above is not related to the jevs_mesoscale_grid2obs_plots job itself, only to its input data, then **I'm comfortable calling jevs_mesoscale_grid2obs_plots successful and wrapping up this PR**.
✔️ jevs_mesoscale_grid2obs_plots

**Comment by PerryShafran-NOAA** [comment]
I think that this PR is OK to merge.  Let me do a quick check of the code and then merge.  Please check to see if you need to sync the fork before I officially merge.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA @MarcelCaron-NOAA This PR looks great! Thanks for getting it over the finish line! This should help things run again in the emc.vpppg parallel (that uses the beta4s)!

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA @AliciaBentley-NOAA Great.  This fork is up to date!  Should be able to merge

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
