### PR TITLE
Update AQM to work with ecflow workflow

### PR DESCRIPTION
**Pull request by lgannoaa**
GitHub #213 

Tested in development ecflow workflow.
[Yes] Has the code been checked to ensure that no errors occur during the execution? [Yes or No]

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @lgannoaa , please merge upstream before I start this PR. PR #204 was just merged and that one definitely needs to be integrated into `feature/evs-213` before I begin. Thanks!

**Comment by ShelleyMelchior-NOAA** [comment]
Nevermind! I resolved the conflict and that brought your branch up to date w/ develop. I will begin testing now. :thumbsup:

**Comment by ShelleyMelchior-NOAA** [comment]
I tested prep for aqm. All results match with the EVS parallel. ✔️
I tested stats for aqm. The results match with the EVS parallel. ✔️
I tested plots of aqm. The results match with the EVS parallel. ✔️

**Comment by ShelleyMelchior-NOAA** [comment]
@PerryShafran-NOAA and @Ho-ChunHuang-NOAA , if you would like to review this PR, I invite you to do so.

**Comment by ShelleyMelchior-NOAA** [comment]
I am going to proceed with this merge. If further AQM changes are required, another PR may be submitted.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Test runs of this PR produced expected results. This PR is ready for merge.

**Comment by Ho-ChunHuang-NOAA** [comment]
@lgannoaa and @PerryShafran-NOAA , is this PR 216 only for the component narre or for the aqm?  I do not see family aqm in https://github.com/NOAA-EMC/EVS/blob/develop/ecf/defs/evs.def (only family narre).  I only see cyc=00 of stats included in daily processing without cyc= 01 to 23 of stats, as well as missing "prep" step.  Can you let us know more detail on this PR? i.e, Update **AQM** to work with ecflow workflow.  Am I looking at the correct file?  Please advise.

**Comment by Ho-ChunHuang-NOAA** [comment]
@lgannoaa and @PerryShafran-NOAA, **please discard my previous comments**.  After digging further down to the changes made in [lgannoaa:feature/evs-213](https://github.com/lgannoaa/EVS/tree/feature/evs-213).  I understand now this PR is not providing the ecf def/script for AQM but to update the JEVS_AQM_* to comply with NCO standard.

**Comment by Ho-ChunHuang-NOAA** [comment]
@lgannoaa and @PerryShafran-NOAA, I have a question of this PR, why "export cyc=${cyc:-00}" is not included in JEVS_AQM_STATS?  Shouldn't we have a default cyc to avoid the crash? where cyc is needed in scripts/aqm/stats/exevs_aqm_grid2obs_stats.sh

**Pull request merged**
