### PR TITLE
feature/wafs_fixes

### PR DESCRIPTION
**Pull request by malloryprow**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

This PR has two simple fixes for the wafs component that address items on the Fixes and Additions document:

1. Remove cat'ing of the METplus log files
2. Rename J-Jobs to be more in line with other J-Jobs

## Developer Questions and Checklist
* Is this a high priority PR? If so, why and is there a date it needs to be merged by?
> No
* Do you have any planned upcoming annual leave/PTO?
> No
* Are there any changes needed for when the jobs are supposed to run?
> No
  
- [ ] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [ ] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [ ] References the feature branch for `HOMEevs` are removed from the code.
- [ ] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [ ] Jobs over 15 minutes in runtime have restart capability.
- [ ] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [ ] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [ ] Code is using METplus wrappers structure and not calling MET executables directly.
- [ ] Log is free of any ERRORs or WARNINGs.

###  **Set-up**
1. Clone my fork and checkout branch feature/wafs_fixes
2. `ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix`

### ✅  **wafs stats**
 3. `cd dev/drivers/scripts/stats/wafs`
 4. Run the following: `jevs_wafs_atmos_stats.sh`
> - Set `HOMEevs` to the location of the clone.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
The stats job is submitted!

**Review by AndrewBenjamin-NOAA — APPROVED** [review]
I approve these changes once testing concludes. Thanks for going back and making WAFS more consistent with other EVS components.

**Comment by PerryShafran-NOAA** [comment]
The stats job is complete.

See the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr588test/EVS/dev/drivers/scripts/stats/wafs/jevs_wafs_stats.o158386417
The small stats files are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v2.0/stats/wafs/atmos.20241015
The large stats files are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v2.0/stats/wafs/wafs.20241015

**Comment by malloryprow** [comment]
Everything looks good!

**Comment by PerryShafran-NOAA** [comment]
Great!  I'll check out the code and then approve.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
