### PR TITLE
Update how MET_VERSION is defined and curtailed for global_ens wave plots processing

### PR DESCRIPTION
**Pull request by StevenSimon-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

I ran the global_ens wave plot driver with the MET 12.0 Beta4 and COMIN set to point to my local stats archive. This job ran to completion with no ERRORs and WARNINGs printed in the log file. The expected global_ens wave plot tar files were generated and with the proper counts of plot pngs. Lastly, I confirmed within the log file that MET_VERSION=12.0, as expected.  

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Repeat the above testing, but with MET 11.0 as well and with COMIN pointing to the emc.vpppg global_ens stats archive. Add additional testing steps as needed.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

Yes

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

I think so.

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@StevenSimon-NOAA I am starting work on this PR.  I am running with your stats archive and have the code set to MET version 12.  

For the second test, I cannot point to the emc.vpppg archive since that also runs with version 12.  Thus, I will point to the *production* archive, since that does run with version 11.  

I'll let you know when the first test is done.

**Comment by PerryShafran-NOAA** [comment]
@StevenSimon-NOAA I completed the first test.

See the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr481test/EVS/dev/drivers/scripts/plots/global_ens/jevs_global_ens_wave_grid2obs_plots.o132535957

and the plot tarballs here:
/lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/global_ens/wave.20240520

**Comment by StevenSimon-NOAA** [comment]
> @StevenSimon-NOAA I completed the first test.
> 
> See the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr481test/EVS/dev/drivers/scripts/plots/global_ens/jevs_global_ens_wave_grid2obs_plots.o132535957
> 
> and the plot tarballs here: /lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/global_ens/wave.20240520

The global_ens wave plot job with MET 12.0 Beta4 ran to completion with no ERRORS or WARNINGs. The log file indicates that MET_VERSION is properly set to 12.0. The expected global_ens wave plot tar files were generated and with the expected png quantities. A subsample of the plots generated match those generated by the steven.simon global_ens wave plots cronjob.

**Comment by PerryShafran-NOAA** [comment]
Good news!  I will move on to Part 2 of the test.  Please note that I will be using the stats file from production, not the emc.vpppg parallel to be sure we are using data created using v11.

**Comment by PerryShafran-NOAA** [comment]
@StevenSimon-NOAA Please check the v11 output.  

The .o file is here:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr481test/EVS/dev/drivers/scripts/plots/global_ens/jevs_global_ens_wave_grid2obs_plots.o132546449

The tarballs are here:
/lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_ens/wave.20240520

**Comment by StevenSimon-NOAA** [comment]
> @StevenSimon-NOAA Please check the v11 output.
> 
> The .o file is here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr481test/EVS/dev/drivers/scripts/plots/global_ens/jevs_global_ens_wave_grid2obs_plots.o132546449
> 
> The tarballs are here: /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_ens/wave.20240520

The global_ens wave plot job with MET 11.0 ran to completion with no ERRORS or WARNINGs. The log file indicates that MET_VERSION is properly set to 11.0. The expected global_ens wave plot tar files were generated and with the expected png quantities. A subsample of the 20240520 plots generated match those generated by the prod global_ens wave plots cronjob (as shown on the GEFS Wave Verification Web Page).

**Comment by PerryShafran-NOAA** [comment]
Excellent!  Looks like this PR was successful.  I'll do a code check and then merge this code into develop and then put the new files in the bugfix branch as well.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
