### PR TITLE
bugfix/define COMROOT

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

The two jobs were run to test that adding COMROOT fixes COMINx* definitions set by the compath function, and each completed successfully.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

I recommend submitting each of the following jobs once:
```
{HOMEevs}/dev/drivers/scripts/cam/stats/jevs_cam_href_radar_stats.sh 
{HOMEevs}/dev/drivers/scripts/cam/stats/jevs_cam_href_severe_stats.sh
```

Before submitting: 
(1) Symlink to EVS_fix: 
`ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix`
(2) set COMROOT to the following:
`export COMROOT=/lfs/h2/emc/vpppg/noscrub/emc.vpppg`

Each job is allocated 30 minutes but should finish much more quickly.

- [x] Has the code been checked to ensure that no errors occur during the execution? **Yes*

- [x] Do these updates/additions include sufficient testing updates? **Yes**

- [x] Please complete this pull request review by **09/20/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
I want to emphasize that **_this PR is a BUGFIX_** and is allowed to happen after the EVS code freeze. Thanks.

**Comment by ShelleyMelchior-NOAA** [comment]
@MarcelCaron-NOAA , I have cloned your fork and checked out branch `bugfix/define_COMROOT`.

**Comment by ShelleyMelchior-NOAA** [comment]
The tests for the href radar and severe stats jobs are underway. I only tested of cyc=00.
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_href_radar_stats.o82401201`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_href_severe_stats_00.o82401233`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam/atmos.20230919/href/radar`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam/href.20230913`

**Comment by MarcelCaron-NOAA** [comment]
Both jobs completed cleanly, working as expected and correctly defined all COMINx* directories.  This looks good to me!

**Comment by ShelleyMelchior-NOAA** [comment]
Excellent. I will start the code review. Please also do a sync fork.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The tests finished cleanly and as expected. This PR is approved for merge.

**Pull request merged**
