### PR TITLE
Create a developer sandbox for testing and driving EVS

### PR DESCRIPTION
**Pull request by aerorahul**
After discussions w/ @PerryShafran-NOAA and @GeoffManikin-NOAA, this PR:
- creates a directory `dev/` for collecting developer artifacts such as tests, drivers, etc.
- moves `ecf/scripts` to `dev/drivers/scripts`
- renames `.ecf` scripts in `dev/drivers/scripts/` as `.sh` (that is what they are)

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, @aerorahul ,

I will begin work on this today.  I'd like to do a full end-to-end test run on one of the components just to see that it works well.  Once we do that, we'll merge.  We have open PRs, and we'll ask those developers to change to the new structure and re-submit their PRs in the new structure.

We also had a PR that was approved and merged after you submitted this PR - as you can see there are href files that were merged into the ecf/scripts/cam directory.  If you can do the git move again and add to this PR, that would resolve this conflict.  

Thanks!

Perry

**Comment by PerryShafran-NOAA** [comment]
@aerorahul The test I ran for the analyses component ran as expected in the new structure for stats and plots (no prep for this component).  I think I am ready for merge.  Before I do so, can we resolve the conflict by copying over the href ecf files to the new structure, in the same manner you brought in all the other ecf files to become sh files?  

Perry

**Comment by aerorahul** [comment]
> @aerorahul The test I ran for the analyses component ran as expected in the new structure for stats and plots (no prep for this component). I think I am ready for merge. Before I do so, can we resolve the conflict by copying over the href ecf files to the new structure, in the same manner you brought in all the other ecf files to become sh files?
> 
> Perry

Done @PerryShafran-NOAA

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by PerryShafran-NOAA** [comment]
Thank you @aerorahul !  I am ready to merge this PR now.

Perry

**Pull request merged**
