### PR TITLE
Replace sourcing a modulescript with explicit module load commands from the modulescript for NCO EE2 requirements

### PR DESCRIPTION
**Pull request by aerorahul**
This PR:
- replaces instances of `source $HOMEevs/modulefiles/$COMPONENT/$COMPONENT_$STEP.sh` with explicit `module load` commands from the script.
- removes the script containing the module load commands.

This was done with a script:
```bash
#!/bin/bash

set -eu

# Location of PWD
readonly pkg_root=$(cd "$(dirname "$(readlink -f -n "${BASH_SOURCE[0]}" )" )/" && pwd -P)


HOMEevs=${1:-${pkg_root}}

cd $HOMEevs

# Find all ecf scripts in the tree
rm -f ecf_tree; touch ecf_tree
find ./ecf -iname '*.ecf' -print >> ecf_tree

# Loop over all the files in the ecf_tree
for file in $(cat ecf_tree); do

  component=$(echo ${file} | cut -d/ -f4)
  step=$(echo ${file} | cut -d/ -f5)

  echo $file $component $step

  # Script containing modules for this component and step
  modulescript="${HOMEevs}/dev/modulefiles/$component/${component}_${step}.sh"

  # locate the line number in the ecf that is sourcing the above modulescript
  line=$(grep -n "source \${HOMEevs}/modulefiles" $file | cut -d: -f1)

  # Pull out all "module load" from the above modulescript
  rm -f tmpmod; touch tmpmod
  grep "module load" $modulescript >> tmpmod

  # Insert the "module load" right after the source line
  tmp="./sed.$$"
  trap "rm -f $tmp; exit 1" 0 1 2 3 13 15
  sed -e "${line}r tmpmod" $file > $tmp
  cp $tmp $file
  rm -f $tmp tmpmod
  trap 0

  # Remove the line that sources the modulefile
  sed -i "${line}d" $file

  echo
done

# Clean up
rm -f ecf_tree

exit 0
```

Developers should test that the changes are correct.  A spot check was performed on a handful of modified files and the changes were as expected.

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request: No testing has been performed.</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions: All</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[No]**

- [ ] Do these updates/additions include sufficient testing updates? **[No]**

- [ ] Please complete this pull request review by **[ASAP or as resources permit]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by aerorahul** [comment]
Closing as this needs to be directed at `develop`.  Will re-open another PR momentarily.

**Comment by aerorahul** [comment]
On further inspection; `develop` is far away from `release/evs.v1.0.0` in terms of ecflow development.
This will need more work to be done for `develop`, so I am re-opening it as is.

**Comment by malloryprow** [comment]
I see all the dev/modulefiles were deleted but none of the dev/drivers/scripts were updated and still call the dev/modulefiles.

Example: https://github.com/aerorahul/EVS/blob/f71272ebe352ed63386fc3ca7ba5a6847bc1a9d7/dev/drivers/scripts/prep/global_det/jevs_global_det_atmos_prep.sh#L29

Is the plan that the dev/drivers/scripts are moving under ecf/scripts? If so, should they deleted? If not, we either need to leave dev/modulefiles or update the dev/drivers/scripts to have the module loads.

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @malloryprow , I noted the same but couldn't address this PR at the time.
@aerorahul , we need the files in `dev/modulefiles/` to stick around. We were told by NCO that it is OK to have items under `dev/`, that they will be ignored. Our driver scripts in `dev/drivers/scripts/` source the files in `dev/modulefiles/`. Deleting them altogether will make the EMC development driver scripts break (unless we go back to loading them directly in the driver scripts, but that is outside of the scope of EVSv1 and we are on limited time -- not to mention, that is how they used to be constructed but then we were advised to source the module loads from a separate file, so we did.). 

The changes in this PR to directly list the module loads in the ecf scripts are fine. We just can't delete `dev/modulefiles` on the whole.

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA @aerorahul @malloryprow Lin also confirmed yesterday that he already made these changes in his ecflow testing and that it's working well. My recommendation is to leave this PR alone until we get a new ecflow PR from Lin with the same changes. Since Lin's module load changes have been tested, I'd feel better about incorporating those changes into the auth repo. Thanks!

**Comment by ShelleyMelchior-NOAA** [comment]
> @ShelleyMelchior-NOAA @aerorahul @malloryprow Lin also confirmed yesterday that he already made these changes in his ecflow testing and that it's working well. My recommendation is to leave this PR alone until we get a new ecflow PR from Lin with the same changes. Since Lin's module load changes have been tested, I'd feel better about incorporating those changes into the auth repo. Thanks!

Just on quick note for @AliciaBentley-NOAA , this PR is to merge into `release/evs.v1.0.0`, not into develop, just in case that is what you meant w/ your phrasing of "auth repo" in your message. Just wanted to point out that little nuance.

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA Yes, that's correct. We want code in develop first. I asked @aerorahul to switch his PR to develop, but he said he can't because ecflow code isn't in develop. He asked me "how is something in release that isn't in develop?" That's a great question. I wrote it down to discuss with Jason on Wednesday morning. I think that release should be a trimmed version of develop. We can discuss more on Wednesday, but the moral of the story is that we need to get ecflow into develop, too!

**Comment by aerorahul** [comment]
Thanks all. I will close this PR.

**Pull request closed without merging**
