### PR TITLE
feature/rtofs_cat_logs

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

1. "Cat" the METplus and plotting log files (so their contents are in the main log file)

- [ ] Describe testing already performed for this Pull Request:</br>
> I compared the file counts for the prep step to the emc.vpppg parallel. I compared the stats for a VDATE of 20231010 to the emc.vpppg parallel. I compared the plots to the emc.vpppg parallel. I compared the number of log files in DATA to instances of "cat" in the main log file.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>**Set-up**
> 1. Clone my fork and checkout branch feature/rtofs_cat_logs
> 2. cd sorc
> 3. ./build-fix-link.sh

**prep**
> 4. Run dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.sh

**stats**
> 5. Run dev/drivers/scripts/stats/rtofs/jevs_rtofs_argo_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_aviso_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_ghrsst_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_ndbc_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_osisaf_stats.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vppg/$NET/${evs_ver}.

> Note: I haven't added dev/drivers/scripts/stats/rtofs/jevs_rtofs_smap_stats.sh and dev/drivers/scripts/stats/rtofs/jevs_rtofs_smos_stats.sh to the list of jobs to run since there are issues with these datasets recently. If the data in prod/dcom is looking better when it comes time to test the PR we can run them too or run for VDATE=20231010.

**plots**
> 6. Run dev/drivers/scripts/plots/rtofs/jevs_rtofs_argo_grid2obs_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_aviso_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_ghrsst_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_headline_grid2grid_last90days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_ndbc_grid2obs_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_osisaf_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_smap_grid2grid_last60days_plots.sh, and dev/drivers/scripts/plots/rtofs/jevs_rtofs_smos_grid2grid_last60days_plots.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/${evs_ver}.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **11/17/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
I am starting work on this PR, starting with prep.  I am running prep on its usual VDATE for now.

**Comment by malloryprow** [comment]
✔️ **prep is good!**

Files counts are good and I can see the contents of the METplus log files in /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr305test/EVS/dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.o106672396,

I'm good with running the stats and plots together next. We can use VDATE as 20231010 for the stats, and leave VDATE as PDYm3 for the plots.

**Comment by PerryShafran-NOAA** [comment]
I will try VDATE=20231010 for one stats job, to see if anything has aged off of it.  That's 8 days ago, and I don't know if anything in rtofs is connected with input data from com.  Let me start with smap because that's usually fast.

**Comment by malloryprow** [comment]
Sounds good, last time I checked earlier today they were there.

It might be good to clear out /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs/*.20231010. Just to be sure we are working with everything from these new runs.

**Comment by malloryprow** [comment]
I double checked and all dcom input for 20231010 exists.

/lfs/h1/ops/prod/dcom/20231010/validation_data/marine/cmems/ssh/nrt_global_allsat_phy_l4_20231010_20231010.nc (aviso), /lfs/h1/ops/prod/dcom/20231010/validation_data/marine/ghrsst/20231010_OSPO_L4_GHRSST.nc (ghrsst), /lfs/h1/ops/prod/dcom/20231010/validation_data/marine/smap/SP_D2023283_Map_SATSSS_data_1day.nc (smap), and /lfs/h1/ops/prod/dcom/20231010/validation_data/marine/smos/SM_D2023283_Map_SATSSS_data_1day.nc (smos). argo, osisaf, and ndbc use from the rtofs/prep.

It looks like everything will age off tomorrow though as the furthest back date is 20231009. :( I hope that the SMOS and SMAP issues can be fixed soon. It seems it is not updating on the webpage Dataflow pulls from at all!

**Comment by PerryShafran-NOAA** [comment]
Great!  The smap stats run finished for 20231010, now I'll run all the stats runs for that same VDATE.

**Comment by malloryprow** [comment]
Thanks! Did you clear out /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs/*.20231010 directories?

**Comment by PerryShafran-NOAA** [comment]
Of course I didn't.  That would be too smart of me (especially now that I just qsub'd all the stats jobs.)

Let me do that and resubmit.

**Comment by malloryprow** [comment]
Thank you! Just want to ensure everything is cleaned out since we ran for this date for stats in the last PR too.

**Comment by PerryShafran-NOAA** [comment]
We have stats files for all but argo and ndbc, which are still running, as expected.  

The .o files are here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr305test/EVS/dev/drivers/scripts/stats/rtofs
The stat files are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs/rtofs.20231010

In the meantime, I will submit the plots job.

**Comment by PerryShafran-NOAA** [comment]
Also remember - we're not just looking at stats and plots files, but also to see whether all the log output that is written to $DATA is written out in the .o file.  Be sure you're looking at the .o files for that log output.

**Comment by malloryprow** [comment]
stats is good so far for argo, aviso, ghrsst, osisaf, smap, and smos. 👍 Files are the same, and the number of instances of "cat " in the .o matches the number of log files produced in the $DATA/logs for each.

ndbc stats will probably be done around 5 today, so I will check those in the morning.

I'll monitor the plots jobs.

**Comment by PerryShafran-NOAA** [comment]
Thank you!  Are there logs in the plot jobs that we should be looking at as well?

**Comment by malloryprow** [comment]
Yup! They are all done minus argo right now, so I'll start looking into them.

**Comment by malloryprow** [comment]
✔️ **plots is good!**

Tar files are the same, and the number of instances of "cat " in the .o matches the number of log files produced in the $DATA/logs/rtofs for each.

**Comment by PerryShafran-NOAA** [comment]
Thank you, I see the log files.  

Looks like we're good!  We have ndbc stats still running.  Want me to wait until this job is finished to merge?

**Comment by malloryprow** [comment]
Yes! Let's wait until ndbc stats is done. I know it will be a few hours yet.

**Comment by PerryShafran-NOAA** [comment]
OK, let me to a code review while we wait.  (Though that should take a bit less than a few hours.)

**Comment by malloryprow** [comment]
✔️ **stats is good!**

I checked out the ndbc stats this morning. The final stat file is the same as the parallel, and the number of instances of "cat " in the .o matches the number of log files produced in the $DATA/logs.

This has my stamp of approval for merging.

**Comment by PerryShafran-NOAA** [comment]
OK, great!  I will go ahead and merge.  Looks like you already did the sync fork.

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
