### PR TITLE
Bugfix/snowfall grib2 pdt

### PR DESCRIPTION
**Pull request by RoshanShrestha-NOAA**
This pull request fixes the errors in snowfall stats job which was noticed since beta upgrade of MET/METplus.

1. Clone my fork at the Bugfix/snowfall grib2 pdt.
2. Symlink /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix locally to fix
3. Use COMIN to the parallel directory /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d
4. Run dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_rap_snowfall_stats.sh
5. Run dev/drivers/scripts/stats/mesoscale/jevs_mesoscale_nam_snowfall_stats.sh
6. The jobs should use qsub -v vhr=00 to submit jobs

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@RoshanShrestha-NOAA I am beginning to test this PR. We will run this PR twice.

First, we will run it as is.  Currently your code is set to the production versions of MET and METplus (MET v 11.0.2 and METplus v 5.0.1).  We will test it in this manner.  Next, we will change the settings to the beta versions and see how well the test does using these versions.  This PR is needed due to an issue exposed in the test vs. the parallel, so we need to test using the beta versions.

I will let you know when the first test is complete.

@AliciaBentley-NOAA @ShelleyMelchior-NOAA for awareness.

**Comment by PerryShafran-NOAA** [comment]
@RoshanShrestha-NOAA Your first test is complete.

Please check the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr462test/EVS/dev/drivers/scripts/stats/mesoscale
And the stats output here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/mesoscale/atmos.20240403

Please let me know how things look.

**Comment by RoshanShrestha-NOAA** [comment]
> @RoshanShrestha-NOAA Your first test is complete.
> 
> Please check the .o files here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr462test/EVS/dev/drivers/scripts/stats/mesoscale And the stats output here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/mesoscale/atmos.20240403
> 
> Please let me know how things look.

Thanks @PerryShafran-NOAA.  The .o files and outputs look good.

**Comment by PerryShafran-NOAA** [comment]
Good news!  Now I am going to make the test to run against the beta versions.  I will let you know when these are done.

**Comment by PerryShafran-NOAA** [comment]
Please take a look at the output once again, both the .o files and the stat files, in the same directories as before.

Also please do a sync fork.

I am leaving for the day so I'll check back later on.

**Comment by RoshanShrestha-NOAA** [comment]
> Please take a look at the output once again, both the .o files and the stat files, in the same directories as before.
> 
> Also please do a sync fork.
> 
> I am leaving for the day so I'll check back later on.

The outputs look all good with the beta versions as well. I have synced the fork to the develop. Thanks

**Comment by PerryShafran-NOAA** [comment]
Thank you!  I will go ahead and merge.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
