### PR TITLE
Feature/cam restart

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

Restart capabilities were developed for all cam/stats and /plots jobs.  All jobs were tested with the restart capabilities in place and all completed successfully.  Each stats job was run twice using the same VDATE and cyc value both times.  Each plots job was run twice using the same VDATE.  The walltimes of the second runs were substantially reduced. 

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

For testing, I recommend running each of the following jobs twice:
```
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_hireswarw_grid2obs_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_hireswarwmem2_grid2obs_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_hireswfv3_grid2obs_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_hrrr_grid2obs_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_namnest_grid2obs_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_hireswarw_precip_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_hireswarwmem2_precip_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_hireswfv3_precip_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_hrrr_precip_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_namnest_precip_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_hireswarw_snowfall_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_hireswarwmem2_snowfall_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_hireswfv3_snowfall_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_hrrr_snowfall_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/stats/jevs_cam_namnest_snowfall_stats.sh
{HOMEevs}/ dev/drivers/scripts/cam/plots/jevs_cam_grid2obs_plots.sh
{HOMEevs}/ dev/drivers/scripts/cam/plots/jevs_cam_precip_plots.sh
{HOMEevs}/ dev/drivers/scripts/cam/plots/jevs_cam_snowfall_plots.sh
```
...replacing `{HOMEevs}` with the location of the EVS testing directory.  For best results, I recommend running the second job after the first job has completed.  No changes need to be made between the first and second runs.  Before running, in the driver scripts…

1. Where relevant, point any COMIN variables to the EVS parallel archive (using “`emc.vpppg`” in place of “`${USER}`”): 
- `export COMIN=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver/stats/$COMPONENT`
- e.g., `export COMINmrms=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver/prep/$COMPONENT`
2. For stats tests: predefine the VDATE and cyc variables in each driver script before running.  I recommend testing with `export cyc=12`.  VDATE should be older than about two days (if the test date is 20230827, VDATE should be `export VDATE=20230824` or earlier) to ensure prep steps have already completed.
3. For plots tests: predefine the VDATE.  Any VDATE should be fine.

Jobs will be checked for successful completion, and second jobs will be checked for reduced walltimes.

- [x] Has the code been checked to ensure that no errors occur during the execution? **[Yes]**

- [x] Do these updates/additions include sufficient testing updates? **[Yes]**

- [x] Please complete this pull request review by **[09/10/2023]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, @MarcelCaron-NOAA , 

I have begun work on this PR.  I am following instructions to set up the emc.vpppg as well as cyc and VDATE.

I do have a question, though; your wallclock time is still 10 hr.  One would think that your job would complete in the 10-hr allotted time.  To check out the restart capability, would you like me to reduce the wallclock to a time that the job would not yet be complete (say 1 hr)?  That is a good test of restart, to see if the job picks up where it left off the previous time.  

Although, this test isn't bad either.  The second job should finish nearly in an instant since all the stats would have been created.  

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi @PerryShafran-NOAA yes that is a great idea, and fine with me.  I would opt to test this the way you've been testing other restart capabilities.

**Comment by PerryShafran-NOAA** [comment]
OK great.  I'm starting with the first job listed (grid2obs hireswarw) and doing that one alone, and set the wallclock to 1 hr.  Then for the 2nd run, I'll set it back to 10-hr and resubmit.

Perry

**Comment by MarcelCaron-NOAA** [comment]
Okay sounds good!

**Comment by PerryShafran-NOAA** [comment]
Hi, @MarcelCaron-NOAA ,

Before I continue any further, I'd like to check to see if this is what you had expected.

Please see the .o files here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr212test/EVS/dev/drivers/scripts/cam/stats
1st run:  jevs_cam_hireswarw_grid2obs_stats.o78536835
2nd run: jevs_cam_hireswarw_grid2obs_stats.o78538570

You have files in the directory /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/atmos.20230825/hireswarw, with a restart directory structure.  

You have no files in any of the COMOUTfinal directory areas.  Should there be?  Just checking to see that everything is what is expected.

Interestingly, the first run completed in only 12 minutes with no indication that the job was killed due to going over the wall clock time.  We also need to make sure that the wallclock request is not too much above the actual running time of the job.  

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi @PerryShafran-NOAA yes this is as expected.  

Since this is not the final cycle of the day, no files in COMOUTfinal are produced, only an intermediate stat file for the 12Z cycle.  

Also, these stats jobs are normally relatively short, but can exceed 15 minutes, more often with hrrr and namnest.  In my final CAM PR (upcoming), I plan to go through each job and adjust the wall clock times based on the average run time .  Is that okay?

**Comment by PerryShafran-NOAA** [comment]
Sure, that's fine.  You can also include this in this particular PR as well.

OK, I'm then going to start working on all the other grid2obs stats jobs.  Then the precip jobs.  They will have the same cyc and VDATE as the hireswarw.  

Perry

**Comment by PerryShafran-NOAA** [comment]
OK, all the grid2obs scripts have run twice.  Please check the .o files in the directory /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr212test/EVS/dev/drivers/scripts/cam/stats and all the stats directories in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/atmos.20230825.  Let me know if all looks good and I'll move on to the precip files.

Perry

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA thanks.  All jobs completed successfully and second runs completed over reduced wall times.  Looks good to me!

**Comment by PerryShafran-NOAA** [comment]
Excellent!  Moving onto the precip jobs.

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Marcel,

All precip jobs failed, and for the same reason:

```
BEGIN: cam_stats_precip_create_poe_job_scripts.py
ERROR: No job files created in /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_cam_hireswfv3_precip_stats.78559556.cbqs01/precip/stats/METplus
_job_scripts/reformat
888 + export err=1
888 + err=1
```
Please look at any of the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr212test/EVS/dev/drivers/scripts/cam/stats

Is there something that I missed when setting this up or running this?  

Perry

**Comment by PerryShafran-NOAA** [comment]
Oh, I think that for precip, the cyc has to be somewhere between 19 and 22, so maybe that's why?  cyc=12 doesn't work for precip I think.

Perry

**Comment by PerryShafran-NOAA** [comment]
OK, I had to make a few changes:

- I made cyc=19 in order to get a correct running cycle time
- I made VDATE=20230826 because the job was getting killed in looking for model data from 20230822, which was no longer on disk.

But there still seems to be some sort of problem:

```
BEGIN: cam_check_input_data.py
ERROR: The following input data were not found:
/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/cam/mrms.20230826/mrms.t04z.01h.ak.gb2
Running echo "Warning: No MRMS data were available for valid date 20230826 at 04Z." >mailmsg
Running echo "Missing files are:
mrms.t04z.01h.ak.gb2
```

And I looked in the emc.vpppg directory, and this particular file was not there, though the prep job was completed:

```
-rw-r--r-- 1 emc.vpppg vpppg 489202 Aug 27 18:30 mrms.t00z.01h.ak.gb2
-rw-r--r-- 1 emc.vpppg vpppg 552780 Aug 28 18:30 mrms.t01z.01h.ak.gb2
-rw-r--r-- 1 emc.vpppg vpppg 456080 Aug 28 18:30 mrms.t02z.01h.ak.gb2
-rw-r--r-- 1 emc.vpppg vpppg 470386 Aug 28 18:30 mrms.t03z.01h.ak.gb2
-rw-r--r-- 1 emc.vpppg vpppg 469441 Aug 28 18:30 mrms.t05z.01h.ak.gb2
-rw-r--r-- 1 emc.vpppg vpppg 483314 Aug 28 18:30 mrms.t06z.01h.ak.gb2
-rw-r--r-- 1 emc.vpppg vpppg 473295 Aug 28 18:30 mrms.t07z.01h.ak.gb2
-rw-r--r-- 1 emc.vpppg vpppg 535966 Aug 28 18:30 mrms.t08z.01h.ak.gb2
```

If you notice, no t04z file is in here.  I'm not sure why.

One thing that I need to peg you on.  Our scripts are not supposed to produce an error code even for missing data.  For example:

```
2227 + export err=1
2227 + err=1
2227 + err_chk

-------------------------------------------------------------
-- FATAL ERROR: Job jevs_cam_hireswarw_precip_stats.78560568.cbqs01 failed RETURN CODE 1
-- ABNORMAL EXIT at Mon Aug 28 20:10:50 UTC 2023 on clogin01
-------------------------------------------------------------
```

We need to ensure that our jobs do not produce an error code even if an error is produced, because once errors are produced, NCO will send the code back to us.  Thus, you need to force an error code of 0 in these cases even if there is missing data that will cause the job to end.

If there is a way for this job to actually continue on without being killed, more the better.  

This will need some fixing by you to address.  

In the meantime, is there an mrms area to see whether this file actually exists and there was a blip perhaps in copying over to the emc.vpppg prep area?  Or is this file just non-existent?

I will do a re-test of this tomorrow, assuming that the prep job is complete.  But the job should not be killed for missing data.  This needs to be fixed.

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi @PerryShafran-NOAA, apologies about the incorrect instructions for precip stats runs;  yes I'd forgotten that only later cycles (19-23Z) will work.  In that case, 19Z is a good choice.

The choice of VDATE will matter here.  MRMS-ak data is occasionally missing from the COMIN directory, as it was on 20230826:

```
[marcel.caron@clogin03 EVS] ls /lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-*0000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-000000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-010000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-020000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-030000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-050000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-060000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-070000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-080000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-090000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-100000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-110000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-120000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-130000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-140000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-150000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-160000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-170000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-180000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-190000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-200000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-210000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-220000.grib2.gz
/lfs/h1/ops/prod/dcom/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE/MultiSensor_QPE_01H_Pass2_00.00_20230826-230000.grib2.gz
```

For this reason, I recommend using VDATE=20230825 instead, as no data were missing on any valid date in the period between 20230822-20230825 as far as I can tell.

Also, I changed the exit code to 0 when data is missing.  I will check that the FATAL ERROR/ ABNORMAL EXIT message doesn't get outputted in these situations.

**Comment by PerryShafran-NOAA** [comment]
Hi, Marcel,

When I used VDATE=20230825 previously, then the job was not able to find older CAM data from the production 20230822 directory (which is why I went to 20230826).  I'll be trying this again tomorrow, in which case I'll try 20230826 again.

Perry

**Comment by MarcelCaron-NOAA** [comment]
Ah okay.  That sounds good.  Thanks.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA - can we back out the mesoscale changes and put that into a separate PR for mesoscale only?  Think that would lessen the confusion on these issues.

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Sure!  I can add them in a mesoscale PR.

**Comment by PerryShafran-NOAA** [comment]
Hi, @MarcelCaron-NOAA:

I am restarting this test for precip plots, with VDATE=20230827.

In the meantime, there are conflicts that are likely due to the latest CAM PR removing mPING data.  Could you merge develop into this fork?  

Thanks!

Perry

**Comment by PerryShafran-NOAA** [comment]
Also; I ran the precip stats jobs twice.  Please take a look at the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr212test/EVS/dev/drivers/scripts/cam/stats

and the output directories here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/atmos.20230827

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi @PerryShafran-NOAA yes, the changes to develop might have affected the tests here.  I just merged those changes so there shouldn't be any problems.

**Comment by MarcelCaron-NOAA** [comment]
> 

Actually nevermind, since we'd already tested grid2obs stats we wouldn't have encountered any issues.  

Checking the precip output now...

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA I checked the output files and both jobs for each model completed cleanly, and each of the second jobs completed with a substantially reduced cput and wall time.  Output stats look normal to me.

**Comment by PerryShafran-NOAA** [comment]
Great!  Moving on to plots now.

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, @MarcelCaron-NOAA 

I am not getting any plots:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr212test/EVS/dev/drivers/scripts/cam/plots/jevs_cam_grid2obs_plots.o78749726

I set COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/cam.  Is this correct?  This should be working if I did that right.  If I didn't set something else right, please let me know.

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hm.  Not sure what happened, but it hasn't produced any plots because it thinks it already restarted.  Can you try deleting the current restart directory and rerunning, to see if the same issue occurs?
```
rm -rf /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/cam/atmos.20230829/grid2obs/restart
```

**Comment by PerryShafran-NOAA** [comment]
OK, let's see if that works.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Today, the run is good!  I set the wallclock time to 1 hr, and I see plots have formed in the DATA directory.  

In this case, the job did not complete in the walltime available, giving this a great test of the restart capability.  I am going to resubmit the job, and then we'll see if we get all the plots in one tar file.  Stay tuned.

I'll also run the precip job.

For snowfall, I'll need to use your stats archive, if you can point me to it.

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA Great!  For snowfall, you can set COMIN to:
```
export COMIN=/lfs/h2/emc/vpppg/noscrub/marcel.caron/$NET/$evs_ver/stats/$COMPONENT
```

**Comment by PerryShafran-NOAA** [comment]
In the file:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr212test/EVS/dev/drivers/scripts/cam/plots/jevs_cam_grid2obs_plots.o78812537, I am noticing at the top of the output file the existing restart plots being copied over to the stmp working directory.  This is good news.  The job is not done yet, but it's looking promising.

Perry

**Comment by PerryShafran-NOAA** [comment]
Apologies, but the machine switch makes things a little more challenging to validate.

I did move the PR over to Dogwood, and you can review all the output files.  If you need to see the actual tar files, I can bring those over, but they're stuck on Cactus.  Let me know if you need to see them.

In the meantime, you can look at the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr212test/EVS/dev/drivers/scripts/cam/plots

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi @PerryShafran-NOAA, everything looks good to me.  The output logs either hit the walltime (first precip, first and second grid2obs plots jobs) or completed successfully.  The second runs seem to have copied restart plots successfully and then skipped the jobs that had already completed in the first run, as expected.

**Comment by PerryShafran-NOAA** [comment]
Good news!  Do you think you need to see the actual plot tar files?  Let me know and I'll figure out how to have you see them.

Perry

**Comment by MarcelCaron-NOAA** [comment]
No I don't think so; I'm okay seeing that jobs completed cleanly and that the restart function kicked in as intended.

**Comment by PerryShafran-NOAA** [comment]
OK, I'm going to check the code review and get this merged in.

Perry

**Comment by PerryShafran-NOAA** [comment]
Before I merge in, I'd like to ensure that you do a sync fork to ensure that the develop branch is updated within your fork.

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA Okay this should be up to date now.

**Comment by PerryShafran-NOAA** [comment]
Super!  Let's try a merge now.

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
