### PR TITLE
ecflow for EVS base

### PR DESCRIPTION
**Pull request by lgannoaa**
This version serve as the base line for upcoming NCO/EVS team meeting.
The condition of this version of the ecflow is:
(1) The definition is developed based on current cron based vpppg parallel.
(2) The script has development wired location removed.
(3) The job cards have extend memory and wallclock setting due to know wcoss system issues.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @lgannoaa , since this PR is just the filling in of the `ecf/` directory, I do not have a problem merging this into `release/evs.v1.0.0` branch. However, doing so will cause `release/v1.0.0` to deviate from `para` since `para` is what runs for the emc.vpppg parallel and does not have the `ecf/` scripts included. Is this difference OK for you?

**Comment by lgannoaa** [comment]
Please keep release/v1.0.0 and para fully in rync. ecf directory can be added into it at this time.

**Comment by ShelleyMelchior-NOAA** [comment]
OK. @PerryShafran-NOAA , when I approve this PR for merge into `release/evs.v1.0.0`, @lgannoaa also wants `para` updated (so that `release/evs.v1.0.0` remains in sync with `para`). If you are OK w/ that, I can update `para`. The only change you will notice is the population of the `ecf/` directory. Let me know your thoughts.

**Comment by PerryShafran-NOAA** [comment]
I'm OK with that.  A merge in this order is not one that I have done before, but if you can put things into para, then I'll simply pull the changes into emc.vpppg.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
This PR includes the files to populate the `ecf/` directory. All changes and additions are approved for  merge into `release/evs.v1.0.0`.

**Comment by ShelleyMelchior-NOAA** [comment]
@lgannoaa , branches `para` and `release/evs.v1.0.0` now contain the same synced files in `ecf/` per this PR's changes.

**Pull request merged**
