### PR TITLE
feature/global_det_atmos_mail

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

* Adds mail function for global_det atmos prep and stats
* Adjustments to ecf script resources

- [ ] Describe testing already performed for this Pull Request:</br>

> This has been running in a cron for a few days now.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> Checkout the branch
>Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_130/evs_global_det_atmos_set_up.sh. This script will link the fix files and build prep executables.
>Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_130/run_evs_global_det_atmos_prep.sh. Run it. I can check the output if you would like, but getting the emails is the important things here. It should run some time after 1400Z.
>Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_130/run_evs_global_det_atmos_stats.sh. Run it.  I can check the output if you would like, but getting the emails is the important things here. It should run some time after 1630Z.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **06/30/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
Hi Mallory,

I'm not sure if you were trying to delete "exclhost" in all scripts or not,
but I noticed a spot in your PR where memory was increased, but exclhost
wasn't deleted. Apologies if this is intentional!

ecf/scripts/global_det/stats/jevs_gfs_atmos_grid2obs_stats.ecf
<https://github.com/NOAA-EMC/EVS/pull/130/files#diff-f515fffa86d75df1ed8ffb4d7d7bb4502f5094d83b451b045fde0c689daac28f>

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by malloryprow** [comment]
@AliciaBentley-NOAA Yes! I left it in some since they are using the whole node. I removed it from ones that don't have "ncpus=128". I think I got them all, but I might have missed a few. Let me know if you see one I missed!

**Comment by ShelleyMelchior-NOAA** [comment]
Just FYI that I have cloned your fork and checked out `feature/global_det_atmos_mail`. I will begin working on the PR soon.

**Comment by ShelleyMelchior-NOAA** [comment]
I have copied and prepared the `run_evs_global_det_atmos_*` scripts. I will wait until after the recommended 1400Z and 1630Z before running.

FYI -- I updated my local cp of your `run_evs_global_det_atmos_*` scripts to include the new `scripts/` dir under `ecf/`.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran the two run scripts after the designated times of 1400Z and 1630Z. Please review.

Prep log file:
`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/MR/EVS/ecf/scripts/global_det/prep/jevs_global_det_atmos_prep_00.o75078269`
Stats log file:
`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/MR/EVS/ecf/scripts/global_det/stats/jevs_*_stats_00.o*`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0`

I ran stats pointing to my local prep that was created. Let me know if I should point to the EVS parallel's prep data files instead.

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA: Mallory is out of the office and will return on Thursday 6/21/23. I'm unsure if your test will need to be redone later this week or not in order to compare results, but I wanted to give you a heads up either way. Thanks!

**Comment by ShelleyMelchior-NOAA** [comment]
@malloryprow b/c of the machine switch, I went ahead and re-ran on cactus, too, just to be thorough.

prep log:
`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/MR/EVS/ecf/scripts/global_det/prep/jevs_global_det_atmos_prep_00.o65271642`
stats log:
`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/MR/EVS/ecf/scripts/global_det/stats/jevs_*_stats_00.o*`

COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0`

**Comment by ShelleyMelchior-NOAA** [comment]
FWIW, @GeoffManikin-NOAA confirmed he is getting **_a lot_** of emails!  lol

**Comment by malloryprow** [comment]
Yes! I am too so it is working, lol. I think there was a production switch yesterday? None of my prep data would have been on the machine.

**Comment by AliciaBentley-NOAA** [comment]
Yes, there was a production switch yesterday! I'm sure that the missing
email alerts were off the charts!

___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Developer acknowledged email alerts were effective and results are as expected. Code changes look good.

**Pull request merged**
