### PR TITLE
replaced mallory.row in MAILTO with qi.shi for global-det

### PR DESCRIPTION
**Pull request by QiShi-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

> replace mallory.row@noaa.gov with qi.shi@noaa.gov for global-det

## Developer Questions and Checklist
* Is this a high priorty PR? If so, why and is there a date it needs to be merged by?
>No
* Do you have any planned upcoming annual leave/PTO?
>At AGU week of 12/9
* Are there any changes needed for when the jobs are supposed to run?
>No
  
- [ ] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [ ] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [ ] References the feature branch for `HOMEevs` are removed from the code.
- [ ] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [ ] Jobs over 15 minutes in runtime have restart capability.
- [ ] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [ ] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [ ] Code is using METplus wrappers structure and not calling MET executables directly.
- [ ] Log is free of any ERRORs or WARNINGs.

## Testing Instructions

> test jevs_global_det_wave_prep.sh
>set HOMEevs to testing clone
>set COMOUT to testing location
>set COMINobsprod to fake location

### CODE REVIEW

**Review by AliciaBentley-NOAA — APPROVED** [review]
I have reviewed the changes made in this PR and think that they look good! I approve this PR to be merged after testing shows that Qi gets the missing emails now instead of Mallory. Thanks!

CC @malloryprow @QiShi-NOAA

**Comment by malloryprow** [comment]
@QiShi-NOAA Since you are at AGU for the rest of the week, I will wait to do testing next week. We will need you to confirm the testing results and make sure you got the missing data emails.

**Comment by QiShi-NOAA** [comment]
Hi Mallory,

Sounds good.

Best,
Qi

**Comment by malloryprow** [comment]
Can you do a sync fork @QiShi-NOAA? If you need a reminder how to shoot me a GChat.

**Comment by malloryprow** [comment]
### jevs_global_det_wave_prep (with COMINobsproc=/lfs/h1/ops/FAKE/com/obsproc/v1.2)
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr616/EVS/dev/drivers/scripts/prep/global_det/jevs_global_det_wave_prep_00.o209097494
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_global_det_wave_prep_00.209097494.dbqs01
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr616/prep/global_det/wave

@QiShi-NOAA Did you get the missing data emails?

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow Since there is a WCOSS2 outage all of next week now, do you think you could potentially run some of these jobs today? Maybe with dummy missing files? We'll know if they worked if Qi gets missing file emails, and those emails will still be in her inbox on Monday. If she confirms that she got missing file emails on Monday, maybe we could merge this PR, despite the WCOSS2 outage? Just a thought to consider! It might be a bad idea, just let us know!

CC @QiShi-NOAA 

P.S. I think you might already be doing this, which is cool! I just got missing file emails!

```
Warning: No GDAS Prepbufr was available for valid date 2024121206
Missing file is /lfs/h1/ops/FAKE/com/obsproc/v1.2/gdas.20241212/06/atmos/gdas.t06z.prepbufr
Job ID: jevs_global_det_wave_prep_00.209097494.dbqs01
```

**Comment by QiShi-NOAA** [comment]
Yes, I have received missing data emails.

Best,
Qi

**Comment by malloryprow** [comment]
Yup, we are testing now! I think I'm okay just testing one job to confirm. @AliciaBentley-NOAA we can test more if you would like.

**Comment by AliciaBentley-NOAA** [comment]
I'm also OK testing one job to confirm that the emails work! All other changed email lines are changed in the same way, so if one works, they should all work. Thank you, @malloryprow and @QiShi-NOAA!

**Review by malloryprow — APPROVED** [review]
Changes are good and testing successful!

Thanks @QiShi-NOAA!

**Pull request merged**
