### PR TITLE
Feature/global_det atmos_headline_long_term

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

> Long term stats and plots jobs were submitted to queue. Tested to generate November 2022, December 2022, and January 2023 monthly statistics. Graphics approved by @AliciaBentley-NOAA at https://emc.ncep.noaa.gov/users/verification/global/gfs/atmos/para/long_term/monthly_yearly_stats/.
> Headline plots approved by @AliciaBentley-NOAA at https://emc.ncep.noaa.gov/gmb/mpr/headline_quick_look/

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
>Checkout branch
>Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_61/evs_global_det_atmos_set_up.sh. Open and set EVSclone to where the clone is. This script will link the fix files and clear out the user's stats/global_det directory and copy my stats/global_det directory since my directory has more data in it.
>Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_61/run_evs_global_det_atmos_long_term_stats.sh. Open and set EVSclone to where the clone is. This script will submit the ecf scripts to run the long term stats job.
>Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_61/run_evs_global_det_atmos_long_term_plots.sh. Open and set EVSclone to where the clone is. This script will submit the ecf scripts to run the long term plots job.
>Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_61/run_evs_global_det_atmos_headline_plots.sh. Open and set EVSclone to where the clone is. This script will submit the ecf scripts to run the headline plots job.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **3/22/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

In your setup script, you have:  

`cp -r /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det global_det`

Usually in your setup files, you link to the global_det directory instead of copying the whole directory, which takes a lot of time.  Did you mean for this to be ln and not cp?  Or is copying important in this case?

Thanks!

Perry

**Comment by malloryprow** [comment]
Yes! Different this time because the long_term stats jobs will write to [your output path]/dev/com/evs/v1.0/stats/global_det/long_term. All the long_term stats and plots won't run in prod/operations.

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

I'm not sure that the stats job was done correctly.  There is a whole lot of data in the directory /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det.  But the job seems to end abruptly.  

If you look at the output file /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/global_det/stats/jevs_global_det_atmos_long_term_stats_00.o48932184, the script seems to end abruptly, with the last line being the python call, but there is nothing after that.  Doesn't seem normal.  Can you take a look here?

Thanks!

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Is the job still running?

**Comment by PerryShafran-NOAA** [comment]
It seems not to be running.  I don't see it on my list of jobs running.

Perry

**Comment by malloryprow** [comment]
Weird. That is what it looks like when the job is running. If the job ended (successfully or not), there should have been all the output from the epilogue.

**Comment by PerryShafran-NOAA** [comment]
Think I should try again?  Might be just a weird blip.  

Perry

**Comment by malloryprow** [comment]
Yeah, try again. Send me the output path and I'll watch and see if anything weird is going on. It seems maybe something with the job scheduler.

**Comment by AliciaBentley-NOAA** [comment]
There is a lot of weirdness going on now with the reduced nodes. Hopefully
trying again will fix this!

___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by malloryprow** [comment]
I ran "qstat -xf 48932184" and I am seeing things like...

job_state = F
Exit_status = -20

**Comment by malloryprow** [comment]
I think the node went down???

03/08/2023 17:24:09  S    Exit_status=-20
03/08/2023 17:24:09  S    Job deleted, execution node nid001381.cactus.wcoss2.ncep.noaa.gov down

**Comment by PerryShafran-NOAA** [comment]
Good detective work!  Where did you find that info?  I didn't see that.

Perry

**Comment by malloryprow** [comment]
I did "/sfs/admin/scripts/tracejob.sh 48932184"

**Comment by PerryShafran-NOAA** [comment]
I just wanted to note that the stats job completed normally this time.  So it's evident that the killing of that node yesterday killed the job abruptly as well.  I simply re-ran today and all was good. 

I'm now going to work on the plots portion of the job.

Perry

**Comment by PerryShafran-NOAA** [comment]
OK, all jobs seem to have finished.  I hope I did things right.  

The stats are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det
The plots are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/plots/global_det

Some questions:

1) In the stats directory, I see a whole bunch of files.  I think most were copied in from the scripts files, but what is the VDATE for the current run?  Some items have new data for 20230307, others have new data for 20230308 and other directories are empty for 20230308.  I am confused as to what I should be seeing here.

2) In the plots directory, the  two directories created were **headline.20230308**, but **long_term.20230309**.  And in the long_term directory, the file has v202302 on it.  Just wanted to confirm that all of this is correct.  It seems unusual and confusing.

Thanks!

Perry

**Comment by malloryprow** [comment]
Thanks for running all this!

1. /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det/long_term is the full archive of monthly and annual means from all the verification systems we have used at EMC for global deterministic models. Some data we have goes back to 1984. There is not necessarily a VDATE for the long term stats since we are running over bulk monthly statistics, it is more like a VDATE month and year. It is running the monthly statistics for 2023 02 (last month). In this case, only the evs_* files will/should update in the directories. "ls -ltr /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det/long_term/monthly_means/gfs" shows that is the case. I compared the files to what I have and the _**long term stats are good**_.
2. For the long term stats output, I had the COMOUT directory (here "longterm.20230309") is longterm.$PDY (https://github.com/malloryprow/EVS/blob/5f03a157df1f7788e939683def10fbd9a80366c8/jobs/global_det/plots/JEVS_GLOBAL_DET_ATMOS_LONG_TERM_PLOTS#L60) so it is reflecting the date the job was run, and have the VDATE month and year in the tar file name (https://github.com/malloryprow/EVS/blob/5f03a157df1f7788e939683def10fbd9a80366c8/scripts/global_det/plots/exevs_global_det_atmos_long_term_plots.sh#L34). I can see how this is confusing now. @AliciaBentley-NOAA Should be left as is or do you have any suggestions for the COMOUT path for the long term plots? Should it just be "long_term" like the stats are? The full path in discussion here is: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/plots/global_det/long_term.20230309/evs.plots.global_det.atmos.long_term.v202302.tar.

The _**headline plots look good**_ (they are all in https://emc.ncep.noaa.gov/gmb/mpr/headline_quick_look/)
The _**long term plots look good**_ (https://www.emc.ncep.noaa.gov/users/verification/global/gfs/atmos/para/long_term/monthly_yearly_stats/)

**Comment by AliciaBentley-NOAA** [comment]
I can see how that would be confusing too. I agree with Mallory that it
could be "long_term" like the stats are. It's consistent and clearer. Would
that help, Perry?

___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
Mallory's explanation really helps me, and based on that it seems that all the stats and plots are as expected.  I'm not sure that I expected this to be different than the rest of the global_det stats/all of EVS, but it makes sense for the long term plots, if it is a monthly mean for 202302, with the result being the same no matter what day it is run.  Thus I am OK with the date for the plotting being the date that it's run and not necessarily a VDATE.  

Currently the directory for plots *is* long_term, so that's good.  My confusion was more about the date stamp in the directory name and the tar file name.  The explanation helped a lot.  

Also this would be good to know:
- Is this a prod job?  Or to be run manually in dev?
- Is this new ecf file for to be run in cron, or is this ecf file just for testing?  I'd need to add it to the parallel when I incorporate new PRs into there.

Thanks!

Perry

**Comment by malloryprow** [comment]
It will be run manually in dev since we need access to the archive.

@AliciaBentley-NOAA Should I change the COMOUT directory name for the long_term plots for consistency or leave it?

**Comment by AliciaBentley-NOAA** [comment]
I tend to side with consistency (which Logan says has made the EVS parallel
look like a dream!), so I suggest making it consistent. Up to you and Perry
if he needs to run it again after that change is made or not!
___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by malloryprow** [comment]
@AliciaBentley-NOAA I agree. I'll change it!

**Comment by PerryShafran-NOAA** [comment]
Y'know, I totally missed the long_term directory!  The global_det directory is a big directory, and I didn't know that I had to look there.  

So - I'm confused to what we are changing tbh.  Are we saying change the long_term directory in stats to have the date of the run attached to it, like it is for plots?  Then I would totally agree.  

And btw, I noticed that these long term stats are written in VSDB format.  VSDB lives!  (I have an affinity for VSDB since I was there when VSDB was invented, so looks like at least the format isn't going away!  But for long term stats, this has to be done since all the older stats are in VSDB.)

Perry

**Comment by malloryprow** [comment]
Just for the long_term plots COMOUT is changing, so with the change

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/plots/global_det/long_term.20230309/evs.plots.global_det.atmos.long_term.v202302.tar

would be

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/plots/global_det/long_term/evs.plots.global_det.atmos.long_term.v202302.tar

**Comment by PerryShafran-NOAA** [comment]
Oh, getting rid of the date in the plots directory, not adding it in for the stats directory.  

Since this is not running in prod, we wouldn't need a date of any sort for NCO to need to check for their scrubber, since this output isn't actually being written in prod, correct?  In that case, this change would be good.  Otherwise, I'd advocate for having the run date in both the stats and plots directories.  

And yes, I would like to run again when the change is made.

Thanks!

Perry

**Comment by malloryprow** [comment]
Correct!

I made the changes and running to make sure there isn't anywhere that I missed it. Once that is done, I'll commit that changes and you can retest!

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Updates made, you're good to retest

**Comment by PerryShafran-NOAA** [comment]
I completed the tests late last Friday - if you could take a look at the output, that would be great.

Thanks!

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Looks good! Image counts in the tar file match the one I ran on Friday too.

**Comment by PerryShafran-NOAA** [comment]
Excellent!  I will approve and merge.

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
