### PR TITLE
feature/update_rtofs_ver

### LINKED ISSUE #545: Update RTOFS version to v2.4
Once RTOFS v2.4 is implemented...

- [x] Create release/evs.v1.0.11 branch with `rtofs_ver=v2.4` in run.ver
- [x] Create EVS.v1.0.11 tag 
- [x] Update develop with `rtofs_ver=v2.4` in run.ver
- [x] Update para with `rtofs_ver=v2.4` in run.ver

### PR DESCRIPTION
**Pull request by malloryprow**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

On 9/13/2024, RTOFS v2.4 was implemented. This updates run.ver for this version change. Closes #545.

## Developer Questions and Checklist
* Is this a high priorty PR? If so, why and is there a date it needs to be merged by?
> Slightly, RTOFS v2.4 was implemented a few days ago.

* Do you have any planned upcoming annual leave/PTO?
> On a half day of work/PTO on 9/16/2024.

* Are there any changes needed for when the jobs are supposed to run?
> No
  
- [x] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [x] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [x] References the feature branch for `HOMEevs` are removed from the code.
- [x] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [x] Jobs over 15 minutes in runtime have restart capability.
- [x] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [x] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [x] Code is using METplus wrappers structure and not calling MET executables directly.
- [x] Log is free of any ERRORs or WARNINGs.

## Testing Instructions

We could run the RTOFS prep job to make sure it is grabbing the version 2.4 data.

### CODE REVIEW

**Review by AliciaBentley-NOAA — APPROVED** [review]
I approve this PR, which updates RTOFS to version 2.4!

**Comment by PerryShafran-NOAA** [comment]
I will do a quick run of rtofs prep, per Mallory's suggestion.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Checked the output file and the script is indeed pulling in data from /lfs/h1/ops/prod/com/rtofs/v2.4.  I don't think I need to finish the code, I think I can just go ahead and approve.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
