### PR TITLE
Feature/cat2stdout ver2d nfcens

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
In this PR: 
1- The evs_ver variable was generated in deriver scripts.
2- Log files for each STEP were concatenated into stdout. 
After applying each change the scripts were tested and compared with emc.vpppg auth repository.  

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
prep driver script: /lfs/h2/emc/vpppg/noscrub/samira.ardani/EVS/dev/drivers/scripts/prep/nfcens/jevs_nfcens_wave_grid2obs_prep.sh
stats driver script: /lfs/h2/emc/vpppg/noscrub/samira.ardani/EVS/dev/drivers/scripts/stats/nfcens/jevs_nfcens_wave_grid2obs_stats.sh
plots driver script:
/lfs/h2/emc/vpppg/noscrub/samira.ardani/EVS/dev/drivers/scripts/plots/nfcens/jevs_nfcens_wave_grid2obs_plots.sh
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes ]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes ]**

- [ ] Please complete this pull request review by **[10/31/2023]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi @SamiraArdani-NOAA - I have begun testing of your PR.

**Comment by PerryShafran-NOAA** [comment]
Hi, @SamiraArdani-NOAA ,

The prep job is finished.

Please see the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr314test/EVS/dev/drivers/scripts/prep/nfcens
and the output directory here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/nfcens/wave.20231023/nfcens/grid2obs

I will move on to the stats now, pointing to the emc.vpppg archive.

Perry

**Comment by PerryShafran-NOAA** [comment]
The stats job is finished.  

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr314test/EVS/dev/drivers/scripts/stats/nfcens
The stats output is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/nfcens/*20231023*

I will also submit the plots job.

Perry

**Comment by PerryShafran-NOAA** [comment]
The plots job is finished.

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr314test/EVS/dev/drivers/scripts/plots/nfcens
and here are the plot tarballs:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/nfcens/wave.20231023

Perry

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA:
Thank you for working on this PR. I will check the .o files and the outputs, compare them with emc.vpppg and let you know shortly.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA @SamiraArdani-NOAA I have looked over this PR and see no issues! I approve this once you are both satisfied with the test results. Thanks!

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA @AliciaBentley-NOAA,
I checked the results. The outputs and the .o files look good.

**Comment by PerryShafran-NOAA** [comment]
Excellent, thanks for doing a quick look, and also for doing the sync fork.  I will do a quick code check and merge when done.

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Pull request merged**
