### PR TITLE
bugfix/ndbc_stations

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

This PR addresses item number 28 in [EVS v1.0 Issue](https://docs.google.com/document/d/1VYGABeEe2eXA1k5NFL5oavgMgiiTPyTKGWk-zWmsPdc/edit?pli=1):

1. Remove PYTHONPATH being set in parm/metplus_config/prep/rtofs/grid2obs/ASCII2NC_obsARGO.conf
2. Only use NDBC buoys which we have location data for rtofs AND global_det wave

- [ ] Describe testing already performed for this Pull Request:</br>
> I ran the GFS wave grid2obs stats jobs. I found no instances of "WARNING: NDBC station" in the log. The final output file from running the NDBC buoys through ascii2nc matched the parallel.
> I ran the RTOFS prep job. I found no instances of "WARNING: NDBC station" in the log. The final output file from running the NDBC buoys through ascii2nc matched the parallel. I found no instances of "PYTHONPATH is already set" in the log. The final output file from running ARGO through ascii2nc matched the parallel.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **12/29/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I ran the rtofs prep job late last Friday, but it was still running when my day ended.  But you can look at the results.

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr397test/EVS/dev/drivers/scripts/prep/rtofs
The output is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs 

I will now submit the wave job.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow For the rtofs checks above, all your rtofs checks pass.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The global_det wave stats is done.

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr397test/EVS/dev/drivers/scripts/stats/global_det
The output is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/____.20231225

I will take a moment to go through your suggested checks.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Unfortunately, I did see NDBC station warnings in the global_det wave stats job.

See /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr397test/EVS/dev/drivers/scripts/stats/global_det/jevs_global_det_wave_gfs_grid2obs_stats_00.o122283005

**Comment by malloryprow** [comment]
> @malloryprow Unfortunately, I did see NDBC station warnings in the global_det wave stats job.
> 
> See /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr397test/EVS/dev/drivers/scripts/stats/global_det/jevs_global_det_wave_gfs_grid2obs_stats_00.o122283005

That's my fault. The script ush/global_det/global_det_wave_prep_trim_ndbc_files.py runs in prep. I updated the testing instructions.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow OK, I think the issue is that I changed COMIN to emc.vpppg in the stats job.  Following instructions to not change COMIN.

**Comment by PerryShafran-NOAA** [comment]
OK, the global_det wave stats are done.

.o file:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr397test/EVS/dev/drivers/scripts/stats/global_det
stats: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/____.20231227

**Comment by malloryprow** [comment]
Looks good!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Everything all set for merge do you think?

**Comment by malloryprow** [comment]
Yup!

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Pull request merged**
