### PR TITLE
Bugfix/meso update cartopy

### PR DESCRIPTION
**Pull request by RoshanShrestha-NOAA**
Hardcoded cartopy paths removed, empty comout folders cleared.
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, @RoshanShrestha-NOAA .  Can you instruct me on the specific tests that you would want to be run that would be relevant for this change?

**Comment by PerryShafran-NOAA** [comment]
OK, I'm told that the cartopy change affects only spatial plots.  Thus, I will run the sref spatial plot job.

@RoshanShrestha-NOAA can you tell me if the jevs_mesoscale_precip_plots.sh contains spatial plots?  Do I need to run this?  If not, I will not run this.  

I think I would only need to test one job to see that the fix for removing empty folders is working as intended.  Which job would you like me to run?

**Comment by PerryShafran-NOAA** [comment]
OK, I am running the SREF spatial plot job and the mesoscale precip plot job.

**Comment by RoshanShrestha-NOAA** [comment]
> OK, I am running the SREF spatial plot job and the mesoscale precip plot job.

@PerryShafran-NOAA  Thank you. Yes, meso precip (for NAM/ RAP) should be tested.

**Comment by PerryShafran-NOAA** [comment]
@RoshanShrestha-NOAA I see you added something regarding sref cartopy.  Do I need to pull that in and re-run?  What was the nature of the change?

**Comment by RoshanShrestha-NOAA** [comment]
> OK, I am running the SREF spatial plot job and the mesoscale precip plot job.

@PerryShafran-NOAA I noticed SREF spatial plots failed as it was still referring to old cartopydatadir. Now it is fixed, please rerun the test.

**Comment by RoshanShrestha-NOAA** [comment]
> @RoshanShrestha-NOAA I see you added something regarding sref cartopy. Do I need to pull that in and re-run? What was the nature of the change?

I posted above about it before I saw this question.  This change fixes the failure of SREF spatial plot job. Please re-run the SREF precip spatial map test.

**Comment by PerryShafran-NOAA** [comment]
Thanks for being on the ball, checking that out, and putting in the fix so quickly!  

The re-run is submitted.

**Comment by PerryShafran-NOAA** [comment]
Looks like the fix prevented an error in the new SREF plot run.

See /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr352test/EVS/dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_precip_spatial_plots.o93384184
Plot tarball here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/mesoscale/atmos.20231114

The mesoscale precip plot job is still running.

**Comment by RoshanShrestha-NOAA** [comment]
> Looks like the fix prevented an error in the new SREF plot run.
> 
> See /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr352test/EVS/dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_precip_spatial_plots.o93384184 Plot tarball here: /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/mesoscale/atmos.20231114
> 
> The mesoscale precip plot job is still running.

Yes, the SREF spatial plots look good.

**Comment by RoshanShrestha-NOAA** [comment]
@PerryShafran-NOAA The mesoscale precip plot job is complete and all looks good.

**Comment by PerryShafran-NOAA** [comment]
Hi, @RoshanShrestha-NOAA , can you also check for empty directories that you had noted above in the PR description?  Would you have found empty directories in one of the two jobs that we just ran/checked?

**Comment by RoshanShrestha-NOAA** [comment]
> Hi, @RoshanShrestha-NOAA , can you also check for empty directories that you had noted above in the PR description? Would you have found empty directories in one of the two jobs that we just ran/checked?

Hi @PerryShafran-NOAA , I already checked the empty directories. There is non.

**Comment by PerryShafran-NOAA** [comment]
Also, @RoshanShrestha-NOAA ,we need you to add this bugfix into your codebase so it can be merged into the parallel.  Please take this file and put it in the ush/global_ens directory:

/lfs/h2/emc/vpppg/noscrub/emc.vpppg/EVS/ush/global_ens/global_ens_atmos_util.py

Thanks!

**Comment by PerryShafran-NOAA** [comment]
Also, check to see if your code needs a sync fork.  I think nothing new has been merged since your last sync.

**Comment by RoshanShrestha-NOAA** [comment]
> Also, @RoshanShrestha-NOAA ,we need you to add this bugfix into your codebase so it can be merged into the parallel. Please take this file and put it in the ush/global_ens directory:
> 
> /lfs/h2/emc/vpppg/noscrub/emc.vpppg/EVS/ush/global_ens/global_ens_atmos_util.py
> 
> Thanks!

Hi @PerryShafran-NOAA I checked diff between /lfs/h2/emc/vpppg/noscrub/emc.vpppg/EVS/ush/global_ens/global_ens_atmos_util.py and the ush/global_ens/global_ens_atmos_util.py in my bugfix branch (current PR). I don't see any difference other than a single space that doesn't change anything. Please check if you see any difference between the two files. Is there a another version that I should include?

**Comment by PerryShafran-NOAA** [comment]
@RoshanShrestha-NOAA That single space was actually important as the previous version was giving an "Indentation error" that was causing the global_ens prep job to fail.  Please copy that file as the change in the spacing was the fix for that file.

**Comment by RoshanShrestha-NOAA** [comment]
> @RoshanShrestha-NOAA That single space was actually important as the previous version was giving an "Indentation error" that was causing the global_ens prep job to fail. Please copy that file as the change in the spacing was the fix for that file.

OK.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code changes look good.

**Comment by PerryShafran-NOAA** [comment]
Thanks, @RoshanShrestha-NOAA !  Merging now.

**Pull request merged**
