### PR TITLE
feature/rtofs_final_ee2

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

1. Set evs_ver to 3 digit number and add evs_ver_2d in dev/drivers/scripts
2. Remove setting COMROOT and add setting COMOUT in dev/drivers/scripts
3. Set HOMEevs default ${PACKAGEROOT}/${NET}.${evs_ver} in J-Jobs
4. Remove exit 0 from plotting configs
5. Add err_chk statements
6. Use cpreq
7. Add more informative logging information
8. Use production date utility ndate
9. Add python interpreter at top of plotting scripts
10. Remove hard-coded WCOSS1 path
11. Remove cycle reference in time_util.py
12. Log were checked for _“error” “Error” “ERROR” “fail” “Fail” “FAIL” “Syntax” “argument expected” “No such file” “exceeded”_; no instances were found but "Error" which is associated with the job's error output path.

- [ ] Describe testing already performed for this Pull Request:</br>

> I ran the prep, stats, and plots. I compared to what was available in the emc.vpppg parallel and all matched.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

**Set-up**
> 1. Clone my fork and checkout branch feature/rtofs_final_ee2
> 2. cd sorc
> 3. ./build-fix-link.sh

**prep**
> 4. Run dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.sh

**stats**
> 5. Run dev/drivers/scripts/stats/rtofs/jevs_rtofs_argo_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_aviso_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_ndbc_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_osisaf_stats.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vppg/$NET/${evs_ver_2d}.

> Note: I haven't added dev/drivers/scripts/stats/rtofs/jevs_rtofs_smap_stats.sh and dev/drivers/scripts/stats/rtofs/jevs_rtofs_smos_stats.sh, and dev/drivers/scripts/stats/rtofs/jevs_rtofs_ghrsst_stats.sh as these data sources have been having problems in dcom recently. When it comes time to test, we can check to see if the files are in dcom for the VDATE that the testing will run for.

**plots**
> 6. Run dev/drivers/scripts/plots/rtofs/jevs_rtofs_argo_grid2obs_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_aviso_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_ghrsst_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_headline_grid2grid_last90days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_ndbc_grid2obs_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_osisaf_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_smap_grid2grid_last60days_plots.sh, and dev/drivers/scripts/plots/rtofs/jevs_rtofs_smos_grid2grid_last60days_plots.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/${evs_ver_2d}.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **11/17/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `feature/rtofs_final_ee2`

**Comment by ShelleyMelchior-NOAA** [comment]
rtofs prep is is complete.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/rtofs`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rtofs_prep.o107317963`

**Comment by ShelleyMelchior-NOAA** [comment]
stats is underway for ndbc, argo, aviso, and osi-saf.
Would it be worthwhile to still run the ghrsst, smap, and smos stats files to make sure they are properly handling the absent data?
UPDATE: I went ahead and ran them anyway!

COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/rtofs`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rtofs_*_stats.o10731*`

**Comment by ShelleyMelchior-NOAA** [comment]
plots processing has also been completed.
COMOUT=`/lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/rtofs`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rtofs_*_plots.o1073190*`

**Comment by malloryprow** [comment]
Reviewing now!

**Comment by malloryprow** [comment]
:heavy_check_mark: **prep, stats, and plots are all good!**

prep file count match the parallel, stats files match the parallel, and plots tar files match the parallel.

I also grep'ed the log file for the key words I mentioned in the opening comment and all is good.

Branch has also merged in latest develop commit.

GOOD TO GO!

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA @malloryprow I have looked over this PR this morning and think that it looks great! Approved for merge after Shelley's checks!

**Comment by ShelleyMelchior-NOAA** [comment]
Awesome! I will do the formal code review (which I have been doing along the way) and approve for merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All tests yielded expected results. This PR is approved for merge.

**Pull request merged**
