### PR TITLE
Bugfix/global ens 2series

### PR DESCRIPTION
**Pull request by ShelleyMelchior-NOAA**
## Pull Request Testing ##

This PR addresses item 34 on Wei's document.
There are lingering errors related to ECME stats not being available to be plotted. There are a number of variables, levels, or forecast leads where ECME does not have stats to be plotted. Defining the model list based on these limitations eliminates the WARNINGs.

- [ ] Describe testing already performed for this Pull Request:</br>

Only local changes have been made on dogwood by Shelley during cactus outage.
Steve has visually reviewed the changes on github.
Shelley will run the plots as user emc.vpppg upon submission of the PR.
### UPDATE
All changes have been tested and the offending WARNINGs for ECME have been removed. 
Please proceed w/ testing this PR to confirm the WARNINGs are removed.
tar files are different size than NCO para tar files; however, the expected graphics are all produced. We can watch this.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

The following plots drivers need to be run.
`jevs_global_ens_atmos_gefs_grid2grid_past31days_plots.sh`
`jevs_global_ens_atmos_gefs_grid2grid_past90days_plots.sh`
`jevs_global_ens_atmos_gefs_profile1_past31days_plots.sh`
`jevs_global_ens_atmos_gefs_profile1_past90days_plots.sh`
`jevs_global_ens_atmos_gefs_profile2_past31days_plots.sh`
`jevs_global_ens_atmos_gefs_profile2_past90days_plots.sh`
`jevs_global_ens_atmos_gefs_profile3_past31days_plots.sh`
`jevs_global_ens_atmos_gefs_profile3_past90days_plots.sh`
`jevs_global_ens_atmos_gefs_profile4_past31days_plots.sh`
`jevs_global_ens_atmos_gefs_profile4_past90days_plots.sh`
`jevs_global_ens_atmos_gefs_snowfall_past31days_plots.sh`
`jevs_global_ens_atmos_gefs_snowfall_past90days_plots.sh`

Check for successful completion of the tar file.
Check for no "WARNING: ECME data" messages in the log file.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Downloaded the code, and now running all the requested plot jobs.

**Comment by PerryShafran-NOAA** [comment]
I am submitting a new tests after pulling in the change from your latest commit.

**Comment by PerryShafran-NOAA** [comment]
OK, the plot jobs are completed.  

I still see WARNINGs for ECME data not being found in some of the output.  

Also - the tar files do not match what is found in the NCO para.  

All the .o files are here:  /lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr413test/EVS/dev/drivers/scripts/plots/global_ens 

The tarballs are here:  /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/global_ens/atmos.20240116

The tarballs for the NCO para are here:  /lfs/h1/ops/para/com/evs/v1.0/plots/global_ens/atmos.20240116

**Comment by PerryShafran-NOAA** [comment]
It seems that Marcel and Steve are still discussing further solutions to this issue in an email chain, so I guess stay tuned?  

@ShelleyMelchior-NOAA

**Comment by ShelleyMelchior-NOAA** [comment]
Correct -- PR testing is still premature.

**Comment by ShelleyMelchior-NOAA** [comment]
@PerryShafran-NOAA , you now have the 🟢 light! The PR description has been updated to indicate the PR is now legitimately ready for testing.

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA I am running the jobs on Dogwood under emc.vpppg in the pridev queue, since I do not believe that the data we need exists yet on Dogwood.  Stay tuned.

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA The jobs are complete on Dogwood.  

Please look at the .o files here:  /lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr413test/EVS/dev/drivers/scripts/plots/global_ens

I am still seeing ECME data WARNINGs in some of the most recent runs.  I did do a git pull before the run.  

Tarballs are here:  /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/global_ens/atmos.20240117
NCO para tarballs are here:  /lfs/h1/ops/para/com/evs/v1.0/plots/global_ens/atmos.20240117

Please note that tarballs are not the same size but it's close.

**Comment by ShelleyMelchior-NOAA** [comment]
I concur that Perry ran the latest code updates.
Perry's latest runs:
```
[dlogin06 /lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr413test/EVS/dev/drivers/scripts/plots/global_ens]$ lltr jevs_global_ens_*.o1258*
-rw-r--r-- 1 emc.vpppg vpppg  5563865 Jan 19 14:42 jevs_global_ens_atmos_gefs_grid2grid_past31days_plots.o125893368
-rw-r--r-- 1 emc.vpppg vpppg  5930329 Jan 19 14:45 jevs_global_ens_atmos_gefs_profile2_past31days_plots.o125893783
-rw-r--r-- 1 emc.vpppg vpppg  7295713 Jan 19 14:45 jevs_global_ens_atmos_gefs_snowfall_past31days_plots.o125893267
-rw-r--r-- 1 emc.vpppg vpppg  5869556 Jan 19 14:46 jevs_global_ens_atmos_gefs_grid2grid_past90days_plots.o125893389
-rw-r--r-- 1 emc.vpppg vpppg 11009323 Jan 19 14:46 jevs_global_ens_atmos_gefs_profile1_past31days_plots.o125893397
-rw-r--r-- 1 emc.vpppg vpppg  4975785 Jan 19 14:46 jevs_global_ens_atmos_gefs_profile4_past31days_plots.o125893873
-rw-r--r-- 1 emc.vpppg vpppg  9064328 Jan 19 14:48 jevs_global_ens_atmos_gefs_profile3_past31days_plots.o125893786
-rw-r--r-- 1 emc.vpppg vpppg  6236157 Jan 19 14:54 jevs_global_ens_atmos_gefs_profile2_past90days_plots.o125893785
-rw-r--r-- 1 emc.vpppg vpppg 11313763 Jan 19 14:57 jevs_global_ens_atmos_gefs_profile1_past90days_plots.o125893732
-rw-r--r-- 1 emc.vpppg vpppg  7604924 Jan 19 14:57 jevs_global_ens_atmos_gefs_snowfall_past90days_plots.o125893270
-rw-r--r-- 1 emc.vpppg vpppg  5285442 Jan 19 14:59 jevs_global_ens_atmos_gefs_profile4_past90days_plots.o125893938
-rw-r--r-- 1 emc.vpppg vpppg  9358977 Jan 19 15:01 jevs_global_ens_atmos_gefs_profile3_past90days_plots.o125893790
```
grid2obs 31 ✔️  90 ✔️ 
snowfall 31 ✔️  90 ✔️ 
profile1 31 ✔️  90 ✔️ 
profile2 31 ✔️  90 ✔️ 
profile3 31 ❗  90 ✔️  --> what is different about profile3 for 31 vs 90 past days? 🤔 
profile4 31 ✔️  90 ✔️ 

I have put the dogwood logfiles into `/dfs/read/emc/vpppg/shelley.melchior/logs-global_ens_plots` on cactus for review by Steve and Marcel.

**Comment by PerryShafran-NOAA** [comment]
Also if this needs to be run again, I can probably now do so on Cactus, the dev machine.  I believe I have all the stats data from Dogwood transferred over to Cactus.

**Comment by ShelleyMelchior-NOAA** [comment]
Perry, I think you have old code for profile3 past 31. See the setting for HOMEevs for the profile 3 past31 vs past90.
```
$ grep HOMEevs= jevs_global_ens_atmos_gefs_profile3_past*
jevs_global_ens_atmos_gefs_profile3_past31days_plots.o125893786:++ export HOMEevs=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/EVS
jevs_global_ens_atmos_gefs_profile3_past31days_plots.o125893786:++ HOMEevs=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/EVS
jevs_global_ens_atmos_gefs_profile3_past31days_plots.o125893786:+ HOMEevs=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/EVS
jevs_global_ens_atmos_gefs_profile3_past31days_plots.o125893786:export HOMEevs=/lfs/h2/emc/vpppg/noscrub/${USER}/EVS
jevs_global_ens_atmos_gefs_profile3_past90days_plots.o125893790:++ export HOMEevs=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr413test/EVS
jevs_global_ens_atmos_gefs_profile3_past90days_plots.o125893790:++ HOMEevs=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr413test/EVS
jevs_global_ens_atmos_gefs_profile3_past90days_plots.o125893790:+ HOMEevs=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr413test/EVS
jevs_global_ens_atmos_gefs_profile3_past90days_plots.o125893790:export HOMEevs=/lfs/h2/emc/vpppg/noscrub/${USER}/pr413test/EVS
```
Please re-run profile3 past 31 with HOMEevs set to `/lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr413test/EVS`

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA I just confirmed that.  I am re-running.

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA The job is complete:

/lfs/h2/emc/vpppg/noscrub/emc.vpppg/pr413test/EVS/dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_profile3_past31days_plots.o125919281

There are no WARNINGs in this .o file.

**Comment by ShelleyMelchior-NOAA** [comment]
I think this PR is ready for merge. 🚀

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA Did you do a sync fork?

**Comment by AliciaBentley-NOAA** [comment]
The changed files look good and the output looks good! This PR can be merged. Thanks, all!

**Comment by ShelleyMelchior-NOAA** [comment]
Thank you for the reminder ... sync'd!

**Review by PerryShafran-NOAA — APPROVED** [review]
Changes are as expected.  Ready to merge.

**Pull request merged**
