### PR TITLE
Feature/stats meso3

### PR DESCRIPTION
**Pull request by RoshanShrestha-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
In light of Perry's recent email message (subject: Changes needed to your filenames), you will need to update all of your nam and rap driver scripts in stats and plots to include "mesoscale".
For example, `jevs_nam_grid2obs_stats.sh` changes to `jevs_mesoscale_nam_grid2obs_stats.sh`.

You will also need to update the job card to include "mesoscale".
For example, `#PBS -N jevs_nam_grid2obs_stats_00` changes to `#PBS -N jevs_mesoscale_nam_grid2obs_stats_00`.

Could you also please do this for @malloryprow for precip and snowfall? This PR is a good opportunity to take care of that maintenance.

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @RoshanShrestha-NOAA , I went ahead and got started on testing g2o stats, pending the updates to the driver scripts as noted in the previous comment. Please review the results to be certain the stats files look as expected.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/mesoscale/`
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nam_grid2obs_stats_00.o7282315`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rap_grid2obs_stats_00.o72823097`

**Comment by RoshanShrestha-NOAA** [comment]
Hi @ShelleyMelchior-NOAA, the driver scripts are updated and some corrections applied. Could you please re-run the jobs. Thank you.

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @RoshanShrestha-NOAA , I have updated my clone of your feature branch and the re-run is underway. It has been running for almost 2 hours so far. You can feel free to monitor.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/mesoscale/`
log files:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_nam_grid2obs_stats_00.o72886644`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_grid2obs_stats_00.o72886642`

Also, there was just a PR merge. Please merge auth EVS develop into this feature branch. Thanks!

**Comment by RoshanShrestha-NOAA** [comment]
Thank you. 
I have merged to the latest auth EVS develop into this feature branch.

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks, @RoshanShrestha-NOAA ! I have completed the re-runs. Please review the output in the COMOUT and log files indicated in my previous comment and let me know how things look.

You will need to remove line 65 in
`dev/drivers/scripts/mesoscale/stats/jevs_mesoscale_nam_grid2obs_stats.sh` and
`dev/drivers/scripts/mesoscale/stats/jevs_mesoscale_rap_grid2obs_stats.sh`.
That line is no longer needed now that the `parm/metplus_config/machine.conf` file specifies:
`MET_BIN_DIR = {MET_INSTALL_DIR}/bin`.

I had the lines commented out in my re-run and I think everything worked OK.

**Comment by RoshanShrestha-NOAA** [comment]
Hi @ShelleyMelchior-NOAA , Your runs are similar to my results. I have added a few minor fixes in it. Would you like to rerun it once more? It's up to you. Thank you.

**Comment by ShelleyMelchior-NOAA** [comment]
Since you're still finding a few things here and there, sure, I will re-run again. I will submit and check it in a few hours and report back.

**Comment by ShelleyMelchior-NOAA** [comment]
HI @RoshanShrestha-NOAA  -- the re-run has completed. Please review.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/mesoscale`
log files:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_nam_grid2obs_stats_00.o72915654`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_grid2obs_stats_00.o72915656`

**Comment by RoshanShrestha-NOAA** [comment]
Hi @ShelleyMelchior-NOAA 

All looks good. Thank you.

**Comment by ShelleyMelchior-NOAA** [comment]
Great, @RoshanShrestha-NOAA  -- let's do one final merge of auth EVS develop into this feature branch to get your branch up to date. Then I can do the final code review and merge your PR.

**Comment by RoshanShrestha-NOAA** [comment]
I just synced fork with the latest auth EVS develop.

**Comment by ShelleyMelchior-NOAA** [comment]
Fantastic! I have been doing the code review as we went along. I will do the formal review and then approve this PR for merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All code changes are tested and approved.

**Comment by RoshanShrestha-NOAA** [comment]
Thankyou @ShelleyMelchior-NOAA

**Pull request merged**
