### PR TITLE
Feature/evsv2-nfcens_fnmoc_errors

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
## Pull Request Testing ##
During the test, it was observed that sometimes fnmoc_wave model data does not have the required HTSGW (significant wave height) wave field, which is required for EVS-NFCENS. This is caused to observe some error messages while running the stats step. This PR addresses this issue by applying some modifications in the prep step to prevent those error messages. This issue was fixed by excluding incomplete fnmoc_wave model data in the prep step so that those incomplete files are not copied to $COMOUT for the the stats analysis step. 

- [ ] Describe testing already performed for this Pull Request:</br>
The modified code has been running since 20240627 to ensure that there is no error messages in the new runs.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
1- To test this PR, you need to run the driver scripts for two steps (prep and stats). "prep" step is required to see the changes in size and number of required fnmoc_wave data to ensure that those incomplete files have been excluded. "stats" step is required to check if the .o files are free from those ERROR messages. It is expected that after the full test (10 days), the .o files will be free from those error messages. My evs/v2.0 directory includes 10 days of healthy prep data in case reviewers need to copy them in their own local for their test.   
2- Clone my fork in your local and checkout branch Feature/EVSv2-nfcens_fnmoc_errors.
3- ln -s to fix directory.
4- Run the driver script for prep step at: EVS/dev/drivers/scripts/prep/nfcens/*
5- Run the driver script for stats step at: EVS/dev/drivers/scripts/stats/nfcens/*
  
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes]**

- [ ] Please complete this pull request review by **[07/19/2024]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
@SamiraArdani-NOAA Can you please update run.ver so that the FNMOC version number is in alphabetical order and not at the bottom of the list of models? Thanks! 

https://github.com/NOAA-EMC/EVS/blob/develop/versions/run.ver#L68

CC @ShelleyMelchior-NOAA @PerryShafran-NOAA

**Comment by ShelleyMelchior-NOAA** [comment]
Hi Samira! I have cloned your fork and checked out branch `feature/EVSv2-nfcens_fnmoc_errors`. I will review your instructions and begin testing this afternoon.

**Comment by ShelleyMelchior-NOAA** [comment]
### prep
I ran prep for nfcens. Please review.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nfcens_wave_grid2obs_prep.o155323693`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v2.0/prep/nfcens`

### stats
I ran stats for nfcens. I used an earlier date, VDATE=20240707, because I used your healthy prep files as input, and `wave.20240708/` was not yet available. Please review.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nfcens_wave_grid2obs_stats.o155324942`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v2.0/stats/nfcens`

**Comment by SamiraArdani-NOAA** [comment]
@ShelleyMelchior-NOAA : 
"prep" works well. I see that the WARNING due to the incomplete file is shown in the .o file as we expected. Also, those incomplete files are excluded in $COMOUT (for example, the wave_2024070800.f012.grib2) which is what we want.
"stats" works well. I see no ERROR in the .o file which is good and was the purpose of this PR. Also, the stats outputs for nfcens part was compared with emc.vpppg and they were identical.

**Comment by ShelleyMelchior-NOAA** [comment]
Great! Thanks for the review.

I also ran another case of stats for VDATE=20240704. This looks back to prep files that are not healthy. Please review the output log file for the expected warnings.

logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nfcens_wave_grid2obs_stats.o155326755`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v2.0/stats/nfcens`

**Comment by SamiraArdani-NOAA** [comment]
@ShelleyMelchior-NOAA : Just adding to my previous comment that I compared your "stats" for "fnmoc" and "gefs" part with my own test results and they were identical which is good.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran one more case of stats b/c my test for VDATE=20240704 did not work as I intended.

This time I am using VDATE=20240708 pointing to Samira's healthy prep files.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nfcens_wave_grid2obs_stats.o155331406`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v2.0/stats/nfcens`

We can compare to the same run for the emc.vpppg parallel. The parallel does not yet have the code fix that this PR introduces.
logfile: `/lfs/h2/emc/ptmp/emc.vpppg/output/jevs_nfcens_wave_grid2obs_stats.o155327678`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v2.0/stats/nfcens`

**Comment by SamiraArdani-NOAA** [comment]
@ShelleyMelchior-NOAA: Thank you for testing this. I reviewed your test results. As expected, no ERROR was observed and the outputs were identical to emc.vpppg. Since the current emc.vpppg parallel does not include these current changes and today we had some unhealthy data in fnmoc_wave, observing the ERRORs in the . o file with emc.vpppg parallel were expected. This test can prove that this PR will fix the issue of error messages.

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks, Samira! I think this PR is ready for the formal code review.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
This PR is approved for merge.

**Pull request merged**
