### PR TITLE
Feature/subseasonal HGT and precip prep

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
This PR includes the following new items:
-500mb geopotential height stats and plots
-CCPA prep and retrieving GEFS and CFS model data every 6 hrs (instead of every 12) for precip prep
New variables have been tested/run on the command line almost daily.
Height graphics have been updating on the dev EVS rzdm site.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Checkout this feature new dev branch.
Make sure COMIN, COMOUT, HOMEevs, and FIXevs are set accordingly.
First, test the 500mb geopotential height stats job by running the following:
EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_cfs_grid2grid_stats.sh
EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.sh
Make sure to point to my prep data directory: /lfs/h2/emc/vpppg/noscrub/shannon.shields/EVS_Data/evs/v1.0/prep/subseasonal/
Once the stats are confirmed, run the height plots:
EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_31days.sh
EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_90days.sh
Make sure to point to my stats data directory (**this is important** or else the plots will show nothing):
/lfs/h2/emc/vpppg/noscrub/shannon.shields/evs_subseasonal_test/dev/com/evs/v1.0/stats/subseasonal/
Once this is confirmed, contact me for instructions on the prep step testing.
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>
End of the week if possible (April 5)
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA I have started work on your PR.  Please examine the latest .o files in this directory:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr463test/EVS/dev/drivers/scripts/stats/subseasonal

And the output is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/subseasonal, in the 20240414 directories.

Please take a look and let me know how they look.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA Sorry for the delay; I was making sure everything ran as it should. I have looked at the output files, DATA directories, and stat files for both GEFS and CFS. I can see the jobs successfully generated the subseasonal HGT stats.
Next, please test the height plots:
EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_31days.sh
EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_90days.sh
**Make sure to point to my stats data directory (or else the plots will show nothing):
/lfs/h2/emc/vpppg/noscrub/shannon.shields/evs_subseasonal_test/dev/com/evs/v1.0/stats/subseasonal/**

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Thanks so much!  I'll get those plot jobs up and running.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA The jobs are complete.

Please see the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr463test/EVS/dev/drivers/scripts/plots/subseasonal
and the output tarballs here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/subseasonal/atmos.20240414

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA The plot output looks fine except for something strange that I noticed for the 90-day plots .o file. jevs_subseasonal_grid2grid_pres_lvls_plots_90days.o142578229 says "ncpus 170.1 exceeded limit 120 (burst)". However, I know I have the correct number of jobs/tasks corresponding to nproc and ncpus. Sure enough, when I look at the DATA directory, jevs_subseasonal_grid2grid_pres_lvls_plots_90days.142578229.dbqs01, there are never more than 120 tasks/jobs. I just ran my own 90-day plot script and it ran fine; I did not see any exceeded warning. Hopefully this is just a random fluke due to WCOSS2 running a bit slow or something?

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA I can't say for sure, other than the fact that NCO wouldn't accept a job with this warning even though it's not really considered a job failure because it finishes and writes output.  But this has been an issue with ncpu exceedance in the past, and I had to spend considerable amounts of time fixing it.   

One way it was fixed was to do one of the following:

1) Split it up into 2 nodes (60 tasks per node instead of 120)
2) Change mpiexec command to:  mpiexec -np 120 --ppn --cpu-bind verbose, depth cfp

I suggest trying the 2nd option.  I made that fix in numerous locations and it seemed to work, and was Wei's preferred option I think.  I will try that and see what happens.

**Comment by ShannonShields-NOAA** [comment]
Ok, thank you. However this is concerning news as I have never seen this exceedance issue on my end before and I have been running these HGT plots in my own dev space for a while. I have of course seen the "mem limit exceeded" with my GEFS jobs, but never this "ncpus exceeded limit".

**Comment by PerryShafran-NOAA** [comment]
Go back and check that.  It may not happen all the time, but it is entirely possible you missed it if it happened to not occur on a day you were not looking.  This is easily fixable and not a big deal.  

BTW, I just ran with the depth option replacing the core option, and there was no burst error:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr463test/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_90days.o142583461

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA That is fantastic news!! Thank you for fixing this. So to be clear, you changed "mpiexec -np ${nnp} -ppn ${nproc} --cpu-bind verbose,**core** cfp" to "mpiexec -np ${nnp} -ppn ${nproc} --cpu-bind verbose,**depth** cfp" in EVS/scripts/plots/subseasonal/exevs_subseasonal_grid2grid_plots.sh?

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA That is correct, that should fix the issue so it doesn't ever come back up.  If it does, we may need to talk about spreading the cpus across more than 1 node.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA As you can see in the commit, I have made that change.
Next and last for this PR is to test CCPA prep and retrieving GEFS and CFS model data every 6 hrs (instead of every 12) for precip prep.
Before running the following, please make sure to set HOMEevs accordingly.
Then run:
EVS/dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_cfs_prep.sh
EVS/dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_gefs_prep.sh
EVS/dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_obs_prep.sh
GEFS prep will take about an hour or so to run.

**Comment by AliciaBentley-NOAA** [comment]
Thanks for working on this, @ShannonShields-NOAA and @PerryShafran-NOAA!

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA I have run the prep jobs.  The GEFS job is still running, but the obs and CFS jobs are finished.  

See the .o files here:   /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr463test/EVS/dev/drivers/scripts/prep/subseasonal
And the output is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/subseasonal/atmos.20240415

**Comment by ShannonShields-NOAA** [comment]
For some reason, I am having trouble logging onto WCOSS2 right now despite logging in an hour earlier. Ugh. Will keep trying as I really want to get this PR merged today.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA The connection went down for everyone for about 15 minutes, but I can get back on now.  Try again.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA Yes, after about 10 tries, I could finally log back in. Ok, so all of the prep jobs completed successfully! They correctly generated the 24hr CCPA prep file and the model data every 6 hrs. No ERRORs and no exceedances. This PR should be set to merge; however, do keep in mind this PR is set with the prod versions of MET and METplus (11.0.2 and 5.0.1). We were just saying in our meeting yesterday that the develop branch was not updated with run.ver yet so this should be good to go.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Yes, but it's also true that this needs to be tested with the beta versions as well to be sure that they all work when we upgrade to those versions.  All jobs destined for EVSv2 needs to be tested with the beta versions.  So before we run this, I will now test all jobs with the new versions and see if they work with them as well.  Please stay tuned. 

@AliciaBentley-NOAA @ShelleyMelchior-NOAA for awareness

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA Is there anything that has completed with the new versions that I can check?

**Comment by PerryShafran-NOAA** [comment]
Yes, you can check in these directories for the HGT stats:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr463test/EVS/dev/drivers/scripts/stats/subseasonal

For the stats output:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/subseasonal

**Comment by PerryShafran-NOAA** [comment]
The plot jobs:

.o files here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr463test/EVS/dev/drivers/scripts/plots/subseasonal
plot tarballs here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr463test/EVS/dev/drivers/scripts/plots/subseasonal

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA In all your checks, please be sure that the .o files are using the beta versions of MET and METplus and the ve/evs version 2.

Thanks!

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA and @AliciaBentley-NOAA  I am seeing something strange and inconsistent with the stat output, specifically in the 2m temperature config files:
"WARNING: Both GRID_STAT_CLIMO_MEAN_FIELD and GRID_STAT_CLIMO_MEAN_VAR<n>_* variables are set. Using values set in GRID_STAT_CLIMO_MEAN_VAR<n>_* variables" However, this makes no sense to me as I am not setting GRID_STAT_CLIMO_MEAN_FIELD at all. 
For example, in GridStat_fcstSUBSEASONAL_obsECMWF_climoERA5_Days6_10NetCDF.conf, I do not have GRID_STAT_CLIMO_MEAN_FIELD listed at all. Instead, I need to specify:
GRID_STAT_CLIMO_MEAN_VAR1_NAME = TMP
GRID_STAT_CLIMO_MEAN_VAR1_LEVELS = Z2
GRID_STAT_CLIMO_MEAN_VAR1_OPTIONS = set_attr_name = "TMP"; set_attr_level = "Z2";
For some reason this yields the WARNING. Yet in GridStat_fcstSUBSEASONAL_obsGFS_climoERA5_Days6_10NetCDF.conf, I have GRID_STAT_CLIMO_MEAN_FIELD =  (it is equal to blank), and this does not yield the WARNING. The WARNING shows up only in the ECMWF 2mtemp config files. The only conclusion I can make is that this WARNING is triggered if GRID_STAT_CLIMO_MEAN_FIELD = is not listed? This seems like a bug to me; was this mentioned at all in the original beta3 testing?

**Comment by ShannonShields-NOAA** [comment]
This seems somewhat similar to:
WARNING: Both *_STAT_CLIMO_MEAN_INPUT_TEMPLATE and *_STAT_CLIMO_MEAN_FILE_NAME are set. Using value set in *_STAT_CLIMO_MEAN_FILE_NAME
I saw this in my beta3 testing and fixed it prior to submitting this PR. This turned out to be a MET bug and so I wonder if the above is the same...

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA @PerryShafran-NOAA Please see this note from the 4/1/24 METplus Users Telecon:

From Steve: WARNING: Both POINT_STAT_CLIMO_MEAN_INPUT_TEMPLATE and POINT_STAT_CLIMO_MEAN_FILE_NAME are set. Using value set in POINT_STAT_CLIMO_MEAN_FILE_NAME (/lfs/h2/emc/vpppg/noscrub/emc.vpppg/EVS/fix/climos/atmos/era5/mean_{valid?fmt=%m%d}). The FILE_NAME Option is new and folds in the INPUT_DIRECTORY and INPUT_TEMPLATE. Do we simply combine INPUT_DIRECTORY with INPUT_TEMPLATE under FILE_NAME to eliminate the deprecation WARNING.

From DTC: This is a problem in the logic of METplus, calling the same subroutine twice. **And expect George to fix this in METplus-6.0.0-beta4.**

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Did you see this in the current emc.vpppg tests, which is using the betas?  Should have showed up there as well.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Looks like this WARNING is indeed also there in the current emc.vpppg beta3 tests.  

But, if the issue is to be corrected in the upcoming beta4 release from the DTC, I would guess there is nothing to be done relating to this for this PR.  

I also notice that there are still stats files.  I am guessing that these stats are not complete in this case?  

@AliciaBentley-NOAA @ShelleyMelchior-NOAA

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA OK, we decided that this being a DTC issue, we won't hold this PR up until we get a beta4 or later release installed on WCOSS2.  If the HGT is OK for this in the stats file, we can just move on to the ccpa precip.  

Which I have done using the betas.  Please check here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr463test/EVS/dev/drivers/scripts/prep/subseasonal

And here for the prep output:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/subseasonal/atmos.20240415 

 Even if HGT isn't OK, we can still move on because we know it works with the current production versions, and we'll have to monitor the emc.vpppg run when it gets upgraded to the beta4 or later version.  

@AliciaBentley-NOAA @ShelleyMelchior-NOAA for awareness.

**Comment by ShannonShields-NOAA** [comment]
Ok, sounds good @PerryShafran-NOAA . I will continue checking the rest of the output.
However, I think this WARNING might have somehow been missed in our original testing? We all noticed the WARNING about the INPUT_TEMPLATE, but this is about the **CLIMO_FIELD**:
WARNING: Both GRID_STAT_CLIMO_MEAN_**FIELD** and GRID_STAT_CLIMO_MEAN_**VAR*** variables are set. Using values set in GRID_STAT_CLIMO_MEAN_VAR* variables
I will check with DTC to see if they are aware of this issue.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA I did see the same error in the output on the emc.vpppg runs.  It may have been missed during original testing.  

I think that this is a similar warning that we have seen in other components such as global_ens.  See Alicia's comment above.  DTC is aware and is fixing it in their next beta.

**Comment by ShannonShields-NOAA** [comment]
Ok @PerryShafran-NOAA , the stats and plots are all good, ignoring the stat WARNING for now. Please proceed with the prep jobs.

**Comment by ShannonShields-NOAA** [comment]
Oh and I confirmed that the WARNING has no effect on the final stat output files; all is in order.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA I posted the info for the prep runs a few posts up.  Please scroll up and check.

**Comment by ShannonShields-NOAA** [comment]
Apologies, it got lost in the thread of responses. I see the model data is fine, but now there is some issue with KeyError: 'METPLUS_PATH' in jevs_subseasonal_obs_prep.o142678483. This environmental variable worked perfectly fine before; I don't understand how a version change is now causing this to fail.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA OK, this is weird, and this one is NOT in the emc.vpppg output for the obs prep.  I'm totally befuddled.  Let me run this again just in case it's some weird blip.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA Somehow when you changed the modulefile for prep, the module loading of met and metplus was removed. This is why it cannot find the METPLUS_PATH. Not sure how this happened, but in /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr463test/EVS/dev/modulefiles/subseasonal/subseasonal_prep.sh, you need:
module load met/${met_ver}
module load metplus/${metplus_ver}

**Comment by PerryShafran-NOAA** [comment]
Interesting - let me look into that.  Things seem to look OK in emc.vpppg, so something may not be correct in the changing of the modulefile.  Let me check.

**Comment by ShannonShields-NOAA** [comment]
The module loading of met and metplus is new to this PR for the prep modulefile and will not be seen in the current emc para.

**Comment by PerryShafran-NOAA** [comment]
OH!  That's it then.  Let me add that in and then try again.

**Comment by PerryShafran-NOAA** [comment]
OK, I have a new run in there.  Apologies for losing the met/metplus loads in changing the environment to the beta environment.  I didn't realize you had made those changes.

Please check in the various directories one more time.

**Comment by ShannonShields-NOAA** [comment]
Just to be clear, this feature branch (new_dev) had the loading correctly since the start of this PR. https://github.com/ShannonShields-NOAA/EVS/blob/feature/subseasonal_new_dev/dev/modulefiles/subseasonal/subseasonal_prep.sh
The CCPA prep is all good now! This PR can finally be merged!

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA I also just confirmed that this feature branch is indeed up-to-date. Thank you so much for your assistance with this PR testing!

**Comment by PerryShafran-NOAA** [comment]
Yes, your PR was correct.  I didn't realize that you had made changes in the modulefile to add in met/metplus loads, so I just copied in the subseasonal directory from emc.vpppg to replace the existing modulefiles.  That's *my* bad.  

When we merge this into the parallel, we'll have to make sure that the modulefile is correct for the beta versions.  It should be fine to use the ones that I just used for the final test.  

I'll make a check at the code changes.  In the meantime, if your code requires a sync fork, please do so.  I don't think it does though.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected, but we'll need to watch for a correction in the beta4 version.  Approved for merge.

**Pull request merged**
