### PR TITLE
Bugfix/subseasonal missing obs loophole fix

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
Testing has been done on the command line.
This PR includes the following:
Fixed grid2obs stats loophole error with missing obs data by requiring 100% prepbufr file exist check (this is valid due to /prod/com obs data).
Fixed grid2grid stats loophole error with missing obs data by matching forecast hour model check with obs check. If all obs and model data exist for that specific forecast hour, the job runs; otherwise, the job will not run for that forecast hour.
Added a few more WARNING statements for missing data situations.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Checkout feature branch and adjust paths as necessary (make sure FIXevs link is in place).
Copy all prep data (atmos.20231014 to atmos.20231118) from /lfs/h2/emc/vpppg/noscrub/shannon.shields/EVS_Data/evs/v1.0/prep/subseasonal.
Then remove atmos.20231112 to simulate a missing data case.
Then run the following for testing:
dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.sh
dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2obs_stats.sh
The grid2grid job should run around the missing data while the grid2obs will not run past GenEnsProd step due to 100% file check for PB2NC.
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes (but grid2obs will throw cpreq error at end because it expects stat file to be there; which it normally should)
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>
ASAP
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
YESSSSSS! Thank you, @ShannonShields-NOAA ! I will get started on this PR very soon.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran a control of g2o and g2g stats w/ no missing prep data
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/subseasonal`
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_subseasonal_gefs_grid2obs_stats.o93760072`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_subseasonal_gefs_grid2grid_stats.o93760069`

**Comment by ShelleyMelchior-NOAA** [comment]
It turns out the original cp of prep data to my local COMIN was incomplete. I have re-started the cp of prep data. In the mean time, I am re-running the control and using emc.vpppg prep files for the gefs g2o and g2g stats processing.
```
93761917.cbqs01                shelley.melchi* dev             jevs_subseason*   242075    1    59   70gb 01:00 R 00:03
93761966.cbqs01                shelley.melchi* dev             jevs_subseason*   220913    1     8   60gb 00:40 R 00:03
```
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_subseasonal_gefs_grid2obs_stats.o93761966`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_subseasonal_gefs_grid2grid_stats.o93761917`

**Comment by ShannonShields-NOAA** [comment]
@ShelleyMelchior-NOAA I went through all of the output and can confirm that all ran as it should with the control runs of no missing data.

**Comment by ShannonShields-NOAA** [comment]
The copying of the prep data is complete. Please follow the exact instructions below:
Remove atmos.20231112 to simulate a missing data case (and please remove this date so I can explicitly check for the missing hours).
Then run the following for testing:
dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.sh
dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2obs_stats.sh

**Comment by ShelleyMelchior-NOAA** [comment]
atmos.20231112 was removed from COMIN.
The two subseasonal gefs grid2* stats jobs are underway.
```
93766204.cbqs01                shelley.melchi* dev             jevs_subseason*    24744    1     8   60gb 00:40 R 00:00
93766206.cbqs01                shelley.melchi* dev             jevs_subseason*   259284    1    59   70gb 01:00 R 00:00
```
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_subseasonal_gefs_grid2grid_stats.o93766206`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_subseasonal_gefs_grid2obs_stats.o93766204`

**Comment by ShannonShields-NOAA** [comment]
@ShelleyMelchior-NOAA I have checked the test runs and confirmed everything ran as it was programmed to.
For grid2grid, there are no errors and the jobs ran around the missing data as you can see in the example below:
export CORRECT_LEAD_SEQ=336,348,**360,372**,384,396,408,420,432,444,456,468,480,492,504
vs
export fhr_list="**336,348,384**,396,408,420,432,444,456,468,480,492,504"
Now for grid2obs there is one FATAL ERROR at the very end of the log file related to cpreq. This is due to a final stat file not being generated (but we would expect this stat file to exist in a normal ops situation). However, this is correct behavior because if this situation/error happens, it means there is missing prepbufr data in /prod/com. This would indicate a higher-level error that is not the fault of EVS. God forbid this should ever happen, we would want NCO to see this error.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The changes are good. Tests yield expected results. This PR is approved for merge.

**Pull request merged**
