### PR TITLE
Feature/aqm plots

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

Ran several tests of the new settings and all plots were created.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run EVS/ecf/scripts/aqm/plots/jevs_aqm_plots.ecf.  You may use the existing stats data in either /lfs/h2/emc/vpppg/noscrub/$USER/evs/v1.0/stats/aqm/aqm.YYYYMMDD to test, where $USER can be either perry.shafran or emc.vpppg.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP.  

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@PerryShafran-NOAA  -- I have cloned your fork and checked out `feature/aqm_plots`.

**Comment by ShelleyMelchior-NOAA** [comment]
The run completed for `jevs_aqm_plots.ecf`. Please see output.
log: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_plots_00.o66151298`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0`

I cp'd the tar file to emcrzdm and untarred it.
https://ftp.emc.ncep.noaa.gov/users/smelchior/EVS/aqm/

**Comment by PerryShafran-NOAA** [comment]
Something is not right.  When you grep for "NO PLOT" in the .o file, you should not see it anywhere, but in your case I see lots of them.  And the results of the specific plot jobs are in stmp and are probably not there.  I did not see that the last time I ran the plots.  Something is amiss, so let me do another run and see what's going on.

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
I am re-running w/ a more current date now that the emc.vpppg para is more stable after the prod switch. I will report results soon.

**Comment by ShelleyMelchior-NOAA** [comment]
The run completed for `jevs_aqm_plots.ecf`. Please see output.
log: `/lfs/h2/emc/vpppg/noscrub/shelley.melchior/jevs_aqm_grid2obs_plots_00.o66380854`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0`

Unfortunately I still see a lot of "NO PLOT FOR" strings in my .o file.

**Comment by ShelleyMelchior-NOAA** [comment]
Re-running using perry.shafran $USER archive for COMIN instead of emc.vpppg.

**Comment by ShelleyMelchior-NOAA** [comment]
The re-run using the perry.shafran archive is complete. The output log file looks better.
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_plots_00.o66383570`
The output tarfile is here:
`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/aqm/atmos.20230623`
`-rw-r--r-- 1 shelley.melchior vpppg 455086080 Jun 26 15:38 evs.plots.aqm.atmos.grid2obs.last31days.v20230623.tar`

**Comment by PerryShafran-NOAA** [comment]
The tar file is exactly the same size as mine, and the png files within the tar file are also exactly the same as mine.  There are no NO PLOT messages in the .o file.  I think that everything looks fine!

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
Excellent. I will complete the final code review next.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All changes look good and are as expected.

**Pull request merged**
