### PR TITLE
Feature/ee2 update wafs

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
In this PR, the pressure levels of observational data have been modified in EVS-WAFS scripts based on the WAFS recent upgrades.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
To run for stats STEP: dev/drivers/scripts/stats/wafs/jevs_wafs_atmos_stats.sh
To run for plots STEP: dev/drivers/scripts/plots/wafs/jevs_wafs_atmos_plots.sh

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
The NCO SPA assigned for the WAFS upgrade is Xiaoxue Wang. She has provided the path on WCOSS2 (dev and prod).

> Hi Shelley,
> The parallel WAFS data is in /lfs/h1/ops/para/com/gfs/v16.3/gfs.YYYYMMDD/CC/atmos. However, I skip today's 06z run. You should find other cycle's data.
> 
> Thanks,
> Xiaoxue
>

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA I am working on your PR.  To do that, I had to point to the correct location of the WAFS files that were denoted by Xiaoxue above.

You will need to add the current line to your driver script:

export COMINgfs=/lfs/h1/ops/para/com/gfs/${gfs_ver}

I already added that line in and am testing your PR.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : Just to confirm: do I need to add it in "stats" driver script?

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA yes, please add it to the stats driver script.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA Please take a look at the output:

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr343test/EVS/dev/drivers/scripts/stats/wafs
The output stats files are here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/wafs/wafs.____20231108

**Comment by AliciaBentley-NOAA** [comment]
Thank you, @SamiraArdani-NOAA! Subseasonal was recently merged into develop, if you could bring that into this PR too!

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : I see some discrepancies in the stats outputs size with those in emc.vpppg for WAFS.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA There are a lot of missing para wafs files.  I think that we are going to wait until Monday when they have populated more of the parallel with files that we can use for verification.

@ShelleyMelchior-NOAA @AliciaBentley-NOAA @YaliMao-NOAA for awareness.

**Comment by AliciaBentley-NOAA** [comment]
It's also worth noting that I didn't get ANY missing file emails, despite all of the missing WAFS file messages in the output that Perry saw. @SamiraArdani-NOAA , if you could possibly test the missing files and get those emails to work, that would be excellent. You can add your name to the maillist, if it helps you debug!

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA I am going to give this another test today to see if we have more files from the parallel.

**Comment by PerryShafran-NOAA** [comment]
There are lots of missing data errors.  I'm looking at the directory /lfs/h1/ops/para/com/gfs/v16.3 on Cactus, and it appears that the most recent date for the WAFS parallel is gfs.20231109.  It didn't run over the weekend at all.  I'm not sure how to proceed.

@YaliMao-NOAA is there another source for WAFS parallel data?  

@SamiraArdani-NOAA @AliciaBentley-NOAA @ShelleyMelchior-NOAA

**Comment by YaliMao-NOAA** [comment]
I am asking NCO to mirror the parallel run data to dev machine. It should be in effect at next cycle.

**Comment by PerryShafran-NOAA** [comment]
@YaliMao-NOAA thanks!  We also informed Xiaoxue and they are working the mirror.  Turns out that the mirror was turned off over the weekend.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA @YaliMao-NOAA Looks like the wafs parallel is finally up to date on Cactus, so I'm giving this run another try to see how well it works.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA the run last night continued to produce errors because it was after 00Z and thus the most recent files did not exist yet.  I will try this now and see if we can get an error-free run.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA @YaliMao-NOAA One issue that has been revealed is that METplus produces errors because files are missing.  This shouldn't happen because since we are checking for the existence of model files, we need to ensure that if a file is missing, METplus doesn't run.  

This is because we have fixed forecast hours set for each model cycle.  What we need is a fix to ensure that if a file is missing for a certain forecast hour, that forecast hour is removed from the list of forecast hours so METplus doesn't run and throw out errors.  Can we add this fix?  Our code handoff isn't for a few weeks, so we have time to get a fix into the code.  

Adding @AliciaBentley-NOAA and @ShelleyMelchior-NOAA for awareness.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA @YaliMao-NOAA I am continuing to see ERRORs in the METplus due to missing data, but this time, no Missing email was generated as there had been previously.  I'm going to need Samira and/or Yali to take a look and see if we can ensure that every time there is a missing file, that we get a Missing email sent and also that forecast hour removed so that METplus doesn't run on that particular file.  

Please look at this file:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr343test/EVS/dev/drivers/scripts/stats/wafs/jevs_wafs_stats.o93178127

I believe that the stmp output DATA directory was not deleted and can be preserved.

**Comment by malloryprow** [comment]
@SamiraArdani-NOAA @YaliMao-NOAA I added file checking in global_ens recently. I can pass along what I did for that, if you need help. Let me know!

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA @YaliMao-NOAA : Yesterday, I was working on the emails from WAFS when there is a missing file. I browsed through the /lfs/h1/ops/para/com/gfs/v16.3/gfs.20231112/00/atmos and could not find this type of file: gfs.t03z.gcip.f00.grib2  @YaliMao-NOAA : Would you please check lines 71-87 of  /lfs/h2/emc/vpppg/noscrub/samira.ardani/EVS/ush/wafs/evs_wafs_atmos_stats_preparedata.sh and let me know if we need to fix or modify that part of the code?

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA I will be making one last run on this; hopefully we are now far enough from the bad data so that there won't be any errors. @YaliMao-NOAA should help you check to see that the stats were done correctly.  If all looks good, we will merge this PR, then Yali will work on a new PR to make the fixes.  

Adding @AliciaBentley-NOAA and @ShelleyMelchior-NOAA for awareness.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : OK, Thanks. I ran the scripts today and saw the errors.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA Interestingly, I saw no errors for the run that I just did.  Maybe you changed the PDY?

Anyway, please take a look at the following output:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr343test/EVS/dev/drivers/scripts/stats/wafs/jevs_wafs_stats.o93290802

And the output stats files are here:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/wafs/wafs.20231114

I'm guessing that they would be different than the emc.vpppg run since we're using different thresholds?  Please check with Yali to help you validate these numbers.  @YaliMao-NOAA

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : The .o file looks good. I agree with you about the discrepancies with emc.vpppg. My morning run was similar to yours, I thought I should not see those "warnings". No "errors" as you said.

**Comment by PerryShafran-NOAA** [comment]
Right, and the discrepancy in this case should indicate that it's working!  It's running on the parallel wafs NCO is running, which outputs different data than emc.vpppg does (which is still running production wafs).

@YaliMao-NOAA can you check the outputs to see that the numbers of the stats files look reasonable for the para wafs?

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA @YaliMao-NOAA : Number of stat outputs are the same as emc.vpppg (156 files).

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA @YaliMao-NOAA I think that's good enough to merge at this point.  Yali will be submitting a PR with the fixes.  For now, we are good to merge.  First, a quick code review.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code looks good; ready to merge.

**Comment by YaliMao-NOAA** [comment]
Sorry for being late to check the data. I am not sure why u/v/t stat files got affected by the pressure level update. I am investigating.

**Comment by PerryShafran-NOAA** [comment]
Hi, @YaliMao-NOAA - thanks for checking!  If there are further issues, you would need to submit them in the new PR that you will be working on.  This PR is merged and we can't un-merge it.

**Comment by YaliMao-NOAA** [comment]
I think I found the issue. Alicia told me you found a METplus error message because a couple of data were missing. Do you still see the errors? Or have a run case saved? Thank you.

**Comment by PerryShafran-NOAA** [comment]
The errors are no longer there because the runs finally caught up with the wafs parallel mirror.  Previous dates had not been fully or properly mirrored by NCO.  But the issues that there were errors in the METplus runs is what needs to be fixed.  

You can go to this directory and see any of the .o runs other than the most recent:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr343test/EVS/dev/drivers/scripts/stats/wafs

**Comment by YaliMao-NOAA** [comment]
Yes, I think the errors in METplus run are the ones Alicia is concerned, though one type of error in METplus run was fixed by my last PR #322.
From what Alicia described today, if a forecast data file is missing, we are going not only to issue email warnings, but also to modify the forecast hour list to avoid METplus error, right?

**Pull request merged**
