### PR TITLE
Remove icing potential from wafs, and update code to use modulefiles to load modules

### PR DESCRIPTION
**Pull request by YaliMao-NOAA**
## Pull Request Testing ##

- [x ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ x] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ x] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ x] Review the source issue metadata (required labels, projects, and milestone).
- [ x] Complete the PR description above.
- [ x] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ x]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ x]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [x ]  Check to see that the output directory structure is followed
- [ x]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi @YaliMao-NOAA - I am starting to work on this PR, so stay tuned.

Thanks!

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, @YaliMao-NOAA .

All runs are complete.

stats output:/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr150test/EVS/dev/drivers/scripts/wafs/stats
plots output: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr150test/EVS/dev/drivers/scripts/wafs/plots

The stats directory:/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/wafs/wafs.20230706
The plots directory: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/wafs/atmos.20230706

Please validate all the runs.

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, @YaliMao-NOAA ,

Please make sure you validate the runs, now that Dogwood is back up to see them.  

Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
Hi Perry,
Yes, all the log files and outputs look good to me. The runtime of stat files is within 15 minutes.
Thank you!
Yali

**Comment by PerryShafran-NOAA** [comment]
Excellent.  So now all is good, and the icing potential is removed (no icing potential stats file), and no plots for icing potential.

Let me check out the code for the review and if it is good, I will go ahead and merge.

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
