### PR TITLE
Feature/s2s CFS Prep File Fix

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
The CFS prep files have been fixed (the pgbf and flxf files are now kept separate due to different grids in each file). This fix has been confirmed in test runs by checking the files and using plot_data_plane to review grid output. 
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Run the following ecf script:
EVS/ecf/subseasonal/prep/jevs_subseasonal_prep.ecf
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>
5 business days or as soon as possible
*Since the "effects" of the corrected files won't be fully seen in the stats or plots until there is 35 days of corrected files, it is imperative that this fix is implemented into the EVS parallel ASAP.*
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have picked up this PR. I submitted a job for `jevs_subseasonal_prep.ecf`.

Output data files are on dogwood:
`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/subseasonal/atmos.20230412`

logfile for reference is: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_subseasonal_prep_00.o63268196`

**Comment by ShannonShields-NOAA** [comment]
@ShelleyMelchior-NOAA I have thoroughly checked the output files (especially for CFS) in your atmos.20230412 directory and everything is running correctly (all files exist). The flxf files (which have the format of cfs.ens01.t00z.f* and contain most of the variables needed for the subseasonal component) are separated from the pgbf files (which have the format of cfs.pgbf.ens01.t00z.f* and contain the pressure-level variables). This PR is set to be merged.

**Comment by ShelleyMelchior-NOAA** [comment]
@ShannonShields-NOAA , wonderful!
Before I merge this PR, can you tell me which flies changed for the prep fix? This PR contains a lot of modified and new plotting scripts. Would you like me to test those, too? Typically a PR only contains the changes related to the fix or feature that is being addressed.
https://github.com/NOAA-EMC/EVS/pull/98/files

**Comment by ShannonShields-NOAA** [comment]
Yes, the following have changed for the CFS prep file fix:
https://github.com/ShannonShields-NOAA/EVS/blob/feature/s2s/ush/subseasonal/get_cfs_subseasonal_data_files_prep.py
https://github.com/ShannonShields-NOAA/EVS/blob/feature/s2s/ush/subseasonal/subseasonal_util.py
I realize I should probably close this feature branch after this merge and create a new feature branch detailing the 2m temp anomalies script edits.

**Comment by ShelleyMelchior-NOAA** [comment]
Yes, please use a new feature branch for your development work for 2m temp anomalies. There are a number of changes that are going to be merged with the merge of this PR that are not related to the CFS prep fix. Your new feature branch could be named along the lines of `feature/s2s2mTempAnom`

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The two impacted files for this PR have been reviewed and tested.
`ush/subseasonal/get_cfs_subseasonal_data_files_prep.py`
`ush/subseasonal/subseasonal_util.py`

**Pull request merged**
