### PR TITLE
Bugfix/update subseasonal code structure

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
Testing for prep, stats, and plots has been done on the command line.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Please test the following for each step:
dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_cfs_prep.sh
dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.sh (Make sure you have sufficient data of 35 days)
dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_31days.sh
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>
Before Oct. 13
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA Thank you for submitting this PR! This looks absolutely great so far! Quick question: Can you please point me to a script where you reference one of the subseasonal parm files? I want to make sure that the paths to your parm files have been updated as well. Thanks!

**Comment by ShannonShields-NOAA** [comment]
@AliciaBentley-NOAA Yes, of course. So I am using a metplus_command function in my ush/util.py script to point to all my parm/metplus_config files. Please see https://github.com/ShannonShields-NOAA/EVS/blob/feature/subseasonal_structure_change/ush/subseasonal/subseasonal_util.py#L50
This function is called in my create_job_scripts.py ush scripts.

**Comment by ShannonShields-NOAA** [comment]
Here is an example of that in one of the scripts I am referring to:
https://github.com/ShannonShields-NOAA/EVS/blob/feature/subseasonal_structure_change/ush/subseasonal/subseasonal_stats_grid2grid_create_job_scripts.py#L470

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA Excellent! Thanks! And this line still works because you updated the _conf_file_ definition in [ush/subseasonal/subseasonal_util.py](https://github.com/NOAA-EMC/EVS/pull/287/files#diff-0a0c45958e9510df7c3df4c19a304d8de644b05b9a555fea864bc266f98b74d9), which is imported and used on the same line in [ush/subseasonal/subseasonal_stats_grid2grid_create_job_scripts.py](https://github.com/ShannonShields-NOAA/EVS/blob/feature/subseasonal_structure_change/ush/subseasonal/subseasonal_stats_grid2grid_create_job_scripts.py#L470), right?

```
    conf_file = os.path.join(os.environ['PARMevs'], 'metplus_config',
                             os.environ['STEP'],
                             os.environ['COMPONENT'],
                             os.environ['VERIF_CASE'],
                             conf_file_name)
```

If so, we can make sure that other developers update that too! I imagine that people could forget to update something small like that!

**Comment by ShannonShields-NOAA** [comment]
That is correct @AliciaBentley-NOAA . & there are numerous ush scripts that use this. I did copy this convention from Mallory's global_det though, so it would depend on how others are calling the parm/metplus_config files.

**Comment by ShannonShields-NOAA** [comment]
@AliciaBentley-NOAA and @PerryShafran-NOAA As you can see in my latest commit, I fixed the COMIN and COMROOT structure in dev/drivers/scripts/plots/subseasonal. Luckily it was an easy fix; set as the following:
export COMROOT=/lfs/h2/emc/ptmp/$USER
export COMIN=/lfs/h2/emc/vpppg/noscrub/$USER/$NET/$evs_ver

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA I also realized why the grid-to-obs plots did not run today. Please make sure that in your crontab for your cronjob that you are setting jevs_subseasonal_grid2obs_**prepbufr**_plots_*days.sh for dev/drivers/scripts/.

**Comment by ShannonShields-NOAA** [comment]
Hang on, that didn't post right. It should look like (with prepbufr lowercase):
jevs_subseasonal_grid2obs_prepbufr_plots_31days.sh
jevs_subseasonal_grid2obs_prepbufr_plots_90days.sh

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA Thank you for making those changes! They look good to me! Plots will go to the right place now!

I suspect that you are right about the emc.vpppg crontab needs to be updated so that your subseasonal prepbufr scripts have all lowercase letters:
```
jevs_subseasonal_grid2obs_prepbufr_plots_31days.sh
jevs_subseasonal_grid2obs_prepbufr_plots_90days.sh
```

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA @ShannonShields-NOAA You are correct; that was a change from previous that I didn't realize.  I just changed them to all lower case, so they should run today.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA several PRs were just merged; please sync fork and I will start work on this PR.

**Comment by PerryShafran-NOAA** [comment]
OK, the prep step is underway!

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA Ok, the CFS prep step finished successfully! Next, please test:
dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.sh (Make sure you have sufficient data of 35 days linked to your directory)

**Comment by ShannonShields-NOAA** [comment]
**But don't link today's date! (20231004) Otherwise, that will cause the same link issues as we experienced before.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA You are fast!  I was just about to tell you that the prep step was done.

**Comment by PerryShafran-NOAA** [comment]
Ah, I see.  I link to emc.vpppg, and atmos.20231004 hasn't been run yet.  But it is 14Z now, so maybe I'll wait a bit to run the stats job.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Looks like now the atmos.20231004 is now available in emc.vpppg.  Are we good to run the stats job as is now?

**Comment by ShannonShields-NOAA** [comment]
Oh oops, sorry, yes, ignore my link comment; that only applies to the prep step. Now that we are testing stats, yes, you are right in that we need data up to 20231004. Yep, I see that we should have all the data we need now, so you can go ahead with the stats step.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA I'm seeing a strange/random error in the output that I don't understand:
"mkdir: cannot create directory â /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/subseasonal/gefs.20231004â : Permission denied"
& then later it is saying:
"PermissionError: [Errno 13] Permission denied: '/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/subseasonal/atmos.20231004'"
Besides the fact that it doesn't make sense that you can't write to your own space, it actually did create the directories so I'm not sure what the problem is...
shannon.shields@clogin02: subseasonal:$ls -lath  atmos.20231004                
total 12K
drwxr-sr-x 3 perry.shafran vpppg 4.0K Oct  6 14:17 .
drwxr-sr-x 9 perry.shafran vpppg 4.0K Oct  6 14:17 ..
drwxr-sr-x 3 perry.shafran vpppg 4.0K Oct  6 14:17 gefs

**Comment by PerryShafran-NOAA** [comment]
The reason is that I had linked stats to emc.vpppg to prepare for the plots run, and didn't unlink it back to prepare for the stats job.  

In fact, you'll note that I noticed this and ran again  and that job seems to be complete.  I often catch these errors and re-run; thus best to check the output after I have informed you that output is ready to see.  

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr287test/EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.o83676075

Output here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/subseasonal/gefs.20231004

**Comment by ShannonShields-NOAA** [comment]
I also have not changed anything in the stats scripts; the only thing that has changed for this PR is the structure, but that is not the COMOUT structure so this doesn't make any sense (and I have not seen it before). It seems totally random. Can you try deleting those COMOUT atmos.20231004 and gefs.20231004 directories (to start from scratch) and re-running?

**Comment by ShannonShields-NOAA** [comment]
Ah, gotcha, sorry about that false alarm. I try to be proactive and monitor the test job as it is running. I will check that rerun.

**Comment by PerryShafran-NOAA** [comment]
Point is, it's a *me* thing and not a *you* thing in this case.  It was my error and I fixed it.  Many errors you see is because I forgot to link the fix directory or that I had a linked directory to elsewhere that I can't write to.  

I appreciate you being proactive!  That's a good thing, but it often causes folks to jump the gun.  I often check the output before I inform people it's ready; thus errors are often caught by me and I re-run.  If it's an error that I can't resolve; then I go to the developer and ask them to take a look.

**Comment by ShannonShields-NOAA** [comment]
Yes, sounds good; thank you for explaining that and I will wait then to check the plots job (which can now be run since all is good with the stats test).

**Comment by ShannonShields-NOAA** [comment]
@AliciaBentley-NOAA @PerryShafran-NOAA @ShelleyMelchior-NOAA In the Slack channel, Mallory mentioned changing the COMIN name for dcom data from something like COMINecmwf to DCOMINecmwf. Is it ok if I make this change here for this PR while it is still open?

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA We are going to need to make some minor changes to COMIN definitions before code delivery to we don't mess things up for NCO (who isn't used to a verification system like EVS, only forecast models). You don't need to make those changes in this PR. Let's get this code structure PR in cleanly and we'll do the COMIN changes in a small PR after this. It'll be easier for you and Perry to troubleshoot that way! Thanks!

@PerryShafran-NOAA @ShelleyMelchior-NOAA

**Comment by ShannonShields-NOAA** [comment]
Ok, got it @AliciaBentley-NOAA . Thanks!

**Comment by PerryShafran-NOAA** [comment]
Agreed with @AliciaBentley-NOAA 's comment.  We'll evaluate the structure here, and then we'll be adding other things to be addressed in subsequent PRs.  The COMINs and COMOUTs have certainly been a thorn in my side (and everyone's side), so we hope to get it all ironed out real soon.

**Comment by ShannonShields-NOAA** [comment]
Sounds good. Yes, I have lost track of how many times I have gone through my dev/drivers and changed COMIN and COMOUT.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Get ready to go through it some more!  

OK, did you say stats checked out?  Wanted to be sure in case I missed it.

**Comment by ShannonShields-NOAA** [comment]
Yes, sorry, the stats job was successful with no errors. We can continue to the last test for dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_31days.sh.

**Comment by PerryShafran-NOAA** [comment]
The plots job is done.  

See /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr287test/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_31days.o83680948

The plot tarball is here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/subseasonal/atmos.20231004

**Comment by ShannonShields-NOAA** [comment]
Yes, everything looks good and we have confirmed that the plots will now go under the ptmp directory. Yay! This should be good to merge after your code review.

**Comment by PerryShafran-NOAA** [comment]
Most excellent!  I'll take a quick look-see.

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by PerryShafran-NOAA** [comment]
Approved for merge.

**Pull request merged**
