### PR TITLE
Bugfix/regional rev3

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

This PR addresses issues 66, 67, 69, and 72 noted in the Google Doc titled "EVS v1.0 issues".  Information about the cause and fix of each:

* 66 - TCDC, MLCAPE, CAPEsfc, and HPBL plots were made at valid hours when only sparse point observations are available.  These are ~15 obs spread across PacificNW, PacificSW, and GreatLakes.  Therefore, at these valid hours,  only these subregions are verified, and no statistics are available for any other subregion. _Fix:_ Removed TCDC, MLCAPE, CAPEsfc, and HPBL when valid times are 03Z, 09Z, 15Z, or 21Z; also removed MLCAPE, CAPEsfc, and HPBL when valid times are 06Z or 18Z.
* 67 - A portion of the href spatial maps plotting code checks for stat files in the DATA directory and attempts to compress them.  However this represents inherited code and is irrelevant for href spatial maps plotting.  Therefore, stat files are not found and a warning is printed.  _Fix:_ Commented out the irrelevant block of code.
* 69 - Stats are not made for Alaska, Puerto Rico, and Hawaii at certain init times, and for Puerto Rico and Hawaii with certain variables.  Therefore, depending on the region, plots are not made for some valid hour/lead hour combos and for some variables. _Fix:_ Defined a list of domains in graphics requests depending on the forecast lead hours and variables requested.
* 72 - A misleading WARNING message is printed when a dbf file (used to make SPC Outlook mask files) contains no SPC Outlook information.  This may be expected on a day when no outlook is issued.  The warning indicates unhelpfully that there is a "bad dbf file". _Fix:_ Change "WARNING" to "NOTE", and indicate that the occurrence is expected when no outlooks were issued for the specified day and time.

The affected jobs were tested and ran successfully.

This PR also addresses the following issues:
* Change HREF log messages from different processes to print to different files, which will make debugging easier.

---
- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

### (1) Set up jobs 
•	symlink the EVS_fix directory locally as "fix"
•	In all driver scripts, point all exports of "HOMEevs" to your EVS test directory
•	In all stats and plots driver scripts, change COMIN to the parallel directory (`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`)

### (2) Test Jobs
Use the following to submit ...

- ... jevs_cam_href_precip_spatial_plots: `qsub –v vhr=00,VDATE=20240123,INITDATE=20240123` 
- ... all other jobs: `qsub –v vhr=00 `

From your EVS testing directory, the following scripts should be run using the setup in step (1):
```
dev/drivers/scripts/prep/cam/jevs_cam_severe_prep.sh
```
```
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ctc_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_precip_spatial_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_profile_past31days_plots.sh
```

_[Total: 1 prep job; 4 plots jobs]_

### (3) Review
- I'll check for red flags:
```
check="FATAL\|WARNING\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|empty\|failed\|unexpected\|exceeded"
grep "$check" $outfile
```
- I'll also verify that the corresponding issues in the EVSv1.0 issue doc no longer exist

---
- [x] Has the code been checked to ensure that no errors occur during the execution? **YES**

---
- [x] Do these updates/additions include sufficient testing updates? **YES**

---
- [x] Please complete this pull request review by **ASAP**.</br>

---
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/regional_rev3`.

**Comment by ShelleyMelchior-NOAA** [comment]
I have kicked off the 5 jobs for your review. The logfiles reside in: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/`
`jevs_cam_severe_prep.o114296907`
`jevs_cam_href_grid2obs_ecnt_past31days_plots.o114296949`
`jevs_cam_href_precip_spatial_plots.o114296963`
`jevs_cam_href_profile_past31days_plots.o114296927`
`jevs_cam_href_grid2obs_ctc_past31days_plots.o114296947`

**Comment by MarcelCaron-NOAA** [comment]
✔️ jevs_cam_severe_prep 
✔️ jevs_cam_href_grid2obs_ecnt_past31days_plots
✔️ jevs_cam_href_precip_spatial_plots
✔️ jevs_cam_href_profile_past31days_plots
✔️ jevs_cam_href_grid2obs_ctc_past31days_plots

Job output are comparable to the parallel.  No errors.  Warnings flagged in the EVSv1.0 Issues doc are resolved.  All remaining warnings are expected. 

👍 Looks good to me.

**Comment by ShelleyMelchior-NOAA** [comment]
Thank you, Marcel! I have checked the log files, too, against the items in Wei's document. I agree things look OK. 

@PerryShafran-NOAA , can you take a moment to look closely at Marcel's code changes for a sanity check? Then I will merge this PR.

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA @MarcelCaron-NOAA Code changes seem fine to me.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yield expected results. This PR is approved for merge.

**Pull request merged**
