### PR TITLE
EVS v1.0.10: bugfix/global_ens_wave_plots_si

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

NCO had a failure in para (v1.0.10) on 8/2/2024 in evs_global_ens_wave_grid2obs_plot. It came from the scatter index forecast mean plots where all value were over 200. There had been additions to ignore values greater than 200, which resulted in an empty array in this case and cause the jobs to fail.

- [ ] Describe testing already performed for this Pull Request:</br>

> NCO ran with these changes on the failed job and it ran successfully. 

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **No**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **8/12/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Review by AliciaBentley-NOAA — APPROVED** [review]
I have reviewed the two changes made in this PR and think that they look good! I approve this PR to be merge once it's tested by either @PerryShafran-NOAA or @ShelleyMelchior-NOAA next week! Thanks, @malloryprow!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I am running your PR now.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The job is complete.  

Please see the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr508test/EVS/dev/drivers/scripts/plots/global_ens

And the plot tarballs are here: /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_ens/wave.20240804

**Comment by malloryprow** [comment]
👍 Log is good and tar files match the para output.

I included the same fix for nfcens here, though it hasn't failed NCO wants this fix it seems across everything using this line. Can you pull in the nfcens changes and then run that plot job pointing to the para stats for COMIN?

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Running the nfcens plot job.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The job is finished.

See the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr508test/EVS/dev/drivers/scripts/plots/nfcens

The plot tarballs are here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/nfcens/wave.20240804

**Comment by malloryprow** [comment]
Everything is good with the nfcens plots too!

**Comment by PerryShafran-NOAA** [comment]
OK, great!  Now to do a quick code review and then merge.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
