### PR TITLE
Bugfix/cam fixes 4

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

> Please include a summary of the changes and the related GitHub issue(s). Please also include relevant motivation and context.

- _Bugfix:_ Commands on job cards that copy restart data to COMOUT were placed incorrectly outside of METplus loops. _Outcome_: All needed restart data are copied to COMOUT in jobs with for loops.
- _Bugfix:_ Some PCPCombine output data were not being copied to restart.  When runs were interrupted and then restarted, the restart runs would fail, lacking the needed files.  _Outcome_: All needed restart data are copied to COMOUT.
- _Enhancement_: Forced x-axis tick labels on fhrmean plots to integer values 
- _Enhancement_: Removed PointStat processing of prepbufr subsets that are not already processed in PB2NC.

## Developer Questions and Checklist
* Is this a high priority PR? If so, why and is there a date it needs to be merged by?

No
* Do you have any planned upcoming annual leave/PTO?

No
* Are there any changes needed for when the jobs are supposed to run?

No
  
- [x] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [x] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [x] References the feature branch for `HOMEevs` are removed from the code.
- [x] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [x] Jobs over 15 minutes in runtime have restart capability.
- [x] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [x] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [x] Code is using METplus wrappers structure and not calling MET executables directly.
- [x] Log is free of any ERRORs or WARNINGs.

## Testing Instructions

> Please include testing instructions for the PR assignee. Include all relevant input datasets needed to run the tests.

#### (1) Set up jobs

- symlink the EVS_fix directory locally as "fix"
- In each driver script, edit the following environment variables:
**HOMEevs** - set to your test EVS directory
**COMIN** - set to `/lfs/h2/emc/vpppg/noscrub/emc.vpppg/${NET}/$evs_ver_2d`
**COMOUT** - set to your test output directory
**SENDMAIL** - (_optional_) set to `"NO"`
**DATAROOT** - (_optional_) set to your test DATAROOT directory

#### (2) Running jobs

I recommend testing the following jobs:
```
jevs_cam_namnest_grid2obs_stats
jevs_cam_hireswarw_precip_stats
jevs_cam_hireswarw_snowfall_stats
```
```
jevs_cam_headline_plots
```
[Total: 0 prep jobs; 3 stats jobs; 1 plots job]

- The _precip stats_ driver script can be submitted using `qsub -v vhr=21,VDATE=$(date -d "-3 days" +"%Y%m%d") $driver`
- All other driver scripts can be submitted using `qsub -v vhr=00 $driver`
- All jobs can be submitted at any time

#### (3) Testing jobs

For each stats job, please run ...
- **a full test**:  Run the job normally, to completion.  Developer can save a copy of the output stats file elsewhere (`$COMOUT/atmos.${VDATE}/${MODELNAME}/${VERIF_CASE}/gather_small/evs*stat`)
- **a restart test**:  Run the same job again, to completion.

For the plots job, only run a full test.

#### (4) Checking jobs
- Log files should be checked by the developer for the following keywords:
```
check="FATAL\|WARNING\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|failed\|unexpected\|exceeded"
grep "$check" $logfile
```

- Also full and restart output stats files should be compared (they should match).

### CODE REVIEW

**Comment by malloryprow** [comment]
Do we need to do a full test and then restart test? I see the description mentions restart data.

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow Good question; yes let's do that, for each of the 3 stats jobs if that's okay.  It would make it easier to just compare the full and restart output stats files.

[updated the PR test instruction]

**Comment by malloryprow** [comment]
### plots

Figured we can knock out the plots job first

### 1. jevs_cam_headline_plots (vhr=00)
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/plots/cam/jevs_cam_headline_plots.o208467983
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_headline_plots.208467983.dbqs01
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/evs/v2.0/plots/cam

**Comment by MarcelCaron-NOAA** [comment]
✔️ **jevs_cam_headline_plots** completed successfully, output look normal, no issues on fhrmean plots.

👍 No other concerns from me about **plots**.

**Comment by malloryprow** [comment]
### stat - full run

COMOUT is /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/evs/v2.0/stats/cam.

### 1. jevs_cam_namnest_grid2obs_stats
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_namnest_grid2obs_stats.o208471970
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_namnest_grid2obs_stats.208471970.dbqs01

### 2. jevs_cam_hireswarw_precip_stats
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.o208471946
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hireswarw_precip_stats.208471946.dbqs01

### 3. jevs_cam_hireswarw_snowfall_stats
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_snowfall_stats.o208471977
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hireswarw_snowfall_stats.208471977.dbqs01

**Comment by MarcelCaron-NOAA** [comment]
#### Full Runs

The following completed cleanly and output files look normal:
✔️ jevs_cam_hireswarw_precip_stats
✔️ jevs_cam_hireswarw_snowfall_stats

I've already copied the output stats files from these runs, so feel free to rerun them for restart!

Still running:
⏳ jevs_cam_namnest_grid2obs_stats

**Comment by MarcelCaron-NOAA** [comment]
The following completed cleanly and output looks normal:
✔️ **jevs_cam_namnest_grid2obs_stats**

👍 That wraps up the **full** runs for **stats**

**Comment by malloryprow** [comment]
### stat - restart run

COMOUT is /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/evs/v2.0/stats/cam.

### 1. jevs_cam_namnest_grid2obs_stats (vhr=00, interrupted run with walltime of 1 hour)
**Interrupted Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_namnest_grid2obs_stats.o208717323
**Interrupted DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_namnest_grid2obs_stats.208717323.dbqs01
**Restart Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_namnest_grid2obs_stats.o208720773
**Restart DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_namnest_grid2obs_stats.208720773.dbqs01

### 2.  jevs_cam_hireswarw_precip_stats (vhr=21, VDATE=20241206, interrupted run with walltime of 10 min)
**Interrupted Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.o208717310
**Interrupted DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hireswarw_precip_stats.208717310.dbqs01
**Restart Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.o208717947
**Restart DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hireswarw_precip_stats.208717947.dbqs01

### 3. jevs_cam_hireswarw_snowfall_stats (vhr=00, interrupted run with walltime of 10 min)
**Interrupted Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_snowfall_stats.o208717314
**Interrupted DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hireswarw_snowfall_stats.208717314.dbqs01
**Restart Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_snowfall_stats.o208717952
**Restart DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hireswarw_snowfall_stats.208717952.dbqs01

**Comment by MarcelCaron-NOAA** [comment]
❌ @malloryprow All restart jobs failed to produce any output... I'm checking to see what went wrong now.

**Comment by malloryprow** [comment]
Oh no, okay! Let me know if anything looks wrong in my testing set up.

**Comment by MarcelCaron-NOAA** [comment]
Set up is good!  But there is a bug.  The MPMD fix added working directories, but the code is still trying to copy to restart from the main directory (which is partially or completely empty when the job is interrupted).  The recent push should fix that and things should work now!

**Comment by malloryprow** [comment]
Just kicked off the restart run for the namnes_grid2obs job. Logs are in /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam. I moved the old COMOUT to /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/evs/v2.0/stats/cam/test1, so COMOUT for these tests is /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/evs/v2.0/stats/cam.

Sorry for the lack of details on this. I'm about to head to a meeting and then I'm done for the day. I wanted to try to get this test done before Dogwood goes down.

**Comment by MarcelCaron-NOAA** [comment]
Thanks @malloryprow I'll keep an eye on it and update the thread (for tomorrow)

**Comment by malloryprow** [comment]
@MarcelCaron-NOAA I'm listing restart times vs. the times in the parallel from yesterday

### jevs_cam_hireswarw_precip_stats
**Parallel:** 24:48
**Restart Test:** 15 min (interrupted)/02:14 (restart)

### jevs_cam_hireswarw_snowfall_stats
**Parallel:** 23:20
**Restart Test:** 16:00  (interrupted)/17:31 (restart)

### jevs_cam_namnest_grid2obs
**Parallel:** 02:08:43
**Restart Test:** 01:00:24 (interrupted)/02:06:48 (restart)

The precip and grid2obs timing doesn't look quite right.

The restart logs also have some errors in them.

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow Sorry I was having trouble finding the restart vs. the interrupted runs yesterday.  Do you mean precip and snowfall don't look quite right?  Looks like the following completed cleanly (no issues in the restart run) and the output file looks normal (EDIT: runtime seems too long as described above):
❓  jevs_cam_namnest_grid2obs_stats

The following were missing needed input files during the restart run, suggesting maybe the restart files were incomplete:
❌ jevs_cam_hireswarw_precip_stats
❌ jevs_cam_hireswarw_snowfall_stats

I'll update with some tested fixes.  Fortunately these remaining two are the shorter jobs.

**Comment by malloryprow** [comment]
For jevs_cam_namnest_grid2obs, I don't think the restart is working correctly, though the final outputs are fine. The full run in the parallel took 02:08:43. For our testing, the interrupted run ran for about 1 hour before. Its restart run took 02:06:48. This tells me the restart isn't working as it should as the restart run took just as long as the full run, even though we had about an hour of run time before it.

**Comment by MarcelCaron-NOAA** [comment]
Ah I understand, I read that too quickly.  Yes the timing is off.  I'll look into all three and get back to this thread, hopefully later today.

**Comment by MarcelCaron-NOAA** [comment]
_Update_:  I found two bugs related to restart.  Looks like they were already in the parallel, so it's good we are testing restart again now and clearing them out.  They affected the **precip** and **snowfall** jobs.  I'm testing a fix for both bugs now and _will push the fix after the test is successful_.

As for the **grid2obs** job, I'm not finding any issues with restart yet;  it appears the restart run worked as expected.  I am testing with a restart on a full run to rule out that either the staging processes dominate the runtime or that the full runtime differs from the parallel.  _I'll update this thread again after these tests are done_.

**Comment by malloryprow** [comment]
Sounds good! Thank you!

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow The following jobs can be retested (interrupted and restart runs) when you get a chance:
- **jevs_cam_hireswarw_precip_stats**
- **jevs_cam_hireswarw_snowfall_stats**


Still working on the grid2obs job ...

**Comment by malloryprow** [comment]
### stat - restart run

COMOUT is /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/evs/v2.0/stats/cam.

### 1.  jevs_cam_hireswarw_precip_stats (vhr=21, VDATE=20241207, interrupted run with walltime of 10 min)
**Interrupted Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.o208834892
**Interrupted DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hireswarw_precip_stats.208834892.dbqs01
**Restart Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.o208835818
**Restart DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hireswarw_precip_stats.208835818.dbqs01

### 2. jevs_cam_hireswarw_snowfall_stats (vhr=00, interrupted run with walltime of 10 min)
**Interrupted Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_snowfall_stats.o208834954
**Interrupted DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hireswarw_snowfall_stats.208834954.dbqs01
**Restart Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_snowfall_stats.o208835875
**Restart DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hireswarw_snowfall_stats.208835875.dbqs01

**Comment by MarcelCaron-NOAA** [comment]
Ugh apologies I forgot to check for "Error", which reveals a typo that affected the precip job.  Can you rerun the following?
**jevs_cam_hireswarw_precip_stats**

The grid2obs job and now snowfall job are otherwise successful, but the issue remains that the restart jobs take about as long to run as the parallel.  I'm testing restart on interrupted runs (rather than full runs) myself to see if I'm getting the same thing ...

**Comment by malloryprow** [comment]
### 1. jevs_cam_hireswarw_precip_stats (vhr=21, VDATE=20241208)
**Interrupted Log File**: /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.o208901226
**Interrupted DATA**: /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hireswarw_precip_stats.208901226.dbqs01
**Restart Log File**: /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.o208901849
**Restart DATA**: /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hireswarw_precip_stats.208901849.dbqs01
**COMOUT**: /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/evs/v2.0/stats/cam

**Comment by malloryprow** [comment]
I can try rerunning the grid2obs restart verification. It was late in the day and I was rushing to get the restart job submitted on time before I left. I could have made a mistake causing a full run instead of a restart run.

**Comment by MarcelCaron-NOAA** [comment]
No, I think the set up for that job was correct.  I confirmed in my own restart runs last night that for snowfall and grid2obs the restart runs do take the same amount of time to run as the parallel.

I'm doing more digging today and hopefully we'll have a reason/fix for all three.

**Comment by MarcelCaron-NOAA** [comment]
### Okay here's what I gathered:
1. For jobs run to completion, then again with restart data, the restart runs take substantially less time.
2. For interrupted jobs, restart runtimes ≈ full runtimes, regardless of interruption timing.

##### Other notes:
- Completed processes don't repeat in the restart runs.  Restart data are used, as expected. 

### What I think is happening:
(e.g., snowfall)
- "generate" processes (e.g., GridStat) take 96% of the runtime (~23 minutes; "reformat" and "gather" are each <1 minute)
- All "generate" processes run concurrently (4 total).  So the longest process determines the total runtime.
- **I think what is happening is**:  say three of the four "generate" processes (the shorter three) complete before the job is interrupted.  On a rerun, these processes no longer run, only the one interrupted process runs.  This process, which takes the full 23 minutes to complete, starts over from the beginning.  Therefore on the restart run, the "generate" processes still take the same amount of time to run.
- For grid2obs (254 "generate" processes), a single process takes nearly the full runtime.  

### Suggested fix:
- Break longer METplus processes into several smaller processes (e.g., _for precip/snowfall_: verify a single neighborhood size rather than a list; _for grid2obs_: verify a single pressure level rather than a list)

**I think this fix is beyond the scope of the current PR.  If you agree, I suggest adding the 'Suggested fix' above to the "Fixes and Additions" document for EVSv2.0.**

Any feedback is appreciated!  

CC: @malloryprow, @AndrewBenjamin-NOAA

**Comment by malloryprow** [comment]
Ah, I see. Thanks for the explanation Marcel! Were you able to put it on the Fixes and Additions? I'm not sure you have edit access.

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow No I can only suggest on that doc.  But I see it's been added, thanks!

**Comment by MarcelCaron-NOAA** [comment]
Other than what was described above, the restart runs for the following jobs worked as expected:
✔️ jevs_cam_hireswarw_snowfall_stats
✔️ jevs_cam_namnest_grid2obs_stats

The following needs a minor fix:
❌ jevs_cam_hireswarw_precip_stats

I pushed the fix, which I tested successfully myself with interrupted jobs.  Can we do that one more time here to confirm?

**Comment by malloryprow** [comment]
### 1. jevs_cam_hireswarw_precip_stats (vhr=21, VDATE=20241209)
**Interrupted Log File**: /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.o208993761
**Interrupted DATA**: /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hireswarw_precip_stats.208993761.dbqs01
Restart Log File: /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.o208994658
**Restart DATA**: /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hireswarw_precip_stats.208994658.dbqs01
**COMOUT**: /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr615/evs/v2.0/stats/cam

**Comment by MarcelCaron-NOAA** [comment]
✔️ **jevs_cam_hireswarw_precip_stats** restart run completed cleanly, output looks normal, and restart processes worked as expected.

👍 No other concerns from me about any of the restart runs.

**Review by malloryprow — APPROVED** [review]
Changes are good and testing successful in the scope of this PR!

Thank you @MarcelCaron-NOAA!

**Comment by malloryprow** [comment]
@AndrewBenjamin-NOAA Ready for your review and approval when you get a chance

**Review by AndrewBenjamin-NOAA — APPROVED** [review]
I have reviewed the files and approve the changes to this PR, and the proposed fixes for restart for grid2obs, precip, and snow will be in a later PR.

**Pull request merged**
