### PR TITLE
Bugfix/cam ee2 edits round2

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

All jobs were run as described in this PR, but untested changes have been made since.

### This bugfix addresses the following for the cam component:
- Fix or catch the following common error messages found in output logs: "too many arguments", "command not found", "mv: cannot stat", "No such file", and "Quitting due to missing data"
- Substantially reduce the number of empty directories created in COMOUT
- Fix radar stats forecast files iteration to only include available cycles
- Fix radar stats METplus configuration, which doesn't work in the ecflow environment

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

**Note:** fewer jobs were affected and need to be tested in this PR compared to recent cam PRs.

Same process as in the most recent cam PR:
### (1) Set up jobs 
•	symlink the EVS_fix directory locally as "fix"
•	In all driver scripts, point all exports of "HOMEevs" to your EVS test directory
•	In all driver scripts, change COMIN to the parallel directory (`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`)
•	Optional: In all stats drivers scripts, change "maillist" to point to your email address
### (2) Test Jobs
Use the following …
•	…to submit stats/precip: `qsub –v vhr=19,VDATE=$(date -d "-3 days" +"%Y%m%d")`
•	…to submit everything else: `qsub –v vhr=00 `
(_Note change to "vhr" in qsub commands_)

From your EVS testing directory, the following scripts should be run using the set up in step (1):
```
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_snowfall_stats.sh
```
```
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ctc_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ctc_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_precip_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_precip_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_precip_spatial_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_snowfall_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_snowfall_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_spcoutlook_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_spcoutlook_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_grid2obs_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_precip_plots.sh
```
_[Total: 0 prep jobs, 23 stats jobs, 13 plots jobs]_

- [x] Has the code been checked to ensure that no errors occur during the execution? **No**

- [x] Do these updates/additions include sufficient testing updates? **Yes**

- [x] Please complete this pull request review by **11/17/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/eam_ee2_edits_round2`. I will get everything set up and begin the test runs when the queues are open on cactus.

**Comment by PerryShafran-NOAA** [comment]
Hi, @MarcelCaron-NOAA ,

We need to make another addition to this PR.  Lin Gan, when doing ecflow testing, noted that the job failed when the cam_check_settings.py file is being called.  The variable machine cannot be defined in the ecf file the way you have it in the driver script.  

He asked that in every exevs script, you should add the following line at the top of the script:

export machine=${machine:-"WCOSS2"}

This should not affect any runs since you do have it defined in your driver script.  But when the jobs run in production, export machine will probably not be used in the ecf, thus the need to make this change.  Lin asked that it go in the exevs script.  

Use this in every exevs you call the cam_check_settings.py script, which can be found in prep, stats, and plots.  

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
> Hi, @MarcelCaron-NOAA ,
> 
> We need to make another addition to this PR. Lin Gan, when doing ecflow testing, noted that the job failed when the cam_check_settings.py file is being called. The variable machine cannot be defined in the ecf file the way you have it in the driver script.
> 
> He asked that in every exevs script, you should add the following line at the top of the script:
> 
> export machine=${machine:-"WCOSS2"}
> 
> This should not affect any runs since you do have it defined in your driver script. But when the jobs run in production, export machine will probably not be used in the ecf, thus the need to make this change. Lin asked that it go in the exevs script.
> 
> Use this in every exevs you call the cam_check_settings.py script, which can be found in prep, stats, and plots.
> 
> Thanks!
> 
> Perry

Okay, let me work on this now, and I'll push the change shortly.  Thanks to you and Lin for the suggested solution!

**Comment by ShelleyMelchior-NOAA** [comment]
I started the cam plots processing. I chose plots first since they take longer to complete. grid2obs and precip are still running.
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/cam/atmos.20231107`
Note the mix of file times. Some of these files were generated from the HREF PR. I have since re-run the complete HREF PR plots and those files were written to stmp instead of ptmp. The cam PR only ran a subset of plots processes. So please focus only on the newest/earliest timestamped tar files in COMOUT noted above.
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_*_plots.o92743*`

**Comment by ShelleyMelchior-NOAA** [comment]
@MarcelCaron-NOAA , I merged the HREF PR into develop. It resulted in 6 flies in conflict. I could resolve them all in this PR github interface. Please run `git pull` in your branch `bugfix/cam_ee2_edits_round2`.

**Comment by MarcelCaron-NOAA** [comment]
Thanks for resolving the conflicts @ShelleyMelchior-NOAA 

I checked logs and output files for the plots jobs.  All plots jobs completed successfully except for the following:
- jevs_cam_href_precip_past31day_plots
- jevs_cam_precip_plots
- jevs_cam_grid2obs_plots

jevs_cam_href_precip_past31day_plots finished but has a "No such file" message.  jevs_cam_precip_plots is still running but I noticed two issues already.  I'm working on a fix for both.  

jevs_cam_grid2obs_plots is still running but looks good so far.

**Comment by ShelleyMelchior-NOAA** [comment]
OK, cam grid2obs plots completed.
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/cam/atmos.20231108`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_grid2obs_plots.o92743175`

I re-submitted `jevs_cam_precip_plots` and `jevs_cam_href_precip_past31day_plots`.
```
                                                                                                   Req'd  Req'd   Elap
Job ID                         Username        Queue           Jobname         SessID   NDS  TSK   Memory Time  S Time
------------------------------ --------------- --------------- --------------- -------- ---- ----- ------ ----- - -----
92870906.cbqs01                shelley.melchi* dev             jevs_cam_href_*   145758    4   312  400gb 01:00 R 00:01
92870924.cbqs01                shelley.melchi* dev             jevs_cam_preci*   141842    4   512    --  05:30 R 00:00
```
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/`
`jevs_cam_precip_plots.o92870924`
`jevs_cam_href_precip_past31days_plots.o92870906`

**Comment by ShelleyMelchior-NOAA** [comment]
Ok, nevermind on that cam precip re-run. I caught that day shift and it tried to verify for 20231110 before stats had run, so the needed data wasn't available. It produced an empty tar. I am re-running now, ~24 hours later, and keeping VDATE=20231110.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_precip_plots.o92975615`

Also, I moved the output for the re-run of the href precip past 31 days plot to vpppg/save in case the results are scrubbed from ptmp before you get to them over the long weekend.
`/lfs/h2/emc/vpppg/save/shelley.melchior/forMC`

**Comment by MarcelCaron-NOAA** [comment]
**jevs_cam_grid2obs_plots completed successfully and output plots look normal.**

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA Thanks for rerunning these this weekend.  

jevs_cam_precip_plots used the restart directory so it didn't run any plots unfortunately--but I also noticed that COMIN is set to use the $USER noscrub instead of emc.vpppg, resulting in no input statistics.  That may actually be why the job failed the first time. 

Finally, the recent jevs_cam_href_precip_past31days_plots job I think was using the HREF PR (HOMEevs=/lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/**BZ**/EVS) instead of /lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/**MC**/EVS, so it didn't use the recent changes added to this PR! XD

**Do you mind correcting COMIN in  the jevs_cam_precip_plots test and HOMEevs in the jevs_cam_href_precip_past31days_plots test and then rerunning both once?**

**Comment by MarcelCaron-NOAA** [comment]
Also, a few METplus developers investigated the issue affecting jevs_cam_*_radar_stats.  [Here's the link to that discussion](https://github.com/dtcenter/METplus/discussions/2415#discussioncomment-7537535).  In summary, while they couldn't find the cause, they found a simple fix.  

**If possible, I'd like to develop and push the fix before those radar/stats jobs are tested.**  I think I can have that updated here by midday on Monday.

**Comment by ShelleyMelchior-NOAA** [comment]
Gah! I wonder what happened in my set up. It is probably related to me moving both b/t dogwood and cactus and also moving from the NCWCP office back to my home office last week. Let me double check my set up and I will re-run the cam precip plots job and the href precip past 31 days plots job. Yes, please go ahead and integrate the bg fix recommendation by the METplus team, too.

**Comment by ShelleyMelchior-NOAA** [comment]
Ok, I re-ran href precip past 31 days w/ COMIN adjusted to use emc.vpppg stats and my HOMEevs is pointed to your branch.
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/cam/atmos.20231110`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_href_precip_past31days_plots.o93023871`
Now that it is almost Monday I will not relocate the files from ptmp.

cam precip is also underway.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_precip_plots.o93023649`

Also, just for background, I figured out the problem. I had correctly set up the HOMEevs symlink to your clone to run your branch, but my qsub command was pointing to the BZ fork and branch. My habit is to use the history command to quickly reconstruct qsub commands and I must have grabbed an old command that used the BZ directory rather than the MC directory. Shortcuts are great, but sometimes they bite you!

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA Ah, okay, that makes sense.  Thanks for the rerun!

1. **jevs_cam_href_precip_past31days_plots completed successfully and output plots look normal.**
2. **jevs_cam_precip_plots** had a python error due to a typo I made in the edit.  It's fixed and I'm rerunning myself now to confirm the fix, but seems to work so far.
3. **I added the fix for cam/radar/stats to this PR**, so that should be ready to go when it's time to test stats.  Lin Gan is testing the same fix now in the ecflow environment, so we'll know of any problems soon.

**Comment by ShelleyMelchior-NOAA** [comment]
I have submitted the re-run for cam precip plots, this time for 20231111.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_precip_plots.o93101804`

**Comment by ShelleyMelchior-NOAA** [comment]
I have started to submit the cam stats jobs. radar and severe have conluded. snowfall is underway and seems to be going well. precip is underway. grid2obs is underway, but I see a lot of FATAL ERRORs in the logfiles.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam/`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_*_stats.o*`

**Comment by MarcelCaron-NOAA** [comment]
jevs_cam_\*\_radar_stats and jevs_cam_\*\_severe_stats completed successfully and output files appear normal.

Waiting on one more job for snowfall stats and two for precip stats.  I need to make a fix on the grid2obs stats jobs, so I will work on that in the meantime.

**Comment by MarcelCaron-NOAA** [comment]
**jevs_cam_\*\_snowfall_stats completed successfully and output files appear normal.**

The precip stats jobs failed and I've made a couple of fixes.  I've pushed the fixes for precip and grid2obs, the latter which tested successfully for me.  Do you mind rerunning precip and grid2obs stats sets @ShelleyMelchior-NOAA?

**Comment by MarcelCaron-NOAA** [comment]
All of the remaining stats jobs completed successfully and output files are normal, except for two that failed:
jevs_cam_href_precip_stats
jevs_cam_href_grid2obs_stats

Also, the following plots job still needs to be fixed:
jevs_cam_precip_plots

I will investigate and work on a fix for these three jobs, and will update this thread when the fixes have been pushed.  Once these run successfully we'll be down to only the prep jobs.

**Comment by ShelleyMelchior-NOAA** [comment]
>Once these run successfully we'll be down to only the prep jobs.

Do prep jobs need to be run? Original PR instructions did not include prep.

**Comment by MarcelCaron-NOAA** [comment]
Oops, nope they don't!  I'm so used to testing prep jobs.  

So once those three run successfully that should cover testing for this PR.

**Comment by ShelleyMelchior-NOAA** [comment]
I will look for the updates and re-run when appropriate. Looks like Binbin provided some help for jevs_cam_href_precip_stats.sh (via email).

**Comment by ShelleyMelchior-NOAA** [comment]
Also, just a note over here in this PR, too, to be thorough ... please update cam to no longer hard code the path for cartopyDataDir now that EVS VE has been updated by NCO.

**Comment by MarcelCaron-NOAA** [comment]
Just an update, I've added fixes to all three files and I'm testing them now.  

The precip plots job has been having slowness issues and some Killed jobs in testing and in the parallel.  I think this occurred after the recent production switch, but definitely identifies areas where memory load could be reduced.  I will verify in the test run that the fixes address these issues.

If all goes well this evening I'll update again that the jobs are ready to re-run.

**Comment by MarcelCaron-NOAA** [comment]
The following tested successfully are ready to be re-run:
jevs_cam_precip_plots
jevs_cam_href_grid2obs_stats

Still working on the following:
jevs_cam_href_precip_stats

**Comment by ShelleyMelchior-NOAA** [comment]
Great, thanks @MarcelCaron-NOAA . I have pulled in your changes and resubmitted the two jobs:
```
Job ID                         Username        Queue           Jobname         SessID   NDS  TSK   Memory Time  S Time
------------------------------ --------------- --------------- --------------- -------- ---- ----- ------ ----- - -----
93276697.cbqs01                shelley.melchi* dev             jevs_cam_href_*   149266    1    72  500gb 04:30 R 00:50
93276885.cbqs01                shelley.melchi* dev             jevs_cam_preci*   213363    4   512    --  05:30 R 00:47
```
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/`
`jevs_cam_href_grid2obs_stats.o93276697`
`jevs_cam_precip_plots.o93276885`

**Comment by ShelleyMelchior-NOAA** [comment]
The cam_precip_plots finished pretty quickly, in 2:10!
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/cam/atmos.20231114`

**Comment by ShelleyMelchior-NOAA** [comment]
The cam href grid2obs stats job completed.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam/href.20231114`

**Comment by MarcelCaron-NOAA** [comment]
:heavy_check_mark: jevs_cam_href_grid2obs_stats completed successfully and output files look normal.

:triangular_flag_on_post: jevs_cam_precip_plots completed normally, within the wallclock limit, and no processes were killed.  A check of output graphics shows that Alaska graphics are missing.  I found the bug and added a fix.  I don't expect any other issue with this job, but I think a re-run would be a good idea.

:triangular_flag_on_post: jevs_cam_href_precip_stats is ready to re-run

:triangular_flag_on_post: jevs_cam_nam_firewxnest_grid2obs_plots jobs have been regularly hitting the wallclock and memory limits in the parallel since the recent prod switch.  I increased the resource allocation.  Can we run this as well?  

So final re-runs for this PR:
- **jevs_cam_precip_plots** (~3h)
- **jevs_cam_href_precip_stats** (~1h30m)
- **jevs_cam_nam_firewxnest_grid2obs_plots** (30m-45m)
 
If results match my tests, I'd feel pretty good about this PR.

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks Marcel! I recloned your fork (and checked out the correct branch) b/c I screwed up my stashed changes. Since I only need to retest 3 drivers, no big loss. All 3 drivers are underway.
```
Job ID                         Username        Queue           Jobname         SessID   NDS  TSK   Memory Time  S Time
------------------------------ --------------- --------------- --------------- -------- ---- ----- ------ ----- - -----
93302115.cbqs01                shelley.melchi* dev             jevs_cam_preci*   249587    4   512    --  05:30 R 00:06
93302215.cbqs01                shelley.melchi* dev             jevs_cam_nam_f*    55533    1     1  100gb 01:00 R 00:05
93302316.cbqs01                shelley.melchi* dev             jevs_cam_href_*   149374    1    88   10gb 02:00 R 00:04
```
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/`
`jevs_cam_precip_plots.o93302115`
`jevs_cam_nam_firewxnest_grid2obs_plots.o93302215`
`jevs_cam_href_precip_stats.o93302316`

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA Thanks for re-running these jobs! Hopefully we can PR squared away today! 

@MarcelCaron-NOAA Please see my email from earlier this morning about adding a fix to global_ens into this PR (so that we can get the fix into the auth repo as soon as possible). Thanks!

**Comment by MarcelCaron-NOAA** [comment]
@AliciaBentley-NOAA the indentation fix in the global_ens file was added here.

@ShelleyMelchior-NOAA: 
✔️ **jevs_cam_precip_plots** and **jevs_cam_nam_firewxnest_grid2obs_plots** ran to completion and output files appear normal.

🚩 **jevs_cam_href_precip_stats** failed (correctly) due to fully missing obs files.  The job was submitted too early because I have the qsub arguments written incorrectly in the instructions.  The should be submitted with no additional arguments:
`qsub $HOMEVS/dev/drivers/scripts/stats/cam/jevs_cam_href_precip_stats.sh`

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks, Marcel! I will re-run cam href precip stats after updating my local clone.

**Comment by ShelleyMelchior-NOAA** [comment]
```
$ qsub /lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/MC/EVS/dev/drivers/scripts/stats/cam/jevs_cam_href_precip_stats.sh
```
```
                                                                                                   Req'd  Req'd   Elap
Job ID                         Username        Queue           Jobname         SessID   NDS  TSK   Memory Time  S Time
------------------------------ --------------- --------------- --------------- -------- ---- ----- ------ ----- - -----
93390626.cbqs01                shelley.melchi* dev             jevs_cam_href_*   144549    1    88   10gb 02:00 R 00:00
```
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_href_precip_stats.o93390626`

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA sorry; I needed to make one more commit.  It doesn't affect the output plots or stats of any jobs already tested or the job currently being tested, it just corrects a warning message in a plots log that isn't quite right.  So no additional re-run is necessary.

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA Thanks for letting us know! I hope that jevs_cam_href_precip_stats looks good this time through!

**Comment by ShelleyMelchior-NOAA** [comment]
Woohoo! The href precip stats job has completed. And also ... 
```
[clogin02 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ grep FATAL jevs_cam_href_precip_stats.o93390626
[clogin02 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$
```
🎉

**Comment by MarcelCaron-NOAA** [comment]
✔️ Yes I think we're good.  The job ran to completion.

The log file has a non-fatal error, but that is expected because one METplus job did not meet the critical threshold of available ensemble member forecasts today (not EVS's fault), and all of that was indicated correctly in the stdout file.

Also output files look normal.

**Comment by ShelleyMelchior-NOAA** [comment]
Fantastic, @MarcelCaron-NOAA ! Thank you for your efforts in this PR. I have been doing the code review during the duration. I will do the formal approval and merge after one more sync fork.

**Comment by MarcelCaron-NOAA** [comment]
Thanks @ShelleyMelchior-NOAA!

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Big news! All changes look good. Tests yield expected results. This PR is approved for merge.

**Pull request merged**
