### PR TITLE
Adding place=shared to remaining 2 ecf scripts

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

In solving Wei's Issue number 4 on his document, there were two ecf scripts that were missing the place=shared designation in the PBS job card.  This PR includes those scripts.  

- [ ] Describe testing already performed for this Pull Request:</br>

No testing required.  

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

No testing required.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by malloryprow** [comment]
This PR made me think of something I have been seeing from the logs in the emc.vpppg parallel. jevs_global_det_atmos_gfs_grid2obs_stats, jevs_global_det_atmos_grid2obs_pres_levs_plots_90days, and jevs_global_det_atmos_grid2obs_sfc_plots_31days are all showing "Cgroup mem limit exceeded".

I'm not sure if that me something easily or appropriate to add to this PR, but if it isn't I can do another PR for it.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Check to see that these jobs are seeing such errors in the NCO parallel.  Right now, the emc.vpppg is using dev drivers, and NCO won't be seeing what's in dev.  What matters is that they see what's in ecf, and if this isn't an issue for them, then the settings for ecf are correct.  They aren't quite matching dev drivers at this time.  Please file this in a separate PR to be addressed later.  

@AliciaBentley-NOAA @ShelleyMelchior-NOAA

**Comment by malloryprow** [comment]
> @malloryprow Check to see that these jobs are seeing such errors in the NCO parallel. Right now, the emc.vpppg is using dev drivers, and NCO won't be seeing what's in dev. What matters is that they see what's in ecf, and if this isn't an issue for them, then the settings for ecf are correct. They aren't quite matching dev drivers at this time. Please file this in a separate PR to be addressed later.
> 
> @AliciaBentley-NOAA @ShelleyMelchior-NOAA

Looked at the logs in /lfs/h1/ops/para/output/20240212, it wasn't in any of the ones I mentioned but in evs_global_det_gfs_atmos_grid2grid_stats, haha. I'll see if it is in any of the other days and submit the necessary PR.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
ecf changes appear correct. No testing can occur. Wei will test in NCO para.

**Pull request merged**
