### PR TITLE
Prep step for CAM radar and severe vx

### PR DESCRIPTION
**Pull request by LoganDawson-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

The prep jobs have been running routinely (hourly to daily frequency) on user cron and output is generated as expected.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

1. Clone the cam_radar_vx feature branch. 

2. Clone the repository with cron scripts for testing: https://github.com/LoganDawson-NOAA/EVS_crons. Driver scripts need to be updated to point to the reviewer's location for $HOMEevs for each `qsub` command

3. Set up cron jobs as follows (one cron for each ecf script that needs to be tested):
```
# Cron for EVS job to prep SPC data for verification once per day
30 07 * * * /lfs/h2/emc/vpppg/save/${USER}/EVS_crons/drive_jevs_cam_severe_prep.sh 1>/lfs/h2/emc/ptmp/${USER}/cron.out/jevs_cam_severe_prep.out 2>&1

# Cron for prepping radar data on a hourly basis
20 * * * * /lfs/h2/emc/vpppg/save/${USER}/EVS_crons/drive_jevs_cam_radar_prep.sh 1>/lfs/h2/emc/ptmp/${USER}/cron.out/jevs_cam_radar_prep.out 2>&1

# Cron for EVS jobs to prep SSPF data (2-4x per day)
06 00,06,12,18 * * * /lfs/h2/emc/vpppg/save/${USER}/EVS_crons/drive_jevs_hrrr_severe_prep.sh 1>/lfs/h2/emc/ptmp/${USER}/cron.out/jevs_hrrr_severe_prep.out 2>&1

08 00,06,12,18 * * * /lfs/h2/emc/vpppg/save/${USER}/EVS_crons/drive_jevs_namnest_severe_prep.sh 1>/lfs/h2/emc/ptmp/${USER}/cron.out/jevs_namnest_severe_prep.out 2>&1

10 00,12 * * * /lfs/h2/emc/vpppg/save/${USER}/EVS_crons/drive_jevs_hireswfv3_severe_prep.sh 1>/lfs/h2/emc/ptmp/${USER}/cron.out/jevs_hireswfv3_severe_prep.out 2>&1

12 00,12 * * * /lfs/h2/emc/vpppg/save/${USER}/EVS_crons/drive_jevs_hireswarw_severe_prep.sh 1>/lfs/h2/emc/ptmp/${USER}/cron.out/jevs_hireswarw_severe_prep.out 2>&1

14 00,12 * * * /lfs/h2/emc/vpppg/save/${USER}/EVS_crons/drive_jevs_hireswarwmem2_severe_prep.sh 1>/lfs/h2/emc/ptmp/${USER}/cron.out/jevs_hireswarwmem2_severe_prep.out 2>&1

16 00,06,12,18 * * * /lfs/h2/emc/vpppg/save/${USER}/EVS_crons/drive_jevs_rrfs_severe_prep.sh 1>/lfs/h2/emc/ptmp/${USER}/cron.out/jevs_rrfs_severe_prep.out 2>&1

18 00,12 * * * /lfs/h2/emc/vpppg/save/${USER}/EVS_crons/drive_jevs_href_severe_prep.sh 1>/lfs/h2/emc/ptmp/${USER}/cron.out/jevs_href_severe_prep.out 2>&1
```

4. Special attention should be paid to the definition of COMOUT in the ecf scripts.

5. Radar job can examined quickly to determine if the 9 hourly files are generated every hour. The severe jobs should be run for a full day prior to checking the output. Initial HREF jobs will fail due to lack of time-lagged members available unless the code manager copies existing SSPF files from the devloper.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **5/1/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@LoganDawson-NOAA  and @PerryShafran-NOAA  I can pick up this PR unless it is preferred Perry do it.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran `drive_jevs_cam_severe_prep.sh` interactively, rather than by cron, since it only needs to run once daily, to make sure I could make a single instance work. I can set it up for cron  upon developer approval in order to support subsequent stats processing.
Please review the prep output.
Data:
`COMOUT=/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/cam`
log file:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_severe_prep.o56898964`

**Comment by LoganDawson-NOAA** [comment]
@ShelleyMelchior-NOAA thanks for picking up this PR. I need to push some updates (primarily to the ecf scripts) to my remote branch that will address the errors in your runs of `jevs_cam_severe_prep.ecf`. 

Yesterday, @PerryShafran-NOAA independently found a problem with my order of setting `$DATAROOT` prior to running `module reset` and loading `prod_envir`. When prod_envir is included in a user's login environment, the module reset statement unsets the $DATAROOT path that points to the "developer location" and the subsequent load of prod_envir in the ecf script then points $DATAROOT to the production path. That results in errors like:

```
0 + DATA=/lfs/h1/ops/prod/tmp/jevs_cam_severe_prep.56898964.cbqs01
0 + rm -rf /lfs/h1/ops/prod/tmp/jevs_cam_severe_prep.56898964.cbqs01
0 + mkdir -p /lfs/h1/ops/prod/tmp/jevs_cam_severe_prep.56898964.cbqs01
mkdir: cannot create directory â/lfs/h1/ops/prod/tmp/jevs_cam_severe_prep.56898964.cbqs01â: Permission denied
0 + cd /lfs/h1/ops/prod/tmp/jevs_cam_severe_prep.56898964.cbqs01
/lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/LD/EVS/jobs/cam/prep/JEVS_CAM_PREP: line 23: cd: /lfs/h1/ops/prod/tmp/jevs_cam_severe_prep.56898964.cbqs01: No such file or directory
```
I wasn't seeing this behavior previously because my login environment did not include prod_envir. I've reordered my ecf scripts to move all "dev testing" settings below the list of module loads, which prevents the issue from occurring regardless of whether the user's login environment includes prod_envir. That order is almost certainly better coding practice anyways.

I'll post a note once the remote branch is ready for you to pull down, and I'll validate subsequent runs of my prep jobs.

**Comment by LoganDawson-NOAA** [comment]
Ok @ShelleyMelchior-NOAA, the current version of the code in my branch is ready for testing.

In addition to pulling the updates from this branch, please pull updates from my EVS_crons repo. I had a minor mistake that would prevent the 12Z hiresw jobs from running.

**Comment by ShelleyMelchior-NOAA** [comment]
The re-run is complete, after updating the cam_radar_vx feature branch. Please review the output.
Data:
`COMOUT=/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/cam`
log file:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_severe_prep.o56955718`

**Comment by LoganDawson-NOAA** [comment]
The rerun was successful! All the data are the same, and there are no errors in the log output.

**Comment by ShelleyMelchior-NOAA** [comment]
Great! I will move onto the remainder of the prep processes.

**Comment by ShelleyMelchior-NOAA** [comment]
I just set up all the cron entries. Of course, I got the crontab set up at `Wed May  3 18:16:17 UTC 2023` ... just missing the entries that kick off at 18Z. I will run them interactively to make sure all is OK instead of waiting until 00Z.

**Comment by ShelleyMelchior-NOAA** [comment]
Interactive runs were submitted. Please review.
`COMOUT=/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/cam`
log output dir: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/`
log output files: 
`jevs_cam_radar_prep.o57054335`
`jevs_hrrr_severe_prep_00.o57054828`
`jevs_hireswfv3_severe_prep_00.o57054838`
`jevs_namnest_severe_prep_00.o57054832`
`jevs_hireswarw_severe_prep_00.o57054850`
`jevs_href_severe_prep_00.o57054904`
`jevs_hireswarwmem2_severe_prep_00.o57054875`
`jevs_rrfs_severe_prep_00.o57054876`

NOTE: cam_severe_prep was not re-run as it has been running in cron for the past day or so.

**Comment by LoganDawson-NOAA** [comment]
@ShelleyMelchior-NOAA with only one exception, the outputs from your interactive runs match the output from my 12Z and 18Z cron jobs.

The only difference is with the `jevs_href_severe_prep` output, which was not produced in your run. This is expected because the HREF job uses on-time and time-lagged output from the other jevs_${model}_severe_prep runs to produce its output. Only 3 of 10 files were available, data missing emails were sent to me and Geoff, and the job still exited cleanly with a 0 exit code. (This will be an issue when EVS is implemented, and this test confirms that our clean exits + warning messages for missing data are working as we expect).

Tonight's 00Z submission of the HREF job should work correctly because the 5 time-lagged inputs (12Z HiResWs and 18Z NAM Nest & HRRR) in addition to the 00Z on-time inputs will be available. Once I validate the 00Z runs from this evening, you'll have the thumbs up from me to merge in these updates.

**Comment by LoganDawson-NOAA** [comment]
@ShelleyMelchior-NOAA can confirm that your 00Z and 12Z runs of the HREF job completed without error and the outputs match mine

**Comment by ShelleyMelchior-NOAA** [comment]
Great! I will begin the more meticulous code review and approve the merge if nothing pops out at me.

**Comment by ShelleyMelchior-NOAA** [comment]
Good and proper use for addressing some of the known NCO standards re: python and shell scripting.

The only question I have is the presence of stats and plots J-jobs for a prep PR: `JEVS_CAM_STATS` and `JEVS_CAM_PLOTS`. Perhaps this was intentional in order to address some of the NCO standards for python and shell scripting?

**Comment by LoganDawson-NOAA** [comment]
I've reverted `JEVS_CAM_STATS` and `JEVS_CAM_PLOTS` back to the versions that are in the auth repo, so those file changes are removed now!

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All files look good

**Pull request merged**
