### PR TITLE
feature/global_det_atmos_headline_jjob

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

> Tested by running dev/drivers/scripts/global_det/plots/jevs_global_det_atmos_headline_plots.sh in feature branch; compared output to my parallel

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> Checkout the branch
Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_test_scripts/pr_172/run_evs_global_det_headline_plots.sh. Run it.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **08/07/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Going to start on this one.  

Perry

**Comment by PerryShafran-NOAA** [comment]
The test is finished.  See the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr172test/EVS/dev/drivers/scripts/global_det/plots

And the plots file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/headline.20230725

Perry

**Comment by malloryprow** [comment]
✔️ Looks good!

**Comment by PerryShafran-NOAA** [comment]
Sweet!  We can merge this one in now.  Code review looks good; not a lot of code to look at here.

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
