### PR TITLE
Changing MXGS to GUST to remove WARNINGs from gust plots

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

This PR:

- Removes the WARNING statements in the firewxnest plot output
- Ensures that all three traces (firewx, namnest, hrrr) are plotted on gust plots

- [ ] Describe testing already performed for this Pull Request:</br>

Ran the firewxplot job.  There were no more WARNINGs in the firewxnest output, and the plots all had all traces of GUST in their plots.  

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

If you are emc.vpppg, run the test as follows:

Run the firewxnest plot job.  Set HOMEevs to your testing directory.  
Set COMIN=/lfs/h2/emc/vpppg/noscrub/$USER/com/$NET/$evs_ver_2d

Check for:
WARNINGs, especially in the GUST part of the output
Check the gust plot itself to see whether all traces of gust are being shown.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP.

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/firewx_gust`.

**_NOTE:_** This covers item 71 in Wei's document.

**Comment by ShelleyMelchior-NOAA** [comment]
The nam firewx next plot has been completed! I see no WARNINGs in the log file.
logfile (cactus): `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_nam_firewxnest_grid2obs_plots.o113308537`
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/cam/atmos.20240118`
I untar'd the tar file and the 2 gust plots are available here: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/untar-firewx`

**Comment by PerryShafran-NOAA** [comment]
The plots have the traces for all the models, which is what we want.  And if you saw no WARNINGs, then I think we're good here for merging.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yield expected results. This PR is approved for merge.

**Pull request merged**
