### PR TITLE
bugfix/global_ens_envir

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- Add "export envir=prod" to driver scripts were needed
- Use DCOMROOT for OSI-SAF and GHRSST data

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> This is another PR where the changes touch a lot of the driver scripts. I would like dev/drivers/scripts/global_ens/prep/jevs_global_ens_atmos_prep.sh to be run to make sure the job is using the OSI-SAF and GHRSST data from prod/dcom and no lone dev/dcom.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **No**

- [ ] Do these updates/additions include sufficient testing updates? **No**

- [ ] Please complete this pull request review by **10/13/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
I have your bugfix branch and am starting the testing now.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Would you please check the following?  The run completed late last night.

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr256test/EVS/dev/drivers/scripts/global_ens/prep/jevs_global_ens_atmos_prep.o82414507

The output directory is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230918

**Comment by malloryprow** [comment]
Seeing GHRSST coming from prod lfs/h1/ops/prod/dcom/20230918/validation_data/marine/ghrsst/20230918_OSPO_L4_GHRSST.nc.

Seeing OSI-SAF coming from prod /lfs/h1/ops/prod/dcom/20230917/seaice/osisaf/ice_conc_nh_polstere-100_multi_202309171200.nc, /lfs/h1/ops/prod/dcom/20230917/seaice/osisaf/ice_conc_sh_polstere-100_multi_202309171200.nc.

@StevenSimon-NOAA, would you like to check out what is in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230918?

**Comment by StevenSimon-NOAA** [comment]
> Seeing GHRSST coming from prod lfs/h1/ops/prod/dcom/20230918/validation_data/marine/ghrsst/20230918_OSPO_L4_GHRSST.nc.
> 
> Seeing OSI-SAF coming from prod /lfs/h1/ops/prod/dcom/20230917/seaice/osisaf/ice_conc_nh_polstere-100_multi_202309171200.nc, /lfs/h1/ops/prod/dcom/20230917/seaice/osisaf/ice_conc_sh_polstere-100_multi_202309171200.nc.
> 
> @StevenSimon-NOAA, would you like to check out what is in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230918?

All prep files generated by the global_ens_atmos prep driver are fully accounted for, including today's osi file.

**Comment by PerryShafran-NOAA** [comment]
Good news!  @malloryprow thumbs up to merge?

**Comment by malloryprow** [comment]
Fine by me!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow do we need a sync fork?  I think that we're fully updated, but I sometimes find it hard to keep track.

**Comment by malloryprow** [comment]
I synced it this morning!

**Comment by PerryShafran-NOAA** [comment]
Great!  We're good to go.

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
