### PR TITLE
Feature/met metplus prod

### PR DESCRIPTION
**Pull request by ShelleyMelchior-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
Tested updates to `modulefiles/global_det/global_det_stat.sh` in a run of `jevs_global_det_wave_grid2obs_stats.sh`. The test performed as expected.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
I suggest a spot check of another stats run in a different component to make sure the expected stats files are produced.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
I am currently testing this on analyses/urma stats.  I will let you know the result.

Perry

**Comment by PerryShafran-NOAA** [comment]
Looks like results are as expected:

.o files:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr210test/EVS/dev/drivers/scripts/analyses/stats/jevs_analyses_urma_grid2obs_stats.o78047384
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr210test/EVS/dev/drivers/scripts/analyses/stats/jevs_analyses_rtma_grid2obs_stats.o78056619

stat files:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/analyses/atmos.20230823/rtma/grid2obs
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/analyses/atmos.20230823/urma/grid2obs

I think that we are good on this.

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
Looks like we are good to go!

**Comment by PerryShafran-NOAA** [comment]
No further testing is needed, do you think?

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
I do not think any further testing is needed.

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
