### PR TITLE
Bugfix/analyses structure

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

The structure of analyses was changed to the system desired by NCO. The stats and plots all worked perfectly after all the changes to structure were made and also within scripts using the structure.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run the stats driver (using the -v cyc=04 or your favorite cycle number). 
Run the plots driver. Set COMIN to the emc.vpppg directory.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP.

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `feature/analyses_structure`.

**Comment by ShelleyMelchior-NOAA** [comment]
stats processing (cyc=04) has concluded.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/analyses/atmos.20231005/*/grid2obs`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_analyses_*_grid2obs_stats.o836057*`

plots processing has concluded.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/analyses/atmos.20231005`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_analyses_grid2obs_plots.o83606257`

**Comment by PerryShafran-NOAA** [comment]
Stats and plots match exactly what is currently in emc.vpppg parallel.

I think that we're good here.

**Comment by ShelleyMelchior-NOAA** [comment]
Excellent! I can do one last code review and then merge.

**Review by ShelleyMelchior-NOAA — COMMENTED** [review]
The testing of the code restructuring produced expected results. This PR is ready for merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]

**Pull request merged**
