### PR TITLE
feature/radar_svr_modulefiles

### PR DESCRIPTION
**Pull request by LoganDawson-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
This PR adds modulefiles changs for the prep and stats steps for the CAM radar and severe subcomponents. Jobs were run on a cron overnight and all jobs successfully completed as expected.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Unlike my prior PRs, there isn't a need to set up full cron jobs to test these changes. Grab updates to cron drivers from [here](https://github.com/LoganDawson-NOAA/EVS_crons/tree/main), and the jobs can be submitted interactively to confirm successful execution. The driver scripts listed below will need to be updated to point to the reviewer's location for `$HOMEevs` for each `qsub` command

Radar jobs:
1. Run `drive_jevs_cam_radar_prep.sh` interactively (typically takes ~12-15 mins to complete)
2. Run `drive_cam_radar_stats.sh` interactively after prior job completes. This will submit stats jobs for each jevs_${model}_radar_stats.sh script included in this PR.
3. The only wrinkle is steps 1 and 2 must be run during the same hour to ensure that hour's prep output is available for the stats jobs.

Severe jobs:
1. Run `drive_jevs_cam_severe_prep.sh` interactively (typically takes ~2-5 mins to complete)
2. Run `drive_cam_severe_prep.sh` interactively. This will submit prep jobs for each jevs_${model}_severe_prep.sh script included in this PR.
3. In jevs_${model}_severe_stats.sh scripts, update COMINspclsr, COMINspcotlk, and COMINfcst to point to /lfs/h2/emc/vpppg/noscrub/logan.dawson/evs/v1.0/prep/cam (or symlink my prep data to your user space)
4. Run `drive_cam_severe_stats.sh` interactively after step 1 completes.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes]**

- [ ] Please complete this pull request review by **[ASAP]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, @LoganDawson-NOAA - I'm going to start working on this PR.  Please be sure that you have brought in the latest develop branch - there has been a few PRs merged since your last develop merge, I think (unless that Merge branch commit listed above was earlier today).

Perry

**Comment by PerryShafran-NOAA** [comment]
Running the stats for radar now.  They are indeed run in the same hour as the prep, as instructed (cyc=13).  I had to add "cam" to the filename in the driver script because you had already changed the filenames in the dev/driver/script directory but not in your driver script.  Stats are running now.  

If you'd like to validate prep, you can find the .o file here:  /lfs/h2/emc/ptmp/perry.shafran/cron.out
and the prep files here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/cam/mrms.20230724

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, @LoganDawson-NOAA ,

All the stats jobs are finished.  Please look here for the .o files:  /lfs/h2/emc/ptmp/perry.shafran/cron.out

And the stats out put is here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/*20230724*

Have a look!

Perry

**Comment by LoganDawson-NOAA** [comment]
@PerryShafran-NOAA I've now brought this branch up to date with the authoritative develop branch.

I checked the output and logfiles for the radar prep and stats steps. All jobs completed successfully without error, and the output looks good. The stat files from your test runs are smaller than my stat files because they don't include stats within the SPC outlook areas. The masks in `spc_lsr.20230724` come from that 20230725 run of jevs_cam_severe_prep.sh, so it's expected that the outlook area stats aren't included. I don't have an issue with providing a 👍 to the radar test runs at this point though.

**Comment by PerryShafran-NOAA** [comment]
Excellent!  I'll just go over the code for a quick review, and then merge if all looks good.

Thanks!

Perry

**Comment by LoganDawson-NOAA** [comment]
@PerryShafran-NOAA these test runs only included review of the radar prep and stats jobs. Please see above instructions that include test runs of the severe prep and stats jobs. Those jobs are being updated with this PR also. Thanks.

**Comment by PerryShafran-NOAA** [comment]
Oops!  Yes, I have to test severe too.  Thanks for that reminder, I got ahead of myself!

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, @LoganDawson-NOAA ,

Starting severe prep.  I have done the drive_jevs_cam_radar_prep.sh run.  See the .o file here:  /lfs/h2/emc/ptmp/perry.shafran/cron.out/jevs_cam_severe_prep.o73069172

The output is here:   /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/cam

Working the other severe prep script.  

Perry

**Comment by PerryShafran-NOAA** [comment]
All prep jobs are now complete.  

You can see all the .o files here: /lfs/h2/emc/ptmp/perry.shafran/cron.out
and all the output here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/cam

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Logan,

Looks like the stats jobs failed.  I changed the variables to point to your prep archive, and it looks like certain files were not in your archive:

For example, in /lfs/h2/emc/ptmp/perry.shafran/cron.out/jevs_cam_href_severe_stats_00.o73071910, I see the following:

```
 echo 'Missing file is /lfs/h2/emc/vpppg/noscrub/logan.dawson/evs/v1.0/prep/cam/href.20230717/href.t12z.MXUPHL25_A24.SSPF.2023071812-2023071912.f48.nc\n'

Missing file is /lfs/h2/emc/vpppg/noscrub/logan.dawson/evs/v1.0/prep/cam/href.20230718/href.t00z.MXUPHL25_A24.SSPF.2023071812-2023071912.f36.nc\n
```
`Missing file is /lfs/h2/emc/vpppg/noscrub/logan.dawson/evs/v1.0/prep/cam/href.20230717/href.t12z.MXUPHL25_A24.SSPF.2023071812-2023071912.f48.nc\n'`

There are other missing files as well, in all the stats runs.

Let me know how to further proceed and if this needs fixing.

Perry

**Comment by PerryShafran-NOAA** [comment]
@LoganDawson-NOAA - when you have time, please address the comments above, to be sure it doesn't fall off the radar (so to speak).  

Thanks!

Perry

**Comment by LoganDawson-NOAA** [comment]
@PerryShafran-NOAA yep, that is first on my to-do list after I finish my biweekly with Jason and a late lunch.

I took a quick look right at the end of yesterday and saw the missing file notifications you highlight. I want to clarify that _the jobs did not fail but rather completed without generating output_ (the missing data checks worked as expected). 

I forgot that I'll need to move prep data over from Dogwood after last week's prod switch. More catchup work after being away during last week's prod switch. I may need to bring my laptop with me on trip so we can try to get this PR done before your leave begins.

**Comment by LoganDawson-NOAA** [comment]
> All prep jobs are now complete.
> 
> You can see all the .o files here: /lfs/h2/emc/ptmp/perry.shafran/cron.out and all the output here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/cam
> 
> Perry

I've looked at the output from all the prep runs (somehow it's still on Cactus!), and all looks good. No errors in the log output and the netcdf output looks as expected.

**Comment by LoganDawson-NOAA** [comment]
@ShelleyMelchior-NOAA if you have an opportunity to pick this PR up this week, validation of the severe stats jobs is the only remaining item. 

If you do pick it up, let's run in "retro mode" and set VDATE=20230710. I had some issues with moving data and updating some script names following the prod switch while Cactus was the dev machine, and we'll be able to validate the severe stats generation more quickly by using an older VDATE

**Comment by ShelleyMelchior-NOAA** [comment]
I have prepared the radar stats processing and have submitted the jobs via the drive script in the EVS_crons repository. I `exported VDATE=20230710` and I pointed COMIN to your user space. I'll report back in the morning once I review the results.

**Comment by ShelleyMelchior-NOAA** [comment]
I looked at the output from my overnight cam radar stats runs but there are no stats files. Did I set up the processing correctly for 20230710? Maybe problems w/ COMIN or VDATE or the input prep data itself?

COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/cron.out/jevs_cam_*radar_stats*`
HOMEevs=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/LD/EVS`
Your drive scripts are here: `/lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/LD/EVS_crons`

**Comment by ShelleyMelchior-NOAA** [comment]
Also, the cam radar drive script doesn't include rrfs in the models array. Should I be testing that one, too?

**Comment by AliciaBentley-NOAA** [comment]
Hi Shelley,

RRFS is not an operational model yet and should not be included in EVSv1.
Thanks!

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks. I was just unsure b/c the rrfs **_is_** included in the model array for the severe stats drive script. Note, what I am referring to is Logan's external drive script that submits the EVS driver scripts via a for loop.

**Comment by LoganDawson-NOAA** [comment]
> 

Sorry for the confusion @ShelleyMelchior-NOAA. Let me repost a complete set of modified instructions below so everything is more clear.

Also, I want to include the RRFS dev scripts in the repository so the stat generation can run in our dev EVS parallel, but as Alicia said, we don't need Lin to build ecflow scripts for EVSv1 delivery

**Comment by ShelleyMelchior-NOAA** [comment]
I just re-read more closely and you indicated *severe* stats. My bad. I will still wait for any further instructions in case I am still missing something key.

**Comment by LoganDawson-NOAA** [comment]
Updated instructions:

I updated my [cron drivers](https://github.com/LoganDawson-NOAA/EVS_crons/tree/main) to account for the dev/driver/script naming updates that are included in this PR. Pull those down unless you manually updated them like I believe Perry did.

**All radar jobs:**

1. There is no need to set an upstream VDATE.
2. Run drive_jevs_cam_radar_prep.sh interactively (typically takes ~12-15 mins to complete)
3. Run drive_cam_radar_stats.sh interactively after prior job completes. This will submit stats jobs for each jevs_${model}_radar_stats.sh script included in this PR.
4. The only wrinkle is steps 1 and 2 must be run during the same hour to ensure that hour's prep output is available for the stats jobs.

**Severe _prep_ jobs:**

1. There is no need to set an upstream VDATE.
2. Run drive_jevs_cam_severe_prep.sh interactively (typically takes ~2-5 mins to complete)
3. Run drive_cam_severe_prep.sh interactively. This will submit prep jobs for each jevs_${model}_severe_prep.sh script included in this PR.

**Severe _stats_ jobs:**

1. In all jevs_cam_${model}_severe_stats.sh dev/driver/scripts, update COMINspclsr, COMINspcotlk, and COMINfcst to point to /lfs/h2/emc/vpppg/noscrub/logan.dawson/evs/v1.0/prep/cam (or symlink my prep data to your user space)
2. In drive_cam_severe_stats.sh, set an upstream definition of `export VDATE=20230710`. There is a complete set of forecast/observation prep data available for this date.
4. Run drive_cam_severe_stats.sh interactively.

**Comment by ShelleyMelchior-NOAA** [comment]
I will not re-run radar since that was previously verified by Perry.

I re-ran severe prep. Please review.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/cam`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/cron.out/jevs_cam_severe_prep.o88358761`

**Comment by ShelleyMelchior-NOAA** [comment]
I re-ran the severe stats for VDATE=20230710. Please review.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/cron.out/jevs_cam_*severe_stats*`

**Comment by LoganDawson-NOAA** [comment]
> I will not re-run radar since that was previously verified by Perry.
> 
> I re-ran severe prep. Please review. COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/cam` logfile: `/lfs/h2/emc/ptmp/shelley.melchior/cron.out/jevs_cam_severe_prep.o88358761`

And the complications continue... The spc_otlk output is good, but the spc_lsr process failed on the python embedding for ASCII2NC. I'm testing the base MET command and the "nested" python call directly on the command line and the process is working for the previous REPDATE/VDATE, but it's not working for the current REPDATE/VDATE. I'm saving the 7/25 and 7/26 SPC report files on noscrub and will probably raise this at Monday's METplus telecon. I don't see the missing data or incorrectly formatted data that's causing the python script to fail.

Will you do a favor and set `VDATE=20230726` and rerun `drive_jevs_cam_severe_prep.sh`? If we can confirm the 7/25 report data works correctly in your test, then we can approve this part of the PR. And I'll separately need to work out the error with DTC.

**Comment by ShelleyMelchior-NOAA** [comment]
Just one quick question ... change VDATE and run prep, or stats? or both? You indicated `drive_jevs_cam_severe_prep.sh` but I think you mean stats?

**Comment by LoganDawson-NOAA** [comment]
VDATE=20230726 is just for the prep job (jevs_cam_severe_prep.sh). I think the VDATE=20230727 observation file is corrupted in some way.

VDATE=20230710 still works for the stats jobs

**Comment by ShelleyMelchior-NOAA** [comment]
Got it! re-running severe prep w/ VDATE=20230726. Please monitor and review. When completed, I will re-run severe stats w/ VDATE=20230710.

COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/cam`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/cron.out/jevs_cam_severe_prep.o88385686`

**Comment by LoganDawson-NOAA** [comment]
Perfect! The latest prep run completed successfully! No errors and outputs match mine.

**Comment by ShelleyMelchior-NOAA** [comment]
Great! The severe stats processing is underway again. Please monitor and review.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/cron.out/jevs_cam_*severe_stats*` (w/ the latest time stamps)

**Comment by LoganDawson-NOAA** [comment]
And we're good to go on the stats jobs as well! Output matches mine and the logfiles are clean. Let me merge develop and then we'll be good to go pending final code review.

**Comment by ShelleyMelchior-NOAA** [comment]
Wonderful! I will formalize the code review and approve the merge of this PR.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The code changes are approved. This PR may be merged.

**Pull request merged**
