### PR TITLE
feature/global_det_reorg

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

1. Change COMROOT to user's ptmp directory for plots
2. Remove "exit 0" statements
3. Reorganize dev, parm, and script directories

- [ ] Describe testing already performed for this Pull Request:</br>
I ran all global_det dev/drivers/scripts yesterday and compared the output. All output matched as exepcted.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
**Set-up**
> 1. Clone my fork and checkout branch feature/global_det_reorg
> 2. cd sorc
> 3. ./build-fix-link.sh
> 4. ./build.sh

**prep**
> 5. Run dev/drivers/scripts/prep/global_det/jevs_global_det_atmos_prep.sh (after 1400Z) and dev/drivers/scripts/prep/global_det/jevs_global_det_wave_prep.sh (after 1315Z).

**stats**
> 6. Run dev/drivers/scripts/stats/global_det/jevs_global_det_wave_gfs_grid2obs_stats.sh, dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_jma_grid2grid_stats.sh, and dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_ukmet_grid2obs_stats.sh. Point COMIN to the emc.vpppg parallel.

**plots**
> 7. Run dev/drivers/scripts/plots/global_det/jevs_global_det_wave_grid2obs_plots_31days.sh, dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_headline_plots.sh, and dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_means_plots_31days.sh. Point COMIN to the emc.vpppg parallel.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **10/13/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@malloryprow it's a bit after 14Z - OK to run prep jobs now?

**Comment by malloryprow** [comment]
Yeah! Go on ahead!

**Comment by PerryShafran-NOAA** [comment]
Also, just want to make sure, since your instructions seem to denote the old structure:  I am running drivers in dev/drivers/scripts/prep/global_det, not dev/drivers/scripts/global_det/prep as indicated in your instructions.

**Comment by malloryprow** [comment]
HAHAHA! That's my fault; copy and pasted from the last global_det PR. Will fix!

**Comment by PerryShafran-NOAA** [comment]
The prep runs are complete.

.o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr288test/EVS/dev/drivers/scripts/prep/global_det

output here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det

**Comment by malloryprow** [comment]
Yup saw they are done and started checking.

✔️ **prep is good!**

**Comment by PerryShafran-NOAA** [comment]
The stats jobs are underway.

**Comment by malloryprow** [comment]
✔️ **stats are good!**

**Comment by PerryShafran-NOAA** [comment]
I didn't even know they were done already.  So fast!  I like to check to see if I might have made an error, but I guess in this case, not.  

Shall I go ahead to plots?

**Comment by malloryprow** [comment]
I was watching the log files! I can check the logs for errors or failures, but in the mean time go ahead and start the plots.

**Comment by malloryprow** [comment]
Okay there is an error in the UKMET. It is trying to run for RH but there are no RH variables in the UKMET forecasts files. Very odd since I had put in a check in the code to make sure this doesn't run.

**Comment by PerryShafran-NOAA** [comment]
OK, then hold the plots then until you can track this down?

**Comment by malloryprow** [comment]
I think it is okay to run the plots still. We can circle back, but we can wait if that is what you would like to do.

**Comment by PerryShafran-NOAA** [comment]
OK, let's go ahead.  It'll at least give us a check of the plotting capabilities.

**Comment by PerryShafran-NOAA** [comment]
Plot jobs underway.

**Comment by malloryprow** [comment]
Bug fix is in if you want to re-run dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_ukmet_grid2obs_stats.sh after you pull in the changes.

Be sure to remove the following directories so restart doesn't kick in!
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/ukmet.20231005
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/atmos.20231005/ukmet
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/atmos.20231005/prepbufr

**Comment by malloryprow** [comment]
> Plot jobs underway.

✔️ **plots are good!**

**Comment by malloryprow** [comment]
I'm heading out for the weekend early since I was working late yesterday.

If you don't want to leave this hanging over the weekend, here is what you can do to check that all is good with the UKMET grid2obs stats run:

1. _grep "error" [new/re-run log file]_ 
2. _diff/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/ukmet.20231005/evs.stats.ukmet.atmos.grid2obs.v20231005.stat /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/global_det/ukmet.20231005/evs.stats.ukmet.atmos.grid2obs.v20231005.stat_

If both return nothing then we are good to go.

**Comment by malloryprow** [comment]
If you do go ahead with merging and it gets into the emc.vpppg parllel, don't forget to update all the global_det crontab driver scripts for the new paths!

**Comment by PerryShafran-NOAA** [comment]
OK great, I will do that!

**Comment by PerryShafran-NOAA** [comment]
Both of the above return nothing!  Thus your fixes are good and we can now merge this PR.

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Comment by malloryprow** [comment]
Woohoo! Thank you!

**Pull request merged**
