### PR TITLE
feature/global_det_atmos_stats_restart

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

This PR:

- Reworks the restart capabilities for global_det atmos stats
- Adjust memory for global_det atmos prep
- Adjust settings in global_det wave METplus configs
- Fix bug in date lengths plotted for headline plots
- Add PBL CTC stat for grid2obs
- Remove "transform_first=True" for precip spatial plots
- Use MET_NDBC_STATIONS to point to FIXevs file for NBDBC buoy locations
- Use NDBC data in prod/dcom
- Use OSI-SAF data in prod/dcom
- Remove loading of METplus in global_det_plots.sh
- Remove unused files
- Add some documentation

- [ ] Describe testing already performed for this Pull Request:</br>
I tested the restart capabilities and the branch has been running in my parallel.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- Checkout the branch (feature/global_det_atmos_restart)
- Set up
> Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_test_scripts/pr_220/evs_global_det_atmos_setup.sh. Edit if needed (set location of EVSclone). Run.

- Testing prep
> Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_test_scripts/pr_220/run_evs_global_det_atmos_prep.sh. Edit if needed (set location of EVSclone). Run.

- Testing stats restart
> In checkout of dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_gfs_grid2obs_stats.sh, point COMIN to /lfs/h2/emc/vpppg/noscrub/mallory.row/evs/v1.0. Change walltime to 00:30:00.
> Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_test_scripts/pr_220/run_evs_global_det_atmos_stats.sh. Edit if needed (set location of EVSclone). Run. The job will exceeded the wallclock with this run.
> In checkout of dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_gfs_grid2obs_stats.sh, change walltime to back to 01:30:00, and submit jevs_global_det_atmos_gfs_grid2obs_stats.sh.

- Testing plots
> In checkout of dev/drivers/scripts/global_det/plots/jevs_global_det_atmos_grid2grid_precip_plots_31days.sh, point COMIN to /lfs/h2/emc/vpppg/noscrub/mallory.row/evs/v1.0.
> In checkout of dev/drivers/scripts/global_det/plots/jevs_global_det_atmos_headline_plots.sh, point COMIN to /lfs/h2/emc/vpppg/noscrub/mallory.row/evs/v1.0.
> Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_test_scripts/pr_220/run_evs_global_det_atmos_plots.sh. Edit if needed (set location of EVSclone). Run.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **09/15/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
Thank you for submitting this PR, @malloryprow! It makes many of critical updates to global_det. One quick question. Does this PR also update the GFS wave scripts to point to the new NDBC buoy look-up table in FIXevs?

**Comment by malloryprow** [comment]
Oh yes, it does. Forgot about that. Let me add it in the description real quick.

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow Any chance that you can remove run.ver.metplus5.0.0 and run.ver.metplus4.1.4 in this PR instead of waiting for the next PR? Thanks for considering!

**Comment by malloryprow** [comment]
Done!

**Comment by ShelleyMelchior-NOAA** [comment]
We will get to this PR soon!

**Comment by malloryprow** [comment]
Thinking about this PR this morning...I had the prep step in the code testing so as to make sure that the OSI-SAF data is coming from the prod location. Should we wait until the GHRSST is also in prod? Then I can update the default COMINghrsst path to the dcom prod location in this PR.

**Comment by ShelleyMelchior-NOAA** [comment]
Sure ... that is not a bad idea. I know @PerryShafran-NOAA intended to get onto this PR today after getting the subseasonal restart PR rolling. That might work well w/ the timeline you are proposing anyway. I forget, when is GHRSST slated for prod?

**Comment by malloryprow** [comment]
Tomorrow!

**Comment by ShelleyMelchior-NOAA** [comment]
Perfect!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I see you have made a few changes other than just bringing in develop.  Are we ready to do the test of this PR?  

Perry

**Comment by malloryprow** [comment]
I was going to wait to update the GHRSST path to the new prod location. But I could do that in another PR if we just want to get a move on with this one.

**Comment by PerryShafran-NOAA** [comment]
It's up to you.  Let me know when you want to give me the go ahead to test.  If ghrsst is moved to prod while we're testing, we can add it to this PR.

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow @PerryShafran-NOAA The validation dataset spreadsheet says that Day 1 of the GHRSST move to /prod/dcom is complete! I just don't know which machine they do on Day 1!

https://docs.google.com/spreadsheets/d/1JuzUtKvey0hFMiQIuEYK4hZMS9jpj5vDmosmg7QO_X8/edit#gid=0

**Comment by malloryprow** [comment]
I see /lfs/h1/ops/prod/dcom/20230906/validation_data/marine/ghrsst on Cactus but not Dogwood.

**Comment by AliciaBentley-NOAA** [comment]
And which is dev right now? Hahaha

**Comment by malloryprow** [comment]
Dogwood!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow So, should I do a test or would you prefer that I wait?

Perry

**Comment by malloryprow** [comment]
We could to the stats and plots test. Then once we see the data on Dogwood go back and do prep. COMIN will point to my stuff. How's that sound?

**Comment by PerryShafran-NOAA** [comment]
OK, sounds good! 

Perry

**Comment by PerryShafran-NOAA** [comment]
The stats job is running.  I want to note that your driver script that you pointed me to is not set up for the current dev/drivers/scripts setup and neither is the file to be submitted (should be jevs_global_det_atmos_gfs_grid2obs_stats.sh, not the old filename indicated.  You might want to be sure those files are correct.

**Comment by malloryprow** [comment]
Ah sorry!

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow Thank you for making the changes in the EE2 document, Mallory! They look good to me and all are now checked off the list.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I had to start again your stats job now, because I hadn't realized that I had already had a global_det linked to your directory from a previous run.  Usually your driver scripts delete that, but I guess I had forgotten.  Trying another run here.

**Comment by malloryprow** [comment]
Did you point COMIN to /lfs/h2/emc/vpppg/noscrub/mallory.row/evs/v1.0? If you did, then it shouldn't have mattered.

**Comment by PerryShafran-NOAA** [comment]
I think I did, but I'm referring to the stats directory, not prep.

Perry

**Comment by PerryShafran-NOAA** [comment]
OK, your use of $COMROOT kind of hosed me, but I think I got it all straightened out.

**Comment by malloryprow** [comment]
Let me know if you need me to look over anything for the set up. Not one of my better instructed PRs.

**Comment by PerryShafran-NOAA** [comment]
OK, the first 30-minute run is complete.  I have started the second run with the regular wallclock time of 1:30.

In the meantime here is the output file:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_gfs_grid2obs_stats_00.o96251159

and the output directory: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det

Perry

**Comment by malloryprow** [comment]
👍 I see "=>> PBS: job killed: walltime 1816 exceeded limit 1800" in /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_gfs_grid2obs_stats_00.o96251159.

Also seeing output in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/atmos.20230907, and no final stat file in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/gfs.20230907! Results for the first run look good.

**Comment by malloryprow** [comment]
Second run looking good so far...

In /lfs/h2/emc/stmp/perry.shafran/evs_test/dev/tmp/jevs_global_det_atmos_gfs_grid2obs_stats_00.96254469.dbqs01/grid2obs_stats/METplus_output/logs there are only the "generate_stats" logs. None of the jobs prior to the "generate_stats" portion ran because the output files existed from the first run!

**Comment by malloryprow** [comment]
✅ /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/gfs.20230907/./evs.stats.gfs.atmos.grid2obs.v20230907.stat looks good! Output matches my output from today's run.

**Comment by PerryShafran-NOAA** [comment]
Super!  OK, can we work on prep yet?  Or do we still need to wait for data to be in the prod area of dcom?  Looking at /lfs/h1/ops/prod/dcom/20230907/validation_data/marine, I don't see ghrsst there today.  

I guess I'll move on to plots?

Perry

**Comment by malloryprow** [comment]
Yeahhhhh, still not there. I emailed because the dev/dcom is there but not prod/dcom.

So we can move onto plots.

**Comment by PerryShafran-NOAA** [comment]
Test is underway!

**Comment by PerryShafran-NOAA** [comment]
Plot jobs have finished:

See /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/dev/drivers/scripts/global_det/plots, the .o files there.

I do want to note the following issue in the grid2grid precip 31day plot job:

```
ERROR: METPLUS_PATH not set in environment, review modules loaded in global_det_atmos_load_modules.sh
1 + status=1
1 + [[ 1 -ne 0 ]]
1 + exit 1
2 + export err=1
2 + err=1
2 + err_chk
```

The headline plot job seems to have finished though.  

What might the problem be for the the grid2grid precip plot job?

Perry

**Comment by malloryprow** [comment]
✅ /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/headline.20230907/evs.plots.global_det.atmos.headline.v20230907.tar is good!

There was a problem with the removal of the loading METplus from the global_det_plots.sh modulefile. I have put it back and pushed the changes. Please re-run jevs_global_det_atmos_grid2grid_precip_plots_31days.sh.

**Comment by malloryprow** [comment]
"=>> PBS: job killed: walltime 1207 exceeded limit 1200" .... Dogwood is maxxed out on nodes right now but the job didn't seem like it was running slow? Maybe the module loading was? I didn't catch that part. Should I increase the walltime?

**Comment by PerryShafran-NOAA** [comment]
Maybe increasing the wall time is a good idea?  I can do that and re-submit.

Perry

**Comment by malloryprow** [comment]
Also, GHRSST is finally in place!

**Comment by PerryShafran-NOAA** [comment]
I added 1 hr to the wallclock time and re-submitted.

Also, if you'd like, we can now do prep, which can be run alongside this plot job.

Perry

**Comment by malloryprow** [comment]
Yeah, sounds good to me! Executables have been built?

Would be great to get this merged before the weekend!

**Comment by PerryShafran-NOAA** [comment]
Yes, I think I did build the executables.

Let's see if we can run this.

Perry

**Comment by malloryprow** [comment]
Prep is done. Did you pull in the changes I made to JEVS_GLOBAL_DET_PREP? It pulled the GHRSST files from /lfs/h1/ops/dev/dcom/20230906/validation_data/marine/ghrsst/20230906_OSPO_L4_GHRSST.nc. It should be Copying /lfs/h1/ops/prod/dcom/20230906/validation_data/marine/ghrsst/20230906_OSPO_L4_GHRSST.nc. It did pull the OSI-SAF from prod/dcom.

If you delete /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det/atmos.20230907/ghrsst_ospo/ghrsst_ospo.2023090600to2023090700.nc and re-run it will just do the prep for GHRSST.

**Comment by PerryShafran-NOAA** [comment]
I think I pulled it in.  I just pulled stuff in and only the J-Job was updated; maybe that's the change?

I'll re-run the prep job.

Perry

**Comment by malloryprow** [comment]
✅  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230907/./evs.plots.global_det.atmos.grid2g
rid_precip.last31days.v20230907.tar is good!

I may increase the walltime on those jobs. It timing out has me a little paranoid now.

**Comment by PerryShafran-NOAA** [comment]
OK, then, plots is now fully validated along with stats.  

Perry

**Comment by malloryprow** [comment]
Something still isn't right with the GHRSST prep.

I need to head out for the weekend though.

**Comment by malloryprow** [comment]
I'm looking at the log from my personal run that just finished. It grabbed the right file.

Copying /lfs/h1/ops/prod/dcom/20230907/validation_data/marine/ghrsst/20230907_OSPO_L4_GHRSST.nc to /lfs/h2/emc/stmp/mallory.row/evs_test/dev/tmp/jevs_global_det_atmos_prep_00.96329391.dbqs01/atmos.20230907_OSPO_L4_GHRSST.nc

However, I did see the missing mail email in my inbox from your run yesterday.

**Comment by AliciaBentley-NOAA** [comment]
Hi everyone. Hopefully this can be sorted out and this PR can be merged
soon! I think it's nearly there. Thanks!
.
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by malloryprow** [comment]
If we could get this knocked out this morning that be great!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow - OK - is there anything else you need to do from your end?  Or my end?  It looks like you said that the prep step worked as expected last Friday, so maybe I can merge now?  Or does it need another test?

Perry

**Comment by malloryprow** [comment]
I'd like you to run it one more time. I'm a little confused why your second run on Friday afternoon look correct.

**Comment by malloryprow** [comment]
The most recent merges have been pulled into your branch right?

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Good question. I'm not sure we've had a clean test of this yet! If we can do a quick test of GHRSST in prep in its new /prod/dcom location and prove that it works for you, I think then this would be ready to merge. Thanks!

**Comment by PerryShafran-NOAA** [comment]
I'll double check to see if my code is fully updated, then run the prep job now.

Perry

**Comment by malloryprow** [comment]
:heavy_check_mark: Okay prep is good

"Copying /lfs/h1/ops/prod/dcom/20230909/validation_data/marine/ghrsst/20230909_OSPO_L4_GHRSST.nc to /lfs/h2/emc/stmp/perry.shafran/evs_test/dev/tmp/jevs_global_det_atmos_prep_00.96471283.dbqs01/atmos.20230909_OSPO_L4_GHRSST.nc"

**Comment by AliciaBentley-NOAA** [comment]
Thanks, all! I think this one is ready to go!

**Comment by PerryShafran-NOAA** [comment]
OK, thanks!  Will do a quick code review and then merge in!

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
