### PR TITLE
bugfix/mem _increase

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

The GFS grid2grid atmos stats jobs log has been showing memory exceeded in the log. This adds more memory in the dev driver script and ecf script.

- [ ] Describe testing already performed for this Pull Request:</br>

> None

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **No**

- [ ] Do these updates/additions include sufficient testing updates? **No**

- [ ] Please complete this pull request review by **06/14/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow I have no issue with making the small changes in this PR in the bugfix release! I'll put it in the release notes as a resource change. Thanks!

CC @PerryShafran-NOAA @ShelleyMelchior-NOAA

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I am beginning work on your PR now.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Please take a look at the output.

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr488test/EVS/dev/drivers/scripts/stats/global_det

And the stats directories are here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v2.0/stats/global_det, the 20240604 directories.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA You ran jevs_global_det_atmos_gfs_grid2obs_stats.sh instead of jevs_global_det_atmos_gfs_grid2grid_stats.sh. The changes are for jevs_global_det_atmos_gfs_grid2grid_stats.sh.

**Comment by PerryShafran-NOAA** [comment]
Oh darn.  Oops!  Thanks for pointing that out to me.  Let me try it again.

**Comment by malloryprow** [comment]
Job is done! No more memory exceeded errors.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Thanks for checking!  Since this is a bugfix PR, we will repeat the test with the current met/metplus production versions.

**Comment by malloryprow** [comment]
Could we point /lfs/h1/ops/prod/com/$NET/$evs_ver_2d for COMIN for the curren met/metplus production version test?

**Comment by PerryShafran-NOAA** [comment]
Yes, will do!

**Comment by malloryprow** [comment]
Looks good for the test with the current production versions of MET and METplus!

**Comment by PerryShafran-NOAA** [comment]
Thanks for your eagle-eye checking!!  Let me check the code and then we'll be all set.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
