### PR TITLE
Feature/naefsv7 verbosity

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

This branch started from work @ShelleyMelchior-NOAA did. It started as work to update EVS to support NAEFS v7, but quickly included changes for adding SENCDOM, removing FIXevs, removal of verbosity settings, and updating maillist. Since the work for NAEFS v7 was done in https://github.com/NOAA-EMC/EVS/pull/240 (with updates in https://github.com/NOAA-EMC/EVS/pull/246). This PR now contains changes for  adding SENCDOM, removing FIXevs, removal of verbosity settings, and updating maillist.

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> The changes touch the driver scripts of all global_ens steps but I don't think we have time to test all the steps? Just test prep?

- [ ] Has the code been checked to ensure that no errors occur during the execution? **No**

- [ ] Do these updates/additions include sufficient testing updates? **No**

- [ ] Please complete this pull request review by **09/19/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
I have brought in this branch and am working it now.  I submitted the jevs_global_ens_atmos_prep.sh job.  Let me know if there are other prep jobs you'd like me to run.

**Comment by ShelleyMelchior-NOAA** [comment]
The global_ens_atmos_prep will take ~4 hours. I suggest running another prep step w/ a shorter walltime also.

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA @PerryShafran-NOAA I think it would be appropriate to test all of the scripts that were changed in this PR. Is that possible?

**Comment by ShelleyMelchior-NOAA** [comment]
There are too  many, @AliciaBentley-NOAA , but I think a good compromise is something from all 3 types. So test the prep as you are doing, then pick a stats process and plots process that point to emc.vpppg prep and stats data.

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA anything's possible.  :)

Just let me know what needs to be done.  I am running the naefs prep job, as that one is faster.  

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
> There are too many, @AliciaBentley-NOAA , but I think a good compromise is something from all 3 types. So test the prep as you are doing, then pick a stats process and plots process that point to emc.vpppg prep and stats data.

Anything is indeed possible. But given the time constraint, testing all global_ens prep, stats, and plots, will take too long. All drivers for all 3 steps were changed.

**Comment by AliciaBentley-NOAA** [comment]
@StevenSimon-NOAA We aren't going to be able to test all of these small changes for global_ens. Can you please continue to make a point of monitoring the emc.vpppg parallel and pointing out to us when images stop updating or start to look funny? Especially after this PR is merged? Thanks.

**Comment by StevenSimon-NOAA** [comment]
> @StevenSimon-NOAA We aren't going to be able to test all of these small changes for global_ens. Can you please continue to make a point of monitoring the emc.vpppg parallel and pointing out to us when images stop updating or start to look funny? Especially after this PR is merged? Thanks.

Sure thing! Mallory has already set up a Google Doc which tracks several issues within the global_ens component that will need to be debugged in the coming days and weeks. I have already appended several plotting issues to that list.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow @StevenSimon-NOAA The naefs prep job is complete.  

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr250test/EVS/dev/drivers/scripts/global_ens/prep/jevs_global_ens_naefs_atmos_prep.o82240435

The prep directory is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230916

Please note that the general global_ens prep script is running now also, but please do please check the output for the naefs output.  

Thanks!

Perry

**Comment by StevenSimon-NOAA** [comment]
> @malloryprow @StevenSimon-NOAA The naefs prep job is complete.
> 
> The .o file is here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr250test/EVS/dev/drivers/scripts/global_ens/prep/jevs_global_ens_naefs_atmos_prep.o82240435
> 
> The prep directory is here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230916
> 
> Please note that the general global_ens prep script is running now also, but please do please check the output for the naefs output.
> 
> Thanks!
> 
> Perry

The prep file quantities in the cmce_bc and gefs_bc subdirectories appear to check out.

**Comment by PerryShafran-NOAA** [comment]
Excellent, thanks!  @StevenSimon-NOAA !

OK, the next question is @ShelleyMelchior-NOAA @malloryprow :

- Should I forget about the global_ens prep job and move onto stats now?  I would use the emc.vpppg prep directory to be used in this test.  And which stats jobs should I be running? 

Once I have this guidance, I'll move on to the next step.

**Comment by ShelleyMelchior-NOAA** [comment]
@PerryShafran-NOAA , keep it running. And in the meantime, pick a stats process using the emc.vppg prep. Any stats processing will do. I suggest one w/ smaller walltime.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow @ShelleyMelchior-NOAA @StevenSimon-NOAA I ran the gefs sst stats job, and that one was pretty quick.  Please validate for me:

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr250test/EVS/dev/drivers/scripts/global_ens/stats/jevs_global_ens_gefs_atmos_sst_stats.o82244115

The output file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens/gefs.20230916

Let me  know if you wish to see more stats jobs being tested.

**Comment by StevenSimon-NOAA** [comment]
> @malloryprow @ShelleyMelchior-NOAA @StevenSimon-NOAA I ran the gefs sst stats job, and that one was pretty quick. Please validate for me:
> 
> The .o file is here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr250test/EVS/dev/drivers/scripts/global_ens/stats/jevs_global_ens_gefs_atmos_sst_stats.o82244115
> 
> The output file is here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens/gefs.20230916
> 
> Let me know if you wish to see more stats jobs being tested.

It appears that the global_ens sst stats job ran to completion with no errors and that all related sst stats files are all accounted for in the stats COMOUT.

**Comment by ShelleyMelchior-NOAA** [comment]
Great! Thanks for validating, @StevenSimon-NOAA .
@PerryShafran-NOAA , pick a lower walltime plots next.

**Comment by malloryprow** [comment]
Thanks @StevenSimon-NOAA for checking and confirming the prep and stats!

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA @AliciaBentley-NOAA @malloryprow @StevenSimon-NOAA To update this:  Lin found that there was an error with a missing library ncea, that is part of the nco load.  global_ens did not have a module load nco in the modulefile.  Thus, I asked Mallory to include the module load and I am testing this to see if that error is gone.  That test is now being run.

**Comment by malloryprow** [comment]
All right so upon further review, the 'ncea' is used to average files to create a weekly average for sea-ice files. However, GEFS is not doing weekly averages for sea-ice verification, so this whole section of the code can be removed.

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow @PerryShafran-NOAA Thanks for looking into this! Should we keep the [module load nco line](https://github.com/NOAA-EMC/EVS/commit/6f92cd19d21f18440fb9f08e0314e613b413226b#diff-eeb6593b24ba3c369d23a68263cbb1c7eff11c43fbfab98770a29a7ec3a51669L19)? I see it was removed in the last edit and just wanted to double check. Thanks!

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA Mallory said it was not necessary, so it was removed as it is not used for anything else in the system.

@malloryprow - cancelled previous test and am re-running the test with updates.

**Comment by malloryprow** [comment]
It doesn't seem we need it anymore. The chunk of code that used it I deleted and no sense of loading a module that won't get used (just like it doesn't make sense to make a file that will never get used)!

**Comment by malloryprow** [comment]
I know the job is still running but the sea ice part looks good

Working in: /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_global_ens_atmos_prep.82307815.cbqs01
---- Prepping data for osi_saf for init 20230917
----> Trying to create /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_global_ens_atmos_prep.82307815.cbqs01/atmos.20230917/osi_saf/osi_saf.multi.2023091600to2023091700_G004.nc and /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_global_ens_atmos_prep.82307815.cbqs01/atmos.20230917/osi_saf/osi_saf.multi.2023091000to2023091700_G004.nc
Running  /apps/prod/hpc-stack/intel-19.1.3.304/cdo/1.9.8/bin/cdo remapbil,/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr250test/EVS/fix/cdo_grids/G004.grid /lfs/h1/ops/dev/dcom/20230916/seaice/osisaf/ice_conc_nh_polstere-100_multi_202309161200.nc /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_global_ens_atmos_prep.82307815.cbqs01/atmos.osi_saf.multi.nh.2023091600to2023091700_G004.nc
Running  /apps/prod/hpc-stack/intel-19.1.3.304/cdo/1.9.8/bin/cdo remapbil,/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr250test/EVS/fix/cdo_grids/G004.grid /lfs/h1/ops/dev/dcom/20230916/seaice/osisaf/ice_conc_sh_polstere-100_multi_202309161200.nc /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_global_ens_atmos_prep.82307815.cbqs01/atmos.osi_saf.multi.sh.2023091600to2023091700_G004.nc
Copying /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_global_ens_atmos_prep.82307815.cbqs01/atmos.osi_saf.multi.2023091600to2023091700_G004.nc to /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_global_ens_atmos_prep.82307815.cbqs01/atmos.20230917/osi_saf/osi_saf.multi.2023091600to2023091700_G004.nc
END: global_det_sea_ice_prep.py
 [[ -n YES=YES ]]
 cp /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_global_ens_atmos_prep.82307815.cbqs01/atmos.20230917/osi_saf/osi_saf.multi.2023091600to2023091700_G004.nc /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230917/osi_saf/.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I'm not entirely sure that I'd need to run the rest of the prep job; is this the only place in the code where this was an issue before?  

I see all the various COMINs were defined cleanly, so why not just kill this job and move on to plots, since I don't think that has been validated yet?

Perry

**Comment by malloryprow** [comment]
Works for me!

**Comment by PerryShafran-NOAA** [comment]
I am going to run the jevs_global_ens_naefs_atmos_grid2obs_stats job to see if it is producing errors.  Seems to be having errors in the parallel.  I need to find out the genesis of this error.

**Comment by StevenSimon-NOAA** [comment]
I would also check out the naefs g2g stats and naefs precip stats logs. It appears that they have the same issues.  There are a handful of other global_ens stats logs with these issues as well (not just naefs).

**Comment by PerryShafran-NOAA** [comment]
I found the source of the problem.  There are missing files in the prep emc.vpppg archive, because they were pointing to NAEFS files that don't exist.  That was causing errors in the ensuing stats job.

However, in the current parallel, those files are now there, as the last fix was put into the parallel yesterday.  

@malloryprow Is this a good explanation?  Do we need further fixes here?

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA asked for a backfill of the missing files for when we pointed to Bo's parallel instead of the NCO parallel.  That backfill is complete.  However, there will still be failures because the current stats code now looks for 30 members, but going back in the prep, there are only 20 members from before we upgraded to NAEFS v7.  Unless someone has a backfill of prep data going back 16 days, I'm not sure what else I can do.  

I'm going to move on to doing a plot job and asking for validation and then we'll merge this PR.  

@malloryprow @StevenSimon-NOAA

**Comment by ShelleyMelchior-NOAA** [comment]
I am running `jevs_global_ens_atmos_naefs_precip_past31days_plots.sh` so Perry can move onto PR #251 .
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_ens_atmos_naefs_precip_past31days_plots.o82323287`
I see valid_time is set to both!

**Comment by malloryprow** [comment]
Yes, I did. It seemed like valid_time=separate was the exception. I would assume or hope it would have been set in the driver script to separate where it was needed.

**Comment by PerryShafran-NOAA** [comment]
Do we need to set these in the driver scripts?  The issue is that they are not for several of the naefs scripts (and maybe a few others).

**Comment by ShelleyMelchior-NOAA** [comment]
It is set in the drivers, and almost always to both. There are just a few that are set to separate in the drivers.
```
$ grep valid_time *
jevs_global_ens_atmos_gefs_grid2grid_past31days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_grid2grid_past90days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_grid2obs_past31days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_grid2obs_past31days_separate_plots.sh:export valid_time=separate
jevs_global_ens_atmos_gefs_grid2obs_past90days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_grid2obs_past90days_separate_plots.sh:export valid_time=separate
jevs_global_ens_atmos_gefs_profile1_past31days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_profile1_past90days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_profile2_past31days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_profile2_past90days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_profile3_past31days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_profile3_past90days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_profile4_past31days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_profile4_past90days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_sea_ice_past31days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_sea_ice_past90days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_sst_past31days_plots.sh:export valid_time=both
jevs_global_ens_atmos_gefs_sst_past90days_plots.sh:export valid_time=both
jevs_global_ens_atmos_naefs_grid2grid_past31days_plots.sh:export valid_time=both
jevs_global_ens_atmos_naefs_grid2grid_past90days_plots.sh:export valid_time=both
jevs_global_ens_atmos_naefs_grid2obs_past31days_plots.sh:export valid_time=both
jevs_global_ens_atmos_naefs_grid2obs_past90days_plots.sh:export valid_time=both
```

**Comment by PerryShafran-NOAA** [comment]
It is not set in *all* the drivers.  Please note that naefs_precip is not in the list.  This is why Lin had seen that error in his run of this particular plot file.

**Comment by ShelleyMelchior-NOAA** [comment]
I see the oversight. OK. Shall I add it to the missing drivers?
```
$ grep -L valid_time= *                                                                        
jevs_global_ens_atmos_gefs_precip_past31days_plots.sh
jevs_global_ens_atmos_gefs_precip_past90days_plots.sh
jevs_global_ens_atmos_gefs_precip_spatial_plots.sh
jevs_global_ens_atmos_gefs_snowfall_past31days_plots.sh
jevs_global_ens_atmos_gefs_snowfall_past90days_plots.sh
jevs_global_ens_atmos_naefs_precip_past31days_plots.sh
jevs_global_ens_atmos_naefs_precip_past90days_plots.sh
jevs_global_ens_headline_gefs_grid2grid_plots.sh
jevs_global_ens_wave_grid2obs_plots.sh
```

**Comment by PerryShafran-NOAA** [comment]
For consistency, they probably should be.

**Comment by ShelleyMelchior-NOAA** [comment]
Meanwhile, the neafs precip past 31 days plot has finished.
```
$ ll /lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/global_ens/atmos.20230917
total 73300
-rw-r--r-- 1 shelley.melchior emc 75059200 Sep 19 18:48 evs.plots.global_ens.atmos.naefs.precip.past31days.v20230917.tar
```

**Comment by malloryprow** [comment]
You don't need to since the addition I added in the J-JOB wil catch it. Similar to the setting of COMIN or COMOUT. It can be set in the driver, but if it is not the J-JOB will set valid_time="both".

**Comment by malloryprow** [comment]
export valid_time=${valid_time:-both}

**Comment by PerryShafran-NOAA** [comment]
Fair enough.

**Comment by malloryprow** [comment]
:heavy_check_mark: /lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/global_ens/atmos.20230917/evs.plots.global_ens.atmos.naefs.precip.past31days.v20230917.tar looks good!

**Comment by malloryprow** [comment]
@ShelleyMelchior-NOAA @PerryShafran-NOAA Would you like me to add valid_time to the driver scripts that are missing it?

**Comment by ShelleyMelchior-NOAA** [comment]
I agree w/ you that it isn't necessary, @malloryprow .

**Comment by ShelleyMelchior-NOAA** [comment]
@StevenSimon-NOAA , @PerryShafran-NOAA , @malloryprow  -- I think we need to get this PR merged so that global_ens is static for Lin. He seems to be insistent on pushing along w/ the ecflow for global_ens, so let's get this moving piece static from our end and be sure he is using the same code. Then we can start from the same baseline to assess any continued errors.

**Comment by malloryprow** [comment]
I think this one is good to go. Unless anyone has objections???

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All tests perform as expected related to the code cleanup for EE2. There are some lingering errors, but they are related to the data gap when moving from a NAEFSv7 developer parallel to the NCO parallel. This PR is ready for merge.

**Pull request merged**
