### PR TITLE
feature/global_det_atmos_config_fhr_list

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

Add EVS configuration setting option to define a list of forecast hour rather than forecast hour min, max, and increment.

- [ ] Describe testing already performed for this Pull Request:</br>

> Tested and compared output to parallels (mine and emc.vpppg)

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> Checkout the branch
>Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_test_scripts/pr_139/evs_global_det_atmos_setup.sh. This script will link the fix files and my stat files.
>Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_test_scripts/pr_139/run_evs_global_det_atmos_plots.sh. Run it.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **07/15/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by malloryprow** [comment]
I know this hasn't been picked up yet but wanted to note with this comment to NOT pick it up until I can get the new changes cleaned up and worked out. I'll comment again when it is good to go!

**Comment by PerryShafran-NOAA** [comment]
Hi, @malloryprow ,

I haven't heard any comments that this is good to go, but I do see the Make driver script changes change to this PR.  Are we ready to test, or is still more coming?

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA More still coming. I'm working on testing the plots driver changes right now.

I'd also like to wait to get this in until the changes for machine.conf get merged in. I'll need to make some changes to some other scripts that use the related environment variables that are being removed.

**Comment by PerryShafran-NOAA** [comment]
Sounds good.

Thanks!

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
PR #147 is ready for review test run results from either @PerryShafran-NOAA or @malloryprow

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Now that machine.conf is in, are we ready to review this PR?

Perry

**Comment by malloryprow** [comment]
Okay I got the changes done and tested for the driver scripts. I got the changes related to machine.conf in as well, though I haven't tested them. 

After the production switch tomorrow, we can go ahead and test this PR.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Yes good to test.

**Comment by PerryShafran-NOAA** [comment]
Please note that I had to change your test script to comply with the new /dev/drivers/scripts format.  It was written in the old ecf format.  

Perry

**Comment by PerryShafran-NOAA** [comment]
The runs are complete.

The .o files are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/dev/drivers/scripts/global_det/plots
The plot tar files are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230705

Please validate the results.

Thanks!

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Ah, sorry about the test scripts. I will remember to update them for the next PR.

✅  Everything looks good!

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
