### PR TITLE
Feature/nfcens modulefiles

### PR DESCRIPTION
**Pull request by ShelleyMelchior-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
**The prep, stats, and plots drivers were all tested in interactive runs. Tests ran to completion and produced the expected results.**

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
**Submit the prep, stats, and plots drivers interactively.
Change settings for HOMEevs and COMIN as needed. I adjusted COMIN in the stats and plots processing to use the emc.vpppg prep and stats files.**

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Starting work on this PR.

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Shelley,

You have a problem somewhere.  Somehow data was written here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0.20230725/nfcens/grid2obs  

rather than here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/nfcens/nfcens.20230725/grid2obs

I'm not sure where you did that but let me check.

Perry

**Comment by PerryShafran-NOAA** [comment]
OK, since COMOUT was written in the driver script:

export COMOUT=/lfs/h2/emc/vpppg/noscrub/$USER/${NET}/${evs_ver}

Then in the jobs file you have the following lines:

export COMOUT=${COMOUT:-$(compath.py -o $NET/$evs_ver/$STEP/$COMPONENT/$RUN)}
export ARCmodel=${COMOUT}.${INITDATE}/${MODELNAME}/${VERIF_CASE}

mkdir -p ${COMOUT}.${INITDATE}/${MODELNAME}/${VERIF_CASE}

And thus our problem.  

Somehow we just need to fix COMOUT (and I think you have COMOUT exactly what it should be) and expand the variable for ARCmodel and the mkdir command.

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
To work w/ the J-jobs, I think my COMOUT in my driver needs to extend longer. 
From
`export COMOUT=/lfs/h2/emc/vpppg/noscrub/$USER/${NET}/${evs_ver}`
to
`export COMOUT=/lfs/h2/emc/vpppg/noscrub/$USER/${NET}/${evs_ver}/$STEP/$COMPONENT/$RUN`

OR

Keep COMOUT in my driver as is, and shorten the COMOUT in the J-jobs and expand ARCmodel and the  mkdir command.

Which do you think is more correct?

**Comment by PerryShafran-NOAA** [comment]
In an effort to be consistent across EVS, I feel that COMOUT for everyone needs to stop at $evs_ver.  I believe that EE2 dictates that.  Everything else can be expanded from that.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Looks like we're good for a re-test?  

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
Now the code is ready for a re-test!

**Comment by PerryShafran-NOAA** [comment]
Running prep again today.  I ran last night but didn't check, but will need to run the whole nfcens suite anyway.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Shelley,

I am looking at the output directory /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/nfcens/wave.20230726/nfcens/grid2obs, and there are the grib2 files, but I don't see the 5 .nc files that should be there.  

The .o file says that they were successfully created:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr175test/EVS/dev/drivers/scripts/nfcens/prep/jevs_nfcens_grid2obs_prep.o73144337:

```
 completed cleanly
 Found 5 /lfs/h2/emc/stmp/perry.shafran/evs_output/jevs_nfcens_grid2obs_prep.73144337.cbqs01/ncfiles/gdas.nc files for 20230726
```

So I look in the directory 

/lfs/h2/emc/stmp/perry.shafran/evs_output/jevs_nfcens_grid2obs_prep.73144337.cbqs01

And see in the errfile.75177:
`cp /lfs/h2/emc/stmp/perry.shafran/evs_output/jevs_nfcens_grid2obs_prep.73144337.cbqs01/ncfiles/gdas.2023072600.nc /lfs/h2/emc/stmp/perry.shafran/evs_output/jevs_nfcens_grid2obs_prep.73144337.cbqs01/ncfiles/gdas.2023072606.nc /lfs/h2/emc/stmp/perry.shafran/evs_output/jevs_nfcens_grid2obs_prep.73144337.cbqs01/ncfiles/gdas.2023072612.nc /lfs/h2/emc/stmp/perry.shafran/evs_output/jevs_nfcens_grid2obs_prep.73144337.cbqs01/ncfiles/gdas.2023072618.nc /lfs/h2/emc/stmp/perry.shafran/evs_output/jevs_nfcens_grid2obs_prep.73144337.cbqs01/ncfiles/gdas.2023072700.nc /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0.20230726/nfcens/grid2obs/.' was not successful. RETURN CODE 0`


This directory name /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0.20230726 still is written here.  Here's why:

Go to scripts/nfcens/prep and look at the prep file:

`cpreq ${DATA}/ncfiles/gdas*nc ${COMOUT}.${INITDATE}/${MODELNAME}/${VERIF_CASE}/.`

You need to fix this line in the prep file.

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks, Perry! I have made the suggested change. I have also included `run.ver` in this PR. There was an erroneous change to this file introduced by a recent PR merge. I removed 2 lines for met and metplus that should not be there. They are listed further down where they should be.

**Comment by PerryShafran-NOAA** [comment]
New prep run underway.

Perry

**Comment by PerryShafran-NOAA** [comment]
Success!  I saw the 5 gdas*.nc files in the output directory:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/nfcens/wave.20230726/nfcens/grid2obs

Now to do the stats job.  

Perry

**Comment by PerryShafran-NOAA** [comment]
The stats job was fast.  I'm seeing a stat file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/nfcens/nfcens.20230726

Is this the correct size of the stat file that you have?

It is identical to the stat file in the emc.vpppg run, so that's good.

On to plots?

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
Yes, my final stats file from the previous day is of comparable size. Mine is identical to emc.vpppg for the same date.

On to plots!

**Comment by PerryShafran-NOAA** [comment]
Plots is done.  My plots tar file is actually larger than the emc.vpppg plots tar file, but I didn't look at individual plot files or plots to know what the issue was.  They are of the same order of magnitude though.  See /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/nfcens/wave.20230726.  I'm not sure it makes much of a different; always depends on how much data went into it.  I copied stats files rather than use the emc.vpppg archive.  Anyway, I'd be good with merging this in if you are.  

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
I am satisfied. 
Related: Samira is working on the NFCENS website and will be able to notice if there any problems with the graphics in terms of filenames. I have untarred the files and copied them to rzdm for her to use as her example in building the website.

**Comment by PerryShafran-NOAA** [comment]
OK...this is your PR, so I guess I do code review and merge.  I'll do that after my 3pm meeting.

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
