### PR TITLE
Updating EVS components with correct task geometry

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by malloryprow** [comment]
What is the logic for dev/drivers/scripts/plots/global_det/jevs_global_det_wave_grid2obs_plots_90days.sh dev/drivers/scripts/plots/global_det/jevs_global_det_wave_grid2obs_plots_31days.sh? What about dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2obs_sfc_plots_90days.sh and not dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2obs_sfc_plots_31days.sh?

**Comment by PerryShafran-NOAA** [comment]
@malloryprow This is not a completed PR.  There's lots more work to come here.  The basic idea is that we are ensuring that the task geometry works for components identified by Wei as ones that have a ncpu exceedance in their testing.  See number 23 on Wei's document.  

When it's finished, this PR will address issues 22, 23, and 46 on that doc.  This PR will continue to be updated until finished.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Thank you for putting this PR together! Please make sure that the changes you've made in the /dev/drivers/scripts make their way into the corresponding .ecf scripts for Wei to use before this PR is ultimately merged. Thanks!

**Comment by PerryShafran-NOAA** [comment]
Thank you!  The plan is to get everything set in /dev/drivers, and then once all that is squared away, transfer everything over to ecf.  At that point I'll write the instructions for testing above and we can get to work testing and merging this.

**Comment by AliciaBentley-NOAA** [comment]
Thank you for making those two EE2 corrections and one bugfix, @PerryShafran-NOAA!

CC @ShelleyMelchior-NOAA for awareness. EE2 checklist and Wei's document point to these changes.

**Comment by AliciaBentley-NOAA** [comment]
Also adding this comment for @PerryShafran-NOAA here, so it doesn't get lost in the shuffle:
https://github.com/NOAA-EMC/EVS/commit/2dfa7e0e8b4729fda163c5bd2db23d638877afba#r136500995

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA @ShelleyMelchior-NOAA As previously discussed, I am going to close this PR and soon open a new one related to this using Wei's suggested fix from last week.  

Just to review, the reason why I am doing this is that this PR features fixes that were created using the helpdesk's suggested limit of 64 cpus per node, which the SPAs have said that we should not use that limit so as to not waste resources.  Wei had suggested a fix to go back to binding to depth and not to core, which they have said eliminates the error.  I am going to test that and then try that.

**Pull request closed without merging**
