### PR TITLE
Feature global det atmos regional stats

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

* Adding stats that will be used to compare the GFS to the RAP and NAM
* Use prod installations of MET v11.0.0 and METplus v5.0.0
* Point to Cartopy shapefiles in prod

- [ ] Describe testing already performed for this Pull Request:</br>

> The GFS stats jobs were ran everyday in a cron and quick look graphics were approved by @AliciaBentley-NOAA and @LoganDawson-NOAA 

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> Checkout the branch
Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_55/evs_global_det_atmos_set_up.sh. Open and set EVSclone to where the clone is. This script will link the fix files and clear out the user's stats/global_det directory and the link to my stats/global_det directory since my directory has more data in it.
Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_55/run_evs_global_det_atmos_stats.sh. Open and set EVSclone to where the clone is. This script will submit the ecf scripts to run the headline plots job.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

> Yes

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

> Yes

- [ ] Please complete this pull request review by 3/2/2023.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

Just ran a quick test of this case.  Please validate the results.  You can find the results here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det.  Please look in both the atmos and gfs directories.

The .o files are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/global_det/stats

Thanks!

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA, could you adjust the permissions?


> ls /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det
ls: cannot access '/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det': Permission denied

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

See if this works now.  If not, I may have to clear the directory and run the scripts again.

Thanks!

Perry

**Comment by malloryprow** [comment]
Still not working...let me run my prep job for today before you rerun. I'll comment here when it is done.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA All done! Just make sure before re-running that you also re-run evs_global_det_atmos_set_up.sh.

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

You may validate the results here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det 

The .o files are found in the same directory as before.  

Let me know if your results are validated.

Perry

**Comment by malloryprow** [comment]
Will review now, I can see the directories now.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Looks good! I did a diff on the gfs.20230222 stat files of your run and mine, and no difference, and the file counts in the atmos.20230222 dirs are the same.

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

One question.  I noted that you have version numbers within your ecf files.  Such as here:

```
export MET_BASE=/apps/ops/prod/libs/intel/19.1.3.304/met/11.0.0/share/met
export MET_ROOT=/apps/ops/prod/libs/intel/19.1.3.304/met/11.0.0
export PATH=/apps/ops/prod/libs/intel/19.1.3.304/met/11.0.0/bin:${PATH}
```

and here:

```
module load prod_envir/2.0.6
module load prod_util/2.0.13
```

We are not to have version numbers anywhere within the ecf files.  All version numbers need to be brought in from the run.ver file.  However, since run.ver is currently the older versions on the parallel, we can probably keep these lines in for now, since I want to have, temporarily, explicitly stated versions of MET and METplus for users who have tested and submitted on the newer versions.  

I'm not sure we need the MET_BASE or MET_ROOT variables in these scripts, since you did have module loads from met and metplus.  

Can we confirm the versions of MET and METplus you are actually running with?  And then change the module loads of prod_envir and prod_util to the run.ver versions.  

Thanks!

Perry

**Comment by malloryprow** [comment]
The prod_envir and prod_util module loads are just there for the dev testing. I believe those happen in the "%include <head.h>" or "%include <envir-p1.h>" that are in the production NCO scripts.

I can clear out the MET_BASE, MET_ROOT, and PATH from the ecf files. I think at one point those weren't getting set in the module load for some reason, but that has since been resolved. They have just kind of lingered in the scripts and it never occurred to me to remove them! All this is running MET v11.0.0 and METplus v5.0.0.

I'll clean up my ecf scripts and then do a commit.

**Comment by PerryShafran-NOAA** [comment]
OK, thanks!  This is good to know.  I do believe that I have prod_util and prod_envir inside the run.ver file, so you can use that as well.  

Interesting about the use of MET_BASE and such.  I hadn't realized that the module loads did not set this properly.  

Thanks for the info!

We can do this cleaning in a separate PR, if that helps.  This PR should be approved as it stands I think.  I'd want to know that the scripts run with these changes.

Perry

Perry

**Comment by PerryShafran-NOAA** [comment]
OK, I have decided to merge this as it is, and do the cleaning of ecf scripts in a separate fork.  These changes to the version numbers and the MET_ROOT stuff needs to be tested first.  This capability is OK.

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]
Version numbers are hard coded in.  Since some folks are updating their versions while others are not, that would be OK.  A future PR will correct these, including the MET_BASE, MET_ROOT, and PATH variables that are not needed.  The future PR will be for files not included in this PR.

**Pull request merged**
