### PR TITLE
CAM Bugfix for METplus Error related to SKIP_IF_OUTPUT_EXISTS

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
_All faulty jobs were tested for successful completion._

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
_Run the CAM/grid2obs workflow (prep and stats steps) as it is normally run in the EVS parallel.  Alternatively, here is how the workflow can be set up in the cron:_

```
0 0 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswarw_grid2obs_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_hireswarw_grid2obs_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswarw_grid2obs_prep.out 2>&1
0 0 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswarwmem2_grid2obs_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_hireswarwmem2_grid2obs_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswarwmem2_grid2obs_prep.out 2>&1
0 0 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswfv3_grid2obs_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_hireswfv3_grid2obs_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswfv3_grid2obs_prep.out 2>&1
0 0 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hrrr_grid2obs_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_hrrr_grid2obs_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hrrr_grid2obs_prep.out 2>&1
0 0 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_namnest_grid2obs_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_namnest_grid2obs_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_namnest_grid2obs_prep.out 2>&1
0 1 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswarw_grid2obs_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_hireswarw_grid2obs_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswarw_grid2obs_stats.out 2>&1
0 1 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswarwmem2_grid2obs_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_hireswarwmem2_grid2obs_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswarwmem2_grid2obs_stats.out 2>&1
0 1 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswfv3_grid2obs_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_hireswfv3_grid2obs_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswfv3_grid2obs_stats.out 2>&1
0 1 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hrrr_grid2obs_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_hrrr_grid2obs_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hrrr_grid2obs_stats.out 2>&1
0 1 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_namnest_grid2obs_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_namnest_grid2obs_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_namnest_grid2obs_stats.out 2>&1
```
_Just be sure to replace all instances of {USER} to your username in the above command (there are 30).  The qsub commands can be spot checked instead if that is easier.  
COMOUT directories are defined in the ten ecf scripts and may be changed during testing to change the location of the output stats files.  Currently, COMOUT is set as it is in the parallel repository._

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes]**

- [ ] Please complete this pull request review by **[20230329]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Beginning work on this PR now.  

Perry

**Comment by MarcelCaron-NOAA** [comment]
Thanks @PerryShafran-NOAA!  This should now be up to date with develop

**Comment by PerryShafran-NOAA** [comment]
Hi, Marcel,

In order to ensure that I can run any time, I set the prep and stats jobs to work on day minus 2, rather than your setting of day minus 1.  I didn't want to be constrained by running at a certain time.

And the HRRR job is still running.  However, I wanted to give you something to look at before the end of the day.

We have stats files.  Please take a look at the stats files here:  /lfs/h2/emc/vpppg/noscrub/stats/cam
Also examine the prep files here:  /lfs/h2/emc/vpppg/noscrub/prep/cam

Please also look at the output .o files here:

prep: /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/prep
stats: /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/stats

Let me know if all of this looks good to you.  

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi Perry:

Thanks for running this so quickly.  Using day minus 2 is fine. 

I just checked the prep and stats job output files (.o...) you referenced and they completed without issues for all of the five cams as far as I can tell.  Indeed, the stat files for each job appeared in your noscrub directory and seem to be the right file sizes.  The other grid2obs data that should appear are the SPC Outlook shapefiles in the prep directory, and they did.  Overall, it looks good to me!

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by PerryShafran-NOAA** [comment]
Approving and merging.

**Pull request merged**
