### PR TITLE
Bugfix:  change depth to core in cpu-bind statements

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

This PR addresses item #3 in Wei Wei's EVS finding document:

Change “-cpu-bind verbose,depth” to “-cpu-bind verbose,core” in /scripts and /ush

- [ ] Describe testing already performed for this Pull Request:</br>

No testing was done.  

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Tests recommended to see how well this change works.  Recommend 1 prep job, 1 stats job, and 1 plots job, and also a fourth test where the change was made in ush in global_ens, prep I think.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
A loose testing plan will look like:
- cam prep
- global_ens atmos prep
- subseasonal prep
---------------------------
- cam stats
- global_det atmos stats
- global_ens atmos stats
- mesoscale stats
- subseasonal stats
---------------------------
- cam plots
- cam-href plots
- global_det atmos plots
- global_ens atmos plots
- mesoscale plots
- mesoscale-sref plots
- narre plots
- subseasonal plots

This may be further refined once testing is underway.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran `jevs_cam_hireswfv3_precip_prep.sh` to test the cam prep processing. The walltime used was 30s.
```
[dlogin06 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ grep "resources_used.walltime" jevs_cam_hireswfv3_precip_prep.o122295973 
    resources_used.walltime = 00:00:30
```
The used walltime for the emc.vpppg parallel for the same vhr and VDATE:
```
[dlogin06 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ grep "resources_used.walltime" ../../emc.vpppg/output/jevs_cam_hireswfv3_precip_prep.o122235285
    resources_used.walltime = 00:00:30
```
The COMOUT dirs b/t my test and emc.vpppg compare exactly.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran the global_ens cmce atmos grid2grid and grid2obs stats jobs to test stats: `jevs_global_ens_cmce_atmos_grid2grid_stats.sh` and `jevs_global_ens_cmce_atmos_grid2obs_stats.sh`.
The results for walltime are very comparable.

The walltime used for my test for VDATE=20231224 for grid2obs and grid2grid respectively:
```
[dlogin06 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ grep "resources_used.walltime" jevs_global_ens_cmce_atmos_grid2obs_stats.o122302778
    resources_used.walltime = 01:06:24
[dlogin06 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ grep "resources_used.walltime" jevs_global_ens_cmce_atmos_grid2grid_stats.o122302736
    resources_used.walltime = 00:25:10
```
The used walltime for the emc.vpppg parallel for the same VDATE for grid2obs and grid2grid, respectively:
```
[dlogin06 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ grep "resources_used.walltime" ../../emc.vpppg/output/jevs_global_ens_cmce_atmos_grid2obs_stats.o122269355
    resources_used.walltime = 01:06:23
[dlogin06 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ grep "resources_used.walltime" ../../emc.vpppg/output/jevs_global_ens_cmce_atmos_grid2grid_stats.o122269342
    resources_used.walltime = 00:25:12
```
The output final stats files also compare well.
```
[dlogin06 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ ll /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/global_ens/cmce.20231224
total 56308
-rw-r--r-- 1 shelley.melchior vpppg  6501984 Dec 26 19:06 evs.stats.cmce.atmos.grid2grid.v20231224.stat
-rw-r--r-- 1 shelley.melchior vpppg 51151136 Dec 26 19:47 evs.stats.cmce.atmos.grid2obs.v20231224.stat
```
```
[dlogin06 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ ll /lfs/h2/emc/vpppg/noscrub/emc.vppp
g/evs/v1.0/stats/global_ens/cmce.20231224/evs.stats.cmce.atmos.grid2*
-rw-r--r-- 1 emc.vpppg vpppg  6501984 Dec 26 10:25 /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/global_ens/cmce.20231224/evs.stats.cmce.atmos.grid2grid.v20231224.stat
-rw-r--r-- 1 emc.vpppg vpppg 51151136 Dec 26 11:07 /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/global_ens/cmce.20231224/evs.stats.cmce.atmos.grid2obs.v20231224.stat
```

**Comment by PerryShafran-NOAA** [comment]
Thank you so much!  Things are looking good thus far.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran the global_det atmos surface grid2obs plots job to test stats: `jevs_global_det_atmos_grid2obs_sfc_plots_31days.sh`.
The results for walltime are very comparable.

The walltime used for my test for VDATE=20231225 for grid2obs was 46 mins
The used walltime for the emc.vpppg parallel for the same VDATE for grid2obs was 47 mins

The resultant tar files compare well.
```
[dlogin06 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ ll /lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/global_det/atmos.20231225/evs.plots.global_det.atmos.grid2obs_sfc.last31days.v20231225.tar 
-rw-r--r-- 1 shelley.melchior emc 33631303680 Dec 26 21:07 /lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/global_det/atmos.20231225/evs.plots.global_det.atmos.grid2obs_sfc.last31da
ys.v20231225.tar[dlogin06 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ ll /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/global_det/atmos.20231225/evs.plots.global_det.atmos.grid2obs_sfc.last31days.v20231225.tar                                                                             
-rw-r--r-- 1 emc.vpppg emc 33631303680 Dec 26 21:02 /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/global_det/atmos.20231225/evs.plots.global_det.atmos.grid2obs_sfc.last31days.v20231225.tar
```

**Comment by ShelleyMelchior-NOAA** [comment]
I think these tests of prep (cam), stats (global_ens), and plots (global_det), are comprehensive enough to extend across the remaining impacted components. I think this PR is acceptable to merge into develop. ✔️

**Comment by PerryShafran-NOAA** [comment]
I agree.  You may merge this into develop.  (I can't because it's my PR.)

**Comment by AliciaBentley-NOAA** [comment]
I agree that this PR looks good and can be merged this morning! @PerryShafran-NOAA @ShelleyMelchior-NOAA

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yield anticipated results. This PR is approved for merge.

**Pull request merged**
