### PR TITLE
bugfix/global_det_rev5

### PR DESCRIPTION
**Pull request by malloryprow**
Fixes EVS v1.0 Issue 86.40

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
> Ran global_det atmos prep

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

### ✅  **global_det atmos prep**
**FOLLOW THESE INSTRUCTIONS SPECIFICALLY**
> 5. Open dev/drivers/scripts/prep/global_det/jevs_global_det_atmos_prep.sh. 
> - On any line set `export DCOMINghrsst_ospo=/lfs/h1/ops/test/dcom`
> - On line 19 set `SENDMAIL=NO`
> 6. Run dev/drivers/scripts/prep/global_det/jevs_global_det_atmos_prep.sh

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **02/09/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, @malloryprow .  I am working on your PR.  I have followed your instructions and the prep job is now running.  You can check the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr442test/EVS/dev/drivers/scripts/prep/global_det/jevs_global_det_atmos_prep_00.o132231915

**Comment by malloryprow** [comment]
Seeing

> WARNING: /lfs/h1/ops/test/dcom/20240206/validation_data/marine/ghrsst/20240206_OSPO_L4_GHRSST.nc does not exist
> NOTE: /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_global_det_atmos_prep_00.132231915.dbqs01/atmos.20240206_OSPO_L4_GHRSST.nc does not exist

This is what Wei wanted so we are good here.

**Comment by malloryprow** [comment]
I need to a sync for real quick

**Comment by PerryShafran-NOAA** [comment]
@malloryprow OK great! Your fork says that you are 1 commit behind, so you might need to sync your fork before I merge.

**Comment by malloryprow** [comment]
> @malloryprow OK great! Your fork says that you are 1 commit behind, so you might need to sync your fork before I merge.

Done!

**Review by PerryShafran-NOAA — APPROVED** [review]
Testing works as expected.  Approved for merge.

**Pull request merged**
