### PR TITLE
bugfix/global_det_rev1

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

This PR addresses the following in [EVS v1.0 Issue](https://docs.google.com/document/d/1VYGABeEe2eXA1k5NFL5oavgMgiiTPyTKGWk-zWmsPdc/edit?pli=1):

- 73 WARNING in global_det_atmos_grid2grid_*_plots
- 74 WARNING in global_det_atmos_grid2obs_*_plots
- 75 WARNING in global_det_atmos_prep
- 78 WARNING in global_det_gfs_wave_grid2obs_stats

- [ ] Describe testing already performed for this Pull Request:</br>

> I ran the associated driver scripts and looked to see if the WARNING messages went away.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **01/25/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I will pick this PR up! I don't think I can get started on it today, though. Maybe tonight. Definitely Wednesday!

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/global_det_rev1`. I will begin the tests Wednesday morning.

**Comment by malloryprow** [comment]
@ShelleyMelchior-NOAA Thanks! We may have to adjust the VDATE for some jobs. Let me know when you're ready to start running.

**Comment by ShelleyMelchior-NOAA** [comment]
I am ready and will start with issue 73: `dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_snow_plots_31days.sh`
Does VDATE need to be forced?

**Comment by malloryprow** [comment]
> I am ready and will start with issue 73: `dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_snow_plots_31days.sh` Does VDATE need to be forced?

Yes! In dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_snow_plots_31days.sh on line 50, can you change `d-1` to `d-2`?

**Comment by ShelleyMelchior-NOAA** [comment]
The snow plots are underway.
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2grid_snow_plots_31days_00.o113820496`
```
113820496.cbqs01               shelley.melchi* dev             jevs_global_de*    46261    1   128    --  00:30 R 00:03
```

**Comment by malloryprow** [comment]
> The snow plots are underway. `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2grid_snow_plots_31days_00.o113820496`
> 
> ```
> 113820496.cbqs01               shelley.melchi* dev             jevs_global_de*    46261    1   128    --  00:30 R 00:03
> ```

:heavy_check_mark: We are good with this one. The final tar file matches the parallel, and the WARNING message Wei noted are no longer appearing. There are other WARNING messages that I need to address after I address the EVS v1.0 Issues.

**Comment by ShelleyMelchior-NOAA** [comment]
> ✔️ We are good with this one. The final tar file matches the parallel, and the WARNING message Wei noted are no longer appearing. There are other WARNING messages that I need to address after I address the EVS v1.0 Issues.

Yes, I saw those, too. These?
```
WARNING: /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/global_det/gfs.20240121/evs.stats.gfs.atmos.grid2grid.v20240121.stat DOES NOT EXIST
WARNING: /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/global_det/ecmwf.20240121/evs.stats.ecmwf.atmos.grid2grid.v20240121.stat DOES NOT EXIST
WARNING: /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/global_det/imd.20240121/evs.stats.imd.atmos.grid2grid.v20240121.stat DOES NOT EXIST
```

I am ready to run sst plots for item 73. Does VDATE_END need adjusting, too?

**Comment by malloryprow** [comment]
> > ✔️ We are good with this one. The final tar file matches the parallel, and the WARNING message Wei noted are no longer appearing. There are other WARNING messages that I need to address after I address the EVS v1.0 Issues.
> 
> Yes, I saw those, too. These?
> 
> ```
> WARNING: /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/global_det/gfs.20240121/evs.stats.gfs.atmos.grid2grid.v20240121.stat DOES NOT EXIST
> WARNING: /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/global_det/ecmwf.20240121/evs.stats.ecmwf.atmos.grid2grid.v20240121.stat DOES NOT EXIST
> WARNING: /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/global_det/imd.20240121/evs.stats.imd.atmos.grid2grid.v20240121.stat DOES NOT EXIST
> ```
> 
> I am ready to run sst plots for item 73. Does VDATE_END need adjusting, too?

Yup those ones. VDATE_END does need adjusting; same thing as for snow.

**Comment by ShelleyMelchior-NOAA** [comment]
The sst plots are underway.
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2grid_sst_plots_31days_00.o113822881`
```
113822881.cbqs01               shelley.melchi* dev             jevs_global_de*   197188    1    32   25gb 00:10 R 00:00
```

**Comment by malloryprow** [comment]
> The sst plots are underway. `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2grid_sst_plots_31days_00.o113822881`
> 
> ```
> 113822881.cbqs01               shelley.melchi* dev             jevs_global_de*   197188    1    32   25gb 00:10 R 00:00
> ```

:heavy_check_mark: This one is good too. Same thing about the WARNING messages as snow.

**Comment by ShelleyMelchior-NOAA** [comment]
Great. Onto item 74. I will do the basic setup adjustments for the 3 grid2obs plots drivers indicated. Are there any additional adjustments I need to make before I run them?

**Comment by malloryprow** [comment]
Nope, no additional adjustments for the item 74 tests!

**Comment by ShelleyMelchior-NOAA** [comment]
The grid2obs plots are underway.
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_pres_levs_plots_31days_00.o113823985`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_ptype_plots_31days_00.o113823995`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_sfc_plots_31days_00.o113823996`
```
113823985.cbqs01               shelley.melchi* dev             jevs_global_de*    40071    5   640    --  01:00 R 00:01
113823995.cbqs01               shelley.melchi* dev             jevs_global_de*   152137    1   128    --  00:10 R 00:01
113823996.cbqs01               shelley.melchi* dev             jevs_global_de*   172248    5   640    --  01:00 R 00:01
```

**Comment by ShelleyMelchior-NOAA** [comment]
👀 Looking ahead at item 78, can you also update the ecf script to export OMP_NUM_THREADS=1?
`ecf/scripts/stats/global_det/jevs_global_det_gfs_wave_grid2obs_stats.ecf`

**Comment by malloryprow** [comment]
> 👀 Looking ahead at item 78, can you also update the ecf script to export OMP_NUM_THREADS=1? `ecf/scripts/stats/global_det/jevs_global_det_gfs_wave_grid2obs_stats.ecf`

Yes, great catch!

**Comment by ShelleyMelchior-NOAA** [comment]
While I wait on grid2obs review, I kicked off `dev/drivers/scripts/prep/global_det/jevs_global_det_atmos_prep.sh`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_prep_00.o113830855`
```
113830855.cbqs01               shelley.melchi* dev             jevs_global_de*   138431    1     1  120gb 00:30 R 00:01
```

**Comment by malloryprow** [comment]
> Great. Onto item 74. I will do the basic setup adjustments for the 3 grid2obs plots drivers indicated. Are there any additional adjustments I need to make before I run them?

Ah, I misunderstood this. I see for the 3 gridobs plots they ran for 20240123. I thought when you said additional you meant in addition to the `d-1` to `d-2` changes. My bad!

Oddly, it looks like /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_pres_levs_plots_31days_00.o113823985 hit the wallclock.

/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_pres_levs_plots_31days_00.o113823985 and lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_sfc_plots_31days_00.o113823996 do not have the WARNING messages Wei noted, just the ones for the missing stat files that will be fixed in my next PR.

**Comment by ShelleyMelchior-NOAA** [comment]
Sorry. OK, let me re-run the 3 grid2obs plots w/ VDATE_END adjusted, for completeness. Maybe the pres_lev plots won't hit walltime this time. I will trash the plots dir so restart doesn't get triggered.

Does the prep driver for item 75 need any changes other than HOMEevs and COMIN?

**Comment by malloryprow** [comment]
For 75, the global_det atmos prep jobs runs at 1815Z. For this test it will be okay with what is running now. I think it will benefit actually. The ECMWF precip files don't come in until ~18Z so those missing data alerts in the log file should say WARNING, whereas the one Wei noted shouldn't.

**Comment by ShelleyMelchior-NOAA** [comment]
The prep job finished.

The grid2obs plots are underway again w/ VDATE_END set for d-2.
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_sfc_plots_31days_00.o113831650`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_pres_levs_plots_31days_00.o113831648`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_ptype_plots_31days_00.o113831649`

**Comment by malloryprow** [comment]
Speaking of /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_prep_00.o113830855 is done!

:+1: :+1: :+1: dcom data with WARNING and files in DATA have NOTE

> WARNING: /lfs/h1/ops/prod/dcom/20240123/qpf_verif/jma_202401231200.grib does not exist
> NOTE: /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_00.113830855.cbqs01/atmos.jma.precip.t12z.f024 does not exist
> NOTE: /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_00.113830855.cbqs01/atmos.20240123/jma/jma.precip.t12z.f024 does not exist
> WARNING: /lfs/h1/ops/prod/dcom/20240123/qpf_verif/jma_202401231200.grib does not exist
> NOTE: /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_00.113830855.cbqs01/atmos.jma.precip.t12z.f048 does not exist
> NOTE: /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_00.113830855.cbqs01/atmos.20240123/jma/jma.precip.t12z.f048 does not exist
> WARNING: /lfs/h1/ops/prod/dcom/20240123/qpf_verif/jma_202401231200.grib does not exist
> NOTE: /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_00.113830855.cbqs01/atmos.jma.precip.t12z.f072 does not exist
> NOTE: /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_00.113830855.cbqs01/atmos.20240123/jma/jma.precip.t12z.f072 does not exist
> NOTE: /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_00.113830855.cbqs01/atmos.METFRA_12_20240123 does not exist
> WARNING: /lfs/h1/ops/prod/dcom/20240123/qpf_verif/UWD202401231200012412001 does not exist
> NOTE: /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_00.113830855.cbqs01/atmos.ecmwf.precip.t12z.f024 does not exist
> NOTE: /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_00.113830855.cbqs01/atmos.20240123/ecmwf/ecmwf.precip.t12z.f024 does not exist
> WARNING: /lfs/h1/ops/prod/dcom/20240123/qpf_verif/UWD202401231200012512001 does not exist
> NOTE: /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_00.113830855.cbqs01/atmos.ecmwf.precip.t12z.f048 does not exist
> NOTE: /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_00.113830855.cbqs01/atmos.20240123/ecmwf/ecmwf.precip.t12z.f048 does not exist
> WARNING: /lfs/h1/ops/prod/dcom/20240123/qpf_verif/UWD202401231200012612001 does not exist
> NOTE: /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_00.113830855.cbqs01/atmos.ecmwf.precip.t12z.f072 does not exist
> NOTE: /lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_det_atmos_prep_00.113830855.cbqs01/atmos.20240123/ecmwf/ecmwf.precip.t12z.f072 does not exist

**Comment by malloryprow** [comment]
For 78, no changes are needed to adjust VDATE. The global_det wave stats ran this morning.

**Comment by ShelleyMelchior-NOAA** [comment]
Ok, the grid2ob plots have been re-submitted. I had done so before my noon meeting but then I forgot to trash the plots dir so that restart wouldn't be triggered. So I killed those processes and then had a meeting. Back on track now ...
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_ptype_plots_31days_00.o113834200`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_pres_levs_plots_31days_00.o113834199`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_sfc_plots_31days_00.o113834201`

**Comment by ShelleyMelchior-NOAA** [comment]
Testing for item 78 is also underway.
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o113834387`
```
113834387.cbqs01               shelley.melchi* dev             jevs_global_de*   213188    1    25   25gb 00:20 R 00:01
```

**Comment by malloryprow** [comment]
> Testing for item 78 is also underway. `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o113834387`
> 
> ```
> 113834387.cbqs01               shelley.melchi* dev             jevs_global_de*   213188    1    25   25gb 00:20 R 00:01
> ```

:heavy_check_mark: final stat file matches the emc.vpppg parallel. No more WARNING messages for OMP_NUM_THREADS. WARNING messages exist for missing GFS files but will be fixed in my next PR.

**Comment by malloryprow** [comment]
> Ok, the grid2ob plots have been re-submitted. I had done so before my noon meeting but then I forgot to trash the plots dir so that restart wouldn't be triggered. So I killed those processes and then had a meeting. Back on track now ... `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_ptype_plots_31days_00.o113834200` `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_pres_levs_plots_31days_00.o113834199` `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_sfc_plots_31days_00.o113834201`

:heavy_check_mark: Good here too. Same notes as the other plots testing.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yield expected results. This PR is approved for merge.

**Pull request merged**
