### PR TITLE
bugfix/global_det_atmos_data_check

### PR DESCRIPTION
**Pull request by malloryprow**
Fix job creation script so scripts don't run if the fhr_list variable is empty

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

> I ran dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_gfs_grid2grid_stats.sh, dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_gfs_grid2obs_stats.sh, and dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_ukmet_grid2grid_stats.sh

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> 1. Clone my fork and checkout branch bugfix/global_det_atmos_data_check
> 2. ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix
> 3. Point COMIN for dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_ukmet_grid2grid_stats.sh to fake directory where there is no prep data.
> 4. Run dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_ukmet_grid2grid_stats.sh.
> 5. Point COMINgfs for dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_gfs_grid2obs_stats.sh to fake directory where there is no prep data.
> 6. Run dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_gfs_grid2obs_stats.sh.
>
> Jobs should run quick since they aren't pointing to any data!

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **10/13/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
These jobs are done.  The .o files are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr253test/EVS/dev/drivers/scripts/global_det/stats

**Comment by malloryprow** [comment]
It looks like you ran dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_ukmet_grid2obs_stats.sh and not dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_gfs_grid2obs_stats.sh.

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr253test/EVS/dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_ukmet_grid2grid_stats_00.o82401237 had one failure. I wasn't getting that earlier when I ran it. Can you rerun with KEEPDATA=YES?

And can you change maillist to just me? I don't mind getting the emails, but I don't want to clutter Alicia's mailbox while she is away. She gets enough emails.

**Comment by PerryShafran-NOAA** [comment]
Oops, I did run the wrong script.  

I'll rerun the ukmet job and run the gfs job.

Perry

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow @PerryShafran-NOAA Thanks for working through this PR, both of you!

**Comment by malloryprow** [comment]
✅ Good to go

**Comment by PerryShafran-NOAA** [comment]
Excellent!

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
