### PR TITLE
Changes to plot config files (aqm, analyses, firewxnest)

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

This PR makes changes to plot config files:

- It removes the hard wired version number in the config file
- It moves the configuration files from the ush directory to the parm/metplus_config directory

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Only plot scripts for each component needs to be tested.  Point COMOUT to the emc.vpppg directory for tests.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP.  

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
In the PR summary instructions, you wrote COMOUT. I presume you mean COMIN?

**Comment by PerryShafran-NOAA** [comment]
Yes, I meant COMIN.  Thanks for noting that!

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and am working in branch `feature/configs`. Tests are underway for plots in analyses, aqm, and firewx.

**Comment by ShelleyMelchior-NOAA** [comment]
The firewx plots processing has completed.
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/cam/atmos.20230927`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_nam_firewxnest_grid2obs_plots.o83041836`
https://ftp.emc.ncep.noaa.gov/users/smelchior/EVS/firewx/

analyses and aqm are still processing. I will update when they are complete.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Is there a reason why the firewx_nest plots stop at f021? I feel like I remember you and Logan having discussions about this before he left.

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA - data is available only is every 3 hours.  And what you're looking at is not a fhrmean plot, but a vhrmean plot.  That's why the vhrmean plots only go up to 21Z (not f021).  The fhrmean plots do go to f036, the length of the firewxnest run.

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA - the firewxmean plots are good!

**Comment by ShelleyMelchior-NOAA** [comment]
The aqm plots processing has completed.
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/atmos.20230925`
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/headline.20230925`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_plots.o83041835`
https://ftp.emc.ncep.noaa.gov/users/smelchior/EVS/aqm/ ... headline and PMAVE

The analyses plots processing has completed.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/analyses/atmos.20230926`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_analyses_grid2obs_plots.o83041833`
https://ftp.emc.ncep.noaa.gov/users/smelchior/EVS/analyses/ ... WIND

**Comment by PerryShafran-NOAA** [comment]
The aqm plots job looks good.

The analyses plots job exceeded its walltime.  However, the plots you showed me looked good.  

Though, the fact that ran and produced plots until it was killed is good enough to suggest that the plot jobs ran with the changes.  If you want to start the job again, it should pick up where it left off due to restart.

**Comment by ShelleyMelchior-NOAA** [comment]
I agree w/ your assessment that the wallclock time exceedance is not a problem to address for the sake of what this PR focuses on. The processing successfully produced plots after the parm and ush changes.

I can perform the code review and get this PR merged.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests produced plots. This PR is approved for merge.

**Pull request merged**
