### PR TITLE
Feature/cyc2vhr nfcens

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
Variable names were modified according to NCO implementation Standard document. Those variables include $CYC, $cyc, $cycle, $cycles.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
prep script: /lfs/h2/emc/vpppg/noscrub/samira.ardani/EVS/dev/drivers/scripts/prep/nfcens/jevs_nfcens_wave_grid2obs_prep.sh
stats script: /lfs/h2/emc/vpppg/noscrub/samira.ardani/EVS/dev/drivers/scripts/stats/nfcens/jevs_nfcens_wave_grid2obs_stats.sh
plots script: /lfs/h2/emc/vpppg/noscrub/samira.ardani/EVS/dev/drivers/scripts/plots/nfcens/jevs_nfcens_wave_grid2obs_plots.sh

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes ]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes ]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @SamiraArdani-NOAA ! We found an inconsistency in how HOMEevs is defined in other components of EVS, so I thought I'd check NFCENS. Please check the J-jobs and modify HOMEevs to look like this.
```
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
```

**Comment by AliciaBentley-NOAA** [comment]
@SamiraArdani-NOAA I compared the changes made in this PR to the changes requested in the EE2 checklist document. Everything was done and looks great! Thank you!

@PerryShafran-NOAA @ShelleyMelchior-NOAA I think this PR is ready for testing!

**Comment by ShelleyMelchior-NOAA** [comment]
I ran the prep processing to completion.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/nfcens/wave.20231018`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nfcens_wave_grid2obs_prep.o106768909`

**Comment by SamiraArdani-NOAA** [comment]
"prep" outputs look good.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran the stats processing to completion.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/nfcens`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nfcens_wave_grid2obs_stats.o106781014`

**Comment by ShelleyMelchior-NOAA** [comment]
I ran the plots processing to completion.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/nfcens/wave.20231018`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nfcens_grid2obs_plots.o106781838`

**Comment by SamiraArdani-NOAA** [comment]
"stats" outputs look good.

**Comment by SamiraArdani-NOAA** [comment]
"plots" look good.

**Comment by ShelleyMelchior-NOAA** [comment]
Great! I will do the formal code review and approve this PR for merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All testing yields expected results. This PR is approved for merge.

**Pull request merged**
