### PR TITLE
feature/EVSv2-nfcens_png_names

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

> Please include a summary of the changes and the related GitHub issue(s). Please also include relevant motivation and context.

In this PR, the individual plot names for EVSv2-NFCENS have changed so that the names contain only the main model name (nfcens) and not the other two added gefs and fnmoc models. In other word, by performing these changes, the .png plots names will change from  **evs.nfcens_gefs_fnmoc.*.png** to **evs.nfcens.*.png**
There is no GitHub issues for this change. 
There are two motivations: 1- Consistency with other EVS components and 2- A more convenient way to define the image names and to display them in NFCENS verification webpages.

## Developer Questions and Checklist
* Is this a high priority PR? If so, why and is there a date it needs to be merged by?
No.

* Do you have any planned upcoming annual leave/PTO?
No.

* Are there any changes needed for when the jobs are supposed to run?
  
Yes, It would be preferable to run the plots step after the time that the emc.vpppg parallel run is finished.

- [x] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [x] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [x] References the feature branch for `HOMEevs` are removed from the code.
- [x] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [x] Jobs over 15 minutes in runtime have restart capability.
- [x] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [x] Jobs contain the appropriate file checking and don't run METplus for any missing data.
- [x] Code is using METplus wrappers structure and not calling MET executables directly.
- [x] Log is free of any ERRORs or WARNINGs.
There is only WARNINGs due to missing files (ex. fnmoc_wave) which is expected and is acceptable. 

## Testing Instructions

> Please include testing instructions for the PR assignee. Include all relevant input datasets needed to run the tests.

1- To test this PR, you need to run the driver script for only plots step.
2- Clone my fork in your local and checkout branch feature/EVSv2-nfcens_png_names.
3- ln -s fix directory.
4- In COMIN, replace the ${USER} with emc.vpppg.
5- Run the driver scripts for plots step driver script located at: EVS/dev/drivers/scripts/plots/nfcens/*

### CODE REVIEW

**Review by AliciaBentley-NOAA — APPROVED** [review]
I have looked over this PR and believe that these changes will successfully change the NFCENS .png filenames from **evs.nfcens_gefs_fnmoc.*.png** back to **evs.nfcens.*.png**. I approve this PR once testing shows that the name change is successful. Thanks!

CC @malloryprow @SamiraArdani-NOAA

**Comment by malloryprow** [comment]
### jevs_nfcens_wave_grid2obs_plots.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr580/EVS/dev/drivers/scripts/plots/nfcens/jevs_nfcens_wave_grid2obs_plots.o157081397
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr580/evs/v2.0
**DATA:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr580/evs/v2.0

I think this job is run in the parallel until 2130Z, but I saw the stat files for 20241002 in /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v2.0/stats/nfcens/nfcens.20241002 so I ran it. Let me know if this is a problem.

**Comment by SamiraArdani-NOAA** [comment]
Thanks, @malloryprow. I will check the results and will let you know if the plots look fine.

**Comment by SamiraArdani-NOAA** [comment]
@malloryprow, Plots job for VDATE=20241002 in emc.vpppg was finished. tarballs look identical to those in emc.vpppg. I transferred the images to emcrzdm and untarred them. Images shows all three models while the image name only contains evs.nfcens.* in the names which was the objective of this PR. The only thing is some WARNING messages in the .o file which is due to event_equalization=False. I was not sure about those messages.

**Comment by malloryprow** [comment]
Ah yes I see that. Do you see this message consistently? We may want to think about making it is "NOTE" or something other than WARNING if you do.

**Comment by SamiraArdani-NOAA** [comment]
@malloryprow, Yes, I have seen this before and it is not due to changes in this PR. Making it as NOTE is a good option.

**Comment by malloryprow** [comment]
Awesome! NOTE or DEBUG or whatever you think is best. Let me know when the change is made and we can retest for VDATE=20241002.

**Comment by SamiraArdani-NOAA** [comment]
@malloryprow, I have made the changes. You can start testing it. Thanks!

**Comment by malloryprow** [comment]
Rerun!!

### jevs_nfcens_wave_grid2obs_plots.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr580/EVS/dev/drivers/scripts/plots/nfcens/jevs_nfcens_wave_grid2obs_plots.o157160164
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr580/evs/v2.0
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_nfcens_wave_grid2obs_plots.157160164.cbqs01

**Comment by SamiraArdani-NOAA** [comment]
@malloryprow, I checked the .o file and the changes worked. The WARNING message changed to INFO. The COMOUT plots look as expected.

**Review by malloryprow — APPROVED** [review]
Codes changes are good and testing successful.

**Comment by malloryprow** [comment]
Thanks @SamiraArdani-NOAA!

**Pull request merged**
