### PR TITLE
Feature/firewx plot modifications

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

Modified the plotting so that the correct forecast hours and valid hours are plotted.
Modified the plot filenames in ush to indicate that they are for cam_nam_firewxnest

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run the plot job.  You may point to the emc.vpppg archive of stats data.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

Yes

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@PerryShafran-NOAA , I got this going b/t other PR tests. I have cloned your fork and checked out branch `feature/firewx_restart`. I submitted `jevs_cam_nam_firewxnest_grid2obs_plots.sh` and it has completed.

COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/cam/atmos.20230904`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_nam_firewxnest_grid2obs_plots.o95964958`

Please review.

**Comment by PerryShafran-NOAA** [comment]
Filesize looks equivalent to my filesizes, all the plots are there, and all the plot content looks good with the valid and forecast hours that need to be in the plot.  It looks good, and I think that we can merge in.

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
@PerryShafran-NOAA , great! I have done the code review, but we need one more sync fork before I can merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests ran and produced expected results. This PR is ready for merge.

**Pull request merged**
