### PR TITLE
feature/EVS-GLWU_LC_buoy

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

This change was added to include NDBC buoy no. 45178 for Lake Champlain region to EVS-GLWU. 

> Please include a summary of the changes and the related GitHub issue(s). Please also include relevant motivation and context.

There is no GitHub issue. The only motivation for this change is to include Lake Champlain verification to EVS-GLWU. 

## Developer Questions and Checklist
* Is this a high priority PR? If so, why and is there a date it needs to be merged by?
 
Would be good if to have the changes earlier that later with the goal to store daily buoy data for Lake Champlain region before freezing time.

* Do you have any planned upcoming annual leave/PTO?
  
  No.

* Are there any changes needed for when the jobs are supposed to run?
   
  No.

- [x] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [x] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [x] References the feature branch for `HOMEevs` are removed from the code.
- [x] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [x] Jobs over 15 minutes in runtime have restart capability.
- [x] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [x] Jobs contain the appropriate file checking and don't run METplus for any missing data.
- [x] Code is using METplus wrappers structure and not calling MET executables directly.
- [x] Log is free of any ERRORs or WARNINGs.

## Testing Instructions

> Please include testing instructions for the PR assignee. Include all relevant input datasets needed to run the tests.

To test this PR, you need to run prep step.
1- Clone my fork in your local and checkout branch feature/EVS-GLWU_LC_buoy
2- ln -s fix directory.
3- Replace $USER with emc.vpppg in driver scripts.
4- Run prep step:
    $EVS/dev/drivers/scripts/prep/glwu/jevs_glwu_wave_grid2obs_prep.sh.

### CODE REVIEW

**Comment by malloryprow** [comment]
### jevs_glwu_wave_grid2obs_prep.sh

**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr569/EVS/dev/drivers/scripts/prep/glwu/jevs_glwu_wave_grid2obs_prep.o156487059
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr569/evs/v2.0/prep/glwu/wave[.20240926]
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_glwu_wave_grid2obs_prep.156487059.cbqs01

**Comment by SamiraArdani-NOAA** [comment]
@malloryprow, The .o file is free from ERRORs and WARNINGs. Also, The NDBC buoy no. 45178 was added which is the objective of this PR. The output results all look good.

**Review by malloryprow — APPROVED** [review]
Code changes and testing are good.

**Review by AndrewBenjamin-NOAA — APPROVED** [review]
I approve these changes

**Comment by malloryprow** [comment]
Thanks Samira! I'll get this into the beta5 parallel!

**Pull request merged**
