### PR TITLE
RTOFS updates

### PR DESCRIPTION
**Pull request by GwenChen-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Just wanted to let you know, I am working on your PR now.

Perry

**Comment by GwenChen-NOAA** [comment]
Happy New Year, Perry!  You may hold on to this.  I updated my scripts to
use the new GHRSST OSPO data in /dcom, but I haven't pushed them to
GitHub.  I will do it after one more check.  You can then merge them
together.

Thanks,
Gwen

**Comment by GwenChen-NOAA** [comment]
Perry,

I have test ran the updated scripts successfully.  You may merge them now.
Please let me know if you run into any problems.

Thanks,
Gwen

**Comment by PerryShafran-NOAA** [comment]
First I have to test them before I merge.   

I'll bring in all the changes and then do some tests, then have you validate them.

Thanks!

Perry

**Comment by GwenChen-NOAA** [comment]
Yes, it's good you also do a test run.

Thanks,
Gwen

**Comment by PerryShafran-NOAA** [comment]
Hi, Gwen,

Can you please tell me if these statements are errors or to be expected?

```
Warning (find_time_vars): Found more than one time variable, skipped variable Date!
Warning (cdfInqContents): Coordinates variable Date can't be assigned!
Warning (cdfInqContents): Coordinates variable Date can't be assigned!
Warning (cdfInqContents): Coordinates variable Date can't be assigned!
Warning (cdfInqContents): Coordinates variable Date can't be assigned!
Warning (cdfInqContents): Coordinates variable Date can't be assigned!

```

Thanks!

Perry

**Comment by GwenChen-NOAA** [comment]
Yes, they are expected.  Please see my explanation in PR #35.

Thanks,
Gwen

**Comment by PerryShafran-NOAA** [comment]
Thank you.  I don't recall if these warnings were the same as the other warnings, but I'll move on and run the stats step now.

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Gwen,

All runs completed late Friday night, so I wanted to have you validate results.

Please look in /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0 and look at all data in prep, stats, and plots for 20230104.  If everything looks good to you, then we can approve this PR.

Thanks!

Perry

**Comment by GwenChen-NOAA** [comment]
Perry,

The SSH verification with AVISO data is missing in your stat files.  Mine
is running fine.  The headline score plots are also missing.  To generate
headline score plots:

> qsub jevs_rtofs_headline_plots.ecf

If you'd like to use my stats archive to generate plots, in the
jevs_rtofs_headline_plots.ecf and jevs_rtofs_plots.ecf files, you may
change:

export COMOUTfinal=/lfs/h2/emc/vpppg/noscrub/$USER/stat_archive/RTOFS

to:

export COMOUTfinal=/lfs/h2/emc/vpppg/noscrub/Lichuan.Chen/stat_archive/RTOFS

Your figures look fine, but there is only one point.

Thanks,
Gwen

**Comment by PerryShafran-NOAA** [comment]
Oh, I haven't done the headline scores yet.  But I should be concerned about the missing AVISO verification.  Can you suggest what I should be looking for to see where the error may be?

As for the figures, I did copy your stat files to my disk, so perhaps I didn't copy over enough.  I'll check.  

Thanks!

Perry

**Comment by GwenChen-NOAA** [comment]
There are RTOFS fcst files
in /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/prep/rtofs/rtofs.20230104/aviso,
but no mask files.  That means the prep scripts ran, but not the stats
scripts.  There is no METplus log file for the AVISO run, so
the exevs_rtofs_aviso_stats.sh exited before it called the rtofs_regions.sh
script.  I checked the obs file in /dcom and fcst files in
your /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/prep/rtofs, and the files are
there.  So I'm not sure why it didn't run.  Can you try to run
the jevs_rtofs_stats.ecf again?  If not, try copy
my /lfs/h2/emc/ptmp/Lichuan.Chen/evs/v1.0/prep to your ptmp directory and
run it again.

Gwen

**Comment by PerryShafran-NOAA** [comment]
Thank you!  Interesting that the prep step is OK but not the stats.  

Perry

**Comment by GwenChen-NOAA** [comment]
I just remember that AVISO data usually is the last one to come in.  So if
you run the stats scripts before 19Z, the obs file may not be there yet.

Gwen

**Comment by AliciaBentley-NOAA** [comment]
Hi Gwen and Perry. Good catch. That information captured in the Run Times
spreadsheet too, should we need it later:
https://docs.google.com/spreadsheets/d/1TAY_yvaFixw7rRzec7dk0NWqgJCwH815pBGP7hZnCGc/edit?pli=1#gid=1274005464

___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
Great!  It's after 19Z now, so I'm going to give this a try again.

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Gwen,

OK, so for 20230107, I do see the aviso stat file in there.  Please let me know that these stat files are correct.

Perry

**Comment by GwenChen-NOAA** [comment]
Perry,

Your 20230107 stat files are identical to mine.  However, I just found that
METplus may have a cross-year bug in time interpolation of climatology
files.  This one is different from the one I fixed.  I will do some testing
tomorrow using MET 11.0.0/METplus 5.0.0 on Hera, which has a new function
for reading monthly climatology files.  Please hold on to this.

Thanks,
Gwen

**Comment by PerryShafran-NOAA** [comment]
Thank you.  I will hold off on further testing until your new updates are in.  

Perry

**Comment by GwenChen-NOAA** [comment]
Perry,

I tested my EVS scripts using MET 11.0.0/METplus 5.0.0 on Hera, and got the
same results.  It is a bug in the time interpolation of MET/METplus, not a
problem in my scripts.  Please go ahead and merge this PR.  I will open a
METplus discussion on the bug.

Thanks,
Gwen

**Comment by PerryShafran-NOAA** [comment]
Just to be clear - the changes in this PR are good to be merged, while we await fixes from the DTC for the bugfix?

Thanks!

Perry

**Comment by GwenChen-NOAA** [comment]
I think so.  The time interpolation works fine for all months, except for
valid dates between January 1-14.

Gwen

**Comment by PerryShafran-NOAA** [comment]
OK, I'll merge.  But if there needs to be a fix, please be sure to submit a new PR for that one, as this one will be closed upon merge.

Thanks!

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
