### PR TITLE
feature/update_beta5

### PR DESCRIPTION
**Pull request by malloryprow**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

This updates develop to using beta5. This is so developers can start using develop to work off of to start making changes related to changes in beta5.

## Developer Questions and Checklist
* Is this a high priority PR? If so, why and is there a date it needs to be merged by?
> Yes, we should get this in quick so developers can start working ASAP. Today would be great!

* Do you have any planned upcoming annual leave/PTO?
> Yes, 9/13 full day and 9/16 half day.

* Are there any changes needed for when the jobs are supposed to run?
> N/A

  
- [ ] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [ ] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [ ] References the feature branch for `HOMEevs` are removed from the code.
- [ ] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [ ] Jobs over 15 minutes in runtime have restart capability.
- [ ] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [ ] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [ ] Code is using METplus wrappers structure and not calling MET executables directly.
- [ ] Log is free of any ERRORs or WARNINGs.

## Testing Instructions

None needed I don't think. We could run a drive to exit after the modulefiles load to make sure everything loaded okay.

### CODE REVIEW

**Review by AliciaBentley-NOAA — APPROVED** [review]
I approve the change to the beta5s to be merged into the develop branch!

@malloryprow @PerryShafran-NOAA

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I think that I will do a single quickie test to check the module loads.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The module loads worked just fine.  I am seeing the extra columns for wind variables for VL1L2.   I am good with merging this.

**Review by PerryShafran-NOAA — APPROVED** [review]
Module loads for the new versions worked just fine.  Approved for merge.

**Pull request merged**
