### PR TITLE
Feature/subseasonal EE2 Edits

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
The prep and stats scripts have been tested in a cronjob and on the command line.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Checkout feature branch and make sure paths like HOMEevs are set correctly for your testing.
Run the following first to test GEFS prep changes (job now runs as poe script based on Lin Gan's suggestion):
EVS/dev/drivers/scripts/subseasonal/prep/jevs_subseasonal_gefs_prep.sh
Once that is done and confirmed, make sure you have 35 days worth of GEFS prep data; if not, link to mine at /lfs/h2/emc/vpppg/noscrub/shannon.shields/EVS_Data/evs/v1.0/prep/subseasonal.
Then run the following stats job:
EVS/dev/drivers/scripts/subseasonal/stats/jevs_subseasonal_gefs_grid2obs_stats.sh
*Note: only G2O here needs to be tested.
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes (these edits are based on Lin Gan's review of the code)
- [ ] Please complete this pull request review by **[Fill in date]**.</br>
By end of the week if possible (8/18)
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShannonShields-NOAA** [comment]
@ShelleyMelchior-NOAA Okay, sorry for the delay; I have been addressing multiple things at the same time. This PR (which now has all of the edits incorporated from PR 195) is now ready for review. The testing instructions outlined above are valid for both PRs. Thank you for the suggestion of merging these PRs together as we were able to realize and fix the $DATA path issues.

**Comment by ShelleyMelchior-NOAA** [comment]
@ShannonShields-NOAA , I have cloned your fork and checked out branch `feature/subseasonal_EE2_edits`. I will post results (or questions) as I have them.

**Comment by ShelleyMelchior-NOAA** [comment]
The gefs prep processing is underway.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/subseasonal`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_subseasonal_gefs_prep.o77530383`

**Comment by ShannonShields-NOAA** [comment]
The GEFS prep job has finished and I can confirm that everything looks correct. I confirmed the success of the DATAROOT/jobid path changes.

**Comment by ShelleyMelchior-NOAA** [comment]
The GEFS g2o stats job has completed. It looks like it sizes up well the emc.vpppg stat file.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/subseasonal`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_subseasonal_gefs_grid2obs_stats.o77534004`

**Comment by ShannonShields-NOAA** [comment]
Yes, all the stats are there (except Days 6-10 avg is missing but that is due to missing model data, not intrinsic code error).
However, I noticed I have to fix/add the job names: "/lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/.77534004.cbqs01".
This output path should read as "/lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_subseasonal_gefs_grid2obs_stats.77534004.cbqs01".

**Comment by ShannonShields-NOAA** [comment]
@ShelleyMelchior-NOAA Ok, all job names have been added in the dev/driver scripts for stats and plots (they were already included in prep scripts). If you could please rerun jevs_subseasonal_gefs_grid2obs_stats.sh to confirm these changes..

**Comment by ShannonShields-NOAA** [comment]
Hmmm...I'm looking at /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_subseasonal_gefs_grid2obs_stats.o77538423, but I am not seeing the job name edit. Just to check, did you update your fork with the change? Or am I looking in the wrong file?

**Comment by ShannonShields-NOAA** [comment]
@ShelleyMelchior-NOAA Ah ok, there we go! "export jobid=jevs_subseasonal_gefs_grid2obs_stats.77541539.cbqs01" is working.

**Comment by ShelleyMelchior-NOAA** [comment]
Yes! Apologies, @ShannonShields-NOAA ! I had forgotten to pull in the updates. But also bonus, I stopped the job and resubmitted which also exercised the restart capability!

**Comment by ShelleyMelchior-NOAA** [comment]
I think this PR is good to go. I will do the official code review. And you can do one more sync fork. Thanks!

**Comment by ShannonShields-NOAA** [comment]
Yes, everything ran correctly for that stat job. Thank you; I appreciate your help with this PR!

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The tests yielded anticipated results. The code in this PR was updated to merge in changes included in PR #195 . This PR is approved for merge.

**Pull request merged**
