### PR TITLE
Feature/evs structure nfcens

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
The EVS code structure for NFCENS component was modified according to NCO request. The codes were tested and the outputs were checked with parallel emc.vpppg. 
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
The location of the driver scripts for each STEP: /lfs/h2/emc/vpppg/noscrub/${USER}/EVS/dev/drivers/scripts/
The location of outputs: /lfs/h2/emc/vpppg/noscrub/${USER]/evs/v1.0/
 
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes]**

- [ ] Please complete this pull request review by **[10/13/2023]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
I will be starting work on your PR.

**Comment by PerryShafran-NOAA** [comment]
Hi, @SamiraArdani-NOAA ,

The prep step is complete.  Would you please take a look at the .o output and the output data to validate this for me?

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr292test/EVS/dev/drivers/scripts/prep/nfcens/jevs_nfcens_wave_grid2obs_prep.o106088079

The output directory is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/nfcens/wave.20231010/nfcens/grid2obs

Thanks!

Perry

**Comment by SamiraArdani-NOAA** [comment]
Hi Perry,
The "prep" step results look good to me.

Thanks,

**Comment by PerryShafran-NOAA** [comment]
Hi, @SamiraArdani-NOAA ,

There was one thing that I noticed that we have in nfcens now and still in this PR that we might want to change with this current PR.

Currently you have your output directory for the stats

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/nfcens/wave/nfcens.20231010
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/nfcens/wave/wave.20231010

When it should be:

/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/nfcens/nfcens.20231010
/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/nfcens/wave.20231010

It's because you have an extra ${RUN} in your COMOUT:

export COMOUT=${OUTPUTROOT}/${NET}/${evs_ver}/${STEP}/${COMPONENT}/${RUN}

If you change this to:

export COMOUT=${OUTPUTROOT}/${NET}/${evs_ver}/${STEP}/${COMPONENT}

then you'll have the output directory structure that is preferred and what we have across EVS.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA
Got it. I will apply this change and push it.

Thanks,
Samira

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA 
I pushed the changes. Thanks.

**Comment by ShelleyMelchior-NOAA** [comment]
I have looked through the progress on this PR. While Perry works through a computer issue, I will re-run the stats processing.

**Comment by ShelleyMelchior-NOAA** [comment]
The re-run of the stats process produces the proper output path.
```
$ ll /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/nfcens/
total 8
drwxr-sr-x 2 shelley.melchior vpppg 4096 Oct 12 14:30 nfcens.20231011
drwxr-sr-x 3 shelley.melchior vpppg 4096 Oct 12 14:29 wave.20231011
```

**Comment by ShelleyMelchior-NOAA** [comment]
@SamiraArdani-NOAA , we need another sync fork. I will run plots next.

**Comment by SamiraArdani-NOAA** [comment]
@ShelleyMelchior-NOAA  
I did sync fork. the "develop" is up-to-date. I will be merging "develop" into my "feature/EVS_structure_nfcens" branch.

**Comment by ShelleyMelchior-NOAA** [comment]
The plots processing is completed. Please review.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/nfcens/wave.20231011`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nfcens_grid2obs_plots.o106144328`

**Comment by SamiraArdani-NOAA** [comment]
The plots look good.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The tests in this PR yielded expected results. This PR is now ready for merge.

**Pull request merged**
