### PR TITLE
feature/global_det_atmos_plots

### PR DESCRIPTION
**Pull request by malloryprow**
This pull request includes:

- global_det atmos grid-to-grid plots
- global_det atmos grid-to-obs plots
- update to MET and METplus prod modules

- [ ] Describe testing already performed for this Pull Request:</br>

> ecf scripts were submitted to be run and tested. Plots are displayed at https://emc.ncep.noaa.gov/gmb/mpr/evs_plots_check/.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

1. Checkout the branch
2. Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_44/evs_global_det_atmos_set_up.sh. Open and set EVSclone to where the clone is. This script will link the fix files and clear out the user's stats/global_det directory and the link to my stats/global_det directory since my directory has more data in it.
3. Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_44/run_evs_global_det_atmos_plots.sh . Open and set EVSclone to where the clone is. This script will submit the ecf scripts to run the plotting jobs.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

> Yes

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

> Yes

- [ ] Please complete this pull request review by 12/16/2022.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

I'd like to start working on this soon.  I'll be doing stats first and then plots, but I was wondering if there is enough data currently on Cactus to do the plotting that you need to produce?

Thanks!

Perry

**Comment by malloryprow** [comment]
Yes! I have been mirroring data between Dogwood and Cactus at /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det.

**Comment by PerryShafran-NOAA** [comment]
Excellent!  

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

Have you ever experienced any of your plot jobs timing out due to reaching the wall clock time?  A few of your plot jobs did just that, others are still running after several hours.  I think you might have noticed that Cactus is moving pretty slow today, including in the execution of jobs.  I'm pretty sure we'll have to do this again.

Could you look at the .o files in this directory and let me know which ones didn't finish and which ones did?

/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/global_det/plots

Also it would be pretty helpful if you could provide for me:

1) the location of where the individual plots reside
2) the final location of the tarred up plots file

Thanks!

Perry

**Comment by malloryprow** [comment]
Jobs were wall times were exceeded:

1. jevs_global_det_atmos_grid2grid_means_plots_31days
2. jevs_global_det_atmos_grid2grid_means_plots_90days
3. jevs_global_det_atmos_grid2grid_sea_ice_plots_31days
4. jevs_global_det_atmos_grid2grid_sea_ice_plots_90days
5. jevs_global_det_atmos_grid2grid_snow_plots_90days
6. jevs_global_det_atmos_grid2grid_sst_plots_31days
7. jevs_global_det_atmos_grid2grid_sst_plots_90days
8. jevs_global_det_atmos_grid2obs_ptype_plots_31days
9. jevs_global_det_atmos_grid2obs_ptype_plots_90days

I haven't heard problems with these jobs exceeding the 
walltime before; most of those should run quickly and so the walltimes are short.

It is hard to give an exact path for the individual plots because there are many jobs that run in parallel with their own run directory of images. For the final tar are you talking about the one in COMOUT or in the DATA directory?

**Comment by malloryprow** [comment]
Also some jobs run a few hours. The longest jobs are the grid2obs_pres_levs ones.

**Comment by PerryShafran-NOAA** [comment]
It would be helpful to see the plots as they are generated.  Maybe just knowing where the DATA directory is would be helpful.

The final tar file would be in the COMOUT directory, the final resting place for the plot tar file.

Think that I should increase the wall times for some of these, or just try again now and see if the machine has cooled down?

Perry

**Comment by malloryprow** [comment]
The jobs are all going to run in /lfs/h2/emc/stmp/perry.shafran/evs_global_det_atmos_test/dev/tmp and the final tar files will all be in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/plots/global_det/atmos.YYYYmmdd.

**Comment by PerryShafran-NOAA** [comment]
Wow, your tar files have tar files in them!  You must really be plotting out thousands of plots!

I have a few tar files here in the final directory:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/plots/global_det/atmos.20221214

What's missing are either the ones who died due to hitting the wall clock limit or are still running (the pres_levs plots).  Those are the only jobs running right now still.  I wonder if *they* will hit the wall clock - one has a required time of 7:30!  

Anyway, if you think I should increase the wall clock time for the ones that failed, I can do so, if you recommend that.

Perry

**Comment by malloryprow** [comment]
There are indeed thousands of images being made; lots of regions, lots of variables and levels, and out to f384. It adds up quickly. I okayed this approach with @AliciaBentley-NOAA! 

The current wall clock times should be okay, but I think the problems with Cactus were the issue. Not sure if you want to rerun those ones and see what happens, but feel free to increase the times if you want to.

**Comment by PerryShafran-NOAA** [comment]
I'm re-running the jobs that previously didn't finish without increasing the wall clock, since you said that they usually run fast.  Maybe the run time is faster since the time Cactus was returned to us and everybody was fighting for resources.  If that doesn't work, I'll increase the run times.  Stay tuned.

Perry

**Comment by PerryShafran-NOAA** [comment]
Well, some of them really are fast!!  So weird that they failed previously - a whole bunch of files just showed up in the  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/plots/global_det/atmos.20221214 directory.  Check out this directory and let me know what's missing and if everything else there is OK.

Perry

**Comment by malloryprow** [comment]
Yup, looks like all of them that timed out before are done, except for jevs_global_det_atmos_grid2grid_snow_plots_90days. That one should run *a little* longer than those other quick ones.

**Comment by PerryShafran-NOAA** [comment]
Yes, that one is still running, along with the grid2obs pres_levs 90 days run that is still active.  So two jobs are still going and the rest have successfully completed.

Please feel free to validate what is in my plot directory while the other two are completed.

Thanks!

Perry

**Comment by malloryprow** [comment]
Everything looks good (looking at the number of tar files in the tar files) but the evs.plots.global_det.atmos.grid2grid_precip.last(31)(90)days.v20221214.tar. These are missing the ones associated with the spatial precip maps. I would guess this is due to the same reason Jiayi's TC spatial plots failed because of the Cartopy shape files. 

Do we have an update from NCO/GDIT when those will be in place? I can either update my code if it is going to be very soon to point to those. It looks like the shape files I need ne_110m_coastline* are not in the fix directory Jiayi added in his pull request. I could added the shape files (both mine and Jiayi's) to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix and can point to those. Thoughts? @PerryShafran-NOAA @AliciaBentley-NOAA @ShelleyMelchior-NOAA

**Comment by PerryShafran-NOAA** [comment]
In order to finish the PR, my thought would be to point to the files you put in EVS_fix and re-run this plot script.  That would get the PR approved and merged.  Then we can point to the production location later.

Perry

**Comment by malloryprow** [comment]
Sounds good! I'll get that all set up and let you know when it is good to re-run the precip plotting jobs.

**Comment by AliciaBentley-NOAA** [comment]
Hi all. I just asked Steven in another thread, but I'm not opposed to
Mallory doing what Jiayi did for now and we can change the path later.
We'll eventually have to do this with the fix directory too when it's in
its final location.
___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by malloryprow** [comment]
Updated my script to use the files Steven copied at /apps/ops/para/data/cartopy.  Let me test the changes myself, and if good I'll commit them. Then you can checkout the new changes and test again Perry.

It sounds like they will get moved to prod early January, so I'd need to update the path again when that happens, but that is no biggie.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Feel free to give the precip plotting jobs a go again!

**Comment by PerryShafran-NOAA** [comment]
Please check the files in the directory /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/plots/global_det/atmos.20221215 to see that all is good there.  I did not run any of the other plots for that day, as those were validated for the 20221214 run - just the ones that you had identified as not correct yesterday.  

Thanks!

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA These look great! I see the precip spatial maps there now!

**Comment by PerryShafran-NOAA** [comment]
Excellent!  We can now approve and merge this PR.

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by malloryprow** [comment]
Awesome! Great way to start the week!!

**Pull request merged**
