### PR TITLE
Bugfix/cam rev8

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

This PR addresses issue 68 noted in the Google Doc titled "EVS v1.0 issues".  Information about its cause and fix:

* 68 - In METplus runs, the href precip (apcp and snowfall) jobs configure the number of expected href members to a static 10 members.  When fewer than 10 are present, a warning is issued, but the job succeeds because it exceeds a static 0.3 threshold of percentage of total members. _Fix:_  Separated METplus processes by valid hour and lead hour, and passed to METplus the number of expected href members, which varies based on the valid and lead hours.  Added valid and lead hour information to log and stage file/dir templates.

The affected jobs were tested and ran successfully.

This PR also addresses the following issues:
* Various warnings in jevs_cam_grid2obs_plots jobs. _Fix:_ Changed 3-hourly leads to 6-hourly leads in raob plotting.  Added Southwest to grid2obs stats job MASK_POLY_LISTs. Removed subregions from graphics requests for TCDC and MSLP plots. Separated graphics requests by groups of forecast leads (e.g., only namnest and hireswfv3 forecast beyond 48 hours; only namnest, hireswfv3, and hrrr for some F00 fields)
* Various warnings in jevs_cam_precip_plots_jobs: _Fix:_ Added the 1" threshold to list of allowable  thresholds for 24-hour precip and NBRCNT plots.  Grouped plots requests based on init hour, forecast hour, and domain, which determines which models have data to plot.

---
- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

### (1) Set up jobs 
•	symlink the EVS_fix directory locally as "fix"
•	In all driver scripts, point all exports of "HOMEevs" to your EVS test directory
•	In all driver scripts, change COMIN to the parallel directory (`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`)

### (2) Test Jobs
Use the following to submit ...

- ... jevs_cam_precip_plots: `qsub –v vhr=00,VDATE=$(date -d "-2 days" +"%Y%m%d")` 
- ... all other jobs: `qsub –v vhr=00 `

From your EVS testing directory, the following scripts should be run using the setup in step (1):
```
dev/drivers/scripts/plots/cam/jevs_cam_href_precip_stats.sh
dev/drivers/scripts/plots/cam/jevs_cam_hireswarw_grid2obs_stats.sh
```
```
dev/drivers/scripts/plots/cam/jevs_cam_precip_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_grid2obs_plots.sh
```

_[Total: 2 stats jobs; 2 plots jobs]_

### (3) Review
---

`jevs_cam_hireswarw_grid2obs_stats`:
- check for red flags ...
```
check="FATAL\|WARNING\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|failed\|unexpected\|exceeded"
grep "$check" $outfile
```
- check for existence of "Southwest" domain

---

`jevs_cam_href_precip_stats`:
- check for red flags ...
```
check="FATAL\|WARNING\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|failed\|unexpected\|exceeded"
grep "$check" $outfile
```
- verify that the corresponding issues in the EVSv1.0 issue doc no longer exist

---

`jevs_cam_grid2obs`:
- check for red flags ...
```
check="FATAL\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|failed\|unexpected\|exceeded"
grep "$check" $outfile
```
- check that WARNINGs are limited to plots configured with ...
1 - ... "Southwest" domain (missing in parallel stats, tested for existence in `jevs_cam_hireswarw_grid2obs_stats`)
2 - ... "SBCAPE", "MLCAPE", "DPT2m", and "RH2m" (seasonal issues: threshold exceedence based on domain)

---

`jevs_cam_precip_plots`:
- check for red flags ...
```
check="FATAL\|WARNING\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|failed\|unexpected\|exceeded"
grep "$check" $outfile
```

---
- [x] Has the code been checked to ensure that no errors occur during the execution? **YES**

---
- [x] Do these updates/additions include sufficient testing updates? **YES**

---
- [x] Please complete this pull request review by **02/15/2024**.</br>

---
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA I am starting work on your PR.  Will start with the stats step.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA The .o files for stats are running here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr443test/EVS/dev/drivers/scripts/stats/cam

You can find the stats files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Plot jobs are underway.  The .o files are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr443test/EVS/dev/drivers/scripts/plots/cam

You'll find the plot tarballs here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/cam

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Both stats jobs are complete; would you please take a look at both the outputs, both the .o file and the COMOUT output?

The plots jobs are, of course, long, and they will continue to run overnight.

**Comment by MarcelCaron-NOAA** [comment]
✔️ jevs_cam_hireswarw_grid2obs_stats: log file looks good and output stat file has "Southwest"
❌ jevs_cam_href_precip_stats: Some METplus jobs failed.  This probably needs a slight fix.  Checking now, then I'll update with a fix.

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA I think I found the issue, so I pushed a fix.  Can you rerun the test for jevs_cam_href_precip_stats?

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Right away!

**Comment by PerryShafran-NOAA** [comment]
> @MarcelCaron-NOAA Plot jobs are underway. The .o files are here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr443test/EVS/dev/drivers/scripts/plots/cam
> 
> You'll find the plot tarballs here: /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/cam

In the meantime, please check out the plot jobs that I ran overnight.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA The href precip stats job is underway.  The .o file will be here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr443test/EVS/dev/drivers/scripts/stats/cam/jevs_cam_href_precip_stats.o132322765

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA The stats job is complete.  Please take a look at the .o file.

The stats output is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/href.20240207

**Comment by MarcelCaron-NOAA** [comment]
✔️ jevs_cam_href_precip_stats
✔️ jevs_cam_grid2obs_plots
🚩 jevs_cam_precip_plots: Minor WARNING.  I pushed a fix.  Rerun instructions are below.

### Rerun instructions for jevs_cam_precip_plots: 
1) Pull in the changes
2) `cp /lfs/h2/emc/vpppg/noscrub/marcel.caron/for_Perry/completed_jobs.txt /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/cam/atmos.20240206/precip/restart/completed_jobs.txt`
3) `qsub vhr=00,VDATE=20240206` to submit job
4) We will use the restart directory to only run a single spatial maps job.  It will take some time to write job cards but should complete much more quickly than the first run.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Thank you!  The job is underway. Check out the .o file in the same directory as before.   jevs_cam_precip_plots.o132339495

@AliciaBentley-NOAA @ShelleyMelchior-NOAA for awareness.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Also I think you need to sync your fork.

**Comment by MarcelCaron-NOAA** [comment]
> @MarcelCaron-NOAA Thank you! The job is underway. Check out the .o file in the same directory as before. jevs_cam_precip_plots.o132339495

@PerryShafran-NOAA Hmm it's using the old version (prior to [e298c4d](https://github.com/NOAA-EMC/EVS/pull/443/commits/e298c4d4657cec26521834dbf18d4129671e8848)) so the WARNINGs still show.  It didn't take long to run though.  Do you mind pulling in the changes, copying completed_jobs.txt again, and running again?

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA Ah, nope, my fault.  I edited 1 of 2 places that needed an edit.  The newest change should fix this.

Can you rerun as described above?

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Pulled in latest version and running again.

**Comment by PerryShafran-NOAA** [comment]
The .o file would be jevs_cam_precip_plots.o132344012.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA The job is finished, and I don't see any WARNINGs.  Can you take a look?

**Comment by MarcelCaron-NOAA** [comment]
✔️ jevs_cam_precip_plots finished running, it ran to completion, no WARNINGs, output file looks good

No other concerns from me about this PR.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Great!  Let me do a quick code check and we'll wrap this up.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA Somehow you got the fix directory into this PR.  Please remove them.

**Comment by MarcelCaron-NOAA** [comment]
> @MarcelCaron-NOAA Somehow you got the fix directory into this PR. Please remove them.

Removed

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
