### PR TITLE
Feature/Subseasonal Restart

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
Testing has been conducted on command line.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Checkout feature branch and make sure paths are set correctly.
You will need 35 days worth of prep data to run the stats jobs; can link to: /lfs/h2/emc/vpppg/noscrub/shannon.shields/EVS_Data/evs/v1.0/prep/subseasonal.
Go under EVS/dev/drivers/scripts/subseasonal/stats/.
Submit the G2O stats job via qsub jevs_subseasonal_gefs_grid2obs_stats.sh.
When the elapsed job time is at 00:06 (after 6 mins), stop the job by qdel jobid (qdel 78820922.cbqs01 for example).
After the job is stopped, let me know so that I can check where it stopped and that the relevant files were copied to $COMOUT/$RUN.$DATE.
Once this is done, I'll tell you to re-run the job and confirm that it picked up where it left off from before.
Even though grid-to-grid stats jobs do not require restart capabilities, I did have to make some small changes for the scripts that coincide with grid-to-obs (like subseasonal_util.py), so please test a G2G job to make sure it runs properly:
qsub jevs_subseasonal_gefs_grid2grid_stats.sh

Once all stats testing is done, instructions will be given for GEFS prep (if ready).
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShannonShields-NOAA** [comment]
@ShelleyMelchior-NOAA or @PerryShafran-NOAA , this PR is now fully complete and ready for testing stats and GEFS prep restart capabilities. Please contact me ASAP when you are ready to start testing (first will be GEFS prep) as this PR needs to be merged before COB Thursday 9/7 as I will be on leave.

**Comment by ShelleyMelchior-NOAA** [comment]
Awesome update, @ShannonShields-NOAA ! Glad prep is included now, too! @PerryShafran-NOAA said he will get to this PR first thing tomorrow morning!

**Comment by PerryShafran-NOAA** [comment]
Hi, @ShannonShields-NOAA ,

I am working on it now.  I have linked to your subseasonal archive.  I changed the wallclock time to 6 minutes, and I will let you know where to look to find the output when done.

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Shannon,

The job has now ended after the 6 minute period.  The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr223test/EVS/dev/drivers/scripts/subseasonal/stats/jevs_subseasonal_gefs_grid2obs_stats.o96041753

There are nc and stat files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/subseasonal/atmos.20230904/gefs/grid2obs 

This directory is empty:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/subseasonal/atmos.20230904/prepbufr/grid2obs

Please let me know if this is what you had intended.

Perry

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA This email comment didn't make it to Github for some reason, so I'm adding it again!

----------

I wanted to quickly confirm that this PR also addresses a previous comment about filenames in the EVS parallel. The comment from 8/28/23 was:

5) There are two subseasonal .tar files that have capital letters in their names, which aren't allowed in ops. Can they be turned into lowercase letters in your next PR, Shannon?
**evs.plots.subseasonal.atmos.grid2obs_PrepBufr.last31days.v20230825.tar
evs.plots.subseasonal.atmos.grid2obs_PrepBufr.last90days.v20230825.tar**

Please let us know if this change is included in this PR. If not, please include it. Thanks!

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA Sorry for the delay; yes that job ran as it should and copied the correct/finished files over to COMOUT/RUN.DATE. Please now rerun jevs_subseasonal_gefs_grid2obs_stats.sh so I can check that it picks up where it left off from before.

**Comment by ShannonShields-NOAA** [comment]
@AliciaBentley-NOAA Yes, I have included that tarfile title change in this PR as requested. This was done in the 
"Start GEFS prep restart and change G2O plots tarfile title" commit seen above.
I saw your email about changing the color of the CFS in plots as well and will try to get that in here.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA - are you sure that the nc files shouldn't be in the prepbufr directory?

In the meantime, I will do another run of the job with the original wallclock time to continue the test.  

I'll also run the gefs grid2grid job to test that as requested.

Perry

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA It's a bit complicated to explain, but since subseasonal component runs multiple jobs on different time scales (weekly, days6-10, weeks3-4 etc), the jobs are trying to look all at the same time at the COMOUT/RUN as the PB2NC files are generating so the jobs get "confused"/messed up. So atmos.20230904/prepbufr/grid2obs is left blank. The way I have it is working for the restart capabilities with the atmos.20230904/gefs/grid2obs. & I did confirm that the grid-to-obs job indeed picked up where it left off and completed running as it should. The grid-to-grid job also ran completely fine.
Next, I want to test the GEFS prep restart. Since you already have copied data over in your COMOUT directory (/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/subseasonal/atmos.20230904/gefs) I need you to delete some files to simulate a restart. So in atmos.20230904/gefs, please delete gefs.ens*.t00z.pgrb2.0p50.f8*. 
Then run the following:
EVS/dev/drivers/scripts/subseasonal/prep/jevs_subseasonal_gefs_prep.sh

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA - I'm actually pointing to your archive (see the symbolic link).  Is it possible for you to delete that file, and then I'll submit the job?

Perry

**Comment by ShannonShields-NOAA** [comment]
Yes, I deleted those GEFS prep files in my prep directory. Please run EVS/dev/drivers/scripts/subseasonal/prep/jevs_subseasonal_gefs_prep.sh

**Comment by PerryShafran-NOAA** [comment]
Actually, I have to copy that directory to my directory since I cannot write into your prep.  I will copy that directory, then delete the  requested gefs file, then run the prep job.

Perry

**Comment by PerryShafran-NOAA** [comment]
Test is underway!

**Comment by ShannonShields-NOAA** [comment]
Yes, make sure that the COMOUT directory is yours, not mine. Sorry, I'm trying to do multiple things right now and missed on that correction.
Also, you should be deleting more than just one file. Use the command "rm gefs.ens*.t00z.pgrb2.0p50.f8*" to remove all members that start with forecast hour 8..

**Comment by PerryShafran-NOAA** [comment]
Yes understood.  I'm also dealing with multiple things; else I'd have worked on this a lot sooner in the day.

**Comment by PerryShafran-NOAA** [comment]
Well that job finished fast.  

See the output file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr223test/EVS/dev/drivers/scripts/subseasonal/prep/jevs_subseasonal_gefs_prep.o96077752

And the prep gefs directory which has files written at a more recent output time:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/subseasonal/atmos.20230904/gefs

Perry

**Comment by ShannonShields-NOAA** [comment]
Yes, everything looks good. Before you merge this PR, I am testing one more thing to see if I can fix the empty prepbufr directory for G2O restart. I'll be done soon and let you know. However, I understand (as it is the end of the day) if we need to hold off and test this tomorrow.

**Comment by ShannonShields-NOAA** [comment]
When you can, please re-test the G2O stats job by running the following:
dev/drivers/scripts/subseasonal/stats/jevs_subseasonal_cfs_grid2obs_stats.sh
After about 7 mins of run time, stop the job to test the restart and let me know when you have done this so I can check the COMOUT directories (specifically atmos.20230904/prepbufr/grid2obs).

**Comment by PerryShafran-NOAA** [comment]
I am running this test now for 20230905.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Oops, I didn't bring in your change into the code.  I need to do this again.  Sorry!

Perry

**Comment by PerryShafran-NOAA** [comment]
OK, I have the 7-minute run complete.  

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr223test/EVS/dev/drivers/scripts/subseasonal/stats/jevs_subseasonal_cfs_grid2obs_stats.o96145341

The output files are here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/subseasonal/atmos.20230905/prepbufr/grid2obs
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/subseasonal/atmos.20230905/cfs/grid2obs

There are .nc files in prepbufr this time but also nc files in the cfs directory.  I don't know if that's expected, but take a look and let me know.

Perry

**Comment by ShannonShields-NOAA** [comment]
No worries. Ok, I see you have stopped the job and everything looks good (the prepbufr/grid2obs directory now correctly contains the pb2nc files). So one more run of submitting jevs_subseasonal_cfs_grid2obs_stats.sh to make sure it finishes correctly and we should be good to go with this PR.

**Comment by ShannonShields-NOAA** [comment]
Yes, that is expected behavior for the G2O stats runs as the pb2nc obs files are kept separate from the rest of the model files.

**Comment by PerryShafran-NOAA** [comment]
Re-submitting the stats job with the regular wallclock time of 40 minutes.  I will let you know when that is complete.

Perry

**Comment by AliciaBentley-NOAA** [comment]
Hi @PerryShafran-NOAA and @ShannonShields-NOAA! I don't think this should impact the testing of this PR, but can Shannon please remove the following two lines of commented out code before this PR is merged?

Remove the commented out, hardcoded path on line 23 of parm/evs_config/subseasonal/config.evs.subseasonal.obs.prep
Remove the commented out, hardcoded path on line 33 of parm/evs_config/subseasonal/config.evs.subseasonal.cfs.prep

**Comment by ShannonShields-NOAA** [comment]
@AliciaBentley-NOAA Yes, I can do that after I check on the completion of the current job test.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA The restart G2O job is complete and I have confirmed the correct output.
Let me remove those lines that Alicia pointed out before you merge.
Look for the commit/I will let you know when it is done.

**Comment by ShannonShields-NOAA** [comment]
@AliciaBentley-NOAA I have removed those commented out lines as requested for all of the config.evs scripts.
@PerryShafran-NOAA This PR is now ready to be merged! Thank you all for your help.

**Comment by PerryShafran-NOAA** [comment]
OK, let me do a quick code review, and if all is good, I will go ahead and merge.

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
