### PR TITLE
AQM PLOT MSG Fix - remove msg Quitting due to missing data...

### PR DESCRIPTION
**Pull request by Ho-ChunHuang-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by Ho-ChunHuang-NOAA** [comment]
Please see https://docs.google.com/document/d/1MEuV92JmhzQB2jMrbao8u1KwE1ICMs_t/edit?usp=sharing&ouid=110971079403051862772&rtpof=true&sd=true for testing instruction

**Comment by ShelleyMelchior-NOAA** [comment]
Hi Ho-Chun! I have cloned your fork and checked out branch `feature/aqmee2msg`. 
I have kicked off the plots job after reviewing your instructions.

**Comment by ShelleyMelchior-NOAA** [comment]
Ok, so, after some troubleshooting w/ typos and forgetting to link the fix directory, we are in business.
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/atmos.20231104`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_plots.o108347655`

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @Ho-ChunHuang-NOAA ! I know you are busy helping w/ moving AQMv7 over to cactus to keep EVSv1's parallel rolling after the machine switch.

Since this PR is still open, there is something else we need you to look at. Can you please review all `cp` commands in prep, stats, and plots and consider whether they need to use `cpreq` in place of `cp`? `cpreq` is a prod_util utility that forces an exit if the file being copied does not exist. Think of the "req" to mean "required". As you find the `cp` statements, ask the question, as in prep for example, "Will the stats processing run if the prep data are unavailable?" If the answer is "no", then please use `cpreq` in place of `cp`.

**Comment by Ho-ChunHuang-NOAA** [comment]
Hi, Shelley

We have a built-in checking process for all the input files needed for prep and stats.  If critical files are vmissing, an email will be send to alert the EVS O&M support.  Using cpreq can break the code and stop the operational task entirely for the AQM.  Is that we wanted?  Please advise.

**Comment by ShelleyMelchior-NOAA** [comment]
Yep! That's how I understand it. But one minor correction -- it will stop the task entirely for EVS. @PerryShafran-NOAA , please advise if I am incorrect.

**Comment by Ho-ChunHuang-NOAA** [comment]
The logfile has been checked and it looks good,
logfile: /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_plots.o108347655

no more "Quitting...." message appeared. The reason of no plot are explained at METPlus logging level.

Spot check a few figures from 
/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/atmos.20231104
/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/headline.20231104

they look okay to me.  You can review figures from https://www.emc.ncep.noaa.gov/mmb/hchuang/ftp/.

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks Ho-Chun! The plots look good to  me, too. I spot checked a few yesterday when the run completed. Excellent that the "Quitting"  messages are removed.

**Comment by Ho-ChunHuang-NOAA** [comment]
**Unless all previous 3 day**s of model and obs data are both missing, we can still produce some statistic in NRT for existing model and obs data.  Simply for missing one-day data then quit the job may not be ideal for us.

**Comment by ShelleyMelchior-NOAA** [comment]
Sure, that makes sense. So the answer to the sample question up above sounds like "yes" and the `cpreq` is not needed. The email traps are more of a warning that things are unavailble, but are not show-stoppers.

**Comment by Ho-ChunHuang-NOAA** [comment]
I would say "yes" for not using the cpreq in the EVS AQM code.

In operational situation, most likely the missing model/obs data will be resolved within a day (or a cycle run) to get both model/obs data restored.  We have at least two days of buffer for NCO/SPA and Dataflow to resolve the potential missing data situation.  Of course, if the problem in on the EPA AirNOW side, then there is nothing can be done at the EMC

**Comment by PerryShafran-NOAA** [comment]
@Ho-ChunHuang-NOAA ,

Can you add the following line (if you haven't done so yet) to the prep and stats driver scripts:

export COMINaqm=/lfs/h2/emc/ptmp/ho-chun.huang/emc.para/com/${MODELNAME}/v7.0

Since you told me that you are archiving the AQM v7 files in your directory, these need to be set for this PR to ensure that the changes I just made for you in the parallel aren't overwritten by the PR merge.  

Thanks!

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks, @Ho-ChunHuang-NOAA and @PerryShafran-NOAA ! I think this PR is ready for merge, correct?

**Comment by PerryShafran-NOAA** [comment]
Yes, I think we can merge.  We might have to change once NCO starts their parallel, but it looks like that won't be for awhile yet.

**Comment by Ho-ChunHuang-NOAA** [comment]
I think so, and should do it before the merge of other PR for not changing the COMINaqm in /dev/driver.... again.  That will impact the EVS parallel for AQM verification.

**Comment by ShelleyMelchior-NOAA** [comment]
I introduced the version files updates into this PR to get them into develop.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Changes look good and tests yield expected results. This PR is approved for merge.

**Pull request merged**
