### PR TITLE
feature/global_det_atmos_prep_metfra

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- Adjust METFRA prep work for changes made for data format in DCOM
- Remove UKMET precip files from prep
- Remove UKMET precipitation verification for stats and plots

- [ ] Describe testing already performed for this Pull Request:</br>

> Prep and stats for METFRA ran successfully in a cron

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> Checkout the branch
> Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_test_scripts/pr_178/run_evs_global_det_atmos_prep.sh. Run it. Have me check the output once it is finished running.
Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_test_scripts/pr_178/run_evs_global_det_atmos_stats.sh. Run it. Have me check the output once it is finished running.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **8/11/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `feature/global_det_atmos_prep_metfra`.

The prep processing is underway. Please monitor and review.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_det/atmos.20230802`
logfile: `/lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/MR/EVS/dev/drivers/scripts/global_det/prep/jevs_global_det_atmos_prep_00.o88378545`

**Comment by malloryprow** [comment]
✔️ prep is good! METFRA files are there and match mine.

**Comment by ShelleyMelchior-NOAA** [comment]
I have the metfra stats processing underway!
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/global_det`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_metfra_grid2grid_stats_00.o88400359`

**Comment by malloryprow** [comment]
✔️ METFRA stat file matches mine. We are good to go!

**Comment by ShelleyMelchior-NOAA** [comment]
Great! I did the code review as we were going along. So I will do the formal approval and then merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Changes work as expected.

**Pull request merged**
