### PR TITLE
feature/global_det_atmos - grid-to-obs ptype stats

### PR DESCRIPTION
**Pull request by malloryprow**
This pull request includes:

- addition of grid-to-obs ptype stats for the GFS
- updated final .stat file name
- change to using /bin/sh to /bin/bash
- updated grid-to-obs thresholds for ceiling and visibility
- added 925 hPa for Ozone statistics
- added SL1L2 for sea-ice concentration
- bug fix for UKMET merge code
- Use ECMWF analysis file as f000

- [ ] Describe testing already performed for this Pull Request:</br>

> The GFS grid-to-obs stats job was ran daily in a cron job. Quick looks were generated at https://emc.ncep.noaa.gov/gmb/mpr/evs_stats_check/g2os_ptype.php?domain=CONUS&variable=FBIAS_CRAIN_L0_ge1.0 and approved by Alicia.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

1. Checkout the branch
2. Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_32/evs_global_det_atmos_set_up.sh. Open and set EVSclone to where the clone is. This script will link the fix files and the previous days stats output.
3.  Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_32/run_evs_global_det_atmos_prep.sh . Open set EVSclone to where the clone is. This script will submit the ecf script "jevs_gfs_atmos_grid2obs_stats.ecf".

> The GFS is the only model that ptype verification is needed for, so there is no need to run the stats ecf scripts for any other models

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

> Yes

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

> Yes

- [ ] Please complete this pull request review by 11/22/20022.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

Completed this particular PR for p-type stats.  Can we look at the results?  

I'm wondering why the atmos.20221129 directory links to your directory.  Can you explain exactly what is going on here?

I do have a file for you to look at and validate, here:   /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det/gfs.20221129.  

Does this particular PR generate only the final stats file but the small stat files have already been generated?

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Oh that is my fault. I wanted it to get copied and not linked. Could you copy it and rerun it?

**Comment by malloryprow** [comment]
It helps with the 2m temperature anomaly stats, but ignoring that and comparing the rest it looks good! Sorry for the other commits there, needed to clean things up a bit.

**Comment by PerryShafran-NOAA** [comment]
I don't think that the linking vs copying will make much of a difference in the results.  I was just wondering why this particular code doesn't *create* stats in the atmos.20221129.  Knowing the flow of your run is kind of important.  So if you could let me know a) what exactly I am copying over, and b) what this new code is actually producing that's new from the previous PR, and c) where to find that new data would help me understand this more.

Thanks!

Perry

**Comment by malloryprow** [comment]
Copying will allow you to write to the directory. I don't think it would have copied correctly to COMOUT if you linked it. It does create stats. It is producing CTC stats for CRAIN, CSNOW, CFRZR, and CIECP, and MCTC stats for PTYPE. In atmos.YYYYmmdd/gfs/grid2obs will be point_stat files with the name "point_stat_ptype_*", and in the gfs.YYYYmmdd/evs.stats.gfs.atmos.grid2obs.vYYYYmmdd.stat file will be the stat lines mentioned in b).

The run you did yesterday the grid-to-obs ptype additional stats were all there.

**Comment by PerryShafran-NOAA** [comment]
Hmm - I wonder why those stats were there even though I linked rather than copy.

Where is the link command located?  I'll change that to a cp.

Perry

**Comment by malloryprow** [comment]
Maybe it did? It was just a soft link? I'm not very sure how that all works! It is in (/lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_32/)evs_global_det_atmos_set_up.sh

**Comment by malloryprow** [comment]
Oh duh, no it would have been fine. The Large stat file creation job would have been looking in the temporary work directory, so yeah all good.

**Comment by PerryShafran-NOAA** [comment]
I'm going to re-run it again with the cp and then have you validate the results once again.

Perry

**Comment by malloryprow** [comment]
I was watching the job as it ran and compared the final large stat file to mine and all looks well!

**Comment by PerryShafran-NOAA** [comment]
Excellent!  We can approve this and merge it in.

Perry

**Comment by PerryShafran-NOAA** [comment]
Before I do so, I wanted to make sure:  your PR had me running the jevs_gfs_atmos_grid2obs_stats.ecf file.  Is this running *all* the GFS stats, or just the p-type stats?  (That made me wonder why I had to copy your stat data to my directory, because shouldn't this be generating all the GFS stats?

Perry

**Comment by malloryprow** [comment]
It is running all the GFS stats!

**Comment by PerryShafran-NOAA** [comment]
Ah!  So what am I copying and why do I need to do that?

**Comment by malloryprow** [comment]
The ptype stats were just the focus of this PR, but the job runs everything (old stuff + ptype)

**Comment by PerryShafran-NOAA** [comment]
OK, great!  Let me proceed with the merging.

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
