### PR TITLE
bugfix/subseasonal_plot_unit_fix_prod

### LINKED ISSUE #574: subseasonal: Fix plots unit conversion for operations
We are going a bugfix code delivery to correct the unit conversions being done in plots. PR should be submitted to [evs.1.0.unit_fix](https://github.com/NOAA-EMC/EVS/tree/release/evs.1.0.unit_fix) and contain the fixes in #572 .

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes
subseasonal_util.py was edited to convert 2m temp anomalies and SST from Kelvin to Fahrenheit.
> Please include a summary of the changes and the related GitHub issue(s). Please also include relevant motivation and context.
#574 subseasonal: Fix plots unit conversion for operations
## Developer Questions and Checklist
* Is this a high priorty PR? If so, why and is there a date it needs to be merged by?
* Yes, this needs to be delivered to NCO in a bugfix.
* Do you have any planned upcoming annual leave/PTO?
* No
* Are there any changes needed for when the jobs are supposed to run?
  No
- [ ] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [ ] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [ ] References the feature branch for `HOMEevs` are removed from the code.
- [ ] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [ ] Jobs over 15 minutes in runtime have restart capability.
- [ ] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [ ] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [ ] Code is using METplus wrappers structure and not calling MET executables directly.
- [ ] Log is free of any ERRORs or WARNINGs.

## Testing Instructions

> Please include testing instructions for the PR assignee. Include all relevant input datasets needed to run the tests.
Checkout this feature branch and make sure to link EVS_fix directory in driver scripts.
Make sure COMIN is set to the prod path (/lfs/h1/ops/prod/com/evs/v1.0), COMOUT to assignee ptmp space, and HOMEevs to assignee path in plots driver scripts. Then please run all of the driver scripts under /dev/drivers/scripts/plots/subseasonal. **Please wait to test this PR until all of the stats jobs are done running.** This is around 17Z I believe; I will let you know.

### CODE REVIEW

**Review by AliciaBentley-NOAA — APPROVED** [review]
I have looked over this PR and think that it contains exactly what it needs to (only [ush/subseasonal/subseasonal_util.py](https://github.com/NOAA-EMC/EVS/pull/577/files#diff-0a0c45958e9510df7c3df4c19a304d8de644b05b9a555fea864bc266f98b74d9)) in order to be included in the upcoming EVS "unit fix" release. I approve this PR to be merged once testing is completed. Thanks!

CC @ShannonShields-NOAA @malloryprow

**Comment by malloryprow** [comment]
Scripts are set up and ready to fire off when the stats in ops are done!

**Comment by ShannonShields-NOAA** [comment]
@malloryprow Today's prod stats are now complete at /lfs/h1/ops/prod/com/evs/v1.0/stats/subseasonal/. This PR is ready for testing.

**Comment by malloryprow** [comment]
Hopefully all these paths are right. I'm working just from my laptop so the screen is small and trying to keep track of things across multiple windows.

COMOUT is /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr577/evs/v1.0/plots/subseasonal/atmos.20241001

### jevs_subseasonal_grid2grid_anom_plots_31days.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr577/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_anom_plots_31days.o157069764
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_anom_plots_31days.157069764.cbqs01

### jevs_subseasonal_grid2grid_anom_plots_90days.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr577/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_anom_plots_90days.o157069766
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_anom_plots_31days.157069766.cbqs01

### jevs_subseasonal_grid2grid_pres_lvls_plots_31days.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr577/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_31days.o157069767
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_pres_lvls_plots_31days.157069767.cbqs01

### jevs_subseasonal_grid2grid_pres_lvls_plots_90days.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr577/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_90days.o157069779
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_pres_lvls_plots_90days.157069779.cbqs01

### jevs_subseasonal_grid2grid_sea_ice_plots_31days.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr577/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sea_ice_plots_31days.o157069832
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_sea_ice_plots_31days.157069832.cbqs01

### jevs_subseasonal_grid2grid_sea_ice_plots_90days.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr577/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sea_ice_plots_90days.o157069901
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_sea_ice_plots_90days.157069901.cbqs01

### jevs_subseasonal_grid2grid_sst_plots_31days.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr577/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sst_plots_31days.o157070054
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_sst_plots_31days.157070054.cbqs01

### jevs_subseasonal_grid2grid_sst_plots_90days.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr577/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sst_plots_90days.o157070060
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_sst_plots_90days.157070060.cbqs01

### jevs_subseasonal_grid2obs_prepbufr_plots_31days.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr577/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2obs_prepbufr_plots_31days.o157070064
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2obs_prepbufr_plots_31days.157070064.cbqs01

### jevs_subseasonal_grid2obs_prepbufr_plots_90days.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr577/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2obs_prepbufr_plots_90days.o157070067
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2obs_prepbufr_plots_90days.157070067.cbqs01

**Comment by ShannonShields-NOAA** [comment]
@malloryprow and @AliciaBentley-NOAA I have checked the output and tar files; everything seems good to go.
https://emc.ncep.noaa.gov/users/verification/global/subseasonal/test/atmos/grid2grid/tmp_anom_2m/
https://emc.ncep.noaa.gov/users/verification/global/subseasonal/test/atmos/grid2grid/sst/

**Review by malloryprow — APPROVED** [review]
Code changes are good and testing successful.

**Pull request merged**
