### PR TITLE
Feature/ee2 final wafs

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
In this PR, the rest of the EE2 -final items were modified. The scripts were tested.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
There is no prep STEP for this component.
stats STEP script: jevs_wafs_atmos_stats.sh
plots STEP script: jevs_wafs_atmos_plots.sh

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
HI Samira! Your PR looks good upon first glance. I will set it up to run wafs stats.

**Comment by ShelleyMelchior-NOAA** [comment]
The stats processing has completed!
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/wafs`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_wafs_stats.o108051926`

**Comment by SamiraArdani-NOAA** [comment]
@ShelleyMelchior-NOAA : The outputs were identical to emc.vpppg parallel. The .o file also look good.

**Comment by ShelleyMelchior-NOAA** [comment]
Fantastic! Thanks for the quick response. I will not merge this PR yet. I will allow an opportunity for @AliciaBentley-NOAA to review the changes. I will merge once she has had a chance to look over the PR.

**Comment by SamiraArdani-NOAA** [comment]
@ShelleyMelchior-NOAA : Sounds great. Thank you!

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA Please ask Samira to add the needed AQM lines into this PR!

After that, it can be merged. Thanks!

**Comment by ShelleyMelchior-NOAA** [comment]
HI @SamiraArdani-NOAA  -- we are going to use your PR to work in one oversight in the recently merged AQM PR. There are 2 driver scripts that need an update.

Please add the following line at line 56 of `dev/drivers/scripts/prep/aqm/jevs_aqm_prep.sh` (https://github.com/SamiraArdani-NOAA/EVS/blob/22642ba3b1008ac250484ef55ac820c4011d7a3b/dev/drivers/scripts/prep/aqm/jevs_aqm_prep.sh#L56):
```
export COMINaqm=/lfs/h2/emc/ptmp/jianping.huang/emc.para/com/aqm/v7.0
```

Please add the following line above line 58 of `dev/drivers/scripts/stats/aqm/jevs_aqm_grid2obs_stats.sh` (https://github.com/SamiraArdani-NOAA/EVS/blob/22642ba3b1008ac250484ef55ac820c4011d7a3b/dev/drivers/scripts/stats/aqm/jevs_aqm_grid2obs_stats.sh#L58):
```
export COMINaqm=/lfs/h2/emc/ptmp/jianping.huang/emc.para/com/aqm/v7.0
```
---
To see the request already in place, you can browse the para branch of the EVS github repository.
https://github.com/NOAA-EMC/EVS/blob/b0f756b80be4448df19adf74499eb63af31fec14/dev/drivers/scripts/prep/aqm/jevs_aqm_prep.sh#L56
https://github.com/NOAA-EMC/EVS/blob/b0f756b80be4448df19adf74499eb63af31fec14/dev/drivers/scripts/stats/aqm/jevs_aqm_grid2obs_stats.sh#L58

**Comment by SamiraArdani-NOAA** [comment]
@ShelleyMelchior-NOAA @AliciaBentley-NOAA : Just to clarify, do you want me to do these changes in aqm? because I worked on wafs.

**Comment by ShelleyMelchior-NOAA** [comment]
Correct. We need the change into the main code base. Instead of opening a new PR by me or Perry, we thought it would be more efficient to integrate this small change into an open PR. Yours is ready for merge so we thought it would be best to have you put the change in. If you are uncertain, I can put the change into this open PR for you.

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA Thanks! I would not be opposed to you adding these two lines and merging the WAFS PR. Lin will begin the EE2 review on Monday, so it would be good to get this PR merged (and maybe added to the parallel) over the weekend. Thanks!

**Comment by ShelleyMelchior-NOAA** [comment]
@SamiraArdani-NOAA , upon recommendation from @AliciaBentley-NOAA , for the interest of time, I went ahead and made the requested changes. Next, I will do the formal code review and approve this PR for merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Changes look good. Tests yield anticipated results. This PR is approved for merge.

**Pull request merged**
