### PR TITLE
feature/EVSv2-RTOFS_additions1

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

> Please include a summary of the changes and the related GitHub issue(s). Please also include relevant motivation and context.

In this PR, one of the items in Fixes and Additions for EVSv2-RTOFS has been addressed. The $VDATE for prep step have been replaced with $INITDATE in all related scripts.

## Developer Questions and Checklist
* Is this a high priority PR? If so, why and is there a date it needs to be merged by?
No.

* Do you have any planned upcoming annual leave/PTO? 
No.

* Are there any changes needed for when the jobs are supposed to run?
  No.

- [x] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [x] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [x] References the feature branch for `HOMEevs` are removed from the code.
- [x] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [x] Jobs over 15 minutes in runtime have restart capability.
- [x] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [x] Jobs contain the appropriate file checking and don't run METplus for any missing data.
- [ ] Code is using METplus wrappers structure and not calling MET executables directly.
- [x] Log is free of any ERRORs or WARNINGs.
There are WARNINGs due to missing observational data (ex. OSI-SAF for the time of testing). 

## Testing Instructions

> Please include testing instructions for the PR assignee. Include all relevant input datasets needed to run the tests.

To test this PR, you need to run the driver scripts for only prep step.
1- Clone my fork in your local and checkout branch feature/EVSv2-RTOFS_additions1.
2- ln -s fix directory.
3- Run the driver scripts for prep step at: EVS/dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.sh

### CODE REVIEW

**Comment by malloryprow** [comment]
### jevs_rtofs_prep.sh

**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr566/EVS/dev/drivers/scripts/prep/rtofs
**DATA:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr566/EVS/dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.o156038379
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr566/evs/v2.0

The job is running, but I believe it takes a few hours so sharing the information now.

**Review by AliciaBentley-NOAA — APPROVED** [review]
I have reviewed this PR and found that it changes VDATE to INITDATE throughout RTOFS prep. I approve this PR to be merged if testing goes well and shows similar results to current prep jobs. Thanks!

CC @malloryprow @SamiraArdani-NOAA

**Comment by malloryprow** [comment]
Looks like the run is done! @SamiraArdani-NOAA , please review when you have the chance.

**Comment by SamiraArdani-NOAA** [comment]
@malloryprow, Yes. I finished reviewing the outputs. The .o file is free from ERROR or WARNING. Also the output results look as expected.

**Review by malloryprow — APPROVED** [review]

**Comment by malloryprow** [comment]
Thanks Samira!

**Pull request merged**
