### PR TITLE
EVS stat and plot adding 1.25 Icing Potential, 1.25 Temperature and Wind Speed

### PR DESCRIPTION
**Pull request by YaliMao-NOAA**
## Pull Request Testing ##

- [ x] Describe testing already performed for this Pull Request:</br>

- [ x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [x ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [x ] Review the source issue metadata (required labels, projects, and milestone).
- [ x] Complete the PR description above.
- [ x] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ x]  Instructions provided on how to run
- [ x]  Developer's name is replaced by ${user} where necessary throughout the code
- [ x]  Check that the ecf file has all the proper definitions of variables
- [ x]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ x]  Check to see that the output directory structure is followed
- [ x]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
Hi Yali. Thank you for submitting your final WAFS Pull Request! I don't
think that I've seen the final plots for these parameters yet. Could you
please send me examples of your final plots for 1.25º Icing Potential,
Temperature, and Wind Speed when you get the chance? I need to approve them
before the Pull Request is eventually merged. Thank you!
___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by YaliMao-NOAA** [comment]
Instructions:

1. git clone -b feature/global_det_aviation git@github.com:YaliMao-NOAA/EVS.git
2. cd EVS
3. To generate stat files: (VDATE is one day ahead of the current date by default) 
   Edit PBS error output filename, change HOMEevs to the EVS folder, and submit a job: qsub ecf/global_det/stats/jevs_global_det_aviation_stats.ecf

   Small stat files are under: /lfs/h2/emc/ptmp/$USER/com/evs/v1.0/stats/global_det/aviation.$PDY
   Final stat files are under: /lfs/h2/emc/ptmp/$USER/com/evs/v1.0/stats/global_det/wafs.$PDY
   Under final stat file folder, there are three stat files, for example:
      evs.stats.wafs.aviation.grid2grid_icesev.v20221130.stat
      evs.stats.wafs.aviation.grid2grid_icip.v20221130.stat
      evs.stats.wafs.aviation.grid2grid_uvt1p25.v20221130.stat
4. To generate plot files: (VDATE is one day ahead of the current date by default)
   Edit PBS error output filename, change HOMEevs to the EVS folder, and submit a job: qsub ecf/global_det/plots/jevs_global_det_aviation_plots.ecf
   One plot tarball is under: /lfs/h2/emc/ptmp/$USER/com/evs/v1.0/plots/global_det/aviation.$PDY
   The tarball file name is, for example:
      evs.plots.global_det.aviation.grid2grid.last90days.v20221130.tar

**Comment by YaliMao-NOAA** [comment]
@AliciaBentley-NOAA 
1.25 Icing Potential has two plots, ROC curve and FBIAS:
image
image

1.25 Temperature has one RMSE plotting:
image

1.25 Wind Speed has two plottings, one is for no threshold, the other is for >=80knots:
image
image

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA gfs_ver in versions/run.ver should be v16.3, not v16.2 now.

@AliciaBentley-NOAA @PerryShafran-NOAA For the final plotting version, I will turn off US and UK for ROC curve and FBIAS of 0.25 Icing Severity and 1.25 Icing Potential. Only blend will be turned on, to be consistent the individual verification package. Stat files will be kept on be generated for all US, UK and blended. I will update the code accordingly later on

**Comment by AliciaBentley-NOAA** [comment]
Hi Yali. Thank you for sending me your plots and explaining how you will
update them! They look good. When you make the updates that you mentioned,
please also add the NOAA and NWS logos to the upper corners as well. Here
are some examples:

G2G plot from global_det (atmos):
[image:
evs.global_det.acc.hgt_p500.last31days.timeseries_valid00z_f120.g004_glb
(1).png]

G2O plot from globel_ens (wave):
[image:
evs.global_ens.me_rmse.htsgw_l0_sfcshp.past31days.timeseries_valid00z_f000.global_0p25.png]
Thanks!
___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by YaliMao-NOAA** [comment]
@AliciaBentley-NOAA Sure. But I can't view your sample images. They are not loaded.

**Comment by YaliMao-NOAA** [comment]
@AliciaBentley-NOAA I added the logos to the plots, removed 'uk' 'us' and keep 'blend' for plots of icing severity and icing potential. Meanwhile I did two very minor updates of the code.
The following is the updated plots with the logos:
image
image
image
image
image
image
image

**Comment by AliciaBentley-NOAA** [comment]
Hi Yali. Your updated graphics look fantastic! Thank you for sharing them.
These graphics are approved to be merged with the authoritative repository
once Perry tests and approves your code. Thanks!

___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
Hi, Yali,

Working on this now.

Thanks!

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Yali,

Please validate the stat files here: /lfs/h2/emc/ptmp/perry.shafran/com/evs/v1.0/stats/global_det/wafs.20221213.  Your code ran with no errors.

I will begin working on plots now.  Do we have enough data on Dogwood to do plots for 31 or 90 days?  Have you moved them?

Thanks!

Perry

**Comment by PerryShafran-NOAA** [comment]
Now that we are on Cactus, do we have enough data on Cactus to do the plot test?  

Perry

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA I usually generated a few days of stat data then tested plotting on it. Do you want me to generate the stat data for you? I haven't tested plotting on a whole 31 days or 90 days of data yet.

**Comment by PerryShafran-NOAA** [comment]
I think there is no need to go back and generate 31 days of stats.  This should work to create the files.  But as long as there is data on Cactus, that would certainly be helpful.  

Do you have any data on Dogwood that can be transferred, or is what's on your directory all that we need?

Perry

**Comment by YaliMao-NOAA** [comment]
Hi Perry,
I didn't save the data. I haven't started  collecting stat data yet considering the code was done on Dec 1.
Yali

**Comment by AliciaBentley-NOAA** [comment]
Hi Yali. If Perry ran your prep scripts for several days on Cactus, would
he produce the data required to make a test plot (with only a few days on
it)?

___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by YaliMao-NOAA** [comment]
Yes, that is the way I did the test. Without a full set of data, the plots can still be generated.

**Comment by PerryShafran-NOAA** [comment]
Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
Here is how to create more days of stat data as long gfs data is available on Cactus
qsub -v "VDATE=20221209" ecf/global_det/stats/jevs_global_det_aviation_stats.ecf
Without -v "VDATE=20221209", the default stat data will be yesterday, current  date minus one.

**Comment by PerryShafran-NOAA** [comment]
I'm not sure it's necessary to run the stats for several days - but I guess I could if you think it would help.

Perry

**Comment by AliciaBentley-NOAA** [comment]
I think at least a few days would be good! A test graphic with one dot and
no line might look kind of silly! :) Thanks!

___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
Working on running the stats scripts for the past several days - maybe up to 10 days so we can have nice looking plots - at least see if all the plots are being created.

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Yali,

I was able to get stats from 12/9 to now, and then I ran the plots.  Would you please look at the output here and let me know if all the files you need are inside each tar file?

Plot tar files are here:  /lfs/h2/emc/ptmp/perry.shafran/com/evs/v1.0/plots/global_det/aviation.20221215

Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA All are good except I found no plots of wind speed over 80knots in east subdomain. May I know your stat file outputs and your log files of both stat and plot? Thank you

**Comment by PerryShafran-NOAA** [comment]
You can find the log files here:  /lfs/h2/emc/ptmp/perry.shafran.  The stats files are overwritten with each run - that's how you had made it.  The plot log is there.

The stats files are /lfs/h2/emc/ptmp/perry.shafran/com/evs/v1.0/stats/global_det.  Check out what I have there.

Perry

**Comment by YaliMao-NOAA** [comment]
Hi Perry,
When I revisited the code, I just realized the plotting of icing severity and icing potential should be every 3 hours between 06 to 36, not every 6 hours. I am working on the fix. I will submit the updates once it's done.
Yali

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA I got my code updated. Thank you!

**Comment by PerryShafran-NOAA** [comment]
Hi there!

Please validate the stat files here:  /lfs/h2/emc/ptmp/perry.shafran/com/evs/v1.0/stats/global_det/wafs.20221222

And here is the plot tar files:   /lfs/h2/emc/ptmp/perry.shafran/com/evs/v1.0/plots/global_det/aviation.20221222

Once this is validated we can close these PRs.

Perry

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA Both the stat files and plot tar files look good to me! Thank you!

**Comment by PerryShafran-NOAA** [comment]
Excellent!  If you could, please bring in my run.ver file from the authoritative branch and put that into your feature branch.  That way we would resolve the conflict.  My run.ver file should have all the libraries you need to run, so would you please check that out?  

Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA I merged your updates to my branch. There is one important thing is:
In your versions/run.ver, export prod_envir=2.0.6. I think it should be export prod_envir_ver=2.0.6

**Comment by PerryShafran-NOAA** [comment]
Ooh, thanks for that correction!  

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
