### PR TITLE
feature/EVSv2-nfcens_additions1

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

> Please include a summary of the changes and the related GitHub issue(s). Please also include relevant motivation and context.

This PR addresses the changes listed below for EVSv2-NFCENS according to Fixes and Additions for EVS v2.0 dcument:
1- Renamed the J-Jobs to JEVS_NFCENS_PREP, EVS_NFCENS_STATS, and EVS_NFCENS_PLOTS. This change is toward the consistency across all EVS components.
2- Used the for-loop instead of while-loop for FNMOC_wave data. This change was motivated to avoid WARNING messages fo files that are never expected to exist.
3- Applied corresponding changes for J-job renaming to ecf scripts.

## Developer Questions and Checklist
* Is this a high priorty PR? If so, why and is there a date it needs to be merged by? 
This PR is not a high priority. 
* Do you have any planned upcoming annual leave/PTO? 
Yes, I will be on leave from 08/27-08/30.

* Are there any changes needed for when the jobs are supposed to run?
  No. 
- [x] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [x] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [x] References the feature branch for `HOMEevs` are removed from the code.
- [x] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [x] Jobs over 15 minutes in runtime have restart capability. 
_Note_: All NFCENS jobs take less than 15 minutes.
- [x] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [x] Jobs contain the appropriate file checking and don't run METplus for any missing data.
- [x] Code is using METplus wrappers structure and not calling MET executables directly.
- [x] Log is free of any ERRORs or WARNINGs.
_Note_: There are WARNINGs only for missing data.

## Testing Instructions

> Please include testing instructions for the PR assignee. Include all relevant input datasets needed to run the tests.

1- To test this PR, you need to run the driver scripts for all three steps (prep, stats and plots).
2- Clone my fork in your local and checkout branch Feature/EVSv2-nfcens_additions1.
3- ln -s fix directory.
4- Run the driver script for prep step at: EVS/dev/drivers/scripts/prep/nfcens/*
5- Run the driver script for stats step at: EVS/dev/drivers/scripts/stats/nfcens/*
6- Run the driver script for plots step at: EVS/dev/drivers/scripts/plots/nfcens/*

Model data: wave_nfcens, gefs, fnmoc_wave.
Observational data: gdas.

### CODE REVIEW

**Comment by malloryprow** [comment]
Code changes all looked good to me. I proceeded to run prep, jevs_nfcens_wave_grid2obs_prep.sh.

**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr524/EVS/dev/drivers/scripts/prep/nfcens/jevs_nfcens_wave_grid2obs_prep.o149585318
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr524/evs/v2.0/prep/nfcens/wave
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_nfcens_wave_grid2obs_prep.149585318.cbqs01

**Comment by malloryprow** [comment]
Let me know if I need to run prep again, either later today or for a different date. I think the nfcens prep step doesn't run until 1900Z.

**Comment by SamiraArdani-NOAA** [comment]
@malloryprow: It is good to run this prep step for INITDATE=20240820 because we do not have fnmoc_wave data for the INITDATE=20240819 and that is what you did 👍 but in order to check with emc.vpppg, we need to wait till 19Z.

**Comment by malloryprow** [comment]
Ah, perfect!!

**Comment by SamiraArdani-NOAA** [comment]
@malloryprow : I checked the prep step output files with emc.vpppg. They all look good. The .o file is free from ERRORs. I see only WARNINGs due to the missing files. The .o file only generated the WARNINGs for only the files that are expected to exists which is one of the objective of this PR.

**Comment by malloryprow** [comment]
### jevs_nfcens_wave_grid2obs_stats.sh

**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr524/EVS/dev/drivers/scripts/stats/nfcens/jevs_nfcens_wave_grid2obs_stats.o149595284
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr524/evs/v2.0/stats/nfcens
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_nfcens_wave_grid2obs_stats.149595284.cbqs01

**Comment by malloryprow** [comment]
Could you do a sync fork when you get a chance?

**Comment by SamiraArdani-NOAA** [comment]
@malloryprow, All stats files compared with emc.vpppg and they all look good. The .o file is free from ERRORs.

**Comment by malloryprow** [comment]
On to plots! Do I need to adjust the dates at all?

**Comment by SamiraArdani-NOAA** [comment]
@malloryprow, You can use VDATE=20240820 for plots.

**Comment by malloryprow** [comment]
### jevs_nfcens_wave_grid2obs_plots.sh

**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr524/EVS/dev/drivers/scripts/plots/nfcens/jevs_nfcens_wave_grid2obs_plots.o149683984
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr524/evs/v2.0
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_nfcens_wave_grid2obs_plots.149683984.cbqs01

**Comment by SamiraArdani-NOAA** [comment]
@malloryprow, No ERROR was found in .o file. The size of plots in your runs is slightly different than emc.vpppg but it is just due to the difference in the time of the running. I have untarred yours and emc.vpppg and investigated both and found no issue.

**Comment by malloryprow** [comment]
Great! With Alicia out, I will add @PerryShafran-NOAA as the second reviewer. Perry, Samira's PR has been successfully tested if you want to review the changes.

**Review by malloryprow — APPROVED** [review]

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
These changes look good. It is nice to see NFCENS adopting the naming convention for J-jobs.

**Comment by malloryprow** [comment]
Merged! Thanks Samira! Be sure to check off any items on the Fixes and Additions related to this PR.

**Pull request merged**
