### PR TITLE
Feature/cam plotting

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

> Successful test runs were made daily from the cron for several weeks.  The test COMOUT directory currently contains about a week's worth of tarballs containing the required output data.  Data from these tarballs were reviewed by the CAM verification team lead for completion.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> This PR primarily includes the plotting workflows for CAM/grid2obs and CAM/precip verif cases.  Therefore, two jobs should be tested, one for each of these verif cases.  Test data is provided since the two jobs include only the plotting step, whereas in operations the input data will be provided by the corresponding stats steps.
> 
> ### Set up the test jobs:
> 
> 1. Copy my COMOUT directory to your PTMP (this includes test data):
> 
> `cp -r /lfs/h2/emc/ptmp/marcel.caron/EVS_out /lfs/h2/emc/ptmp/$USER/.`
> 
> 2. Edit HOMEevs in two ECF scripts at line 39 so that HOMEevs points to the top-level directory of your version of feature/CAM_plotting:
> 
> ECF script 1: $HOMEevs/ecf/cam/plots/jevs_cam_precip_plots.ecf
> ECF script 2: $HOMEevs/ecf/cam/plots/jevs_cam_grid2obs_plots.ecf
> `line 39: export HOMEevs="/lfs/h2/emc/vpppg/noscrub/$USER/EVS"`
> 
> ### Run the test jobs (this can run in cron or on the command line):
> ```
> qsub -o /lfs/h2/emc/stmp/$USER/jevs_cam_grid2obs_plots.out /lfs/h2/emc/vpppg/noscrub/$USER/EVS/ecf/cam/plots/jevs_cam_grid2obs_plots.ecf >> /lfs/h2/emc/stmp/$USER/cron.out/test_jevs_cam_grid2obs_plots.out 2>&1
> qsub -o /lfs/h2/emc/stmp/$USER/jevs_cam_precip_plots.out /lfs/h2/emc/vpppg/noscrub/$USER/EVS/ecf/cam/plots/jevs_cam_precip_plots.ecf >> /lfs/h2/emc/stmp/$USER/cron.out/test_jevs_cam_precip_plots.out 2>&1
> ```
> 
> ### See the results of the test jobs:
> ```
> vi /lfs/h2/emc/stmp/$USER/jevs_cam_precip_plots.out
> vi /lfs/h2/emc/stmp/$USER/jevs_cam_grid2obs_plots.out
> ```
> 
> **Unsuccessful runs may include any of the following:**
> "nid######.dogwood.wcoss2.ncep.noaa.gov: rank ### exited with code 1"
> "ValueError", "KeyError", "OSError", "IOError"
> 
> **Successful runs will result in the following output files:**
> ```
> /lfs/h2/emc/ptmp/$USER/EVS_out/com/evs/v1.0/plots/cam/atmos/evs.plots.cam.atmos.grid2obs.v${VDATE}.tar
> /lfs/h2/emc/ptmp/$USER/EVS_out/com/evs/v1.0/plots/cam/atmos/evs.plots.cam.atmos.precip.v${VDATE}.tar
> ```

- [Yes] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [Yes] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [2023/03/15] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I will be looking into this PR

**Comment by ShelleyMelchior-NOAA** [comment]
@MarcelCaron-NOAA , I ran `jevs_cam_grid2obs_plots.ecf`. It ran to completion and created tar files! Please see my log file and output directory for your comment.
log file: `/lfs/h2/emc/ptmp/shelley.melchior/jevs_cam_grid2obs_plots.out`
output: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/com/evs/v1.0/plots/cam/atmos`
I untarred `evs.plots.cam.atmos.grid2obs.v20230220.tar` and peeked at a few plots.

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA I don't see any errors in the output log for the G2O job, and the job seems to have completed normally.  The outputted tar file is the expected file size (17-18 GB) and contains the right images at a glance.  It looks good to me!

**Comment by ShelleyMelchior-NOAA** [comment]
@MarcelCaron-NOAA , I ran `jevs_cam_precip_plots.ecf`. It ran to completion and created tar files! Please see my log file and output directory for your comment.
log file: `/lfs/h2/emc/ptmp/shelley.melchior/jevs_cam_precip_plots.out`
output: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/com/evs/v1.0/plots/cam/atmos`
I untarred `evs.plots.cam.atmos.precip.v20230221.tar` and peeked at a few plots.

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA I noticed a FileExistsError near the end of the jobs processing, but I've pushed a fix for it, and it should work correctly now.  **Would you mind re-running the updated version?**  

Also, the spatial maps haven't been completing since those jobs rely on stats file output from the previous day or two.  Unfortunately, I forgot to mention this in the PR, so my apologies for that.  **To ensure the correct input files are present, you can do the following before submitting the precip job**:
`cp -TR /lfs/h2/emc/ptmp/marcel.caron/EVS_out/com/evs/v1.0/stats /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/com/evs/v1.0/stats`

**Comment by ShelleyMelchior-NOAA** [comment]
Got it! OK, I will re-run `jevs_cam_precip_plots.ecf` after following your `cp` instructions.

**Comment by ShelleyMelchior-NOAA** [comment]
@MarcelCaron-NOAA , the re-run of `jevs_cam_precip_plots.ecf` has completed. Please review the output.
output log: `/lfs/h2/emc/ptmp/shelley.melchior/jevs_cam_precip_plots.out`
output plots: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/com/evs/v1.0/plots/cam/atmos/evs.plots.cam.atmos.precip.v20230222.tar`

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA No errors this time, the spatial maps made it into the set of output plots, and the size of the tar file is as expected.  Seems like a successful run to me!  Thanks

**Comment by ShelleyMelchior-NOAA** [comment]
Excellent! And I see you updated your `feature/CAM_plotting` after the merge of PR #53 . I think your PR #57 is ready for merge. I will begin the formal review to allow the merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]

**Comment by ShelleyMelchior-NOAA** [comment]
And PR #55 has been merged into this PR. Good.

**Pull request merged**
