### PR TITLE
Bugfix/global ens grep

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

This PR is done because of the request to reduce the number of greps in the global_ens prep step.  A procedure to do that has been described by the WCOSS2 helpdesk.  Other helpdesk items to reduce the wall time of the run will be added when those have been tested (the use of the & and wait for certain steps).  

- [ ] Describe testing already performed for this Pull Request:</br>

Tested the global_ens atmos prep step.  There are no errors or anything missing from the output.  

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run the global_ens atmos prep step.  Check to see that the output matches what is in emc.vpppg.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

Yes

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP.

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/global_ens_group`.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran global_ens_prep Friday afternoon. It did not finish prior to COB. I have looked at the results over the weekend. I moved the .o file to /dfs/write so that you may view it on dogwood in /dfs/read.
logfile on dogwood: `/dfs/read/emc/vpppg/shelley.melchior/forPS/jevs_global_ens_atmos_prep.o112921098`

COMOUT on cactus: `/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_ens/atmos.20240110`
The file counts are close.
cmce = 7602 (shelley.melchior)
cmce = 7604 (emc.vpppg)
ecme = 12003 (shelley.melchior) ✔️ 
ecme = 120003 (emc.vpppg) ✔️ 
gefs = 14828 (shelley.melchior) ✔️ 
gefs = 14828 (emc.vpppg) ✔️ 
osi-saf = 1 (shelley.melchior) ✔️ 
osi-saf = 1 (emc.vpppg) ✔️ 

Of note, the job ran from 19:08 to 23:16. That is a total run time of 4:08.

There are definitely fewer greps in the logfile. The NCO and EMC para log files have over 300,000 grep commands in the logfile. This test run has 23,337 grep commands. I am seeing some errors, though, like this one:
```
/lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_ens_atmos_prep.112921098.cbqs01/cmce/pattern..348: No such file or directory
```
and then
```
rm: cannot remove '/lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_global_ens_atmos_p
rep.112921098.cbqs01/cmce/pattern..348': No such file or directory
```

**Comment by PerryShafran-NOAA** [comment]
I believe that I have found a potential source of this issue.  I needed to change a variable $gens_cyc to $gens_ihour.  Re-running that.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Good find! I hope that will do the trick!

**Comment by PerryShafran-NOAA** [comment]
Changed a variable that was incorrect (gens_cyc needed to be changed to gens_ihour).  Looked for ERROR, "No such file" and "not found" and none of those appeared in the output.

**Comment by ShelleyMelchior-NOAA** [comment]
Excellent. I cloned your fork and checked out the branch on dogwood as emc.vpppg.
HOMEevs=`/lfs/h2/emc/vpppg/save/emc.vpppg/forSM/PR409/EVS`
I adjusted the global_ens_atmos_prep jobs to use the pridev queue: `#PBS -q pridev`
I adjusted COMOUT to write to a new unique location: `/lfs/h2/emc/vpppg/save/${USER}/forSM/PR409/$NET/$evs_ver_2d`.
I built the exec/ dir.
I linked the fix/ dir.
Anything else I need to know before I run this?

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA Set COMIN to this:  

export COMIN=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/com/$NET/$evs_ver_2d

I don't know if prep uses any existing prep data, but you'll need to add the "com" in order to run this job.

**Comment by ShelleyMelchior-NOAA** [comment]
Ok, I have made all of the changes. I will try to submit this job as user emc.vpppg.

**Comment by ShelleyMelchior-NOAA** [comment]
OK, the process is running on dogwood
```
125378654.dbqs01               emc.vpppg       pridev          jevs_global_en*   160794    1    83  350gb 06:00 R 00:01
```
```
emc.vpppg@dlogin05:/lfs/h2/emc/ptmp/emc.vpppg/PR409_out> ls -ltr
total 780
-rw-r--r-- 1 emc.vpppg emc 795366 Jan 17 18:11 jevs_global_ens_atmos_prep.o125378654
```

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA Are you running this PR in the save directory?  Please note that the Files quota is nearing 98% full.  I suggest moving processing to noscrub.

```
Project/Team Path               %GBUsed     GBUsed    GBSfQta    GBHdQta   %Files       FilesUsed      FilesSfQta      FilesHdQta
/lfs/h2/emc                          nA          0        def          0        0               0               0               0
/lfs/h2/emc/vpppg                    nA          0        def          0        0               0               0               0
/lfs/h2/emc/vpppg/save              7.7        157       2048       2252       98          403638          409600          450560
/lfs/h2/emc/vpppg/noscrub          54.5      81801     150000     165000       64        19310780        30000000        33000000
/lfs/h2/emc/ptmp                   19.4     203520    1048576    1153433        0         1439291       209715200       230686720
/lfs/h2/emc/stmp                    8.1      24903     307200     337920        3         1898846        61440000        67584000
```

**Comment by ShelleyMelchior-NOAA** [comment]
I killed the process and restarted it after directing COMOUT to use noscrub. 
COMOUT=`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/forSM/PR409/evs/v1.0/prep/global_ens/atmos.20240115`
This will take another round to fully verify. But, FWIW, I looked through the log file of the killed process.

- It got through 2:12 before I had to kill it.
- There were 23,336 grep commands. Of note, this number compares with the number of grep commands I found in my run on cactus last Friday (23,337). I think the processing made it through the section that Perry modified with the consolidated grep commands.
- There are none of the errors I was seeing in my first run on Friday.

**Comment by PerryShafran-NOAA** [comment]
Thank you.  I'm sorry you had to do that, but I didn't want to fill the disk.

**Comment by ShelleyMelchior-NOAA** [comment]
Strange ... the re-run ended very prematurely. `/lfs/h2/emc/ptmp/emc.vpppg/PR409_out/jevs_global_ens_atmos_prep.o125402995`

**Comment by PerryShafran-NOAA** [comment]
Did you move the code to noscrub also?  

```
+ /apps/ops/prod/libs/intel/19.1.3.304/metplus/5.0.1/ush/run_metplus.py -c /lfs/h2/emc/vpppg/save/emc.vpppg/forSM/PR409/EVS/parm/metplus_config/machine.conf -c /lfs/h2/emc/vpppg/save/emc.vpppg/forSM/PR409/EVS/parm/metplus_config/prep/global_ens/atmos_grid2grid/PcpCombine_fcstGEFS_APCP24h.conf
01/17 20:50:56.835 metplus (config_metplus.py:102) INFO: Starting METplus configuration setup.
01/17 20:50:56.836 metplus (config_metplus.py:183) ERROR: Invalid argument: /lfs/h2/emc/vpppg/save/emc.vpppg/forSM/PR409/EVS/parm/metplus_config/machine.conf
01/17 20:50:56Z jevs_global_ens_atmos_prep-metplus: ERROR:  Invalid argument: /lfs/h2/emc/vpppg/save/emc.vpppg/forSM/PR409/EVS/parm/metplus_config/machine.conf
01/17 20:50:56.836 metplus (config_metplus.py:183) ERROR: Invalid argument: /lfs/h2/emc/vpppg/save/emc.vpppg/forSM/PR409/EVS/parm/metplus_config/prep/global_ens/atmos_grid2grid/PcpCombine_fcstGEFS_APCP24h.conf
01/17 20:50:56Z jevs_global_ens_atmos_prep-metplus: ERROR:  Invalid argument: /lfs/h2/emc/vpppg/save/emc.vpppg/forSM/PR409/EVS/parm/metplus_config/prep/global_ens/atmos_grid2grid/PcpCombine_fcstGEFS_APCP24h.conf

```

**Comment by ShelleyMelchior-NOAA** [comment]
Oh! When I wiped out the forSM/ dir in save, that wiped out HOMEevs! Doh! Ok, fixing.

**Comment by ShelleyMelchior-NOAA** [comment]
Ok, everything is set back up again. The run is underway.
logfile: `/lfs/h2/emc/ptmp/emc.vpppg/PR409_out/jevs_global_ens_atmos_prep.o125425270`

```
125425270.dbqs01               emc.vpppg       pridev          jevs_global_en*    59874    1    83  350gb 06:00 R 00:01
```

**Comment by ShelleyMelchior-NOAA** [comment]
The re-run completed during non-work hours. Here is the summary.
logfile: `/lfs/h2/emc/ptmp/emc.vpppg/PR409_out/jevs_global_ens_atmos_prep.o125425270`
There are 23,336 grep commands. The same log file in the nco para contains 371,270 grep commands.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/forSM/PR409/evs/v1.0/prep/global_ens/atmos.20240115`
The prep file counts match exactly between this test run and the nco para for cmce, ecme, gefs, osi-saf.
I no longer see any of the "No such" system error statements.
I think this PR is good to go in its current state.

**Comment by PerryShafran-NOAA** [comment]
I agree, we can go ahead and merge.  Things look good!

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yield expected results. This PR is approved for merge.

**Pull request merged**
