### PR TITLE
Feature/wafs atmos

### PR DESCRIPTION
**Pull request by YaliMao-NOAA**
Update WAFS verification to VE, MET-11.0.2, and METplus-5.0.1

WAFS plotting will not go operational with EVSv1, but the plotting code will follow EVS standards, it's going to be used for developmental run. WAFS stat will go operational with EVSv1

Separate WAFS verification from global_det.
- Inside code, change to COMPONENT=wafs and RUN=atmos
- script files are renamed
- WAFS verification has its own vertical structure:
  - ecf/wafs
  - jobs/wafs
  - scripts/wafs
  - ush/wafs
  - parm/metplus_config/wafs
  - parm/evs_config/wafs

Speed up stat runtime by adding more MPMD processes 
- On top of observation data (GFS GCIP), run at resolutions (0P25 1P25) parallel and centers (blend UK US) parallel for icing. 
- Increase number of CPUs from 2 to 7
- Runtime is less than 15 minutes

Speed up plotting runtime by adding more MPMD processes
- Run on different domains (9 subdomains + 1 global) parallel instead of sequentially
- Multiplied the number of CPUs by the number of domains, increased from 4 to 40.
- Runtime is down from 40 minutes to 16

Add email alerts when observation data are missing

Modify Python code to plot a domain at one time. Global (all) is a domain which collects data of all subdomains and is plotted once.

## Pull Request Testing ##

- [ x] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ Yes] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [Yes ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [x ] Complete the PR description above.
- [ x] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [x ]  Instructions provided on how to run
- [ x]  Developer's name is replaced by ${user} where necessary throughout the code
- [x ]  Check that the ecf file has all the proper definitions of variables
- [ x]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ x]  Check to see that the output directory structure is followed
- [ x]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by YaliMao-NOAA** [comment]
The log file of stat test run is on Cactus: (runtime is 13 minutes)
/lfs/h2/emc/vpppg/noscrub/yali.mao/git/EVS/jevs_wafs_stats.o58835874
The log file of plot test run is on Cactus:
/lfs/h2/emc/vpppg/noscrub/yali.mao/git/EVS/jevs_wafs_plots.o58838745

**Comment by PerryShafran-NOAA** [comment]
I am beginning testing of this PR.

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, @YaliMao-NOAA ,

I have completed the stats and plots jobs for this PR.  Your stats job ran for 13 minutes, which is close to what you had expected.  Your plots job ran for 39 minutes, though your comments above seem to imply that you reduced the runtime for plots down to 16 minutes.  I copied your existing wafs files (which amounted to about 5-6 days' worth) - perhaps more files adds in more time for the plots?  How many days' data did you use for your test runs?

In the meantime, please examine the output:

stats:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/wafs/*20230529*
plots: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/wafs/atmos.20230529

The .o files are here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_wafs/ecf/wafs/stats and /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_wafs/ecf/wafs/plots.

Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA Thank you for the testing. Both stat files and plots look good to me ((stat file should be /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/wafs/wafs.20230529).
As to the plotting runtime, I agreed with what you guessed, the more days of data, the longer the runtime. When I did the first test, it took 16 minutes when plotting one day of data; but it turned out it took longer time when processing more days of data.
The WAFS plotting is going to be more than one year, the runtime will be much longer. But it's not an issue for EVSv1 since WAFS plotting will not be implemented operationally with EVSv1 as agreed among Jason,  @AliciaBentley-NOAA and @HuiyaChuang-NOAA

**Comment by PerryShafran-NOAA** [comment]
Ah, good point on the plotting capability remaining in dev!  

Just wanting to make sure, since wafs is being taken out of global_det:  are all wafs/aviation files removed from global_det in this PR?  I want to ensure that these items are no longer there.  Otherwise, looks like we can merge this one rather quickly.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, @YaliMao-NOAA:

If you could do one more thing before merge.  We are required to have the first line of the python scripts start with this line:

#!/usr/bin/env python3

Can you make these changes in the .py python scripts?  

Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA Yes, in this PR, wafs has been taken out of global_det and has its own folder in each folder of the EVS vertical structure.
I added '#!/usr/bin/env python3' as the first line of all Python scripts, I did a test run and had the same plotting results as yours.

**Comment by PerryShafran-NOAA** [comment]
Can you add those python scripts to this github branch so they can be merged in?  

Thanks!

Perry

**Comment by PerryShafran-NOAA** [comment]
@YaliMao-NOAA - it would be great if you could add the python scripts with the header into your repository ASAP so I can get this merged.  

Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA I just did it. Sorry I pushed to a wrong branch last Friday.

**Comment by PerryShafran-NOAA** [comment]
Excellent, thanks!  Approving and merging.

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
