### PR TITLE
EVS v1.0.10: bugfix/global_det_wave_plots_si

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

NCO had a failure in prod (v1.0.9) and para (v1.0.10) on 8/1/2024 in evs_global_det_wave_grid2obs_plots_31days. It came from the scatter index forecast mean plots where all value were over 200. There had been additions to ignore values greater than 200, which resulted in an empty array in this case and cause the jobs to fail.

- [ ] Describe testing already performed for this Pull Request:</br>

> I ran some a quick test by running the failing job.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **8/12/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by malloryprow** [comment]
Assigning to @ShelleyMelchior-NOAA for now, but we can assign to @PerryShafran-NOAA next week if we need.

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/global_det_wave_plots_si`.

**Comment by ShelleyMelchior-NOAA** [comment]
I have made the instructed modifications and have run the plots driver. The run is underway, just about 2 mins in.
```
qsub lfs/h2/emc/vpppg/noscrub/shelley.melchior/githubwkspc/forks/mr/EVS/dev/drivers/scripts/plots/global_det/jevs_global_det_wave_grid2obs_plots_31days.sh
```
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_grid2obs_plots_31days_00.o146419691`
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/global_det/wave.20240731`

**Comment by malloryprow** [comment]
Watching the log file progress and will report back when it is done!

**Comment by malloryprow** [comment]
Looks good! The image counts in the final tar file is what is expected and the log file does not contain the error that was noted by NCO.

**Comment by ShelleyMelchior-NOAA** [comment]
Great! I also reviewed the code change and it appears OK to me. Should we wait for Alicia to also review, as an assigned reviewer, before I do the merge?

**Comment by malloryprow** [comment]
Yes, let's wait for her

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The changes look appropriate. This PR is approved for merge.
Merge will happen after Alicia, the other assigned reviewer, has looked at the changes.

**Review by AliciaBentley-NOAA — APPROVED** [review]
The changes look good to me! Thanks for getting to the bottom of this so quickly!

**Pull request merged**
