### PR TITLE
Updating build.ver and run.ver with PrgEnv-intel version upgrade

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

The version of PrgEnv-intel is being updated to version 8.3.3 in the code.  Changes were made in run.ver and build.ver.  

- Compiled the code using build.sh
- Ran tests on a prep step (aqm), a stats step (global_det), and a plots step (subseasonal).  All worked as expected.  

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- Run sorc/build.sh to see that exec files are being built.  Compare to the exec files in the emc.vpppg parallel code base.  
- Run a prep, stats, and plots step across various components, perhaps different to my tests.  See that the codes run properly.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP.  

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by malloryprow** [comment]
Test with build.ver to 8.3.3 in my personal EVS copy matches the sizes of those in the parallel.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Per Lin's email:

Alicia: Should we remove ["export KEEPDATA"] everywhere in EVS (even from the j-jobs) so that it's only in ecf/include/head.h?
Lin: Yes. You may wire in KEEPDATA in vpppg official parallel development only driver. (which I take to mean run.ver)

Can you please add _**export KEEPDATA="YES"**_ into run.ver so that people can delete all instances of "export KEEPDATA" in their components of EVS?

@ShelleyMelchior-NOAA Tagging Shelley for her awareness!

**Comment by PerryShafran-NOAA** [comment]
I can do that.

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/PrgEnv`. I will run tests soon.

**Comment by malloryprow** [comment]
Should KEEPDATA be set to NO? All drivers had previously had it set to NO.

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow Lin Gan recently asked us to set _export KEEPDATA=YES_ so that he can continue debugging EVS. Thanks for asking!

**Comment by malloryprow** [comment]
We will need to keep an eye on ptmp then. It is currently sitting at 90%.

**Comment by PerryShafran-NOAA** [comment]
Our $DATA directories should be residing in stmp, not ptmp.

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow Thanks for the heads up on that. After this PR in merged, should someone with emc.vpppg access go in and do a clean-up of old files in the emc.vpppg parallel?

**Comment by ShelleyMelchior-NOAA** [comment]
I tested prep w/ `dev/drivers/scripts/nfcens/prep/jevs_nfcens_wave_grid2obs_prep.sh`. It ran to completion and the prep results match emc.vpppg.

**Comment by ShelleyMelchior-NOAA** [comment]
I tested stats w/ `dev/drivers/scripts/nfcens/stats/jevs_nfcens_wave_grid2obs_stats.sh`. It ran to completion and the stats results match emc.vpppg.

**Comment by ShelleyMelchior-NOAA** [comment]
I tested plots w/ `dev/drivers/scripts/nfcens/plots/jevs_nfcens_wave_grid2obs_plots.sh`. It ran to completion and the plots results match emc.vpppg.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests produced expected results. This PR is approved for merge.

**Pull request merged**
