### PR TITLE
Bugfix/regional rev2

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

This PR addresses issues 50, 60, 62, 64, and 68 noted in the Google Doc titled "EVS v1.0 issues".  Information about the cause and fix of each:

* 39 - Logs for Hawaii plots mention that hrrr data are not found (expected because hrrr isn't being verified over hawaii). _Fix:_ Remove hrrr from the list of models compared on Hawaii plots
* 50 - After extended periods of missing data, missing file checks for spc_otlk masks fail. _Fix:_ Refine the logic for checking needed data.  
* 60 - An earlier fix of href check files logic introduced another logic problem in the same file that causes the quoted job to consistently exit with an error message. _Fix:_ Rearrange nested for-if blocks to fix the href member counters in two sections
* 62 - WARNING message is outputted when ccpa data are not yet available to grab.  This should not be a WARNING because this is expected behavior.  cam precip prep runs several times a day, grabbing what is available if it is available, to be used by the stats job, which is run later. _Fix:_ Changed the message from a WARNING to just a log message.
* 64 - WEASD and TCDC fields yield multiple records when grib2 files are searched for fields that match requests made in the METplus config files, and, each time, the first match is chosen arbitrarily. _Fix:_ Set GRIB2_ipdtmpl_index and GRIB2_ipdtmpl_val options as needed to select exactly the needed field.  This was complicated by the fact that METplus 5.0.1 has a bug where these options are not used if the pcp_combine method is set to "SUBTRACT"; therefore, a USER_DEFINED subtract command needed to be written and tested.  The bug is fixed in 5.1.0
* 68 -  The href script that checks for available members looks for files that never exist (e.g. href member 09 @ f42). _Fix:_ Same as the fix used for issue 60.

The affected jobs were tested and ran successfully.

This PR also addresses the following issues:
* headline plots are outputted to the atmos.YYYYMMDD COMOUT directory, which differs from other components. _Fix:_ Change to _headline_.YYYYMMDD
* Minor typo "prep" in the header of the cam stats modulefiles script. _Fix:_ "stats"
* Mismatched interpolation method and width for several cam-ens grid2obs METplus jobs, an issue that was flagged before for another job in the issues document. _Fix:_ correct width "4" to "2" to match bilinear interp method
* 63 - Part of issue 63 included a warning that OMP_NUM_THREADS would be overwritten. _Fix:_ Set OMP_NUM_THREADS=1 in ecf and dev driver scripts

---
- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

### (1) Set up jobs 
•	symlink the EVS_fix directory locally as "fix"
•	In all driver scripts, point all exports of "HOMEevs" to your EVS test directory
•	In all stats and plots driver scripts, change COMIN to the parallel directory (`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`)

### (2) Test Jobs
Use the following to submit all jobs: `qsub –v vhr=00 `

From your EVS testing directory, the following scripts should be run using the setup in step (1):
```
dev/drivers/scripts/prep/cam/jevs_cam_hireswarw_precip_prep.sh
```
```
dev/drivers/scripts/stats/cam/jevs_cam_href_spcoutlook_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_grid2obs_stats.sh
```
```
dev/drivers/scripts/plots/cam/jevs_cam_headline_plots.sh
```

_[Total: 1 prep job; 6 stats jobs; 1 plots job]_

### (3) Review
- I'll check for red flags:
```
check="FATAL\|WARNING\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|empty\|failed\|unexpected\|exceeded"
grep "$check" $outfile
```
- I'll also verify that the corresponding issues in the EVSv1.0 issue doc no longer exist

---
- [x] Has the code been checked to ensure that no errors occur during the execution? **NO**

---
- [x] Do these updates/additions include sufficient testing updates? **YES**

---
- [x] Please complete this pull request review by **ASAP**.</br>

---
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/regional_rev2`.

**Comment by ShelleyMelchior-NOAA** [comment]
I have set up the runs for the following tests. I did not look at results. There may be VDATE issues since I am running in early GMT of 20240125.

**headline plots**
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_headline_plots.o113862954`

----

**hireswarw_precip prep**
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_hireswarw_precip_prep.o113863`

----

**href_spcoutlook stats**
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_href_spcoutlook_stats.o113863510`

----

**hireswarw_snowfall stats**
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_hireswarw_snowfall_stats.o113863568`

----

**hireswarwmem2_snowfall stats**
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_hireswarwmem2_snowfall_stats.o113864388`

----

**hireswfv3_snowfall stats**
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_hireswfv3_snowfall_stats.o113864389`

----

**hrrr_snowfall stats**
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_hrrr_snowfall_stats.o113864393`

----

**hrrr_grid2obs stats**
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_hrrr_grid2obs_stats.o113864394`

**Comment by MarcelCaron-NOAA** [comment]
Thanks @ShelleyMelchior-NOAA!
🚩 headline plots - Can we run this again?  The COMOUT change worked, but I added a simple fix that would wrap up issue 39
✔️  hireswarw_precip prep
✔️  href_spcoutlook stats
✔️  hireswarw_snowfall stats
❌ hireswarwmem2_snowfall stats - Minor issue.  Should work now
❌ hireswfv3_snowfall stats - Should work now
✔️  hrrr_snowfall stats
✔️  hrrr_grid2obs stats

**Comment by ShelleyMelchior-NOAA** [comment]
5 out of 8 on the first go isn't too bad! Here are the re-runs.
```
113927223.cbqs01               shelley.melchi* dev             jevs_cam_hires*    29765    1   128  128gb 00:45 R 00:02
113927224.cbqs01               shelley.melchi* dev             jevs_cam_hires*   177867    1   128  128gb 00:45 R 00:02
113927375.cbqs01               shelley.melchi* dev             jevs_cam_headl*   108655    1   128    --  00:30 R 00:00
```

headline plots
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_headline_plots.o113927375`

hireswarwmem2_snowfall stats
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_hireswarwmem2_snowfall_stats.o113927223`

hireswfv3_snowfall stats
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_hireswfv3_snowfall_stats.o113927224`

**Comment by MarcelCaron-NOAA** [comment]
✔️   headline plots
❌ hireswarwmem2_snowfall stats - Apologies, typo.  Fixed, and I ran the full jobs this time and they completed successfully
❌ hireswfv3_snowfall stats

**Comment by ShelleyMelchior-NOAA** [comment]
ok, 6 out of 8!

hireswarwmem2_snowfall stats
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_hireswarwmem2_snowfall_stats.o113933496`

hireswfv3_snowfall stats
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_hireswfv3_snowfall_stats.o113933497`

**Comment by MarcelCaron-NOAA** [comment]
✔️   hireswarwmem2_snowfall stats 
✔️   hireswfv3_snowfall stats

👍 Jobs completed successfully, no red flags, and the WARNINGS indicated in doc'd issue 64 are no longer there.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yielded expected results. This PR is approved for merge.

**Pull request merged**
