### PR TITLE
Replace error logs with warnings.

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
## Pull Request Testing ##
This PR addresses a bugfix issue for EVS-RTOFS. The EVS should not send fatal errors in ops when the stat files are missing.

- [ ] Describe testing already performed for this Pull Request:</br>
 While the top-level stats directory exists and there are other .stats files from other dates there, the code was tested for a date with no stats files on that date and produced no error message.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
1- To test this PR, you can only run the driver scripts for plots step.
2- Clone my fork in your local and checkout branch bugfix/rtofs_plots_ush.
3- Set the $COMIN to where the stats files for evs_bugfix are located.
4- Find the driver scripts for plots step at:  EVS/dev/drivers/scripts/plots/rtofs/* and run them.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes]**

- [ ] Please complete this pull request review by **[06/11/2024]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA I am working on your PR now.  Jobs are running.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA I tried to run your PR while pointing to the production stats directory.  I made an error and pointed to a directory that does not exist.  However, this is kind of fortuitous, since your PR was meant to fix an error when stats are missing, which just occurred.

You can check the .o files to see if there are any fatal errors:    /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr489test/EVS/dev/drivers/scripts/plots/rtofs

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA , I still see the ERROR, but It makes sense to me since the top level stats directory does not exist. The df_preprocessing.py was set for this error at line 87 here: [https://github.com/SamiraArdani-NOAA/EVS/blob/bugfix/rtofs_plots_ush/ush/rtofs/df_preprocessing.py#L87].

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA Hmm, I'd think we'd want that error fixed as well?  I'm not sure.

In the meantime, I'll set the correct directory and re-run.  Which date did you run for which there are no stats files?

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : I ran for 20240607 on Friday (20240607) when there was no stats produced on that date but we still had the stats directory with stats files from previous dates.
From the email discussions, I think this is what we expect, Right?

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA OK, so you don't need to make any more changes.  Having a fatal error when the directory is missing is actually good.  

I'll point to the bugfix directory, which has missing files due to the short archive.  (Which is what you asked for in the first place, which makes more sense!)

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA The runs have finished.  Check the latest .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr489test/EVS/dev/drivers/scripts/plots/rtofs

Check to see that there *are* missing files (since the archive doesn't go for all 60 days) and check to see that there are no errors as a result.

The tarballs are here: /lfs/h2/emc/ptmp/perry.shafran/evs_bugfix/v1.0/plots/rtofs

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : I checked the .o files and there were without any ERROR (as expected). Also, the tarballs were identical with those in prod directory. I did not find any WARNING messages as well. I am not sure how to check the changes for Warning messages due to the missing files.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA I'm not sure what you are asking in your last sentence?  I'm looking at one of the log files from the plot runs (/lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_rtofs_aviso_grid2grid_last60days_plots.134866100.cbqs01/logs/rtofs/verif_plotting.20240610130917_48233.log), and there are no Warning messages there.  I do not think that there are any Warning messages anywhere.  Should there be?

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA I think @SamiraArdani-NOAA  is asking how we can produce some WARNING messages so that functionality can also be tested. Will a WARNING be produced if a stats file within the directory is temporarily moved, for example?

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA , Correct, you are right. I should not see the Warnings in the plots steps.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA @AliciaBentley-NOAA In my experience, the Empty Dataframe warning occurs only when there is *no* data that exists.  If there is a single missing stats file during the plot period, it usually just skips over that file and I don't see any Warnings.  

Since rtofs stats are not being generated in bugfix (stats is linked to production), I will have to create a directory with no stats data in there and see what happens.  That should be easy enough.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA, Yes, This is what I wanted to test:  
https://github.com/SamiraArdani-NOAA/EVS/blob/202ec4f738f0c6d6dd3e67f721704406a0a6d1c4/ush/rtofs/df_preprocessing.py#L94C1-L102C21

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA Empty stats directories also give FATAL ERRORs, which I think is what we want.  

I will now try doing verification with VDATE=20240610, which is today, and see what happens.  That should truly mimic your test.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA I ran with VDATE=20240610, just as you ran, and compared it to the evs_bugfix directory's stats.  I do not see any Empty Dataframe warnings.  

Please look at the latest .o files in the same directory as well as the tarballs. Let me know if this is what you saw in your own tests.  This is test that should be closest to your own test.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : No ERROR and NO WARNING was observed. The tarballs are the same with prod (as expected). 
I just learned this: In order to simulate the situation that the WARNING messages happen, I think we need to create a .stat file with partially/totally empty DataFrames. This means the individual stat file exist with the correct naming but some or all of the columns in the .stat files are empty. Am I right?

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA I am cc'ing @MarcelCaron-NOAA here, who might be able to provide more insight on how to hit that section of code.  I have had empty dataframes before, but that was when a file had incorrect data in it (like when I had HRRR rather than hrrr in it, but the code was searching for hrrr).  That type of stuff.  It usually happens when the code reads readable stats files but can pull out no data during the pruning process.  

The good thing is that the code produces no fatal errors when data is missing, as in the situations you and I have tested.  When you originally tested on 20240607, did you see any Warnings?

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : I did not see any Warnings in my test on 20240607.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA OK, then - what would you like to see for a successful test?  Looks like I repeated the results of your test, which is good.  If you need to see the warning, you would need to produce it yourself and then have me repeat that test.

**Comment by MarcelCaron-NOAA** [comment]
> @PerryShafran-NOAA, Yes, This is what I wanted to test: https://github.com/SamiraArdani-NOAA/EVS/blob/202ec4f738f0c6d6dd3e67f721704406a0a6d1c4/ush/rtofs/df_preprocessing.py#L94C1-L102C21

> @SamiraArdani-NOAA I am cc'ing @MarcelCaron-NOAA here, who might be able to provide more insight on how to hit that section of code. I have had empty dataframes before, but that was when a file had incorrect data in it (like when I had HRRR rather than hrrr in it, but the code was searching for hrrr). That type of stuff. It usually happens when the code reads readable stats files but can pull out no data during the pruning process.

There are a few checks in df_preprocessing:

1. Is there a stats directory? ERROR if False
2. Is there anything at all in the stats directory? ERROR if False
3. Is there a pruned stat file for the given model (i.e. were there stat files for the given model in the stats directory)?  WARNING if False
4. Is there any data in the pruned stat file? WARNING if False
5. Is there any leftover data after filtering for ____?  WARNING if False  **<-- This check is the block of code @SamiraArdani-NOAA indicated above.**  

A possible way to test that would be to attempt to plot a var_name or domain (e.g., VX_MASK="DDDD") that definitely doesn't exist in the stats files.  During the filtering step for that data column, all leftover data will be removed, and check 5 should fail with a WARNING.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : I tested the code for warning by generating the empty stat file. The .o file is located here: /lfs/h2/emc/ptmp/samira.ardani/jevs_rtofs_smos_grid2grid_last60days_plots.o134902481. Please search for "WARNING".

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : My files are located here: /lfs/h2/emc/vpppg/noscrub/samira.ardani/evs/v1.0/stats/rtofs/ smos.20240607 and rtofs.20240607.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA OK, if I do the same test that Samira did by having an empty stats file, would that suffice to make this test?

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA, @MarcelCaron-NOAA : Thanks for your comments in this PR. I see that the test was successful and produced expected results.

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA It doesn't look like [this block](https://github.com/SamiraArdani-NOAA/EVS/blob/202ec4f738f0c6d6dd3e67f721704406a0a6d1c4/ush/rtofs/df_preprocessing.py#L94C1-L102C21) was accessed, since it checks across subsets of the data after already checking for empty data, but **having an empty stats file will suffice to test that the code doesn't send fatal errors in ops when the stat files are missing/empty**.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA @MarcelCaron-NOAA OK, I will do one more test by using an empty stats file.  I will try it for aviso, specifically.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA @MarcelCaron-NOAA Can you check the latest output?  I'm still not entirely sure I'm hitting the warning message.  I ran this for VDATE=20240607, on aviso. 

You can see the latest .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr489test/EVS/dev/drivers/scripts/plots/rtofs/jevs_rtofs_aviso_grid2grid_last60days_plots.o134914985

The empty stats file is here:
/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs_bugfix/v1.0/stats/rtofs/rtofs.20240607

**Comment by MarcelCaron-NOAA** [comment]
@PerryShafran-NOAA No warning, but that's because the code found stats elsewhere to work with (e.g., 20230606).  If the test here is for empty stats files to be allowable in the plots code, then seems like a success.

**Comment by PerryShafran-NOAA** [comment]
@MarcelCaron-NOAA  - OK so there has to be *only* empty files for the whole time period.  Let me try one more time then by doing that.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA @MarcelCaron-NOAA OK, that seemed to work!

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr489test/EVS/dev/drivers/scripts/plots/rtofs/jevs_rtofs_aviso_grid2grid_last60days_plots.o134993527

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA, @MarcelCaron-NOAA : It sounds like a success.

**Comment by PerryShafran-NOAA** [comment]
Excellent!  Let me go ahead and approve the code and merge it in.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
