### PR TITLE
Fixing bug in ecme processing file for global_ens prep

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

In PR #409, several ush scripts for global_ens prep were modified in order to reduce the number of greps.  In the course of making those changes, a line was inadvertently removed from the code, causing input ecme files to be missing a lot of data.  This PR puts that line back into the evs_process_atmos_ecme.sh script in the ush directory.  

- [ ] Describe testing already performed for this Pull Request:</br>

Compared runs with the current develop version vs the fixed version and saw that the output ecme files were of the correct size.  

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run the global_ens prep script.  Examine the output ecme files to ensure that they are all the correct size.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP.  

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checkout out branch `bugfix/emce`.

**Comment by ShelleyMelchior-NOAA** [comment]
I have set up and kicked off the global_ens prep driver script. This process takes a while to complete. Please watch the output log file and the output ecme files to ensure that they are all the correct size. @PerryShafran-NOAA , @StevenSimon-NOAA 

logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_ens_atmos_prep.o113927683`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_ens/atmos.20240123/ecme`

----

A good follow on test would also be to run `jevs_global_ens_ecme_atmos_grid2grid_stats.sh` to make sure that the following warning is not present. It is this warning that alerted Steve to the change in the ecme data files from the prep processing. (From PR #416)
```
WARNING: process_n_vld() -> no data found for forecast field "GH/P500" in file "/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/global_ens/atmos.20240117/ecme/ecme.ens50.t00z.grid4.f108.grib1"
```

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA @StevenSimon-NOAA Although the run is not finished yet, I am looking at the *grid4* data in the COMOUT directory, and did notice that all the ecme grid4 data is now the correct length.  @StevenSimon-NOAA can take a quick look at the COMOUT directory to see that the content is OK as well, but I feel like this fix is now working OK.  I did a wgrib on one of the files, and the GH/P500 data now exists in the ecme output file.  

I think you can run the ecme stats job now, or wait until the entire prep job is finished to check to see if that error that you quote exists.  

I also synced my fork.

**Comment by StevenSimon-NOAA** [comment]
> /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_ens/atmos.20240123/ecme

I just wgribb'ed into five random ecme wgrib1 files in this directory. All 56 forecast variables are there and accounted for so far.

**Comment by ShelleyMelchior-NOAA** [comment]
Fantastic -- thanks for this update so far. The prep run is 2:45 in. Once it completes I will run the stats processing pointing to my local prep dir to confirm that the WARNING is no longer present.

**Comment by AliciaBentley-NOAA** [comment]
I approve this PR to be merged if the output looks good when it finishes running! @PerryShafran-NOAA @ShelleyMelchior-NOAA

**Comment by ShelleyMelchior-NOAA** [comment]
The prep job has completed. The full complement of files is in the COMOUT directory.
My test:
```
$ lltr /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_ens/atmos.20240123/ecme/ | wc -l
12003
```
NCO parallel:
```
[dlogin07 /lfs/h1/ops/para/com/evs/v1.0/prep/global_ens/atmos.20240123]$ ll ecme/ | wc -l            
12003
```

NEXT: I will run `jevs_global_ens_ecme_atmos_grid2grid_stats.sh` to assure there are no WARNINGs associated w/ the ecme data files generated in the prep processing.

**Comment by ShelleyMelchior-NOAA** [comment]
🎉 Good news! I ran the ecme grid2grid stats pointing to my local prep directory generated in this PR's test. There are no more WARNING messages.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_ens_ecme_atmos_grid2grid_stats.o113954622`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/global_ens/ecme.20240123`
The stats file is a lot smaller than what is in the NCO para, but that is b/c I ran on a much smaller prep archive.

My test:
```
$ ll /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/global_ens/ecme.20240123
total 444
-rw-r--r-- 1 shelley.melchior vpppg 452358 Jan 25 23:45 evs.stats.ecme.atmos.grid2grid.v20240123.stat
```

NCO para:
```
[dlogin07 /lfs/h1/ops/para/com/evs/v1.0/prep/global_ens/atmos.20240123]$ ll ../../../stats/global_ens/ecm
e.20240123/evs.stats.ecme.atmos.grid2grid.v20240123.stat 
-rw-rw-r-- 1 ops.para para 5006867 Jan 25 09:59 ../../../stats/global_ens/ecme.20240123/evs.stats.ecme.at
mos.grid2grid.v20240123.stat
```

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yield anticipated results. This PR is approved for merge.

**Pull request merged**
