### PR TITLE
Modify exevs_narre_plots.sh to add application logic to create DATA d…

### PR DESCRIPTION
**Pull request by lgannoaa**
Provide fix to EVS GitHub issue #168 by insert mkdir statement on top level script exevs_narre_plots.sh line 51.

This fix address EVS GitHub issue 168

## Pull Request Testing ##

- Describe testing already performed for this Pull Request:</br>
This fix is tested in WCOSS ecflow workflow by Lin Gan. The result have been reviewed by the narre plot code manager.
- [Yes] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [Yes] Do these updates/additions include sufficient testing updates? **[Yes or No]**

## Pull Request Checklist ##

- [X] Complete the PR description above.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@lgannoaa -- happy to finalize this PR. Please update branch `feature/evs-issue-168` with auth EVS develop.

**Comment by lgannoaa** [comment]
@ShelleyMelchior-NOAA , merged to upstream.

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks @lgannoaa  -- the merge has made this PR obsolete as all code is in agreement w/ auth  EVS develop.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
There are no code changes in relation to auth EVS develop.

**Pull request merged**
