### PR TITLE
Feature/fix_lsr_nans

### PR DESCRIPTION
**Pull request by LoganDawson-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

The ush script update was tested both on the command line and in the associated EVS job, and successful completion on the recent bad data was confirmed.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

1. If you don't still have them, grab cron drivers from [here](https://github.com/LoganDawson-NOAA/EVS_crons/tree/main). The relevant job can be submitted interactively to confirm successful execution.
2. In the jevs_cam_severe_prep.sh driver script, make the following updates to test on the old report file that includes NaNs:
```
export COMINspc=/lfs/h2/emc/vpppg/noscrub/logan.dawson
export VDATE=20230727
```
3. Run drive_jevs_cam_severe_prep.sh interactively (typically takes ~2-5 mins to complete)

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes]**

- [ ] Please complete this pull request review by **[asap]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Hi Logan! I have checked out your branch `fix_lsr_nans` and will begin testing.

**Comment by ShelleyMelchior-NOAA** [comment]
Hi Logan, I ran the cam severe prep processing as described in your PR testing instructions. Please review.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/cron.out/jevs_cam_severe_prep.o89360478`

**Comment by LoganDawson-NOAA** [comment]
Perfect. The logfile is clean and the output matches mine. We're good to go!

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
This PR is approved for merge.

**Pull request merged**
