### PR TITLE
bugfix/global_det_units

### LINKED ISSUE #573: global_det: Fix plots unit conversion for operations
We are going a bugfix code delivery to correct the unit conversions being done in plots. PR should be submitted to [evs.1.0.unit_fix](https://github.com/NOAA-EMC/EVS/tree/release/evs.1.0.unit_fix) and contain the fixes in #526.

### PR DESCRIPTION
**Pull request by malloryprow**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

This contains the fixes in #526 to a release branch for operations. Closes #573.

## Developer Questions and Checklist
* Is this a high priority PR? If so, why and is there a date it needs to be merged by?
> Somewhat. The faster this gets merge in the sooner we can deliver to NCO
* Do you have any planned upcoming annual leave/PTO?
> No
* Are there any changes needed for when the jobs are supposed to run?
> No

- [x] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [x] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [x] References the feature branch for `HOMEevs` are removed from the code.
- [x] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [x] Jobs over 15 minutes in runtime have restart capability.
- [x] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [x] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [x] Code is using METplus wrappers structure and not calling MET executables directly.
- [x] Log is free of any ERRORs or WARNINGs.

###  **Set-up**
1. Clone my fork and checkout branch bugfix/global_det_units
2. `ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix`
3. Uncomment `evs_ver` in versions/run.ver.

### ✅  **global_det atmos plots**
 4. `cd dev/drivers/scripts/plots/global_det`
 5. Run the following: `jevs_global_det_atmos_grid2grid_means_plots_31days.sh`, `jevs_global_det_atmos_grid2grid_precip_plots_31days.sh`,  `jevs_global_det_atmos_grid2grid_pres_levs_plots_31days.sh`, `jevs_global_det_atmos_grid2grid_sea_ice_plots_31days.sh`, `jevs_global_det_atmos_grid2grid_snow_plots_31days.sh`, `jevs_global_det_atmos_grid2grid_sst_plots_31days.sh`,  `jevs_global_det_atmos_grid2obs_pres_levs_plots_31days.sh`, `jevs_global_det_atmos_grid2obs_ptype_plots_31days.sh`, `jevs_global_det_atmos_grid2obs_sfc_plots_31days.sh`, and `jevs_global_det_atmos_headline_plots.sh`. 
> - Set `HOMEevs` to the location of the clone.
> - Set `COMIN` to `/lfs/h1/ops/prod/com/$NET/$evs_ver_2d`
> - Let me know when you are about to run and we can adjust `VDATE_END` if needed

### CODE REVIEW

**Review by AliciaBentley-NOAA — APPROVED** [review]
I have compared this PR to the previous unit fix PR that was merged into develop. This PR doesn't include the changes to [ush/global_det/global_det_atmos_long_term_util.py](https://github.com/NOAA-EMC/EVS/pull/526/files#diff-6f1ce66351f72596134ab94658ca12af3b2a436c23729a058645ad2167f19240), which is expected because the long-term plot scripts aren't included in prod EVS. Everything else looks consistent. I approve this PR for merge after it is tested. Thanks!

@malloryprow @PerryShafran-NOAA

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I'm sure you won't see these until tomorrow.  It's late in the day (after 3 pm) so I'm guessing we wouldn't have to adjust VDATE_END, or anything like that.  Just wanted to get this started if you return to work tomorrow.

**Comment by PerryShafran-NOAA** [comment]
The .o files will be located here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr581test/EVS/dev/drivers/scripts/plots/global_det

And the plot tarballs will be here:   /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_det, atmos.20241007 and headline.20241007

**Comment by malloryprow** [comment]
Going to get this sent up to EMCRZDM to the test website to review this morning.

**Comment by PerryShafran-NOAA** [comment]
Thank you!  Don't forget to sync fork while you're doing that.

**Comment by malloryprow** [comment]
This one should be good since it isn't off develop.

**Comment by PerryShafran-NOAA** [comment]
oh wait, never mind, this isn't a develop PR, you don't need to sync.

**Comment by malloryprow** [comment]
Ah, realizing that since the plots are a few days old I can't compare to the ops plots now. I want to make sure we get this right. Can we re-run for VDATE_END=20241008?

**Comment by PerryShafran-NOAA** [comment]
Yup, will do.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Most jobs are finished, with just two more jobs still ongoing.  You can start checking out some of the tar files.

**Comment by malloryprow** [comment]
✅ headline is good. atmos will take a little longer to untar everything and then review. Will update when that is done.

**Comment by malloryprow** [comment]
✅ atmos is good.

**Comment by PerryShafran-NOAA** [comment]
Excellent!  Let me then do the code check and then merge.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
