### PR TITLE
Feature/restart2

### PR DESCRIPTION
**Pull request by RoshanShrestha-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned @RoshanShrestha-NOAA 's fork and checked out branch `feature/restart2`.

**Comment by ShelleyMelchior-NOAA** [comment]
@RoshanShrestha-NOAA , please do a sync fork on this feature branch to bring in the latest changes in auth EVS develop. Thanks!

**Comment by ShelleyMelchior-NOAA** [comment]
I have adjusted the walltime on the nam and rap g2o stats jobs to reduce it to 00:59 (from 04:59). The jobs have been submitted and are running. Once the job stops early, I will reset the walltime to 04:59 and re-run.

**Comment by ShelleyMelchior-NOAA** [comment]
The jobs have completed and I can confirm the walltime exceedance.
`08/09/2023 21:40:47  M    walltime 3560 exceeded limit 3540`
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_nam_grid2obs_stats_00.o89172814`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_grid2obs_stats_00.o89172821`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/mesoscale` is empty
DATA=`/lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_mesoscale_nam_grid2obs_stats_00.89172814.dbqs01`

Now I will re-submit the 2 jobs w/ the walltime reverted to 04:59.

**Comment by ShelleyMelchior-NOAA** [comment]
The re-sbumissions are running. Please check the log files.
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_nam_grid2obs_stats_00.o89180139`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_grid2obs_stats_00.o89180161`

Do I need to adjust $evs_run_mode to trigger the restart processing? I am seeing this in the logfiles:
`RUN MODE: standalone`
`10 + '[' 7 -lt 1 ']'`
`10 + export FHR_GROUP_LIST=FULL`
`10 + FHR_GROUP_LIST=FULL`
`10 + echo ' Check for restart files reformat begin'`
` Check for restart files reformat begin`
`10 + '[' standalone = production ']'`

**Comment by RoshanShrestha-NOAA** [comment]
Hi Shelley, 

Yes, the restart feature works only in production mode. Please adjust it accordingly.

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks, @RoshanShrestha-NOAA ! I made the change and resubmitted. I see the copying happening, but I also see some rsync errors. Are these expected?
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_nam_grid2obs_stats_00.o89181527`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_grid2obs_stats_00.o89181526`

**Comment by RoshanShrestha-NOAA** [comment]
Hi Shelley,
I did not notice that error before. I am running a test in my end and I will check and report you back. 

Thank you.

**Comment by RoshanShrestha-NOAA** [comment]
The python script generated rsync command was behaving funny. rsync encountered permission issue while writing in the folder and resulted error. It's not clear what went wrong since recent maintenance of dogwood, or, updated modules. Python calling bash command was irregularly missing spaces, which made the generated commands useless. So, now the script is replace avoiding rsync, and now it is working.

**Comment by ShelleyMelchior-NOAA** [comment]
Ok! I will re-test today.

**Comment by ShelleyMelchior-NOAA** [comment]
@RoshanShrestha-NOAA , I restarted the restart test. Hah! Please keep an eye on the processing to assure all is functioning as expected.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/mesoscale`
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_grid2obs_stats_00.o89265443`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_nam_grid2obs_stats_00.o89265442`

**Comment by ShelleyMelchior-NOAA** [comment]
The restart test has concluded. Please let me know how things look, and also if the threshold adjustment is as expected.

**Comment by RoshanShrestha-NOAA** [comment]
Hi Shelley,
It appears that the concluded test is killed after 1 hr wall time. Could you please re-run again with wall time reset?

Also, NAM run was ended with error because of accidental '#' typo in there, which was corrected in [7eca937](https://github.com/NOAA-EMC/EVS/pull/186/commits/7eca937bb2bb72c0d051dd54ec8b003105905226)

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @RoshanShrestha-NOAA -- it does look like I missed the update for the typo. I have that pulled in now. However, the walltime was 04:59. The job did end after about an hour, but it doesn't appear to be because of time.

I have submitted the re-run.
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_grid2obs_stats_00.o89275153`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_nam_grid2obs_stats_00.o89275151`

**Comment by RoshanShrestha-NOAA** [comment]
Hi @ShelleyMelchior-NOAA, I got it. Both NAM and RAP runs were affected by the typo. Sorry, my bad.

**Comment by RoshanShrestha-NOAA** [comment]
Hi @ShelleyMelchior-NOAA , I have checked the re-run, everything looks good to me.

**Comment by ShelleyMelchior-NOAA** [comment]
Great! I just looked through the code review and all seems good. One question ... does `ush/mesoscale/mesoscale_util.py` have any other models in the mesoscale component using this file? I am having a hard time finding where this file is called/used.

**Comment by RoshanShrestha-NOAA** [comment]
Hi @ShelleyMelchior-NOAA, that ush/mesoscale/mesoscale_util.py file contains a lot of python utility functions that are being used everywhere, from all stats, to all plots. Without that file, nothing will run properly.

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks, @RoshanShrestha-NOAA , yes. I just can't find how it is used or called. I want to know if other developers in mesoscale use this file to confirm that changes will not impact their work.

**Comment by ShelleyMelchior-NOAA** [comment]
I think this is on me, not knowing python well. Is `import mesoscale_util` a call to run that script?

**Comment by RoshanShrestha-NOAA** [comment]
Yes, that's correct

**Comment by ShelleyMelchior-NOAA** [comment]
Just doing some due diligence to not have to do more work later, @malloryprow and @MarcelCaron-NOAA  , can you check `ush/mesoscale/mesoscale_util.py` to make sure this file is in good shape for g2g stats and plots processing?

**Comment by malloryprow** [comment]
Looks good to me; looks like only things have been added.

**Comment by MarcelCaron-NOAA** [comment]
Agreed, I don't think the additions to mesoscale_util can cause any problems for plots

**Comment by ShelleyMelchior-NOAA** [comment]
Great! THanks Marcel and Mallory.

@RoshanShrestha-NOAA , please do one more sync fork and then I can merge your PR.

**Comment by RoshanShrestha-NOAA** [comment]
Syncing is done

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All code changes are good. This PR is approved for merge.

**Pull request merged**
