### PR TITLE
feature/gfs_dpt2m_stats

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

This adds thresholds for SL1L2 stats 2 meter dewpoint stats for the grid2obs sfc jobs. This is done so the GFS can appear on the mesoscale headline plots.

- [ ] Describe testing already performed for this Pull Request:</br>
> I have been running the GFS grid2obs stats jobs in my cron.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

 
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Review by AliciaBentley-NOAA — APPROVED** [review]
The two lines changed in this PR and consistent with adding threshold values to the grid2obs dewpoint stats. I approve this PR once tested! @malloryprow

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I will start running some of these jobs before I go grab some lunch.  Am I good to just go ahead with the current VDATE?

**Comment by malloryprow** [comment]
Let's do VDATE=20240814, thanks!

**Comment by PerryShafran-NOAA** [comment]
Job is underway.  Now for some lunch.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The job is complete.

Please see the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr518test/EVS/dev/drivers/scripts/stats/global_det

And the stats output is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v2.0/stats/global_det/gfs.20240814

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I have also started the plot job for this PR.

**Comment by malloryprow** [comment]
Log is good and output matches mine!

**Comment by PerryShafran-NOAA** [comment]
Yay!  OK, so the plots job appears to be done.  

See the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr518test/EVS/dev/drivers/scripts/plots/mesoscale
And the plot output here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/mesoscale/headline.20240815

**Comment by malloryprow** [comment]
Plots look good!

[https://emc.ncep.noaa.gov//gmb/mpr/mesoscale_headline/evs.mesoscale.bcrmse_me_obsge40.dpt_z2.last90days.fhrmean_init00z.buk_conus_w.png](https://emc.ncep.noaa.gov//gmb/mpr/mesoscale_headline/evs.mesoscale.bcrmse_me_obsge40.dpt_z2.last90days.fhrmean_init00z.buk_conus_w.png)
[https://emc.ncep.noaa.gov//gmb/mpr/mesoscale_headline/evs.mesoscale.bcrmse_me_obsge30.dpt_z2.last90days.fhrmean_init00z.alaska.png](https://emc.ncep.noaa.gov//gmb/mpr/mesoscale_headline/evs.mesoscale.bcrmse_me_obsge30.dpt_z2.last90days.fhrmean_init00z.alaska.png)
[https://emc.ncep.noaa.gov//gmb/mpr/mesoscale_headline/evs.mesoscale.bcrmse_me_obsge50.dpt_z2.last90days.fhrmean_init00z.buk_conus_c.png](https://emc.ncep.noaa.gov//gmb/mpr/mesoscale_headline/evs.mesoscale.bcrmse_me_obsge50.dpt_z2.last90days.fhrmean_init00z.buk_conus_c.png)
[https://emc.ncep.noaa.gov//gmb/mpr/mesoscale_headline/evs.mesoscale.bcrmse_me_obsge50.dpt_z2.last90days.fhrmean_init00z.buk_conus_e.png](https://emc.ncep.noaa.gov//gmb/mpr/mesoscale_headline/evs.mesoscale.bcrmse_me_obsge50.dpt_z2.last90days.fhrmean_init00z.buk_conus_e.png)
[https://emc.ncep.noaa.gov//gmb/mpr/mesoscale_headline/evs.mesoscale.bcrmse_me_obsge50.dpt_z2.last90days.fhrmean_init00z.buk_conus_s.png](https://emc.ncep.noaa.gov//gmb/mpr/mesoscale_headline/evs.mesoscale.bcrmse_me_obsge50.dpt_z2.last90days.fhrmean_init00z.buk_conus_s.png)

**Comment by PerryShafran-NOAA** [comment]
OK, great, GFS is there!  Excellent!  

Code review is quick and hopefully we can get both sign offs.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Comment by PerryShafran-NOAA** [comment]
Alicia already signed off, so I shall merge....

**Pull request merged**
