### PR TITLE
bugfix/feature_global_det_rev4

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

1. Fixes EVS v1.0 Issues 87

- [ ] Describe testing already performed for this Pull Request:</br>
> Tested FNOMC atmos grid2grid stats job

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **02/09/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Getting started on this PR for the next 20  mins ...

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/feature_global_det_rev4`.

**Comment by ShelleyMelchior-NOAA** [comment]
The job has been submitted.
```
132054130.dbqs01               shelley.melchi* dev             jevs_global_de*      --     1    20   25gb 00:15 R   -- 
```
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_fnmoc_grid2grid_stats_00.o132054130`

@PerryShafran-NOAA can merge this PR once @malloryprow approves the results are satisfactory in case I am unavailable.

**Comment by AliciaBentley-NOAA** [comment]
Adding this email from Wei for additional context:

```
"Thanks, Mallory, for fixing this so quickly!

I've tested your changes with today's failure. It ran to completion as expected.
/lfs/h1/ops/para/output/20240206/evs_global_det_fnmoc_atmos_grid2grid_stats.o115477045

Thanks,
Wei"
```

@malloryprow @ShelleyMelchior-NOAA @PerryShafran-NOAA

**Comment by malloryprow** [comment]
> The job has been submitted.
> 
> ```
> 132054130.dbqs01               shelley.melchi* dev             jevs_global_de*      --     1    20   25gb 00:15 R   -- 
> ```
> 
> logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_fnmoc_grid2grid_stats_00.o132054130`
> 
> @PerryShafran-NOAA can merge this PR once @malloryprow approves the results are satisfactory in case I am unavailable.

All looks good and with Wei's additional testing and approval, we can merge this!

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yield anticipated results. This PR is approved for merge.

**Pull request merged**
