### PR TITLE
Updating analyses branch with the EVS VE and other changes

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

Tested the stats and the plots scripts with the new VE, upgraded METplus codes, adding in email for missing datasets, and upgraded plots code to updated versions.  

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run the run files so that all 24 hours of stats are run and a final stat file is written for the day.  Just qsub the run files.

In order to have full 31 days of stats, bring in the stats output from the parallel, and then qsub the plot job.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

Yes

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

June 1, 2023

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned Perry's fork and checked out his branch: `feature/analyses_ve`.

**Comment by ShelleyMelchior-NOAA** [comment]
Stats files have been generated for the three analyses, rtma, rtma_ru, urma. Please review in the COMOUT dir:
`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/analyses`
I am not sure where the jevs* log files are written, but here are the log files for the run scripts:
log files: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/run_*ma*stats.o*`

**Comment by ShelleyMelchior-NOAA** [comment]
I have begun running the plots ecf script. It is presently still running ...
log file: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rtma_plots_00.o58826212`
COMOUT: `/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/analyses`

**Comment by ShelleyMelchior-NOAA** [comment]
Gah! The plots job was killed b/c of wall time exceedance. I will start it again.
`=>> PBS: job killed: walltime 3621 exceeded limit 3600`

**Comment by PerryShafran-NOAA** [comment]
I'm double checking my own runs to see if they match yours.  There were some weird differences in the urma file, but that may have been due to the time some of these jobs ran.  I did not get urma or rtma ges files, but for those runs the anl files matched yours, and both the rtma_ru stat files matched yours.  

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
OK, let me know if you need me to re-run the stats processing.

**Comment by ShelleyMelchior-NOAA** [comment]
I re-ran the plots processing and hit wall clock limit again.

**Comment by PerryShafran-NOAA** [comment]
When Cactus is good, it should take about an hour or so.  Try expanding the wall clock time.

**Comment by PerryShafran-NOAA** [comment]
Also, please run the stats again.  I am seeing differences in a few of the stat files.  That can happen when the gather job runs before other runs are done.

What I'm doing is running hours 00 through 22 using the run_.sh files.  Then I'll run the 23Z run, which contains the gather job, when those are all finished.  You should do that too.  Then we can compare the stats.

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
stats have been re-run for all 3 analyses, first for fhr 0-22 and again for fhr 23.

COMOUT: `/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/analyses`

**Comment by PerryShafran-NOAA** [comment]
All stats are now identical to my own stats.  They are good.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran the analyses plots job and it completed and produced the expected tar file. Please review.
`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/analyses/atmos.20230524`

**Comment by PerryShafran-NOAA** [comment]
Plot tar file looks good!  I think we're set to merge here.

Perry

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Code looks good. Developer will add $maillist test (as a requirement to be set before processing continues) in subsequent PR.

**Pull request merged**
