### PR TITLE
feature/global_ens_wave_ncfens_missing_data

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- Removal of FIXevs from driver scripts
- General clean up of driver scripts
- Adjust driver script resources
- Add mail alerts for missing data in prep
- Add restart capabilites
- Add data directives in J-JOBS and make EE2 compliant
- Remove MET and METplus logging verbosity settings
- Remove "www" reference in METplus configs
- Fix NFCENS graphics names
- Remove unused files

- [ ] Describe testing already performed for this Pull Request:</br>

> I ran two days of the prep and stat for global_ens wave and nfcens. The global_ens wave output was the same as the emc.vpppg parallel; it sems nfcens is broken in the parallel.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

prep

> Run dev/drivers/scripts/global_ens/prep/jevs_global_ens_wave_grid2obs_prep.sh
> Run dev/drivers/scripts/nfcens/prep/jevs_nfcens_wave_grid2obs_prep.sh

stats
> Point COMIN to /lfs/h2/emc/vpppg/noscrub/mallory.row/${NET}/${evs_ver} in the following: dev/drivers/scripts/global_ens/stats/jevs_global_ens_wave_grid2obs_stats.sh, dev/drivers/scripts/global_ens/stats/jevs_global_ens_wave_grid2obs_stats.sh
> Run dev/drivers/scripts/global_ens/stats/jevs_global_ens_wave_grid2obs_stats.sh
> Run dev/drivers/scripts/nfcens/stats/jevs_nfcens_wave_grid2obs_stats.sh

plots
> Run dev/drivers/scripts/nfcens/plots/jevs_nfcens_wave_grid2obs_plots.sh

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **09/15/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Brought in the code and am beginning testing the prep.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow 

The prep runs have finished:

global_ens_wave:
.o file: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr238test/EVS/dev/drivers/scripts/global_ens/prep/jevs_global_ens_wave_grid2obs_prep.o81858034
output directory:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/wave.20230913/gefs/grid2obs

nfcens:
.o file: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr238test/EVS/dev/drivers/scripts/nfcens/prep/jevs_nfcens_wave_grid2obs_prep.o81858089
output directory: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/nfcens/wave.20230913/nfcens/grid2obs

Perry

**Comment by malloryprow** [comment]
Awesome will look! I didn't get any missing data emails so that is a good first sign!

**Comment by malloryprow** [comment]
Files count for each prep directory match mine!
✅ prep is good!

So for the stats I have the instructions telling you to point to my directory...I know that gave us trouble yesterday...not sure if you want to link my wave.* directories into the right places instead? Let me know what you would like to do! And I can put in the necessary commands here.

**Comment by PerryShafran-NOAA** [comment]
I think that I can point to your directory fine.  You have enough prep jobs in your global_ens and nfcens directories?

**Comment by malloryprow** [comment]
I linked to the parallel for global_ens for missing ones for the full forecast period. I have a few days for  global_ens and nfcens than I have run.

**Comment by PerryShafran-NOAA** [comment]
I linked to your directories and am running the stats jobs now.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow We have errors in the global_ens stats file.  See: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr238test/EVS/dev/drivers/scripts/global_ens/stats/jevs_global_ens_wave_grid2obs_stats.o81864983.   

nfcens failed too: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr238test/EVS/dev/drivers/scripts/nfcens/stats/jevs_nfcens_wave_grid2obs_stats.o81865054

I think I properly pointed to your directories of prep files.  I'm not sure what the problem is.  Should I run with KEEPDATA set to YES so you can see the METplus logfiles?  

Perry

**Comment by malloryprow** [comment]
Yes please.

**Comment by malloryprow** [comment]
Found the problem you need to link the fix directory.

ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr238test/EVS/fix

**Comment by PerryShafran-NOAA** [comment]
Oh darn it.  Yes, I knew that I had to do this for every PR, but I'm not yet quite in the habit of it.  I'll take care of that.

**Comment by malloryprow** [comment]
✅ stat files are same as mine.

Let's merge this.

**Comment by PerryShafran-NOAA** [comment]
You don't want to do a test of plots?

Perry

**Comment by malloryprow** [comment]
Ah, sorry forgot that I made changes to that too.

**Comment by PerryShafran-NOAA** [comment]
You list only nfcens at the top for a plot test, so I'll run that only; unless you want to do global_ens too.

Perry

**Comment by malloryprow** [comment]
Nah, I trust past me more than I am trusting current me right now on what needs to me run.

**Comment by PerryShafran-NOAA** [comment]
I'm running global_ens plots, just for completeness sake.  I'm pointing to the emc.vpppg stat output for this.

**Comment by PerryShafran-NOAA** [comment]
nfcens has completed:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr238test/EVS/dev/drivers/scripts/nfcens/plots/jevs_nfcens_grid2obs_plots.o81876293

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/nfcens/wave.20230913

**Comment by PerryShafran-NOAA** [comment]
global_ens has finished:

 /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr238test/EVS/dev/drivers/scripts/global_ens/plots/jevs_global_ens_wave_grid2obs_plots.o81876946

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_ens/wave.20230913

**Comment by malloryprow** [comment]
✅ plots look good!

Okay, NOW let's merge this.

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by PerryShafran-NOAA** [comment]
Approved for merge.

**Pull request merged**
