### PR TITLE
bugfix/global_det_rev6

### PR DESCRIPTION
**Pull request by malloryprow**
Adjust memory for jobs to avoid "Cgroup mem limit exceeded"

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
> None

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **No**

- [ ] Do these updates/additions include sufficient testing updates? **No**

- [ ] Please complete this pull request review by **02/16/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/global_det_rev6`.

**Comment by ShelleyMelchior-NOAA** [comment]
Confirmed that the corollary ecf scripts are not updated in this PR b/c they 
a) already have sufficient memory, and 
b) the EVS auth repository already matches the NCO para ecf scripts.
The only exception is `jevs_global_det_gfs_atmos_grid2grid_stats.ecf`. NCO para ecf has mem=150. Mallory has increased it to mem=175 to fix the errors she is seeing in the NCO para log files concerning memory exceedance.

**Comment by ShelleyMelchior-NOAA** [comment]
The global_det atmos stats jobs have been submitted.
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_gfs_grid2grid_stats_00.o132716595`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_gfs_grid2obs_stats_00.o132716649`

**Comment by ShelleyMelchior-NOAA** [comment]
The global_det atmos plots jobs have been submitted.
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_pres_levs_plots_31days_00.o132717824`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_pres_levs_plots_90days_00.o132717825`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_sfc_plots_31days_00.o132717826`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_sfc_plots_90days_00.o132717828`

**Comment by malloryprow** [comment]
Good for both global_det atmos stats and plots tests! Output matches the parallel, and grep'd the logs for "limit exceeded" and found no instances.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Changes yield expected results. This PR is approved for merge.

**Pull request merged**
