### PR TITLE
Bugfix/subseasonal Wei comments

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
The following changes have been made:
Moved a parenthesis in JEVS_SUBSEASONAL_STATS.
Renamed ecf scripts/jobs to meet requirements.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Since the changes are super minor, no testing should be needed.
However, check to make sure I renamed the ecf scripts correctly, keeping the history associated with the file.
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>
ASAP
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA @PerryShafran-NOAA I see that no testing is asked for in this PR, but if we could run the dev driver for one of the shortest stats scripts, just to test the change in [jobs/JEVS_SUBSEASONAL_STATS](https://github.com/NOAA-EMC/EVS/pull/387/files#diff-5cd5dd83e119afeb64d503251f097aa6177b6bc34e93e778588f8ebe07899be0), that would be excellent. Which stats job is fastest?

**Comment by ShannonShields-NOAA** [comment]
@AliciaBentley-NOAA dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_cfs_grid2grid_stats.sh would be good to test.

**Comment by ShannonShields-NOAA** [comment]
However, FYI I did not initially list that to test because that script uses "export COMIN=/lfs/h2/emc/vpppg/noscrub/$USER/$NET/${evs_ver_2d}/prep/$COMPONENT/$RUN" instead of compath.py. (A previous COMIN path is defined ahead of the j-job, which I think is why the ) error was not caught in dev.)

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA @ShannonShields-NOAA Currently running the suggested script.

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA Totally understood. I just want to make sure that we can still run our scripts successfully in dev with this change. We should be absolutely fine, but we should be incredibly thorough before merging any more PRs. Thanks!

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA Please make sure then that all paths (like COMIN) are successfully set and/or pointing to parallel prep.

**Comment by PerryShafran-NOAA** [comment]
In /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr387test/EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_cfs_grid2grid_stats.o121612804, I see the following:

From the dev driver:

```
++ export COMIN=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/subseasonal/atmos
++ COMIN=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/subseasonal/atmos
```

From the J-job:

```
0 + export COMIN=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/subseasonal/atmos
0 + COMIN=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/subseasonal/atmos
```

This is what we would expect, since the COMIN is fed into it from the dev driver.

But the true test of the correctness is to remove the COMIN from the dev driver and see what the J-job gives us.  (This won't run because COMIN won't be correct, but it will at least tell us what COMIN would be set to in the new setting.)

In jevs_subseasonal_cfs_grid2grid_stats.o121613060 we see:

```
11 + compath.py prod/com/evs/v1.0.0/prep
Could not find evs/v1.0/prep
1 + export COMIN=/subseasonal/atmos
1 + COMIN=/subseasonal/atmos
```

But this would be good because when this is run in the production space, then if we can evaluate the evs/v1.0/prep, it would go to subseasonal/atmos like it should.  

I'm not entirely sure this is the best way to test the change in the J-job?  But I feel that this change is good, because when they do evaluate compath.py, this should work as expected.  Wei made this fix in his own J-job, and I see the change in how it treats this statement.

**Comment by AliciaBentley-NOAA** [comment]
Thank you both! Can someone quickly check out the COMIN line in the stats J-job looks in Wei's parallel? If it's the same as what's in this PR, we should be good to go!

/lfs/h1/ops/para/packages/evs.v1.0.0

**Comment by ShannonShields-NOAA** [comment]
@AliciaBentley-NOAA I just checked and can confirm they match!

**Comment by PerryShafran-NOAA** [comment]
Wei's J-job has this line:

export COMIN=${COMIN:-$(compath.py ${envir}/com/$NET/$evs_ver/prep)/$COMPONENT/$RUN}

Thus I think this PR is good to go.

**Comment by AliciaBentley-NOAA** [comment]
Great job, all! Thanks!

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Pull request merged**
