### PR TITLE
Removed extra bracket in prep exevs aqm script

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
There was an extra bracket in a statement that was causing errors.  This PR removes the extra bracket.  

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run the prep step and check the output.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Wow! Such a teensy thing.

I have cloned your fork and checked out branch `bugfix/aqm_bracket`. I will run aqm prep processing.

**Comment by ShelleyMelchior-NOAA** [comment]
The aqm prep process has completed.
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_prep_00.o94630131`
It looks like the cat'ing worked better? My log file is larger than emc.vpppg's.
```
$ ll jevs_aqm_prep_00.o94630131 
-rw-r--r-- 1 shelley.melchior emc 955470 Dec  1 18:21 jevs_aqm_prep_00.o94630131
```
vs
```
$ ll /lfs/h2/emc/ptmp/emc.vpppg/output/jevs_aqm_prep_00.o94*
-rw-r--r-- 1 emc.vpppg emc 901972 Nov 26 00:02 /lfs/h2/emc/ptmp/emc.vpppg/output/jevs_aqm_prep_00.o94182767
-rw-r--r-- 1 emc.vpppg emc 901739 Nov 27 00:01 /lfs/h2/emc/ptmp/emc.vpppg/output/jevs_aqm_prep_00.o94247747
-rw-r--r-- 1 emc.vpppg emc 908558 Nov 28 00:02 /lfs/h2/emc/ptmp/emc.vpppg/output/jevs_aqm_prep_00.o94321782
-rw-r--r-- 1 emc.vpppg emc 908709 Nov 29 00:02 /lfs/h2/emc/ptmp/emc.vpppg/output/jevs_aqm_prep_00.o94396421
-rw-r--r-- 1 emc.vpppg emc 908036 Nov 30 00:02 /lfs/h2/emc/ptmp/emc.vpppg/output/jevs_aqm_prep_00.o94476360
-rw-r--r-- 1 emc.vpppg emc 908153 Dec  1 00:02 /lfs/h2/emc/ptmp/emc.vpppg/output/jevs_aqm_prep_00.o94563717
```

**Comment by PerryShafran-NOAA** [comment]
Yes, that looks good, and makes sense.  Printing a large log file is longer than a "No such file" statement takes.  

I think we're good on this one.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Test yields anticipated results. This PR is approved for merge.

**Pull request merged**
