### PR TITLE
EVSTC for V1.0

### PR DESCRIPTION
**Pull request by JiayiPeng-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [x] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [x] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [x] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR description above.
- [x] Ensure the PR title matches the feature branch name.
- [x] Check the following:
- [x]  Instructions provided on how to run
- [x]  Developer's name is replaced by ${user} where necessary throughout the code
- [x]  Check that the ecf file has all the proper definitions of variables
- [x]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [x]  Check to see that the output directory structure is followed
- [x]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [x] After submitting the PR, select **Development** issue with the original issue number.
- [x] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [x] Close the linked issue.

### CODE REVIEW

**Comment by JiayiPeng-NOAA** [comment]
The test data is located on Dogwood: /lfs/h2/emc/vpppg/noscrub/jiayi.peng/MetTCData

**Comment by JiayiPeng-NOAA** [comment]
The test data is located on Dogwood: /lfs/h2/emc/vpppg/noscrub/jiayi.peng/MetTCData

**Comment by ShelleyMelchior-NOAA** [comment]
Getting started on this PR, as a continuation/extension/replacement of PR #31, which was submitted back on Nov 3.

**Comment by ShelleyMelchior-NOAA** [comment]
The global_det and global_ens stats and plots components run to success and produce expected graphics. The plots and stats files are located in the appropriate EVS directory structure.

Onto testing the regional side.

**Comment by ShelleyMelchior-NOAA** [comment]
The regional stats and plots components run to success and produce the expected graphics. The plots and stats files are located in the appropriate EVS directory structure.

Various plots from global_det, global_ens, and regional were cp'd to rzdm for review.
https://ftp.emc.ncep.noaa.gov/users/smelchior/EVS/hurricane3/

**Comment by ShelleyMelchior-NOAA** [comment]
I am still not wild about the notation used in the J-job scripts for the default COMIN directory locations. Should someone ever run the ecf scripts with those variables unset (perhaps inadvertently commented out), the processing will break b/c, for example, `/your/NHC/bdeck/data/dir` is not a valid path on any system.  But I am not willing to die on this hill. Since the TC verif component will be running in on-demand non-ops and on a variety of platforms, it is difficult to identify what the default paths would be anyway.

**Comment by ShelleyMelchior-NOAA** [comment]
@JiayiPeng-NOAA , before I can merge this PR, I need to reconcile conflicts in `versions/run.ver`. The `run.ver` file in the auth repo is more comprehensive than what you have in your PR, as is expected. I need clarity on one item in your `run.ver` file.
`export libfabric_ver=1.11.0.0.`
Is that final dot supposed to be there? I think so, but I just want to make sure.

**Comment by JiayiPeng-NOAA** [comment]
Hi Shelley,
That's the version number with the final dot.
Thanks,
Jiayi

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
This PR is ready for merge. But there are 2 items of note:

1. formally address a more meaningful substitute for default COMIN paths rather than the current pseudo-code paths in the J-job scripts.
2. Make sure the binary shapefiles and logo graphics are not carried in the repository and instead in a fixed location on disk. I understand they are included in the PR for the purposes of testing, but this cannot be the long term solution.

**Pull request merged**
