### PR TITLE
bugfix/global_det_rev3

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

1. Replace use of "cpreq" with "cp" and file checking

- [ ] Describe testing already performed for this Pull Request:</br>
> None

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **No**

- [ ] Do these updates/additions include sufficient testing updates? **No**

- [ ] Please complete this pull request review by **02/08/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow I have looked over the changes made in this PR and I think that they look good! All cpreqs have been changed to cp and are now wrapped in if statements. Once tested, I approve this for merge. Thanks!

@ShelleyMelchior-NOAA @PerryShafran-NOAA

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/global_det_rev3`.

**Comment by ShelleyMelchior-NOAA** [comment]
The 3 wave processes are underway.
logfiles: 
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_prep_00.o131955952`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o131955975`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_grid2obs_plots_31days_00.o131956010`

**Comment by ShelleyMelchior-NOAA** [comment]
The 5 atmos processes are underway.
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_cmc_grid2grid_stats_00.o131956133`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_cmc_grid2obs_stats_00.o131956138`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_headline_plots_00.o131956315`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_ptype_plots_31days_00.o131956313`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2grid_means_plots_31days_00.o131956311`

**Comment by ShelleyMelchior-NOAA** [comment]
Do I Need to fudge the validation date ... I may have run too soon.

**Comment by malloryprow** [comment]
prep is running now for the parallel's so if we wait a little bit you can just resubmit dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_cmc_grid2grid_stats.sh and dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_cmc_grid2obs_stats.sh.

**Comment by malloryprow** [comment]
> The 3 wave processes are underway. logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_prep_00.o131955952` `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_gfs_grid2obs_stats_00.o131955975` `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_grid2obs_plots_31days_00.o131956010`

We are good with these tests for global_det wave. The output matches the emc.vpppg parallel. I didn't find any use of "cpreq" in the logs.

**Comment by malloryprow** [comment]
> prep is running now for the parallel's so if we wait a little bit you can just resubmit dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_cmc_grid2grid_stats.sh and dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_cmc_grid2obs_stats.sh.

@ShelleyMelchior-NOAA Feel free to rerun these when you get a chance!

**Comment by malloryprow** [comment]
/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_headline_plots_00.o131956315, /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2obs_ptype_plots_31days_00.o131956313, and /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2grid_means_plots_31days_00.o131956311 are good. I found no use of "cpreq" and the final tar sizes look like what they should be.

**Comment by ShelleyMelchior-NOAA** [comment]
The two atmos stats jobs have been re-run now that the prep data in emc.vpppg are available.
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_cmc_grid2obs_stats_00.o131959456`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_cmc_grid2grid_stats_00.o131959457`

**Comment by malloryprow** [comment]
> The two atmos stats jobs have been re-run now that the prep data in emc.vpppg are available. logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_cmc_grid2obs_stats_00.o131959456` `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_cmc_grid2grid_stats_00.o131959457`

Re-runs are good! Final stat files match the emc.vpppg parallel and no use of cpreq in the logs.

Merge away!

**Comment by AliciaBentley-NOAA** [comment]
Thanks for getting this to the finish line, @ShelleyMelchior-NOAA and @malloryprow

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All tests yield expected results. This PR is approved for merge.

**Pull request merged**
