### PR TITLE
Fix unit conversion

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

> Please include a summary of the changes and the related GitHub issue(s). Please also include relevant motivation and context.

The fix addresses a logic error affecting plotting output for five EVS components.

The logic error was found in several instances of code used for converting the units of certain METplus summary statistics.  Values of these stats were already converted before being used in follow-up conversion equations (incorrect).  As a result, some output plots were displaying incorrect "doubly converted" values of verification metrics.

In this fix, METplus summary statistics are first stored as new variables prior to conversion, and these new variables are used when performing unit conversion and are never overwritten.  As a result, all EVS plots affected by the issue should display correct converted values of verification metrics.

## Developer Questions and Checklist
* Is this a high priorty PR? If so, why and is there a date it needs to be merged by?

**Yes**; Currently, some EVS plots are inaccurate if they display SL1L2- or VL1L2-based metrics and apply unit conversion.  The issue affects five EVS components.  

This PR has no specific due date, but should probably be merged **ASAP**.

* Do you have any planned upcoming annual leave/PTO?

No

* Are there any changes needed for when the jobs are supposed to run?
  
No

- [x] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [x] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [x] References the feature branch for `HOMEevs` are removed from the code.
- [x] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [x] Jobs over 15 minutes in runtime have restart capability.
- [x] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [x] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [x] Code is using METplus wrappers structure and not calling MET executables directly.
- [x] Log is free of any ERRORs or WARNINGs.

## Testing Instructions

> Please include testing instructions for the PR assignee. Include all relevant input datasets needed to run the tests.

#### (1) Set up jobs

* symlink the EVS_fix directory locally as "fix"
* In each driver script, edit the following environment variables:
HOMEevs - set to your test EVS directory
COMIN - set to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d
COMOUT - set to your test output directory
SENDMAIL - (optional) set to "NO"

#### (2) Running jobs
* I recommend testing the following jobs:
```
jevs_cam_grid2obs_plots
jevs_mesoscale_grid2obs_plots
jevs_global_ens_atmos_gefs_grid2obs_past31days_plots
jevs_analyses_grid2obs_plots
jevs_aqm_grid2obs_plots
```
[Total: 5 plots jobs]

* All driver scripts can be submitted using `qsub -v vhr=00 $driver`
* All jobs can be submitted at any time

#### (3) Checking jobs
Log files should be checked by the developer for the following keywords:
```
check="FATAL\|WARNING\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|failed\|unexpected\|exceeded"
grep "$check" $logfile
```

Additionally, a sample of test output plots should be compared to EVS parallel output.

### CODE REVIEW

**Comment by malloryprow** [comment]
Code changes look good! I'm going to start kicking off the jobs. I'll put the job info here when they are all done running.

**Comment by malloryprow** [comment]
### jevs_global_ens_atmos_gefs_grid2obs_past31days_plots

**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr521/EVS/dev/drivers/scripts/plots/global_ens/jevs_global_ens_atmos_gefs_grid2obs_past31days_plots.o149558094
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr521/evs/v2.0/plots/global_ens/atmos.20240819
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_global_ens_atmos_gefs_grid2obs_past31days_plots.149558094.cbqs01

**Comment by malloryprow** [comment]
### jevs_aqm_grid2obs_plots

**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr521/EVS/dev/drivers/scripts/plots/aqm/jevs_aqm_grid2obs_plots.o149558415
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr521/evs/v2.0
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_aqm_grid2obs_plots.149558415.cbqs01

**Comment by malloryprow** [comment]
### jevs_analyses_grid2obs_plots

**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr521/EVS/dev/drivers/scripts/plots/analyses/jevs_analyses_grid2obs_plots.o149558287
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr521/evs/v2.0
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_analyses_grid2obs_plots.149558287.cbqs01

**Comment by malloryprow** [comment]
### jevs_mesoscale_grid2obs_plots

**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr521/EVS/dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_grid2obs_plots.o149557840
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr521/evs/v2.0/plots/mesoscale
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_mesoscale_grid2obs_plots.149557840.cbqs01

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow The following jobs completed cleanly, their output files look normal, and affected output graphics have been corrected:
✔️ jevs_mesoscale_grid2obs_plots
✔️ jevs_global_ens_atmos_gefs_grid2obs_past31days_plots
✔️ jevs_analyses_grid2obs_plots
✔️ jevs_aqm_grid2obs_plots

⌛ jevs_cam_grid2obs_plots is still running but should be finished soon!

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow 

✔️ jevs_cam_grid2obs_plots completed cleanly, the output file looks normal, and affected output graphics look corrected.

👍 No further concerns about the test jobs from me

**Review by malloryprow — APPROVED** [review]
Code changes are good and testing was successful.

**Review by AndrewBenjamin-NOAA — APPROVED** [review]
Changes were successful, thank you for finding and putting in the fix so quickly.

**Pull request merged**
