### PR TITLE
EVS v1.0.10: bugfix/global_det_atmos_plots_logging

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

Following EVS v1.0.10 testing in para NCO discovered two things to be changed for global_det:

1. The log file size for jevs_global_det_atmos_grid2obs_pres_levs_plots_last90days.ecf is too big; this is resolved by removing very detailed log messages
2. Repeated environment variable export statements in the individual jobs scripts for plots; this is resolved by removing certain high-level set environment variables from those jobs scripts.

- [ ] Describe testing already performed for this Pull Request:</br>

> I ran all the 90 days plotting jobs. I looked to see the log file size was reduced and the environment variables were no longer being set in the individual log scripts. I checked the final tar sizes against the EVS v1.0.10 NCO parallel.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **ASAP**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
I am currently working on your PR.  I have submitted all plot jobs using PDYm2 (it was set to PDYm1 in the J-job, I just changed that to PDYm2).  The directory for the .o files will be ) /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr501test/EVS/dev/drivers/scripts/plots/global_det.

Per your instructions, I am pointing to the NCO *para* directory.  Did you mean that, or did you mean the prod directory?

**Comment by malloryprow** [comment]
I meant para! I wanted to run with the output from the bugfix testing by NCO.

**Comment by PerryShafran-NOAA** [comment]
Gotcha.  I am indeed using para.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA It looks like the jobs ran for VDATE_END=20240725 which would be PDYm1 (/lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_det/[atmos][headline].20240725).

**Comment by PerryShafran-NOAA** [comment]
I forgot that it was set in the dev driver, which overwrites what is in the J-job.  I am correcting and re-submitting.

**Comment by malloryprow** [comment]
Thank you!

**Comment by PerryShafran-NOAA** [comment]
Some runs have completed.  You can find the tarballs here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_det/atmos.20240724

The .o files are in the directory I mentioned above.  I did not delete the .o files from the 20240725 runs, so check out the most recent ones.  

Some of the bigger jobs are still running.

**Comment by malloryprow** [comment]
Will start reviewing!!

**Comment by malloryprow** [comment]
Log file sizes 👍 :

118M    jevs_global_det_atmos_grid2grid_means_plots_31days_00.o145882634
150M    jevs_global_det_atmos_grid2grid_means_plots_90days_00.o145882630
253M    jevs_global_det_atmos_grid2grid_precip_plots_31days_00.o145882628
283M    jevs_global_det_atmos_grid2grid_precip_plots_90days_00.o145882626
549M    jevs_global_det_atmos_grid2grid_pres_levs_plots_31days_00.o145882624
667M    jevs_global_det_atmos_grid2grid_pres_levs_plots_90days_00.o145882619
4.4M    jevs_global_det_atmos_grid2grid_sea_ice_plots_31days_00.o145882501
5.8M    jevs_global_det_atmos_grid2grid_sea_ice_plots_90days_00.o145882476
91M     jevs_global_det_atmos_grid2grid_snow_plots_31days_00.o145882451
110M    jevs_global_det_atmos_grid2grid_snow_plots_90days_00.o145882449
2.5M    jevs_global_det_atmos_grid2grid_sst_plots_31days_00.o145882441
3.3M    jevs_global_det_atmos_grid2grid_sst_plots_90days_00.o145882440
2.9G    jevs_global_det_atmos_grid2obs_pres_levs_plots_31days_00.o145882437
3.6G    jevs_global_det_atmos_grid2obs_pres_levs_plots_90days_00.o145882434
28M     jevs_global_det_atmos_grid2obs_ptype_plots_31days_00.o145882430
36M     jevs_global_det_atmos_grid2obs_ptype_plots_90days_00.o145882419
3.5G    jevs_global_det_atmos_grid2obs_sfc_plots_31days_00.o145882405
4.9G    jevs_global_det_atmos_grid2obs_sfc_plots_90days_00.o145882316
1.2M    jevs_global_det_atmos_headline_plots_00.o145882314

**Comment by malloryprow** [comment]
grep "export evs_ver" \*_00.o14588\* 👍 :

jevs_global_det_atmos_grid2grid_means_plots_31days_00.o145882634:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2grid_means_plots_90days_00.o145882630:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2grid_precip_plots_31days_00.o145882628:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2grid_precip_plots_90days_00.o145882626:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2grid_pres_levs_plots_31days_00.o145882624:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2grid_pres_levs_plots_90days_00.o145882619:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2grid_sea_ice_plots_31days_00.o145882501:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2grid_sea_ice_plots_90days_00.o145882476:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2grid_snow_plots_31days_00.o145882451:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2grid_snow_plots_90days_00.o145882449:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2grid_sst_plots_31days_00.o145882441:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2grid_sst_plots_90days_00.o145882440:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2obs_pres_levs_plots_31days_00.o145882437:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2obs_pres_levs_plots_90days_00.o145882434:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2obs_ptype_plots_31days_00.o145882430:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2obs_ptype_plots_90days_00.o145882419:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2obs_sfc_plots_31days_00.o145882405:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_grid2obs_sfc_plots_90days_00.o145882316:+++ export evs_ver=v1.0.10
jevs_global_det_atmos_headline_plots_00.o145882314:+++ export evs_ver=v1.0.10

**Comment by PerryShafran-NOAA** [comment]
@malloryprow This all sounds great!  Looks like all we need here is the code review and then we can merge.

**Comment by malloryprow** [comment]
Log and tar files are good too. 

Only oddity is that /lfs/h1/ops/para/com/evs/v1.0/plots/global_det/atmos.20240724/evs.plots.global_det.atmos.grid2grid_pres_levs.last31days.v20240724.tar does not exist. I can see in /lfs/h1/ops/para/output/20240725/evs_global_det_atmos_grid2grid_pres_levs_plots_31days.o162711936 that looks like NCO did a qdel on the job for some reason.

> /var/spool/pbs/mom_priv/jobs/162711936.dbqs01.SC: line 89: 83802 Terminated              $HOMEevs/jobs/JEVS_GLOBAL_DET_PLOTS
> Killed by signal (likely via qdel)

Perhaps related to testing of logging stuff they were doing for the different global_det atmos plots jobs? I'm not sure.

Regardless, I feel good that the changes in this PR don't impact the output and meet the changes NCO is looking for.

**Comment by PerryShafran-NOAA** [comment]
Oh, interesting.  Well, yeah, I wouldn't worry about that, especially if the current code works as expected.

**Comment by malloryprow** [comment]
I know it was noted outside of this PR, but wanted to note here too.

There will be another PR in the future EVS v2.0.0: feature/global_det_atmos_plots_logging that will address the same concerns  addressed here but for EVS v2.0. The scripts here have changed from v1.0 to v2.0 so there needs to be a seperate PR for it. It will also include the stats in the repetitive export statements.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
