### PR TITLE
Bugfix/cam rev5

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

This was not tested but represents two minor changes (see commit messages).  Job run times are usually no more than a couple of minutes.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Same process as in the recent cam PRs:
### (1) Set up jobs 
•	symlink the EVS_fix directory locally as "fix"
•	In all driver scripts, point all exports of "HOMEevs" to your EVS test directory
•	In all driver scripts, change COMIN to the parallel directory (`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`)
•	Optional: In all stats drivers scripts, change "MAILTO" to point to your email address
### (2) Test Jobs
**Use the following to submit everything: `qsub –v vhr=08 `**

From your EVS testing directory, the following scripts should be run using the set up in step (1):
```
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_severe_stats.sh
```
_[Total: 0 prep jobs, 6 stats jobs, 0 plots jobs]_

I'll check the resulting COMOUT directory for empty subdirectories:
find $COMOUT/atmos.2023* -type d -empty

- [x] Has the code been checked to ensure that no errors occur during the execution? **NO**

- [x] Do these updates/additions include sufficient testing updates? **YES**

- [x] Please complete this pull request review by **12/08/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @MarcelCaron-NOAA ! I have cloned your fork and checked out branch `bugfix/cam_rev5`. I am setting up the test environment.

**Comment by ShelleyMelchior-NOAA** [comment]
All 6 severe stats jobs have been submitted and completed.
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/`
```
-rw-r--r-- 1 shelley.melchior emc 1219091 Dec  7 19:56 jevs_cam_hireswarwmem2_severe_stats_00.o120608444
-rw-r--r-- 1 shelley.melchior emc 1217543 Dec  7 19:56 jevs_cam_hireswarw_severe_stats_00.o120608473
-rw-r--r-- 1 shelley.melchior emc 1215608 Dec  7 19:56 jevs_cam_href_severe_stats_00.o120608477
-rw-r--r-- 1 shelley.melchior emc 1274307 Dec  7 19:56 jevs_cam_hireswfv3_severe_stats_00.o120608476
-rw-r--r-- 1 shelley.melchior emc 1328148 Dec  7 19:56 jevs_cam_hrrr_severe_stats_00.o120608479
-rw-r--r-- 1 shelley.melchior emc 1442068 Dec  7 19:56 jevs_cam_namnest_severe_stats_00.o120608480
-rw-r--r-- 1 shelley.melchior emc 1442637 Dec  7 20:01 jevs_cam_namnest_severe_stats_00.o120608943

```

**Comment by MarcelCaron-NOAA** [comment]
Jobs have completed cleanly. 

✔️ Output files match size of files in the parallel:
```
[marcel.caron@dlogin05 EVS] du -sh /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam/*20231130/*severe*.stat
96K     /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam/hireswarw.20231130/evs.stats.hireswarw.atmos.severe.v20231130.stat
96K     /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam/hireswarwmem2.20231130/evs.stats.hireswarwmem2.atmos.severe.v20231130.stat
124K    /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam/hireswfv3.20231130/evs.stats.hireswfv3.atmos.severe.v20231130.stat
96K     /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam/href.20231130/evs.stats.href.atmos.severe.v20231130.stat
156K    /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam/hrrr.20231130/evs.stats.hrrr.atmos.severe.v20231130.stat
216K    /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam/namnest.20231130/evs.stats.namnest.atmos.severe.v20231130.stat
[marcel.caron@dlogin05 EVS] du -sh /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/cam/*20231130/*severe*.stat
96K     /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/cam/hireswarw.20231130/evs.stats.hireswarw.atmos.severe.v20231130.stat
96K     /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/cam/hireswarwmem2.20231130/evs.stats.hireswarwmem2.atmos.severe.v20231130.stat
124K    /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/cam/hireswfv3.20231130/evs.stats.hireswfv3.atmos.severe.v20231130.stat
96K     /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/cam/href.20231130/evs.stats.href.atmos.severe.v20231130.stat
156K    /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/cam/hrrr.20231130/evs.stats.hrrr.atmos.severe.v20231130.stat
216K    /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/cam/namnest.20231130/evs.stats.namnest.atmos.severe.v20231130.stat

```


✔️ No hits on the following keywords:
```
grep "ERROR\|error\|Cgroup\|Killed\|o such file\|argument expected" /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_*_severe_stats_00.o120608* | wc -l
0
```

✔️ No empty files:
```
find /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam/* -type d -empty | wc -l
0
```

No other concerns from me about this PR.

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA Can you hold on this PR for a second?  I want to make sure one concern from Lin is addressed.

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA @MarcelCaron-NOAA @PerryShafran-NOAA Thanks! Please merge this, folks!

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Changes look good and test yields expected results. This PR is approved for merge.

**Pull request merged**
