### PR TITLE
feature/global_ens_wave

### PR DESCRIPTION
**Pull request by DeannaSpindler-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [x] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [x] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [x] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR description above.
- [x] Ensure the PR title matches the feature branch name.
- [x] Check the following:
- [x]  Instructions provided on how to run
- [x]  Developer's name is replaced by ${user} where necessary throughout the code
- [x]  Check that the ecf file has all the proper definitions of variables
- [x]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [x]  Check to see that the output directory structure is followed
- [x]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, @DeannaSpindler-NOAA ,

Please be sure that you provide complete instructions on how to bring in the data and run your stats job.  Also be sure that all the items in the checklist has been done before I can start.  

Thanks!

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,
This code has been running on my cron since Nov 9, 2022.
Alicia gave the OK to go ahead and submit a PR for GEFS-Wave EVS development.  

To run the prep step, make sure to modify the OUTPUTROOT directory under the "developers directories" in 
ecf/global_ens/prep/jevs_global_ens_wave_grid2obs_prep.ecf
and to point COMIN to my OUTPUTROOT='/lfs/h2/emc/vpppg/noscrub/deanna.spindler/EVS_stats/evs/v1.0'
because the prep jobs will need this to access the archive.
Then: 
qsub jevs_global_ens_wave_grid2obs_prep.ecf
The work directory will be under: /lfs/h2/emc/stmp/$USER/evs_output
and is named jevs_global_ens_wave_g2o_prep.{qsubID}
The run will make ${OUTPUTROOT}/evs/v1.0/prep/global_ens/wave.YYYYMMDD/gefs/grid2obs
where you will find 5 NetCDF files and 260 grib2 files per day.

To run the stats step, also change the OUTPUTROOT (should be the same as the one above) in
ecf/global_ens/stats/jevs_global_ens_wave_grid2obs_stats.ecf
then
qsub jevs_global_ens_wave_grid2obs_stats.ecf
The work directory will be under the same /lfs/h2/emc/stmp/$USER/evs_output
but this time is named jevs_global_ens_wave_g2o_stats.{qsubID}
This run will make ${OUTPUTROOT}/evs/v1.0/stats/global_ens/wave.YYYYMMDD/gefs/grid2obs
where you will find 260 small stat files: point_stat_fcstGEFS_obsGDAS_climoERA5_*.stat
and
${OUTPUTROOT}/evs/v1.0/stats/global_ens/gefs.YYYYMMDD/evs.stats.gefs.wave.grid2obs.vYYYYMMDD.stat

Let me know if you have any questions,
Deanna

**Comment by DeannaSpindler-NOAA** [comment]
Added the plots code to the repo.  To test:

Same as usual, change the OUTPUTROOT in
ecf/global_ens/plots/jevs_global_ens_wave_grid2obs_plots.ecf
to my
OUTPUTROOT='/lfs/h2/emc/vpppg/noscrub/deanna.spindler/EVS_stats/evs/v1.0'
because the job will need this to access the archive.
Then
qsub jevs_global_ens_wave_grid2obs_plots.ecf
The work directory will be under the same /lfs/h2/emc/stmp/$USER/evs_output
but this time is named jevs_global_ens_wave_g2o_plots.{qsubID}
This run will make ${OUTPUTROOT}/evs/v1.0/plots/global_ens/global_ens.YYYYMMDD
where you will find the two tar files:
evs.plots.global_ens.wave.grid2obs.last31days.vYYYYMMDD.tar
and
evs.plots.global_ens.wave.grid2obs.last90days.vYYYYMMDD.tar

Let me know if you have any questions,
Deanna

**Comment by PerryShafran-NOAA** [comment]
Hi, Deanna,

To clarify your first step in : jevs_global_ens_wave_grid2obs_prep.ecf

You want me to modify OUTPUTROOT so that this points to your directory?  Or this should be pointed to my directory, yet COMIN should point to your directory?  OUTPUTROOT sounds like an output, so I'm a bit confused.

Perry

**Comment by PerryShafran-NOAA** [comment]
Also, in your JEVS_GLOBAL_ENS_WAVE_GRID2OBS_PREP in the jobs directory, I recommend changing:

export COMOUT=${COMIN}/${STEP}/${COMPONENT}/${RUN}

to 

export COMOUT=${COMOUT:-${COMIN}/${STEP}/${COMPONENT}/${RUN}}

NCO may require usage of compath.py in any output directory, but since COMIN uses compath.py, this may suffice for now.  

Also I recommend changing the following:

export COMINobs=${COMINobs:-$(compath.py obsproc/${obsproc_ver})}
export COMINgdas=${COMINobs}/gdas

to 

export COMINgdas=${COMINgdas:-$(compath.py obsproc/${obsproc_ver}/gdas)}

Unless COMINobs is used for something else in your script other than pointing to the gdas files, then it's fine the way it is.  

Thanks!

Perry

**Comment by PerryShafran-NOAA** [comment]
One more item, and this is the most critical since it is preventing execution of the prep step.

OUTPUT_BASE is not set anywhere.  From the output file:

`ERROR: run_metplus  failed: OUTPUT_BASE cannot be set to or contain '/path/to'`

See /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_deanna_gefs_wave/ecf/global_ens/prep/jevs_global_ens_wave_g2o_prep.o20189560

It's not in the machine.conf file nor is it in your PB2NC_wave.conf file.  Somehow it went missing?  Please be sure that you have this set in your machine.conf file.

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,

OUTPUTROOT would usually be the output dir, but for you to run my test case
the code has to find my archive.  So for testing purposes, it has to point
to /lfs/h2/emc/vpppg/noscrub/$USER/EVS_stats.

OUTPUT_BASE is set in my machine.conf, and is just {ENV[DATA]}.
The issue is that I did not upload my machine.conf to GitHub!  I will do
that when I have made the other changes you suggested.

I'll send you an email when the changes are made and uploaded to GitHub.

Best,
Deanna

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,

I've been trying to get $COMINgdas to work with compath.py, but everything
I try gets this error message:
++ 0 + compath.py obsproc/v1.1
WARNING: Could not find the dev COM paths list at
/lfs/h1/ops/dev/config/compaths.list
Could not find obsproc/v1.1
+ 0 + export COMINgdas=/gdas

Yet when I issue it interactively (after loading the modules), it seems to
work - it just won't work when I qsub it.

Any suggestions?

Thanks,
Deanna

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
Hi, Deanna,

Try this:

`export COMINobs=${COMINobs:-$(compath.py ${envir}/com/obsproc/${obsproc_ver})}`

Be sure that envir is set to prod for this to work.  

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,

I've fixed the directories as suggested in all the ecf and jobs scripts in all the waves EVS branches and tested them, then uploaded the new versions.
Try as I might, I can't add my parm/metplus_config/machine.conf nor my versions/run.ver to any of my branches.  It doesn't give any errors, just doesn't load them!

Best,
Deanna

**Comment by PerryShafran-NOAA** [comment]
Send me your WCOSS2 path to where your machine.conf file is located, and I can use that.  The run.ver and machine.conf will eventually be merged by me at the end because these are the only two files used by all contributors.

Perry

**Comment by PerryShafran-NOAA** [comment]
Finally got through your prep step.  Please look here and see if the dataset in there looks OK:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_stats/evs/v1.0/prep/global_ens/wave.20221206/gefs/grid2obs

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,

Yes, those look fine and the sizes match what my code produced this morning.

Best,
Deanna

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
Oh good.  The prep step is now validated.  :)

Now onto the stats step.  

In my .o file (/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_deanna_global_ens_wave/ecf/global_ens/stats/jevs_global_ens_wave_g2o_stats.o21227905), I am seeing some errors:

```
12/07 17:48:09.443 metplus (command_builder.py:265) ERROR: (command_builder.py:723) Could not find FCST_INPUT file /lfs/h2/emc/stmp/perry.shafran/evs_output/jevs_global_ens_wave_g2o_stats.21227905.cbqs01/gribs/gefs.wave.20221126.t06z.mean.global.0p25.f252.grib2 using template gefs.wave.{init?fmt=%Y%m%d}.t{init?fmt=%2H}z.mean.global.0p25.f{lead?fmt=%3H}.grib2
12/07 17:48:09.443 metplus (command_builder.py:265) ERROR: (command_builder.py:723) Could not find FCST_INPUT file /lfs/h2/emc/stmp/perry.shafran/evs_output/jevs_global_ens_wave_g2o_stats.21227905.cbqs01/gribs/gefs.wave.20221129.t00z.mean.global.0p25.f168.grib2 using template gefs.wave.{init?fmt=%Y%m%d}.t{init?fmt=%2H}z.mean.global.0p25.f{lead?fmt=%3H}.grib2
12/07 17:48:09.443 metplus (command_builder.py:265) ERROR: (command_builder.py:723) Could not find FCST_INPUT file /lfs/h2/emc/stmp/perry.shafran/evs_output/jevs_global_ens_wave_g2o_stats.21227905.cbqs01/gribs/gefs.wave.20221129.t06z.mean.global.0p25.f168.grib2 using template gefs.wave.{init?fmt=%Y%m%d}.t{init?fmt=%2H}z.mean.global.0p25.f{lead?fmt=%3H}.grib2

```

That said, I do have data here:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_stats/evs/v1.0/stats/global_ens/wave.20221206/gefs/grid2obs

and here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_stats/evs/v1.0/stats/global_ens/gefs.20221206

But the fact that there are errors due to missing files needs to be addressed.  Can you look into this one?  Check out the output directories as well and let me know if that's what you expect.

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,

It's looking for the grib2 files from the last 17 days that would be
archived in EVS_stats/evs/v1.0/prep/global_ens/wave.YYYYMMDD/gefs/gridobs.
This should be set in
OUTPUTROOT='/lfs/h2/emc/vpppg/noscrub/deanna.spindler/EVS_stats/evs/v1.0'
 so the job can access my archive.

Best,
Deanna

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by DeannaSpindler-NOAA** [comment]
You may have to copy the prep files from my archive to yours... it's going
to need OUTPUTROOT to write to.

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
Ah - I had to copy 17 days worth of data for Binbin's GEFS stats run, looks like I'll need to do the same for you as well.

Perry

**Comment by PerryShafran-NOAA** [comment]
After copying 17 days into the prep directory, I re-ran.  I got a bigger output file but also some errors remain.  

See /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_deanna_global_ens_wave/ecf/global_ens/stats/jevs_global_ens_wave_g2o_stats.o21238239

```
12/07 20:34:41.952 metplus (command_builder.py:265) ERROR: (command_builder.py:723) Could not find FCST_INPUT file /lfs/h2/emc/stmp/perry.shafran/evs_output/jevs_global_ens_wave_g2o_stats.21238239.cbqs01/gribs/gefs.wave.20221202.t12z.mean.global.0p25.f084.grib2 using template gefs.wave.{init?fmt=%Y%m%d}.t{init?fmt=%2H}z.mean.global.0p25.f{lead?fmt=%3H}.grib2
12/07 20:34:41.953 metplus (compare_gridded_wrapper.py:152) INFO: Processing forecast lead 3 days 18 hours
```
```
12/07 20:35:49.511 metplus (command_builder.py:265) ERROR: (command_builder.py:723) Could not find FCST_INPUT file /lfs/h2/emc/stmp/perry.shafran/evs_output/jevs_global_ens_wave_g2o_stats.21238239.cbqs01/gribs/gefs.wave.20221202.t12z.mean.global.0p25.f090.grib2 using template gefs.wave.{init?fmt=%Y%m%d}.t{init?fmt=%2H}z.mean.global.0p25.f{lead?fmt=%3H}.grib2
12/07 20:35:49.512 metplus (compare_gridded_wrapper.py:152) INFO: Processing forecast lead 4 days
```

There are a few others.  Looks like forecast hours 84, 90, 96, 300, 102, are missing.

Do you have checks in your script to check for missing data?

Perry

**Comment by DeannaSpindler-NOAA** [comment]
No, the scripts don't check for each fcst grib2 file, they just check to
see how many are there - more than 0 and the script continues to run.

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
We are expected to run EVS without any errors, and thus we need to have checks in the scripts to see if files exist.  Otherwise errors will occur and NCO would likely flag us to fix the errors.  We'll need to check for missing files to ensure that METplus isn't looking for them.  

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,The missing files are grib2 files in prod.  They might be missing in my archives because I have only been running with an archive for a short time.  What are we supposed to do if the model grib2 files are missing for some reason? Do we want to continue to run? METplus handles gaps fine, but it puts out the error message.Thanks,DeannaOn Dec 8, 2022, at 9:14 AM, PerryShafran-NOAA ***@***.***> wrote:﻿
We are expected to run EVS without any errors, and thus we need to have checks in the scripts to see if files exist.  Otherwise errors will occur and NCO would likely flag us to fix the errors.  We'll need to check for missing files to ensure that METplus isn't looking for them.
Perry

**Comment by PerryShafran-NOAA** [comment]
You should be able to point directly to prod to bring data into the archive, as this is what we'd be doing in production.  Does your script point to the prod directory at all?  

We need to find a way to check whether model data exists before METplus is run, because if METplus can't find a file, it produces an error and thus that would be reflected in NCO's runs.   

METplus should be able to run even if files are missing, but having a pre-METplus check would remove a file being searched in METplus and producing the error.  

I am curious in this case, the missing files are due to the dates when the machine was down and thus no archive.  If that's the case, then maybe we can run from an earlier date and see if it produces no error.  But we need to make sure that there are no errors in our runs.

**Comment by DeannaSpindler-NOAA** [comment]
The prep script (exevs_global_ens_wave_grid2obs_prep.sh) copies the model's
grib2 files from the prod directory to the archive directory, each day
adding that day to the archive.  The stats script then copies all the
necessary grib2 files (18 days) and the nc files (produced from PB2NC in
prep) from the archive.

How are others doing the pre-METplus check? I can check that the individual
grib2 files are there or not, but then I don't know how to pass a reduced
set of specific files to METplus.

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by AliciaBentley-NOAA** [comment]
Tagging @malloryprow and @GwenChen-NOAA, as I think they have incorporated this type of check into their code. Thanks!

**Comment by PerryShafran-NOAA** [comment]
Do you have METplus searching for files by fhr (which would be by valid time)?  If so, I have a method that can do this, removing a fhr from the list of forecast hours, and then passing the list into the METplus configuration file.  If your verification is by INIT time, then you'll probably need help from the folks Alicia mentioned above.

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Perry, I use PointStat by valid time, so your method may work.

**Comment by malloryprow** [comment]
@DeannaSpindler-NOAA I set LEAD_SEQ to an environment variable "fhr_list". https://github.com/NOAA-EMC/EVS/blob/ca30361339bc5048d46f193eab8bbf2a68fa894c/parm/metplus_config/global_det/atmos_grid2grid/stats/GridStat_fcstGLOBAL_DET_obsModelAnalysis_climoERA5.conf#L35 My code will check for missing forecast files and if one it missing it doens't get added to "fhr_list".

**Comment by DeannaSpindler-NOAA** [comment]
I checked  my archive, and starting Oct 30th there are 260 grib2 files in each day except in 20221202 where there are 195 (missing all the t12z).

**Comment by DeannaSpindler-NOAA** [comment]
Thanks, Mallory! I already use LEAD_SEQ = {ENV[fhr_list]} but with set hours for different cfp processes.  
I will add a loop to check for each fcst hour file and modify my lists accordingly.

**Comment by PerryShafran-NOAA** [comment]
Hi, Deanna,

Are we ready for me to do the testing on this system?  Do we have enough data on Cactus to run this test?

Thanks!

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,

Yes, you should be able to run the test fine.  The plots will have gaps for
the stats of the week we were on Dogwood, but otherwise everything else
should be good.

Best,
Deanna

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
No error in your .o file!  Yay!

Please validate the data here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_stats/evs/v1.0/stats/global_ens

Thanks!

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Hello Perry,

The file looks good and matches the run from my cron.

Best,
Deanna

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
Excellent!  

When doing the plots,  I think it's easier to move 90 days worth of stats files to my directory.  I think pointing OUTPUTROOT to your directory causes the code to try to write to your directory.  It's probably better to have your files in my directory.  Thus I will do that when running the plot job.

Thanks!

Perry

**Comment by PerryShafran-NOAA** [comment]
There is an issue with the plot script.  Please look here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/global_ens/plots/jevs_global_ens_wave_g2o_plots.o26106092.  I don't know where else to look for output other than here - it's better that all stdout and stderr is self-contained in one file.

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Do you have all the stat files loaded somewhere?

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
They are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_stats/evs/v1.0/stats/global_ens

**Comment by DeannaSpindler-NOAA** [comment]
I see it.  The script is looking for
/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/parm/metplus_config/global_ens/wave_grid2obs/plots/py_plotting_wave.config
and the only file you have in that directory is verif_plotting.rtofs.conf



--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
How did that happen?  Here is your repository on GitHub:

https://github.com/DeannaSpindler-NOAA/EVS/tree/feature/global_ens_wave/parm/metplus_config/global_ens/wave_grid2obs/plots

Fix up the plot directory here and I'll try again.

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Ok, I think it's good now.  I also checked global_det and nfcens, and those
are fine.

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
OK, we have plot files!  Located here:   /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_stats/evs/v1.0/plots/global_ens/gefs.20221218

Looking at the .o file, your plotting filenames look OK.  I'm assuming that you only want timeseries, because that's all I see.  

Let me know if all is good.  

Perry

**Comment by DeannaSpindler-NOAA** [comment]
Yes, only time-series right now.  Looks good.

Best,
Deanna

--
Deanna Spindler, PhD
Physical Scientist III
Lynker at NOAA/NWS/NCEP/Environmental Modeling Center
NOAA Center for Weather and Climate Prediction

**Comment by PerryShafran-NOAA** [comment]
Excellent!  Looks like we validated prep, stats, plots, and we can now merge this one in.  

Thanks!

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
