### PR TITLE
Bugfix/cam final ee2

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

All jobs were run as described in this PR and completed normally.

### This bugfix addresses the following for the cam component:
- Add "set -x" as needed to driver and ush files
- Remove any remaining hardcoded paths 
- Add interpreter headers as needed
- Check for and remove dead J-job and ex-scripts code
- Check that ERROR messages are sufficiently descriptive
- Correct any regular "syntax error", "argument expected", "no such file or directory" messages and the like seen in recent stdout files
- Use "FATAL ERROR" and "WARNING" where possible to catch fatal and non-fatal runtime issues
- Add err_chk statements after running ush files and ex-scripts
- Add err_exit statements after each time a "FATAL ERROR" occurs
- Replace usages of the UNIX date utility with tools from the production date utilities
- Use cpreq in place of cp commands
- Check that permissions are set correctly for all files copied to COMOUT
- Check that no files written to COMOUT have byte size > 0
- Remove needless comments from all code
- remove jlogfiles statements 
- Remove remaining instances of "exit 0"
- Remove remaining indirect invocations of shell scripts (e.g., "sh sample.sh")

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Same process as in the most recent cam PR:
### (1) Set up jobs 
•	symlink the EVS_fix directory locally as "fix"
•	In all driver scripts, point all exports of "HOMEevs" to your EVS test directory
•	In all driver scripts, change COMIN to the parallel directory (`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`)
•	Optional: In all stats drivers scripts, change "maillist" to point to your email address
### (2) Test Jobs
Use the following …
•	…to submit stats/precip: `qsub –v vhr=19,VDATE=$(date -d "-3 days" +"%Y%m%d")`
•	…to submit everything else: `qsub –v vhr=00 `
(_Note change to "vhr" in qsub commands_)

From your EVS testing directory, the following scripts should be run using the set up in step (1):
```
dev/drivers/scripts/prep/cam/jevs_cam_hireswarw_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswarw_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswarwmem2_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswarwmem2_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswfv3_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hireswfv3_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_href_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hrrr_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_hrrr_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_namnest_precip_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_namnest_severe_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_radar_prep.sh
dev/drivers/scripts/prep/cam/jevs_cam_severe_prep.sh
```
```
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_href_spcoutlook_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hrrr_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_precip_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_radar_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_severe_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_namnest_snowfall_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_nam_firewxnest_grid2obs_stats.sh
```
```
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_cape_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_cape_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ctc_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ctc_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_grid2obs_ecnt_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_precip_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_precip_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_precip_spatial_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_profile_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_profile_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_snowfall_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_snowfall_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_spcoutlook_past31days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_spcoutlook_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_nam_firewxnest_grid2obs_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_grid2obs_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_headline_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_precip_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_snowfall_plots.sh
```
_[Total: 13 prep jobs, 31 stats jobs, 20 plots jobs]_

- [x] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [x] Do these updates/additions include sufficient testing updates? **Yes**

- [x] Please complete this pull request review by **11/17/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA Let me know when your Final CAM PR is in a pretty stable state and I will take a look at it! Thanks!

**Comment by MarcelCaron-NOAA** [comment]
@AliciaBentley-NOAA This PR is in a stable state now!  Thanks

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA I have looked over your Final CAM PR and I think that it looks excellent. I only have a few questions and comments for you (which isn't bad at all considering you changed 215 files):

1) Should "FATAL ERROR" always accompany the use of err_exit? (CC @ShelleyMelchior-NOAA @PerryShafran-NOAA )

2) Is the syntax surrounding $NDATE in your /parm files correct? It just looks different and I wanted to flag it.
`export LOG_TEMPLATE="${SAVE_DIR}/logs/EVS_verif_plotting_job{njob}_$($NDATE)_$$.out"`

3) Should we be using cpreq to copy prep files to their final location? If a prep file doesn't exist (which they just don't sometimes, let's be honest), trying to copy using cpreq will kill the job and produce an error. For .stat and plots files, sure. We should always have those to copy, I've been told. But does it make sense to use cpreq for prep? Perhaps it's ok because it's gone through a lot of checks to even get to the copy step?

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @MarcelCaron-NOAA . I have cloned your fork and checked out branch `bugfix/cam_final_ee2`

**Comment by ShelleyMelchior-NOAA** [comment]
The prep processing has completed. Please review. Looks good to me except for severe which is missing a file: 
` /lfs/h1/ops/prod/dcom/20231025/validation_data/weather/spc/spc_reports_20231025.csv` I will re-run that w/ an older date.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/cam`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_*_prep.o1079219*`

UPDATE: ok, apologies for so many missing data emails, @MarcelCaron-NOAA and @AliciaBentley-NOAA ! I got bit by the change of date from Nov 1 to Nov 2 and lack of availability of data in dcom after the date change for the PDY settings. I finally found the magic combination to get spc_otlk data. But the good news is the cam_severe_prep job has been thoroughly tested in the case of missing data! 😆 

Summary -- prep is tested end to end.

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA It looks like the changes made worked.  Checking the log files, all jobs completed successfully, and COMOUT looks good!  Thanks

**All prep jobs look good to me!**

**Comment by MarcelCaron-NOAA** [comment]
@AliciaBentley-NOAA 

> @MarcelCaron-NOAA I have looked over your Final CAM PR and I think that it looks excellent. I only have a few questions and comments for you (which isn't bad at all considering you changed 215 files):
> 
> 1. Should "FATAL ERROR" always accompany the use of err_exit? (CC @ShelleyMelchior-NOAA @PerryShafran-NOAA )

I tried following the changes made in the the global-det PR ([example](https://github.com/NOAA-EMC/EVS/blob/b5180478fe4e109fb3a75becdd1127ab7eef0e30/scripts/plots/global_det/exevs_global_det_atmos_long_term_plots.sh#L14)) in which the failure case of a conditional is an err_exit command with the error message, but no "FATAL ERROR" in the message.   
> 2. Is the syntax surrounding $NDATE in your /parm files correct? It just looks different and I wanted to flag it.
>    `export LOG_TEMPLATE="${SAVE_DIR}/logs/EVS_verif_plotting_job{njob}_$($NDATE)_$$.out"`

Thanks for flagging this.  I double-checked just now to make sure it works, and it does:
```
[marcel.caron@dlogin08 marcel.caron] ml prod_util
[marcel.caron@dlogin08 marcel.caron] export LOG_TEMPLATE="${USER}/logs/EVS_verif_plotting_job1_$($NDATE)_$$.out"
[marcel.caron@dlogin08 marcel.caron] echo $LOG_TEMPLATE
marcel.caron/logs/EVS_verif_plotting_job1_2023110212_32099.out
```
Checking the stdout files from my tests, the naming of log files using NDATE seems to be working correctly:
```
[marcel.caron@dlogin08 marcel.caron] grep "LOG_TEMPLATE=" /lfs/h2/emc/vpppg/noscrub/marcel.caron/jevs_cam_headline_plots.o107879770
...
0 + LOG_TEMPLATE=/lfs/h2/emc/stmp/marcel.caron/evs_test/prod/tmp/jevs_cam_headline_plots.107879770.dbqs01/headline/out/logs/EVS_verif_plotting_job9_2023110113_124062.out
...
```

> 3. Should we be using cpreq to copy prep files to their final location? If a prep file doesn't exist (which they just don't sometimes, let's be honest), trying to copy using cpreq will kill the job and produce an error. For .stat and plots files, sure. We should always have those to copy, I've been told. But does it make sense to use cpreq for prep? Perhaps it's ok because it's gone through a lot of checks to even get to the copy step?

Yes, for all prep cpreq commands, if a file is missing and can't be copied, it will not reach the command, either because the conditional loops through files that exist based on a wildcard expression, or it directly checks whether or not the file exists before copying.  I'm not sure if cpreq is required here though, since the data that are being copied are already available based on the check.

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA: 

1) @malloryprow ran a test of err_exit, and it produces the following:

```
err_exit "No file"
-------------------------------------------------------------
-- FATAL ERROR: No file
-- ABNORMAL EXIT at Thu Nov  2 13:22:01 UTC 2023 on dlogin07
-------------------------------------------------------------
```
So we are good there! No need to add it or it will be written twice. 

2) I'm glad that the $NDATE syntax worked! It just looked like an abnormal number of parentheses. 

3) If the prep files have gone through enough checks to guarantee that they exist by the time it gets to cpreq, you can continue to use it. If NCO needs to change it back to cp for some unknown reason, they can! 

**Summary:** No changes are needed for any of these things and I approve for merge after this PR passes testing. Thanks!

**Comment by ShelleyMelchior-NOAA** [comment]
Great -- I will commence stats and plots shortly.

**Comment by ShelleyMelchior-NOAA** [comment]
stats processing is underway.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_*_stats.o107958*`

Several processes are still ongoing.
```
Job ID                         Username        Queue           Jobname         SessID   NDS  TSK   Memory Time  S Time
------------------------------ --------------- --------------- --------------- -------- ---- ----- ------ ----- - -----
107958822.dbqs01               shelley.melchi* dev             jevs_cam_href_*   177579    1    72  500gb 04:30 R 00:51
107958826.dbqs01               shelley.melchi* dev             jevs_cam_hrrr_*    55511    1   128  128gb 01:45 R 00:50
107958830.dbqs01               shelley.melchi* dev             jevs_cam_hrrr_*    94967    1   128  256gb 02:45 R 00:50
107958842.dbqs01               shelley.melchi* dev             jevs_cam_namne*   202911    1   128    --  01:30 R 00:50
107958888.dbqs01               shelley.melchi* dev             jevs_cam_href_*    80499    1    88   10gb 02:00 R 00:49
107958889.dbqs01               shelley.melchi* dev             jevs_cam_hrrr_*   228435    1   128  256gb 02:00 R 00:49
107958890.dbqs01               shelley.melchi* dev             jevs_cam_namne*    58215    1   128    --  01:30 R 00:49
```

**Comment by MarcelCaron-NOAA** [comment]
jevs_cam_href_grid2obs_stats is still going;  I'd expect it to be done in about an hour and will review it then.  The others have completed successfully and the output files compare well with the parallel output.

**Comment by ShelleyMelchior-NOAA** [comment]
Sounds good. I will submit plots presently while href  grid2obs completes.

**Comment by AliciaBentley-NOAA** [comment]
Thanks, @ShelleyMelchior-NOAA! I like that approach!

**Comment by MarcelCaron-NOAA** [comment]
The jevs_cam_href_grid2obs_stats job completed successfully and the output files compare well with those from the parallel.

**All stats jobs look good to me!**

**Comment by ShelleyMelchior-NOAA** [comment]
plots processing is mostly completed. cam grid2obs and precip are still processing.
```
107966921.dbqs01               shelley.melchi* dev             jevs_cam_grid2*   251199    4   512    --  10:00 R 01:15
107966927.dbqs01               shelley.melchi* dev             jevs_cam_preci*   146057    4   512    --  05:30 R 01:15
```
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/cam/`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_*_plots.o10796*`

**Comment by MarcelCaron-NOAA** [comment]
jevs_cam_grid2obs_plots is still running.  I expect it to be complete at around 9 PM EST and will check back later this evening to review.  The others have completed successfully and the respective output files look good!

**Comment by MarcelCaron-NOAA** [comment]
jevs_cam_grid2obs_plots completed successfully and the output file compares well with the parallel output.

**All plots jobs look good to me!  I have no further issues with the testing portion of this review.**

**Comment by ShelleyMelchior-NOAA** [comment]
🎉  I will completed the formal code review and then approve this PR for merge!

**Comment by ShelleyMelchior-NOAA** [comment]
@MarcelCaron-NOAA , can you tell me about `sys,exit(1)`, like in this script, `ush/cam/ush_href_plot_py/check_variables.py`? Is that "1" a hardcoded exit value?

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA It is.  It triggers after a FATAL ERROR occurs in a python script, in which case a "FATAL ERROR: ..." message is logged followed by sys.exit(1).  The error code is then caught in the ex-script.  There are many such sys.exit(1) commands in my ush scripts, but they should all by caught after the code returns to the ex-scripts.

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA @ShelleyMelchior-NOAA Thanks! I support merging this PR in its current state and continuing to discuss whether or not hardcoded exits are appropriate via email. Does that sound like a good compromise?

**Comment by AliciaBentley-NOAA** [comment]
P.S. For what it's worth, I think it might be OK. The issue in the past was hardcoding scripts with "exit 0", even when another error code may have been found earlier the script. For example, from the EE2 channel:

Lin: "Any job need to generate error code **and exit with appropriate exit code** as needed.
However, the above jobs exited with hardwired "exit 0" caused EE2 unable to review."

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks for the explanation, @MarcelCaron-NOAA . I will complete the formal code review and then approve the PR for merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Changes look good. All tests yield appropriate results. This PR is approved for merge.

**Comment by ShelleyMelchior-NOAA** [comment]
Before I merge, I need @MarcelCaron-NOAA to do a sync fork. Thanks!

**Comment by MarcelCaron-NOAA** [comment]
@ShelleyMelchior-NOAA Apologies--should be up to date now!

**Pull request merged**
