### PR TITLE
feature/global_det_atmos_plots_units

### PR DESCRIPTION
**Pull request by malloryprow**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

> Previously, global_det atmos were changing the units on the title but not the stats. This PR fixes that. There is not associated GitHub issue for this.

## Developer Questions and Checklist
* Is this a high priority PR? If so, why and is there a date it needs to be merged by?
> It would be good to get this in the parallel sooner rather than later, but not super critical need.

* Do you have any planned upcoming annual leave/PTO?
> No

* Are there any changes needed for when the jobs are supposed to run?
>No

  
- [x] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [x] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [x] References the feature branch for `HOMEevs` are removed from the code.
- [x] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [x] Jobs over 15 minutes in runtime have restart capability.
- [x] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [x] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [x] Code is using METplus wrappers structure and not calling MET executables directly.
- [x] Log is free of any ERRORs or WARNINGs.

###  **Set-up**
1. Clone my fork and checkout branch feature/global_det_atmos_plots_units
2. `ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix`

### ✅  **global_det atmos plots**
 3. `cd dev/drivers/scripts/plots/global_det`
 4. Run the following: `jevs_global_det_atmos_grid2grid_means_plots_last31days.sh`, `jevs_global_det_atmos_grid2grid_precip_plots_last31days.sh`,  `jevs_global_det_atmos_grid2grid_pres_levs_plots_last31days.sh`, `jevs_global_det_atmos_grid2grid_sea_ice_plots_last31days.sh`, `jevs_global_det_atmos_grid2grid_snow_plots_last31days.sh`, `jevs_global_det_atmos_grid2grid_sst_plots_last31days.sh`,  `jevs_global_det_atmos_grid2obs_pres_levs_plots_last31days.sh`, `jevs_global_det_atmos_grid2obs_ptype_plots_last31days.sh`, `jevs_global_det_atmos_grid2obs_sfc_plots_last31days.sh`, and `jevs_global_det_atmos_headline_plots.sh`. 
> - Set `HOMEevs` to the location of the clone.
> - Set `COMIN` to `/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`
> - Let me know when you are about to run and we can adjust `VDATE_END` if needed 
5. Run the following: jevs_global_det_atmos_long_term_plots.sh
> - Set `HOMEevs` to the location of the clone.
> - Set `COMIN` to `/lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/global/archive/evs_data`

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Ready to run.  Let me know what VDATE_END to be using.

**Comment by malloryprow** [comment]
Let's do VDATE_END=20240821.

**Comment by PerryShafran-NOAA** [comment]
Jobs are now underway.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I had to run them a second time.  I didn't realize you set VDATE_END in the dev driver script; I had changed the J-job but that didn't work.

Anyway, there is still one job running, but you can look at the .o files here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr526test/EVS/dev/drivers/scripts/plots/global_det

And the plot tarballs here: /lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/global_det

**Comment by malloryprow** [comment]
Logs look good. I'm going to put them on rzdm and review them now.

**Comment by malloryprow** [comment]
Also feel free to do the long-term plots!

**Comment by PerryShafran-NOAA** [comment]
Oops!  Don't know why I missed that instruction.  Running that now.

**Comment by malloryprow** [comment]
I reviewed the images and they all look good. Final tarball sizes match mine.

Long-term log is good and images good as well.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Approved!

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA You need to actually review it as approved to be able to merge it.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Is this up to date?  Does it need another sync fork?

**Comment by malloryprow** [comment]
> @malloryprow Is this up to date? Does it need another sync fork?

Done!

**Comment by PerryShafran-NOAA** [comment]
Super!  We have 2 approvals, time for merge!

**Pull request merged**
