### PR TITLE
Update run.ver to list libraries and models in alphabetical order

### PR DESCRIPTION
**Pull request by LoganDawson-NOAA**
Reordered library and model versions
Added ve_evs_ver for future use
Updated RTMA/URMA versions to match current production

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

No testing recommended. As a sanity check, review file changes to confirm deletion/insertion of all version numbers except for ve_evs_ver.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have reviewed the changes to run.ver and can confirm that all module/library and model ver variables are retained.
I can confirm the inclusion of the ve_evs version.

Nitpicky question ... any reason for the double blank lines between the two primary sections? (~line 42)

**Comment by LoganDawson-NOAA** [comment]
@ShelleyMelchior-NOAA there wasn't a substantive reason at all. I just removed it!

**Comment by ShelleyMelchior-NOAA** [comment]
I ran `jevs_hurricane_regional_tropcyc_stats.ecf` using the revised `run.ver` file and the process ran to completion generating the expected stats.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The revised `run.ver` looks good. Test run completed as expected.

**Pull request merged**
