### PR TITLE
feature/global_det_atmos_version_upgrade

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- Upgrade to MET v11.0.2, METplus v5.0.1, and ve/evs v1.0.0

- Updates to python script related to upgrade to using ve/evs v1.0.0 (python 3.10.4)

- Adjustment to ecf job resources

- [ ] Describe testing already performed for this Pull Request:</br>

> I am currently running in my daily EVS runs, and did testing with individual runs of each script prior to that

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> Checkout the branch
> Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_114/evs_global_det_atmos_set_up.sh. This script will link the fix files and build the executables needed for the prep.
> Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_114/run_evs_global_det_atmos_prep.sh. Run it. _After it runs have me check the output!_
> Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_114/run_evs_global_det_atmos_stats.sh. Run it. _After it runs have me check the output!_
> Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_114/run_evs_global_det_atmos_plots.sh. Run it. _After it runs have me check the output!_

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **06/01/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Beginning testing of this PR.

**Comment by malloryprow** [comment]
Let me know when the prep output is ready for me to review!

**Comment by PerryShafran-NOAA** [comment]
Prep results now available here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det/atmos.20230517

**Comment by malloryprow** [comment]
✔ prep looks good!

**Comment by PerryShafran-NOAA** [comment]
Excellent!  Starting stats now.

**Comment by malloryprow** [comment]
I was watching  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det for output. I see everything completed.

✓ stats looks good!

In terms of testing the plotting, I have /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_114/run_evs_global_det_atmos_plots.sh set up to run all the plotting jobs, but maybe we should just test a few? What do you think?

**Comment by PerryShafran-NOAA** [comment]
Let's just run it as is and see what happens.  Glad everything is looking good!

Perry

**Comment by malloryprow** [comment]
Sounds good!

**Comment by PerryShafran-NOAA** [comment]
Plots are now complete, if you want to look at them.  

Perry

**Comment by malloryprow** [comment]
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230517 is looking pretty empty. There aren't tar files for many of the jobs.

**Comment by malloryprow** [comment]
I'd give the script a re-run. Since there are restart capabilities hopefully the scripts won't take the whole time to run.

**Comment by PerryShafran-NOAA** [comment]
Yes, today's Cactus slowness could have been causing other issues with scripts.  Let's see what happens here.  

Perry

**Comment by PerryShafran-NOAA** [comment]
I re-ran the plots last night.  Please take a look at the plots to see if things are better.  If not, I'll re-run again.  Seems Cactus may be better today?

**Comment by malloryprow** [comment]
Cactus does seem better. /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230517 looks that same as it did yesterday though.

**Comment by PerryShafran-NOAA** [comment]
I will have to re-run again.  These were run yesterday so I am sure there are still issues.

**Comment by malloryprow** [comment]
I'm running some plotting jobs now and they are going just fine

**Comment by PerryShafran-NOAA** [comment]
I've started re-runs.  I'll let you know what happens.

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

The plot jobs have completed.  Now there are no tar files in the directory /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230518.  Wallclock limits have been reached (see the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/global_det/plots).  

Thoughts?

Thanks!

Perry

**Comment by malloryprow** [comment]
Shame :( I was off Friday afternoon so I don't know how Cactus was acting. Let's try to get the jobs to run in the morning. It seems like the afternoon is always a bad time.

I'd scrub /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230517 and  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230518.

**Comment by PerryShafran-NOAA** [comment]
You are still getting your wall clock exceeded on some of these plot runs.  Only 2 plot runs are still running and yet there is only one tar file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230521.  Either Cactus is too slow again, or you'll have to adjust the run times to adjust to the Cactus slowness.

Perry

**Comment by malloryprow** [comment]
I was having trouble running some development I'm doing for the sea-ice extent. When the job started it didn't do anything for 10 minutes and then the module loads were slow. I have run the jobs they have finished in the wallclock limit numerous times before.

I'd say we just run a few of the jobs and check the output. Want to clear out /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230521 to start with a clean slate? Then start with jevs_global_det_atmos_grid2grid_means_plots_31days.ecf.

**Comment by malloryprow** [comment]
Or we can put this on hold until after the production switch? Up to you.

**Comment by PerryShafran-NOAA** [comment]
Trying one more time running the one plot job that you suggested.  If that doesn't work, I'll need to do some work on the global_ens PR today.  

Perry

**Comment by malloryprow** [comment]
Sounds good. I know that PR has been in the works for awhile. I'm fine with putting a pause in this if we need to!

**Comment by AliciaBentley-NOAA** [comment]
Hi everyone,

We did ask Perry to extend wallclock times during the testing of another
global_det PR when Cactus was running very slowly. I would be open to doing
that again here to get this PRs through! I suspect that working on the
global_ens PR will still be impacted by Cactus' slowness, so whatever
approach Perry thinks is the most efficient for the remaining PRs. Thanks!

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
Unfortunately, I ran with the one plot job that Mallory suggested, and that one, too, was killed when reaching the wall clock time.  

It is also true that the global_ens will also likely be impacted by this slowness as well, so I think we'll need to rejigger run times on these plot runs and retry later.

Perry

**Comment by malloryprow** [comment]
Should we put a pin in this until we figure out how to handle the directories in COM for restart? Or potentially cut the images being produced from the grid2obs sfc jobs (meeting scheduled to discuss that on 5/31).

**Comment by AliciaBentley-NOAA** [comment]
Hi all,

With only a few work days left until the EVS Beta Test starts, I'd be ok
with Perry scrubbing individual images, extending the runtimes, and getting
this merged. It's very likely that other EVS developers will need Mallory's
help with restart capabilities, etc., and I'd like this PR to be all set
before Mallory changes gears. It seems like the most likely solution from
Justin Cooke was that NCO will increase the number of files allowed in /com
for EVS to make this work, so changes to the EVS code may not be happening
anyway. I don't want this PR to wait until our meeting on 5/31 either.
That's cutting it way too close for something that's very good already and
essentially done.

Can we turn those individual image scrubbers on soon, Perry? Thanks.

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
Yes, I have the scrubber in place.  It should run every day at 02Z for the latest global_det runs.

For this PR, how long should I extend the runs for?  I can give it one more test, or just run one individual plot job and call it a day.   

Perry

**Comment by malloryprow** [comment]
I'd be comfortable with just running 1. When we initially started testing, the ones that were created matched what I was getting so we know some of them were good. I'd feel confident giving 1 a run and if it looks good, we can merge. Shall we run jevs_global_det_atmos_grid2grid_pres_levs_plots_31days.ecf?

**Comment by malloryprow** [comment]
Also probably definitely a good idea to increase the walltime. This morning I was trying to copy around a ~5GB directory and it took an insane amount of time.

**Comment by PerryShafran-NOAA** [comment]
I'm running two right now:  the jevs_global_det_atmos_grid2grid_means_plots_31days.ecf and the jevs_global_det_atmos_grid2obs_sfc_plots_90days.ecf.  Feel like a 90days run should be tested.  I added the run time to around 4 hours for each one.  Hopefully that will be good.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Looks like the grid2grid_means_plots_31days completed and there is a tarball.  Finished in just 12 minutes too!  

Perry

**Comment by malloryprow** [comment]
✓ Woohoo! evs.plots.global_det.atmos.grid2grid_means.last31days.v20230522.tar matches my output!

Will check the output from jevs_global_det_atmos_grid2obs_sfc_plots_90days.ecf when yours and mine are both done running.

**Comment by PerryShafran-NOAA** [comment]
The 90 day plot completed in just a hair under 2 hours.  I don't remember the expected run time for that one.  It produced a plot tar ball.  Please check that one out.  

I think based on what Alicia said earlier that we can merge this now?

**Comment by AliciaBentley-NOAA** [comment]
Hi Perry and Mallory,

I think that everything else worked before this Cactus slow down, so if
these two jobs ran and the output matches Mallory's 31-day and 90-day
plots, I think this can be approved and merged! Thank you very much!

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by malloryprow** [comment]
✓ We are good with evs.plots.global_det.atmos.grid2obs_sfc.last90days.v20230522.tar!

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by PerryShafran-NOAA** [comment]
Excellent!  I will go ahead and merge.

**Pull request merged**
