### PR TITLE
bugfix/ops_cam_href_spcoutlook

### PR DESCRIPTION
**Pull request by malloryprow**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

jevs_cam_href_spcoutlook failed in operations over the weekend. A small verifying area didn't catch any match pairs resulting in StatAnalysis creating a 0 byte sized file. This caused the code to fail. This fixes it to operational code delivery.

## Developer Questions and Checklist
* Is this a high priority PR? If so, why and is there a date it needs to be merged by?
> Yes, merge by 12/23 to send CDF.

* Do you have any planned upcoming annual leave/PTO?
> 12/24-12/27

* Are there any changes needed for when the jobs are supposed to run?
> No
  
- [ ] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [ ] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [ ] References the feature branch for `HOMEevs` are removed from the code.
- [ ] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [ ] Jobs over 15 minutes in runtime have restart capability.
- [ ] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [ ] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [ ] Code is using METplus wrappers structure and not calling MET executables directly.
- [ ] Log is free of any ERRORs or WARNINGs.

### Set-up

1. Clone my fork and checkout branch bugfix/ops_cam_href_spcoutlook
2. ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix
3. Uncomment `evs_ver` in versions/run.ver

### ✅  cam stats
4. `cd dev/drivers/scripts/stats/cam`
5. Run jevs_cam_href_spcoutlook.sh

> * Set HOMEevs to the location of the clone.
> * Set COMIN to /lfs/h1/ops/prod/com/$NET/$evs_ver_2d
> * Add `export VDATE=20241221`
> * Add `export EVSINspcotlk=/lfs/h1/ops/prod/com/evs/v1.0/prep/cam`

### CODE REVIEW

**Review by AliciaBentley-NOAA — APPROVED** [review]
I have looked over these changes and believe that they look good. I approve this for merge if testing shows that it works. If NCO needs it faster than additional testing will allow, please let Perry know. Thanks!

CC @malloryprow @PerryShafran-NOAA

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Testing is underway.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The job is finished.  There may be some issues.  

See /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr622test/EVS/dev/drivers/scripts/stats/cam/jevs_cam_href_spcoutlook_stats.o273906

`WARNING: CPU oversubscription detected for application`

and 

`12/23/2024 15:11:47  M    ncpus 4.0 exceeded limit 2 (burst)`

The stats files are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam
The working directory is here:  /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_cam_href_spcoutlook_stats.274376.dbqs01

**Comment by PerryShafran-NOAA** [comment]
Also:

```
WARNING: PointStatVxOpt::process_config() -> The range of requested observation pressure levels is not contained within the range of requested forecast pressure levels.  No vertical interpolation will be performed for observations falling outside the range of forecast levels.  Instead, they will be matched to the single nearest forecast level.
WARNING: 
```

And there is no final stats file.

**Comment by malloryprow** [comment]
All files in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/atmos.20241221/href/spcoutlook/point_stat_HREF_MEANmean_PREPBUFR_CONUS_SFC_FHR are 240 bytes like when ops failed, but the job did not fail. No empty final stat file copied to /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/cam/href.20241221. :+1: 

The WARNING is a known Bugzilla resolved in the next METplus version (https://docs.google.com/document/d/13ZSZUk2eiEJKkZ4wkHHuGQ5WHq79k4qXbLS-kM2Ls_c/edit?tab=t.0#heading=h.z2kux12un12v)

NCO didn't note anything about the CPU over subscription but I noted it in the Fixes and Additions document. It may have been resolved already in develop.

**Comment by PerryShafran-NOAA** [comment]
Oh, OK, so this is all the expected result.  Good to know!  In PR 623, the develop version, there was indeed no oversubscription.  

I guess then you are satisfied with the results of this PR?

**Comment by malloryprow** [comment]
Yup, I'm good. Thanks!

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  I will approve this for merge.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Can you merge this as well?

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Do we need @AndrewBenjamin-NOAA to approve?  You had asked for 3 approvals, and you now have 2 approvals.

**Comment by PerryShafran-NOAA** [comment]
Oh, Andrew is out all week, but I do see that I can press the Squash and merge button.  Let me know if I should go ahead and do that.

**Comment by malloryprow** [comment]
He is on leave for the next two weeks. I just added him so he will see it when he gets back.

**Comment by PerryShafran-NOAA** [comment]
Oh, OK, but I can still merge and thus I'll do so.

**Pull request merged**
