### PR TITLE
feature/global_det_atmos_sea_ice_extent

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

* Adjust prep step for OSI-SAF
* Change lat-lon grid to polar stereographic grids for sea-ice verification
* Added stats and plots for sea-ice extent

- [ ] Describe testing already performed for this Pull Request:</br>

> Jobs are running daily in a cron

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Checkout the branch
Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_124/evs_global_det_atmos_set_up.sh. This script will link the fix files and build the executables needed for the prep.
Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_125/run_evs_global_det_atmos_prep.sh. Run it. After it runs have me check the output!
Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_125/run_evs_global_det_atmos_stats.sh. Run it. After it runs have me check the output!
Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_125/run_evs_global_det_atmos_plots.sh. Run it. After it runs have me check the output!

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **06/15/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Pulling in this PR for testing now.

Perry

**Comment by PerryShafran-NOAA** [comment]
Do you mean pr_125 for the directory for your set up scripts, rather than pr_124?

Perry

**Comment by malloryprow** [comment]
Yes, pr_125. I thought I updated the directories in the PR but guess I didn't. I'll fix it now.

**Comment by PerryShafran-NOAA** [comment]
No problem; I have the files.  I was surprised when the cp command couldn't find the files.

**Comment by PerryShafran-NOAA** [comment]
The prep is done.  Please take a look at the output here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det/atmos.20230531

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/global_det/prep 

Perry

**Comment by malloryprow** [comment]
:D Prep is good!

**Comment by malloryprow** [comment]
For running the stats today, you'll need to re-run the prep step!

**Comment by PerryShafran-NOAA** [comment]
Of course, was planning to do so!  But this time I won't validate prep with you, I'll go right to stats.

Perry

**Comment by malloryprow** [comment]
I was watching the stats log to see when the jobs finished. Stats are good! 👍 

There are only two plots jobs and they run in <5 min, so we should be able to get this one done this morning!

**Comment by PerryShafran-NOAA** [comment]
You are on the ball as usual!  I was in a meeting so I hadn't been keeping track.

I'll be running the plots then.  Then another meeting, then probably lunch.  I'm assuming you'll be keeping an eye on stuff while it's running.

Thanks!

Perry

**Comment by malloryprow** [comment]
Yup! I'll be on watch.

**Comment by malloryprow** [comment]
Plots are good! This PR is good to go! 👍

**Comment by PerryShafran-NOAA** [comment]
Great, thanks!  I'll merge now.

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
