### PR TITLE
Feature/naefs precip bugfix

### PR DESCRIPTION
**Pull request by StevenSimon-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

I ran the naefs prep driver for two consecutive days and confirmed that the expected cmce_bc and gefs_bc prep files were fully accounted for and that the associated log file did not have any visceral ERRORs or WARNINGs. To test the naefs precip stats job, I needed the gefs and cmce prep data (validation datasets) for the same consecutive days, so I copied those over from the emc.vpppg COMUT to my local COMOUT. Then I ran the naefs precip stats driver and confirmed that the associated log file no longer had the "first 11 entries MetPlus WARNING" and that the expected small and larger naefs precip stats files were generated.   

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

1. Run he naefs prep driver for two consecutive days and confirm that the expected cmce_bc and gefs_bc prep files are fully accounted for and that the associated log file do not have any visceral ERRORs or WARNINGs.

2. Copy over cmce and gefs prep files (validation datasets) from the emc.vpppg COMOUT to the local COMOUT for the same consecutive days.

3. Run the naefs precip stats driver and confirm that the associated log file no longer has the "first 11 entries MetPlus WARNING" and that the expected small and larger naefs precip stats files are generated successfully.       

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

Yes

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Probably yes.

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@StevenSimon-NOAA I am beginning work on your PR.  As previously done, since this is a bugfix PR, I will run this PR experiment twice:  once as is for the current versions of MET/METplus, and again for the beta versions of MET and METplus.  

I am starting by following your first instruction to run the NAEFS prep driver on two consecutive days.  What I'm probably going to do is to run it for today, then run it again by setting VDATE (or INITDATE, whichever is proper for this job) to yesterday and run again.  That way we can move into steps 2 and 3 sooner.  

I'll run Step 1 and have you validate that.  Then I'll follow the instructions and run steps 2 and 3 and have you validate again.  This should work fine.

@AliciaBentley-NOAA and @ShelleyMelchior-NOAA for awareness.

**Comment by PerryShafran-NOAA** [comment]
@StevenSimon-NOAA I have now completed 2 days worth of naefs prep jobs.  Please look at the results here:

.o file: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr474test/EVS/dev/drivers/scripts/prep/global_ens
output: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20240428, atmos.20240429

Let me know if things look good to you.

**Comment by StevenSimon-NOAA** [comment]
> @StevenSimon-NOAA I have now completed 2 days worth of naefs prep jobs. Please look at the results here:
> 
> .o file: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr474test/EVS/dev/drivers/scripts/prep/global_ens output: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20240428, atmos.20240429
> 
> Let me know if things look good to you.

The log files indicate that all naefs prep jobs ran to completion with no visceral ERRORs or WARNINGs. The COMOUT for both days show that all cmce_bc and gefs_bc prep files are fully accounted for and that the gefs_bc 24h prep files have only one listing for APCP per file (the expected result).

**Comment by PerryShafran-NOAA** [comment]
Excellent!  Now to move on to the stats step.

**Comment by PerryShafran-NOAA** [comment]
@StevenSimon-NOAA Just wanted to check, I needed to fill out the cmce and gefs prep directories *only* for those 2 days that I just tested on in the prep step.  I know that global_ens usually requires 16 days' worth of data, but in this case I am going to point to my own archive of those two directories and then run the naefs precip step.  This should be all I need to do?

**Comment by StevenSimon-NOAA** [comment]
> @StevenSimon-NOAA Just wanted to check, I needed to fill out the cmce and gefs prep directories _only_ for those 2 days that I just tested on in the prep step. I know that global_ens usually requires 16 days' worth of data, but in this case I am going to point to my own archive of those two directories and then run the naefs precip step. This should be all I need to do?

That would be correct. We need to have the gefs and cmce prep files for those two days as well. In this case, we do not need the full 16 days of prep data to generate naefs precip stats free of the "11 entry WARNING".

**Comment by PerryShafran-NOAA** [comment]
OK, thanks!  The job is currently underway.

**Comment by PerryShafran-NOAA** [comment]
Also, a PR was merged, so please do a sync fork.

**Comment by StevenSimon-NOAA** [comment]
Just added the recent merge to the PR.

**Comment by PerryShafran-NOAA** [comment]
@StevenSimon-NOAA The stats job is finished.  Please check the output:

.o file: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr474test/EVS/dev/drivers/scripts/stats/global_ens
output: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens

**Comment by StevenSimon-NOAA** [comment]
> @StevenSimon-NOAA The stats job is finished. Please check the output:
> 
> .o file: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr474test/EVS/dev/drivers/scripts/stats/global_ens output: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens

The log file indicates that that the naefs stats job ran to completion with no visceral ERRORs or WARNINGs, including the 11 entries WARNING we aimed to eliminate. The stats COMOUT shows that all small and large naefs stats files are fully accounted for, in conjunction with the two consecutive days of naefs and gefs prep data as input.

**Comment by PerryShafran-NOAA** [comment]
@StevenSimon-NOAA Excellent!  We'll need to do this test again with the betas too, but it's getting late in the day and I'll work on the beta tests tomorrow.  I would suspect we'll get the same results, but we still need to do them.

@AliciaBentley-NOAA @ShelleyMelchior-NOAA for awareness.

**Comment by PerryShafran-NOAA** [comment]
@StevenSimon-NOAA OK, now we are going to repeat yesterday's tests, but with the beta versions of met and metplus.  I'll be running the prep data for 20240429 and 20240430.

**Comment by PerryShafran-NOAA** [comment]
@StevenSimon-NOAA The prep jobs for both dates are done.  Please check the most recent .o files in the same directory above.  Please check to see that the beta3 versions of met and metplus were used, as well as checking for errors.  Then check the output directory in noscrub above, dates 20240429 and 20240430.  Double check that the files you are looking at are dated May 2 (today) and that they are what you expect.

**Comment by StevenSimon-NOAA** [comment]
> @StevenSimon-NOAA The prep jobs for both dates are done. Please check the most recent .o files in the same directory above. Please check to see that the beta3 versions of met and metplus were used, as well as checking for errors. Then check the output directory in noscrub above, dates 20240429 and 20240430. Double check that the files you are looking at are dated May 2 (today) and that they are what you expect.

The log files indicate that all naefs prep jobs used the correct beta versions of met and metplus and ran to completion with no visceral ERRORs or WARNINGs. The COMOUT for both days (20240429 and 20240430) show that all cmce_bc and gefs_bc prep files were retrieved at May 2nd, are fully accounted for, and that the gefs_bc 24h prep files have only one listing for APCP per file (the expected result).

**Comment by PerryShafran-NOAA** [comment]
@StevenSimon-NOAA Good news!  After the MEG and after lunch, I will do the stats job.

**Comment by StevenSimon-NOAA** [comment]
> @StevenSimon-NOAA Good news! After the MEG and after lunch, I will do the stats job.

Sounds good. Just remember to add the gefs and cmce prep data to the respective days before kicking off the naefs precip stats job.

**Comment by PerryShafran-NOAA** [comment]
@StevenSimon-NOAA We are seeing WARNINGs similar to ones that we have seen in other PRs.  See here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr474test/EVS/dev/drivers/scripts/stats/global_ens/jevs_global_ens_naefs_atmos_precip_stats.o130749239

`05/02 16:13:31.431 metplus.c6fbaca3 (met_config.py:908) WARNING: Both GRID_STAT_CLIMO_MEAN_INPUT_TEMPLATE and GRID_STAT_CLIMO_MEAN_FILE_NAME are set. Using value set in GRID_STAT_CLIMO_MEAN_FILE_NAME (/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr474test/EVS/fix/climos/atmos/ccpa/ccpa_24hr_1p0_prob_{valid?fmt=%m%d}.grib2)`

Wasn't this fixed in a previous PR?  Maybe it wasn't changed in any NAEFS config files previously?  Can we check?  

@AliciaBentley-NOAA @ShelleyMelchior-NOAA for awareness

**Comment by StevenSimon-NOAA** [comment]
> @StevenSimon-NOAA We are seeing WARNINGs similar to ones that we have seen in other PRs. See here:
> 
> /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr474test/EVS/dev/drivers/scripts/stats/global_ens/jevs_global_ens_naefs_atmos_precip_stats.o130749239
> 
> `05/02 16:13:31.431 metplus.c6fbaca3 (met_config.py:908) WARNING: Both GRID_STAT_CLIMO_MEAN_INPUT_TEMPLATE and GRID_STAT_CLIMO_MEAN_FILE_NAME are set. Using value set in GRID_STAT_CLIMO_MEAN_FILE_NAME (/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr474test/EVS/fix/climos/atmos/ccpa/ccpa_24hr_1p0_prob_{valid?fmt=%m%d}.grib2)`
> 
> Wasn't this fixed in a previous PR? Maybe it wasn't changed in any NAEFS config files previously? Can we check?
> 
> @AliciaBentley-NOAA @ShelleyMelchior-NOAA for awareness

This was not handled in a prior PR. I was advised to keep those out of bugfix PRs until down the road. It is my understanding that these are trivial deprecation WARNINGs that will become applicable only after MetPlus 6.0 and Met 12.0 are implemented.

**Comment by PerryShafran-NOAA** [comment]
Right, it's coming back to me, as I have not seen this in any of Mallory's or your previous bugfix PRs.  

Can you examine the .o file for other WARNINGs or ERRORs, and then check the stats files in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens?  Thanks!

**Comment by ShelleyMelchior-NOAA** [comment]
Some background. The climo reorder bug was only fixed in the bugfix branch and was not ported into develop. The beta3 versions for MET/METplus already have the fix for climo ordering included.

**Comment by PerryShafran-NOAA** [comment]
I'm not sure this had/has anything to do with the climate reorder, but these INPUT_TEMPLATE vs FILE_NAME thing that I think that the DTC is fixing for us in a future beta or in the final release.  Let me find the issue at hand.

**Comment by PerryShafran-NOAA** [comment]
Ah yes, from another PR:

"From Steve: WARNING: Both POINT_STAT_CLIMO_MEAN_INPUT_TEMPLATE and POINT_STAT_CLIMO_MEAN_FILE_NAME are set. Using value set in POINT_STAT_CLIMO_MEAN_FILE_NAME (/lfs/h2/emc/vpppg/noscrub/emc.vpppg/EVS/fix/climos/atmos/era5/mean_{valid?fmt=%m%d}). The FILE_NAME Option is new and folds in the INPUT_DIRECTORY and INPUT_TEMPLATE. Do we simply combine INPUT_DIRECTORY with INPUT_TEMPLATE under FILE_NAME to eliminate the deprecation WARNING.

"From DTC: This is a problem in the logic of METplus, calling the same subroutine twice. And expect George to fix this in METplus-6.0.0-beta4."

I had forgotten about this, but it's now coming back to me.  This is something for the DTC to fix.

**Comment by StevenSimon-NOAA** [comment]
> Right, it's coming back to me, as I have not seen this in any of Mallory's or your previous bugfix PRs.
> 
> Can you examine the .o file for other WARNINGs or ERRORs, and then check the stats files in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens? Thanks!

The naefs precip stats job for VDATE 20240430 successfully ran to completion. Aside from the highlighted MetPlus Deprecation WARNING, the naefs precip stats log file indicates no visceral ERRORs or WARNINGs, including the 11 entries WARNING we aimed to eliminate. The stats COMOUT shows that all small and large naefs stats files are fully accounted for, in conjunction with the now three consecutive days of naefs, cmce, and gefs prep data as input. Furthermore, the naefs.20240430 large precip stats file is larger than the naefs.20240429 large precip stats file, which is expected because it spans a more extensive prep archive (3 days vs 2 days).

**Comment by PerryShafran-NOAA** [comment]
Excellent!  Then this PR is good to be merged.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
