### PR TITLE
Add conditions to imports of plots scripts

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

> Please include a summary of the changes and the related GitHub issue(s). Please also include relevant motivation and context.

Changes merged from PR #529 exposed several imports of plots scripts that, since the change, trigger fatal errors during prep and stats steps.  This minor fix should prevent those imports from happening during prep, stats, and certain plots jobs.

## Developer Questions and Checklist
* Is this a high priorty PR? If so, why and is there a date it needs to be merged by?

**Yes**, some cam prep jobs have been failing in the EVS parallel due to this issue.  Other jobs that point to cam prep output have been reporting missing data and are unable to run completely.  Merge ASAP, however a production switch on 9/4 may affect when PR tests can occur or be properly reviewed.

* Do you have any planned upcoming annual leave/PTO?

**No**.
* Are there any changes needed for when the jobs are supposed to run?

**No**.
  
- [x] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [x] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [x] References the feature branch for `HOMEevs` are removed from the code.
- [x] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [x] Jobs over 15 minutes in runtime have restart capability.
- [x] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [x] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [x] Code is using METplus wrappers structure and not calling MET executables directly.
- [x] Log is free of any ERRORs or WARNINGs.

## Testing Instructions

> Please include testing instructions for the PR assignee. Include all relevant input datasets needed to run the tests.

#### (1) Set up jobs

- symlink the EVS_fix directory locally as "fix"
- In each driver script, edit the following environment variables:
**HOMEevs** - set to your test EVS directory
**COMIN** - (_stats/plots_) set to `/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`
**COMOUT** - set to your test output directory
**SENDMAIL** - (_optional_) set to `"NO"`
**DATAROOT** - (_optional_) set to your test DATAROOT directory

#### (2) Running jobs

I recommend testing the following jobs:
```
jevs_cam_hrrr_precip_prep
```
```
jevs_cam_hrrr_precip_stats
```
```
jevs_cam_grid2obs_plots_last31days
jevs_cam_grid2obs_plots_last90days
jevs_cam_precip_plots_last31days
jevs_cam_precip_plots_last90days
jevs_cam_snowfall_plots
jevs_cam_headline_plots
```
[Total: 1 prep job; 1 stats job; 6 plots jobs]

- jevs_cam_hrrr_precip_stats can be submitted using `qsub -v vhr=19 $driver`
- All other driver scripts can be submitted using `qsub -v vhr=00 $driver`
- All jobs can be submitted at any time

#### (3) Checking jobs
Log files should be checked by the developer for the following keywords:

```
check="FATAL\|WARNING\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|failed\|unexpected\|exceeded"
grep "$check" $logfile
```

_**Note:** jevs_cam_hrrr_precip_stats will likely have missing data warnings, but we are primarily looking for FATAL ERRORs, which have been occurring due to the issue this PR is addressing._

### CODE REVIEW

**Comment by malloryprow** [comment]
@AliciaBentley-NOAA I added you as a reviewer with @AndrewBenjamin-NOAA out. Is that okay?

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow No problem! I'll review this right now!

**Review by AliciaBentley-NOAA — APPROVED** [review]
I have looked over this PR and believe that it will address the issues in the emc.vpppg parallel that appeared after the previous CAM PR was merged. I approve this PR to be merged after it is tested on the prep jobs that failed and other applicable CAM jobs (e.g., plots). 

CC @malloryprow @MarcelCaron-NOAA

**Comment by malloryprow** [comment]
### jevs_cam_hrrr_precip_prep with vhr=00

**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr541/EVS/dev/drivers/scripts/prep/cam/jevs_cam_hrrr_precip_prep.o151094367
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr541/evs/v2.0/prep/cam
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hrrr_precip_prep.151094367.cbqs01

**Comment by malloryprow** [comment]
Since the prep step was failing I'm not sure the needed input files for stats are available for jevs_cam_hrrr_precip_stats. What files can I link to the emc.vpppg parallel? Are there other dates that the prep job should be run for to make sure the needed inputs are available?

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow @MarcelCaron-NOAA Is there any chance that the missing prep files can be copied into the emc.vpppg parallel from /prod? I'm not sure how different the dev and prod prep files are at this point!

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow @AliciaBentley-NOAA 
That's a good idea.  Let's point to the prod directory for HRRR stats:
```
export COMIN="/lfs/h1/ops/prod/com/evs/v1.0"
```
I would also submit that job a day earlier than normal to make sure the needed prep files exist, so PDYm3:
`qsub -v vhr=19,VDATE=$(date -d "-3 days" +"%Y%m%d") $driver`

**Comment by MarcelCaron-NOAA** [comment]
Also @malloryprow, the following job completed successfully and output look normal:
✔️ jevs_cam_hrrr_precip_prep

👍 the cam prep run is complete.  No other concerns about prep from me

**Comment by malloryprow** [comment]
### jevs_cam_hrrr_precip_stats.sh with vhr=19 and VDATE=20240831

For this run, COMIN=/lfs/h1/ops/prod/com/evs/v1.0

**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr541/EVS/dev/drivers/scripts/stats/cam/jevs_cam_hrrr_precip_stats.o151096804
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_hrrr_precip_stats.151096804.cbqs01
**COMOUT:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr541/evs/v2.0/stats/cam

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow, the following completed successfully and the output looks normal:
✔️ jevs_cam_hrrr_precip_stats

👍 the cam stats run is complete. No other concerns about stats from me

**Comment by malloryprow** [comment]
### jevs_cam_grid2obs_plots_last31days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr541/EVS/dev/drivers/scripts/plots/cam/jevs_cam_grid2obs_plots_last31days.o151097968
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_grid2obs_plots_last31days.151097968.cbqs01

### jevs_cam_grid2obs_plots_last90days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr541/EVS/dev/drivers/scripts/plots/cam/jevs_cam_grid2obs_plots_last90days.o151097969
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_grid2obs_plots_last90days.151097969.cbqs01

### jevs_cam_precip_plots_last31days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr541/EVS/dev/drivers/scripts/plots/cam/jevs_cam_precip_plots_last31days.o151097971
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_precip_plots_last31days.151097971.cbqs01

### jevs_cam_precip_plots_last90days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr541/EVS/dev/drivers/scripts/plots/cam/jevs_cam_precip_plots_last90days.o151097973
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_precip_plots_last90days.151097973.cbqs01

### jevs_cam_snowfall_plots
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr541/EVS/dev/drivers/scripts/plots/cam/jevs_cam_snowfall_plots.o151097976
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_snowfall_plots.151097976.cbqs01

### jevs_cam_headline_plots
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr541/EVS/dev/drivers/scripts/plots/cam/jevs_cam_headline_plots.o151097978
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_cam_headline_plots.151097978.cbqs01

For all, COMOUT=/lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr541/evs/v2.0/plots/cam and COMIN=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v2.0.

3 jobs are still running: both grid2obs and precip last 90 days

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow, the following completed successfully and the output tar files look normal:
✔️ jevs_cam_grid2obs_plots_last31days
✔️ jevs_cam_precip_plots_last31days
✔️ jevs_cam_snowfall_plots
✔️ jevs_cam_headline_plots

Still waiting on the following:
⏳  jevs_cam_grid2obs_plots_last90days
⏳  jevs_cam_precip_plots_last90days

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow, the following have completed successfully and the output tar files look normal:
✔️ jevs_cam_grid2obs_plots_last90days
✔️ jevs_cam_precip_plots_last90days

👍 all runs are complete. No other concerns about jobs in this PR from me

**Review by malloryprow — APPROVED** [review]
Testing successful and code changes look good!

**Comment by malloryprow** [comment]
Thanks for the changes @MarcelCaron-NOAA!

**Pull request merged**
