### PR TITLE
bugfix/dev_cam_href_spcoutlook

### PR DESCRIPTION
**Pull request by malloryprow**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

jevs_cam_href_spcoutlook failed in operations over the weekend. A small verifying area didn't catch any match pairs resulting in StatAnalysis creating a 0 byte sized file. This caused the code to fail. This fixes it for develop.

## Developer Questions and Checklist
* Is this a high priority PR? If so, why and is there a date it needs to be merged by?
> The operational PR is more important so this isn't as important.

* Do you have any planned upcoming annual leave/PTO?
> 12/24-12/27

* Are there any changes needed for when the jobs are supposed to run?
> No
  
- [ ] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [ ] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [ ] References the feature branch for `HOMEevs` are removed from the code.
- [ ] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [ ] Jobs over 15 minutes in runtime have restart capability.
- [ ] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [ ] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [ ] Code is using METplus wrappers structure and not calling MET executables directly.
- [ ] Log is free of any ERRORs or WARNINGs.

### Set-up

1. Clone my fork and checkout branch bugfix/dev_cam_href_spcoutlook
2. ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix

### :black_square_button:  cam stats
3. `cd dev/drivers/scripts/stats/cam`
4. Run jevs_cam_href_spcoutlook.sh

> * Set HOMEevs to the location of the clone.
> * Set COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d
> * Add `export VDATE=20241221`
> * Add `export EVSINspcotlk=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/v2.0/prep/cam`

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@malloryprow PR is underway.  I have changed COMOUT slightly so I don't overwrite what is coming out of PR 622.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The job is complete.  

The .o file is here:  

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr623test/EVS/dev/drivers/scripts/stats/cam/jevs_cam_href_spcoutlook_stats.o274376
No errors, but a warning about missing SPC files:

```
0.023 + echo 'Warning:  No SPC outlook mask files available for 20241221'
0.023 + 1> mailmsg
0.025 + echo Missing mask files are '/lfs/h2/emc/vpppg/noscrub/emc.vpppg/v2.0/prep/cam/spc_otlk.20241220/spc_otlk.day1_*G227.nc' , '/lfs/h2/emc/vpppg/noscrub/emc.vpppg/v2.0/prep/cam/spc_otlk.20241219/spc_otlk.day2_*G227.nc' and '/lfs/h2/emc/vpppg/noscrub/emc.vpppg/v2.0/prep/cam/spc_otlk.20241218/spc_otlk.day3_*G227.nc'


```

Stats directory:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v2.0/stats/cam
Working directory /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_cam_href_spcoutlook_stats.274376.dbqs01

**Comment by malloryprow** [comment]
Ah that is my fault. I messed up the path for EVSINspcotlk. Should be EVSINspcotlk=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v2.0/prep/cam.

**Comment by PerryShafran-NOAA** [comment]
Oops, I copied that right in without realizing it wasn't correct.  I will share in the blame and try again.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The job ran again to completion.  Would you take a look at the output?  I see no errors or warnings in the new .o file.

**Comment by malloryprow** [comment]
Yup, everything looks good!

**Review by PerryShafran-NOAA — APPROVED** [review]
Changes work as expected.  I approve for merge.

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA We are ready for your review of this code.

**Review by AliciaBentley-NOAA — APPROVED** [review]
I also approve these changes to be merged!

CC @malloryprow @PerryShafran-NOAA

**Pull request merged**
