### PR TITLE
bugfix/global_det_envir

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- Change envir=dev to envir=prod
- Increase walltime for dev/drivers/scripts/global_det/plots/jevs_global_det_atmos_grid2grid_precip_plots_31days.sh
- Use $envir in compath.py
- Remove settings of some COMIN subdirectories in dev driver scripts

- [ ] Describe testing already performed for this Pull Request:</br>

> The global_det atmos and wave prep jobs ran fine in my parallel today. The GFS grid2obs stats are running right now, but are past the point where I though things might get weird (setting of the COMIN paths for data).

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
> 1. Clone my fork and checkout branch bugfix/global_det_envir
> 2. ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix
> 3. Run dev/drivers/scripts/global_det/prep/jevs_global_det_atmos_prep.sh
> 4. Run dev/drivers/scripts/global_det/prep/jevs_global_det_atmos_wave.sh
> 5. Run dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_gfs_grid2obs_stats.sh
> 6. Set COMIN=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver in dev/drivers/scripts/global_det/plots/jevs_global_det_atmos_grid2grid_precip_plots_31days.sh. Run dev/drivers/scripts/global_det/plots/jevs_global_det_atmos_grid2grid_precip_plots_31days.sh. This will need to run after the GFS grid2grid stats are done. The emc.vpppg parallel cron is set to run this at 1845Z so run at that time or after.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **10/13/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch: `bugfix/global_det_envir`.

**Comment by ShelleyMelchior-NOAA** [comment]
Tests 3, 4, and 5 have been submitted.
DATAROOT definitions looks good.
COMIN definitions look good.
wave prep has finished. logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_prep_00.o82486754`
The other 2 are still running ...
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_prep_00.o82486667`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_gfs_grid2obs_stats_00.o82486801`

**Comment by ShelleyMelchior-NOAA** [comment]
@malloryprow , for test 6 can I run w/ an older VDATE and run now instead of waiting until after 1845z?

**Comment by malloryprow** [comment]
:heavy_check_mark: /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_prep_00.o82486754 is good!

**Comment by malloryprow** [comment]
> `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_prep_00.o82486667`

Works for me!

**Comment by malloryprow** [comment]
> @malloryprow , for test 6 can I run w/ an older VDATE and run now instead of waiting until after 1845z?

Works for me!

**Comment by ShelleyMelchior-NOAA** [comment]
Ok, submitted the plots test for VDATE=20230919.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2grid_precip_plots_31days_00.o82487778`

**Comment by malloryprow** [comment]
:heavy_check_mark: /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_prep_00.o82486667 is good!

**Comment by malloryprow** [comment]
:heavy_check_mark: /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_gfs_grid2obs_stats_00.o82486801 and /lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_atmos_grid2grid_precip_plots_31days_00.o82487778 are both good!

Good to merge!

**Comment by ShelleyMelchior-NOAA** [comment]
Great! Looks like you need 1 sync fork. And I will do code review.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The tests checked out as expected. This PR is approved for merge.

**Pull request merged**
