### PR TITLE
feature/rtofs_comin_paths

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

1. Remove COMINxxx paths
2. Adjust scripts and configs impacted by COMINxxx  changes
3. Fix settings in METplus configs where input files are being defined with COMOUT
4.  Update to run when some files (e.g., prep) are missing 

- [ ] Describe testing already performed for this Pull Request:</br>

> I compared the file counts for the prep step to the emc.vpppg parallel; file counts matched. I ran the stats jobs for 20231008 in the emc.vpppg parallel and the stat files were the same. I tested the plots jobs using the emc.vpppg parallel as input and the tar files were the same.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

*Set-up**
> 1. Clone my fork and checkout branch feature/rtofs_comin_paths
> 2. cd sorc; ./build-fix-link.sh

**prep**
> 3. Run dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.sh

**stats**
> 4. Run dev/drivers/scripts/stats/rtofs/jevs_rtofs_argo_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_aviso_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_ghrsst_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_ndbc_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_osisaf_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_smap_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_smos_stats.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vppg/$NET/${evs_ver} .

**plots**
> 5. Run dev/drivers/scripts/plots/rtofs/jevs_rtofs_argo_grid2obs_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_aviso_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_ghrsst_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_headline_grid2grid_last90days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_ndbc_grid2obs_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_osisaf_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_smap_grid2grid_last60days_plots.sh, and dev/drivers/scripts/plots/rtofs/jevs_rtofs_smos_grid2grid_last60days_plots.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/${evs_ver}.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **11/19/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
I am working on your PR now.

**Comment by malloryprow** [comment]
Great, hopefully the stats part will be easier this time around with the changes!

**Comment by PerryShafran-NOAA** [comment]
Hi, @malloryprow 

The prep job is finished.  Please look at the following:

.o file /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr296test/EVS/dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.o106222055

The output directory:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs

Note many directories are filled as expected.

**Comment by malloryprow** [comment]
Looks good to me!

**Comment by PerryShafran-NOAA** [comment]
Great!  On to the stats step!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Think we should choose a date before 20231011?  Looks like smap and smos valiation data is not there, so I think that might be prudent.  

We do have stats files for aviso, ghrsst, and osisaf for today, though:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs/rtofs.20231011

**Comment by PerryShafran-NOAA** [comment]
I set VDATE to PDYm3 and am re-running the smap and the smos jobs.

**Comment by malloryprow** [comment]
Doing it for 20231011 is fine with me. I see the stats haven't ran yet. (ls: cannot access '/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/rtofs/rtofs.20231011': No such file or directory)

**Comment by PerryShafran-NOAA** [comment]
The smap and smos reruns are already done!

 /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs/rtofs.20231010

And we have stats for aviso, ghrsst, and osisaf here:  

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs/rtofs.20231011

Do you wish for me to re-run aviso, ghrsst, and osisaf for 20231010?  

Also, do you wish to have me kill the jobs for 20231011 for argo and ndbc and re-run them for 20231010?  Those two are still running.

**Comment by malloryprow** [comment]
Would be good to have everything for 20231010 to compare!

**Comment by PerryShafran-NOAA** [comment]
Yup, you got it!  Though argo and ndbc probably won't be done by the end of your workday, the others might.

**Comment by PerryShafran-NOAA** [comment]
I could also run the plots alongside it.  PDYm3.

**Comment by malloryprow** [comment]
Running the plots will be fine I see they ran for today /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/rtofs/rtofs.20231010 (plots uses PDYm3)

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow @PerryShafran-NOAA I've looked over this PR and don't have any recommended changes for you. Once you are both satisfied with the testing and results, I think this RTOFS PR can be merged. Thanks!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Looks like everything but argo and ndbc is complete on the stats side:

 /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs/rtofs.20231010

And most plot jobs look complete except argo:
/lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/rtofs/rtofs.20231010

Here's headline:
 /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/rtofs/headline.20231010

**Comment by malloryprow** [comment]
Everything is looking good so far!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Do you want to see .o files?  They are here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr296test/EVS/dev/drivers/scripts/stats/rtofs 
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr296test/EVS/dev/drivers/scripts/plots/rtofs

**Comment by malloryprow** [comment]
They look good too!

**Comment by malloryprow** [comment]
argo plots tar file is good too.

**Comment by PerryShafran-NOAA** [comment]
I suppose at this time all that's left to look at are argo and ndbc stats.

**Comment by malloryprow** [comment]
Yup! I think the argo stat file should be done in about 15 min. ndbc has a good bit more to get through.

**Comment by PerryShafran-NOAA** [comment]
Looks like Alicia is satisfied with all the COMIN changes.  All you have is COMIN and COMOUT for all your components.  I guess that works.  Let me look over the rest of your code as these other items run.

**Comment by malloryprow** [comment]
argo starts are good! ndbc won't be done by the end of anyone's work day, but I will check on Monday morning.

**Comment by PerryShafran-NOAA** [comment]
Yup, saw the argo stat files.  Thanks for looking!

Guess merging will have to wait until Monday.  Have a happy weekend!

**Comment by malloryprow** [comment]
ndbc file is good! We can merge this! Woohoo!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Do we need a sync fork now?  I think that we're up to date, but can you check before I merge?

**Comment by malloryprow** [comment]
Nope, branch is up to date!

**Review by PerryShafran-NOAA — APPROVED** [review]
Ready for merge.

**Pull request merged**
