### PR TITLE
Update wafs module files modified to work with ecflow workflow

### PR DESCRIPTION
**Pull request by lgannoaa**
GitHub #190 

Modified module files to work with ECFLOW workflow for implementation.
    [Yes] Describe testing already performed for this Pull Request:</br>

## Pull Request Checklist ##

    [Yes] Complete the PR description above.
    [Yes] Ensure the PR title matches the feature branch name.
    [Yes] Check to see that the output directory structure is followed
    [Yes] After submitting the PR, select Development issue with the original issue number.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks @lgannoaa ! Please do a sync fork on `feature/evs-190`.

**Comment by lgannoaa** [comment]
@ShelleyMelchior-NOAA Done. Please take a look.

**Comment by ShelleyMelchior-NOAA** [comment]
@lgannoaa , this looks good. I will approve this PR for merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All changes are approved for merge.

**Comment by YaliMao-NOAA** [comment]
The two changes look good to me

**Pull request merged**
