### PR TITLE
Feature/final aqm EE2

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

Adding WARNING in front of missing data statements and adding them to the output

Putting in meaningful docblocks and comments

Adding -p to mkdir comments to prevent "File exists" comments

Changing cp to cpreq for the plot step

Ensure that set -x is at the top of scripts

Remove hardwired WCOSS1 directories in plot comment lines

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run the prep step.
Run the stats step, using qsub -v vhr=04.  Set COMIN to emc.vpppg.
Run the plots step.  Set COMIN to emc.vpppg

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
prep processing is complete! Seems to agree w/ emc.vpppg.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/aqm/atmos.20231024/aqm/`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_prep_00.o107483447`

**Comment by PerryShafran-NOAA** [comment]
Wow you are fast.

**Comment by PerryShafran-NOAA** [comment]
Prep looks good.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Can you please remove lines 21–24 in [ush/aqm/string_template_substitution.py](https://github.com/NOAA-EMC/EVS/blob/b9ec7d3d19dd2b95e859d0a7e5f186edef2c15b1/ush/aqm/string_template_substitution.py#L21-L24)?

**Comment by ShelleyMelchior-NOAA** [comment]
> @PerryShafran-NOAA Can you please remove lines 21–24 in [ush/aqm/string_template_substitution.py](https://github.com/NOAA-EMC/EVS/blob/b9ec7d3d19dd2b95e859d0a7e5f186edef2c15b1/ush/aqm/string_template_substitution.py#L21-L24)?

ooh yes, good one! 👍

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Can you please update HOMEevs definition in J-jobs to: 
`export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}`
(i.e., change "evs" to ${NET})

**Comment by ShelleyMelchior-NOAA** [comment]
stats processing has completed for vhr=04. The results compare well w/ emc.vpppg.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/aqm/atmos.20231024/aqm/grid2obs`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_stats.o107483805`

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA done, and we (I) didn't catch that in the analyses J-jobs, so I'm just going to go ahead and include those here, if that's OK.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Agreed! I think that sounds great. We don't need to retest analyses because that change is so minor, it won't hurt anything!

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks @PerryShafran-NOAA , I will look for your push of those changes and then run aqm plots.

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA @ShelleyMelchior-NOAA That string_template python script was also in analyses, so I changed it there.  I don't know if removing those lines harms the execution of plots.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Thanks for pushing those updates! I've checked off all the remaining boxes for analyses and aqm on the EE2 checklist!

**Comment by ShelleyMelchior-NOAA** [comment]
I will re-run analyses plots and also run aqm plots. 👍

**Comment by ShelleyMelchior-NOAA** [comment]
The re-run of analyses plots completed and the tar file was produced successfully. ✔️ aqm plots is still running.

**Comment by PerryShafran-NOAA** [comment]
These will both need to be re-run.  While we were discussing with Shannon, I realized that I have no err_chk for the plotting codes.  I also use sh to call them and if I recall that's a no-no.  Testing of these seem to be working well thus far.

**Comment by ShelleyMelchior-NOAA** [comment]
I know there are some changes forthcoming, but I wanted to let you know that aqm plots completed successfully and compares well to emc.vpppg.
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/atmos.20231024`
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/headline.20231024`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_plots.o107485037`

**Comment by PerryShafran-NOAA** [comment]
Thank you!  I think that for analyses I'm going to need to add some traps in there.  Because there are a lot of NO PLOT warnings, ones that we'd expect, but it might give an err code other than 0 if we add in the err_chk (like there is no Guam for urma, and rtma-ru is only CONUS).  Thus, it will take a bit, but all will be updated in *this* PR.  Testing now.

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA @AliciaBentley-NOAA You may now do both the analyses and aqm plot runs.  But I probably won't be able to look at the results until Monday.  You can look at the code changes - I removed hardcoded exit 0 in the config scripts which I hadn't noticed that were still there.  Also I made it so that the plots that don't exist aren't run (we have no Guam for urma, while rtma_ru is only the CONUS regions), so there are no WARNINGs of plots that don't exist.

**Comment by ShelleyMelchior-NOAA** [comment]
I re-ran analyses and aqm plots processing. AQM seems good, but analyses' tar file is empty ...
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/analyses/atmos.20231028` (analyses)
COMOUT= `/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/atmos.20231026` (aqm)
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/headline.20231026` (aqm headline)

logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/`

`jevs_analyses_grid2obs_plots.o107651543`
`jevs_aqm_grid2obs_plots.o107651544`

**Comment by ShelleyMelchior-NOAA** [comment]
I re-ran analyses and aqm plots processing.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/analyses/atmos.20231028` (analyses)
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/atmos.20231026` (aqm)
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/headline.20231026` (aqm headline)

logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/`

`jevs_analyses_grid2obs_plots.o107660724`
`jevs_aqm_grid2obs_plots.o107651544`

**Comment by PerryShafran-NOAA** [comment]
I adjusted the PDYs for the plot J-jobs.  Since those plot jobs run at/after 00Z, I have made sure that plot PDYs are 1 day later than stats PDYs.  This shouldn't need any re-runs, and am working on validating Shelley's most recent runs.  Both the aqm and the analyses plot jobs look good and I would approve merging.

**Comment by ShelleyMelchior-NOAA** [comment]
Excellent! @PerryShafran-NOAA , please do a sync fork and then I can approve and merge this PR.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The changes look good. The testing yields expected results. This PR is approved for merge.

**Pull request merged**
