### PR TITLE
MET version was removed from the config file.

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
## Pull Request Testing ##
 
- [ ] Describe testing already performed for this Pull Request:</br>
This PR removes the hardcoding of MET version from EVS-RTOFS.
After modifying the EVS-RTOFS config file for grid2grid plots, the test was performed with one of the RUNs: "aviso". The test generated expected results.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
For testing please follow this steps:
1- Clone my fork and checkout this branch: bugfix/rtofs_MET_version
2- For "plots" step: cd dev/driver/scripts/plots/rtofs/
3- Run all the plot scrips that include "grid2grid" in their names.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes]**

- [ ] Please complete this pull request review by **[05/22/2024]**.</br> 

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA I will be soon be testing your PR.  I will need to test this twice; once with MET v12, using v12 stats files from the emc.vpppg para, and once with METv11, from the production.  This will need to work with both versions to be merged.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA I'm going to hold off running this PR until tomorrow; we seem to be having issues on stmp and ptmp disks and don't want to risk filling them up.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA I am running your PR now, first for the MET v 12.0.0 case.  I have brought in your code and am running all the plot scripts for all the grid2grid runs.  I will let you know the results.  

NOTE:  I am leaving the office for the day at 10:30 am.

**Comment by PerryShafran-NOAA** [comment]
All the jobs are finished.  You can find all results here:

See the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr482test/EVS/dev/drivers/scripts/plots/rtofs

rtofs tarballs are here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/rtofs, for the 20240519 directories.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : The .o files and the plot tarballs all look good.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA Great!  Now I am going to run for the MET v11 case, and copy in files from the production output.  Look in the same directories for output.

**Comment by PerryShafran-NOAA** [comment]
Correction:  The output tarball directory will be v1.0, not v2.0.  I'll let you know when all is finished.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : I checked v1.0 directory here /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/rtofs/ for MET v11 case. The plot tarballs all look good. The .o files also look as expected.

**Comment by PerryShafran-NOAA** [comment]
Excellent!  I will approve and merge the code now.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
