### PR TITLE
feature/global_det_cape_config

### PR DESCRIPTION
**Pull request by malloryprow**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

This updates the CAPE METplus configuration settings to match those made in #567 and #571.

## Developer Questions and Checklist
* Is this a high priorty PR? If so, why and is there a date it needs to be merged by?
> No
* Do you have any planned upcoming annual leave/PTO?
> Taking sick leave to go to the dentist starting 1pm on 10/15.
* Are there any changes needed for when the jobs are supposed to run?
 > No

- [ ] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [ ] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [ ] References the feature branch for `HOMEevs` are removed from the code.
- [ ] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [ ] Jobs over 15 minutes in runtime have restart capability.
- [ ] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [ ] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [ ] Code is using METplus wrappers structure and not calling MET executables directly.
- [ ] Log is free of any ERRORs or WARNINGs.

###  **Set-up**
1. Clone my fork and checkout branch feature/global_det_cape_config
2. `ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix`

### ✅  **global_det stats**
 3. `cd dev/drivers/scripts/stats/global_det`
 4. Run the following: `jevs_global_det_gfs_atmos_grid2obs_stats.sh`
> - Set `HOMEevs` to the location of the clone.
> - Set `COMIN` to `/lfs/h2/emc/vpppg/noscrub/emc.vpppg/${NET}_beta5/$evs_ver_2d`
> - Run with `VDATE=20241013` (qsub -v VDATE=20241013)

### ✅   **global_det plots**
 3. `cd dev/drivers/scripts/plots/global_det`
 4. Run the following: `jevs_global_det_atmos_grid2obs_sfc_plots_last31days.sh`
> - Set `HOMEevs` to the location of the clone.
> - Set `COMIN` to `/lfs/h2/emc/vpppg/noscrub/mallory.row/$NET/$evs_ver_2d` (I have a few days of stats files with the CAPE configuration changes)
> - Set `VDATE_END` to `20241013`

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Both the stats and plots jobs are underway.

**Comment by PerryShafran-NOAA** [comment]
OK, I'm finally logged on so I can point you to the tests from yesterday.

Stats:
.o file: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr587test/EVS/dev/drivers/scripts/stats/global_det/jevs_global_det_gfs_atmos_grid2obs_stats_00.o158290185
small stats files: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v2.0/stats/global_det/atmos.20241013
large stats file: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v2.0/stats/global_det/gfs.20241013

Plots:
.o file: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr587test/EVS/dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2obs_sfc_plots_last31days_00.o158290328
plot tarball: /lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/global_det/atmos.20241013

**Review by AndrewBenjamin-NOAA — APPROVED** [review]
These changes mirror the updates to CAPE found #567 and #571. I approve these changes once testing has concluded.

**Comment by malloryprow** [comment]
stats and plots are good for both! Logs are good too.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Good news!  I'll do the code check and then merge this in.  I do not think we need a sync of the develop branch, I think your branch is up to date.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
