### PR TITLE
TC for EVSVE1.0

### PR DESCRIPTION
**Pull request by JiayiPeng-NOAA**
## Pull Request Testing ##

- [X] Describe testing already performed for this Pull Request:</br>

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ Yes] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [Tes] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
Hi Jiayi,

This looks great, but please remove the second line in run.ver where you
specify the EVS VE version number: export evsve_ver=1.0. The EVS VE version
number is already specified on L36
<https://github.com/NOAA-EMC/EVS/blob/1688c74ca1b56c4d7936d62b1b21c593ddc2f01d/versions/run.ver#L36>
of
run.ver, so changes to run.ver are not needed in your PR. This will also
require you to change ${evsve_ver} to ${ve_evs_ver} in your various .ecf
scripts. Can you please make these few changes before Perry or Shelley
tests this PR. Thank you!

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by AliciaBentley-NOAA** [comment]
No problem. I will change it back. Thanks.

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned Jiayi's fork and checked out branch TC4EVS2VE.

**Comment by ShelleyMelchior-NOAA** [comment]
I have run `jevs_hurricane_global_det_tcgen_stats.ecf`.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_hurricane_global_det_tcgen_stats.o57614368`
COMOUT: `/lfs/h2/emc/ptmp/shelley.melchior/com/evs/v1.0/hurricane/global_det/tcgen/stats`

I have run `jevs_hurricane_global_det_tropcyc_stats.ecf`.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_hurricane_global_det_tropcyc_stats.o57615376`
COMOUT: `/lfs/h2/emc/ptmp/shelley.melchior/com/evs/v1.0/hurricane/global_det/tropcyc/stats`

I have run `jevs_hurricane_global_ens_tropcyc_stats.ecf`.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_hurricane_global_ens_tropcyc_stats.o57615836`
COMOUT: `/lfs/h2/emc/ptmp/shelley.melchior/com/evs/v1.0/hurricane/global_ens/tropcyc/stats`

@JiayiPeng-NOAA , if these look good I will move onto generating the plots.

**Comment by JiayiPeng-NOAA** [comment]
Hi Shelley,
The data you generated looks good to me.
Please go ahead and run the jobs for making the plots.
Thanks,
Jiayi

**Comment by ShelleyMelchior-NOAA** [comment]
The slowness of cactus today got me too frustrated so I didn't run the plotting code until now.

I have run `jevs_hurricane_global_det_tcgen_plots`.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_hurricane_global_det_tcgen_plots.o57678095`
COMOUT: `/lfs/h2/emc/ptmp/shelley.melchior/com/evs/v1.0/hurricane/global_det/tcgen/plots`

I have run `jevs_hurricane_global_det_tropcyc_plots.ecf`.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_hurricane_global_det_tropcyc_plots.o57678135`
COMOUT: `/lfs/h2/emc/ptmp/shelley.melchior/com/evs/v1.0/hurricane/global_det/tropcyc/plots`

I have run `jevs_hurricane_global_ens_tropcyc_plots.ecf.`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_hurricane_global_ens_tropcyc_plots.o57678434`
COMOUT: `/lfs/h2/emc/ptmp/shelley.melchior/com/evs/v1.0/hurricane/global_ens/tropcyc/plots`

**Comment by JiayiPeng-NOAA** [comment]
Hi Shelley,
I have checked the plots you generated. They are all good.
Thanks for the testing.
Jiayi

**Comment by ShelleyMelchior-NOAA** [comment]
Excellent! For a future PR, or maybe it can be handled in a future PR for Olivia, let's add the python interpreter statement to the top of all of the python scripts in the hurricane component. Like this:
`#!/usr/bin/env python3`
This is a requirement in NCO code implementation standards. While TC Verification will not be run in ops, it is good practice for the code to adhere to implementation standards.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Code changes to run w/ the latest python and met look correct.

A future PR can address adding the python ve interpreter statement to the top of all python scripts.

**Comment by ShelleyMelchior-NOAA** [comment]
@JiayiPeng-NOAA  -- please update your PR feature branch (TC4EVS2VE) to include the recently updated auth EVS develop from the PR  merge this morning. Once the sync is completed I will merge this PR.

**Comment by JiayiPeng-NOAA** [comment]
Hi Shelley,
I just updated this branch:
https://github.com/JiayiPeng-NOAA/EVS/tree/TC4EVS2VE
Please go ahead to merge this PR.
Thanks,
Jiayi

**Pull request merged**
