### PR TITLE
Updating machine.conf to fix the bin dir and verbosities

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

Update the machine conf to make changes to 4 lines of code to fix the bin directory and several verbosity lines.  The code was tested when the definitions of these former variables that had been expressed in the code were commented out.  

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Test one particular area of the code to see that this works.  I had used the analyses component.  Removed lines from both the driver file for urma and also in the parm/evs_config/analyses/config.evs.urma.prod file (not included in this PR).  Run script 

`qsub -v cyc=00 jevs_urma_stats.sh`

and check for errors.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

Yes

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Great I will test this with global_det_wave processing. @PerryShafran-NOAA and @malloryprow , I will ping you when there are results to view.

**Comment by ShelleyMelchior-NOAA** [comment]
@PerryShafran-NOAA , @malloryprow 

I elected to test this PR by running global_det_wave prep, stats, and plots. I modified the 3 driver scripts to comment out the following:
`#export metplus_verbosity="INFO"`
`#export met_verbosity="2"`
`#export log_met_output_to_metplus="yes"`
`#export MET_bin_exec=bin`

COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/global_det` (20230629)
log files: 
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_g2o_prep.o66731671`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_g2o_stats.o66742172`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_g2o_plots.o66746942`

I did not point to any archives, just used my $USER prep and stats, so I am sure he plots are incomplete. But that should not matter for the sake of this test.

**Comment by malloryprow** [comment]
I looked at the stats (I think that is what mostly matters for the changes), and looked at a METplus log file /lfs/h2/emc/stmp/shelley.melchior/evs_output/jevs_global_det_wave_g2o_stats.66742172.cbqs01/logs_00_fhr8/metplus_00_fhr8.log.

Looks like grid_stat ran. [Good for the MET_BIN_DIR change]

I see METplus DEBUG statements [Good for the LOG_LEVEL change]

I noticed that there are level 4 MET logging statements in the log file despite LOG_MET_VERBOSITY = 2. This is because in parm/metplus_config/global_det/wave_grid2obs/stats/PointStat_fcstGFS_obsGDAS_climoERA5_Wave_Multifield.conf LOG_POINT_STAT_VERBOSITY = 4. When LOG_[METplus wrapper]_VERBOSITY is set it trumps what LOG_MET_VERBOSITY  is.

**Comment by PerryShafran-NOAA** [comment]
Shelley - in prep, you have global_det linked to Mallory's directory, so nothing can write there.  And you also exceeded the walltime.  HOWEVER, in looking at the file, METplus did run, which is good.  But there was an error in the file /lfs/h2/emc/stmp/shelley.melchior/evs_output/jevs_global_det_wave_g2o_prep.66731671.cbqs01/errfile.57352 - likely having to the fact that it was trying to run to the global_det directory which is linked to Mallory's.  

Looks like Mallory also checked the stat file.  I didn't realize that there was another statement elsewhere of LOG_POINT_STAT_VERBOSITY.  Thanks to Mallory for noting that.  I also see INFO statements, but I think that DEBUG includes INFO - is that right @malloryprow ?

I don't think plots has any METplus in it so that wouldn't matter there.  

Let's give prep another run, but be sure to write to your own directory, and then try stats again by removing the statement in the conf file that Mallory notes.

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Correct, DEBUG includes INFO (and WARNING and ERROR)!

This also brings up the question if we want developers to remove any other instances LOG_MET_VERBOSITY, LOG_[METplus wrapper]_VERBOSITY, and LOG_LEVEL from the individual conf files. Not sure if it matters or not but thought I'd bring it up.

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks for the review! Darnit -- that link to Mallory's global_det bites me again! I will resolve that problem and re-run prep.

**Comment by PerryShafran-NOAA** [comment]
Don't feel bad - I've been bitten by that too!

Perry

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I think that the goal is to standardize that throughout all of EVS.  Therefore we probably do want people to remove that from their configuration files. 

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
global_det_wave prep processing was re-run.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/global_det` (20230629)
log file:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_det_wave_g2o_prep.o66751142`

**Comment by PerryShafran-NOAA** [comment]
Hi, Shelley,

I see prep, stats, and plots data - which means that the machine.conf file is correctly done (especially the bin setting - had that not been done properly no METplus would have run).  

Prep does depend on METplus since PB2NC is used to create the input GDAS data, and that data is there in prep.  Having a stats file means that we are good.  

The other things have to do with verbosity, but in the waves system, the METplus output is in /stmp which means that it's probably not there.  However, I do believe that we are OK to merge since I did see the verbosity in last week's runs and that looked fine.

Perry

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Code looks good and changes are as expected.

**Pull request merged**
