### PR TITLE
First version of WAFS verification to create stat files for icing severity at 0.25 degree (with renamed branch)

### PR DESCRIPTION
**Pull request by YaliMao-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR description above.
- [x] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [x]  Instructions provided on how to run
- [x]  Developer's name is replaced by ${user} where necessary throughout the code
- [x]  Check that the ecf file has all the proper definitions of variables
- [x]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [x]  Check to see that the output directory structure is followed
- [x]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by YaliMao-NOAA** [comment]
Please refer the close pull request #23  which was closed automatically after the branch name was changed.

**Comment by YaliMao-NOAA** [comment]
Instructions:

1. git clone -b feature/global_det_aviation git@github.com:YaliMao-NOAA/EVS.git
2. cd EVS
3. Edit PBS error output filename, change HOMEevs to the EVS folder, and submit a job: qsub ecf/global_det/stats/jevs_global_det_aviation_stats.ecf
4. Small stat files were generated: /lfs/h2/emc/ptmp/$USER/evs/com/stats/global_det/aviation.$PDY
5. Final stat files were generated: /lfs/h2/emc/ptmp/$USER/evs/com/stats/global_det/wafs.$PDY

**Comment by PerryShafran-NOAA** [comment]
Hi, Yali,

I am working on your PR now.  I will let you know soon.

Thanks!

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Yali,

One item is that your output directory structure is missing one item.  The directory structure you have is:

/lfs/h2/emc/ptmp/perry.shafran/evs/com/stats/global_det

It should be:

/lfs/h2/emc/ptmp/perry.shafran/com/evs/v1.0/stats/global_det

Please be sure you make this correction.
 
Otherwise, I'd like you to look at the stat files in the following directories and let me know if the data is what you expect: 

/lfs/h2/emc/ptmp/perry.shafran/evs/com/stats/global_det/aviation.20221026/wafs/grid2grid
/lfs/h2/emc/ptmp/perry.shafran/evs/com/stats/global_det/wafs.20221026

Everything else in your ecf and jobs files looks good, but let me peruse them more closely before I give the official stamp of approval.

Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA 
I made the modifications as you suggested, changing the COMOUT to /lfs/h2/emc/ptmp/$USER/com/evs/v1.0/stats/global_det

Meanwhile this branch is updated with plotting ROC and Frequency BIAS of icing severity

May you please delete two files in your develop branch?
1. scripts/global_det/stats/exevs_global_det_atmos_aviation_stats.sh, both atmos and aviation are RUN, under global_det. I am using scripts/global_det/stats/exevs_global_det_aviation_stats.sh instead
2. ush/global_det/evs_global_det_aviation.sh. It doesn't specify stats or plot, so I am not going to use this file name.
Thank you!

**Comment by PerryShafran-NOAA** [comment]
Hi, Yali,

Please be sure you read Alicia's email and make the filename changes that are requested.  They will be included in this pull request review.

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Yali,

If you remove those files from your fork's repository, then when I submit your code, that should delete the two files in the develop branch.  You can remove the files, then push to the repository.  Those changes will then be put into the develop branch.

Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
I removed the two files in this PR. The scripts were modified according to the new file name standards.

- For aviation, there will be two stat files:
com/evs/v1.0/stats/global_det/wafs.20221031/evs.stats.wafs.aviation.grid2grid.v20221031.stat
com/evs/v1.0/stats/global_det/gfs.20221031/evs.stats.gfs.aviation.grid2grid.v20221031.stat (not done yet, **the folder name will be shared with Mallory's code**) @AliciaBentley-NOAA @malloryprow 

- There will be one plot file for all aviation:
com/evs/v1.0/plots/global_det/aviation.20221101/evs.plots.global_det.aviation.grid2grid.last90days.v20221101.tar

**Comment by PerryShafran-NOAA** [comment]
OK  - I'll bring in your changes and test them today.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Yali,

I noticed that there were errors in your code, mainly due to the fact that there were no observation files found.  I would like you to change your obs directory from v16.2 to v16.3, as NCO recently implemented v16.3  I would recommend changing to GFS v16.3 for your verification (both model and obs) and test that for me.  

I can make those changes and run again, but you should make those changes in your own script and test with v16.3 and see that it works fine.

Thanks!

Perry

**Comment by AliciaBentley-NOAA** [comment]
Hi Perry,

NCO will upgrade the GFS to v16.3 at 12Z on 11/29/22 according to the SCN
<https://www.weather.gov/media/notification/pdf2/scn22-104_gfs.v16.3.0_aaa.pdf>.
The outage on Tuesday–Wednesday was a parallel production test of the new
version on Cactus. I wrote this in Slack, so Yali may not have seen it, but
the copying of ops files from Dogwood onto Cactus after the parallel
production test has been very slow. Files are still missing today. This
could account for the errors that you're running into! You can either wait
until everything catches back up or try an earlier VDATE! I'm not sure
which would be better. Thanks!
___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by YaliMao-NOAA** [comment]
Hi Perry,
I updated gfs_ver to 16.3 in versions/run.ver, also made a link a file only if it exists. From my observation, GFS v16.3 may not fully be mirrored from Dogwood and Cactus. The stat files will be generated with errors because of some missing data.

**Comment by PerryShafran-NOAA** [comment]
Hi, Yali,

Apparently, they have not finished backfilling data from the para prod test, so it's possible the 16.2 version may reappear, and 16.3 isn't supposed to be operational until the end of the month.  It's good to be tested for either case.  I'll let you know what happens.

Perry

**Comment by YaliMao-NOAA** [comment]
Hi Perry,
Thank you for the confirmation.
Yes, from my test results, my fork works for both 16.2 and 16.3, though some data is missing and generates errors. METplus continues to work with the missing data errors.

**Comment by PerryShafran-NOAA** [comment]
Hi, Yali,

Per Alicia's suggestion, I went back in time to choose a VDATE.  Please take a look at the data in the following directories, and let me know if this is what you expect.

/lfs/h2/emc/ptmp/perry.shafran/com/evs/v1.0/stats/global_det/aviation.20221031/wafs/grid2grid
/lfs/h2/emc/ptmp/perry.shafran/com/evs/v1.0/stats/global_det/wafs.20221031

Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
Hi Perry,
The stat files under both folders look good to me.

Sorry I forgot to mention how to run the plotting script.

Go to the same folder and run:
qsub -v "VDATE=20221101" ecf/global_det/plots/jevs_global_det_aviation_plots.ecf

The plot tar ball will be generated as:
com/evs/v1.0/plots/global_det/aviation.20221101/evs.plots.global_det.aviation.grid2grid.last90days.v20221101.tar

**Comment by PerryShafran-NOAA** [comment]
Do you want me to submit the stats portion of the PR, and do a different PR for the plots?  That's basically the way I'm doing it with everyone else.

Perry

**Comment by YaliMao-NOAA** [comment]
Hi Perry,
It is ok to combine the stat and plotting scripts together. Thank you!
Yali

**Comment by PerryShafran-NOAA** [comment]
OK, I will work on the plots section.

Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
@AliciaBentley-NOAA Icing severity plots of ROC and FBIAS
image
image

**Comment by AliciaBentley-NOAA** [comment]
Thanks for sending these plots to us, @YaliMao-NOAA. It appears that you are
plotting Frequency Bias (FBias) in your second plot, but the EVS Stats and
Graphics Overview spreadsheets both ask for regular bias (Bias). I checked
the original EVS Planning Document, and it also says Bias. This brings up a
few questions:

1) Does the WAFS community require a Bias or an FBias calculation?
2) Do you plot Bias or FBias on your *current* WAFS verification webpage?
3) Are you calculating Bias or FBias in your EVS stats scripts?

If you are calculating FBias and a Bias calculation isn't required by the
WAFS community, you can leave things as they are and I will update
the spreadsheets to say FBias. If you are calculating Bias in your EVS
stats scripts and accidentally plotting FBias, then the plot could be
changed to say "Bias" and the dotted line could be moved to zero. If you're
calculating FBias and Bias is what is needed for WAFS, you will need to
update your stats code to calculate Bias and the plotting code to plot Bias
as well.
___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by YaliMao-NOAA** [comment]
@AliciaBentley-NOAA To my understanding, when bias applies to contingency table, it is Frequency Bias, while the regular bias applies to continuous values. Sorry I didn't make it clear that WAFS has always been doing Frequency Bias. Here is the definition: https://resources.eumetrain.org/data/4/451/english/msg/ver_categ_forec/uos2/uos2_ko1.htm

The reason to do Frequency Bias instead of regular bias, it is because both the bias and ROC are both derived from 2x2 contingency table.

From METplus web page, you can search fbias and you can see the statistics type is categorical, not continuous
https://metplus.readthedocs.io/en/latest/Users_Guide/statistics_list.html
I didn't even write the formula to calculate fbias, the python package that Marcel gave to me has already have the formula ready and I have checked it is what I need.

From the standalone WAFS verification webpage https://www.emc.ncep.noaa.gov/gmb/icao/, if you select 'Icing Potential: BIAS" from "Parameter", you will see a similar plotting:
image

**Comment by PerryShafran-NOAA** [comment]
Hi, Yali,

A few items to correct with the plots:

1)  I don't know what p595.2 represents in your plot filenames, but I've been told that the period here will cause some trouble.  You should change that to p595p2.  If you could define this section, that would help.

2)  Also - the forecast hours such as f18 should always be three-digit, e.g. f018 instead of f18.  Can you correct that?

3)  Region names.  Can you list me out all the region names?  You need to be sure that the region names conform to what is in the graphics output sheet:  https://docs.google.com/document/d/1ZVfHzhzLnyDpqVoE0hB4mAluUDZ87W5hIqsw03lTLXY/edit.  Scroll down to the REGION section for that list of regions.  I believe these changes need to be made:

nhem instead of nhm
shem instead of shm
tropics instead of trp
npo instead of npcf

I don't even know what ar2 is.  

aunz and asia are OK, those are on the list of regions.  

Please make the above corrections.

I'm assuming that "icesev" is OK for the parameter.  Is that the name of the parameter in METplus?  

Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
Hi Perry,
Thank you for the feedbacks!
1. How about naming the plot files with 'p595' instead of 'p595.2' or 'p595p2'? Though the file name is with p595, but the plotting itself will display as 595.2 hPa.
2. WAFS forecast hours have not extended to three digits yet, both UK and US WAFC centers are using two digit forecast hours. Must EVS use 3 digits? If so, the rule applies to plots only or both stats and plots?
3. I will update the subregions. AR2 is North Atlantic - Area 2, which is WAFS specific region. Should you or I update the document?
4. ICESEV is not supported by METplus yet, but it's listed on grib2 so I defined it on my own in METplus. https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-0-19.shtml

**Comment by PerryShafran-NOAA** [comment]
1) I'm OK with that, but check with @AliciaBentley-NOAA to find out if that's OK with EVS.  If the plotting is 595.2 hPa, Alicia may want that to be indicated precisely in the filename.
2) Same here. I think that this needs to be a 3-digit forecast hour.  I'm not sure that would apply to stats - your final stats file may not have forecast hours.  
3)  The AR2 is also listed in the natl-r2, and I think that should be used.  
4)  That one we can leave as it is.  I think "icingseverity" would probably be too long a name so I think that "icesev" is probably OK, if that's the variable name.  

Perry

**Comment by YaliMao-NOAA** [comment]
@AliciaBentley-NOAA
May you please confirm the answers of the 3 questions that Perry and I are discussing?
Also as to question 3, is it ok that the image file is named with a subregion with an underscore? For example *g045_natl_r2.png instead of *g045_ar2.png? Then the file name will be with two underscores to define a subregion?

**Comment by AliciaBentley-NOAA** [comment]
1. I think that using p595 will work for our purposes. The only reason it
wouldn't is if you plot both 595.2 hPa and another 595 level like 595.9
hPa. I don't think you do, so p595 should be clear enough. The title that
you write in your final image can say 595.2 hPa in it to be explicit.
2. Based on the EVS image naming convention document
<https://docs.google.com/document/d/1ZVfHzhzLnyDpqVoE0hB4mAluUDZ87W5hIqsw03lTLXY/edit?usp=sharing>,
all components of EVS will be moving to an FXXX (three digit) forecast hour
for consistency. I don't think that stats file names will have FXXX in them
(see the EVS output directory structure document
<https://docs.google.com/document/d/1HOJ5hTCMz-RipkGLk8zd2dov3V5IbhtgGJocqbwGQX8/edit>),
but the image names definitely can and should use FXXX.
3. Yes, please call it *natl_ar2* as it is named in the EVS image naming
convention document.
4. When the grid number and the region are included, it is ok to have three
underscores. This is shown in the third example in the EVS naming document:
evs.cam.ets.apcp_a24.last31days.threshmean_f048.*g212_buk_conus*.png

These are great questions! Please let me know if you have any more!
___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by YaliMao-NOAA** [comment]
@AliciaBentley-NOAA Thank you for the advice.
1. There are no other 595.x hPa levels for icing severity so p595 will not cause confusion.
2. I will correct the image file name with fxxx.
3. Thank you for the confirmation. I will use natl_ar2.

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA Hi Perry,
I modified the code to fix the 3 issues that you mentioned earlier. Please let me know if there are any other issues.
Thank you!
Yali

**Comment by PerryShafran-NOAA** [comment]
Hi, @YaliMao-NOAA ,

I was able to finally work on this, and I noticed an error near the end of the output just before the tar command (starting line 4972):

```
Traceback (most recent call last):
  File "/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ush/global_det/evs_global_det_aviation_plot_fbias.py", line 1161, in <module>
    main()
  File "/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ush/global_det/evs_global_det_aviation_plot_fbias.py", line 1039, in main
    plot_fbias(
  File "/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ush/global_det/evs_global_det_aviation_plot_fbias.py", line 617, in plot_fbias
    y_val for y_val in np.arange(yticks_min, yticks_max+incr, incr)
ValueError: arange: cannot compute length
```

Also there were several cases where I saw the following comment:

`Quitting due to missing data.  Check the log file for details.`

The output file is here:  /lfs/h2/emc/ptmp/perry.shafran/evs_aviation_plots.log

The plots are here:   /lfs/h2/emc/ptmp/perry.shafran/evs/working/plots.59636/plot

You did have an exit code of 0 despite the error.  Can we look into these items?

Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA Can you allow me to access your folder: /lfs/h2/emc/ptmp/perry.shafran/evs? Thank you!

**Comment by PerryShafran-NOAA** [comment]
I think you should have access now.  Let me know if you do not.

**Comment by YaliMao-NOAA** [comment]
/lfs/h2/emc/ptmp/perry.shafran/evs can be accessed now, but not any of its subfolders and subfolders of subfolders. I am running the script on the same VDATE as yours. Let's see what will happen

**Comment by PerryShafran-NOAA** [comment]
I did a chmod -R 744 on the evs directory.  Let's see if it can be accessed now.

Perry

**Comment by YaliMao-NOAA** [comment]
I got the same error message as yours. After I compared the branch for the PR to the develop branch that I am working on, I realized I did have a fix for it. I am adding that fix to this PR branch and having another test run. I will let you know the result soon.

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA I pushed the bug fix to the PR branch. May you please try again?

**Comment by PerryShafran-NOAA** [comment]
Thank you, will do!

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Yali,

Looks like the fbias error has been solved.

I'm still seeing this in places:

`Quitting due to missing data.  Check the log file for details.`

Is this to be expected, just a message to note that there is data missing and this is what you put in in case of missing data?  If you tell me that this is OK and normal, we can approve the PR.

Thanks!

Perry

**Comment by YaliMao-NOAA** [comment]
Hi Perry,
Yes, it is normal of missing data in short period of time when there is no icing on some pressure level in some special subregion. Then there will be no plotting for this case.
Thank you.
Yali

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by PerryShafran-NOAA** [comment]
Thank you!  I am approving and merging your PR.

Great work!

**Comment by YaliMao-NOAA** [comment]
Great! Thank you very much, Perry!

**Pull request merged**
