### PR TITLE
Feature/run.ver pare down

### PR DESCRIPTION
**Pull request by ShelleyMelchior-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

run.ver was adjusted to remove unneeded variables and to reduce COMPATH to just the parallel path for NAEFSv7.
I tested that all three steps checked out in spot checks.
I tested prep in global_ens for `dev/drivers/scripts/global_ens/prep/jevs_global_ens_naefs_atmos_prep.sh`.
I tested stats in analyses for `dev/drivers/scripts/analyses/stats/jevs_analyses_urma_grid2obs_stats.sh`.
I tested plots in analyses for `dev/drivers/scripts/analyses/plots/jevs_analyses_grid2obs_plots.sh`.

I also modified the 3 analyses stats drivers to correct the COMOUT definition to not use COMIN. This is an EE2 bug that NCO would have found.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Please pick 3 random (and different from my tests) prep, stats, and plots processes to make sure the removal of the variables at the bottom of run.ver does not impact successful runs. Comparing against emc.vpppg results for the same cyc and/or VDATE is sufficient to assess success.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **ASAP**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
The subseasonal gefs prep job is running and producing prep files that look good; reasonable number and size.  It was a bigger than I thought component - let me also run another job that's smaller to check.

**Comment by PerryShafran-NOAA** [comment]
The subseasonal obs prep job is fast.  It ran quickly and provided all the prep data needed.  

I'm moving onto a stats job.

**Comment by PerryShafran-NOAA** [comment]
For stats; I am running a global_det job (ukmet grid2grid) that is fast.

**Comment by ShelleyMelchior-NOAA** [comment]
Ok, plots directions coming shortly!

**Comment by ShelleyMelchior-NOAA** [comment]
For the plots test, please run `dev/drivers/scripts/mesoscale/plots/jevs_mesoscale_sref_precip_*`. There are 2 drivers for sref precip plots.

The bug fix change has been pushed to `feature/run.ver-pare-down`.  The old lines are still in the code, just commented out. Once @BinbinZhou-NOAA can confirm that changes are correct, I can remove those old commented lines and then you can merge the PR.

**Comment by PerryShafran-NOAA** [comment]
Running the sref precip plots jobs.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA @malloryprow I got a TON of missing global_det UKMET file emails just now. Is this expected? Were things set up correctly for the UKMET stats test?

Screen Shot 2023-09-20 at 10 02 52 AM

**Comment by PerryShafran-NOAA** [comment]
Hmm, I'm not sure what went wrong here.  I could just have accidentally have pointed to the wrong prep directory.

**Comment by malloryprow** [comment]
> Hmm, I'm not sure what went wrong here. I could just have accidentally have pointed to the wrong prep directory.

Yes it was looking in your directory, /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det/

**Comment by PerryShafran-NOAA** [comment]
Yes, I found out what happened; it's pointing to a non-existent directory.  Fixing.  

Sorry to alarm people!!!

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA - the plots jobs have finished.  Can you specifically tell me if there's anything special I need to look for here?  

The tar files do look like what is expected for sref precip tar files, so the run.ver part is validated for plots.

**Comment by ShelleyMelchior-NOAA** [comment]
Yes,  we need to confirm what @BinbinZhou-NOAA indicated was the problem is corrected. This is the problem he described. 

> I just found a bug in the [sref precip plot script](https://github.com/NOAA-EMC/EVS/blob/develop/scripts/mesoscale/plots/exevs_mesoscale_atmos_sref_precip_plots.sh) that causes SREF's curve to be missing
(only GEFS curve) in some forecast hour's plots). 
The reason is SREF and GEFS are initiated at different times (3 fhr shift) but validated 
at the same time.

**Comment by PerryShafran-NOAA** [comment]
Darn - the ukmet grid2grid job actually failed, and it looks like some kind of library error?

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr251test/EVS/dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_ukmet_grid2grid_stats_00.o82390209

```
nid001149.cactus.wcoss2.ncep.noaa.gov: rank 0 exited with code 1
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source             
cfp                000000000041593B  for__signal_handl     Unknown  Unknown
libpthread-2.31.s  00001479E688E8C0  Unknown               Unknown  Unknown
libifcoremt.so.5   00001479E2B27F60  _fini                 Unknown  Unknown
```

Since this is a run.ver test, this could be significant.  @malloryprow any thoughts?

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA can you get a specific plot from @BinbinZhou-NOAA , then take a quick look to see if that plot has any issue?  Again, I'm having trouble with XLaunch, so if you could do that, that would be great.  

Plot tar files are here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/mesoscale/atmos.20230918

**Comment by malloryprow** [comment]
I see CFP RANK   2    CFP TASK NUMBER: 0003 FAILED.     USER COMMAND: /lfs/h2/emc/stmp/perry.shafran/evs_test/dev/tmp/jevs_global_det_atmos_ukmet_grid2grid_stats_00.82390209.cbqs01/grid2grid_stats/METplus_job_scripts/assemble_data/job3

I can try testing and see on my own and see what is happening. I'll point to your directory to recreate where it looked for the data. I'll comment out where it sends that emails for my testing.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Before you do that, I noticed that my job ended before today's global_det prep job completed.  Let me re-run again and see if that had anything to do with the issue.

**Comment by PerryShafran-NOAA** [comment]
OK, I think that was indeed the problem!  The stats job is running as expected now.

**Comment by PerryShafran-NOAA** [comment]
Unfortunately, while the new run is better, I'm still seeing some FAIL statements. 

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr251test/EVS/dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_ukmet_grid2grid_stats_00.o82390857

```
1 + cp -v /lfs/h2/emc/stmp/perry.shafran/evs_test/dev/tmp/jevs_global_det_atmos_ukmet_grid2grid_stats_00.82390857.cbqs01/gr
id2grid_stats/METplus_output/atmos.20230919/ukmet/grid2grid/daily_avg_pres_levs_DailyAvg_GeoHeightAnom_init2023091300_valid
2023091812to2023091900.nc /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/atmos.20230919/ukmet/grid2grid/
daily_avg_pres_levs_DailyAvg_GeoHeightAnom_init2023091300_valid2023091812to2023091900.nc
cp: cannot stat '/lfs/h2/emc/stmp/perry.shafran/evs_test/dev/tmp/jevs_global_det_atmos_ukmet_grid2grid_stats_00.82390857.cb
qs01/grid2grid_stats/METplus_output/atmos.20230919/ukmet/grid2grid/daily_avg_pres_levs_DailyAvg_GeoHeightAnom_init202309130
0_valid2023091812to2023091900.nc': No such file or directory
CFP RANK   0    CFP TASK NUMBER: 0001 FAILED.     USER COMMAND: /lfs/h2/emc/stmp/perry.shafran/evs_test/dev/tmp/jevs_global_det_atmos_ukmet_grid2grid_stats_00.82390857.cbqs01/grid2grid_stats/METplus_job_scripts/assemble_data/job1
```

**Comment by PerryShafran-NOAA** [comment]
OK - the global_det prep job in emc.vpppg is still running, so it's still seeing files as missing.  Thus, I'm going to run this stats job on an earlier VDATE.  Stay tuned.

**Comment by PerryShafran-NOAA** [comment]
OK, there are some issues in global_det that will be looked into, but they aren't related to the run.ver fix, so I'll look at another stats job after my 11 am meeting.

**Comment by PerryShafran-NOAA** [comment]
OK, Binbin reports that the sref precip plots look good.  

Now I still need to do a stats test, so I'm just going to do aqm as I know that's fast.

Perry

**Comment by PerryShafran-NOAA** [comment]
Just validated that the stats step works with aqm.

I think that we are good to merge this one.  @ShelleyMelchior-NOAA agreed?

**Comment by ShelleyMelchior-NOAA** [comment]
✔️ Yes! Let's get this one in.

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
