### PR TITLE
WARNING added in precip jobs

### PR DESCRIPTION
**Pull request by RoshanShrestha-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/warning_fix`.

**Comment by ShelleyMelchior-NOAA** [comment]
The data denial run for rap precip stats looks good! No FATALs and now I see WARNINGs. See what you think, @RoshanShrestha-NOAA  and @PerryShafran-NOAA .

`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_precip_stats_00.o132635504`

**Comment by RoshanShrestha-NOAA** [comment]
I think, the issue is fixed now.

> The data denial run for rap precip stats looks good! No FATALs and now I see WARNINGs. See what you think, @RoshanShrestha-NOAA and @PerryShafran-NOAA .
> 
> `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_precip_stats_00.o132635504`

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA @RoshanShrestha-NOAA Are there any other scripts where the phrase "NO SIZE OR MISSING" needs a WARNING in front of it?  Can we be make sure of that?

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks Perry. It looks like `ush/mesoscale/mesoscale_snowfall_stats_create_job_scripts.py` needs a few. @RoshanShrestha-NOAA , please make that change and then I can test snowfall stats.

**Comment by RoshanShrestha-NOAA** [comment]
@ShelleyMelchior-NOAA The fixes are included for the snowfall stats.

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks @RoshanShrestha-NOAA . I ran the rap snowfall stats job. I see no FATALs and I see WARNINGs.
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_snowfall_stats_00.o132639417`

**Comment by RoshanShrestha-NOAA** [comment]
@ShelleyMelchior-NOAA. It look good. Thanks for catching the issue in the snowfall stats.

> Thanks @RoshanShrestha-NOAA . I ran the rap snowfall stats job. I see no FATALs and I see WARNINGs. `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_rap_snowfall_stats_00.o132639417`

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Data denial tests yield expected results. This PR is approved for merge.

**Pull request merged**
