### PR TITLE
Feature/cam cycle

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [X] Describe testing already performed for this Pull Request:</br>
_All workflows have been running in the cron as described below without error for at least a week.  The mail command has also been tested against workflows that have errors to ensure that the errors triggered the mail command and that the command ran correctly._

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Test to see that CAM/grid2obs and CAM/precip jobs produce similar stat files if jobs are run in cycles compared to how they are currently run in the parallel:
1. Run the CAM/grid2obs and CAM/precip prep workflows as they are normally run in the EVS parallel. 

2. Then run CAM/grid2obs and CAM/precip stats workflows at the following cycles:

>     grid2obs (5 models): 2, 3, 6, 9, 12, 15, 18, 21
>     precip (5 modles): 19, 20, 21, 22 

In summary, here is how the workflows can be set up in the cron:

```
30 0,6,12,18 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswarw_precip_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_hireswarw_precip_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswarw_precip_prep.out 2>&1
30 0,6,12,18 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswarwmem2_precip_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_hireswarwmem2_precip_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswarwmem2_precip_prep.out 2>&1
30 0,6,12,18 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswfv3_precip_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_hireswfv3_precip_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswfv3_precip_prep.out 2>&1
30 0,6,12,18 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hrrr_precip_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_hrrr_precip_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hrrr_precip_prep.out 2>&1
30 0,6,12,18 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_namnest_precip_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_namnest_precip_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_namnest_precip_prep.out 2>&1
0 19-22 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswarw_precip_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_hireswarw_precip_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswarw_precip_stats.out 2>&1
0 19-22 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswarwmem2_precip_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_hireswarwmem2_precip_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswarwmem2_precip_stats.out 2>&1
0 19-22 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswfv3_precip_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_hireswfv3_precip_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswfv3_precip_stats.out 2>&1
0 19-22 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hrrr_precip_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_hrrr_precip_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hrrr_precip_stats.out 2>&1
0 19-22 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_namnest_precip_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_namnest_precip_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_namnest_precip_stats.out 2>&1
0 0 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswarw_grid2obs_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_hireswarw_grid2obs_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswarw_grid2obs_prep.out 2>&1
0 0 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswarwmem2_grid2obs_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_hireswarwmem2_grid2obs_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswarwmem2_grid2obs_prep.out 2>&1
0 0 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswfv3_grid2obs_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_hireswfv3_grid2obs_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswfv3_grid2obs_prep.out 2>&1
0 0 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hrrr_grid2obs_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_hrrr_grid2obs_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hrrr_grid2obs_prep.out 2>&1
0 0 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_namnest_grid2obs_prep.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/prep/jevs_namnest_grid2obs_prep.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_namnest_grid2obs_prep.out 2>&1
30 2,3,6,9,12,15,18,21 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswarw_grid2obs_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_hireswarw_grid2obs_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswarw_grid2obs_stats.out 2>&1
30 2,3,6,9,12,15,18,21 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswarwmem2_grid2obs_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_hireswarwmem2_grid2obs_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswarwmem2_grid2obs_stats.out 2>&1
30 2,3,6,9,12,15,18,21 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hireswfv3_grid2obs_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_hireswfv3_grid2obs_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hireswfv3_grid2obs_stats.out 2>&1
30 2,3,6,9,12,15,18,21 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_hrrr_grid2obs_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_hrrr_grid2obs_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_hrrr_grid2obs_stats.out 2>&1
30 2,3,6,9,12,15,18,21 * * * qsub -o /lfs/h2/emc/stmp/{USER}/jevs_namnest_grid2obs_stats.out /lfs/h2/emc/vpppg/noscrub/{USER}/EVS/ecf/cam/stats/jevs_namnest_grid2obs_stats.ecf >> /lfs/h2/emc/stmp/{USER}/cron.out/test_jevs_namnest_grid2obs_stats.out 2>&1
```

Just be sure to replace all instances of {USER} with your username in the above command (there are 60 instances). The qsub commands can be spot checked instead if that is easier.

Lastly, COMOUT directories are defined in the twenty ecf scripts and may be changed during testing to change the location of the output stats files. Currently, COMOUT is set as it is in the parallel repository.
- [X] Has the code been checked to ensure that no errors occur during the execution? **[Yes]**

- [X] Do these updates/additions include sufficient testing updates? **[Yes]**

- [X] Please complete this pull request review by **[20230504]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned Marcel's fork and will begin working on this PR.

**Comment by ShelleyMelchior-NOAA** [comment]
The cron entries have been set up and are running for the prep and stats for precip.
Please see the relevant output for prep (at this point in the day stats has not yet run).
log files: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/CAM_cycle`
`COMOUT=/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/cam`

**Comment by ShelleyMelchior-NOAA** [comment]
I will be setting up the grid2obs cron entries next.

**Comment by ShelleyMelchior-NOAA** [comment]
All cron entries are in place.
I ran the grid2obs prep interactively in order to have data available for the stats when the cron entries kick off.
The first stats will be at 18:30 for grid2obs. The next stats will be run at 19:00 for precip.

**Comment by ShelleyMelchior-NOAA** [comment]
All cron entries have been running through the weekend. Please review the output data
`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/cam`
and logfiles
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/CAM_cycle`

**Comment by MarcelCaron-NOAA** [comment]
Hi Shelley, the jobs ran well and successfully produced final stat files that match those I've been running in parallel.  I only noticed that I missed a closing "fi" and misspelled the "err_chk" command in the J-job, so an error triggers at the tail end of the jobs.  That error is fixed in the most recent commit, and otherwise I have no concerns about this feature branch.

**Comment by ShelleyMelchior-NOAA** [comment]
Excellent! I just pulled the update into my clone of your fork and feature/CAM_cycle.
Follow on cycle runs should clear up the minor errors you were seeing.

**Comment by MarcelCaron-NOAA** [comment]
Great, thanks!  I checked the output files of the stats jobs for the 1530Z cycle, which just finished, and the errors I mentioned were resolved by the fix in each of them.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Cron entries were set up and permitted to run over the weekend. The developer reviewed the output log files and data files and confirmed results  match what is running in their own parallel cron.

**Pull request merged**
