### PR TITLE
feature/global_det_beta5

### PR DESCRIPTION
**Pull request by malloryprow**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

This supports the beta5 vector line type changes in global_det.

## Developer Questions and Checklist
* Is this a high priority PR? If so, why and is there a date it needs to be merged by?
> Would be nice to get it in sooner rather than later
* Do you have any planned upcoming annual leave/PTO?
> No
* Are there any changes needed for when the jobs are supposed to run?
> No

- [x] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [x] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [x] References the feature branch for `HOMEevs` are removed from the code.
- [x] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [x] Jobs over 15 minutes in runtime have restart capability.
- [x] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [x] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [x] Code is using METplus wrappers structure and not calling MET executables directly.
- [ ] Log is free of any ERRORs or WARNINGs.

###  **Set-up**
1. Clone my fork and checkout branch feature/global_det_beta5
2. `ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix`

### :heavy_check_mark:  **global_det stats**
 3. `cd dev/drivers/scripts/stats/global_det`
 4. Run the following: `jevs_global_det_gfs_atmos_wmo_monthly_stats.sh`
> - Set `HOMEevs` to the location of the clone.
> - Set `COMIN` to `/lfs/h2/emc/vpppg/noscrub/emc.vpppg/${NET}_beta5/$evs_ver_2d`
> - Run with `VDATE=20240930`

### :heavy_check_mark:  **global_det plots**
 3. `cd dev/drivers/scripts/plots/global_det`
 4. Run the following: `jevs_global_det_wave_grid2obs_plots_last31days.sh`, `jevs_global_det_atmos_grid2grid_pres_levs_plots_last31days.sh`,  `jevs_global_det_atmos_grid2obs_pres_levs_plots_last31days.sh`, `jevs_global_det_atmos_grid2obs_sfc_plots_last31days.sh`.
> - Set `HOMEevs` to the location of the clone.
> - Set `COMIN` to `/lfs/h2/emc/vpppg/noscrub/emc.vpppg/${NET}_beta5/$evs_ver_2d`
> - Let me know when you are about to run and we can adjust `VDATE_END` if needed

### CODE REVIEW

**Review by AliciaBentley-NOAA — APPROVED** [review]
@malloryprow I have reviewed the changes made in this PR and think that they are consistent with the changes needed to use the MET-12.0.0 beta5s (with new columns added). I approve this PR to be merged after testing confirms that plots look good. @PerryShafran-NOAA is out for the next two days, so I'm CCing @ShelleyMelchior-NOAA, should she happen to have some time Thursday or Friday to pick up a PR! No pressure, though! :)

**Comment by ShelleyMelchior-NOAA** [comment]
> @malloryprow I have reviewed the changes made in this PR and think that they are consistent with the changes needed to use the MET-12.0.0 beta5s (with new columns added). I approve this PR to be merged after testing confirms that plots look good. @PerryShafran-NOAA is out for the next two days, so I'm CCing @ShelleyMelchior-NOAA, should she happen to have some time Thursday or Friday to pick up a PR! No pressure, though! :)

Am I still allowed? 😆

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I am starting work on this PR, so it is ready to review when you return to work.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I am running both the wmo stats and the plots.  For the plots, I set the VDATE_END to day-2 rather than day-1, which it was set at.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The stats wmo run is complete.

You can find the .o file here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr578test/EVS/dev/drivers/scripts/stats/global_det/jevs_global_det_gfs_atmos_wmo_monthly_stats_00.o157700792
Small stat files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v2.0/stats/global_det/atmos.20240930/gfs/wmo
Final stat files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v2.0/stats/global_det/gfs.20240930

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The plot jobs are complete.

See the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr578test/EVS/dev/drivers/scripts/plots/global_det
Plot tarballs here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v2.0/plots/global_det/atmos.20241007 and wave.20241007

**Comment by malloryprow** [comment]
This one looks good to me!

**Comment by PerryShafran-NOAA** [comment]
Great!  You might need to sync fork so I can merge.

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
