### PR TITLE
feature/naefsv7

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

This PR is submitted without any EE2 edits on purpose. This is to ensure a _clean_ PR for NAEFS v7 with no other complications from outside factors. This plan of action was worked out with @AliciaBentley-NOAA and @ShelleyMelchior-NOAA since EE2 edits can come after 09/15/2023, but the changes for NAEFS v7 cannot. 

- [ ] Describe testing already performed for this Pull Request:</br>

Ran the various prep, stats, and plots jobs.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

These instructions are going to be a little hacky since we are not running all the global_ens prep jobs. I want to keep this in the scope of NAEFS v7. 

Start by running jevs_global_ens_naefs_atmos_prep.sh. Subsequent instructions to follow.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **No*

- [ ] Do these updates/additions include sufficient testing updates? **No**

- [ ] Please complete this pull request review by **09/15/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by malloryprow** [comment]
I will not be able to be online tonight (going to a rescheduled concert from last Friday in Baltimore tonight). I'm only planning on working a half a day tomorrow, but I will keep my laptop nearby tomorrow in order to address this PR.

**Comment by PerryShafran-NOAA** [comment]
Starting the prep step now.

**Comment by malloryprow** [comment]
I was looking in  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens and it is currently linked to /lfs/h2/emc/vpppg/noscrub
/mallory.row/evs/v1.0/prep/global_ens.

Can you do "unlink /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens"?

**Comment by PerryShafran-NOAA** [comment]
I beat you to it; I just noticed that and fixed that.  

Re-run in progress.

**Comment by PerryShafran-NOAA** [comment]
The prep run is complete: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr240test/EVS/dev/drivers/scripts/global_ens/prep/jevs_global_ens_naefs_atmos_prep.o81889909

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230912

**Comment by malloryprow** [comment]
Yes! File counts match mine!

Okay here is where it gets weird and we need to link to the prep files from the global_ens prep job from the parallel...

1. rm -r /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230912/cmce
2. rm -r /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230912/ecme
3. rm -r /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230912/gefs
4. rm -r /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230912/osi_saf
5. ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/global_ens/atmos.20230912/cmce /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230912/cmce
6. ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/global_ens/atmos.20230912/ecme /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230912/ecme
7. ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/global_ens/atmos.20230912/gefs /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230912/gefs
8. ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/global_ens/atmos.20230912/osi_saf /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230912/osi_saf

Once that is done run jevs_global_ens_headline_prep.sh.

**Comment by PerryShafran-NOAA** [comment]
OK - if you're not concerned about the 0-length filenames in the gefs and gefs_bc files that I see, then I'm OK with that.  

Also - in the gefs directory, there are gefs_bc files.  Is that right?  

Perry

**Comment by malloryprow** [comment]
Which files are you talking about?

**Comment by malloryprow** [comment]
After running jevs_global_ens_naefs_atmos_prep.sh, cmce_bc and gefs_bc will only have files.

**Comment by PerryShafran-NOAA** [comment]
I was incorrect about the gefs directory; that is empty.

But the gefs_bc directory has lots of empty files.  Do a listing here:   /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230912/gefs_bc.  There's a significant number of 0 length files:

```
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f000.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f012.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f024.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f036.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f048.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f060.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f072.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f084.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f096.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f108.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f120.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f132.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f144.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f156.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f168.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f180.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f192.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f204.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f216.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f228.grib2
-rw-r--r-- 1 perry.shafran vpppg      0 Sep 14 18:14 gefs_bc.ens30.t12z.grid3.f240.grib2
```

This is only a small snippet of those files.  

Perry

**Comment by malloryprow** [comment]
Oh yes. That is fine; Bo's NAEFS v7 parallel has no 12Z cycles...00Z only.

**Comment by PerryShafran-NOAA** [comment]
OK then - moving on to your next step!

**Comment by malloryprow** [comment]
Files counts for /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/headline.20230912 match mine!

✅ Prep!

Okay time for stats...

1.  ln -sf /lfs/h2/emc/vpppg/noscrub/mallory.row/evs/v1.0/prep/global_ens/atmos.20230911 /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/atmos.20230911
2. ln -sf /lfs/h2/emc/vpppg/noscrub/mallory.row/evs/v1.0/prep/global_ens/headline.20230911 /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_ens/headline.20230911

Then run jevs_global_ens_naefs_atmos_grid2grid_stats.sh, jevs_global_ens_naefs_atmos_grid2obs_stats.sh, jevs_global_ens_naefs_atmos_precip_stats.sh, jevs_global_ens_naefs_headline_grid2grid_stats.sh.

**Comment by malloryprow** [comment]
My day is ending soon, but I can stick around if we want to knock this out today. Let me know!

**Comment by PerryShafran-NOAA** [comment]
If you can stick around, that would be great.  I'm making your PR top priority.

**Comment by malloryprow** [comment]
👍 Sticking around!

**Comment by malloryprow** [comment]
Ah looks like  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens is linked to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/global_ens

**Comment by PerryShafran-NOAA** [comment]
OK, fixed.

**Comment by PerryShafran-NOAA** [comment]
Oh great; they're all stuck in queue now.  Hopefully it won't be too long before they run.

**Comment by malloryprow** [comment]
And they should be pretty quick once they do run since we don't have much prep data!

**Comment by PerryShafran-NOAA** [comment]
OK cool.  Will let you know

**Comment by malloryprow** [comment]
In /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr240test/EVS/dev/drivers/scripts/global_ens/stats/jevs_global_ens_naefs_atmos_grid2obs_stats.o81897283, I'm seeing 

++ /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr240stats/EVS/jobs/global_ens/stats/JEVS_GLOBAL_ENS_STATS
/var/spool/pbs/mom_priv/jobs/81897283.cbqs01.SC: line 50: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr240stats/EVS/jobs/global_ens/stats/JEVS_GLOBAL_ENS_STATS: No such file or directory

**Comment by malloryprow** [comment]
HOMEevs in jevs_global_ens_naefs_atmos_grid2obs_stats.sh should be export HOMEevs=/lfs/h2/emc/vpppg/noscrub/${USER}/pr240test/EVS

**Comment by malloryprow** [comment]
Otherwise the other 3 stat files look good.

**Comment by PerryShafran-NOAA** [comment]
OK, thanks, rerunning that stat file.

**Comment by PerryShafran-NOAA** [comment]
OK, I now have 4 stat files.  Please check.

**Comment by malloryprow** [comment]
✅ Stats!

Okay plots time...

1. ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/global_ens/gefs.20230912 /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens/gefs.20230912
2. ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/global_ens/cmce.20230912 /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_ens/cmce.20230912

Then run jevs_global_ens_atmos_naefs_grid2grid_past31days_plots.sh, jevs_global_ens_atmos_naefs_grid2obs_past31days_plots.sh, jevs_global_ens_atmos_naefs_precip_past31days_plots.sh.

**Comment by malloryprow** [comment]
These should be quick ones too since we only have 1 day of stats files!

**Comment by PerryShafran-NOAA** [comment]
Plot runs underway.

**Comment by PerryShafran-NOAA** [comment]
Wow they are fast.  We already have two plot tar files, and the third one is stuck in queue still.  

/lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/global_ens/atmos.20230912

**Comment by malloryprow** [comment]
✅ plots tar files sizes match mine!!

WOOHOO!

**Comment by PerryShafran-NOAA** [comment]
OK, all plot files are done.

**Comment by PerryShafran-NOAA** [comment]
OK then!  Are we now fully validated?

**Comment by malloryprow** [comment]
Fully validated; merge away!

**Comment by malloryprow** [comment]
Thanks so much Perry!

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by malloryprow** [comment]
I'm not sure what time the NAEFS jobs runs but I would be curious to see what happens when it runs tomorrow. Tomorrow's prep run will be the first with 30 gefs_bc members while the older prep directories will have 20. I'm not sure how that will impact the stats jobs!

**Pull request merged**
