### PR TITLE
Feature/subseasonal mpmd fix for stats

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

> Please include a summary of the changes and the related GitHub issue(s). Please also include relevant motivation and context.
This PR includes output directory changes to address the MPMD bugzilla 1547 (Issue #561) for subseasonal G2G and G2O stats jobs.
## Developer Questions and Checklist
* Is this a high priorty PR? If so, why and is there a date it needs to be merged by?
* Not really, but it would be highly preferred if this PR was tested and completed before the next WCOSS2 outage on 11/19.
* Do you have any planned upcoming annual leave/PTO?
* No
* Are there any changes needed for when the jobs are supposed to run?
* No
  
- [ ] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [ ] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [ ] References the feature branch for `HOMEevs` are removed from the code.
- [ ] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [ ] Jobs over 15 minutes in runtime have restart capability.
- [ ] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [ ] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [ ] Code is using METplus wrappers structure and not calling MET executables directly.
- [ ] Log is free of any ERRORs or WARNINGs.

## Testing Instructions

> Please include testing instructions for the PR assignee. Include all relevant input datasets needed to run the tests.
There is some missing prep data (due to outage) that will need to be filled in the parallel either from my own directories or prod, so please inform developer when you are ready to test. Once prep is set, please run the following jobs to test:
dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_cfs_grid2grid_stats.sh
jevs_subseasonal_cfs_grid2obs_stats.sh
jevs_subseasonal_gefs_grid2grid_stats.sh
jevs_subseasonal_gefs_grid2obs_stats.sh

### CODE REVIEW

**Comment by malloryprow** [comment]
Thanks @ShannonShields-NOAA! I'll get to this when I am done working with operations on changes to a few EVS jobs after the changes to Cactus.

**Comment by ShannonShields-NOAA** [comment]
Sounds good!

**Comment by ShannonShields-NOAA** [comment]
FYI, the following is missing from /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v2.0/prep/subseasonal/:
atmos.20241105: ghrsst_ospo, osi_saf
atmos.20241106: osi_saf
atmos.20241108: all
atmos.20241109: cfs, gefs, prepbufr_nam
atmos.20241112: cfs, gefs (walltime exceeded)
While the jobs (except for G2O with prepbufr_nam) can run based on the 80% existing threshold, a complete test would include all prep data.

**Comment by malloryprow** [comment]
Do you have prep directories I can copy or should I copy from prod?

We need to make a note to look into the wall time exceedances for the recent runs. This is occurring with some jobs on Cactus post upgrades where this wasn't happening before.

**Review by AliciaBentley-NOAA — APPROVED** [review]
I have reviewed the extensive changes made in this PR and I think that they look great. What is done here makes sense to solve the mpmd bugzilla. I approve this PR to be merged after it is tested (which may be delayed by some ops EVS work on Cactus). 

@ShannonShields-NOAA @malloryprow

**Comment by ShannonShields-NOAA** [comment]
You can copy from /lfs/h2/emc/vpppg/noscrub/shannon.shields/EVS_Data/evs/v2.0/prep/subseasonal as I have these filled in after the outage. & agreed about run times...all my prep jobs ran fine this morning (which kick off an hour before the parallel), but the para timed out. :-(

**Comment by malloryprow** [comment]
When you prep job ran did you notice if the runtime was longer than usual/what is in ops?

**Comment by malloryprow** [comment]
I know ops isn't running the same version but here are the runtimes

> `grep "resources_used.walltime" /lfs/h1/ops/prod/output/20241114/evs_subseasonal_*prep.*`
> /lfs/h1/ops/prod/output/20241114/evs_subseasonal_cfs_prep.o205884828:    resources_used.walltime = 00:03:31
> /lfs/h1/ops/prod/output/20241114/evs_subseasonal_gefs_prep.o205884827:    resources_used.walltime = 00:39:11
> /lfs/h1/ops/prod/output/20241114/evs_subseasonal_obs_prep.o205884826:    resources_used.walltime = 00:00:00

**Comment by ShannonShields-NOAA** [comment]
My CFS and GEFS prep jobs ran in the usual wallclock time as defined in ops. For example, my GEFS prep job kicks off at 1300Z and it took its typical 1.5 hours to run (the wallclock is set for 2 hours). CFS job kicked off at 1430Z.

**Comment by ShannonShields-NOAA** [comment]
Looking at the Job summary section under the output log files, GEFS prep says "resources_used.walltime = 02:00:42" and for CFS, "resources_used.walltime = 00:20:07" for the parallel runs today.

**Comment by ShannonShields-NOAA** [comment]
Overall, ignoring the different kick off cronjob times, jobs on Dogwood (prod) seem to run **much** faster compared to Cactus.
We ran into a similar issue when working on the GEFS Precip Grand Challenge where NODD transfers were like 10x faster on Dogwood compared to Cactus; I think @AliciaBentley-NOAA can confirm this too.

**Comment by AliciaBentley-NOAA** [comment]
@ShannonShields-NOAA Correct. Cactus transfers from an external source (like the NODD) run infinitely slower on Cactus than on Dogwood. The EVS job slowness on Cactus is new and we're told is the result of the recent upgrades that were made to Cactus making memory allocation stricter or something. Multiple models, including EVS, are running slower on Cactus now, and @malloryprow  has been troubleshooting these slowness issues with Wei Wei and NCO all day. Sigh.

**Comment by malloryprow** [comment]
I re-ran the prep for parallel for today that was missed from the prod switch. Can you check that it looks okay? I'll start setting up the job to run in the meantime.

**Comment by ShannonShields-NOAA** [comment]
@malloryprow I checked through the parallel prep directories and everything looks good/is filled in through today's prep run (atmos.20241113). The stats jobs should be set to run once you have changed COMIN and linked FIXevs.

**Comment by malloryprow** [comment]
### stats

COMOUT is /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr602/evs/v2.0/stats/subseasonal.

### jevs_subseasonal_cfs_grid2grid_stats.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr602/EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_cfs_grid2grid_stats.o206190686
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_cfs_grid2grid_stats.206190686.dbqs01

### jevs_subseasonal_cfs_grid2obs_stats.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr602/EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_cfs_grid2obs_stats.o206190687
**DATA**: /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_cfs_grid2obs_stats.206190687.dbqs01

### jevs_subseasonal_gefs_grid2grid_stats.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr602/EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.o206190690
**DATA**: /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_gefs_grid2grid_stats.206190690.dbqs01

### jevs_subseasonal_gefs_grid2obs_stats.sh
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr602/EVS/dev/drivers/scripts/stats/subseasonal/jevs_subseasonal_gefs_grid2obs_stats.o206190697
**DATA**: /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_gefs_grid2obs_stats.206190697.dbqs01

**Comment by ShannonShields-NOAA** [comment]
@malloryprow Apologies for the delayed response, but I had to check through many directories to make sure everything matched up. Good news is that everything is correct with the new individual job output (and the associated copying after each job group). There are no ERRORs in the output log files (apparently model data is missing for Day 11 of daily SST, but everything else is fine), and the final stat files are correct.

**Review by malloryprow — APPROVED** [review]
Changes are good and testing successful.

**Comment by malloryprow** [comment]
Yup, I saw that too and didn't see anything in the logs that was concerning. I'll merge.

I'll check off the stats jobs in https://github.com/NOAA-EMC/EVS/issues/561.

P.S. Working through this PR and merging it is the most normal thing I've felt I've got to do in weeks. Lol!

**Comment by ShannonShields-NOAA** [comment]
@malloryprow Yes, it feels good to get this PR done after working on it for what I think was 2.5 weeks due to changing 90% of my scripts, outage, etc. Thank you for your assistance and checking off items in the issue. Hopefully the plot changes won't take as long.

**Pull request merged**
