### PR TITLE
Feature/subseasonal Prep Refinement

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
The GEFS, CFS, and obs prep jobs have been successfully running as cronjobs for a while now.
The mail alert function has been successfully tested for the GEFS and CFS models.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Checkout this feature branch under your own directory.
Under EVS/dev/drivers/scripts/subseasonal/prep, run the following:
jevs_subseasonal_cfs_prep.sh
jevs_subseasonal_obs_prep.sh
Make sure to set HOMEevs to the correct feature branch path. Both driver scripts should run successfully.
Please let me know when you have completed this first test and then we can move on to the mail test.
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>
ASAP! I need to merge this PR before I can submit my modulefiles PR to avoid conflicts.
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @ShannonShields-NOAA ! I don't want to hold up your progress while me and @PerryShafran-NOAA work through the backlog of PRs. You can submit a subsequent PR before this one is merged.  There are a couple of options to do this, but I recommend creating a new feature branch off of `feature/subseasonal_prep_refinement`. That way the new feature branch for modulefiles will have all of the prep refinement changes contained in it w/o conflicts. @malloryprow has offered to help you with this set up so that me and Perry can keep churning through PRs.

**Comment by ShannonShields-NOAA** [comment]
@ShelleyMelchior-NOAA @PerryShafran-NOAA @malloryprow Ah yes, of course, thank you Shelley for that suggestion. I have gone ahead and made a new feature branch for modulefiles from prep_refinement and will work on getting this submitted as a PR.

**Comment by ShelleyMelchior-NOAA** [comment]
This PR (#162 ) remains open for reference. However, it is absorbed by PR #165 . Please do all work from the feature branch that is the foundation for PR #165  (`feature/subseasonal_modulefiles`).

**Comment by PerryShafran-NOAA** [comment]
Closing this PR since the items from PR 165 absorbed the items in this PR.  

Perry

**Pull request closed without merging**
