### PR TITLE
Feature/s2s Update to Fix METplus Looping Errors

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

The subseasonal prep step has been running for several months as a cronjob.
The subseasonal stats step has been thoroughly tested/run on the command line.
This PR is specifically testing the METplus loop error fix to resolve the "missing" data errors seen in the reformat step. 

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

How to Run My EVS Scripts:
Step 1: Prep
In your local clone of EVS/ecf/subseasonal/prep/jevs_subseasonal_prep.ecf, you will need to change my name to yours in the output file:
#PBS -o /lfs/h2/emc/vpppg/noscrub/**shannon.shields**/EVS/ecf/subseasonal/prep/evs_subseasonal_prep_out.txt

Then run the prep ecf file by doing the following:
cd /lfs/h2/emc/vpppg/noscrub/$USER/EVS/ecf/subseasonal/prep
qsub jevs_subseasonal_prep.ecf

This will take a little over an hour to run.
The output should be in: /lfs/h2/emc/vpppg/noscrub/$USER/EVS_Data/evs/v1.0/prep/subseasonal/atmos.YYYYMMDD

Step 2: Stats
You will also need to change my name to yours in the output files for stats in the following:
EVS/ecf/subseasonal/stats/jevs_cfs_subseasonal_grid2grid_stats.ecf
EVS/ecf/subseasonal/stats/jevs_gefs_subseasonal_grid2grid_stats.ecf

Then run the stats ecf files one model at a time by doing the following:
cd /lfs/h2/emc/vpppg/noscrub/$USER/EVS/ecf/subseasonal/stats
qsub jevs_cfs_subseasonal_grid2grid_stats.ecf
qsub jevs_gefs_subseasonal_grid2grid_stats.ecf

This should take about 10 mins per model to run.
The output should be in: /lfs/h2/emc/vpppg/noscrub/$USER/evs_subseasonal_test/dev/com/evs/v1.0/stats/subseasonal/$MODEL.YYYYMMDD

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **April 6 2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShannonShields-NOAA** [comment]
@ShelleyMelchior-NOAA A few more clarifications when you go to run the prep and stats steps:
For prep, VDATE is already set to PDYm2 so as long as you run this step before 8pm tonight, you do not need to change anything.
The same goes for stats; VDATE is set to the default PDYm2 so as long as you run this step before 8pm tonight, you do not need to adjust the date. As with the previous PR, the data directory is pointing to my own.

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks @ShannonShields-NOAA ! I got the prep done before 8:00p! Please see `/lfs/h2/emc/ptmp/shelley.melchior/EVS_Data/evs/v1.0/prep/subseasonal/atmos.20230321` to evaluate my results.

I will get started w/ stats, but adjust the VDATE to PDYm3 (20230321) since it is after 8p and make sure to point to your prep data.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran stats for cfs grid2grid. Please see the results here:
`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs_subseasonal_test/dev/com/evs/v1.0/stats/subseasonal/cfs.20230321`

And if you need it, the output log file:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/evs_cfs_subseasonal_grid2grid_stats_out.txt`

**Comment by ShelleyMelchior-NOAA** [comment]
I ran stats for gefs grid2grid. Please see the results here:
`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs_subseasonal_test/dev/com/evs/v1.0/stats/subseasonal/gefs.20230321`

And if you need it, the output log file:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/evs_gefs_subseasonal_grid2grid_stats_out.txt`

**Comment by ShannonShields-NOAA** [comment]
@ShelleyMelchior-NOAA The prep step ran fine and everything is in the atmos.20230321 directory as it shoud be. However, the stats step for CFS and GEFS will have to be rerun for today. This is because in the EVS/scripts/subseasonal/stats the exevs_subseasonal_grid2grid_stats.sh script is now set based on a VDATE = PDYm2 for the explicit daily, weekly, and monthly looping. This looping (with the PDY numbers) must be set as is in the exec script to run correctly. My apologies for not saying this clearly before (hence why this had to run before 8pm). I am running the prep step on my end now and will let you know when that is done so you may rerun the stats for today.

**Comment by ShannonShields-NOAA** [comment]
The prep step has finished running (for 20230322) so you should now be able to run the stats step for both models. Make sure VDATE is set to PDYm2 as should be the default in the JEVS_SUBSEASONAL_STATS j-job.

**Comment by ShelleyMelchior-NOAA** [comment]
Got it! Thanks, @ShannonShields-NOAA . I have re-run stats for cfs and gefs grid2grid. The run was for PDYm2 (20230322). The output stats dir and log files are provided before for you to check. The stats files and log files are larger so that is promising.
`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs_subseasonal_test/dev/com/evs/v1.0/stats/subseasonal`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/evs_cfs_subseasonal_grid2grid_stats_out.txt`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/evs_gefs_subseasonal_grid2grid_stats_out.txt`

**Comment by ShannonShields-NOAA** [comment]
Everything looks good @ShelleyMelchior-NOAA ! All daily, weekly, and monthly SST and sea ice concentration stat values exist in the model stat files and a brief check of the METplus log files yields no errors. So this PR should be good to merge into the EMC develop branch.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All file changes look good. Approved.

**Pull request merged**
