### PR TITLE
Feature/ee2 rev3 rtofs

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
This PR fixes the syntax errors that occur due to missing the observational data. It was observed that sometimes the observational data have abnormal sizes while they exist that causes syntax errors in the .o files. To prevent this, the size of the data file is checked in addition to its existence.                               
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

clone my EVS repository in your local, then find the driver scripts located at: EVS/dev/drivers/scripts
for prep: dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.sh
for stats: dev/drivers/scripts/stats/rtofs/
for SMAP data, run: jevs_rtofs_smap_stats.sh
for plots: dev/driver/scripts/plots/rtofs/
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA I will begin work on this PR.  

I do see that you only changed one file for this PR.  and the issue occurred in stats.  I do not think it's really necessary to test prep, stats, and plots to check this PR if no changes were made to prep or plots.  These jobs take too long.  Rather, I can just test the stats job in question and point COMIN to emc.vpppg.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran several tests.
VDATE=20231202 -- `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rtofs_smap_stats.o94894767`
COMOUT was empty for SMAP because there is no data in 20231202:
```
$ ls /lfs/h1/ops/prod/dcom/202312*/validation_data/marine/smap/                                                                 
/lfs/h1/ops/prod/dcom/20231201/validation_data/marine/smap/:
FR_20231201.dat  SP_D2023335_Map_SATSSS_data_1day.nc

/lfs/h1/ops/prod/dcom/20231202/validation_data/marine/smap/:
```

So I decided to run again and force VDATE=20231201 -- `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rtofs_smap_stats.o94895562`
COMOUT was also empty for SMAP, but this time b/c the data that is present, is of irregular size (too small) and the code update handled the situation properly.
```
$ ll /lfs/h1/ops/prod/dcom/202312*/validation_data/marine/smap/
/lfs/h1/ops/prod/dcom/20231201/validation_data/marine/smap/:
total 8
-rw-rw-r-- 1 dfprod prod 369 Dec  3 18:05 FR_20231201.dat
-rw-rw-r-- 1 dfprod prod 519 Dec  3 17:23 SP_D2023335_Map_SATSSS_data_1day.nc

/lfs/h1/ops/prod/dcom/20231202/validation_data/marine/smap/:
total 0
```

I am going to run two more tests, for VDATE=20231201 and 20231202, but using the old version of `exevs_rtofs_smap_stats.sh`, before Samira's updates, to make sure it throws the system error that Lin was seeing in his EE2 review.

**_Interestingly, and just for the record, the last time there was good SMAP data was back on 20231128._**

**Comment by SamiraArdani-NOAA** [comment]
> I ran several tests. VDATE=20231202 -- `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rtofs_smap_stats.o94894767` COMOUT was empty for SMAP because there is no data in 20231202:
> 
> ```
> $ ls /lfs/h1/ops/prod/dcom/202312*/validation_data/marine/smap/                                                                 
> /lfs/h1/ops/prod/dcom/20231201/validation_data/marine/smap/:
> FR_20231201.dat  SP_D2023335_Map_SATSSS_data_1day.nc
> 
> /lfs/h1/ops/prod/dcom/20231202/validation_data/marine/smap/:
> ```
> 
> So I decided to run again and force VDATE=20231201 -- `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rtofs_smap_stats.o94895562` COMOUT was also empty for SMAP, but this time b/c the data that is present, is of irregular size (too small) and the code update handled the situation properly.
> 
> ```
> $ ll /lfs/h1/ops/prod/dcom/202312*/validation_data/marine/smap/
> /lfs/h1/ops/prod/dcom/20231201/validation_data/marine/smap/:
> total 8
> -rw-rw-r-- 1 dfprod prod 369 Dec  3 18:05 FR_20231201.dat
> -rw-rw-r-- 1 dfprod prod 519 Dec  3 17:23 SP_D2023335_Map_SATSSS_data_1day.nc
> 
> /lfs/h1/ops/prod/dcom/20231202/validation_data/marine/smap/:
> total 0
> ```
> 
> I am going to run two more tests, for VDATE=20231201 and 20231202, but using the old version of `exevs_rtofs_smap_stats.sh`, before Samira's updates, to make sure it throws the system error that Lin was seeing in his EE2 review.
> 
> **_Interestingly, and just for the record, the last time there was good SMAP data was back on 20231128._**

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA , @ShelleyMelchior-NOAA:
Sorry, I wanted to edit comment and mistakenly closed the discussion. Thanks @ShelleyMelchior-NOAA for opening it again.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : Right. The SMAP data have been missed since mid-November. That is the reason the stat data is empty.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran the tests again for 20231202 w/ the old code to reproduce what Lin was seeing. In the logfile (`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rtofs_smap_stats.o94897236`) I see the following:
```
00 + ls -l '/lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_rtofs_smap_stats.94897236.cbqs
01/stats/smap.20231202/sss/*.stat' ls: cannot access '/lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_rtofs_smap_stats.94897236.cbqs01/stats/smap.20231202/sss/*.stat': No such file or directory
```
and as noted above, the code additions by Samira prevent this system error from occurring.

I ran the test again, w/ the old code, but for VDATE=20231201, which has data, just of abnormal size.
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rtofs_smap_stats.o94897433`
The result are some METplus errors b/c it is trying to generate statistics on an abnormal smap data file. Which then cascades to a FATAL error when trying to copy the stats file from $DATA to $COMOUT b/c the stats file was not generated.
The code changes introduced by Samira will not allow the processing to get to this point b/c her additions check both for smap  data file existence as well as for abnormal size.

I think the changes introduced for this PR are robust and address the EE2 finding pointed out by Lin. This is sufficient for the EE2 review.

I would like to see similar code for the other data sets required by EVS for RTOFS so that all data sets are coded just as robustly.

**Comment by ShelleyMelchior-NOAA** [comment]
@SamiraArdani-NOAA , in anticipation of an impending  merge, please run a sync fork on `feature/EE2_REV3_rtofs`. Marcel's PR was merged over the weekend.

**Comment by AliciaBentley-NOAA** [comment]
@ShelleyMelchior-NOAA @SamiraArdani-NOAA This PR looks very good to me! Thank you. I approval merging it into develop! Thanks!

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yielded expected results. This PR is approved for merge.

**Pull request merged**
