### PR TITLE
feature/global_det_atmos - prep and stats

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

> - The prep and stats jobs are run every day as cron jobs. Quick look graphics generated at https://emc.ncep.noaa.gov/gmb/mpr/evs_stats_check/ were approved by Geoff and Alicia.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> There are scripts set up for testing at /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts. 

1. Checkout the branch.
2. Open /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/evs_global_det_atmos_set_up.sh and set EVSclone to where the clone is. Run the script.
3. Open /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/run_evs_global_det_atmos_prep.sh and set EVSclone to where the clone is.
4.  Open /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/run_evs_global_det_atmos_stats.sh and set EVSclone to where the clone is.
5. /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/crontab.evs_global_det_atmos_test is a crontab set up to run the scripts in step 3 and 4. The paths for those scripts and the associated log paths will need to be updated accordingly.

> I would like the prep step to be run and tested, rather than the prep directories I have been running being linked or copied and the stats jobs just being run. There will need to be some spin up done for the prep and stats jobs before they get running at full capacity.

- [ ] Do these updates/additions include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation?</br>

> We do not have any EVS documentation.

- [ ] Do these updates/additions include sufficient testing updates?</br>

> Yes

- [ ] Please complete this pull request review by <b>11/8/2022</b>.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

I'm kind of confused. I clone your code am in your branch, but are these test scripts part of this code?  Or are these test scripts outside the code on GitHub?

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA They are outside of GitHub at /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA I need to make an adjustment to the code involving the prep step. NCO started pulling in the GHRSST median data into dcom. I need to make some paths updates related to that. Is that okay to make these changes?

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

It is OK to make these changes.  I haven't started on your code yet as I am working on someone else's at the moment.  Please be sure that if you make changes that they are well-tested before submitting them.  

Also, I am not entirely sure that execution scripts can be outside of the code system.  I'll go ahead and test them per your instructions, but we'll also need to make sure that we can execute codes the way NCO would submit them, with a qsub to an ecf job.  I'm guessing that is inside these test scripts.  

Thanks!

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA These scripts are just for testing. NCO will just be submitting the ecf scripts and these scripts will in no way be used by them. That is essentially what these scripts do (submit the ecf scripts), but I made these test scripts to make testing easier for you.

**Comment by PerryShafran-NOAA** [comment]
I am beginning work on your PR now.  I pulled in the updates to your feature branch just now, and unless I am missing anything else, I am ready to test.

Perry

**Comment by PerryShafran-NOAA** [comment]
I started with the 1st step, the set-up script, and am seeing this error:

```
+ ls '/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/sorc/../exec/*'
ls: cannot access '/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/sorc/../exec/*': No such file or directory
```

I think this is OK for me to continue on, as I see this in the exec directory:

```
16 (clogin01) /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/exec > ls -l
total 5304
-rwxr-xr-x 1 perry.shafran vpppg 1422424 Oct 26 14:46 ecm_gfs_look_alike_new
-rwxr-xr-x 1 perry.shafran vpppg 1400280 Oct 26 14:46 jma_merge
-rwxr-xr-x 1 perry.shafran vpppg 1163160 Oct 26 14:46 pcpconform
-rwxr-xr-x 1 perry.shafran vpppg 1439136 Oct 26 14:46 ukm_hires_merge
17 (clogin01) /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/exec >
``` 

Just wanted to check to see that all the exec files you expect are there.

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Yup, build of the execs looks good.

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

Could you check if the following directories are giving results as you expect them?

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/prep/global_det/atmos.20221025
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det

Also, the structure looks good.  I've noticed in your scripts that you set some COMIN/COMOUT variables in both the ecf and the jobs file - they probably should be defined once.  Also some settings are seen twice in your ecf file, but I do notice that one section of the ecf file is labelled "For dev testing" and I'm wondering if they are used for these runs.

Thanks!

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Thanks! 

The output from the prep at /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/prep/global_det/atmos.20221025 looks good. Glad to see the prep step ran on its own just fine!

For the stats output since there is just the one day in the prep directory, the "full" results won't be there, meaning for the models the full length to which they should be verified out to can't be done since the files in the prep directory for the previous days aren't there.

I would say next steps would be for some copying of directories, and then set the prep and stats jobs to run at their designated times. I can then compare the results to what I am running.

If this next step is okay, let me know and I can send a list of what should be copied.

**Comment by PerryShafran-NOAA** [comment]
You mean run the jobs in cron?  What kind of timing are we looking at to get "full" results?

Please send what needs to be copied.

**Comment by malloryprow** [comment]
It would be best to run in a cron. The prep step should be run at 1830Z so it can pick up ECMWF precipitation files. Then the stats step runs at 1930Z. I have the run times listed in the EVS Technical Document, and in /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/crontab.evs_global_det_atmos_test.

The longest job that will run will be the GFS grid-to-grid stats job (jevs_gfs_atmos_grid2grid_stats.ecf), which runs at a little bit over an hour.

Here is what should be copied:

- cp -r /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test/dev/com/evs/v1.0/prep/global_det/* /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/prep/global_det/.
- cp -r /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det/atmos.* /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs_global_det_atmos_test/dev/com/evs/v1.0/stats/global_det/.

**Comment by PerryShafran-NOAA** [comment]
I will go ahead and copy and the add in the crons.  

I meant how many days of this will need to be run before we have the "full" verification stats we need?  

Perry

**Comment by malloryprow** [comment]
Ah, I see. Once the directories are copied over everything will be there to generate the "full" stats. If we didn't, it would be 16 days. Copying the directories will speed the process along.

**Comment by PerryShafran-NOAA** [comment]
Your jobs are currently running, so if you can check the stats directory that I posted earlier, that would be great.

Also, could you please address the other issues I posted above regarding the items in the "For dev testing" section of your ecf files?

Thanks!

Perry

**Comment by PerryShafran-NOAA** [comment]
Seems like all the scripts have completed.  If you'd have a look and compare the stat and output files with mine, that would be great.

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Yes, that section is just for dev testing. It should removed before the code gets passed on to NCO. The variables in the "for dev testing" section, does some of the things that are done in the head.h an envir-p1.h files do as well as define some variables to override their default settings in the j-job and ex-script in order to do development testing. The are defined in their appropriate places in the j-job and ex-script.

I'll go ahead and look at the output.

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Output looks good! I wrote a script yesterday to quickly compare your results with mine and all looks well!

**Comment by PerryShafran-NOAA** [comment]
Excellent, you're good to go!  I'll do the merging and hopefully that won't cause too much trouble for others.

Perry

**Comment by AliciaBentley-NOAA** [comment]
Hi everyone,

Great job! Another merged pull request!

Mallory- will you let me know what lines to turn dark blue in the EVS
Overview Spreadsheets when you can? Thanks!

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Physical Scientist | Model Evaluation Group
<https://www.emc.ncep.noaa.gov/users/meg/home/>
Global Model Verification Team Lead
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by malloryprow** [comment]
@AliciaBentley-NOAA Yes! Lines 3-18, 20-28, 33-38, 43, 48, 50-53

**Pull request merged**
