### PR TITLE
bugfix/analyses Guam rtma gusts

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
This item addresses items 37 and 38 on Wei's EVSv1 Issues document.  There were certain WARNINGs related to the verification of wind gust in the Guam rtma.  There is no wind gust analysis in the Guam rtma.  It also removes the HTSGW, significant wave height, since we are not doing that in analyses verification but also throws up warnings.  

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

I tested the rtma stats job and the analyses plots job.  The warnings were not present in either once I removed any processing of Guam rtma wind gust.  

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run the rtma stats job, using qsub -v vhr=00.  You do NOT have to run urma nor rtma_ru; neither of them have any Guam verification to worry about.  

Run the analyses plots job.  Set COMIN to point to emc.vpppg.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/rtma_guam`.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran the rtma stats job.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_analyses_rtma_grid2obs_stats.o122318544`
I no longer see the warning statements. ✔️ 
```
[dlogin01 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ grep WARNING jevs_analyses_rtma_grid2obs_stats.o122318544 
[dlogin01 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$
```
The output stat files for vhr=00 match between my test and emc.vpppg.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran the analyses plots job.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_analyses_grid2obs_plots.o122332348`
I no longer see the warning statements. ✔️ 
```
[dlogin01 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ grep WARNING jevs_analyses_grid2obs_plots.o122322314
[dlogin01 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$
```
The resultant tar files are different. Mine is smaller. I believe this is expected. My tar does not include the following files:
`evs.rtma.bcrmse_me.gust_z10.last31days.vhrmean.buk_*.png` (8)
`evs.rtma_ru.bcrmse_me.gust_z10.last31days.vhrmean.buk_*.png` (5)
`evs.urma.bcrmse_me.gust_z10.last31days.vhrmean.buk_*.png` (8)
```
[dlogin01 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ ll /lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/analyses/atmos.20231225/evs.plots.analyses.atmos.grid2obs.last31days.v20231225.tar 
-rw-r--r-- 1 shelley.melchior emc 201144320 Dec 27 02:55 /lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/analyses/atmos.20231225/evs.plots.analyses.atmos.grid2obs.last31days.v20231225.tar
[dlogin01 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ ll /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/analyses/atmos.20231225/evs.plots.analyses.atmos.grid2obs.last31days.v20231225.tar 
-rw-r--r-- 1 emc.vpppg emc 221009920 Dec 27 01:21 /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/analyses/atmos.20231225/evs.plots.analyses.atmos.grid2obs.last31days.v20231225.tar
```
Please confirm.

**Comment by PerryShafran-NOAA** [comment]
Hmm - I'll have to figure that one out - you shouldn't have had any fewer gust plots.  Let me look into that, I may have coded that up wrong.

**Comment by PerryShafran-NOAA** [comment]
OK, I see what happened there:

```
48 + for varb in GUST
48 + '[' yes = yes -a CONUS '!=' 'Guam]'
/lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_guam/EVS/scripts/plots/analyses/exevs_analyses_grid2obs_plots.sh: line 20
9: [: missing `]'
```

Whoops!  I didn't have a space between the Guam and the closing bracket.  The gust plots should not be missing altogether.  

Please pull in the changes and try again.  I will also re-run in my own space.

**Comment by ShelleyMelchior-NOAA** [comment]
The re-run has completed. The tar files match better!
```
[dlogin04 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ ll /lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/analyses/atmos.20231225/evs.plots.analyses.atmos.grid2obs.last31days.v20231225.tar 
-rw-r--r-- 1 shelley.melchior emc 221009920 Dec 27 16:18 /lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/analyses/atmos.20231225/evs.plots.analyses.atmos.grid2obs.last31days.v20231225.tar
```
```
[dlogin04 /lfs/h2/emc/ptmp/shelley.melchior/EVS_out]$ ll /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/analyses/atmos.20231225/evs.plots.analyses.atmos.grid2obs.last31days.v20231225.tar         
-rw-r--r-- 1 emc.vpppg emc 221009920 Dec 27 01:21 /lfs/h2/emc/ptmp/emc.vpppg/evs/v1.0/plots/analyses/atmos.20231225/evs.plots.analyses.atmos.grid2obs.last31days.v20231225.tar
```
I think this PR is ready for merge.

**Comment by ShelleyMelchior-NOAA** [comment]
To address 47 of Wei's list, I have updated the project code for two ecf scripts.

**Comment by PerryShafran-NOAA** [comment]
Thank you!  I have synced the fork and I approve for merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests resulted in anticipated results. This PR is approved for merge.

**Pull request merged**
