### PR TITLE
Feature/stats meso2

### PR DESCRIPTION
**Pull request by RoshanShrestha-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out `feature/stats_meso2`. I am re-running g2o stats for nam and rap from this new branch.

**Comment by ShelleyMelchior-NOAA** [comment]
@RoshanShrestha-NOAA -- I re-ran nam and rap g2o stats from `feature/stats_meso2` and everything completed. Please have a look at the output for 20230626.
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nam_grid2obs_stats_00.o66437848`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rap_grid2obs_stats_00.o66437850`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/mesoscale`

Let me know how things look.
If everything looks good I will do the final code review. I will also take some care to see if some large file was accidentally introduced per Rahul's thinking.

**Comment by RoshanShrestha-NOAA** [comment]
Everything looks good. Thank you.

**Review by ShelleyMelchior-NOAA — COMMENTED** [review]
The code all looks fine to me. And no files are egregiously large, which is good. But I am still seeing some code in ush/ that appears to be for plotting. Are these really needed for stats processing? Maybe they are! I am inclined to proceed w/ the PR merge, though, as long as @MarcelCaron-NOAA can confirm that adding these files in this PR to the auth EVS develop won't cause trouble in his mesoscale g2o plots feature branch.

**Comment by RoshanShrestha-NOAA** [comment]
The code in ush/ that you are referring may be mesoscale_plots_grid2obs_graphx_defs.py which I was using for graphics definitions. I will remote it as well. Thank you.

**Comment by RoshanShrestha-NOAA** [comment]
The plots related graphics definitions are removed now.

**Comment by MarcelCaron-NOAA** [comment]
@RoshanShrestha-NOAA and @ShelleyMelchior-NOAA thanks, this looks good to me.  I don’t think there will be any difficulty merging these changes into the plotting feature branches.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]

**Pull request merged**
