### PR TITLE
Feature/stats meso2

### PR DESCRIPTION
**Pull request by RoshanShrestha-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
    The module load statements are moved to modulefiles/mesoscale directory.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@RoshanShrestha-NOAA this looks great upon first glance. Have you re-run the stats g2o jobs after making these adjustments for /dev/driver/scripts and modulefiles?

**Comment by ShelleyMelchior-NOAA** [comment]
@RoshanShrestha-NOAA -- I have submitted the nam and rap g2o jobs w/ the changes as a sanity check.
While those run, can you also make these changes for:
`jevs_nam_precip_stats.sh`
`jevs_nam_snowfall_stats.sh`
`jevs_rap_precip_stats.sh`
`jevs_rap_snowfall_stats.sh`

@malloryprow  and @MarcelCaron-NOAA  - just FYI.

**Comment by malloryprow** [comment]
Thanks for making the changes @RoshanShrestha-NOAA!

A few things:

- Do we need _source /usr/share/lmod/lmod/init/sh_ in there? I'm not sure if this is needed.
- Does _export MET_bin_exec="bin"_ belong in the module files or the ecf scripts? @GeoffManikin-NOAA @AliciaBentley-NOAA @LoganDawson-NOAA 
- The module loads you commented out I would just remove for brevity of the script.

**Comment by RoshanShrestha-NOAA** [comment]
Hi @malloryprow 

I left source /usr/share/lmod/lmod/init/sh  as it is, thinking that it would avoid any conflicts with other sh configuration that the machine may inherit. If it is not needed, I will remove it.

I will remove the lines commented out.

Thank you.

**Comment by AliciaBentley-NOAA** [comment]
Hi Mallory and Roshan,

I'm not sure if *export MET_bin_exec="bin"* belongs in the modulefiles or
the /dev/drivers/scripts. Leaning toward modulefiles so that it can be
imported by our /dev/drivers/scripts and the future ops .ecf scripts, but I
will let Logan/Geoff/Perry/Shelley answer you! Thanks!

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA RE: MET_bin_exec=bin, eventually we will fix certain values in machine.conf so that it is defined in there so that it doesn't have to be defined anywhere else.  I believe we decided that as a group recently.  I think it's a good idea.  Until that particular work is done, leaving it in the driver .sh script should be OK.  

Perry

**Comment by AliciaBentley-NOAA** [comment]
Hi Perry,

Thanks! My concern is that if we define *export MET_bin_exec="bin"* in the
.sh driver scripts only, then the new .ecf scripts won't know that
information when we run EVS using ecflow. Will not knowing that
MET_bin_exec="bin"
in the new .ecf scripts cause our jobs to crash?

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by ShelleyMelchior-NOAA** [comment]
It is my uderstanding that the driver `.sh` scripts will still be used as a model for building the official `*.ecf` scripts.

**Comment by AliciaBentley-NOAA** [comment]
Sounds good! Thanks, all! That makes sense to me.

___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA not if it's fixed in machine.conf.  machine.conf is called every time run_metplus.py is run.  Like right now, in machine.conf, we have:

`MET_BIN_DIR = {MET_INSTALL_DIR}/{ENV[MET_bin_exec]}`

The plan is to change that to:

`MET_BIN_DIR = {MET_INSTALL_DIR}/bin`

That way, MET_bin_exec won't need to be defined anywhere.  It's taken care of in the machine.conf.

Perry

**Comment by AliciaBentley-NOAA** [comment]
Hi Perry,

I agree with you, but that change isn't in the auth repo yet, right? Since
that change isn't in the auth repo yet and since we need our code to
continue to run in the meantime, I agree that *export MET_bin_exec="bin" *can
be in the .sh driver scripts for now. When can we expect this update to
machine.conf be made to the auth repo?

Take care,
Alicia
___________________________________
*Alicia M. Bentley, Ph.D.*
Global Verification Project Lead
Model Evaluation Group (MEG) <https://www.emc.ncep.noaa.gov/users/meg/home/>
NOAA/NWS/NCEP/EMC (VPPPG Branch)
Work Phone: ‪(301) 683-3783‬

**Comment by PerryShafran-NOAA** [comment]
Soon.  In fact I probably should do it sooner rather than later, like before the end of the week.  Shouldn't take too much time.

Perry

**Comment by malloryprow** [comment]
It probably be good to do ASAP since everyone is updating the scripts. We don't want them to have to go back and do it again to remove MET_bin_exec. OR wait until everyone is done and then 1 person goes back and makes the changes to machine.conf and cleaning up the drivers.

**Comment by ShelleyMelchior-NOAA** [comment]
@RoshanShrestha-NOAA , your g2o nam and rap runs comleted successfully. I can try to test snowfall and precip next.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/mesoscale`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rap_grid2obs_stats_00.o66642561`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nam_grid2obs_stats_00.o66642551`

**Comment by RoshanShrestha-NOAA** [comment]
The outputs look all as expected. Thank you.

**Comment by ShelleyMelchior-NOAA** [comment]
Great! Next I will run the precip and snowfall processing.

**Comment by ShelleyMelchior-NOAA** [comment]
@RoshanShrestha-NOAA and @malloryprow , I completed the runs for nam and rap precip and snowfall stats. I think they ran correctly, but there aren't snowfall stats. It may be because of the season?
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/mesoscale`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_[nam][rap]_[precip][snowfall]_stats*.o*`

**Comment by RoshanShrestha-NOAA** [comment]
I also got the same results. The runs were complete without snowfall stats.

**Comment by ShelleyMelchior-NOAA** [comment]
Great -- I will do the code review and then merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All code changes are as expected.

**Pull request merged**
