### PR TITLE
bugfix/global_det_atmos_pb_check

### PR DESCRIPTION
**Pull request by malloryprow**
This addresses the note from Lin in https://docs.google.com/document/d/1dnV3fjtuQOdmYMqdj4Ew4tLsouOIhk2luQji_DMXOPI/edit

> Silent failed job jevs_global_det_atmos_gfs_grid2obs_stats_00.o94456608
> -rw-r--r-- 1 emc.vpppg emc 172M Nov 29 19:27 jevs_global_det_atmos_gfs_grid2obs_stats_00.o94456608

/lfs/h2/emc/ptmp/emc.vpppg/output/jevs_global_det_atmos_gfs_grid2obs_stats_00.o94456608 shows

> FATAL ERROR: chmod 640 /lfs/h2/emc/stmp/emc.vpppg/evs_test/prod/tmp/jevs_global_det_atmos_gfs_grid2obs_stats_00.94456608.cbqs01/grid2obs_stats/METplus_output/atmos.20231128/prepbufr/grid2obs/pb2nc_pres_levs_gdas_valid2023112812.nc gave return code 1

The code now checks for the prepbufr file before running the chmod and chgrp commands.

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

> None

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
> **Set-up**
> 1. Clone my fork and checkout branch bugfix/global_det_atmos_pb_check
> 2. ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix
> 
> **stats**
> Run dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_gfs_grid2obs_stats.sh 

- [ ] Has the code been checked to ensure that no errors occur during the execution? **No**

- [ ] Do these updates/additions include sufficient testing updates? **No**

- [ ] Please complete this pull request review by **12/7/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Starting the test for this PR.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Your jobs are now complete.  Please carefully examine the .o file here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr369test/EVS/dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_gfs_grid2obs_stats_00.o94619117

And the output here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det 

Also, do you know if this issue would affect any other portions of global_det?  Does this change work on all of global_det atmos?

**Comment by malloryprow** [comment]
Reviewing now!

It doesn't apply to all of global_det atmos, just the global_det atmos grid2obs stats jobs.

**Comment by PerryShafran-NOAA** [comment]
OK, but it does apply to all g2o stats jobs, not just gfs, yes?

**Comment by malloryprow** [comment]
Correct all g2o stats jobs. The gfs one is what Lin mentioned in the document. If you want to run the other ones, feel free! Those are much shorter than the gfs one. I think the rest take about 20 min at most.

**Comment by malloryprow** [comment]
BTW, everything looks good with the gfs run.

**Comment by PerryShafran-NOAA** [comment]
Only if you think it's necessary.  Usually I'm of the mindset of if it works for one, it should work the same for the others, especially if it's the same code reading the same file.  I'm ok with merging now if you are.

**Comment by malloryprow** [comment]
I'm okay with merging too!

**Comment by PerryShafran-NOAA** [comment]
OK, I don't think that we need a sync fork, but do check for me please?

**Comment by malloryprow** [comment]
All good!

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Pull request merged**
