### PR TITLE
feature/global_det_atmos_plots_units

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

Change the units in the graphic's title and values for FBAR graphics (where applicable) for the following variables:

- 2m TMP from K to F
- 2m DPT from K to F
- SST from K to F
- Soil TMP from K to F
- Daily average 2m TMP ANOM from K to F
- All winds (UGRD, VGRD, UGRD_VGRD) from m/s to kt
- Wind gust from m/s to kt
- Wind shear from m/s to kt

Adjust x-tick labels for threshold mean to be in F
Remove FIXevs from all dev/drivers/scripts/global_det
Add @AliciaBentley-NOAA to maillist

- [ ] Describe testing already performed for this Pull Request:</br>

> Ran impacted jobs and reviewed the images

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> The following jobs in dev/drivers/scripts/global_det/plots should be run: jevs_global_det_atmos_grid2grid_means_plots_31days.sh. jevs_global_det_atmos_grid2grid_pres_levs_plots_31days.sh, jevs_global_det_atmos_grid2grid_sst_plots_31days.sh, jevs_global_det_atmos_grid2obs_pres_levs_plots_31days.sh, jevs_global_det_atmos_grid2obs_sfc_plots_31days.sh, jevs_global_det_atmos_headline_plots.sh, jevs_global_det_atmos_long_term_plots.sh
> Set COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg in the scripts

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **09/15/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow Adding a few global_det comments from the [EE2 checklist document](https://docs.google.com/document/d/1fYsVrcrjj_NxJBYG6v0sDhi-vYxShT2l2EUauHIByLs/edit?pli=1) here for you: 

**Create a symbolic link in your HOMEevs directory to /EVS_fix. Here is how:**
1. cd into your HOMEevs directory
2. Create a new /fix directory using mkdir fix
3. Set up a symbolic link between the new /fix and the actual /EVS_fix directory:
4. ln -s /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix/* fix/

**Remove export FIXevs lines in all global_det /dev/drivers**
- Remove export FIXevs from line 41 of [dev/drivers/scripts/global_det/plots/jevs_global_det_atmos_headline_plots.sh](https://github.com/NOAA-EMC/EVS/blob/de168d6d4e6a9ed157eb350b914b906aaada9479/dev/drivers/scripts/global_det/plots/jevs_global_det_atmos_headline_plots.sh#L41)
- Remove export FIXevs from line 39 of [dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_long_term_stats.sh](https://github.com/NOAA-EMC/EVS/blob/de168d6d4e6a9ed157eb350b914b906aaada9479/dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_long_term_stats.sh#L39)
- Remove export FIXevs from line 45 of [dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_gfs_grid2obs_stats.sh](https://github.com/NOAA-EMC/EVS/blob/de168d6d4e6a9ed157eb350b914b906aaada9479/dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_gfs_grid2obs_stats.sh#L45)
- Remove export FIXevs from line 45 of [dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_cfs_grid2obs_stats.sh](https://github.com/NOAA-EMC/EVS/blob/de168d6d4e6a9ed157eb350b914b906aaada9479/dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_cfs_grid2obs_stats.sh#L45)
- Remove export FIXevs from line 45 of [dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_cmc_grid2obs_stats.sh](https://github.com/NOAA-EMC/EVS/blob/de168d6d4e6a9ed157eb350b914b906aaada9479/dev/drivers/scripts/global_det/stats/jevs_global_det_atmos_cmc_grid2obs_stats.sh#L45)
- Remove export FIXevs from line 45 of [dev/drivers/scripts/global_det/stats/jevs_global_det_wave_gfs_grid2obs_stats.sh](https://github.com/NOAA-EMC/EVS/blob/de168d6d4e6a9ed157eb350b914b906aaada9479/dev/drivers/scripts/global_det/stats/jevs_global_det_wave_gfs_grid2obs_stats.sh#L45)

**Comment by PerryShafran-NOAA** [comment]
@malloryprow - is this one ready for testing?

Perry

**Comment by malloryprow** [comment]
Good to go!

**Comment by PerryShafran-NOAA** [comment]
Tests underway.

**Comment by malloryprow** [comment]
I was looking at the plots from jevs_global_det_atmos_grid2grid_means_plots_31days.sh (/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230911/evs.plots.global_det.atmos.grid2grid_means.last31days.v20230911.tar) and they were empty. 

I see in /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr235test/EVS/dev/drivers/scripts/global_det/plots/evs_global_det_atmos_grid2grid_means_plots_31days_00.o96592411 that COMINgfs is /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/gfs. COMIN is /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0, though.

In jobs/global_det/plots/JEVS_GLOBAL_DET_PLOTS, COMINgfs=${COMINgfs:-$(compath.py -o $NET/$evs_ver/stats/$COMPONENT/gfs)}. So I guess that compath.py uses COMROOT to find the paths??

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow @PerryShafran-NOAA I think that compath.py should use COMPATH to find the past. That's why, if you have a model in /para and not /prod, you can [change this path in your run.ver](https://github.com/NOAA-EMC/EVS/blob/develop/versions/run.ver#L66) to point to the /para location. 

Let me look into this more... two seconds...

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow @PerryShafran-NOAA It looks like the COMINgfs path that you wrote is for the GFS "output" when you include the -o designation. For example, Mallory says it's:

export COMINgfs=${COMINgfs:-$(compath.py -o $NET/$evs_ver/stats/$COMPONENT/gfs)}
I think that's making it use COMOUT. Can we update this to not use the -o designation?

export COMINgfs=${COMINgfs:-$(compath.py $NET/$evs_ver/stats/$COMPONENT/gfs)} ???

**Comment by PerryShafran-NOAA** [comment]
I don't think it works that way.  When I remove the -o, I get the following.  I don't think that -o stands for "output"  This is what happens when I remove the -o.  

```
1 + export COMINgfs=
1 + COMINgfs=
11 + compath.py evs/v1.0/stats/global_det/cmc
WARNING: Could not find the dev COM paths list at /lfs/h1/ops/dev/config/compaths.list
WARNING: A member of the COM path list (evs/v1.0/stats/global_det/cmc) is not formatted correctly
Traceback (most recent call last):
  File "/apps/ops/prod/nco/core/prod_util.v2.0.13/ush/compath.py", line 210, in <module>
    print(get_compath(args.path.strip(), args.envir, args.out, args.verbose))
  File "/apps/ops/prod/nco/core/prod_util.v2.0.13/ush/compath.py", line 175, in get_compath
    pathenvir = getparts(relpath)["envir"]
KeyError: 'envir'

```

Perry

**Comment by PerryShafran-NOAA** [comment]
I think that the way for me to test this properly is to link to the emc.vpppg stats archive in my directory.  Let me try that.

**Comment by malloryprow** [comment]
Yeah that is what I had you all do before. I was trying to see if I could avoid that because I know it has caused some troubles in the past and with all the PR testing flying around I was trying to see if I could avoid having you do that and avoid any complications.

**Comment by malloryprow** [comment]
If you do this and do rerun, make sure you clear your COMOUT. The restart capabilities will just copy the files resulting in the same output.

**Comment by malloryprow** [comment]
I should be using compath.py though to set these variables in the J-JOB right??

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow Absolutely. NCO needs us to use compath.py for these definitions in the J-jobs!

**Comment by PerryShafran-NOAA** [comment]
OK, I cleared COMOUT and re-submitted one plot job, and then I'll knock out the rest.

Perry

**Comment by PerryShafran-NOAA** [comment]
The grid2grid means tar file is complete, and it does look bigger than before, which is good.  Can you check?

I'll run the other jobs.

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
Just FYI -- I will merge PR #234 soon. This action may pose some conflicts in this PR. I need to get PR #234 merged b/c there are plotting code fixes that other components will need.

**Comment by malloryprow** [comment]
I can check later tonight!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I actually submitted all the plot jobs that you requested.

**Comment by malloryprow** [comment]
Checking the output from /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230911/evs.plots.global_det.atmos.grid2grid_means.last31days.v20230911.tar.

image

Woohoo, stats are there now! Thanks for going and linking the stats directory. When I first started getting global_det up and running I was struggling to understand how compath.py worked and it feels full circle here we are the week of code delivery and I still don't understand it. LOL!

I'll do a more in-depth look into the other tar files during the production switch tomorrow.

**Comment by malloryprow** [comment]
Reviewed the rest of the PR this morning...

✅ Good to merge this PR!

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by PerryShafran-NOAA** [comment]
Everything looks good!  Merging now.

**Pull request merged**
