### PR TITLE
feature/build_exec_script

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- To be in compliance with EE2 standards, one build script was created to build the EVS executables

- [ ] Describe testing already performed for this Pull Request:</br>

> Compare the executables from the original scripts to the new ones using "diff"; there was no difference.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> Run sorc/build.sh

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **09/15/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
I just pulled this test out and did the build.  And then I did the build on the original directory and there was no difference.  I think we're generally good.

**Comment by malloryprow** [comment]
I'm good with merging!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I noticed some changes to sref and naefs build scripts as well.  Was that supposed to be done or did you intend to only make changes in global_det?

Perry

**Comment by PerryShafran-NOAA** [comment]
This merge is good to go!

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
