### PR TITLE
bugfix/ndbc_times

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

The NDBC buoy files in dcom keep data for weeks, even months in the text files. In the current global_det wave prep step, the NDBC buoy files in dcom are trimmed down to keep only INITDATE so that ascii2nc and point_stat run faster (not processing data that is not used). When point_stat is run there is a +/- 30 min window around the observation time. For 00Z this goes into 30 minutes back into the previous day, and the trimming of the NDBC buoy data misses the observations from the -30 min period. 

This fix adds to the prep step the addition of the day previous to INITDATE's observations.

- [ ] Describe testing already performed for this Pull Request:</br>

> I ran global_det wave prep and checked the trimmed NDBC files have the previous day to INITDATE in there. I also ran GFS wave stats. I saw in the ascii2nc file from the NDBC output had the additional data in there, and observation counts for the NDBC in the final stat file changed.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **05/17/2024 👼 🙏 **.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@malloryprow PR downloaded and prep job underway.  From your instructions, I'm guessing that if I run as it is, then I'm running using the beta4 versions?

**Comment by malloryprow** [comment]
Correct, no MET or METplus running in prep.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow But when I run stats, it's running the beta4 versions in this instance, correct?

**Comment by malloryprow** [comment]
Yes, correct!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow The prep job is already finished.

Check the .o file here:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr479test/EVS/dev/drivers/scripts/prep/global_det

And the output prep directory here:
 /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det/wave.20240516

**Comment by malloryprow** [comment]
✅ Everything is good with global_det wave prep! No WARNING or ERROR messages in the log. I checked a few random NDBC buoy files in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det/wave.20240516/ndbc and saw data for 20240516 (INITDATE) and 20240515 (day before INITDATE).

**Comment by PerryShafran-NOAA** [comment]
Correction for instruction 5:  the file I am running is: jevs_global_det_wave_gfs_grid2obs_stats.sh (you had the name of the prep file in the stats instruction).  

I also updated run.ver to use the beta4 versions of met and metplus, per your instruction, as well.

For your NOTE 2, I am somewhat confused.  I can point COMIN to /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det/wave.20240516 , but you said it has to be linked rather than have COMIN set to it.  I'm not sure what this means or where I should be linking to/from.  Can you elaborate?

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA @malloryprow Can we also test this step using the ops versions (MET-11.0.2/METplus-5.0.1), since this PR is destined for the EVS v1.0.x-bugfix release that will be using MET-11.0.2/METplus-5.0.1? Thanks!

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA Yes, this is part of the instruction and plan to do so.

**Comment by malloryprow** [comment]
Thanks for catching that! I updated the PR testing instructions.

COMIN is set as `export COMIN=/lfs/h2/emc/vpppg/noscrub/$USER/$NET/$evs_ver_2d`. For you that is /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det, but there is only wave.20240516. To use the updated NDBC files COMIN needs to stay this. It would be nice to test using GFS initializations from previous dates (ex. wave.20240515, wave.20240514, etc.), so those would need to be linked into /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det.

**Comment by PerryShafran-NOAA** [comment]
Ohhhh, I think I gotcha.  You want to link all the other days so there are all 16 days necessary to run the stats job.  Makes sense!

**Comment by malloryprow** [comment]
Exactly! The job would run fine without but it would just be nice to run with all 16 days of data.

**Comment by PerryShafran-NOAA** [comment]
Job is underway.  I have linked back to 20240430.  I am using the beta4 versions.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Job is finished.

Please examine the .o file here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr479test/EVS/dev/drivers/scripts/stats/global_det

and the output here:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det, 20240516 directories.

**Comment by malloryprow** [comment]
✅ All is good for GFS wave grid2obs stats with MET v12.0.0-beta4 and METplus v6.0.0-beta4. There were WARNING messages: `05/17 17:59:08.024 metplus.daeb8ce2 (time_looping.py:300) WARNING: PB2NC_SKIP_TIMES is deprecated. Please use PB2NC_SKIP_VALID_TIMES`. I'll address that in a future PR.

We can test now with MET v11.0.2 and METplus v5.0.1. Be sure to clean out /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/gfs.20240516 and /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/global_det/wave.20240516 so that restart doesn't kick in.

**Comment by PerryShafran-NOAA** [comment]
The production versions test is underway.

**Comment by malloryprow** [comment]
✅ All is good for GFS wave grid2obs stats with MET v11.0.2 and METplus v5.0.1.

**Comment by PerryShafran-NOAA** [comment]
Thank you!  Looks like we are good to go!

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
