### PR TITLE
feature/EVSv2_nfcens_naming

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
This PR addresses item no. 2 of "Fixes and Additions in EVS v1.0+" for nfcens component. In this PR, all the image names were updated to "lastXXdays" (previously, "pastXXdays").
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
1- To test the changes, you can only run the plots STEP.
2- Clone my fork in your local and checkout branch "feature/EVSv2_nfcens_naming", then find the driver scripts located at: EVS/dev/drivers/scripts/plots/nfcens/jevs_nfcens_wave_grid2obs_plots.sh

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
_**NOTE: I suggested to Samira that she file this PR. The changes are trivial and can be considered for EVSv1.0 as a bugfix.**_ However, if it is determined that this should be held for EVSv1.0+, we can keep this PR in the queue and she will keep `branch/feature/EVSv2_nfcens_naming` in sync w/ develop until we are ready to address this PR, after EVSv1.0 implementation.

**Comment by AliciaBentley-NOAA** [comment]
Thank you, @ShelleyMelchior-NOAA and @SamiraArdani-NOAA! I totally agree. I'm glad you submitted this PR. We'll hold off on it for a minute on testing it in favor of testing the EVS v1.0-related PRs. It would also be good to keep these changes out of develop until EVS v1.0 is in ops, just so that we don't have any issues creating upcoming tags. But great overall!

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA I am beginning to test your PR.  I am using as input the stats files from the EMC production, since you originally tested it using the current production versions of MET and METplus.  Since this is also scheduled to be an EVSv2 fix and not an immediate bugfix, I will also test it against the beta versions of MET and METplus, vs the current emc.vpppg stats.  

@AliciaBentley-NOAA @ShelleyMelchior-NOAA for awareness.

**Comment by PerryShafran-NOAA** [comment]
Hi, @SamiraArdani-NOAA ,

Please examine the .o output here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr426test/EVS/dev/drivers/scripts/plots/nfcens
and the plot tarball here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/nfcens/wave.20240404

Please let me know if all looks good to you in this first case.

**Comment by SamiraArdani-NOAA** [comment]
Hi @PerryShafran-NOAA, The .o file, plot tarballs and the images look good.

**Comment by PerryShafran-NOAA** [comment]
Great, and if that includes the filename, let me move on to the 2nd test, for the beta versions.  I'll let you know how that goes.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : filenames look as they were expected.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA The runs are complete.  Please look for the .o file and tar files in the same places, and pay close attention to see that the filename change is seen in your plot files.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : The .o file, tar files and the images look good. I checked the filenames and compared some random images with nfcens prod webpage and they all look as expected.

**Comment by PerryShafran-NOAA** [comment]
Great!  I am happy with the code and it all looks good.

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Pull request merged**
