### PR TITLE
Bugfix/aqm structure

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

The structure of aqm was changed to the system desired by NCO.  The prep, stats, and plots all worked perfectly after all the changes to structure were made and also within scripts using the structure.  

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run the prep driver.
Run the stats driver (using the -v cyc=04 or your favorite cycle number).  Set COMIN to the emc.vpppg directory.
Run the plots driver.  Set COMIN to the emc.vpppg directory.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/aqm_structure`.

**Comment by ShelleyMelchior-NOAA** [comment]
prep processing has concluded.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/aqm/atmos.20231003/aqm`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_prep_00.o83604813`

stats processing (cyc=04) has concluded.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/aqm/atmos.20231003/aqm/grid2obs`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_stats.o83605048`

plots processing has concluded.
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/atmos.20231003`
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/aqm/headline.20231003`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_aqm_grid2obs_plots.o83605360`

**Comment by PerryShafran-NOAA** [comment]
All prep, stats, and plots match exactly to what is in the emc.vpppg parallel.  

I think we're good here.

**Comment by ShelleyMelchior-NOAA** [comment]
Excellent! I will do one last code review and can merge.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests of code restructure produced expected results. This PR is ready for merge.

**Pull request merged**
