### PR TITLE
feature/global_det_cat_logs

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

1. "Cat" the METplus and plotting log files (so their contents are in the main log file)

- [ ] Describe testing already performed for this Pull Request:</br>
> I tested the stats and plots jobs and I compared the number of log files in DATA to instances of "cat" in the main log file.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
**Set-up**
> 1. Clone my fork and checkout branch feature/global_det_cat_logs
> 2. cd sorc
> 3. ./build-fix-link.sh

**prep**
> None of the changes in this PR impact the global_det wave or atmos prep jobs. Start with stats jobs.

**stats**
> 4. Run dev/drivers/scripts/stats/global_det/jevs_global_det_wave_gfs_grid2obs_stats.sh, dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_gfs_grid2grid_stats.sh, .dev/drivers/scripts/stats/global_det/jevs_global_det_atmos_gfs_grid2obs_stats.sh Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver. Depending on when this is run, VDATE in jobs/JEVS_GLOBAL_DET_STATS may be need to be set to PDYm2.

**plots**
> 5. Run dev/drivers/scripts/plots/global_det/jevs_global_det_wave_grid2obs_plots_31days.sh, dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2grid_means_plots_31days.sh, dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_grid2obs_ptype_plots_31days.sh, and dev/drivers/scripts/plots/global_det/jevs_global_det_atmos_headline.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **11/17/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I have begun work on this PR.  I am working on the stats job as instructed.  Are you certain that the prep jobs do not have any log files in $DATA that are not written out to the .o file?

**Comment by malloryprow** [comment]
Yes I am certain there are no logs in the prep step.

**Comment by malloryprow** [comment]
Not sure if you are running the stats with VDATE=PDYm2, but it can be left as PDYm1. I got missing data emails from your run that I didn't get earlier from my runs or from the parallel.

**Comment by malloryprow** [comment]
You can go ahead and run the plots too. No need to change VDATE_END, just point COMIN to emc.vpppg.

Then I can check these all in the morning.

**Comment by PerryShafran-NOAA** [comment]
I am running with VDATE=PDYm2.  Should I go back and run again with PDYm1?

**Comment by PerryShafran-NOAA** [comment]
OK, I am re-running stats with VDATE=PDYm1.

**Comment by PerryShafran-NOAA** [comment]
All the plot scripts are underway too.

**Comment by malloryprow** [comment]
Checking out the stats and plots for this PR right now. I'll update when I'm done checking everything.

**Comment by malloryprow** [comment]
✔️ **stats and plots are good**

The stat final stats files and plot tar files match the parallel. Additionally, the number of logs produced by each job matches the number of "cat" appearances in the job's .o file.

I'm good to merge this if others are.

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow Your changes in this PR look good! I think we can merge this today, too!

**Comment by malloryprow** [comment]
Just merged in develop after the merge of https://github.com/NOAA-EMC/EVS/pull/305 into develop

**Review by PerryShafran-NOAA — COMMENTED** [review]
Approved for merge.

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
