### PR TITLE
Bugfix/Subseasonal Final EE2

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
Testing has been conducted on the command line.
Changes include the following:
Add export err=$?; err_chk
Remove jlogfile
Change "cp" to "cpreq"
Remove "date" lines in J-jobs
Add prep data restrictions with "chmod" and "chgrp"
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Checkout feature branch and adjust paths accordingly.
Run all scripts under dev/drivers/scripts/prep/subseasonal/.
Run all scripts under dev/drivers/scripts/stats/subseasonal/. (Make sure you link 35 days of prep data)
Run all scripts under dev/drivers/scripts/plots/subseasonal/. (Make sure to link stats files)
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>
ASAP
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, @ShannonShields-NOAA - I am beginning work on this PR.  I am starting the prep step now; will let you know when that completes.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA It appears that the GEFS prep job timed out shortly before completing. Not sure if the slowness is related to the switch work from earlier, but can you please re-run the GEFS prep job? It should run fast as only a few forecast hours are still needed.

**Comment by PerryShafran-NOAA** [comment]
Well, I'll be, so it did!  I'll restart it.  

You *can* examine the .o output in /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr328test/EVS/dev/drivers/scripts/prep/subseasonal to see that the EE2 items that you listed in your instructions are actually there and working as intended.

**Comment by ShannonShields-NOAA** [comment]
For everything that has completed for prep so far, I can confirm the EE2 changes. However, I think the GEFS prep job restart is now stuck...might need to resubmit yet again. Ugh.
@PerryShafran-NOAA and @AliciaBentley-NOAA I have a few questions looking at the output:
1) Should I leave in "msg="JOB $job HAS COMPLETED NORMALLY." " at the bottom of my J-jobs or remove now that we are not using the postmsg command?
2) Should I add "export err=$?; err_chk" after I run my parm/evs_config file?

**Comment by PerryShafran-NOAA** [comment]
The GEFS prep job seems to be continuing as it is still in the queue.  Let's wait until the job is no longer in queue.  I happened to increase the wall time to get it to run.

As for your other questions, I think that the msg is OK as long as you don't have jlogfile or postmsg.  And I don't think you need to add an err check after doing the evs_config file.

**Comment by ShannonShields-NOAA** [comment]
Ok, thanks @PerryShafran-NOAA

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA do you confirm my answers to Shannon's question?  I could be wrong.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA @ShannonShields-NOAA I think that @ShelleyMelchior-NOAA  had other developers remove the "msg="JOB $job HAS COMPLETED NORMALLY." lines because they were only used in the lines with jlogfile and those have been removed. Leaving them won't hurt anything, they just aren't used anymore. Please check other PRs for removing usage of msg and jlogfiles as well.

**Comment by AliciaBentley-NOAA** [comment]
Others seem to have removed it ([global_det jlogfile PR](https://github.com/NOAA-EMC/EVS/pull/329/files#diff-7c6ca76cc2e90cce7731229f9ef9fb92f0bde1d3ba69782801a37f3ca763a87e))

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA all jobs seem to have completed successfully.  Please check the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr328test/EVS/dev/drivers/scripts/prep/subseasonal

The output files are here:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/subseasonal/atmos.20231030

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA and @AliciaBentley-NOAA I had one more realization: looking at other components, no one seems to be running evs_config in their [J-jobs](https://github.com/ShannonShields-NOAA/EVS/blob/develop/jobs/JEVS_SUBSEASONAL_STATS#L71) like I am doing. global_det for example is using:
source $config
export err=$?; err_chk
in the exevs script. So I wanted to check if I am doing this wrong or if sourcing the evs_config in the J-job is fine...?

**Comment by PerryShafran-NOAA** [comment]
Really good question; many of us have been sourcing in the dev drivers.  Probably J-job is fine.  @AliciaBentley-NOAA ?  Something else for us to worry about?

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA @ShannonShields-NOAA Good question! 

1) I don't know that anyone should be sourcing parm in a dev driver script. I think that the location of the parm directory is specified in the J-jobs, so it should come after that path is established. 

2) Shannon is right that other EVS parm files are typically sourced at the /scripts (exevs...) level. I think that it would be good to move the sourcing of parm files into the /scripts so that there so as little "extra work" done in the J-jobs as possible. Other than the time needed to make the change, I don't think this would be too difficult to do! If you want an even more definitive answer, please write Lin and Wei in the EVSv1 EE2 Space. They could be definitive.

**Comment by PerryShafran-NOAA** [comment]
No, this is definitely not more difficult to do.  I don't think that I'll need anything more definitive, we'll just go ahead and do it.  I will probably have to submit PRs in my own areas of interest to take care of this.

@ShannonShields-NOAA please make those changes.  Remove from J-job and put into exevs script.  

Let me know if you need anything re-run.

**Comment by ShannonShields-NOAA** [comment]
Ok, thank you @PerryShafran-NOAA and @AliciaBentley-NOAA , I will go ahead and make those changes. Perry, please hold on further testing until this is done.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA I have made the commits as seen above; please rerun the dev/drivers/scripts/prep/subseasonal/jevs_subseasonal_obs_prep.sh. This will cover the sourcing change for all prep jobs.

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA . Will do.  In the meantime, please feel free to validate the gefs and cfs prep jobs.

**Comment by ShannonShields-NOAA** [comment]
Yes, I confirmed with the previous runs that all EE2 changes took affect and worked.

**Comment by ShannonShields-NOAA** [comment]
Oops, sorry @PerryShafran-NOAA I forgot to tell you to re-check out the branch before re-running to include the recent changes.

**Comment by PerryShafran-NOAA** [comment]
Oops!  You didn't have to tell me, I should have done it.  Sorry!  Not your fault.

**Comment by PerryShafran-NOAA** [comment]
OK, I brought in the changes and re-ran the obs prep job.  You can take a look now.

**Comment by ShannonShields-NOAA** [comment]
Yes, there we go; all looks good to go with the recent changes (successfully sourcing evs_config with the new way).
Please proceed to running all stats drivers.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA @ShannonShields-NOAA I realized I hadn't said this explicitly yet: I have reviewed this Final EE2 PR and I think that it looks great! No comments from me. I approve for merging this once all testing is completed. 

Looks like prep went well! Are we up to testing stats now?

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA The stats step is complete:

Please see the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr328test/EVS/dev/drivers/scripts/stats/subseasonal
And the stats output here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr328test/EVS/dev/drivers/scripts/stats/subseasonal/____.20231030

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA I went through all of the output files and confirmed the EE2 changes were successful. I also made sure the cpreq statement worked at the end to copy final .stat files. So all good for stats jobs! We can move on to plots drivers.

**Comment by PerryShafran-NOAA** [comment]
OK, setting up plots drivers.

**Comment by PerryShafran-NOAA** [comment]
Plots are complete.

See the .o files:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr328test/EVS/dev/drivers/scripts/plots/subseasonal
tarballs are here:  /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/subseasonal/atmos.20231030

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA Yep, everything looks good with the plots! This PR should be set for merging.

**Comment by PerryShafran-NOAA** [comment]
Awesome.  I see you brought in the develop branch twice (with each of the other code merges), so I think we are good on that front?  Please confirm if you need to sync fork one more time.

**Comment by ShannonShields-NOAA** [comment]
I just checked and all syncs are up-to-date.

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Pull request merged**
