### PR TITLE
Feature/ee2 update nfcens

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
This PR is related to the generated log files for NFCENS plots.  For each run, two types of log files with extensions .log and .out (only one file with .log extension and many .out files) are generated. This modification is added to prevent receiving any potential syntax error like "no such file or directory" in .o file during the cp command execution in case files with that extension type do not exist.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
PREP driver script: /lfs/h2/emc/vpppg/noscrub/samira.ardani/EVS/dev/drivers/scripts/prep/nfcens/jevs_nfcens_wave_grid2obs_prep.sh
STATS driver script: /lfs/h2/emc/vpppg/noscrub/samira.ardani/EVS/dev/drivers/scripts/stats/nfcens/jevs_nfcens_wave_grid2obs_stats.sh
PLOTS driver script: /lfs/h2/emc/vpppg/noscrub/samira.ardani/EVS/dev/drivers/scripts/plots/nfcens/jevs_nfcens_wave_grid2obs_plots.sh

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes ]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes ]**

- [ ] Please complete this pull request review by **[11/22/2023]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks for this PR, @SamiraArdani-NOAA . I have cloned your fork and checked out branch `feature/EE2_update_nfcens`.
It looks like only a plots script was modified. Do I need to test all three steps, or only plots?

**Comment by SamiraArdani-NOAA** [comment]
Hi @ShelleyMelchior-NOAA , You can test only the plots scripts. Thanks!

**Comment by ShelleyMelchior-NOAA** [comment]
I submitted the nfcens plots job.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_nfcens_grid2obs_plots.o93501290`

**Comment by SamiraArdani-NOAA** [comment]
@ShelleyMelchior-NOAA : the .o file looks good. No syntax error was observed.

**Comment by AliciaBentley-NOAA** [comment]
@SamiraArdani-NOAA @ShelleyMelchior-NOAA If the output looks good and you are both satisfied, I approve this PR for merge! The code changed look good.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
The changes look good. The test yielded expected results. This PR is approved for merge.

**Pull request merged**
