### PR TITLE
Updating rtofs perf diag plots to have 3-digit fcst hours

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

Updated the performance diagram plot code in the same manner that the time series plot code was to get the 3-digit forecast hour in the filename.  

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Pull in the stats from the emc.vpppg parallel, then run the plot code to see that the perf diagrams are written out to have 3-digit forecast hours.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP.  

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@PerryShafran-NOAA , I have cloned your fork and checked out branch `feature/rtofs_fcsthr3`.

**Comment by ShelleyMelchior-NOAA** [comment]
The plots processing is underway.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_rtofs_plots.o77877206`
COMROOT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/rtofs/rtofs.20230820`
DATAROOT=
`/lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_rtofs_plots.77877206.cbqs01/plots/rtofs/rtofs.20230820`
I looked in the osisaf dir and the perfidag plots have 3 digit forecast hour fields!
`$ pwd`
`/lfs/h2/emc/stmp/shelley.melchior/evs_test/prod/tmp/jevs_rtofs_plots.77877206.cbqs01/plots/rtofs/rtofs.20230820/osisaf`
`$ ls *perf*`
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f000.antarctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f000.arctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f024.antarctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f024.arctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f048.antarctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f048.arctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f072.antarctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f072.arctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f096.antarctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f096.arctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f120.antarctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f120.arctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f144.antarctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f144.arctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f168.antarctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f168.arctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f192.antarctic.png
evs.rtofs.ctc.ice_coverage_z0_osisaf.last60days.perfdiag_valid00z_f192.arctic.png

**Comment by PerryShafran-NOAA** [comment]
Looks like all the performance diagrams have three-digit forecast hours in their filenames, so I feel that this test was a successful one.

I would be OK to merge.

Perry

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Code edit tested and produced expected results. This PR is approved for merge.

**Pull request merged**
