### PR TITLE
Bugfix/regional rev1

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

This PR addresses issues 58 and 59 noted in the Google Doc titled "EVS v1.0 issues".  Information about the cause and fix of each:

* 58 - KeyError occurs when trying to plot a model among a list of models and the model's data are filtered out for any reason before plotting occurs.  Python tries to access the model data from a dictionary, resulting in a KeyError.  _Fix:_ Added a check for the existence of the model name in dictionary keys, passing if True
* 59 - (1) "ncpus exceeded limit" and (2) FileExistsError when multiple python plotting processes attempt to write the same directory _Fix:_ (1) change mpi launcher slightly as described in the issues document, (2) wrap the makedirs function in a try-except block, catching any FileExistsErrors.
* 61 - Upper air verification of all Hires Windows includes levels P450 and P350, which are not available for AK forecasts.  Therefore, METplus outputs a warning that these levels are not available to verify. _Fix:_ Remove P350 and P450 from hiresw* raob variable definitions.

For the most part, the affected jobs were not tested.

---
- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

### (1) Set up jobs 
•	symlink the EVS_fix directory locally as "fix"
•	In all driver scripts, point all exports of "HOMEevs" to your EVS test directory
•	In all stats driver scripts, change COMIN to the parallel directory (`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/$evs_ver_2d`)

### (2) Test Jobs
Use the following to submit all jobs: `qsub –v vhr=00 `

From your EVS testing directory, the following scripts should be run using the setup in step (1):
```
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_grid2obs_stats.sh
```
```
dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_grid2obs_past90days_plots.sh
dev/drivers/scripts/plots/mesoscale/jevs_mesoscale_sref_cape_past90days_plots.sh
dev/drivers/scripts/plots/cam/jevs_cam_href_profile_past90days_plots.sh
```

_[Total: 3 stats jobs; 3 plots jobs]_

### (3) Review
- I'll check for red flags:
```
check="FATAL\|WARNING\|error\|Killed\|Cgroup\|argument expected\|No such file\|cannot\|empty\|failed\|unexpected\|exceeded"
grep "$check" $outfile
```
---
- [x] Has the code been checked to ensure that no errors occur during the execution? **NO**

---
- [x] Do these updates/additions include sufficient testing updates? **YES**

---
- [x] Please complete this pull request review by **ASAP**.</br>

---
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `bugfix/regional_rev1`.

**Comment by ShelleyMelchior-NOAA** [comment]
The runs for the mesoscale sref and cam href plot jobs have completed. 
logfiles:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_sref_cape_past90days_plots.o113311132`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_mesoscale_sref_grid2obs_past90days_plots.o113311111`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_href_profile_past90days_plots.o113311208`
I grep'd for FileExistsError and found 0.
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/mesoscale/atmos.20240117`
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/cam/atmos.20240117`
Final tar file sizes match very closely to NCO para.

**Comment by MarcelCaron-NOAA** [comment]
✔️ Agreed, I think jevs_mesoscale_sref_cape_past90days_plots, jevs_mesoscale_sref_grid2obs_past90days_plots, and jevs_mesoscale_sref_grid2obs_past90days_plots are successful and issues 58 and 59 are resolved.  


---
Can we test three more jobs?  
```
dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_grid2obs_stats.sh
dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_grid2obs_stats.sh
```

It would be the same testing instructions as in the PR description.  This tests a fix for issue 61, also added to the description.

**Comment by ShelleyMelchior-NOAA** [comment]
> ✔️ Agreed, I think jevs_mesoscale_sref_cape_past90days_plots, jevs_mesoscale_sref_grid2obs_past90days_plots, and jevs_mesoscale_sref_grid2obs_past90days_plots are successful and issues 58 and 59 are resolved.

I assume you meant to include `jevs_cam_href_profile_past90days_plots.sh` and not list `jevs_mesoscale_sref_grid2obs_past90days_plots` twice?
> 
> Can we test three more jobs?
> 
> ```
> dev/drivers/scripts/stats/cam/jevs_cam_hireswarw_grid2obs_stats.sh
> dev/drivers/scripts/stats/cam/jevs_cam_hireswarwmem2_grid2obs_stats.sh
> dev/drivers/scripts/stats/cam/jevs_cam_hireswfv3_grid2obs_stats.sh
> ```
> 
> It would be the same testing instructions as in the PR description. This tests a fix for issue 61, also added to the description.

On it! Thanks for updating the PR description and citing the item number in Wei's document.

**Comment by MarcelCaron-NOAA** [comment]
> I assume you meant to include jevs_cam_href_profile_past90days_plots.sh and not list jevs_mesoscale_sref_grid2obs_past90days_plots twice?

Oops, yes!  Copy-paste error.

**Comment by ShelleyMelchior-NOAA** [comment]
The three hiresw grid2obs stats jobs are underway.
logfiles: 
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_hireswfv3_grid2obs_stats.o113319648`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_hireswarwmem2_grid2obs_stats.o113319647`
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_cam_hireswarw_grid2obs_stats.o113319598`

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA Incase you missed @ShelleyMelchior-NOAA 's email:

"I think we can cap PR414 at issues 58, 59, and 61, unless Marcel can get the fix for 60 to me today, pretty soon. I can test it this weekend. The impacted drives have wall times of 4:00, 2:00, and 1:00, so they will need a bit of time to test."

Do we think this PR can be merged before the end of today before Monday's dev outage?

**Comment by MarcelCaron-NOAA** [comment]
@AliciaBentley-NOAA @ShelleyMelchior-NOAA Let's cap this at 58, 59, and 61  I'll stash my fix for 60 and prepare it for a separate PR if that's okay.  I don't want to carry it over too late in the day.

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA That's totally fine. Let's wrap up any loose ends in this PR (maybe the log files from those last 3 jobs?) and call it a day. Thank you!

**Comment by ShelleyMelchior-NOAA** [comment]
Marcel, did you provide a confirmation that the 3 hiresw grid2obs stats jobs performed as expected? I did some grepping for "WARNING: process_f" and "WARNING: Met" and got 0 hits.

**Comment by MarcelCaron-NOAA** [comment]
Hi @ShelleyMelchior-NOAA, apologies, I wrote the confirmation but did not "send":

The three jobs have no hits for the issue 61 warning described in the issues document.  I have no concerns with finishing up this PR.

**Comment by ShelleyMelchior-NOAA** [comment]
> Hi @ShelleyMelchior-NOAA, apologies, I wrote the confirmation but did not "send":

Oooops! 🙊

Can you also please do a sync fork! Then I will merge the PR.

**Comment by MarcelCaron-NOAA** [comment]
synced 👍

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Tests yield expected results. This PR is approved for merge.

**Pull request merged**
