### PR TITLE
Update rtofs j-job, module files modified to work with ecflow workflow

### PR DESCRIPTION
**Pull request by lgannoaa**
GitHub #179 

Tested in development ecflow workflow. Result checked by team member.
JEVS_RTOFS_PREP and JEVS_RTOFS_STATS are using dcom from dev location as application logic currently used.
Rename module file because the model name is indicated in directory assignment.
Module prod_envir should not be loaded in module file. It should load before calling J-Job. Because loading this module will reset some necessary environment setting established from the top level of the workflow.

- [Yes] Has the code been checked to ensure that no errors occur during the execution?

## Pull Request Checklist ##

- [X] Complete the PR description above.
- [X] Ensure the PR title matches the feature branch name.
- [X]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [X]  Check to see that the output directory structure is followed
- [X]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [X] After submitting the PR, select **Development** issue with the original issue number.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
Hi @lgannoaa  -- please update branch `feature/evs-179` with the auth EVS develop.

**Comment by lgannoaa** [comment]
Hi @ShelleyMelchior-NOAA , done with merge upstream.

**Comment by ShelleyMelchior-NOAA** [comment]
I ran RTOFS prep and stats processing and the expected prep and stats files are generated.

Re: ` module load prod_envir/${prod_envir_ver}`, a follow on PR will update the driver scripts to include the prod_envir module loading.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
This PR is approved for merge.

**Pull request merged**
