### PR TITLE
feature/global_det_atmos_g2o_sfc_img_reduce

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- These changes drastically reduce the number of images produced by the grid2obs sfc plots jobs; it adjusts the resources used as well

- [ ] Describe testing already performed for this Pull Request:</br>

> Ran the ecf scripts

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> Checkout the branch
> Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_128/evs_global_det_atmos_set_up.sh. This script will link the fix files.
> Copy /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test_scripts/pr_128/run_evs_global_det_atmos_plots.sh. Run it. 

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **06/15/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by malloryprow** [comment]
I had been looking at the parallel log files and saw that some of the jobs had the "memory exceeded" errors, so I bumped up the memory defined in the ecf scripts.

**Comment by AliciaBentley-NOAA** [comment]
Thanks for bumping up the requested memory in the ecf scripts, Mallory! Have those updates been working in your own space since the memory increase? Is this PR in a good place for Perry or Shelley to test?

**Comment by malloryprow** [comment]
Yup! All good!

**Comment by PerryShafran-NOAA** [comment]
I'll go ahead and pick it up in a few.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

Two of your plot scripts went over the wall clock time.  Looks like we'll need to expand the wall clock time again?

Thanks!

Perry

**Comment by malloryprow** [comment]
Sure!

**Comment by PerryShafran-NOAA** [comment]
OK, cool.  

Perry

**Comment by malloryprow** [comment]
I see the 31 day tar files in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/global_det/atmos.20230605. They match my tar files, so I'm fine with calling this one good! 👍 

Additionally, one minor tweak that won't effect the run. I ran my jobs this morning setting VDATE_START and VDATE_END variables in my ecf script to match what you ran yesterday. I noticed the output went to /lfs/h2/emc/vpppg/noscrub/mallory.row/evs_global_det_atmos_test/dev/com/evs/v1.0/plots/global_det/atmos.20230606, which didn't match the date in the tar files evs.plots.global_det.atmos.grid2obs_sfc.last31days.v20230605.tar.

I changed the COMOUT path from being $RUN.$PDYm1 to $RUN.$VDATE_END

**Comment by PerryShafran-NOAA** [comment]
Hi, Mallory,

Do you want to run it again just in case?

Thanks!

Perry

**Comment by malloryprow** [comment]
@PerryShafran-NOAA Sure! Do we just want to do the 31 day jobs?

**Comment by PerryShafran-NOAA** [comment]
Let's just do all the jobs.

Perry

**Comment by malloryprow** [comment]
Okay! I have the Developing Frontline Leaders session starting here in 10 min. I'll run by jobs after and then can check the output with yours when it is over.

**Comment by PerryShafran-NOAA** [comment]
The plot jobs have finished.

**Comment by malloryprow** [comment]
Looks good to me! 👍

**Comment by malloryprow** [comment]
Once this gets in the parallel the space it uses will be less, and resources for the job will be less so the EVS-DEV high-water mark chart will look different. :D

**Comment by PerryShafran-NOAA** [comment]
Good news, thanks!

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]

**Pull request merged**
