### PR TITLE
feature/cam_precip

### PR DESCRIPTION
**Pull request by MarcelCaron-NOAA**
## Pull Request Testing ##

- [x] Describe testing already performed for this Pull Request:</br>

> 
> Testing:
> 
> - Submitted concurrent runs for multiple models that avoid IO-type errors
> - Submitted runs for multiple dates
> - Verified output files and directories are created automatically
> - Verified output statistics for completion and correctness by plotting them according to EVS graphics needs
> - Submitted graphics prototypes for review and received approval from Geoff Manikin and Logan Dawson

> Outcome: Job submission files for prep and stats steps are submitted in order, yielding prepared observation data and stat files for each model and verification domain without errors (as long as input data are available).  

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

> To run EVS/CAM/precip verification up to stat file generation, first run the following on the command line:
> ```
> qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/prep/jevs_hireswarw_precip_prep.ecf
> qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/prep/jevs_hireswarwmem2_precip_prep.ecf
> qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/prep/jevs_hireswfv3_precip_prep.ecf
> qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/prep/jevs_namnest_precip_prep.ecf
> qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/prep/jevs_hrrr_precip_prep.ecf
> ```
> 
> These prep jobs should take about 1 minute to complete.  Then execute the following on the command line:
> ```
> qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/stats/jevs_hireswarw_precip_stats.ecf
> qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/stats/jevs_hireswarwmem2_precip_stats.ecf
> qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/stats/jevs_hireswfv3_precip_stats.ecf
> qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/stats/jevs_namnest_precip_stats.ecf
> qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/stats/jevs_hrrr_precip_stats.ecf
> ```
> 
> Stats jobs will take between 45 minutes (HiResWs ARW and ARW2) and 3 hours (HRRR) to complete.  After stats jobs are complete, output stat files should be available here:
> `/lfs/h2/emc/ptmp/$USER/EVS_out/com/evs/v1.0/stats/cam/atmos/$MODEL.${valid?fmt=%Y%m%d}/`
> 
> The valid date will be yesterday's date.  If the stat files are not available, then model and/or observation data were likely missing (barring other unexpected errors).

- [x] Do these updates/additions include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

> Yes

- [x] Do these updates/additions include sufficient testing updates? **[Yes or No]**

> Yes

- [x] Please complete this pull request review by **10/15/2022**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR description above.
- [x] Ensure the PR title matches the feature branch name.
- [x] Check the following:
- [x]  Instructions provided on how to run
- [x]  Developer's name is replaced by ${user} where necessary throughout the code
- [x]  Check that the ecf file has all the proper definitions of variables
- [x]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables

> NOTE: COMINccpa, COMINmrms, and COMOUT are currently defined without using compath.py.  This is because the operational EVS output directory was not used during development or testing.  However, the in-ops definitions are included in this pull request as comments.  These comments exist in the following files:
```
/lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/jobs/cam/prep/JEVS_CAM_PREP
/lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/jobs/cam/stats/JEVS_CAM_STATS
```

- [x]  Check to see that the output directory structure is followed
- [x]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, Marcel,

One item that should be changed:  NCO production likes to have their directory names in formats that look like this:

export HOMEevs=/lfs/h2/emc/vpppg/save/perry.shafran/EVS
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}

You should change these directory names to be these, rather than your directory names:

export EVS_PARM_DIR=$EVS_HOME_DIR/parm
export EVS_USH_DIR=$EVS_HOME_DIR/ush
export EVS_EXEC_DIR=$EVS_HOME_DIR/exec
export EVS_FIX_DIR=$EVS_HOME_DIR/fix
export EVS_SCRIPTS_DIR=$EVS_HOME_DIR/scripts

Please make these changes and post to your feature branch.  Let me know when this is done and I'll start the review.

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
> Please make these changes and post to your feature branch. Let me know when this is done and I'll start the review.

Hi Perry:  I replaced occurrences of EVS directory names with the corresponding NCO production format.  The updates have been pushed to my feature branch.
Thanks,
-Marcel

**Comment by PerryShafran-NOAA** [comment]
Thank you!  Also be sure that you present all your graphics to Geoff and Logan, and let me know when they have been approved.  If they already have been approved, then let me know that.  

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
> Thank you! Also be sure that you present all your graphics to Geoff and Logan, and let me know when they have been approved. If they already have been approved, then let me know that.

Perry--yes, graphics prototypes for these stats have been reviewed and approved by Geoff and Logan.

**Comment by PerryShafran-NOAA** [comment]
Thank you, then I'll start reviewing at my earliest chance!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Thank you Perry!

**Comment by PerryShafran-NOAA** [comment]
Hi, Marcel,

I started with running the prep step, for both the namnest and the hrrr, and found similar errors for each:

```
555 + compath.py -o evs/v1.0
$COMROOT is not defined. Please define it or load the prod_envir module.
55 + export COMIN=
55 + COMIN=
```

And later on in the output file:

```
BEGIN: cam_prep_precip_create_job_script.py
ERROR: Found no matches for /lfs/h1/ops/prod/com/ccpa/v4.2/ccpa.20221003/*/ccpa.t13z.01h.hrap.conus.gb2. Cannot copy necessary data into the prep archive.
77 + export err=1
77 + err=1
77 + err_chk

-------------------------------------------------------------
-- FATAL ERROR: Job jevs_hrrr_precip_prep.15299807.cbqs01 failed RETURN CODE 1
-- ABNORMAL EXIT at Tue Oct  4 13:04:04 UTC 2022 on clogin01
-------------------------------------------------------------
```

See both .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/prep

Can you have a look and make fixes where need be?

Thanks!

Perry

**Comment by PerryShafran-NOAA** [comment]
I have moved the .o files to a different directory so I can begin processing another pull request.

That directory is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_marcel 

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi Perry.  I made some changes and pushed the updated code to feature/CAM_precip.

Details:  

- I added a module load statement for prod_envir/2.0.8, which will define COMROOT.  
- The second issue you brought up is because many CCPA obs are only available later in the day.  A run in the evening would likely work without error.  However, I changed the verification date from {TODAY minus 1 day} to {TODAY minus 2 days}, which worked fine in my tests, as the code should have access to all the necessary CCPA obs.

Thanks,
-Marcel

**Comment by PerryShafran-NOAA** [comment]
Hi, Marcel,

Thank you.  Hopefully this will work this time.  I'll work on this soon.

Thanks!

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Marcel,

I have errors in the stats job for HRRR.  Please take a look at /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS_marcel/ecf/cam/stats/jevs_hrrr_precip_stats.o15324594 and search for the word "ERROR" (all caps).  Seems like there is a problem in the pcpcombine job looking for mrms files for Alaska?  Please take a look into this.

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi Perry:

Apologies that the code isn't running cleanly.  I think the issue has to do with the availability of all necessary analysis data at the time of code execution.  The two analysis datasets (CCPA and MRMS) are only concurrently available for a short amount of time, and their availability is very sensitive to the valid date and the time of code execution:  

1. The error you pointed out a few days ago ("could not find CCPA file") happened because the valid date was set to "yesterday", and some CCPA files for that time weren't yet available on WCOSS2.  
2. Then I changed the valid date to a day earlier to catch CCPA data, and the error you are getting now happened because MRMS were no longer available; they'd already been scrubbed.  

These errors can be resolved if I reset the valid date to "yesterday" and the code is tested in the evening (~21Z) when CCPA data become available, but a better solution may be to edit the code to pull from HPSS any scrubbed data.  **What do you think**?

**Comment by PerryShafran-NOAA** [comment]
Sorry for delays in this.  Perhaps it would be good to pull all the data that is needed for a single run, and then edit your code to point to that data.  That will at least provide the concept that the code is working for all data types.  If you could do that and let me know, I'll bring those changes in and test the code.

I think once that's done, we can merge.

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Perry:

The most recent commits include three changes:

1. the updated prep script uses "yesterday" as the valid date
2. the updated stats script uses "20221011" as the valid date, for testing
3. the stats jobs point COMINccpa and COMINmrms to a marcel.caron directory with archived prep data, for testing.  

If you submit the stats jobs: 
`qsub EVS/ecf/cam/stats/jevs_{MODELNAME}_precip_stats.ecf `
... they should run cleanly.

Logan suggested (if I understood correctly) that I change the prep code to prepare observation data in batches, say every 6 hours, then run the prep code soon after each batch becomes available on WCOSS2, and then run the stats code at the end of the day.  That way all prepared observation data are available at the same time for the stats jobs.  Do you want the associated edits included in this pull request?

**Comment by PerryShafran-NOAA** [comment]
Yes please.  Then please resend the instructions needed to run it in this manner.  

How do you intend this to be run in production?

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Okay will do.  

My plan is that the prep step runs four times a day, followed by the stats step.  I will conduct a test tomorrow using the cron, and if the test is successful I'll push any changes to my feature branch and will update this thread with new instructions for running the code.

-Marcel

**Comment by MarcelCaron-NOAA** [comment]
Perry:

I tested the CAM/precip component the following way and it completed cleanly:

- Submit the same prep job for each model at 00:30Z, 06:30Z, 12:30Z, and 18:30Z
- Submit the stats job for each model at 19:00Z

For testing, my crontab on WCOSS2 looked like this:
```
30 0,6,12,18 13 10 * qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/prep/jevs_hireswarw_precip_prep.ecf >> /lfs/h2/emc/stmp/marcel.caron/cron.out/test_jevs_hireswarw_precip_prep.out 2>&1
30 0,6,12,18 13 10 * qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/prep/jevs_hireswarwmem2_precip_prep.ecf >> /lfs/h2/emc/stmp/marcel.caron/cron.out/test_jevs_hireswarwmem2_precip_prep.out 2>&1
30 0,6,12,18 13 10 * qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/prep/jevs_hireswfv3_precip_prep.ecf >> /lfs/h2/emc/stmp/marcel.caron/cron.out/test_jevs_hireswfv3_precip_prep.out 2>&1
30 0,6,12,18 13 10 * qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/prep/jevs_hrrr_precip_prep.ecf >> /lfs/h2/emc/stmp/marcel.caron/cron.out/test_jevs_hrrr_precip_prep.out 2>&1
30 0,6,12,18 13 10 * qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/prep/jevs_namnest_precip_prep.ecf >> /lfs/h2/emc/stmp/marcel.caron/cron.out/test_jevs_namnest_precip_prep.out 2>&1
0 19 13 10 * qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/stats/jevs_hireswarw_precip_stats.ecf >> /lfs/h2/emc/stmp/marcel.caron/cron.out/test_jevs_hireswarw_precip_stats.out 2>&1
0 19 13 10 * qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/stats/jevs_hireswarwmem2_precip_stats.ecf >> /lfs/h2/emc/stmp/marcel.caron/cron.out/test_jevs_hireswarwmem2_precip_stats.out 2>&1
0 19 13 10 * qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/stats/jevs_hireswfv3_precip_stats.ecf >> /lfs/h2/emc/stmp/marcel.caron/cron.out/test_jevs_hireswfv3_precip_stats.out 2>&1
0 19 13 10 * qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/stats/jevs_hrrr_precip_stats.ecf >> /lfs/h2/emc/stmp/marcel.caron/cron.out/test_jevs_hrrr_precip_stats.out 2>&1
0 19 13 10 * qsub /lfs/h2/emc/vpppg/noscrub/marcel.caron/EVS/ecf/cam/stats/jevs_namnest_precip_stats.ecf >> /lfs/h2/emc/stmp/marcel.caron/cron.out/test_jevs_namnest_precip_stats.out 2>&1
```

**Comment by PerryShafran-NOAA** [comment]
OK, great!  Are you saying that your code is now ready for review?

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Perry:

Ah, yes, I forgot to add that; the code is ready for review.  Please test the code using the directions in my previous comment (four prep runs 6 hours apart, and one stats run 30 minutes after the last prep run) to ensure a clean run.  Thanks!

**Comment by PerryShafran-NOAA** [comment]
OK, so I have to run these at specific times, not just whenever I am testing it. Good to know!  I'll set that up first thing next week, then have you look at the stat files to tell me that the files created are as expected.

Thanks!

Perry

**Comment by PerryShafran-NOAA** [comment]
I had issues because the standard out and standard error files were being written to my home directory, filling up the quota for my home directory.  Is it possible for you to set up your prep files to ensure that the stdout and stderr are being written to stmp?  I had to turn off the cron because I didn't want to have quota issues overnight.  

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi Perry:

Sure, I've changed the stdout and stderror paths to point to your stmp directory.  There should be no changes necessary to the updated feature branch to run it.  Let me know how that works.

Thanks,
-Marcel

**Comment by PerryShafran-NOAA** [comment]
Thank you Marcel!  I'll try this now and see if it works.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, @MarcelCaron-NOAA ,

Just so you know, since this is in cron, and I was off on Friday, I'm getting this set to run tomorrow so it can run from start to finish, and I can see the results.  I will be reporting on this tomorrow.  

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Marcel,

I think there are problems.  I have the following in my crontab:

```
30 0,6,12,18 25 10 * qsub /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/prep/jevs_hireswarw_precip_prep.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hireswarw_precip_prep.out 2>&1
30 0,6,12,18 25 10 * qsub /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/prep/jevs_hireswarwmem2_precip_prep.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hireswarwmem2_precip_prep.out 2>&1
30 0,6,12,18 25 10 * qsub /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/prep/jevs_hireswfv3_precip_prep.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hireswfv3_precip_prep.out 2>&1
30 0,6,12,18 25 10 * qsub /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/prep/jevs_hrrr_precip_prep.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hrrr_precip_prep.out 2>&1
30 0,6,12,18 25 10 * qsub /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/prep/jevs_namnest_precip_prep.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_namnest_precip_prep.out 2>&1
0 19 25 10 * qsub /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/stats/jevs_hireswarw_precip_stats.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hireswarw_precip_stats.out 2>&1
0 19 25 10 * qsub /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/stats/jevs_hireswarwmem2_precip_stats.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hireswarwmem2_precip_stats.out 2>&1
0 19 25 10 * qsub /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/stats/jevs_hireswfv3_precip_stats.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hireswfv3_precip_stats.out 2>&1
0 19 25 10 * qsub /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/stats/jevs_hrrr_precip_stats.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hrrr_precip_stats.out 2>&1
0 19 25 10 * qsub /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/stats/jevs_namnest_precip_stats.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_namnest_precip_stats.out 2>&1

```

Yet I see nothing in the cron.out directory.  I thought I had my cron set up correctly, but maybe not? I'm at a loss here.  This works in cron for you?

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi Perry:

I ran the qsub command outside of cron and it looks like the "PBS -N" entry in each ecf file is "illegal" because it includes forward slashes, which is why it isn't submitting for you.  I changed this entry to something that works, pushed the change to Github, and I'm rerunning the updated scripts in the cron myself this afternoon.  I will update this thread once that is complete.

Thanks,
-Marcel

**Comment by MarcelCaron-NOAA** [comment]
Perry:

The change I mentioned above worked for me, and should allow the crontab method to work for you.  Once the changes are pulled to your noscrub clone of the EVS, the only changes necessary will be in your crontab.  

Here is my current crontab, but I replaced my name with your name so that you can just copy and paste the lines:

```
30 0,6,12,18 * 10 * qsub -o /lfs/h2/emc/stmp/perry.shafran/jevs_hireswarw_precip_prep.out /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/prep/jevs_hireswarw_precip_prep.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hireswarw_precip_prep.out 2>&1
30 0,6,12,18 * 10 * qsub -o /lfs/h2/emc/stmp/perry.shafran/jevs_hireswarwmem2_precip_prep.out /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/prep/jevs_hireswarwmem2_precip_prep.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hireswarwmem2_precip_prep.out 2>&1
30 0,6,12,18 * 10 * qsub -o /lfs/h2/emc/stmp/perry.shafran/jevs_hireswfv3_precip_prep.out /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/prep/jevs_hireswfv3_precip_prep.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hireswfv3_precip_prep.out 2>&1
30 0,6,12,18 * 10 * qsub -o /lfs/h2/emc/stmp/perry.shafran/jevs_hrrr_precip_prep.out /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/prep/jevs_hrrr_precip_prep.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hrrr_precip_prep.out 2>&1
30 0,6,12,18 * 10 * qsub -o /lfs/h2/emc/stmp/perry.shafran/jevs_namnest_precip_prep.out /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/prep/jevs_namnest_precip_prep.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_namnest_precip_prep.out 2>&1
0 19 * 10 * qsub -o /lfs/h2/emc/stmp/perry.shafran/jevs_hireswarw_precip_stats.out /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/stats/jevs_hireswarw_precip_stats.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hireswarw_precip_stats.out 2>&1
0 19 * 10 * qsub -o /lfs/h2/emc/stmp/perry.shafran/jevs_hireswarwmem2_precip_stats.out /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/stats/jevs_hireswarwmem2_precip_stats.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hireswarwmem2_precip_stats.out 2>&1
0 19 * 10 * qsub -o /lfs/h2/emc/stmp/perry.shafran/jevs_hireswfv3_precip_stats.out /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/stats/jevs_hireswfv3_precip_stats.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hireswfv3_precip_stats.out 2>&1
0 19 * 10 * qsub -o /lfs/h2/emc/stmp/perry.shafran/jevs_hrrr_precip_stats.out /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/stats/jevs_hrrr_precip_stats.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_hrrr_precip_stats.out 2>&1
0 19 * 10 * qsub -o /lfs/h2/emc/stmp/perry.shafran/jevs_namnest_precip_stats.out /lfs/h2/emc/vpppg/noscrub/perry.shafran/EVS/ecf/cam/stats/jevs_namnest_precip_stats.ecf >> /lfs/h2/emc/stmp/perry.shafran/cron.out/test_jevs_namnest_precip_stats.out 2>&1
```

Let me know if there are any other issues.  

Thanks. 
-Marcel

**Comment by PerryShafran-NOAA** [comment]
Hi, Marcel,

Thanks!  I'll set this up and see what happens.

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, @MarcelCaron-NOAA ,

Your prep steps are running.  However, seeing some concerning statements in all the stdout files:

`WARNING: Found no matches for /lfs/h1/ops/prod/com/ccpa/v4.2/ccpa.20221025/*/ccpa.t15z.01h.hrap.conus.gb2. Cannot copy necessary data into the prep archive ... Continuing to the next valid datetime.`

I am seeing this in all your output files (which is probably why they are such enormous files)  See all the output files here:  /lfs/h2/emc/stmp/perry.shafran

I would probably recommend you setting VDATE to PDYm2 in order to run this.  Though I think you said that by doing so doesn't help your access to MRMS data?  I'm looking at the ccpa.20221025 directory, and it seems to be filling up with data today, so the ccpa directories seem to be available at PDYm2.  

Can we check this and let me know when it's fixed?

Thanks!

Perry

**Comment by PerryShafran-NOAA** [comment]
Also another thing I've noticed is that in my qstat report now, I see that the runs from 06Z have not finished - they have been running for 8 hours, while the runs from 12Z have been running for 2 hours.  So having two cycles from two time periods running at the same time could cause problems.  It would be good to have output files that are labelled for the cycle it is running so I can differentiate.

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi Perry:

It's concerning that the scripts are taking 8+ hours to complete.  The prep step should really only take a minute or two ... **I will check the output files you mentioned**. 

Otherwise, **the WARNING message itself is  expected output**.  The t15z CCPA file is not yet available (as is shown by running `ls /lfs/h1/ops/prod/com/ccpa/v4.2/ccpa.20221025/*/ccpa.t15z.01h.hrap.conus.gb2`).  The prep workflow included grabbing all the observation data that were available at 0Z, 6Z, and 12Z; and the same workflow will run again at 18Z to grab what remains.  

This type of WARNING used to be an ERROR and would cause the workflow to fail if a file like the one you mentioned was not found, but because of timing mismatches in necessary MRMS and CCPA data, Logan suggested grabbing data (i.e. running the prep step) several times over the course of the day before running the stats step, so I've changed this to a WARNING, allowing the script to "succeed" even if all of the necessary observation files were not found during a single run.

-Marcel

**Comment by MarcelCaron-NOAA** [comment]
There is an infinite loop:  the WARNING message outputs, and the loop skips the increment expression, restarting without the increment.  I've added an increment expression after the WARNING message to update the loop correctly.  I will run the cron job myself to make sure this feature is working correctly.  

Thanks for catching this!
-Marcel

**Comment by PerryShafran-NOAA** [comment]
Marcel - please be sure that you merge in the authoritative develop branch before I can continue.  Because I merged a PR, you have to pull that in.

**Comment by PerryShafran-NOAA** [comment]
Marcel - thanks!  Looks like there aren't any conflicts anymore.

**Comment by PerryShafran-NOAA** [comment]
I am setting up the crons so the jobs run tomorrow.  I will let you know if there are any further problems.

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi Perry:

Thanks!  The prep step ran correctly via my cron today, and so I think it's safe to for you to test once again.  No changes necessary (aside from updating the feature branch!)

**Comment by PerryShafran-NOAA** [comment]
Hi, Marcel,

Please take a look at the output files in /lfs/h2/emc/stmp/perry.shafran and tell me if this is what you expect.  The size of these files is still very large and I wanted to see if this is what you expect.  I think some of the old output is there.

Can you show me where I can see the output of prep - the products that come out of your prep step?  That would help me diagnose that things are working.

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi Perry:

Did you happen to delete the old output files?  If not, those are probably output for both the current run and the previous run, since the output files are not overwritten.  Looking at one of those large files, the final run was about 500kB of output data, which is closer to the expected size.

The prep step seems to have been working correctly so far, having grabbed most of the ccpa data and all of the mrms data that are needed.  

Those data can be found in these folders:
```
/lfs/h2/emc/ptmp/perry.shafran/EVS_out/com/evs/v1.0/prep/cam/atmos/ccpa.20221026
/lfs/h2/emc/ptmp/perry.shafran/EVS_out/com/evs/v1.0/prep/cam/atmos/ccpa.20221027
/lfs/h2/emc/ptmp/perry.shafran/EVS_out/com/evs/v1.0/prep/cam/atmos/mrms.20221026
/lfs/h2/emc/ptmp/perry.shafran/EVS_out/com/evs/v1.0/prep/cam/atmos/mrms.20221027
```

The missing ccpa data are not yet available on WCOSS2, but will be available before the 18:30Z prep cycle, after which the stats cycle should be able to complete cleanly.  

Here is where the stats output should end up later in the day:
`/lfs/h2/emc/ptmp/perry.shafran/EVS_out/com/evs/v1.0/stats/cam/atmos/`

Thanks,
-Marcel

**Comment by PerryShafran-NOAA** [comment]
Excellent, thanks!  Will continue to monitor for the stats files, but good to hear that the prep step is working OK for now.  

Thanks so much!  Feels like we're close to wrapping this one up, but will see later today.

Perry

**Comment by PerryShafran-NOAA** [comment]
Hi, Marcel,

Since your stuff is in cron, it has been running over the weekend.  Please take a look at the data in /lfs/h2/emc/ptmp/perry.shafran/EVS_out/com/evs/v1.0/stats/cam/atmos and let me know if that is data that you would expect.  I'll take one last look at your code to see if everything is in compliance, and then we should consider your code approved once all this is done!

Thanks!

Perry

**Comment by MarcelCaron-NOAA** [comment]
Hi Perry:

It looks like all the expected data have been saved to that folder over the weekend.  The first jobs ran on 10/28 for valid date 10/27, and having had three days to run in the cron, I'm seeing 3 days (10/27-29) of ccpa (CONUS) and mrms (Alaska) data for all five deterministic CAMs.  The content of the files looks good to me at a glance.

Thanks,
-Marcel

**Comment by PerryShafran-NOAA** [comment]
OK great!  In that case, we will merge this pull request today.  Thanks, and great work!

Perry

**Pull request merged**
