### PR TITLE
feature/global_ens_prmsl_plots_bugfix: Bugfix for units mismatch between prmsl plots and plot labels

### PR DESCRIPTION
**Pull request by StevenSimon-NOAA**
feature/global_ens_prmsl_plots_bugfix: Bugfix for units mismatch between g2g and g2o prmsl plots and plot labels

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

Identified the source of the global_ens g2g and g2o prmsl plots (Pa) and plot labels (hPa) mismatch in line 3893 /lfs/h2/emc/vpppg/noscrub/emc.vpppg/EVS/ush/global_ens/ush_gens_plot_py/settings.py. There was a missing "return hPa_vals" command in the user function for Pa-to-hPa units conversions. This bugfix will allow the Pa-to-hPa units conversion to be implemented. Additional units mismatches between plotted global_ens stats data and plots labels were also identified. Thus, the proposed global_ens plots bugfix will address units conversions for the following six fields:

1. prmsl (Pa to hPa)

2. ugrd and vgrd (m/s to kts)

3. ugrd_10 and vgrd_10 (m/s to kts)

4.  dpt_2m (K to F)

5. temp_2m (K to F)

6. sst (K to F)
 

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run the following global_ens plot drivers with COMIN using emc.vpppg as USER in its path:

jevs_global_ens_atmos_gefs_grid2grid_past31days_plots.sh
jevs_global_ens_atmos_gefs_grid2grid_past90days_plots.sh
jevs_global_ens_atmos_gefs_grid2obs_past31days_plots.sh
jevs_global_ens_atmos_gefs_grid2obs_past90days_plots.sh
jevs_global_ens_atmos_gefs_grid2obs_past31days_separate_plots.sh
jevs_global_ens_atmos_gefs_grid2obs_past90days_separate_plots.sh
jevs_global_ens_atmos_gefs_profile1_past31days_plots.sh
jevs_global_ens_atmos_gefs_profile1_past90days_plots.sh
jevs_global_ens_atmos_gefs_profile2_past31days_plots.sh
jevs_global_ens_atmos_gefs_profile2_past90days_plots.sh
jevs_global_ens_atmos_gefs_profile3_past31days_plots.sh
jevs_global_ens_atmos_gefs_profile3_past90days_plots.sh
jevs_global_ens_atmos_gefs_profile4_past31days_plots.sh
jevs_global_ens_atmos_gefs_profile4_past90days_plots.sh
jevs_global_ens_atmos_gefs_sst_past31days_plots.sh
jevs_global_ens_atmos_gefs_sst_past90days_plots.sh
jevs_global_ens_atmos_naefs_grid2grid_past31days_plots.sh
jevs_global_ens_atmos_naefs_grid2grid_past90days_plots.sh
jevs_global_ens_atmos_naefs_grid2obs_past31days_plots.sh
jevs_global_ens_atmos_naefs_grid2obs_past90days_plots.sh

Unzip the generated tar files in the user COMOUT.

Review the g2g and g2o prmsl, u/v wind, 10-m u/v wind, 2-m dpt, 2-m temp, and sst plots for mean error and mean absolute error and/or rmse and spread and confirm that the plotted data are in the correct order of magnitude following unit conversion.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

Not yet, but no errors are anticipated given this bugfix.

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

Yes

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

Summary: The proposed bugfix will align the plotted global_ens stats data with the existing plot labels for the following fields:

1. prmsl (Pa to hPa)

2. ugrd and vgrd (m/s to kts)

3. ugrd_10 and vgrd_10 (m/s to kts)

4.  dpt_2m (K to F)

5. temp_2m (K to F)

6. sst (K to F)

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
I have cloned your fork and checked out branch `feature/global_ens_prmsl_plots_bugfix`.
The 4 drivers have been set up to run from my user environment and have been submitted.
logfiles are in: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out`
```
-rw-r--r-- 1 shelley.melchior emc     1790729 Nov 21 17:25 jevs_global_ens_atmos_gefs_grid2grid_past31days_plots.o93843392
-rw-r--r-- 1 shelley.melchior emc      757872 Nov 21 17:25 jevs_global_ens_atmos_gefs_grid2obs_past31days_plots.o93843395
-rw-r--r-- 1 shelley.melchior emc      761000 Nov 21 17:25 jevs_global_ens_atmos_gefs_grid2obs_past90days_plots.o93843396
-rw-r--r-- 1 shelley.melchior emc     1528968 Nov 21 17:25 jevs_global_ens_atmos_gefs_grid2grid_past90days_plots.o93843393
```

**Comment by ShelleyMelchior-NOAA** [comment]
I pulled in the changes and have kicked off ALL global_ens plotting drivers. There are a lot of log files b/c I accidentally kicked off all of the plots drivers **BEFORE** pulling in the changes. 😨  The re-run has the changes and they are presently processing.
COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/global_ens/atmos.20231120`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_ens_*_plots.o93941*` (those should be the log files that cover the re-runs that have the changes)

**Comment by StevenSimon-NOAA** [comment]
> I pulled in the changes and have kicked off ALL global_ens plotting drivers. There are a lot of log files b/c I accidentally kicked off all of the plots drivers **BEFORE** pulling in the changes. 😨 The re-run has the changes and they are presently processing. COMOUT=`/lfs/h2/emc/ptmp/shelley.melchior/evs/v1.0/plots/global_ens/atmos.20231120` logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_ens_*_plots.o93941*` (those should be the log files that cover the re-runs that have the changes)

All plot tar files and pngs per tar file are fully accounted for by quantity. Next, I will review the plots to verify the unit conversions and associated plot filenames.

**Comment by AliciaBentley-NOAA** [comment]
@StevenSimon-NOAA @MarcelCaron-NOAA @ShelleyMelchior-NOAA Thanks for all the updates that got us to a better place with global_ens plots! How are things looking on this PR? Pretty good? Any issues?

**Comment by MarcelCaron-NOAA** [comment]
@AliciaBentley-NOAA @ShelleyMelchior-NOAA 
Yes one more issue.  Steven identified that unit conversion for profile4 plots was not happening.  I found the bug and fixed; a few lines weren't indented correctly in the vertprof plotting script.  

@StevenSimon-NOAA is checking plots now.  If he finds no other issues, and after he pushes the fix, I think we can test profile4 once more.  Hopefully that will be it for this PR!

**Comment by AliciaBentley-NOAA** [comment]
@MarcelCaron-NOAA @StevenSimon-NOAA @ShelleyMelchior-NOAA Please double check which conversions should be happening in profile4. This is an email from Geoff in September:

```
Hi Marcel and Steve-

        We've been getting feedback from EVS evaluators about consistency with the temperature stat units across components.  

      Marcel, you're using degrees F for all of the CAM/regional stats.    We're good with using F for the 2-m temperature stats, but the vertical profile temperature stats should use K.   

           Can you please make that change to the CAM and regional 2m temperature plots and submit PRs?  No changes are needed to the stat files, and the 2m temperature plots are fine.  Thank you!

            Steve, can you please change the upper air temperature plots to use K as the units and then submit a PR?   Thank you!

                       -Geoff
```

**Comment by StevenSimon-NOAA** [comment]
> @MarcelCaron-NOAA @StevenSimon-NOAA @ShelleyMelchior-NOAA Please double check which conversions should be happening in profile4. This is an email from Geoff in September:
> 
> ```
> Hi Marcel and Steve-
> 
>         We've been getting feedback from EVS evaluators about consistency with the temperature stat units across components.  
> 
>       Marcel, you're using degrees F for all of the CAM/regional stats.    We're good with using F for the 2-m temperature stats, but the vertical profile temperature stats should use K.   
> 
>            Can you please make that change to the CAM and regional 2m temperature plots and submit PRs?  No changes are needed to the stat files, and the 2m temperature plots are fine.  Thank you!
> 
>             Steve, can you please change the upper air temperature plots to use K as the units and then submit a PR?   Thank you!
> 
>                        -Geoff
> ```

The vertical temp profile plots are all in Kelvin units.

**Comment by StevenSimon-NOAA** [comment]
I finished my review of the updated global_ens plots. Based on the updated sample I viewed and compared against the existing global_ens plots, all expected unit conversions were carried out across the following fields for the applicable metrics:

1. prmsl (Pa to hPa)

2. ugrd and vgrd (m/s to kts)

3. ugrd_10 and vgrd_10 (m/s to kts)

4. dpt_2m (K to F)

5. temp_2m (K to F)

6. sst (K to F)

Furthermore, all threshold associated fields (precip, snowfall, sea-ice, and CAPE) are now properly represented in their png plot filenames (thresholds are now with the correct precision). 

At your earliest convenience and following final review, please merge this PR.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Changes look good. Tests yield expected results. This PR is approved for merge.

**Pull request merged**
