### PR TITLE
bugfix/imd_corrupt

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

Sometimes the IMD forecast files come in with non-zero file sized, but are corrupt. The files are saved in prep, but when the corrupt files are run by METplus the jobs fails. This adds a check for the IMD files to make sure they are not corrupt before putting them into the prep archive.

- [ ] Describe testing already performed for this Pull Request:</br>
> The changes were tested for INITIDATE=20240411, which contains a few corrupt files in dcom. For INITDATE=20240411 with the changes the corrupted files did not get saved by prep. I also tested for INITDATE=20240416 which does not have any corrupt files and the output matched production.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

>  ###  **Set-up**
> 1. Clone my fork and checkout branch bugfix/imd_corrupt
> 2. `ln -sf /lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix fix`
> 3. `cd sorc; ./build.sh`

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **04/25/2024**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I am starting your PR, starting with the first test of INITDATE=20240416.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Your first test is complete.

See the .o file here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr469test/EVS/dev/drivers/scripts/prep/global_det

And the prep output is here:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det/atmos.20240416

I'll await your verdict on this test before I start the 2nd test.

**Comment by malloryprow** [comment]
Log looks good (only WARNING messages are for missing data in dcom), and the output matches that in production.

✅ Good for test 1!

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Great!  Moving on to the second test for INITDATE of 20240411.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow Looks like the second run has completed also.  Please take a look at the results here, please.

**Comment by malloryprow** [comment]
Log is good, and I see the corrupt files imd.t12z.f198, imd.t12z.f156, imd.t12z.f120, imd.t12z.f042, and imd.t12z.f006 are not in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/global_det/atmos.20240411/imd, which is what we want (not archiving corrupt IMD files in prep anymore).

✅ Test 2 is good so that means the PR is good to go ✅

@AliciaBentley-NOAA @ShelleyMelchior-NOAA @PerryShafran-NOAA, feel free to look over if you want but this PR has the thumbs up from me.

**Comment by PerryShafran-NOAA** [comment]
@malloryprow I think everything looks good and is in good shape.  Thanks for working on this so quickly!

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
