### PR TITLE
Feature/ee2 rev5 rtofs

### PR DESCRIPTION
**Pull request by SamiraArdani-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
This PR fixes the syntax errors that occur due to missing the observational data.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
clone my EVS repository in your local, then find the driver scripts located at: EVS/dev/drivers/scripts
To test the stats scripts for SMOS, AVISO and GHRSST, please run:
dev/drivers/scripts/stats/rtofs/jevs_rtofs_smos_stats.sh
dev/drivers/scripts/stats/rtofs/jevs_rtofs_ghrsst_stats.sh
dev/drivers/scripts/stats/rtofs/jevs_rtofs_aviso_stats.sh
Since ARGO, NDBC and OSI-SAF obs data need preparation, we need to test the prep script for them. To do so, please run:
/dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.sh

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, @SamiraArdani-NOAA 

I am running the prep job already (as suggested by @ShelleyMelchior-NOAA , to get that moving), as well as the cam grid2obs plots job (that you are not responsible for checking).  I am running everything at PDYm3.  

I will also submit the stats jobs now.  Your stats tests should include smap, right?  I plan to run the smap, smos, ghrsst, and aviso stats jobs.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : Thanks! stat jobs include SMAP, SMOS, GHRSST and AVISO.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA Since the SMAP data is still missing, you can look right now to see if the output is what you should be expecting.  

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr381test/EVS/dev/drivers/scripts/stats/rtofs/jevs_rtofs_smap_stats.o120530765

**Comment by SamiraArdani-NOAA** [comment]
I did not find any syntax errors for SMAP. The .o file looks good to me.

**Comment by PerryShafran-NOAA** [comment]
Not a huge deal - but you have the warning spelled WARNNG.  Maybe fix the spelling of this?

**Comment by ShelleyMelchior-NOAA** [comment]
> Not a huge deal - but you have the warning spelled WARNNG. Maybe fix the spelling of this?

Good find, Perry. In Samira's previous PR she corrected a typo'd "cpreq". That was a good find, too! 👍

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA The prep job ended quickly.  Please take a look here at the .o file:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr381test/EVS/dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.o120529126

Please look at the data here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs 

One thing that might need to be examined:  I see a lot of WARNINGs of missing data that look like this:

`233 + echo 'WARNING: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs/rtofs.20231202/rtofs_glo_2ds_f024_diag.nc does not exist; cannot create /lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_rtofs_prep.120529126.dbqs01/rtofs.20231202/ghrsst/rtofs_glo_2ds_f024_diag.ghrsst.nc'`

Despite the fact that COMIN is set to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/EVS

Can you look into that?  Is COMIN being used here?

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA OK, to answer the question from above, you are using COMOUTprep for the input prep data, and that remains set to perry.shafran.  Thus, I am setting COMOUTprep to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/prep/rtofs to run this test, which will be a more accurate test.  

@AliciaBentley-NOAA @ShelleyMelchior-NOAA

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA The stats jobs are all finished.  

Please see all the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr381test/EVS/dev/drivers/scripts/stats/rtofs 

And the stats output here:

/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/rtofs

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA Also, please validate the prep script as well, with the logfile and output as listed above.  We are going to ignore those WARNINGs in the prep for now, as we are testing just to ensure that we are free of syntax errors and using the file checking that Lin had requested.  

@ShelleyMelchior-NOAA @AliciaBentley-NOAA

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : I cannot find the stats file for 20231203 in emc.vpppg to check with the results but the number of stat files and the file sizes for each individual data make sense.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA That directory is /lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/rtofs/rtofs.20231203

The small stat files were not transferred over to Dogwood after the switch.  If the number of stat files and sizes make sense, I'm OK for that. 

Main thing is to look in the .o file to see if the change that Lin is asking was done, that we look for the file's existence before we look for size.  Are all those parts OK?  

@AliciaBentley-NOAA @ShelleyMelchior-NOAA

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : I am ok with that too. In addition, I can confirm that the folder rtofs.20231203 in our test is similar to  emc.vpppg and the stats outputs make sense.

**Comment by PerryShafran-NOAA** [comment]
OK, if you can do the prep, we can merge this in tonight.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA :  the .o files for SMAP, SMOS, AVISO and GHRSST look good. No syntax error was found.

**Comment by SamiraArdani-NOAA** [comment]
@PerryShafran-NOAA : I see no syntax error in prep .o file. Sounds good to me.

**Comment by PerryShafran-NOAA** [comment]
@SamiraArdani-NOAA OK, thanks!  I will do a quick code review and then merge.

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Comment by SamiraArdani-NOAA** [comment]
Thank you, @PerryShafran-NOAA , @ShelleyMelchior-NOAA  @AliciaBentley-NOAA

**Pull request merged**
