### PR TITLE
Fixing analyses plots so ceiling height plots in kft

### PR DESCRIPTION
**Pull request by PerryShafran-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

Modified ush script to ensure that the ceiling height threshold output plots in kft, not miles.  

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run the plot job and let me see the output.  The ceiling height plots should have the correct thresholds in kft.  

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

ASAP

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@PerryShafran-NOAA , I have cloned your fork and checked out branch `feature/analyses_plots_fix`.

**Comment by ShelleyMelchior-NOAA** [comment]
The plots job is processing. Please review.
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_analyses_grid2obs_plots.o96162649`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/analyses/atmos.20230905`

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Thanks for starting to address the comments in the document! I see that you have updated SENDCOM = "NO" in this PR. I think it should stay "YES". Can you please confirm this?

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA I don't use it anywhere in the analyses component, but I can set it to YES if that helps.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Yes, please set it to yes for now. Steven Earle said the following about using SENDCOM yesterday, so I think you will have to add in the near future. 

From Steven Earle email:
2) SENDCOM is the boolean test to know whether or not to send data to the com directory structure. This is almost always going to be YES, but it's useful to turn off the send to com when we're doing tests that we just want to stay in the working directory (DATA). **Any copy of data to com should be wrapped in a test for SENDCOM=YES.**

**Comment by PerryShafran-NOAA** [comment]
OK.  In that case I will set SENDCOM=YES and also set up these wrappers in all my components, which I currently don't have.  

Perry

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Please remove FIXevs on L29 of [dev/drivers/scripts/analyses/plots/jevs_analyses_grid2obs_plots.sh](https://github.com/NOAA-EMC/EVS/blob/de168d6d4e6a9ed157eb350b914b906aaada9479/dev/drivers/scripts/analyses/plots/jevs_analyses_grid2obs_plots.sh#L29) if you haven't already done so. Thanks!

**Comment by ShelleyMelchior-NOAA** [comment]
I re-ran after all of the changes in this PR's feature branch. I also ran the plots processing w/ FIXevs removed from the driver script and used a local symbolic link. @PerryShafran-NOAA will still need to update the driver script to officially remove FIXevs.
Please review.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/plots/analyses/atmos.20230910`
logfile: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_analyses_grid2obs_plots.o96534003`

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA - I don't think that stats got a test after I put in the changes for SENDCOM.  I removed FIXevs from the stats and plots driver scripts.  Please re-run all three stats jobs and let me see the results.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Thanks for these edits! Did you intend to change KEEPDATA to "yes" everywhere? For example, [see change here](https://github.com/NOAA-EMC/EVS/commit/428e7b4a0f570c90d91e0c532c7d167b6f573691#diff-d5aeb0484105411aacd419b0307cf7be3c68fec1ed827cdeaffbb4c32d660ed1R30).

**Comment by PerryShafran-NOAA** [comment]
Whoops!  Trying to keep track of the yeses and nos for SENDCOM and KEEPDATA, I must have mistaken these.  I'll fix.

Perry

**Comment by ShelleyMelchior-NOAA** [comment]
@PerryShafran-NOAA , I re-ran the analyses stats processes w/ cyc=04 . Things look good to me. Please review.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/emc.vpppg/evs/v1.0/stats/analyses/atmos.20230911`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_analyses_rtma_*stats.o965825*`

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Please change geoffrey.manikin@noaa.gov to alicia.bentley@noaa.gov in your maillists! Thanks!

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Was removing this file intentional?
[parm/metplus_config/analyses/grid2obs/stats/StatAnalysis_fcstANALYSES_obsNDAS_PrepBufr.conf](https://github.com/NOAA-EMC/EVS/pull/230/files#diff-1f1201c287047367be75eb55d876060551a9e3f46d6b6253eea90c4bba2e0602)

**Comment by PerryShafran-NOAA** [comment]
@AliciaBentley-NOAA yes, removing that file was intentional.  It is not used and it's basically the same file as the StatAnalysis GatherByDay file, with the more proper name of the file.

**Comment by AliciaBentley-NOAA** [comment]
@PerryShafran-NOAA Awesome! Thank you for confirming! Also, in case my second comment bumped it too far up in this thread, please change [geoffrey.manikin@noaa.gov](mailto:geoffrey.manikin@noaa.gov) to [alicia.bentley@noaa.gov](mailto:alicia.bentley@noaa.gov) in your maillists! Those emails are kind of spam to Geoff now. Haha. Thank you!

**Comment by PerryShafran-NOAA** [comment]
@ShelleyMelchior-NOAA - Well, RESTART still works in the output files you specified (though that was not a focus of this PR).  Can you do me a favor?  Clear the stats directory and run again.  I'll need that to see if the SENDCOM stuff worked as expected.

**Comment by ShelleyMelchior-NOAA** [comment]
> d

Sure thing. Yes, I ran the first submission w/o specifying a cycle.

**Comment by ShelleyMelchior-NOAA** [comment]
I re-ran analyses stats processing Please review, @PerryShafran-NOAA .
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/stats/analyses/atmos.20230911`
logfiles: `/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_analyses_*_grid2obs_stats.o9659262*`

**Comment by PerryShafran-NOAA** [comment]
Everything looks good with finding the masks in the fix directory, and I also see the the SENDCOM tests working, and all the 04Z valid stat files in the directories.  I'm pretty satisfied with the analyses stats run.

**Comment by ShelleyMelchior-NOAA** [comment]
Fabulous. Your branch is one commit behind. Please do a sync fork. I also did a quick code review and things look good. I will do the official review and merge after your sync.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
This PR is approved for merge

**Pull request merged**
