### PR TITLE
Fix EVSv1 WAFS issues according to NCO para run

### PR DESCRIPTION
**Pull request by YaliMao-NOAA**
1. Create working directory for each MPMD of WAFS stat job
2. Change COMINuk to DCOMINuk in WAFS jobs

## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**

- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
@YaliMao-NOAA Please also address this comment from Wei in his [EVSv1 Issue's document](https://docs.google.com/document/d/1VYGABeEe2eXA1k5NFL5oavgMgiiTPyTKGWk-zWmsPdc/edit?pli=1):

JEVS_WAFS_ATMOS_STATS:
export COMINgfs=${COMINgfs:-$(compath.py gfs/${gfs_ver})}
→
export COMINgfs=${COMINgfs:-$(compath.py **${envir}/com**/gfs/${gfs_ver})}

CCing @PerryShafran-NOAA and @ShelleyMelchior-NOAA.

**Comment by YaliMao-NOAA** [comment]
> @YaliMao-NOAA Please also address this comment from Wei in his [EVSv1 Issue's document](https://docs.google.com/document/d/1VYGABeEe2eXA1k5NFL5oavgMgiiTPyTKGWk-zWmsPdc/edit?pli=1):
> 
> JEVS_WAFS_ATMOS_STATS: export COMINgfs=${COMINgfs:-$(compath.py gfs/${gfs_ver})} → export COMINgfs=${COMINgfs:-$(compath.py **${envir}/com**/gfs/${gfs_ver})}
> 
> CCing @PerryShafran-NOAA and @ShelleyMelchior-NOAA.
Sure. Just added it to this PR.

**Comment by PerryShafran-NOAA** [comment]
@YaliMao-NOAA I am starting work on this PR now.

**Comment by PerryShafran-NOAA** [comment]
@YaliMao-NOAA @AliciaBentley-NOAA @ShelleyMelchior-NOAA I have finished your wafs stats job.  I do have a question (and Alicia and/or Shelley can help answer this).

I noticed that you do have a working directory for each mpmd process, as requested.  But you are recycling the DATA directory variable, and I'm wondering if it needs to be something else.

DATA is defined at the start of the job as:

`export DATA=/lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_wafs_stats.123578308.dbqs01`

Which is correct.  But then you use the DATA variable name for each process subdirectory:

```
export DATA=/lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_wafs_stats.123578308.dbqs01/GCIP.0P25.us
export DATA=/lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_wafs_stats.123578308.dbqs01/GCIP.0P25.blend
export DATA=/lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_wafs_stats.123578308.dbqs01/GCIP.0P25.uk
export DATA=/lfs/h2/emc/stmp/perry.shafran/evs_test/prod/tmp/jevs_wafs_stats.123578308.dbqs01/GFS.1P25.gfs
etc
```

I suspect that NCO is not going to like this re-defining of the DATA variable for each process subdirectory.  Is it possible to have a different directory name for each process (i.e., DATAgfs, DATAgcipus, DATAgcipblend, DATAgcipuk)?  That way DATA remains defined as the main working directory for the entire process.  

Thanks!

**Comment by PerryShafran-NOAA** [comment]
@YaliMao-NOAA Thank you for updating!  (And also for syncing your fork.)  I think using DATAmpmd should be fine.  

Please take a look at the .o file here:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/pr407test/EVS/dev/drivers/scripts/stats/wafs/jevs_wafs_stats.o112709038

And take a look at the stats output here:
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/wafs/___.20240109

Thanks!

@ShelleyMelchior-NOAA @AliciaBentley-NOAA

**Comment by YaliMao-NOAA** [comment]
@PerryShafran-NOAA 
The log file looks good to me. With the script updates, the output is the same as the parallel, as expected.
/lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/wafs/wafs.20240109
/lfs/h1/ops/para/com/evs/v1.0/stats/wafs/wafs.20240109
So good to go.

**Comment by AliciaBentley-NOAA** [comment]
I have looked over the changes made in this PR and think that they look good! I approve for merging when @PerryShafran-NOAA is ready. Thank you, @YaliMao-NOAA!

**Review by PerryShafran-NOAA — APPROVED** [review]
Code works as expected.  Approved for merge.

**Pull request merged**
