### PR TITLE
feature/global_ens_atmos_prep_COMINs

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

- Point global_ens atmos prep to NAEFSv7 being run by NCO.
- Fix small typo

- [ ] Describe testing already performed for this Pull Request:</br>

jevs_global_ens_atmos_prep.sh is currently running, but I am seeing cmce files populating in /lfs/h2/emc/stmp/mallory.row/evs/v1.0/prep/global_ens/atmos.20230913/cmce and the emc.vpppg parallel was failing to find thos files this morning.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run all the global_ens atmos prep scripts. I will be out this afternoon but deffering to @StevenSimon-NOAA on approving the output.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **No**

- [ ] Do these updates/additions include sufficient testing updates? **No**

- [ ] Please complete this pull request review by **10/13/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow Thanks for submitting this! Quick question (understanding that you are out the rest of today): Are the 31 GEFS bias-corrected members being produced by the NAEFSv7 NCO parallel yet? If so, I think that we can point to the NCO parallel for everything that is NAEFSv7 related (including the COMINgefs_bc path) and not point to Bo's parallel! 

That said, I support merging this PR sooner rather than later to fix what is broken and potentially address this when Mallory returns. Thanks!

**Comment by StevenSimon-NOAA** [comment]
> @malloryprow Thanks for submitting this! Quick question (understanding that you are out the rest of today): Are the 31 GEFS bias-corrected members being produced by the NAEFSv7 NCO parallel yet? If so, I think that we can point to the NCO parallel for everything that is NAEFSv7 related (including the COMINgefs_bc path) and not point to Bo's parallel!
> 
> That said, I support merging this PR sooner rather than later to fix what is broken and potentially address this when Mallory returns. Thanks!

For clarification, can you please confirm the definition of the NAEFSv7 NCO parallel?

**Comment by AliciaBentley-NOAA** [comment]
@StevenSimon-NOAA NCO is starting to spin up a /para version of NAEFSv7 that they will eventually move into /prod. The parallel version can be found here: /lfs/h1/ops/**para**/com/naefs/

**Comment by ShelleyMelchior-NOAA** [comment]
I have submitted all 4 prep jobs for good  measure. I will update w/ results.

**Comment by ShelleyMelchior-NOAA** [comment]
headline and naefs are completed.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_ens/atmos.20230913`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_ens/headline.20230913`

The wave prep job ended w/ a walltime exceedance. Somehow along the way it got set to 15 mins! It needs to revert back to 2 hrs. the pb2nc processing takes a while. I will do the change and push to `feature/global_ens_atmos`. Then I will re-run the wave prep processing.

The global_ens_atmos_prep job is still running.

**Comment by StevenSimon-NOAA** [comment]
The file quantities in /lfs/h2/emc/ptmp/bo.cui/com/naefs/v7.0/naefs.20230913/00 and /lfs/h1/ops/para/com/naefs/v7.0/naefs.20230913/00 match up. I can imagine that the NAEFSv7 NCO parallel generates the 31 GEFS bias-corrected members.

**Comment by AliciaBentley-NOAA** [comment]
@StevenSimon-NOAA I think we're looking for the number of GEFS bias-corrected members to replace these lines in the dev drivers:
export COMINgefs_bc=/lfs/h2/emc/ptmp/bo.cui/com/${MODELNAME}/${naefs_ver}

Try looking in /lfs/h1/ops/para/com/naefs/v7.0/gefs.20230915/00/pgrb2ap5_bc/.  Are there 31 members?

**Comment by StevenSimon-NOAA** [comment]
> /lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_ens/atmos.20230913

The naefs prep file quantities for cmce_bc and gefs_bc (now 30 members) check out. Similarly, the headline prep file quantities for cmce and gefs (now 30 members) also check out.

**Comment by AliciaBentley-NOAA** [comment]
As I said previously, I'm fine merging this in as is, but I might ask for Mallory to do another PR on Monday and point to the NCO parallel for COMINgefs_bc as well. Thanks.

**Comment by StevenSimon-NOAA** [comment]
> @StevenSimon-NOAA I think we're looking for the number of GEFS bias-corrected members to replace these lines in the dev drivers: export COMINgefs_bc=/lfs/h2/emc/ptmp/bo.cui/com/${MODELNAME}/${naefs_ver}
> 
> Try looking in /lfs/h1/ops/para/com/naefs/v7.0/gefs.20230915/00/pgrb2ap5_bc/. Are there 31 members?

The files are formatted as such: gep05.t00z.pgrb2a.0p50_bcf234. I am not sure how to identify the number of ensemble members based off of that. 

Update: I see that gepMM goes out to gep30. I am assuming that indicates 31 members.

**Comment by AliciaBentley-NOAA** [comment]
News flash! I'm an idiot! Everything is fine! Red means that those lines were removed in the [PR change files](https://github.com/NOAA-EMC/EVS/pull/246/files), not added! I'm so sorry for suggesting otherwise! Please consider this a sign that I really need to take a break at some point later today. Sorry, @malloryprow, that I was dumb!

**Comment by ShelleyMelchior-NOAA** [comment]
Ok, more results to share. atmos_prep is still running, but wave is now finished.
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_ens/atmos.20230913`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_ens/headline.20230913`
COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_ens/wave.20230914`

**Comment by StevenSimon-NOAA** [comment]
> Ok, more results to share. atmos_prep is still running, but wave is now finished. COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_ens/atmos.20230913` COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_ens/headline.20230913` COMOUT=`/lfs/h2/emc/vpppg/noscrub/shelley.melchior/evs/v1.0/prep/global_ens/wave.20230914`

The global_ens wave prep file quantities for gefs also check out.

**Comment by ShelleyMelchior-NOAA** [comment]
For monitoring purposes, the log for the global_ens atmos prep job:
`/lfs/h2/emc/ptmp/shelley.melchior/EVS_out/jevs_global_ens_atmos_prep.o81979500`

**Comment by StevenSimon-NOAA** [comment]
All cmce, ecme, gefs, and osi prep files are all in and accounted for.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
All tests of the prep processing performed as expected. This PR is approved for merge.

**Pull request merged**
