### PR TITLE
Feature/subseasonal finalization

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
Some testing (for CFS prep and obs prep steps) has been conducted on the command line.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Multiple edits have been made in this PR, but mostly just to finalize. So the only testing to be done is GEFS prep:
EVS/dev/drivers/scripts/subseasonal/prep/jevs_subseasonal_gefs_prep.sh 
This is to make sure the "SENDCOM == YES" statements that were added to copy data to COMOUT are working properly.
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Hi, @ShannonShields-NOAA ,

Working on your PR now.  Would you want to validate more components?  Your instructions say only to run the prep step, but you probably have SENDCOM for your stats and plots steps too, correct?

Perry

**Comment by ShannonShields-NOAA** [comment]
Hi @PerryShafran-NOAA , yes, I do have the "if SENDCOM == YES" statements for stats and plots, but those have been in the scripts and validated for a long time now. I just realized recently with the Slack message about copying data to COMOUT that this requirement was missing in the prep steps. Hence, why my testing just lists prep. That said, it definitely would be good with my other small clean-up edits to test stats and plots just to make sure.

**Comment by PerryShafran-NOAA** [comment]
Thanks, Shannon!  The gefs prep script is still running; I will let you know when it is complete.

Perry

**Comment by ShannonShields-NOAA** [comment]
Oh man! Sorry @PerryShafran-NOAA , I realized when I was making some further final edits, I forgot to set SENDCOM = YES in the j-job. I'm trying to push this to GitHub, but for some reason it isn't allowing me to do so. When I try to update my feature branch on WCOSS2 with "git pull", it is saying:
**shannon.shields@clogin09: EVS:$git pull
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.**

**Comment by PerryShafran-NOAA** [comment]
My fix usually entails re-cloning your fork, checking out your branch again, and the making those edits.  This happens when you sync fork on the web interface but then don't sync to your local copy - which I do all the time.  I think that makes things clean and is relatively fast and gets you to the point where you can commit new stuff.

**Comment by PerryShafran-NOAA** [comment]
OK then - do I need to restart the prep job?

**Comment by ShannonShields-NOAA** [comment]
Ok, yes, all the changes should now be set for this PR. My apologies for the delay. Please re-run the GEFS prep job after a re-checking out of the branch:
EVS/dev/drivers/scripts/subseasonal/prep/jevs_subseasonal_gefs_prep.sh
At the same time, please run a quick obs prep test too to make sure changes didn't affect anything:
jevs_subseasonal_obs_prep.sh

**Comment by PerryShafran-NOAA** [comment]
Prep jobs are now underway!

**Comment by ShannonShields-NOAA** [comment]
I see that the obs prep job finished successfully and that the GEFS prep is halfway done. To prepare for the stats test, please copy more prep directories into /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/subseasonal/ from /lfs/h2/emc/vpppg/noscrub/shannon.shields/EVS_Data/evs/v1.0/prep/subseasonal. To make sure this is a complete test, please copy back to atmos.20230809.

**Comment by PerryShafran-NOAA** [comment]
When the prep job is done, I will just link the entire subseasonal directory to your directory.  That's the easiest.  Which stats jobs would you like me to do?  All of them?

**Comment by ShannonShields-NOAA** [comment]
Ah, got it. If you would like to test all of the stats jobs to be thorough, you can, but otherwise, running  jevs_subseasonal_gefs_grid2grid_stats.sh and jevs_subseasonal_gefs_grid2obs_stats.sh should cover the changes that have been made.

**Comment by PerryShafran-NOAA** [comment]
Up to you what you want to see tested.  I will just run the gefs jobs then.

**Comment by ShannonShields-NOAA** [comment]
The GEFS prep job has finished running successfully! So yes, for stats, running the listed GEFS jobs will suffice since the jobs run the same way for both models.

**Comment by PerryShafran-NOAA** [comment]
The stats jobs are now underway.

**Comment by ShannonShields-NOAA** [comment]
Just wondering, have you linked the prep directories as we discussed? I'm only seeing atmos.20230913 in /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/subseasonal.

**Comment by PerryShafran-NOAA** [comment]
Yes, it is linked.  Are you sure you are looking at the correct directory?

**Comment by PerryShafran-NOAA** [comment]
`lrwxrwxrwx  1 perry.shafran vpppg    76 May 25 14:53 subseasonal -> /lfs/h2/emc/vpppg/noscrub/shannon.shields/EVS_Data/evs/v1.0/prep/subseasonal`

**Comment by ShannonShields-NOAA** [comment]
Ah yes, never mind.

**Comment by PerryShafran-NOAA** [comment]
OK, the stats processing is complete.

See the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr244test/EVS/dev/drivers/scripts/subseasonal/stats

The final stats files are here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/stats/subseasonal/gefs.20230913

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA The GEFS G2G and G2O stats jobs have successfully completed. For the last test, please run the following:
EVS/dev/drivers/scripts/subseasonal/plots/jevs_subseasonal_grid2grid_pres_lvls_plots_31days.sh
jevs_subseasonal_grid2obs_PrepBufr_plots_31days.sh

**Comment by PerryShafran-NOAA** [comment]
The plots job have completed.

See the .o files here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr244test/EVS/dev/drivers/scripts/subseasonal/plots

and the output plot tarballs here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/plots/subseasonal/atmos.20230913

**Comment by ShannonShields-NOAA** [comment]
All looks good to me! Yay; this last subseasonal PR is ready for merging after your code review.
Thank you so much @PerryShafran-NOAA for all of your assistance testing these PRs; I greatly appreciate it.

**Review by PerryShafran-NOAA — APPROVED** [review]

**Comment by PerryShafran-NOAA** [comment]
Good to go, thanks!

**Pull request merged**
