### PR TITLE
feature/rtofs_cyc_changes

### PR DESCRIPTION
**Pull request by malloryprow**
## Pull Request Testing ##

1. Change "cyc" to "vhr"; set "cycle" default to "t${vhr}z"
2. I found no instances of "CYC" being used by rtofs

- [ ] Describe testing already performed for this Pull Request:</br>
> I compared the file counts for the prep step to the emc.vpppg parallel.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
**Set-up**
> 1. Clone my fork and checkout branch feature/rtofs_cyc_changes
> 2. cd sorc; ./build-fix-link.sh

**prep**
> 3. Run dev/drivers/scripts/prep/rtofs/jevs_rtofs_prep.sh

**stats**
> 4. Run dev/drivers/scripts/stats/rtofs/jevs_rtofs_argo_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_aviso_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_ghrsst_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_ndbc_stats.sh, dev/drivers/scripts/stats/rtofs/jevs_rtofs_osisaf_stats.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vppg/$NET/${evs_ver}.

> Note: I haven't added dev/drivers/scripts/stats/rtofs/jevs_rtofs_smap_stats.sh and dev/drivers/scripts/stats/rtofs/jevs_rtofs_smos_stats.sh to the list of jobs to run since there are issues with these datasets recently. If the data in prod/dcom is looking better when it comes time to test the PR we can run them too.

**plots**
> 5. Run dev/drivers/scripts/plots/rtofs/jevs_rtofs_argo_grid2obs_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_aviso_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_ghrsst_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_headline_grid2grid_last90days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_ndbc_grid2obs_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_osisaf_grid2grid_last60days_plots.sh, dev/drivers/scripts/plots/rtofs/jevs_rtofs_smap_grid2grid_last60days_plots.sh, and dev/drivers/scripts/plots/rtofs/jevs_rtofs_smos_grid2grid_last60days_plots.sh. Point COMIN to /lfs/h2/emc/vpppg/noscrub/emc.vpppg/$NET/${evs_ver}.

- [ ] Has the code been checked to ensure that no errors occur during the execution? **Yes**

- [ ] Do these updates/additions include sufficient testing updates? **Yes**

- [ ] Please complete this pull request review by **11/17/2023**.</br>

## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
Starting work on this PR, and the prep step is underway.

**Comment by PerryShafran-NOAA** [comment]
The rtofs prep is finished.  Please have a look:

The .o file is here:  /lfs/h2/emc/vpppg/noscrub/perry.shafran/pr301test/EVS/dev/drivers/scripts/prep/rtofs

and the output is here: /lfs/h2/emc/vpppg/noscrub/perry.shafran/evs/v1.0/prep/rtofs (output in several directories)

I'm going to run the stats jobs for VDATE=PDYm3.  I know that there have been issues with some of the observations, but I'll try them anyway.

**Comment by PerryShafran-NOAA** [comment]
Not surprisingly, there are no smap or smos stats output due to the recent dataflow problems.  Interestingly there *is* a ghrsst stat file; I guess that particular observation file was fixed?  argo and ndbc still running; there are also aviso and osisaf stats files. 

Do you want me to try an earlier date to try to get smap and smos output?

**Comment by malloryprow** [comment]
:heavy_check_mark: **prep and stats are good!**

Yeah, I think that Dataflow was able to backfill the GHRSST data so that is why we have stats for that one for 20231014. If you would like to run for another VDATE with SMAP and SMOS data that would be 20231010.

**Comment by PerryShafran-NOAA** [comment]
OK, re-running the SMAP and the SMOS with VDATE=20231010.  Those are generally fast, so we'll know pretty soon.

**Comment by malloryprow** [comment]
They are done already and everything looks good with them!

**Comment by PerryShafran-NOAA** [comment]
Excellent!  Let me work on the plots then!

**Comment by AliciaBentley-NOAA** [comment]
@malloryprow @PerryShafran-NOAA I have looked over this PR and have no additional comments. When you are both satisfied with plots, I think this can be merged!

**Comment by malloryprow** [comment]
:heavy_check_mark: **plots are good!**

**Comment by PerryShafran-NOAA** [comment]
Excellent!  Let me do a quick code review and then merge this PR.  Thanks for all your hard and quick work!

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Pull request merged**
