### PR TITLE
Bugfix/subseasonal Fix tarname in dbn alert

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
## Pull Request Testing ##

- [ ] Describe testing already performed for this Pull Request:</br>
Testing done on command line to fix tarname in SENDDBN section
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Checkout branch and adjust paths accordingly
Link stat files from parallel
Run all grid2grid jobs under dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid*.sh
- [ ] Has the code been checked to ensure that no errors occur during the execution? **[Yes or No]**
Yes
- [ ] Do these updates/additions include sufficient testing updates? **[Yes or No]**
Yes
- [ ] Please complete this pull request review by **[Fill in date]**.</br>
ASAP
## Pull Request Checklist ##

- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR description above.
- [ ] Ensure the PR title matches the feature branch name.
- [ ] Check the following:
- [ ]  Instructions provided on how to run
- [ ]  Developer's name is replaced by ${user} where necessary throughout the code
- [ ]  Check that the ecf file has all the proper definitions of variables
- [ ]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [ ]  Check to see that the output directory structure is followed
- [ ]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue.

### CODE REVIEW

**Comment by PerryShafran-NOAA** [comment]
@ShannonShields-NOAA Testing is now underway.

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA Did you set "export SENDDBN=YES" in the dev/drivers?

**Comment by PerryShafran-NOAA** [comment]
Actually, I did not!  I'll have to re-run.

**Comment by ShannonShields-NOAA** [comment]
Sorry about that; I should not have assumed that was a given assumption.

**Comment by PerryShafran-NOAA** [comment]
Re-runs underway!

**Comment by ShannonShields-NOAA** [comment]
@PerryShafran-NOAA I went through all of the job output files and confirmed the tar name is now correct in the SENDDBN section and completes err_chk cleanly:
64 + '[' YES = YES ']'
64 + tarname=evs.plots.subseasonal.atmos.grid2grid_sst.last90days.v20231202.tar
64 + /apps/ops/prod/nco/core/prod_util.v2.0.13/fakedbn/bin/dbn_alert MODEL EVS_RZDM jevs_subseasonal_grid2grid_sst_plots_90days /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/subseasonal/atmos.20231202/evs.plots.subseasonal.atmos.grid2grid_sst.last90days.v20231202.tar
FAKE dbn_alert MODEL EVS_RZDM jevs_subseasonal_grid2grid_sst_plots_90days /lfs/h2/emc/ptmp/perry.shafran/evs/v1.0/plots/subseasonal/atmos.20231202/evs.plots.subseasonal.atmos.grid2grid_sst.last90days.v20231202.tar
64 + export err=0
64 + err=0
64 + err_chk
  completed cleanly
I also confirmed the existence of tar files in COMOUT ptmp space. This PR should be set for merging upon your approval.

**Comment by PerryShafran-NOAA** [comment]
Great to hear!  Would you please do a sync fork so we are up to date?

Thanks!

Perry

**Comment by ShannonShields-NOAA** [comment]
I just confirmed that this fork is up-to-date.

**Comment by PerryShafran-NOAA** [comment]
Oh, you must have submitted after the previous PR was merged, so that is why you are up to date.

Thanks!

Perry

**Review by PerryShafran-NOAA — APPROVED** [review]
Approved for merge.

**Pull request merged**
