### PR TITLE
Update narre j-job, module files, ex-script modified to work with ecflow workflow

### PR DESCRIPTION
**Pull request by lgannoaa**
GitHub #180 

Tested in development ecflow workflow. Result checked by team member.
Add missing J-Job JEVS_NARRE_PLOTS.
Fix DATA location assignment syntax for J-Job JEVS_NARRE_STATS.
Rename module file because the model name is indicated in directory assignment.
Module prod_envir should not be loaded in module file. It should load before calling J-Job. Because loading this module will reset some necessary environment setting established from the top level of the workflow.
Take care of local met_v usage within exevs_narre_plots.sh script.

- [Yes] Has the code been checked to ensure that no errors occur during the execution?

## Pull Request Checklist ##

- [X] Complete the PR description above.
- [X] Ensure the PR title matches the feature branch name.
- [X]  Check that the jobs file has all the proper settings of COMIN and COMOUT and other input variables
- [X]  Check to see that the output directory structure is followed
- [X]  Be sure that you are not using MET utilities outside the METplus wrapper structure

- [X] After submitting the PR, select **Development** issue with the original issue number.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@lgannoaa , please update branch `feature/evs-180` with the auth EVS develop.

**Comment by lgannoaa** [comment]
@ShelleyMelchior-NOAA , merged upstream.

**Comment by ShelleyMelchior-NOAA** [comment]
@lgannoaa  tests of this PR look as expected. Please update your branch w/ auth EVS develop and then I can approve for merge.

**Comment by lgannoaa** [comment]
@ShelleyMelchior-NOAA merged upstream.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Code changes are clear and tests return expected results. This PR is approved for merge.

**Pull request merged**
